### ISSUE TITLE
Main scene fails to load for exported projects

### ISSUE THREAD

**Issue by levidavidmurray** [godotengine/godot#100084]
### Tested versions

- Reproducible on master

### System information

Godot v4.4.dev.mono (eb5103093) - Windows 10.0.22631 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 2700X Eight-Core Processor (16 threads)

### Issue description

I was getting the following error when launching an exported project in `4.4dev5`, which instantly crashes the application:
```
ERROR: No loader found for resource: res://uid:/cu2wmlv7867bo (expected type: )
   at: ResourceLoader::_load (core\io\resource_loader.cpp:327)
ERROR: Failed loading scene: res://uid:/cu2wmlv7867bo.
   at: Main::start (main\main.cpp:4214)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: ObjectDB::cleanup (core\object\object.cpp:2342)
```

---

### Issue 1
Changing resource values such as `application/run/main_scene` or `application/boot_splash/image` in Project Settings results in an automatic conversion from their `res://` paths to their `uid://` paths (this is the value that's stored in `project.godot`)

### Issue 2
The bit of code that determines the main scene path doesn't appear to be expecting a `uid://` path. I've tracked down the code that results in `res://uid:/cu2wmlv7867bo` to [main.cpp:4161](https://github.com/godotengine/godot/blob/master/main/main.cpp#L4161).

---

I'm not exactly sure if this code should handle the `uid://` path, or if these resource paths saved under `project.godot` should be reverted back to their `res://` paths.

In any case, manually hardcoding the paths to their `res://` paths in `project.godot` has temporarily fixed the issue for me.

### Note
I actually don't remember if this was the exact issue I was facing when building on 4.4dev5. This is an issue on latest master that I ran into after having similar issues on 4.4dev5. I built latest master because I thought this very similar issue (https://github.com/godotengine/godot/issues/99151) might've been fixed.

### Steps to reproduce

1. Create a project in 4.4dev5
2. Export that project
3. Run the project

### Minimal reproduction project (MRP)

N/A

**Comment by IsaacMarovitz** [comment]
I also started experiencing this issue in `dev5`, which persists in `dev6`. Seen reports from several others in the Godot Discord also.

**Comment by IsaacMarovitz** [comment]
In my testing, it didn't occur with a project created in `dev5`, so this seems to be an issue with projects created in `dev4` or earlier and upgraded to `dev5` or newer.

**Comment by IsaacMarovitz** [comment]
I managed to work around this by manually editing `project.godot` to use a `res://` path.

**Comment by IsaacMarovitz** [comment]
FWIW, this should absolutely be included in the release blockers list

**Comment by CSLRDoesntGameDev** [comment]
i've come across the same issue, and the `project.godot` did fix it.

**Comment by akien-mga** [comment]
Fixed by #100408.

**Comment by lucasmaffazioli** [comment]
I'm running `v4.4.1.stable.official [49a5bc7b6]` on MacOs, and the problem persists on web exports. The main scene is still saved as `uid`, and changing it to res works. But the issue happens only with Web Export, export to Macos go fine with `uid`

**Comment by Calinou** [comment]
@lucasmaffazioli Please open a new issue with a minimal reproduction project attached.
