### ISSUE TITLE
glTF importer fails to import models with armatures

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#10130]
[makehuman.zip](https://github.com/godotengine/godot/files/1203715/makehuman.zip)
Exporting the attached (makehuman-generated) blend file using khronos gltf 2.0 exporter & trying to import it in godot results in following errors:

```
ERROR: instance_remove_skeleton: Condition ' !skeleton ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5728.
ERROR: instance_remove_skeleton: Condition ' !skeleton ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5728.
ERROR: instance_remove_skeleton: Condition ' !skeleton ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5728.
ERROR: instance_remove_skeleton: Condition ' !skeleton ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5728.
ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:1016.
ERROR: load: Failed loading resource: res://.import/makehuman.gltf-381f200aad9d187d7a1548869e4bc450.scn
   At: core/io/resource_loader.cpp:223.
ERROR: load: Failed loading resource: res://models/makehuman/makehuman.gltf
   At: core/io/resource_loader.cpp:223
```

(using current master)

**Comment by BrainBlasted** [comment]
Seems to be a regression, since I was using it fine the other day. Tested with your character and my own mesh. The mesh I created the other day properly imported, yet one made today didn't. Re-exported the first mesh I used, and Godot crashed on import. This suggest an issue with the exporter, but I have not updated the exporter since testing it the other day. A change in this repo seems to have broken compatibility.

**Comment by BrainBlasted** [comment]
Alright, after some testing it seems part of it is that Godot does not handle exporting glTF files with the camera. Opening a new issue for that. I can't seem to figure out what's up with your mesh.

**Comment by BrainBlasted** [comment]
Alright, after some testing of #10291, I'm beginning to think this is an issue with how armatures are imported. After deleting the armature, their mesh imported properly.

**Comment by kubecz3k** [comment]
related issue #10176

**Comment by pcvonz** [comment]
Maybe related: The attached model crashes Godot when imported. After removing the armatures the model imports fine.  
[legs.zip](https://github.com/godotengine/godot/files/1220007/legs.zip)

**Comment by reduz** [comment]
I'm busy with older issues at the moment, so anyone that wants to give it a shot feel welcome

**Comment by djrm** [comment]
@tagcup, @pcvonz why dont you post the glTFs instead of blend files?

**Comment by tagcup** [comment]
I'm away from my desktop computer but you can generate those with blender; also I'm pretty sure reduz has the gltf2 exporter installed.

**Comment by n-pigeon** [comment]
There is other Blender GLTF exporter that is developed by actual Blender contributors:
https://github.com/Kupoman/blendergltf

It might work better, any test are welcome because this one is likely to be official blender GLTF addon.

**Comment by tagcup** [comment]
That one seems to be a gltf 1.0 exporter though

**Comment by n-pigeon** [comment]
@tagcup They are working on GLTF 2.0

**Comment by BrainBlasted** [comment]
I've tried it, and it seems to have a lot of issues exporting glTF 2.0 for
me. The Khronos one works fine for the most part. Not sure of this is
caused by something in Godot or the Khronos Exporter. Anyone know other
Linux 3D software with glTF support?

**Comment by reduz** [comment]
I fixed a bug preventing export, but truth is that the exported glTF files are really broken, they all have alpha transparency at 0 so meshes are not visible... I suspect the exporter is kinda broken..

**Comment by tagcup** [comment]
Can we repoen this? I just tried with the most recent version of the export, and it's still crashing the latest godot. Here's the backtrace

```
ERROR: operator[]: FATAL: Index p_index out of size (size()).
   At: core/vector.h:137.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x34920) [0x7f0cd42b2920] (??:0)
[2] EditorSceneImporterGLTF::_generate_bone(EditorSceneImporterGLTF::GLTFState&, int, Vector<Skeleton*>&, int) (??:0)
[3] EditorSceneImporterGLTF::_generate_node(EditorSceneImporterGLTF::GLTFState&, int, Node*, Node*, Vector<Skeleton*>&) (??:0)
[4] EditorSceneImporterGLTF::_generate_scene(EditorSceneImporterGLTF::GLTFState&, int) (??:0)
[5] EditorSceneImporterGLTF::import_scene(String const&, unsigned int, int, List<String, DefaultAllocator>*, Error*) (??:0)
[6] ResourceImporterScene::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*) (??:0)
[7] EditorFileSystem::_reimport_file(String const&) (??:0)
[8] EditorFileSystem::reimport_files(Vector<String> const&) (??:0)
[9] EditorFileSystem::_update_scan_actions() (??:0)
[10] EditorFileSystem::_notification(int) (??:0)
[11] EditorFileSystem::_notificationv(int, bool) (??:0)
[12] Object::notification(int, bool) (??:0)
[13] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[14] SceneTree::idle(float) (??:0)
[15] Main::iteration() (??:0)
[16] OS_X11::run() (??:0)
[17] godot.x11.opt.tools.64.llvm(main+0x90) [0x55f595245fb0] (??:0)
[18] /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f0cd429ef6a] (??:0)
[19] godot.x11.opt.tools.64.llvm(_start+0x2a) [0x55f595245e3a] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)
```

**Comment by akien-mga** [comment]
It would be better to open a new issue, the initial one was about errors when importing and was fixed, the new one is about a crash when importing and needs a different fix.

**Comment by tagcup** [comment]
Actually it was crashing from the beginning, the difference is I only copy-pasted the backtrace part this time which is recently added.
