### ISSUE TITLE
Duplicating a folder messes up script UIDs

### ISSUE THREAD

**Issue by GuyUnger** [godotengine/godot#101433]
### Tested versions

 v4.4.dev7.official [46c8f8c5c]

### System information

Windows 11

### Issue description

Duplicating a folder duplicates script UID's and its almost impossible to fix because even if i delete the UID file, remove the UID in the tscn file, reload the editor etc. it somehow finds a way to still keep attaching the wrong script (the one its copied from). I duplicate folders all the time to make new enemies and this version is just completely unusable because of this

### Steps to reproduce

duplicate a folder with a script

### Minimal reproduction project (MRP)

just duplicate a folder

**Comment by AThousandShips** [comment]
By "duplicating" do you mean duplicating *in* the editor or *out* of the editor? If it is out of the editor this is already solved in:
* https://github.com/godotengine/godot/pull/100927

**Comment by GuyUnger** [comment]
> By "duplicating" do you mean duplicating _in_ the editor or _out_ of the editor? If it is out of the editor this is already solved in:
> 
> * [Assign new UID when duplicating file externally #100927](https://github.com/godotengine/godot/pull/100927)

in the latest dev snapshot either editor or file explorer but if its solved in editor for next snapshot that's great 👍

**Comment by AThousandShips** [comment]
Then that's solved in that PR, closing, if it persists in the next snapshot please comment here again

**Comment by GuyUnger** [comment]
This still happens in the new beta snapshot (v4.4.beta1.official [d33da79d3])
