### ISSUE TITLE
Editing an exported array of type Resource, will not update in a running debug instance.

### ISSUE THREAD

**Issue by ryanrom5** [godotengine/godot#101979]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6094) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

If I try to edit an exported Array[Resource] inside the editor while a debug instance is running, the array will not update in the running instance. 

If I edit exported ints, floats, bools, Strings and more; it will update in the running debug instance, allowing me to test game state. For example: reducing the player's health to see HUD updates and character animations/display. I expected this functionality would work with Arrays filled with objects but it does not. I would like to add items to a player inventory, quests to a quest log, status effects and state to a player character and have it update in the running instance.

Additionally, (and I don't know if this is related), but non-typed arrays can be edited; however if they are, all Resources inside the array are changed to an "EncodedObjectAsID" which breaks Resources used as constant types. I'm not sure if this is intended, or if I should open another issue. 

### Steps to reproduce

1) Create an exported array with 'Resource' types.
2) Create a timer that prints the array to console every few seconds.
3) Try editing the array, add/remove elements, drag/drop Resource objects from file system; the array will not update as seen in the console window.

### Minimal reproduction project (MRP)

[Godot Array Issue.zip](https://github.com/user-attachments/files/18532843/Godot.Array.Issue.zip)

**Comment by AThousandShips** [comment]
This might have been fixed recently, can you test with [`4.5.beta5`](https://godotengine.org/article/dev-snapshot-godot-4-5-beta-5/)?

**Comment by PatIndermuehle** [comment]
Hello
I have just tested the Minimal reproduction project with the release version 4.5 of Godot and the issue still remains.
I have also noticed the same issue happens when using C#.

**Comment by PatIndermuehle** [comment]
Hello

I would like to help to fix the bug since it affects my personal project too, but I am stuck on finding the issue. 
I have managed to compile the source code and debug the engine. I have looked at the inspector classes but it seems that changing a resource array in the inspector correctly changes the data in the scene file. I suspect the issue is that the game instance does not reload the resource array when it is changed. But I don't know what mechanism the game uses to reload resources.
How exactly does the game know that a Resource was changed? 
	Does it connect to a Signal?
When a scene with a script is instantiated which part loads the exported variables of the script?
	is it the Node class, the script class or something else?

**Comment by PatIndermuehle** [comment]
I have found the issue
In the ScriptEditorDebugger when a resource is changed it sends the "scene:live_node_prop_res" message with the resource path as argument.
In the LiveEditor::_node_set_res_func function it them loads the resource using the path.
When editing a resource array it sends the "scene:live_node_prop" message instead with an array of EncodedObjectAsID as argument, which is then never loaded as a resource. This then causes the value to not be updated in the node.

**Comment by Northrain-cmd** [comment]
I stumbled upon the same problem recently too, it was very frustrating to understand whats wrong, and this definitely needs fixing, would appreciate if anybody could do it
