### ISSUE TITLE
Rendering glitches in 3.0 alpha 1

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#10221]
**Operating system or device - Godot version:**
Win 7 x64 
Godot 3.0 alpha 1

**Issue description:**
Pictures are worth more than a thousand words.

![godot_v3 0-alpha1_win64_2017-08-10_11-20-19](https://user-images.githubusercontent.com/4525388/29164121-ca682ca8-7dbe-11e7-8830-d9776fe5fef6.png)

The only practical difference between the left and right road is the size. Both roads are made of a sequence of quads using the same material. See how one road shows the middle markings (at this zoom level) and the other doesn't. If I zoomed in more, the other one would start showing too.

(The ground is a single quad too, but the bug isn't noticeable on it probably due to its size)

![godot_v3 0-alpha1_win64_2017-08-10_11-19-27](https://user-images.githubusercontent.com/4525388/29164189-f2358b36-7dbe-11e7-80a2-e6567581bc64.jpg)

Same scene, now angled. See how all the markings disappear giving way to a uniform black?

A gfycat because you can see how the angle affects the markings disappearing.
https://gfycat.com/gifs/detail/YellowOldGalapagosdove

The final angles are extremely close to the angle my in-game camera uses.

The issue is present both in editor and in game.

**Steps to reproduce:**

slap a texture with some detail on a mostly uniform background on a quad, zoom and angle camera

**Link to minimal example project:**
If a minimal example is really needed, I believe I could whip one up today or tomorrow.

**Comment by Zylann** [comment]
mipmap issue?

**Comment by Zireael07** [comment]
Checking/unchecking mipmaps on texture used in material doesn't change a thing, it was the first thing I tried.

**Comment by Zireael07** [comment]
I looked at #7164 and in my case, the mipmaps setting doesn't change a thing for video vram mode, but it does for uncompressed (I can import uncompressed with mipmaps on, untick, reimport and see the change, while untick+ reimport fails to do anything observable in video vram mode)

So it is either a rendering problem or a mipmap not getting cleared/setting reset problem.

**Comment by Zireael07** [comment]
Bump.

Still an issue as of alpha 2.

**Comment by NathanWarden** [comment]
Watching your animated Gif it looks more like a shading bug that I've seen a few times. You may want to try putting a much lighter texture on that (solid white?) and see if it turns black at those angles.

**Comment by Zireael07** [comment]
If I untick mipmaps and switch to uncompressed, the issue is gone. So it's definitely related to mipmaps.
As I said above, unticking mipmaps in video vram does nothing at all.

(It's possible there's two bugs at play here, one related to mipmaps unticking not doing anything and the other may be what you say, I will check with a white texture and report)

**Comment by NathanWarden** [comment]
@Zireael07 Thanks for the road texture. It did make it easy to reproduce. Ticking "Anisotropic" filtering on in the import settings seems to get rid of most of it. However, I don't think this is a bug and is intended functionality as this is one of the ways that mip maps work. Here are two screenshots from Unity using the same setup and it has a very similar problem when Anisotropic filtering is turned off.

**Aniso Off (Unity)**
![aniso_off](https://user-images.githubusercontent.com/629422/32517566-cf901edc-c3d4-11e7-9bc4-ce5d51fec603.png)

**Aniso On (Unity)**
![aniso_on](https://user-images.githubusercontent.com/629422/32517582-dd2b003e-c3d4-11e7-8a9d-92ef83b1225e.png)

Here's an excerpt from the Computer Graphics section for Anisotropic filtering on Wikipedia:
"Anisotropic filtering (AF) is a method of enhancing the image quality of textures on surfaces that are **far away and steeply angled** with respect to the point of view."

Hope that helps :)

**Comment by Zireael07** [comment]
I know what mipmaps are. The problem is, if I untick mipmaps and click reimport, that means there should be no mipmapping anymore and the texture should be crispy (as is the case if I do it in uncompressed mode). If I do it in video vram mode, nothing happens.

**Comment by bojidar-bg** [comment]
Possible duplicate of #16079?

**Comment by Zireael07** [comment]
The other way round, my issue is half a year older ;)

**Comment by reduz** [comment]
This may have been fixed recently with the fix to mipmap generation, can you test again?

**Comment by Zireael07** [comment]
Nope, not fixed.

![2018-09-06_15-41-18](https://user-images.githubusercontent.com/4525388/45161368-00494480-b1ec-11e8-8f13-0f8dc48c8c30.gif)

**Comment by akien-mga** [comment]
Quoting @reduz from https://github.com/godotengine/godot/issues/16079#issuecomment-419191231:

> Yeah, GLES2/WebGL does not support compression without mipmaps. I can make the option disappear when VRAM is selected I guess?

**Comment by Zireael07** [comment]
Please make the option disappear, problem will be solved ;)
