### ISSUE TITLE
Deserializing custom resource created through inspector results in parser error

### ISSUE THREAD

**Issue by mihe** [godotengine/godot#102551]
### Tested versions

- Reproducible in: 4.4.beta3
- Not reproducible in: 4.3.stable

### System information

Godot v4.4.beta3 - Windows 11 (build 26100) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6636) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 threads)

### Issue description

When doing `bytes_to_var_with_objects(var_to_bytes_with_objects(some_custom_resource))` where `some_custom_resource` was specifically created through the editor inspector, and not through something like `MyResource.new()`, you end up with a debugger break saying:

```
Parser Error: Class "MyResource" hides a global script class.
```

The exact same setup seemingly worked in 4.3-stable.

### Steps to reproduce

1. Open the MRP.
2. Run the main scene.
3. Note error.

### Minimal reproduction project (MRP)

[resource-serialization-error.zip](https://github.com/user-attachments/files/18710656/resource-serialization-error.zip)

**Comment by AThousandShips** [comment]
Can confirm, but happens for me in 4.3.stable and even in 4.2.2.stable, at least in my testing using the MRP

**Comment by mihe** [comment]
If you recreate that same setup in 4.3 the error won't show.

It might be related to the `metadata/_custom_type_script` property added to the `sub_resource` as of 4.4.

I was planning on providing a 4.3-stable MRP instead, but there's some other strange issue happening in the upgrade process (that I need to report as well) which forced me to provide a 4.4 repro instead.

**Comment by AThousandShips** [comment]
That makes sense when clarified!

**Comment by mihe** [comment]
I just realized I could have just provided two MRPs in the first place, so here's one for 4.3, with no error: [resource-serialization-error-4.3.zip](https://github.com/user-attachments/files/18711303/resource-serialization-error-4.3.zip)

**Comment by AThousandShips** [comment]
Will bisect now that I know the span

**Comment by AThousandShips** [comment]
Bisected to:
* https://github.com/godotengine/godot/pull/91341

CC @bjornmp @KoBeWi 

Change was to close:
* https://github.com/godotengine/godot/issues/37479
* https://github.com/godotengine/godot-proposals/issues/7905

---

Related issue:
* https://github.com/godotengine/godot/issues/100154

Which was supposed to be solved by:
* https://github.com/godotengine/godot/pull/101001

**Comment by KoBeWi** [comment]
`bytes_to_var_with_objects` will for some reason embed resources instead of referencing them. Custom type resources have hidden `_custom_type_script` metadata, which gets duplicated. The same would happen if you export a variable of type Script.

To fix it there needs to be an exception, similar to #100177.
Though a more comprehensive fix would be changing `_custom_type_script` to String. It would fix all duplication problems.

**Comment by KoBeWi** [comment]
So I implemented the quick fix:

[patch.txt](https://github.com/user-attachments/files/18759506/patch.txt)

But then realized `_custom_typed_script` is not supposed to be referenced in core, so I'll go with reworking how the script is saved.

**Comment by ShrigmaDev** [comment]
@KoBeWi Hi, still running into this issue in 4.4 rc1. Tried deleting .godot folder, and the custom resource file itself and then recreating it, and the issue still persists... The project was created in 4.3 stable, is there anything I need to "reset" in order to fix this?

**Comment by KoBeWi** [comment]
It should be gone after you re-save the problematic scene. Check inside tscn if `_custom_type_script` meta is a String.

**Comment by ShrigmaDev** [comment]
> It should be gone after you re-save the problematic scene. Check inside tscn if `_custom_type_script` meta is a String.
@KoBeWi My setup is slightly different but I've managed to create an MRP in #103271. The difference is the resource contains a PackedScene that defines a custom class, but also results in the same error as this one.
