### ISSUE TITLE
"Script modified outside of Godot" window shows up when script was not modified.

### ISSUE THREAD

**Issue by GloriousGlider8** [godotengine/godot#102578]
### Tested versions

Bug happens in 4.4.beta3 and no other Versions that I have tried this on.
I have used:
- 4.4.beta3
- 4.4.beta2
- 4.3
- 4.2

It has not shown up in any version except 4.4.beta3

### System information

Godot v4.4.beta3 - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 threads)

### Issue description

The "Script modified outside of Godot" window shows up when un-focussing and re-focussing the Godot Editor window, even if nothing was changed. The only windows I had open were:
- Godot Editor
- Discord
- Windows Media Player

### Steps to reproduce

- Open a project
- Open a Script in the Editor
- Click on a different window
- Go back to the Editor window
- See the result.

### Minimal reproduction project (MRP)

N/A

**Comment by Jordyfel** [comment]
I cannot reproduce. Does this happen for you on a new project, or is it more specific?

**Comment by AThousandShips** [comment]
Are you sure it occurs specifically in 4.4.beta3? This sounds like this bug which was *fixed* in beta3:
* https://github.com/godotengine/godot/issues/102234

**Comment by etherealxx** [comment]
i got this too when i open two godot 4.4beta3 projects at once. but idk what triggered it first

**Comment by GloriousGlider8** [comment]
> Are you sure it occurs specifically in 4.4.beta3? This sounds like this bug which was _fixed_ in beta3:
> 
> * [Editor wants to reload GDScript files constantly #102234](https://github.com/godotengine/godot/issues/102234)

I am sure. I just updated and then it started happening. I have since switched back to beta2

**Comment by GloriousGlider8** [comment]
> I cannot reproduce. Does this happen for you on a new project, or is it more specific?

It might be to do with me using a project last opened in beta2..?

**Comment by Jordyfel** [comment]
It's possible that one of the already fixed issues created bad editor state. Can you try deleting the `.godot` folder and see if the issue persists?

**Comment by GloriousGlider8** [comment]
> It's possible that one of the already fixed issues created bad editor state. Can you try deleting the `.godot` folder and see if the issue persists?

It's fixed now! Thanks!

**Comment by ProfCJLee** [comment]
Not fixed for me. 
Godot v4.4.beta3 - macOS Sequoia (15.3.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M2 Pro (Apple8) - Apple M2 Pro (12 threads)

**Comment by GloriousGlider8** [comment]
> Not fixed for me. Godot v4.4.beta3 - macOS Sequoia (15.3.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M2 Pro (Apple8) - Apple M2 Pro (12 threads)

Did you delete the `.godot` folder?

**Comment by CatzHoekk** [comment]
This is closed but i wanted to mention that i ran into this on v4.4.stable.official [4c311cbee] today.
I rebooted the system, started godot, ran the project. When i closed it again i got the warning.
Also tabbing out of godot and back in caused it. 

I ended up deleting and recreating the file.
