### ISSUE TITLE
Godot 4.4.beta2 editor freezes at every debugger/remote_scene_tree_refresh_interval when complex remote scene tree is open

### ISSUE THREAD

**Issue by DaZang** [godotengine/godot#102525]
### Tested versions

- Reproducible in v4.4.beta2.official [a013481b0] and v4.4.beta1.official [d33da79d3]
- Not reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.beta2 - Windows 10 (build 19045) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 threads)

### Issue description

When the remote scene tree is open in 4.4.beta1 or 4.4.beta2 when playing a game in editor **with a big scene tree** the whole editor lags every 1.2 seconds (or at every debugger/remote_scene_tree_refresh_interval).
The issue is not present in v4.3.stable.official [77dcf97d8]

Also reproduced on:
- multiple game projects by multiple different people
- different machine: Godot v4.4.beta2 - Windows 11 (build 22631) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce MX450 (NVIDIA; 31.0.15.5274) - 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 threads)
- 2D and 3D
- Forward+ and Compatibility Renderer

### Steps to reproduce

1. Clone https://github.com/lampe-games/godot-open-rts on newest commit on main branch a628ad3bb6a9a903587a181a7ee3300dbf735e81
2. Open project in Godot v4.4.beta2
3. Run Project
4. In game click "Play" then click "Start"
5. In Godot editor open the Remote Scene Tree
6. Open script editor and open a bigger script with scroll bars like "Match.gd"
7. Drag the scroll bars and notice the editor freeze by default every 1.2 seconds (that's the default debugger/remote_scene_tree_refresh_interval in the editor settings)
8. You can also try other editor actions like editing a script or drag the new embedded floating game window to notice the lag

### Minimal reproduction project (MRP)

https://github.com/lampe-games/godot-open-rts 
on newest commit on main branch a628ad3bb6a9a903587a181a7ee3300dbf735e81

**Comment by matheusmdx** [comment]
Im able to reproduce the issue and seems a regression between 4.4 dev 3 and 4.4 dev 4. I'll start the bisect.

**Comment by matheusmdx** [comment]
Bisected to #88427, @CrayolaEater

![Image](https://github.com/user-attachments/assets/ae815021-eb67-4bdd-b3b0-d2d103711998)

**Comment by AeioMuch** [comment]
Duplicate of https://github.com/godotengine/godot/issues/78645

**Comment by akien-mga** [comment]
I believe this was fixed already by #101489 in 4.4.beta3.

Can anyone confirm?

I've tested and I _think_ I could reproduce the issue in 4.4.beta2 and not in 4.4.beta3/master, but the freeze isn't super visible on my setup so it's easy to misjudge.

**Comment by AeioMuch** [comment]
> I believe this was fixed already by [#101489](https://github.com/godotengine/godot/pull/101489) in 4.4.beta3.
> 
> Can anyone confirm?
> 
> I've tested and I _think_ I could reproduce the issue in 4.4.beta2 and not in 4.4.beta3/master, but the freeze isn't super visible on my setup so it's easy to misjudge.

I tested with a debug build, and it is still present.
Also, both this issue and https://github.com/godotengine/godot/issues/98666 point to the same PR (https://github.com/godotengine/godot/pull/88427) as the cause of the regression. Applying https://github.com/godotengine/godot/pull/101435 does help if the remote tree is collapsed; but if you uncollapse everything in the remote tree, the freeze is present again, while without this patch (current master), even with the remote tree collapsed, the freeze is present. So [it ](https://github.com/godotengine/godot/pull/101435) helps, but it is not enough.

**Comment by jaydensipe** [comment]
![Image](https://github.com/user-attachments/assets/7f3d00b7-9c6d-4c62-b856-e8fc8fae6b33)

The main issue now are the TreeItem functions (_namely_ **get_minimum_size**) being repeatedly called for each node. I tried looking into a fix, but I believe the minimum_size dirty flag and variable are reset each time the remote tree is updated (every remote_screne_tree_refresh_interval). If this function is commented out, the issue is around 80% better, with the rest of the slowness coming from how the engine rebuilds each node instead of caching.

**Comment by fire** [comment]
One more reports from rocketchat.

**Comment by bbbscarter** [comment]
I'm also seeing this on Mac in 4.4.1, and in  4.4.2rc - pauses of several seconds every couple of seconds when using the remote viewer on a scene with thousands of nodes. It unfortunately makes the remote inspector very difficult to use.

I've built locally and run some profiling:

- Despite the icon optimisation mentioned above seemingly being in this build, `EditorNode::get_class_icon` is the main issue.
- If I comment out icon retrieval, things are better but still slow, this time via `Tree::_determine_hovered_item`.

I've attached both profiles in case it's useful.

[sample_with_icons.txt](https://github.com/user-attachments/files/20426562/sample_with_icons.txt)
[sample_without_icons.txt](https://github.com/user-attachments/files/20426561/sample_without_icons.txt)

**Comment by AeioMuch** [comment]
@bbbscarter you can try this build with a possible fix https://github.com/godotengine/godot/pull/105376

**Comment by bbbscarter** [comment]
Ah, wonderful! I can confirm that, if I comment out the call get `get_class_icon` as well, this patch almost completely fixes the problem.

**Comment by akien-mga** [comment]
> Despite the icon optimisation mentioned above seemingly being in this build, `EditorNode::get_class_icon` is the main issue.

CC @KoBeWi - we should look into optimizing this further.

If `EditorNode::get_class_icon` itself can't be optimized significantly, we could:
- Cache the results so we only query this once per node in the debugger, and not on every scene tree sync.
- Bypass it if the scene tree has 1000+ nodes or some threshold that makes it a performance issue.

**Comment by KoBeWi** [comment]
I think the main problem is that every refresh rebuilts the whole tree again.

**Comment by KoBeWi** [comment]
I tried disabling icons completely and I don't see any difference.

**Comment by bbbscarter** [comment]
Strange. Was that combined with #105376? (I had to do both to see a perf difference).

**Comment by KoBeWi** [comment]
I don't know, see if it works for you: https://github.com/KoBeWi/godot/commit/c49d8127e8dbb4a7877952101f1a6ec75d9a5372

**Comment by bbbscarter** [comment]
Combined with #105376, this makes a big difference for me. 

In an dev build:
- With ~5k nodes, performance goes 'hard to use', to 'good'.
- At ~25k nodes there is still sluggishness, but it's much better - e.g. pauses of ~300ms vs ~4 seconds.

So with both these changes it's a big improvement for me; but additional improvements will be required for more nodes.

I've attached profiles of both the 5k and 25k scenarios with both of these changes applied.

[with_icon_and_text_fixes_25k.txt](https://github.com/user-attachments/files/20442269/with_icon_and_text_fixes_25k.txt)
[with_icon_and_text_fixes_5k.txt](https://github.com/user-attachments/files/20442270/with_icon_and_text_fixes_5k.txt)

**Comment by bbbscarter** [comment]
Oh, sorry, to clarify - in my before/after timings above at 25k nodes, both had #105376; the only variable was your patch.

I suspect the challenge is that both of the icons and the 'hovered_items' take >2 seconds at 25k nodes, so mitigating only one of them doesn't make a visible difference.

**Comment by akien-mga** [comment]
@bbbscarter Could you test this PR? https://github.com/godotengine/godot/pull/106866

**Comment by bbbscarter** [comment]
@akien-mga - sure!

In my very rough performance test this seems to help as much as @KoBeWi's patch (in combination with #105376). If it also keeps the icons in tact, that's great!

**Comment by akien-mga** [comment]
Fixed by #101489 and #106866.
