### ISSUE TITLE
New embedded game window does not follow tab during drag

### ISSUE THREAD

**Issue by yoont4** [godotengine/godot#102756]
### Tested versions

- Reproducible in v4.4.beta3.official [06acfccf8]

### System information

Godot v4.4.beta3 - Windows 10 (build 19045) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 32.0.15.6636) - AMD Ryzen Threadripper 3970X 32-Core Processor (64 threads)

### Issue description

When dragging the embedded window around, it freezes/stutters as it catches up with the main window. I've attached a video below.

I love the new embedded window feature, but this is one of those little polish things that is really jarring. I'm sure there are complicated platform-specific reasons behind it, but it's strange to see that it only happens in the embedded window, and not other running instances (default windows frames)

https://github.com/user-attachments/assets/ce422af3-42b3-40f7-980d-f885703ae389

### Steps to reproduce

- launch any scene
- drag the embedded window around

### Minimal reproduction project (MRP)

this happens for any project, including an empty project.

**Comment by AThousandShips** [comment]
Thank you for reporting, this was reported in:
* https://github.com/godotengine/godot/issues/102566

And has been solved, the fix will be in beta4

**Comment by yoont4** [comment]
@AThousandShips Just wanted to notify you that I pulled the latest 4.4.stable release, and appear to still get the bug 😢

**Comment by dpiv** [comment]
v4.6.3.stable.official [7d41c59c4] the issue still present
