### ISSUE TITLE
Intermittent editor freezes after upgrading to 4.4

### ISSUE THREAD

**Issue by KingSupernova31** [godotengine/godot#103780]
### Tested versions

Didn't happen in 4.3, started happening to me once I upgraded to 4.4.

### System information

MacOS 10.14.6
AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB

### Issue description

The editor will sometimes "half-freeze", where some things stop working, but others still do. For example, during one of these half-freezes:

* The background highlight that occurs when you hover your mouse over a button stops happening.
* Pressing the "add child node" button doesn't do anything.
* I can still type in the code editor.
* I can still expand and hide dropdown menus in the node inspector.
* But trying to change the value of any of the properties in the inspector doesn't work.
* Clicking and dragging on a node in the scene panel still pops up the little sprite of it to follow the mouse pointer as I drag it elsewhere.
* But releasing it on top of another node doesn't result in the node's position changing in the tree.
* While dragging a node around in the scene panel, the border highlight that normally appears around another node that I've moved the mouse cursor on top of it, or the horizontal line that appears when I'm between nodes, does not appear.

This sometimes solves itself if I wait a few seconds, but usually it does not. What does almost always solve it however is changing the focus to a different, non-Godot window, and then coming back to Godot. (There's only one time that didn't work.)

### Steps to reproduce

It always seems to be triggered by me doing *something*. Usually me adding a child node or changing a property value on an existing node. But I haven't figured out any way to make it happen reliably.

I have tested on a new clean project and it still happens there, so it's not anything specific to the larger project I'm working on.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Could you test the versions between 4.3 stable and 4.4 stable to find when the freezes started? You can download them here: https://godotengine.org/download/archive/

**Comment by KingSupernova31** [comment]
System information shows both AMD Radeon R9 M370X 2 GB and Intel Iris Pro 1536 MB

**Comment by KingSupernova31** [comment]
Looks like it started happening in dev4.

**Comment by KingSupernova31** [comment]
Happens consistently in dev4. In dev3 it still happens but seems less frequent, not sure. Can't get it to happen in dev2.

**Comment by blackthorncyber** [comment]
I've also had this same issue occur on my Mac M4 Mini 16GB RAM - Godot 4.4 Stable. Godot works for a while, then menus become randomly unclickable within the editor itself - usually drop down menus in the inspector, as well as pop up dialogues such as the save dialogue.

I have been unable to reliably reproduce.

I have found that keyboard inputs continue to work - eg navigating the save dialogue once the mouse inputs have begun to stop working.

**Comment by SudoThis913** [comment]
I am also experiencing this freezing issue. After switching focus to any other program, then back to Godot 4.4, the editor is unresponsive for up to 5 seconds. This started after converting project from 4.3 to 4.4.
Program is also unresponsive for several seconds after saving.
Enabled single window mode, disabled v-sync.

12th Gen Intel(R) Core(TM) i9-12900K   3.20 GHz
32.0 GB (31.7 GB usable)
NVIDIA GeForce RTX 4070 SUPER

**Comment by bruvzg** [comment]
> The editor will sometimes "half-freeze", where some things stop working

macOS issue might be related to tooltips and mouse focus handling, should be already fixed by https://github.com/godotengine/godot/pull/104328 (but this is specific to macOS, so not related to freezes on Windows).

**Comment by knightofiam** [comment]
I'm on 4.4.1.stable (macOS Sonoma 14.5) and can confirm that https://github.com/godotengine/godot/pull/104328 did not fix this. Right now most of my editor is clickable, but seemingly at random, various UI elements will freeze. Right now it's the + button to create a new node in the scene tab (and the chain icon next to it to instantiate a child scene), but I still experience this behavior with other areas of the editor occasionally as well. It does seem to be related to window focus.

**Comment by sebbasim** [comment]
Same for me. I am on 4.4.1 stable. The "play scene" button and dropdowns are not clickable.

**Comment by noahwagner04** [comment]
This bug also happens to me on 4.4.1 stable. - MacBook Pro M2, MacOS Sonoma

**Comment by LanceLiang2011** [comment]
This bug also happens to me on 4.4.1 stable, MacBook Pro M4, Sequoia

**Comment by u1967076** [comment]
I found a workaround for those how don't want to dowgrade the project back to 4.3. I found that if you change to "Single Window Mode" to On in "Editor Settings" all works as expected 🥳!

**Comment by Calinou** [comment]
I can't reproduce this on 4.4.1.stable on macOS. I've tried adding nodes using the + button over 10 times, as well as changing inspector properties of various times and couldn't get the bug to occur a single time. Single Window Mode is disabled in the editor settings (the default).

<details open>
<summary>Mac specifications</summary>

- MacBook Pro 16 2024
- **SoC:** M4 Max 16-core CPU, 40-core GPU
- **RAM:** 48 GB
- **SSD:** 1 TB
- **OS:** macOS 15.5
</details>

**Comment by GarlandKey** [comment]
Is this a duplicate of #105688 ?

**Comment by KingSupernova31** [comment]
...No? The issue descriptions are totally different.

**Comment by Calinou** [comment]
I just managed to reproduce this on the same system as above on 4.4.1.stable. What I did was to move a 3D scene file (glTF) with an import error to the project folder, fix the import error somehow while the editor is unfocused, then focus back to the editor. I can still click to select nodes but can't use any dropdowns. Restarting the editor fixes the issue for now.

**Comment by clayjohn** [comment]
@Calinou Can you run the same test with a debugger and then dump the stack trace when things are stuck?

**Comment by Calinou** [comment]
> [@Calinou](https://github.com/Calinou) Can you run the same test with a debugger and then dump the stack trace when things are stuck?

I've tried to reproduce the issue by following the exact same steps, but I can't get it to happen anymore on either 4.4.1.stable or `master` 🙁 

While trying to reproduce it, I got a crash but it's unrelated: https://github.com/godotengine/godot/issues/108712

For other people who can reproduce this issue, please try the following:

- [Compile the `master` branch of Godot for macOS](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_macos.html).
- While in the Godot repository root, open a terminal and run `lldb bin/godot.macos.editor.arm64` (change this to follow the actual binary name if you've used specific SCons options that change it).
- Enter the administrator password at the prompt, as lldb needs some elevated permissions to work.
- Once you see `(lldb)`, enter this command: `run /path/to/project.godot` where `/path/to/project.godot` is the absolute path to your Godot project file (you can use `~` to refer to your home folder as a shortcut).
- Run the editor until you run into the freezing issue.
- Switch back to the terminal and press <kbd>Ctrl + C</kbd> (not <kbd>Cmd + C</kbd>). This will pause project execution, so the editor will appear frozen, but you'll see the `(lldb)` command line appear again. Enter `bt` in the lldb command line.
- Post the backtrace here.
- To resume execution, enter `c` in the lldb command line. I suggest taking a screenshot after resuming execution and attaching it here to add some context. Ideally, you could also record a video of the entire session to see what exactly caused the issue to start occurring (OBS can be used for this).

**Comment by stuartcarnie** [comment]
Another easy macOS trick is to open the Activity Monitor and when it freezes, select the Godot process and then click **Sample Process**. Drop the spin dump here.

**Comment by Alex2782** [comment]
> The editor will sometimes "half-freeze", where some things stop working, but others still do. 

I was able to observe these issues in the past as well (on MacMini M1), but I haven't noticed it in `Godot 4.5`. Perhaps it's been fixed now.

Can you still reproduce it in Godot version `4.5 beta 3`?
@KingSupernova31 @u1967076 @sebbasim @noahwagner04 @LanceLiang2011 

with `interface/editor/single_window_mode` = `disabled`

https://godotengine.org/download/archive/


---------


<details><summary>video Godot 4.4.1</summary>

https://github.com/user-attachments/assets/d9032ca5-ea6d-4c6b-999c-a328ee172f32

</details>

Here's a video showing how to reliably reproduce it in 4.4 and 4.4.1. Use the mouse to focus (hover) on the system buttons in the top left corner of the window. After that, the "Godot buttons" suddenly stop working in the Project Manager. It's also reproducible in the editor, but not for all input elements at once. 

---------

> I found that if you change to "Single Window Mode" to On in "Editor Settings" all works as expected 🥳!

As soon as I activate `interface/editor/single_window_mode` this bug as shown in the video is no longer reproducible in Godot 4.4.1

**Comment by Alex2782** [comment]
<details><summary>10s video</summary>

https://github.com/user-attachments/assets/d9032ca5-ea6d-4c6b-999c-a328ee172f32

</details>



**reproducible up to:** v4.5.dev3.official [28089c40c]
**fixed in:** v4.5.dev4.official [209a446e3]


https://godotengine.github.io/godot-interactive-changelog/#4.5-dev4

maybe a commit from `Input`

> Input
> - Fix FOCUS_ACCESSIBILITY grabbing focus when it is not supposed to, forward GraphNode key input to GraphEdit ([GH-105595](https://github.com/godotengine/godot/pull/105595)).
> - macOS: Update entered state from mouseMoved ([GH-105822](https://github.com/godotengine/godot/pull/105822)).
> - macOS: Embedded window support ([GH-105884](https://github.com/godotengine/godot/pull/105884)).
> - Fix issues with Android controller input handling ([GH-105992](https://github.com/godotengine/godot/pull/105992)).
> - Fix added missing shortcuts from tree to file list ([GH-105997](https://github.com/godotengine/godot/pull/105997)).
> - macOS: Process first click event without requiring focus ([GH-106317](https://github.com/godotengine/godot/pull/106317)).
>

**Comment by Repiteo** [comment]
I'll mark this as completed for now; feel free to reopen if the issue persists
