### ISSUE TITLE
Visual script Call/Set - Basic type does not have a flow node!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#10440]
WIN 10 , nvidia 960m godot 3.0
![screenshot 80](https://user-images.githubusercontent.com/13883739/29485826-a0a195a0-84f6-11e7-975b-3323a5268342.png)

whenever i call from a variable in the output shows this Output error : 
core\class_db.cpp:274 - Condition ' !ti ' is true. returned: StringName()

can't see a logical way to connect for executing the function! 

step to reproduce - just make a variable here i have created array and call a function through it, any function!

**Comment by gamergamesz** [comment]
any update on this or am i doing it in a wrong way. but i am pretty sure that set basic type should also have dlow control and i also say UE having flow control on append

**Comment by gamergamesz** [comment]
Custom node and Deconstruct node also seems problematic to me

**Comment by gamergamesz** [comment]
![append-array-node](https://user-images.githubusercontent.com/13883739/30391613-b54bed9e-98d7-11e7-8e13-290da06a8853.png)
![screenshot 105](https://user-images.githubusercontent.com/13883739/30391848-85bd0dd2-98d8-11e7-878a-1107e9f668cf.png)

**Comment by bojidar-bg** [comment]
Can confirm, should work like normal call (which gets sequence ports when the method is non-const)

**Comment by reduz** [comment]
I don't understand

**Comment by bojidar-bg** [comment]
@reduz Some methods of basic types modify the object they are called on. For example, `Array.append(value)` would return nothing, but would change the array itself. That's why it needs a sequence port, so that you can tell it when to append the value to the array.

**Comment by reduz** [comment]
hmm.. I am not sure if this is marked in the bindings as const, will have to check

**Comment by bojidar-bg** [comment]
@reduz Variant method bindings didn't have const, I added it in my PR (#11258)

**Comment by gamergamesz** [comment]
Thank you so much! Things are working now arrays are iterating!!!!

**Comment by akien-mga** [comment]
For the record, fixed by c5da28f24.

**Comment by flarn2006** [comment]
The Pool Array Append functions still don't have sequence terminals, at least not the Pool Float Array.
