### ISSUE TITLE
Double clicking on message in output should jump to file and line where message is printed

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#10566]
In unity's output window it is possible to double click on every printed message to open the corresponding file and jump to the line with the print() method. 

I think something similar would be a nice addition to godot.

**Comment by akien-mga** [comment]
Fixed by #23875.

**Comment by BeayemX** [comment]
Why was this closed?
You still can't double-click on printed messages in the output log.

Tested with f7d2750844546f5d8a2b664c132890f7ed466b35

**Comment by akien-mga** [comment]
My mistake, I thought this referred to the errors/warnings output panel in the debugger, not the main Output one.

Currently I don't think the Output panel has any information on the provenance of messages, it just gets them from the message queue and prints them. So implementing such feature would need some work and design decision.

**Comment by creikey** [comment]
Maybe a new logging panel that shows entries from `print_debug` ?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1154, as feature proposals are now tracked in the Godot proposals repository.
