### ISSUE TITLE
[4.5] macOS floating game workspace doesn't receive `InputEventMouseMotion` when `Input.mouse_mode == Input.MOUSE_MODE_CAPTURED`

### ISSUE THREAD

**Issue by TranquilMarmot** [godotengine/godot#106431]
### Tested versions

- Reproducible in: v4.5.dev4
- Not reproducible in: v4.4.1

### System information

Godot v4.5.dev4 - macOS Sequoia (15.4.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M4 Pro (Apple9) - Apple M4 Pro (14 threads)

### Issue description

When running my game in the floating game workspace, it does not receive the `InputEventMouseMotion` input (from a trackpad on a Macbook Pro) but ONLY when `Input.mouse_mode == Input.MOUSE_MODE_CAPTURED`.

My code is something like this...

```gdscript
func _ready() -> void:
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)


func _unhandled_input(event: InputEvent):
       print(event, " " , Input.mouse_mode == Input.MOUSE_MODE_CAPTURED)

	if event.is_action_pressed("ui_cancel"):
		if Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

                get_viewport().set_input_as_handled()

	if event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		_handle_mouse_motion(event) # rotate camera, etc.
                get_viewport().set_input_as_handled()
```

When `Input.mouse_mode == Input.MOUSE_MODE_CAPTURED`, the event is NOT logged at all - almost like it is getting consumed by the viewport somewhere.

When `Input.mouse_mode == Input.MOUSE_MODE_VISIBLE`, for example if I hit Option+Esc to free the mouse, then the event is always logged.

If I un-check "Make Game Workspace Floating on Next Play" so that the game window is embedded in the editor, then the mouse input works as expected without any code changes. This is only specific to the floating game window.

### Steps to reproduce

Try to get `InputEventMouseMotion` inside of `_unhandled_input` when using a floating game window on macOS.

### Minimal reproduction project (MRP)

I tried to set up an MRP here with this attached to a camera:

```gdscript
extends Node3D


func _ready() -> void:
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)


func _unhandled_input(event: InputEvent):
	print(event)
	if event.is_action_pressed("ui_cancel"):
		if Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
		
		get_viewport().set_input_as_handled()

	if event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		rotate_y(-event.relative.x * 0.01)
		
		get_viewport().set_input_as_handled()
```

But in a basic project, it seems to work just fine in both the floating and embedded viewports. I'm not sure what would be different in my setup - I only read this event in one place.

**Comment by stuartcarnie** [comment]
I am unable to reproduce the issue. In your scenario, is the `_unhandled_input` always printing the `InputEventMouseMotion`?

In this video, if I press `ESC`, mouse capture is disabled, and the cube stops rotating. Note that I still see the stream of events. I press `ESC` again, capturing the mouse, and the cube rotates again.

https://github.com/user-attachments/assets/84b83ae5-ab4c-40e6-8eb3-0d95b0feea96

If you can provide a complete project that demonstrates the issue, that might help.

**Comment by mieko** [comment]
I'm experiencing this as well, with both floating and embedded Game views.  I'm also using `_unhandled_input`.  

(macOS, git build as of today.)

I noticed another new behavior while debugging this that feels related:

When I...
  - Disable "Game View" (via Manager Editor Features)
  - Run a scene.
  - Using `MOUSE_MODE_VISIBLE`.

The game only receives `InputEventMouseMotion` events when the mouse is **outside** the window rect.  The Window itself eats/ignores events when my cursor is over it.

**Comment by mieko** [comment]
In the top-level menubar, "Editor -> Manage Editor Features" has a dialog that allows the entire Game View to be disabled (it's entirely removed from the window decoration area in Godot's main window, too.)


<img width="746" alt="Image" src="https://github.com/user-attachments/assets/09d967c0-774b-4b93-b794-7ad67b17c642" />


I'm simplifying my case to what @TranquilMarmot reported (`MOUSE_MODE_CAPTURED`, floating workspace) and `git bisect`-ing now.

**Comment by stuartcarnie** [comment]
Cool. That is no the same result as unchecking **Embed Game on next play**

![Image](https://github.com/user-attachments/assets/d3d6fef1-bec6-46c3-8ab2-92fca4e3d883)

I tried that and was also unable to reproduce. If you can give me exact steps and an MRP, it will help!

**Comment by TranquilMarmot** [comment]
Yeah, I really can't figure out an MRP here. I even went as far as completely re-implementing all of my menus and loading states and everything works.

In my project it's only in the floating window that things don't work, and only when going through main menu -> loading screen -> scene. If I run a specific scene without going through all of that, it works in the floating window.

> noticed a `Control` had gotten accidentally scaled to screen boundaries. It was eating the input from an underlying node reacting to `_unhandled_input`.

I was thinking this was what was happening to me, too, but even after deleting all my `Control`s and every single `_unhandled_input` it's broken! Very strange 😩

**Comment by stuartcarnie** [comment]
@TranquilMarmot if you uncheck **Embed Game on Next Play**, does that resolve it? In this scenario it is running as a normal, standalone application without any of the new changes.

**Comment by TranquilMarmot** [comment]
@stuartcarnie yes, un-checking **Embed Game on Next Play** _fixes_ the issue.

The only scenario in which it is broken is when using the embedded, floating window.

**Comment by stuartcarnie** [comment]
@TranquilMarmot if you can put together an MRP that replicates the issue, that would be very much appreciated! I'd like to get to the bottom of it!

**Comment by stuartcarnie** [comment]
@TranquilMarmot I am fairly confident I have addressed the issue, as I noticed that sometimes the host control was not resized after embedding, so it was not correctly placed to intercept mouse events, and replicated the behaviour you described here.

Should be addressed by #106538

**Comment by TranquilMarmot** [comment]
@stuartcarnie I just tried out the latest `master` branch and this is still broken for me on macOS, still only specifically in the floating embedded window. Non-floating window works fine, and disabling embedding works fine.

Let me know if there's anything I could do to help debug 😢

**Comment by stuartcarnie** [comment]
@TranquilMarmot can you provide an mrp that consistently reproduces the issue? 

Without a way for me to reproduce the issue, it is difficult to identify a fix. 

Are you running on an external display (either via a Mini or attached to a laptop). Is the issue reproducible via both, if running multiple displays? What is the resolution of the display and what resolution are you running at?
