### ISSUE TITLE
Rightclick-menu for folders in FileSystem tab is blank if project is made in 4.4

### ISSUE THREAD

**Issue by SteinMakesGames** [godotengine/godot#107804]
### Tested versions

Bug does not occur in v4.4.stable.official
I open the same project in v.4.5.beta.1official, the bug now occurs.
I exit and re-open the project just opened in 4.5beta back to the original 4.4 stable. Bug no longer occurs.

### System information

Godot v4.5.beta1 - Windows 11 (build 22631) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.4630) - AMD Ryzen 5 5600H with Radeon Graphics (12 threads) - 13.85 GiB memory

### Issue description

See video. Rightclicking folders in v.4.5.beta.1 (within the FileSystem tab) makes the popup menu completel y blank, with no visible options in the dropdown menu. The bug does not occur if I create a new folder, until it's first clicked, then it too stays blank. 

The bug does not occur on a fresh project made in 4.5.1beta. However, making a new one in 4.4 and then opening in 4.5 beta makes the bug appear again. Going back to 4.4 makes the bug disappear (until going back to 4.5).

https://github.com/user-attachments/assets/dea6033e-40f0-46c5-9037-c169203cb746

### Steps to reproduce

1) Make a new Godot project in v.4.4.
2) Add some folders (nested?), save.
3) Open the same project in v.4.5.beta.1
4) Try rightclicking folders in FileSystem, it will likely goblank. If not, try click again, open-reopen, mess-around with folders, and they will eventually all go blank.

### Minimal reproduction project (MRP)

[broken_folders.zip](https://github.com/user-attachments/files/20847098/broken_folders.zip)

**Comment by precup** [comment]
I can't reproduce using the MRP. Tried making new folders and interacting with the dock for a while with no issues.

> Godot v4.5.beta1 - Windows 10 (build 19045) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 31.0.15.3713) - AMD Ryzen 9 3900X 12-Core Processor (24 threads) - 31.94 GiB memory

**Comment by KoBeWi** [comment]
Might be related to #99203

**Comment by KoBeWi** [comment]
Can't reproduce either.
@SteinMakesGames Can you check if it's fixed in beta4?

**Comment by romgerman** [comment]
Can't reproduce this in 4.5.beta5. Other than slow rendering there is no issues.
> Godot v4.5.beta5 - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 32.0.15.6119) - AMD Ryzen 5 5600H with Radeon Graphics (12 threads) - 15.34 GiB memory
<details>
  <summary>Rendering</summary>

In 4.4.1 it's the same
RMB -> Esc -> repeat

https://github.com/user-attachments/assets/529729f6-d1b3-480f-8315-4300d752ac07

</details>

**Comment by Repiteo** [comment]
Given a consistent lack of reproduction, I'll assume this has been dealt with and close the issue. If problems persist, let us know
