### ISSUE TITLE
Sound not working on HTML export running with Android device

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#10790]
Godot 2.1.4

1.Export a Game with a playing StreamPlayer Node.
2.Upload the HTML game.
3.Open with Android(Chrome Browser) -> No sound is playing.

Test(I don't know how long this link will work and the file is 11MB)
https://alexholly.itch.io/test?secret=923aJmGOxqkXe1kO8nGGbtgks

**Comment by GustavoMarciano** [comment]
Godot 3.0

The problem persists
No sound is playing.

**Comment by AlexHolly** [comment]
Is there any work beeing done for 2.1 HTML5 or can I close it?

**Comment by vnen** [comment]
cc @eska014

**Comment by akien-mga** [comment]
@eska014 pushed several HTML5 changes to the 2.1 branch, but overall it has various known bugs that were fixed only in 3.0 and later. As it stands HTML5 exports in 2.1 are not recommended for use in production, so I don't think we'll bother trying to support them even on mobile browsers.

**Comment by GustavoMarciano** [comment]
@akien-mga This bug still exists in 3.0
I think this may be related to chrome blocking autoplay
chrome does not allow applications to play HTML5 audio without an explicit action by the user.

**Comment by akien-mga** [comment]
In my opinion it would be better to open a new bug report for that, as this one lacked visibility since it targeted the 2.1 branch.

**Comment by AlexHolly** [comment]
I will give it another test, I am pretty sure it worked on a version a few weeks ago.
