### ISSUE TITLE
for with typed variable does not filter key types in Dictionary iteration (GDScript)

### ISSUE THREAD

**Issue by BielyDev** [godotengine/godot#108539]
### Tested versions

Reproducible error in Godot 4.2-stable, Godot 4.3-stable, Godot 4.4.1-stable
Not reproducible in Godot 4.4.1-stable and earlier versions

### System information

Godot v4.1.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 09 May 2025 17:36:18 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce MX570 A (nvidia; 570.144) - Intel(R) Core(TM) 5 120U (12 Threads)

### Issue description

When using a typed for loop variable in GDScript to iterate over the keys of a Dictionary, the typing does not filter the types as expected.

Example:

`
var a_dictionary: Dictionary = {}
var just_an_array: PackedInt32Array = []

func _ready() -> void:
    a_dictionary[1] = 0
    a_dictionary[2] = 0
    a_dictionary["test"] = 0

    for and_to_be_int: int in a_dictionary:
        print(and_to_be_int)  # Does not print "test"
        if typeof(and_to_be_int) == TYPE_INT:
            just_an_array.append(and_to_be_int)  # Error here when trying to append a string
`

Expected behavior
The typed variable and_to_be_int: int should automatically filter and iterate only over the dictionary keys of type int.

The print should show only integer values.

There should be no error when appending and_to_be_int to the PackedInt32Array.

Current behavior
The loop goes through the value "test" (a string) even though the variable is typed as int.

The print ignores this string (does not print it).

The error happens on the append line with the message:

`
Trying to assign value of type 'String' to a variable of type 'int'.
`

### Steps to reproduce

1. Create a typed array or packed array (e.g., Array[int] or PackedInt32Array).
2. Create a dictionary with keys of different types (e.g., int and string).
3. Use a typed loop variable (e.g., for var: int in dict).
4. Try to access the variable and use it in a PackedInt32Array.append().

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/21191700/test.zip)

A single script is enough to reproduce the issue:

`
extends Node

var a_dictionary: Dictionary = {}
var just_an_array: PackedInt32Array = []

func _ready() -> void:
	a_dictionary[1] = 0
	a_dictionary[2] = 0
	
	a_dictionary["test"] = 0
	
	await get_tree().create_timer(1).timeout
	
	for and_to_be_int: int in a_dictionary:
		print(and_to_be_int)
		if typeof(and_to_be_int) == TYPE_INT:
			just_an_array.append(and_to_be_int)
	
	print(just_an_array)
`

**Comment by dalexeev** [comment]
This is expected behavior, the `for` loop never filters the elements it iterates over. If the collection might encounter an element of the "wrong" type, then you should use type checking and a local variable inside the loop block instead:

```gdscript
for node: Node in parent.get_children():
    if node is not Control:
        continue
    var control: Control = node
    # ...
```

**Comment by HolonProduction** [comment]
To add to that, the code behaves differently than described in this issue at least on `master`. It errors as soon as the string is reached in the iteration: `Trying to assign value of type 'String' to a variable of type 'int'.` which seems like the correct behavior.

**Comment by BielyDev** [comment]
> Esse é o comportamento esperado, o `for` o Loop nunca filtra os elementos sobre os quais itera. Se a coleção encontrar um elemento do tipo "errado", você deverá usar a verificação de tipo e uma variável local dentro do bloco de loop:
> 
> for node: Node in parent.get_children():
>     if node is not Control:
>         continue
>     var control: Control = node
>     # ...



I ended up making a mistake in the issue title by using the word "filter" — what I actually expected was an error to occur when the key is not of the type specified in the for loop.
I also edited the description to reflect the correct error in the script.

**Comment by AThousandShips** [comment]
So just to make things clear, what is the bug you're experiencing?

Is it that it doesn't skip the wrong type, or is it that there's no error?

**Comment by BielyDev** [comment]
> So just to make things clear, what is the bug you're experiencing?
> 
> Is it that it doesn't skip the wrong type, or is it that there's no error?

The expected error does not occur.

**Comment by AThousandShips** [comment]
That should have been solved in `master`, can you test [`4.5.beta3`](https://godotengine.org/article/dev-snapshot-godot-4-5-beta-3/)

**Comment by BielyDev** [comment]
> That should have been solved in `master`, can you test [`4.5.beta3`](https://godotengine.org/article/dev-snapshot-godot-4-5-beta-3/)

The same error occurs in Godot_v4.5-beta3.

**Comment by AThousandShips** [comment]
Does it print the expected error that's missing from 4.4.1, or is it still not printing the error?

**Comment by BielyDev** [comment]
> Does it print the expected error that's missing from 4.4.1, or is it still not printing the error?

Both print the same error, an error that shouldn't occur.

**Comment by AThousandShips** [comment]
The error should be here:
```gdscript
for and_to_be_int: int in a_dictionary:
```

And it should be: `Trying to assign value of type 'String' to a variable of type 'int'.`

Is it there in 4.4.1 and 4.5.beta3?

**Comment by BielyDev** [comment]
> The error should be here:
> 
> for and_to_be_int: int in a_dictionary:
> And it should be: `Trying to assign value of type 'String' to a variable of type 'int'.`
> 
> Is it there in 4.4.1 and 4.5.beta3?

The error should occur on the line you mentioned, but in versions 4.4.1-stable, 4.5-beta3, and the other versions listed in the issue description, this does not happen.

Instead, the error ends up occurring on the line:
just_an_array.append(and_to_be_int)
And the value that causes the error isn’t even printed.

**Comment by AThousandShips** [comment]
Okay, good, that's what I originally asked for sorry for not being clear that I meant the same error on the same line

That sounds like the original bug in 4.4 has been fixed in 4.5, the only problem is that the behavior needs to be documented

**Comment by dalexeev** [comment]
Please note that the error line number is incorrect:

* #92681

**Comment by BielyDev** [comment]
> Please note that the error line number is incorrect:
> 
> * [Wrong error line indicator position of Static typed for loop #92681](https://github.com/godotengine/godot/issues/92681)

The real error is indeed this one, thanks. Even after changing the types and altering the order, the same error still occurs.



<img width="999" height="540" alt="Image" src="https://github.com/user-attachments/assets/e050ac91-d05b-4ef1-9674-66d3dbb90dd4" />
