### ISSUE TITLE
Editor 3D Gizmos disappear after modifying code

### ISSUE THREAD

**Issue by OlegVegan** [godotengine/godot#109114]
### Tested versions

- Present in 4.4.1 stable
- Present in 4.5 beta4

### System information

Godot v4.5.beta4 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6614) - AMD Ryzen 9 3900X 12-Core Processor (24 threads) - 47.92 GiB memory

### Issue description

https://github.com/user-attachments/assets/2f4170b6-6c93-4cff-925d-aacf96c0a2b1

If you select a DirectionalLight3D or CollisionShape3D or SpotLight3D or OmniLight3D, switch to code and modify a variable and switch back to 3D, editor gizmos disappear

### Steps to reproduce

1. Create a 3D scene
2. Add DirectionalLight3D or CollisionShape3D or SpotLight3D or OmniLight3D and select it
3. Switch to code and modify a variable
4. Switch back to 3D

Reproducible 10 out of 10 times on my PC

### Minimal reproduction project (MRP)

[bugreport.zip](https://github.com/user-attachments/files/21503948/bugreport.zip)

**Comment by AThousandShips** [comment]
Can you please test with 4.4.1 to see if this is a regression, also could be the same as:
* https://github.com/godotengine/godot/issues/109022

**Comment by OlegVegan** [comment]
> Can you please test with 4.4.1 to see if this is a regression, also could be the same as:

Reproducible in 4.4.1 too. It could be linked to a similar bug that was fixed in 4.5 beta4
https://github.com/godotengine/godot/issues/106713

**Comment by SilverWolveGames** [comment]
I've faced the same issue. Thanks for reporting

**Comment by dorjoosoft** [comment]
And also when switching between scenes all bones in Skeleton3D nodes not showing and are not editable.

**Comment by SchultzenDK** [comment]
This also happens on my end, except I don't need to edit anything to trigger it.

It happens if I click the script button in the scene tree.  
It does not happen if I click the "Script" button at the top.

Doesn't seem to matter if the script is on Node3D or DirectionalLight3D

https://github.com/user-attachments/assets/e3192bb6-83be-4531-a4ea-deb5aab38f25

**Comment by OlegVegan** [comment]
> This also happens on my end, except I don't need to edit anything to trigger it.

True, I tested it out in 4.5 beta4, it's pretty much the same for me. No need to edit code, a simple switch to Script files triggers it. Most likely the same kind of issue that was in https://github.com/godotengine/godot/issues/106713

**Comment by SchultzenDK** [comment]
Did some more testing.

Found out that if you click the script icon, the inspector seems to select the script in the sub-resource dropdown.

Not sure if it matters, but the inspector doesn't actually show the script resource after it selected it itself. Still shows the DirectionalLight3D resource.

<img width="1172" height="460" alt="Image" src="https://github.com/user-attachments/assets/e4169e38-fcbc-4e46-a0cc-878396f2f694" />

I also initially assumed it was related to the other issue, but now I'm not so sure (but this is also the first time I'm looking at the Godot source, so take all my words with an ocean of salt haha)

**Comment by AThousandShips** [comment]
Note that this can still be the same as:
* #109022 

It was not in beta4 so won't be fixed in the official build

Can you [build from source](https://docs.godotengine.org/en/latest/contributing/development/compiling/index.html)?

**Comment by SchultzenDK** [comment]
My screenshot is of a build from source I pulled about 24 hours ago.

For good measure, I've just pulled again and built, and the issue is unfortunately still present.

**Comment by Alia5** [comment]
> Can you please test with 4.4.1 to see if this is a regression, also could be the same as:
> 
> * [3D gizmos disappearing and not showing back until reopening the scene #109022](https://github.com/godotengine/godot/issues/109022)

Not reproducible in 4.4.1 for me 

Can confirm [#109176](https://github.com/godotengine/godot/pull/109176) Fixes this

**Comment by Ranoller** [comment]
I confirm this bug in 4.5 beta 4. Gizmos are only showed in first scene open, if you change the scene and returns to the previous scene, gizmo is no more displayed until you close and open the scene. (All gizmos listed in viewport/view/gizmos)
