### ISSUE TITLE
`SkeletonModifier3D._process_modification_with_delta` is called with a `delta` value of `0.0`

### ISSUE THREAD

**Issue by nkrisc** [godotengine/godot#110350]
### Tested versions

- Reproducible in v4.5.rc1 [08e9e6b29]
- Not Reproducible in v4.5.beta6 [d5ad0556a]

### System information

Windows 10 - Godot v4.5.rc1 - Forward+

### Issue description

If a node inheriting SkeletonModifer3D is present in the main scene when the application starts, the `_process_modification_with_delta` method is initially called with a `delta` value of `0.0`, which caused some downstream NaN issues. This seems like a bug to me because it seems unexpected that the frame delta should ever be `0.0`, and thus requires always checking for this case. The latest docs do not warn about this issue either.

(Totally separate issue, but it was even harder to diagnose because the debugger is displaying NaN values as `0.0`).

### Steps to reproduce

I have included a MRP, but it is trivial to reproduce with out it.

1. Create a new scene with a Skeleton3D as root. No bones or any other data is required.
2. Create the following class:
```
class_name ZeroDelta extends SkeletonModifier3D

func _process_modification_with_delta(delta):
    if delta == 0.0:
        breakpoint
```
3. Add an instance of ZeroDelta as a child of the Skeleton3D.
4. Run the scene.

### Minimal reproduction project (MRP)

[skeleton-modifier-3d-zero-delta.zip](https://github.com/user-attachments/files/22235910/skeleton-modifier-3d-zero-delta.zip)

**Comment by AThousandShips** [comment]
Might be fixed by:
* https://github.com/godotengine/godot/pull/110145

Could be a regression from:
* https://github.com/godotengine/godot/pull/109841

**Comment by TokageItLab** [comment]
As mentioned in the comments, it should have been fixed in a recent PR.

**Comment by nkrisc** [comment]
I tested the MRP in v4.5.rc2 [2dd26a027] and the issue persists, despite the aforementioned PR being included.

https://github.com/godotengine/godot/pull/110145

At the breakpoint in the MRP `Engine.get_process_frames()` returns `0`.

**Comment by TokageItLab** [comment]
This is the same as AnimationPlayer, but it initially plays at delta 0 as part of state initialization.

As pointed out in https://github.com/godotengine/godot/issues/109110, SkeletonModifier is processed outside the normal Node process cycle because it must be processed once even when paused.

Since this is indeed a difference from the normal Node process cylce, it seems like something that should be documented.
