### ISSUE TITLE
Edit Sun and Environment Settings button leads to engine crash.

### ISSUE THREAD

**Issue by SuperStarVandal** [godotengine/godot#111028]
### Tested versions

v4.5.stable.official [876b29033]
v4.4.1.stable.official [49a5bc7b6] (No issue)

### System information

Godot v4.5.stable - Steam Runtime 2 (soldier) 2 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (nvidia) - 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz (16 threads) - 15.45 GiB memory

### Issue description

I believe it is a regression as there seems to be no issue on v4.4.1 stable, however v4.5.stable presents a bad crash whenever I press on the button Edit Sun and Environment Settings, where instead of loading the preview editor, it briefly shows a transparent panel where the editor should be, only to crash less than a few seconds later. 

### Steps to reproduce

I can reproduce it on both steam and downloadable release, but the issue does not happen on 4.4.1 release, indicating its a new issue. Other than that, I have no clue as it happens on new projects, not sure what else I can provide. (please let me know, I'll try my best to provide!)

### Minimal reproduction project (MRP)

N/A, visible in new project

**Comment by rsubtil** [comment]
I'm not able to reproduce this issue on Arch Linux, X11, on AMD 6750 XT. Could be specific to your setup, maybe graphics drivers, or having a multi-monitor setup (which I don't have).

Can you try testing earlier dev builds of Godot [between 4.4.1 and 4.5](https://godotengine.org/download/archive/#4.5), to narrow down which version introduced this issue?

**Comment by precup** [comment]
I'm also unable to reproduce:

> Godot v4.5.stable - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (nvidia; 570.133.07) - AMD Ryzen 9 3900X 12-Core Processor (24 threads) - 31.28 GiB memory

**Comment by SuperStarVandal** [comment]
> Can you try testing earlier dev builds of Godot [between 4.4.1 and 4.5](https://godotengine.org/download/archive/#4.5), to narrow down which version introduced this issue?

Thank you for the swift support! I have just tried all versions between 4.4.1 and 4.5, and it seems that the issue is introduced in v4.5.beta6.official [d5ad0556a], with beta5 having no issues whatsoever. I am no means an academic on godot, so I am unsure what might be different betwen the versions to cause this issue, but until I updated from 4.4.1 to 4.5 I had no issues using the panel, on my current setup.

I can provide a video if needed, along with other information that you might need in order to help diagnose the issue. 

Cheers!

**Comment by rsubtil** [comment]
Could you also please provide the stack trace when Godot crashes? You'll need to open your project directly from the command line, not from the project manager:
`./godot.exe -e --path <path/to/project>`

**Comment by SuperStarVandal** [comment]
> Could you also please provide the stack trace when Godot crashes? You'll need to open your project directly from the command line, not from the project manager: `./godot.exe -e --path <path/to/project>`

I did this for v4.5 stable, here is what my terminal produced after recreating the crash:

new-game-project
Godot Engine v4.5.stable.official.876b29033 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 570.172.08 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3060


thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_consumer-0.30.0/src/iterators.rs:406:45:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by Zireael07** [comment]
AccessKit related crash it looks like.

Disable accessibility/accesskit in Godot settings and it should go away

**Comment by rsubtil** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Try running the following commands and check the output (both should return `false`), `AccessKit` code should not be called if you are not using screen reader (it seems to be quite buggy on Linux):

```
dbus-send --dest=org.a11y.Bus --print-reply /org/a11y/bus org.freedesktop.DBus.Properties.Get string:org.a11y.Status string:IsEnabled
```

```
dbus-send --dest=org.a11y.Bus --print-reply /org/a11y/bus org.freedesktop.DBus.Properties.Get string:org.a11y.Status string:ScreenReaderEnabled
```

**Comment by SuperStarVandal** [comment]
> Try running the following commands and check the output (both should return `false`), `AccessKit` code should not be called if you are not using screen reader (it seems to be quite buggy on Linux):

Both are returning true unfortunately...

> AccessKit related crash it looks like.
> 
> Disable accessibility/accesskit in Godot settings and it should go away

I am quite the noob and unsure of where and how to disable these settings, I will try to see if it is something I can manage on my end, seeing as not many others are having this issue. Also, thank you for the support, you guys catch on to these things crazy fast!!!

**Comment by bruvzg** [comment]
> I am quite the noob and unsure of where and how to disable these settings

`Editor` (menu) → `Editor Settings`, in the dialog `Interface` → `Accessibility` → `Accessibility Support`, set it to "Disabled".

<img width="755" height="393" alt="Image" src="https://github.com/user-attachments/assets/16ae2b90-83cc-48a8-9242-1ed29c2e5f58" />

**Comment by SuperStarVandal** [comment]
FIXED!

Thank you!!!

> `Editor` (menu) → `Editor Settings`, in the dialog `Interface` → `Accessibility` → `Accessibility Support`, set it to "Disabled".

You guys are all legends, something so simple but sometimes a pain to figure out for the average user, you guys take your time out of the day to help, I can't be more grateful!

I certainly hope anyone who gets the same issue is able to find this thread going forward :D

I'm not sure if I'm the one who should be closing this thread so I will leave it as is but know that I don't have anymore problems, you guys are doing great work out here!

**Comment by Zireael07** [comment]
No, please leave it as there is clearly some sort of an issue with dbus/AccessKit itself

**Comment by DataTriny** [comment]
Hi there,

Not sure exactly what is leading to these crashes but I'm making them impossible in https://github.com/AccessKit/accesskit/pull/621.

The fact that AccessKit gets initialized for so many users who apparently don't have any assistive technology running on their system is concerning and I am not sure what is the best course of actions there. We are playing by the rules so I'm starting to wonder if some Linux distributions force accessibility to always be enabled.

**Comment by bruvzg** [comment]
> Not sure exactly what is leading to these crashes but I'm making them impossible in

It almost certainly has something to do with the creation and destruction of windows, but I was not able to determine the exact cause. The issue is extremely inconsistent.

**Comment by bruvzg** [comment]
> We are playing by the rules so I'm starting to wonder if some Linux distributions force accessibility to always be enabled.

All distros I have tested seems to behave correctly, but we got a bunch of issues from the same distros  (this is the first one when both dbus properties are set), so it might be caused by a specific app (something is abusing accessibility API to circumvent screen/input capture restrictions?), and not a distro issue.

**Comment by DataTriny** [comment]
I have found another issue hitting this exact same bug with a bunch of people running different distributions and presumably no assistive technology: https://github.com/JHDev2006/Super-Mario-Bros.-Remastered-Public/issues/89

**Comment by DataTriny** [comment]
@bruvzg I've just released [accesskit-c 0.17.1](https://github.com/AccessKit/accesskit-c/releases/tag/0.17.1) which contain the fix for this bug.

**Comment by bruvzg** [comment]
> I've just released [accesskit-c 0.17.1](https://github.com/AccessKit/accesskit-c/releases/tag/0.17.1) which contain the fix for this bug.

I'll test in and update our custom build repo on Saturday.

**Comment by bruvzg** [comment]
Still getting crashes with the same dialog, but in slightly different conditions:

```
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.17.1/src/context.rs:61:78:
called `Result::unwrap()` on an `Err` value: InterfaceNotFound
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/result.rs:1765:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/result.rs:1167:23
   4: accesskit_unix::context::get_or_init_messages::{{closure}}::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.17.1/src/context.rs:61:78
   5: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.0/src/future.rs:454:46
   6: async_executor::State::run::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.1/src/lib.rs:748:32
   7: async_executor::Executor::run::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.1/src/lib.rs:344:34
   8: accesskit_unix::executor::Executor::run::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.17.1/src/executor.rs:85:39
   9: futures_lite::future::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.0/src/future.rs:99:35
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/thread/local.rs:315:12
  11: std::thread::local::LocalKey<T>::with
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/thread/local.rs:279:20
  12: futures_lite::future::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.0/src/future.rs:78:11
  13: accesskit_unix::util::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.17.1/src/util.rs:13:5
  14: accesskit_unix::context::get_or_init_messages::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_unix-0.17.1/src/context.rs:57:17
```

Seems to only happen if text input control in the popup was focused when popup is closed, so might be related to IME (but there are no issues with-non popup windows).

At least it is less random, and might be easier to debug, so I'll try to reproduce it with a simple project instead of editor a bit later.

**Comment by DataTriny** [comment]
Unfortunately this stack trace doesn't point to the exact place where the crash occur. If you can give me reliable steps to reproduce, I might be able to see what happens on our side.

**Comment by bruvzg** [comment]
> If you can give me reliable steps to reproduce, I might be able to see what happens on our side.

- Open any project in the editor (creating new empty project will work).
- Select 3D tab.
- Open sun preview popup (`⋮` button).
- Select and enter edit text for any of the values (it is not crashing if it's editor with slider).
- Close the popup (click outside it).
- It is crashing when popup is closed.

<img width="1192" height="715" alt="Image" src="https://github.com/user-attachments/assets/4562c536-6de0-4e36-ba35-e8746c384524" />

**Comment by DataTriny** [comment]
@bruvzg I still don't have the proper setup to hunt this bug, but I have prepared a [modified version of the bindings](https://github.com/AccessKit/accesskit-c/tree/tree-capture). You'd have to set the `ACCESSKIT_CAPTURE_PATH` environment variable to a JSONL file that I'd appreciate you sending to me if you happen to trigger the bug. Hopefully this file will allow me to replay the sequence of events that led to the crash.

Also, we've just released [accesskit-c 0.18](https://github.com/AccessKit/accesskit-c/releases/tag/0.18.0) which contain changes in how we initialize on *nix platforms: detecting if an AT is running, not if accessibility is enabled on the system. This should finally prevent users who don't need AccessKit to hit this bug in the first place.

**Comment by bruvzg** [comment]
I'll check this Friday.

**Comment by bruvzg** [comment]
> I still don't have the proper setup to hunt this bug, but I have prepared a [modified version of the bindings](https://github.com/AccessKit/accesskit-c/tree/tree-capture). You'd have to set the ACCESSKIT_CAPTURE_PATH environment variable to a JSONL file that I'd appreciate you sending to me if you happen to trigger the bug. Hopefully this file will allow me to replay the sequence of events that led to the crash.

https://gist.githubusercontent.com/bruvzg/b79003161681739e7eadbf2cc5985900/raw/93846bb38bf1de37f4c7a5cc5285ab12eaa8fc31/crash.jsonl

> Also, we've just released [accesskit-c 0.18](https://github.com/AccessKit/accesskit-c/releases/tag/0.18.0) which contain changes in how we initialize on *nix platforms: detecting if an AT is running, not if accessibility is enabled on the system.

Since I was not able to reproduce conditions when screen reader is incorrectly detected, I can't test it, but the crash with enabled screen reader is still reproducible.

I'll update Godot repos to 0.18 on the weekend.

**Comment by DataTriny** [comment]
Thanks @bruvzg, I'm able to reproduce the crash without having to run Godot with your file. I'm currently investigating and will let you know once a fix is available.

**Comment by bruvzg** [comment]
Reopening since it is not fully fixed, same background thread `called Result::unwrap() on an Err value: InterfaceNotFound` crash is still happening, it seems to be semi random and less frequent (only common condition is removing nodes), so might be a race condition.

**Comment by phoenixdk** [comment]
I've also been having this issue, starting within the last week. I've been used to working for hours with Godot with no problems, but now I get a crash every hour or so. Godot v 4.6.2.stable on Windows 11, I get this error:
thread '<unnamed>' (13388) panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/accesskit_consumer-0.35.0/src/tree.rs:224:21:
TreeUpdate includes duplicate child #634843410989746
