### ISSUE TITLE
Scaling problems on Android

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#11387]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot bc005a57d38137b062e0ccc26467353f53556930, Samsung Galaxy S6 (Android 7.0)

**Issue description:**

See how scaled screen looks like on [Android (bad)](https://user-images.githubusercontent.com/2417849/30807974-5b51b5d2-a226-11e7-92b7-899af73a58c2.png) vs [macOS (ok)](https://user-images.githubusercontent.com/2417849/30807975-5c830848-a226-11e7-8102-b2b6a156cfc5.png) with the same project.

![Android (bad)](https://user-images.githubusercontent.com/2417849/30807974-5b51b5d2-a226-11e7-92b7-899af73a58c2.png)
![macOS (ok)](https://user-images.githubusercontent.com/2417849/30807975-5c830848-a226-11e7-8102-b2b6a156cfc5.png)

**Steps to reproduce:**

```bash
git clone -b 2d-scale-bug https://github.com/endragor/etc2bug.git 2d-scale-bug
cd 2d-scale-bug
godot --export-debug Android test.apk
```

Then install and open `test.apk` on the device.

**Comment by volzhs** [comment]
you can attach images directly on github with D&D.

**Comment by endragor** [comment]
@volzhs thanks, will do that next time. Are the images still visible for you? Shouldn't this issue be put on 3.0 milestone? This seems to be the main thing preventing games from looking as expected on Android. There are also font scaling problems in general - it looks as if texts are scaled after being rasterized which results in severe visual artifacts.

**Comment by Calinou** [comment]
> Are the images still visible for you?

Yes, the images are still visible. However, to my knowledge, Imgur deletes images which have received no views in 6 months and compresses large images (which may be undesirable). So, it's better to use GitHub attachments.

**Comment by endragor** [comment]
Changed links to point to GitHub attachments.

**Comment by volzhs** [comment]
I edited OP to show image directly.

**Comment by kosz78** [comment]
Some additional information.

Below some artifacts that taken from Android Device Monitor:
result screen(cropped):
![screen_cr](https://user-images.githubusercontent.com/3992195/31110458-7d30e810-a831-11e7-834b-fa0332964e53.png)

Generated font texture (inverted for preview):
![texture_neg](https://user-images.githubusercontent.com/3992195/31110547-014c31b8-a832-11e7-82c9-f0342c27771b.png)

Texture parameters:
![texture_params](https://user-images.githubusercontent.com/3992195/31110562-1ba02862-a832-11e7-9869-8ba40f1da7e1.png)

Fragment shader that draw one symbol:
[fragment_shader.txt](https://github.com/godotengine/godot/files/1351172/fragment_shader.txt)

**Comment by endragor** [comment]
Scaling part of this issue would be fixed by #12022. But even when scaling is alright, fonts and some other 2D elements are rendered ugly as shown in the previous comment.

**Comment by reduz** [comment]
Scaling should now be fixed. I don't undestand the font problem

**Comment by endragor** [comment]
Texts get distorted on Android (and iOS). Take a look at these images:

![Android (bad)](https://user-images.githubusercontent.com/2417849/30807974-5b51b5d2-a226-11e7-92b7-899af73a58c2.png)

(it may not be seen in the preview easily - just open it in full size in a separate tab).

 ![img](https://user-images.githubusercontent.com/3992195/31110458-7d30e810-a831-11e7-834b-fa0332964e53.png)

**Comment by endragor** [comment]
Still seeing the scaling issue as shown on the original screenshot with current master.

**Comment by endragor** [comment]
Now it's actually fine. So either I used old apk or old Godot or it's been fixed since the last comment :/

@reduz any chance you can look into the rendering issue? It's currently the main thing hurting the look on mobile. Seems to affect not only the fonts but any 2D elements. Very visible on the edges of UI elements.

**Comment by reduz** [comment]
@endragor the font problem is really strange, does it only happen on Android?

**Comment by endragor** [comment]
@reduz both Android and iOS.

**Comment by akien-mga** [comment]
The scaling issue being fixed, and the rendering issue tracked in #15116, closing.
