### ISSUE TITLE
Mouse warping in editor plugin doesn't work if no mouse buttons are pressed

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12497]
Godot 3.0 Windows 10 64 bits

I was implementing a feature that would make holding RMB optional when using freelook (https://github.com/godotengine/godot/issues/10463#issuecomment-340312665). And then I found that `Input::warp_mouse_motion(motion_event, rect)` is not working at all in this situation.

It doesn't work because InputEventMouseMotion never reports positions outside of the rectangle if no mouse buttons are pressed, but it DOES when buttons are pressed for the very reason of warping the mouse Oo

Is it a bug?

**Comment by mhilbrunner** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
Because of this bug, freelook is currently using mouse lock like an FPS. I don't remember well how I did test this bug though...

**Comment by akien-mga** [comment]
@Zylann Wasn't this fixed in 3.1? If not, it would be good to have a minimal reproduction project to get it tested and fixed.

**Comment by Zylann** [comment]
From the initial description, I think mouse motion is not reported outside of the rectangle because mouse capture only happens for a dragging gesture, so a button of the mouse needs to be pressed.

However, there is still investigation to be made for freelook mode to not rely on FPS mouse locking.

So currently, freelook uses mouse locking. What was fixed in 3.1 is the fact that sometimes it stayed locked.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by KoBeWi** [comment]
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.

**Comment by Zylann** [comment]
Note, it is not possible to make an MRP because `warp_mouse_motion` is not exposed to GDScript. Originally this issue is about the inability to implement freelook with RMB using mouse warp instead of locking like an FPS.
