### ISSUE TITLE
C# new export variables won't show in Inspector until restart

### ISSUE THREAD

**Issue by codeFlu** [godotengine/godot#12518]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux Ubuntu 16.04 , 3.0.Alpha (3-4 day old i think), R7 250

**Issue description:**
Script wont show references in Inspector if i dont restart Godot , and no support for Lists :(

**Steps to reproduce:**
Created new project, c# script whit export variable,  added it to node

[Export]
public int ran = new int();

wont show in inspector, tryed switching nodes, starting stoping game, nothing worked until restarted godot. Possible cuz it was first added script, later adding more export variables, started showing after  running game in editor

**Comment by neikeq** [comment]
Currently, Godot does not build the project automatically when your script changes. You can build with the `Build Project` button in the `Mono` bottom panel, or externally from an IDE or terminal.

**Comment by akien-mga** [comment]
Duplicate of #11955?

**Comment by codeFlu** [comment]
Ok just saying , even if i builded in vscode it dident show in inspector until i restarted Godot editor..  I get it needs alot of polish anyway, and pls dont froget to add support for Exporting Lists and Arrays... This is my first issue whit github so sorry if i am not using it proper :)

**Comment by akien-mga** [comment]
Your issue is good, don't worry :) My comment is more meant for @neikeq to decide if it's the same issue or a different but related one.

**Comment by neikeq** [comment]
@codeFlu that was fixed by #12474. Now Godot should detect that the assembly changed and reload it.

**Comment by akien-mga** [comment]
Well I could still reproduce this issue today with a build newer than #12474, though I'd have to debug a bit more to see the exact steps to reproduce.

**Comment by zatherz** [comment]
C# exports don't appear for me even after restarting Godot.

**Comment by NathanWarden** [comment]
@zatherz I think what's going on here is that the C# project needs to be built before Godot can know about the variables. So, instead of restarting, try adding the export attribute, then run your game with F5 or F6. The variable should then appear in the inspector.

**Comment by zatherz** [comment]
@NathanWarden It doesn't, but I might have to make a new build

**Comment by zatherz** [comment]
Found my problem, only fields can be `Export`ed at this moment. Can reproduce this issue.

**Comment by akien-mga** [comment]
Many users are confused by this issue, it even makes the `monkey_pong` demo hard to understand as the export variables used to set the paddle and wall directions are not visible at first.

**Comment by NathanWarden** [comment]
This also causes a **major** issue when working in teams or on multiple machines because when downloading the repo for the first time when you first open the project whatever variables are in the startup scene get auto-updated, but since they haven't been exported they get completely deleted. I could make a video showing this if desired.

I may be wrong, but the obvious solution seems to be that when opening the project it should compile the project (if possible), then load the first scene.

**Comment by neikeq** [comment]
@NathanWarden That's not related to this, but it sounds like a serious issue indeed.

**Comment by NathanWarden** [comment]
@neikeq Thanks, I'll open a new issue :)

**Comment by maikramer** [comment]
New problem, if i export arrays, and mark as [Tool], i cant change the array length in inspector, if i try too much godot crash without too much things in console.
if i dont mark [Tool], i can change the array in inspector, but with no effect, if i debug i see that the array is null, then i think is something about the code that change the array lenght in mono

should i open another issue?I could not find any issue already open.

if i can make any test to help i can do

**Comment by exts** [comment]
Yeah I'm having this issue on master atm.

**Comment by Jaden-Giordano** [comment]
Im having an issue where once I add a signal, the exports I added are no longer showing in the inspector and the signals aren't either.

**Comment by NQNStudios** [comment]
As of today on Ubuntu 16.04 running 3.0.5 Mono version stable, I get the same behavior as @maikramer:

> Created new project, added some [Export] variables
> Not showing even building the project.
> Restarted godot
> Without doing anything, now the variables show
> Added new [Export] variables
> Showing perfectly after build.
> 
> Looks like its just a problem in a new project in the first run. 

Looks like it's been a while. Is anyone still maintaining the Mono version? I might be able to help on this issue with some guidance from someone who's worked with the code base before.

**Comment by NathanWarden** [comment]
If I remember correctly, this is an issue even with GDScript, where if a script had an error in it then it could no longer generate the variables, thus those values would be lost when the scene is saved.

So, I think the solution would be to have Godot internally know the last successful build of each script, and only update serialized variables in the event of a successful build. It would be set to unsuccessful by default, so when you first open a project it will keep all variables there. This is especially a problem if you just cloned a project from source control, as this means everything gets reset immediately in the main scene.

**Comment by NQNStudios** [comment]
That's not the problem I'm describing. My script built *successfully*, but its Export variables still didn't show up in the editor without restarting.

**Comment by NathanWarden** [comment]
Oops, I confused this with another very similar issue (again). I bet you'd should be safe to try and tackle this bug then :) @neikeq is still the maintainer, but if I'm not mistaken, I *think* his time is somewhat limited right now due to school, but should pick up soon.

**Comment by neikeq** [comment]
Does this still happen after f1130f9?

**Comment by NQNStudios** [comment]
I'll let you know as soon as I've forked and built from source -- might take until tomorrow.

**Comment by NQNStudios** [comment]
Still haven't checked on Ubuntu because when I ran the build with Mono support enabled, there was still no option to create a C# project. Maybe the build failed silently and I was running the non-Mono bin by accident. I'll look into it more when I get the chance

**Comment by lawsonry** [comment]
@NQNStudios I ran into the same problem on my Mac last week. Thank you for taking care of Ubuntu. in my case, though I had thought I set the build flags appropriately, I ended up with a non-Mono Godot. Nowadays I just check the About box as soon as I am done building to verify I didn't screw things up.

**Comment by neikeq** [comment]
What is the issue? The C# project should be generated automatically when you create a C# acript. Is there any error?

**Comment by lawsonry** [comment]
@neikeq There's no error, just behavior that is unexpected. I don't think this is a bug so much as a feature request. When working in a C# script, if I add `[Export]` to a variable and then go back to Godot, I need to rebuild the project before my exported variable appears in the editor. 

I believe the intention is to have this automatically updated behind the scenes, wherein I add `[Export]` to a variable, go back to the editor, and the editor sees the change and then adds it to the Godot inspector pane automatically--without us having to automatically build the project.

It's more of a nuisance than anything else, and anyone coming from Unreal or Unity has this "auto-build" expectation as well.

**Comment by lawsonry** [comment]
Again, I think this should be re-labelled, since this is not a bug and more of a feature request/improvement.

**Comment by exts** [comment]
@lawsonry I get what you're saying. Essentially with gdscript if you make a change in the editor (even before saving) godot picks up your export variables on keypress it seems.

With c# it picks it up on build and that's not a problem, but it would be nice if godot would reload assemblies if a script has changed when focused. Then it would update exports in the editor before building, but idk if the editor can do that without building the source.

**Comment by neikeq** [comment]
Oh, I thought the issue was that the exported properties didn't appear after building.
I plan to make building automatic, it's just that I've been focusing on other parts.

**Comment by lawsonry** [comment]
@neikeq Thank you for your response. I know from other threads that that's your plan, which is why I though this issue should be relabeled as a feature request/improvement because it's not really a bug.

**Comment by exts** [comment]
@lawsonry yeah, you should create a new issue and I think and @neikeq should close this one because that original issue essentially fixed to the first problem which was you not being able to see exports until you restart. Now building from the mono tab or play scene reloads them fine.

**Comment by NathanWarden** [comment]
The issue was that the variables didn't show up even after building. I'm not sure if it has been fixed or not, but I had also seen this a few times. I haven't had much time to work in Godot in the last couple of months, so maybe it's been fixed since then :)

**Comment by lawsonry** [comment]
@NathanWarden I think it has been fixed. I've been testing v3.0.6 on both Mac and Windows, and in both cases, a rebuild of the project makes the variables appear.

**Comment by neikeq** [comment]
I'm closing this then. Feel free to open an issue about automatic builds.

**Comment by gusg21** [comment]
Sorry to revive this but it's still not working for me. It doesn't even work when I rebuild, or restart Godot. I can use hard-coded values in the meantime but I really like this feature and wish it worked.

I'm running Windows 10, 64-bit.

**Comment by gusg21** [comment]
Okay, it updates but only if I changed the hard coded value. If I change the variable name it doesn't care.

**Comment by Delpire** [comment]
Same issue here. I set the value in the editor, then I try to GD.Print() the value. I always get 0 no matter what I set it to. I've tried with both a Property, and a Field, neither work for me.

They appear in the editor just fine. They just don't do anything.

**Comment by Delpire** [comment]
Additionally, removing an export seems to not remove the exported variable from the Godot editor. I've remove it, rebuild, closed the scene, closed godot, reopened everything. Its there forever.

**Comment by glebasos** [comment]
Fixed for me on 4.0 Beta

**Comment by Aurumaker72** [comment]
Possible regression: this sometimes still happens, requiring a manual build to coerce the editor into showing the newly added exports.

**Comment by hsandt** [comment]
The issue reappeared indeed, but in specific contexts, for reasons related to changes in Godot 4. To leave this old issue closed, I'd recommend future reporters to open new issues, if possible with the more specific contexts causing the bug.

For instance:
Issue with tooltips update only: https://github.com/godotengine/godot/issues/70217
If this only happens with base class fields on child class instances: https://github.com/godotengine/godot/issues/73390

**Comment by Momo8289** [comment]
Having this same issue on Godot 4.2.2 on Windows 11. Even after building, reloading the project, changing the script, etc. No exported properties showing up in the editor.
