### ISSUE TITLE
A new script to drive Kinect 2 sensor via Ni Mate, but GDScript leaks memory

### ISSUE THREAD

**Issue by jay3d** [godotengine/godot#12513]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 x64, Godot git latest, Quadro K5000m, Latest NVIDIA driver

**Issue description:**
Ni Mate script works perfectly, but the memory consumed by Godot keep increasing steadily without stopping, as it is shown in the included video. Possibly a memory leak.

**Steps to reproduce:**
Ni Mate software is free and can be operated without an actual sensor (e.g. Kinect) by using the built it recorded capture to test.

**Link to minimal example project:**
[NiMate.zip](https://github.com/godotengine/godot/files/1427105/NiMate.zip)

![leak](https://user-images.githubusercontent.com/2527637/32171394-e59d305c-bdb2-11e7-8288-75e4d3ee3821.gif)

**Comment by jay3d** [comment]
Guys?! You're gearing up for beta and no one even commented on this issue? This is serious memory leak here!

Please consider this. I did my homework and included full description with sample project and it's really easy to test.

**Comment by akien-mga** [comment]
>  jay3d commented 2 days ago 

2. Days. Let us breathe.

**Comment by reduz** [comment]
IF anyone wants to debug what may be causing a leak, feel free to give it a try

**Comment by reduz** [comment]
on Linux, valgrind with memcheck is a nice alternative to debug leaks, also LLVM has tools for this.

**Comment by jay3d** [comment]
Unfortunately, memory leak detection tools on Windows are very rare, I tried Dr.Memory but it crashes miserably with Godot :(

**Comment by alejodiazg** [comment]
@jay3d MIcrosoft used to have App Verifier and umdh, maybe one of those can u help debug.

**Comment by jay3d** [comment]
Ok, latest Godot compiled with VS 2017 doesn't show any memory leak, but only when compiled with Mingw64 GCC 7.2.0, I have to try to compile it with Clang to see if any memory leaks occur.

**Comment by reduz** [comment]
this may have been solved by @hpvb 's recent fix to the GDScript VM, so confirmation welcome

**Comment by hpvb** [comment]
If it didn't happen with GCC it's almost certainly the scoping issue of the dispatch code that was fixed.

**Comment by mhilbrunner** [comment]
@jay3d Any updates on this? Can you still reproduce this with current master or can this be closed?

**Comment by akien-mga** [comment]
Assuming fixed, please comment if it's not the case.
