### ISSUE TITLE
(Import) Plug-ins will not activate on editor launch

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#12749]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
WIndows 10 (x64), Godot 3 Alpha 2

**Issue description:**
First off, disclaimer: I don't know if this issue exists for all kinds of plug-ins, I have only used import plug-ins so far in Godot 3.

When opening a project with enabled import plugins, the associated file types are not shown in the FileSystem Dock and will not be reimported at all (not automatically and the option is not available if manual is attempted).
To fix this, you have to open the project settings and disable, then re-enable the plugin and hit Update. Sometimes it doesn't even work until you disable it, then hit Update, then re-enable and then hit Update again.
If multiple import plugins are present, doing this once will activate all of them at once.

The console outputs this error, which seems very related:
```ERROR: EditorNode::set_addon_plugin_enabled: Condition ' p_enabled && plugin_addons.has(p_addon) ' is true.
   At: editor\editor_node.cpp:2655
WARNING: not found: editor_plugins/enabled
```

Also, Godot seems to completely re-import every file that the given import plugin CAN import, even though the files were already present in the `.import/` directory. This does not seem desirable.

Visual example of this issue:
![plugindelayoptimized](https://user-images.githubusercontent.com/20242421/32557475-8a72f710-c4a2-11e7-9f97-cbcdb3a35d4a.gif)

**Steps to reproduce:**
* Install and enable an importer plugin in a project
* Quit to Project List or close Godot entirely
* Re-open the project

**Link to minimal example project:**
[Tiled Importer Example Project.zip](https://github.com/godotengine/godot/files/1454444/Tiled.Importer.Example.Project.zip)

**Comment by leoddd** [comment]
Just want to confirm that this is still the case in Godot 3 Beta 1, the re-importing logic rework that happened had no effect on this.
(It wasn't supposed to, but I figure it's worth mentioning just so nobody has to go and test that.)

**Comment by vnen** [comment]
I can't reproduce this with a current build. The re-import is working as it should. The other problems are very similar to what I mentioned in #9286 and they were already solved.

**Comment by reduz** [comment]
since report is for alpha, i will close. please reopen if problem persists

**Comment by leoddd** [comment]
Problem persists in build a8ae46e.

See here, the .tmx file only shows up in the FileSystem dock after disabling a plugin:
![importfilesmissing](https://user-images.githubusercontent.com/20242421/33744422-62471ade-dbb1-11e7-92ff-79cbd170c567.gif)

Note that this can be any plugin, it doesn't even have to be the plugin associated with the file type.

**Comment by vnen** [comment]
Okay, I get now. When you have more than one import plugin, it seems only the first one will work on start. I'm not entirely sure *why* this happens.
