### ISSUE TITLE
Containers don't resort themselves properly when elements inside are removed

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12919]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Propably since forever.

**Issue description:**
A while ago I made this report https://github.com/godotengine/godot/issues/10207, thinking that the problem was only with ScrollContainers, but with the help of @manokara, we found out that the problem lies with Containers in general.

**Here's the true issue:** Containers take into account the removed elements when auto resorting.

**Comment by YeldhamDev** [comment]
@reduz, as the archived bug before this one was tagged "hero wanted", could you consider tagging this one it as well? As it affects not just ScrollContainers, but all Containers in general.

**Comment by DualMatrix** [comment]
This seems fixed in master.

**Comment by YeldhamDev** [comment]
@DualMatrix Just tested, still occurs.
But now reflecting a little more on it, I think this behaviour is fine. It would be quite the annoyance to have a Container with a certain size shrink itself when removing elements.

**Comment by akien-mga** [comment]
Closing then as a "feature" :)
