### ISSUE TITLE
Cannot change remote variables in debuger

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#13346]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, d992eb1

**Issue description:**
I am unable to change the variable values in the remote debugger unless i use the arrows manually.

**Steps to reproduce:**
setup some variables in a script, run the game and try to adjust them in the remote debugger

**Link to minimal example project:**
![unlineddaringindochinesetiger-max-14mb](https://user-images.githubusercontent.com/6185415/33280492-46e0ea02-d370-11e7-8d9c-7c0ea5108bdb.gif)

**Comment by Geequlim** [comment]
It did work before :confused:

**Comment by Geequlim** [comment]
I have found the reason. This will be fixed tonight.

**Comment by Geequlim** [comment]
@reduz  Find the reason for failing to change the remote values as you mentationed in #11940 
The property edit tree items are updated (They are cleared and recreated by the debugger) before enter the new value so the changed value cannot be emitted to the editing object.
Any way for `PropertyEdit` or `Tree` to check the value is editing to avoid update the property items?

**Comment by reduz** [comment]
We could disable updating for like 10 seconds after an edit is done?

**Comment by Geequlim** [comment]
That shouldn't work as the property tree items have already updated before the edit done.
For example:
 When I select the `anchor_top` property of the Control then it popup the selection dialog then the property items are updated by the debugger and then the choice is not affect to the *new* editing object.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by Geequlim** [comment]
@reduz I can still reproduct this problem with the new inspector.

**Comment by avril-gh** [comment]
it simply constantly steal focus while updating controls so they cannot be selected nor edited by user.
1. updating controls shouldnt set focus to updated control.
2. if control have focus - it shouldnt be updated - because it meant user is editing it.

**Comment by avril-gh** [comment]
also closing https://github.com/godotengine/godot/issues/21805 as resolved by d16ce4a

**Comment by MattUV** [comment]
Well, it seems that the bug is still present.

Here, I have an array (sources), containing a dictionary (source_dict), containing some keys/values.
I cannot modify any of the key/values, nor access sublevels of editing, such as the PoolByteArray "data".

![bug](https://user-images.githubusercontent.com/13215043/51982578-b280f180-2496-11e9-8c2e-c4bfd357fc20.gif)
