### ISSUE TITLE
Messed up animation when importing 3D scene DAE

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#14399]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 3 (tip), ubuntu

**Issue description:**
When importing a DAE that contains a rigged mesh and animation exported from blender using the better collada exporter, the resulting animation flips around and generally misbehaves.

Here's an example video, blender is running on the right (slowly) and the equivalent import for godot is on the left.
https://www.youtube.com/edit?o=U&video_id=fBVpZ2v6Nt4

**Comment by Zireael07** [comment]
The link is bad (are you sure it should have "edit"? it leads to creating a new video i.e. prompting to create a channel)

**Comment by dodgyville** [comment]
Oops, thanks, corrected!

**Comment by rminderhoud** [comment]
FWIW I am also having a similar issue with rigged meshes and animations except I am not importing a COLLADA file. It would be good to identify whether this is an issue with the COLLADA importer or with the animation system.

**Comment by karroffel** [comment]
I experience the same thing, but it looks like it's Better Collada's fault.

Comparison Blender - Godot: https://gfycat.com/ScentedConfusedBeardedcollie

Watch the head movement. It's not completely smooth in Blender either but it's much more bumpy in Godot.

I also tried the two glTF exporters for Blender. One exports the meshes incorrectly but has proper animations, the other one has (almost) proper meshes but no animations.

Here you can see that the head movement is a lot smoother like in Blender: https://gfycat.com/FarawayHideousChimpanzee

So the problem seems to actually be in the Better Collada exporter and not Godot.

**Comment by rminderhoud** [comment]
@karroffel - Do you have a 3rd software you can use to test the penguin that was exported with Better Collada exporter? What about when you re-import the Collada file back into blender?

**Comment by dodgyville** [comment]
I found this nugget while looking at an unrelated 3D program that exports to DAE. This describes the symptoms of my problem but I'm not sure how it applies to exporting.

"COLLADA does not support a native 4x4 matrix transformation format, so we write to the file as a translation or rotation. If you use this to make smoothed animations, this can lead to gimbal lock issues, which appear as sudden 180 flips in playback. You many need to manually edit rotations or smoothing settings."

**Comment by rminderhoud** [comment]
@dodgyville Interesting find but it looks like the collada export uses a 4x4 matrices?

Writing the bone matrix to collada:
https://github.com/godotengine/collada-exporter/blob/master/io_scene_dae/export_dae.py#L1113

Here is how it makes the 4x4 matrix string:
https://github.com/godotengine/collada-exporter/blob/master/io_scene_dae/export_dae.py#L61

**Comment by rminderhoud** [comment]
@dodgyville are you able to share the file you've been working with?

**Comment by dodgyville** [comment]
It's a pretty large file (256mb - several minutes of animation), I'll see if I can shrink it.

I've just noticed that if I [bake the animation](https://i.imgur.com/rYpmXJc.png) using the Pose data then the import to godot plays smoothly but the character does not move around.

**Comment by rminderhoud** [comment]
So you are now able to import the skeleton (armature) into godot correctly with animations but the mesh does not move? Was the issue always only with the mesh or was the armature previously "spinning" also?

**Comment by dodgyville** [comment]
I mean the bone animation deforms the mesh correctly and there is no flipping but the character does not move around the scene and is instead pinned in place. So close! [Video](https://www.youtube.com/watch?v=f45guMdylyY)

**Comment by dodgyville** [comment]
OK, update on this. In Blender, changing the rotation type for objects (3D View > Properties region (N) > Transform panel > Rotation) from XYZ Euler to Quaternion (WXYZ) helps a lot when exporting as DAE. There's now an issue with the object drifting around but it's closer than ever.

**Comment by artellblender** [comment]
Hello, while porting the collada exporter code to 2.8 i've found out that the armature rest pose are not exported, instead the first frame is set as the rest pose which lead to incorrect results. Not sure if this is the same as this bug report, but here it is:
https://github.com/godotengine/collada-exporter/issues/99

**Comment by artellblender** [comment]
I've fixed it in a patch along the 2.8 update:
https://github.com/godotengine/collada-exporter/pull/100

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by hignatious** [comment]
@KoBeWi Hi I might have a small project that might be exhibiting the behaviour described here.

[Video](https://streamable.com/42fjir)

[collada-animation-bug.zip](https://github.com/godotengine/godot/files/5087439/collada-animation-bug.zip)

- The .blend file has the model and rig with some simple animations using a rigify human rig.
- in the zipped project there's a torso.dae file, double click and select 'New Inherited', go to the AnimationPlayer and you should see the head acting strangely in the point-rifle-01-loop animation as in the video above.
- The export_dae.py file is included in the zip because when trying to use the better collida exporter in Blender 2.83, I got a TypeError on line 642 due to too many function parameters in the mesh.update() method, so I changed it locally to remove one of the function parameters at random and it seemed to work again.

Not sure if this is exactly the same bug as described above but I found this thread while trying to find a solution so I thought I might as well post what I have.

**Comment by aaronfranke** [comment]
Can anyone reproduce this issue in a Godot 4.x version, such as Godot 4.3?

Does this issue occur if you export a glTF (.glb or .gltf) file from Blender instead of exporting a Collada (.dae) file? The Collada/DAE importer is not being actively maintained anymore, in favor of glTF.

**Comment by dodgyville** [comment]
Closing this as I doubt it is relevant anymore after all these years. Godot gets better every release!
