### ISSUE TITLE
VideoPlayer `set_stream_position()` doesn't work (seeking is not implemented)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#14430]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 16.04, Godot 3.0 beta 1

**Steps to reproduce:**
set_stream_position(20.0)

**Comment by akien-mga** [comment]
What kind of VideoStream are you playing? This bug report doesn't provide enough information, please try to be more specific.

**Comment by akien-mga** [comment]
- `VideoPlayer::set_stream_position` calls `VideoStreamPlayback::seek`: https://github.com/godotengine/godot/blob/86ed07c/scene/gui/video_player.cpp#L378
- It's a virtual method which has to be defined in each `VideoStreamPlayback` implementation: https://github.com/godotengine/godot/blob/03a0805/scene/resources/video_stream.h#L59
- We currently support Theora and WebM, both of which have a non-implemented `seek` method. Implementing it for both formats should solve this issue.
  * https://github.com/godotengine/godot/blob/3edd3cd/modules/theora/video_stream_theora.cpp#L636-L639
  * https://github.com/godotengine/godot/blob/13c2ff9/modules/webm/video_stream_webm.cpp#L222-L225

**Comment by DimaKiva** [comment]
Example
https://github.com/godotengine/godot/files/1503680/Bug.video.zip

**Comment by hungrymonkey** [comment]
i am just looking around to see how to add seek to ogg.

looks pretty complicated

http://blog.pearce.org.nz/2009/05/video-seeking-improvements.html

i am debating whether or not to try to fix it since i kinda want to understand how ogg works

**Comment by blurymind** [comment]
@hungrymonkey would it be easier to implement for webm?

**Comment by hungrymonkey** [comment]
@blurymind  probably somewhat the same difficulty.

you have to seek to find keyframes. The code doesnt really separate grabbing frames and finding the keyframe.

**Comment by Galileo53** [comment]
I would like to give this problem a push.
It would be really great if the seek function could be implemented.
Godot 3.1 ?

**Comment by zszen** [comment]
godot 3.1.1 same bug

**Comment by hungrymonkey** [comment]
https://github.com/godotengine/godot/tree/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/thirdparty/libsimplewebm

I just realize the libsimplewebm does not have seek support.

**Comment by hungrymonkey** [comment]
I do not think libsimplewebm supports seeking.

**Comment by hungrymonkey** [comment]
@akien-mga   I am attempting to implement ogg theora seek support but I do not understand why the video just waits for the full seek as if it is playing normally.
https://github.com/hungrymonkey/godot/tree/seek_theora
Can somebody tell me why?

**Comment by hungrymonkey** [comment]
I never realize force pushing would lead to such spam. Opps.

**Comment by hungrymonkey** [comment]
Should we close this bug or mark it as fixed in godot 3.2?
https://github.com/godotengine/godot/commit/9b8c355eab9b0b4ab1597efac2b424fbaf24ff1f
 VideoStreamGDNative works.

**Comment by CrimsonZA** [comment]
set_stream_position method is still not functioning in Godot 3.2 beta 4

**Comment by hungrymonkey** [comment]
@CrimsonZA  Godot already have a ffmpeg decoder for all codecs
https://github.com/kidrigger/godot-videodecoder

**Comment by CrimsonZA** [comment]
seems like Godot isn't ready to play video on Android, at least not on an Oculus Go, definitely not for immersive vide using the built in vide player node or godot-videodecoder

**Comment by hungrymonkey** [comment]
@CrimsonZA  You can try my seek theora branch which might end up in Godot 4.0. You have to compile in support for it.

**Comment by arsen-ch** [comment]
> @CrimsonZA Godot already have a ffmpeg decoder for all codecs
> https://github.com/kidrigger/godot-videodecoder
Does it support seek function?

**Comment by hungrymonkey** [comment]
@arsen-ch Do you trust the code works? https://github.com/kidrigger/godot-videodecoder/blob/master/src/gdnative_videodecoder.c#L693

**Comment by heyimyunyl** [comment]
Will this ever be implemented?

**Comment by hungrymonkey** [comment]
https://github.com/kidrigger/godot-videodecoder/blob/master/src/gdnative_videodecoder.c#L1083

@heyimyunyl  Upstream official position is to use kidrigger's gdnative plugin. I made an ogg-theora seek implementation but upstream broke a few things within their ogg theora so I cant commit it.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2945, as feature proposals are now tracked on the Godot proposals repository.

**Comment by John-Gdi** [comment]
see #57744

**Comment by golddotasksquestions** [comment]
For those interested, there is a PR for webm seek() support: https://github.com/godotengine/godot/pull/57744
