### ISSUE TITLE
Snapping doesnt work after rotate node

### ISSUE THREAD

**Issue by marchm3** [godotengine/godot#14496]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Arch Linux, Godot 3 beta

**Issue description:**

Snapping doesnt work after rotate node.
It works in Godot 2.1

**Steps to reproduce:**
Just create Node2D and rotate.

**Link to minimal example project:**
Just create new project.

**Comment by akien-mga** [comment]
cc @groud

**Comment by homer666** [comment]
Yeah, can confirm. Here's some footage: https://streamable.com/fd33r

**Comment by marchm3** [comment]
Final 3.0 and this critical bug still exists...

**Comment by akien-mga** [comment]
> Final 3.0 and this critical bug still exists...

And thousands of other more critical bugs have been fixed. Can't satisfy everyone I guess, but feel free to provide a fix.

**Comment by groud** [comment]
This can probably be closed now.

**Comment by broccoligamedev** [comment]
I'm still getting this behaviour. Is there an open issue for this bug?

**Comment by BlueNoise** [comment]
Can confirm too.

**Comment by groud** [comment]
> Can confirm too.

I saw the mail about the problem not solved. Are you on master?
I cannot reproduce the bug on my side, snapping works with rotated nodes.

**Comment by groud** [comment]
Alright then it's normal, it's fixed only on master.

**Comment by BlueNoise** [comment]
Ok nice thank you. Will those changes be integrated soon in the binary release?
________________________________

**Comment by groud** [comment]
In 3.1
