### ISSUE TITLE
Scrolling on touch pad does not work

### ISSUE THREAD

**Issue by Waasha** [godotengine/godot#14689]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win10 64bit, Notebook Lenovo E31, Godot 3 Beta 1

**Issue description:**
If I try to scroll anywhere in the interface (but it's the most painful in the script editor)  on the notebook's touch pad, it doesn't work. Scrolling with mouse wheel works normally. I thought it's the same "system signal"? Maybe I was wrong :)

**Steps to reproduce:**
Try to scroll in the inspector window or write a vertically long script and try to scroll down or up.

**Link to minimal example project:**

**Comment by eon-s** [comment]
Works fine on a HP Pavillion with Ubuntu, I cannot make the scroll to work on windows at all in this notebook so I can't test Godot.

In your case, scroll works on every program? (like games, java, flash  or html5 programs, not only pure windows software).

**Comment by pwab** [comment]
Works fine on a XMG A501 (synaptics) with Win7 x64. (Godot 3 beta1)

**Comment by eon-s** [comment]
Fixed my touchpad scroll on Windows 10 and works fine with Godot (docs, viewport, script editor).

**Comment by Calinou** [comment]
@Waasha Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
