### ISSUE TITLE
BakedLightmap in RayTrace mode does not create emission lighting.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#14686]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Manjaro 64bit, Godot - Master build, NVidia GT540M

**Issue description:**

BakedLightmap in RayTrace mode does not create emission lighting.
![bake_raytrace_emmision](https://user-images.githubusercontent.com/13662414/34029007-d26593c8-e16e-11e7-88b8-1e6f8f05629a.png)

**Steps to reproduce:**
Bake with only emission lights and set the mode to RayTrace.

**Link to minimal example project:**
[Bake_GI_Probe_Problems.zip](https://github.com/godotengine/godot/files/1561722/Bake_GI_Probe_Problems.zip)

Test tscn is test_Bake_raytrace_emmision.tscn

**Comment by kakoeimon** [comment]
Emission still not created. Emission exists for dynamic objects but it does not "paint" the baked objects.

**Comment by reduz** [comment]
Sorry, I made a mistake, mixed up the commits. Please try again.

**Comment by kakoeimon** [comment]
Yes, now it works!

**Comment by kakoeimon** [comment]
Here a screenshot
![bake_raytrace_emmision_2 png](https://user-images.githubusercontent.com/13662414/34167300-04d5bb7a-e4ea-11e7-8852-9d01839d9934.png)
By the way, we have the same problem as we have with VocelTrace emissions.
https://github.com/godotengine/godot/issues/14685

**Comment by reduz** [comment]
A few questions:

1) Are normals correct or exist in there?
2) Are you using mirrored meshes? (scale -1 in one of the axes)

**Comment by kakoeimon** [comment]
1) I do not know. Isn't this vissible at back face culling?
2) No mirror.

**Comment by reduz** [comment]
i will check for determinant < 0 and flip normals in the baking, that's as
much as i can think.

**Comment by reduz** [comment]
please try again

**Comment by kakoeimon** [comment]
VoxelTrace seems better, but it is again a little bit to the left (our view) again.
![1](https://user-images.githubusercontent.com/13662414/34172252-16eaa25c-e4fa-11e7-9184-0300f8d83a8f.png)

RayTrace looks the same
![2](https://user-images.githubusercontent.com/13662414/34172335-5b396920-e4fa-11e7-9e9f-637ca838b12e.png)

**Comment by reduz** [comment]
please make a small scene where I can test raytrace on this

**Comment by kakoeimon** [comment]
[bake_test.zip](https://github.com/godotengine/godot/files/1572916/bake_test.zip)

Strange results I am getting with raytrace.... Triangles are visible.

**Comment by reduz** [comment]
That is expected due to the post process blur used in raytracer (maybe it should be configurable, or somehow account for neighbour pixels), and the fact the unwrapper we are using does not seem to like that geometry very much (will eventually try to find a better one).

In any case, that is not a bug. The one in the screenshot you posted above is, so a testcase like that would be appreciated.

**Comment by kakoeimon** [comment]
For the screenshots I used the example project I attached to this issue.
You can find it at the first post. Bake_GI_Probe_Problems.zip
Hope it helps.

**Comment by reduz** [comment]
Also just a hint, the unwrapper is not able to join the triangles because the mesh is non manifold (the edges on top of the box are shared by more than 2 primitives. This produces the seam when bluring, and this is why similar scenes I used to test exhibited no problem.

For best result when using lightmappers, always make sure that geometry is manifold (one edge per two triangles).  Of course I understand this may not always be possible.

**Comment by reduz** [comment]
Adding to that, while it does not solve the problem, using more texture resolution (smaller texel size), also copes with the problem better:

![image](https://user-images.githubusercontent.com/6265307/34175528-733d33ae-e4db-11e7-8d67-8a0c039f0d01.png)

**Comment by reduz** [comment]
I think the problem in RayTrace should be fixed now

**Comment by kakoeimon** [comment]
Yes looks better now. Still not balanced but diferences are smaller.
![3](https://user-images.githubusercontent.com/13662414/34177241-9aa5c4da-e50b-11e7-8f53-014a4fc0c84c.png)
