### ISSUE TITLE
Proximity fade with depth mode as opaque pre-pass is broken

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#14759]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/f1683a290b7261e9bb099aa8f4548809218b31b7 Windows 10 Nvidia  GTX 1070

**Issue description:**

![https://i.imgur.com/axVmAwi.gifv](https://i.imgur.com/axVmAwi.gif)

It flips from white to black each frame

**Steps to reproduce:**
1. Open the example

**Link to minimal example project:**

[proximity_fade.zip](https://github.com/godotengine/godot/files/1565209/proximity_fade.zip)

**Comment by reduz** [comment]
Proximty fade always implies the object is transparent, so it will not
really work in that mode.

**Comment by mrcdk** [comment]
I was under the impression that opaque pre-pass was the mode for _transparent_ objects to cast shadows but I guess I was wrong.

Either way, this is still a bug that should be fixed somehow.

**Comment by reduz** [comment]
It may work, but the shadow will disappear as soon as it fades..

**Comment by mrcdk** [comment]
It actually shows a shadow if it moves while running, if it doesn't it doesn't show a shadow (although the shadow length is somewhat related to the viewport size? )

![https://i.imgur.com/VaQdWF9.gifv](https://i.imgur.com/VaQdWF9.gif)

![https://i.imgur.com/Tf3rLl9.gifv](https://i.imgur.com/Tf3rLl9.gif)

**Comment by reduz** [comment]
I think the glitches are the result of a problem that, if I fix, fails on
some old buggy amd mesa drivers..

Not sure what to do about it

**Comment by vonflyhighace2** [comment]
I say fix the issues pertaining to the engine. leave external issues for others to notice and ask for a potential fix if one is even warranted.

**Comment by reduz** [comment]
Can you try again? this may have been fixed now

**Comment by mrcdk** [comment]
Nope, still happening at commit https://github.com/godotengine/godot/commit/50b975548dcd65a9506e7fb449d40404320c0983

![https://i.imgur.com/Doj93y4.gifv](https://i.imgur.com/Doj93y4.gif)
