### ISSUE TITLE
md5 of imported source is in a wrong place

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#14858]
**Godot version:**
Godot 3.0 b08735f20987a6188fd54c5e2dcd072dc316b413

**OS/device including version:**
any OS

**Issue description:**
Currently `source_md5` is located within the .import file near the source file. So when you change the source, reimport and commit the files, it doesn't get reimported for other people who pull the changes. Shouldn't it be located within the .import folder, associated with the imported file?

**Comment by vnen** [comment]
Yeah, I think the MD5 shouldn't be commited, then it doesn't belong to the `*.import` files.

**Comment by reduz** [comment]
Ah, I see. Technically you can commit the .import folder now and it should
work fine. That said, probably should add the MD5 of the imported files to
the check..

**Comment by NathanWarden** [comment]
I agree, the md5 should be somewhere in the .import folder, not the *.import file :)

**Comment by vnen** [comment]
BTW, while you *could* commit the `.import` folder, I don't think you *should*. Git isn't helpful for binary files, so adding copies of it in the same repository is just a waste of space. It's more practical to let each contributor reimport stuff they need.

**Comment by NathanWarden** [comment]
It could probably just be another path added to the [remap] block?

For instance, I have an image with an import file with:

```
path.s3tc="res://.import/grid_default.png-d70f242c379990a079b4f22ba9d11a2e.s3tc.stex"
path.etc2="res://.import/grid_default.png-d70f242c379990a079b4f22ba9d11a2e.etc2.stex"
```

Just add another:

```
path.md5="res://.import/grid_default.png-d70f242c379990a079b4f22ba9d11a2e.md5"

or

path.hash="res://.import/grid_default.png-d70f242c379990a079b4f22ba9d11a2e.hash"
```

It would work the same as the current md5 in the [deps] block, but it wouldn't be committed to version control. Therefore, anyone who's computer needs to update the file will.

**Comment by reduz** [comment]
@NathanWarden It's simply easier to keep an md5 of the exported file. The editor filesystem keeps a cache of all modification dates anyway, so this check will only be performed if the date of the source file changes.

**Comment by reduz** [comment]
The problem right now is that Godot _is_ detecting that source file changes and goes and checks MD5 as it should, but it does not check the MD5 of the imported files, which it should.

**Comment by Zireael07** [comment]
I committed the .import folder too, and now everytime I open the editor it wants to reimport some of the files (namely the .obj resources). The only thing that changes is the md5 in the .import file, though.

**Comment by NathanWarden** [comment]
@reduz I see what you're saying. That would certainly fix the problem :)

**Comment by endragor** [comment]
@reduz if you check stored md5 against imported file, the check will always yield that it is up to date (since *.import file would keep md5 of the last imported file), even if the source actually changed.  So checking against imported file seems useless, unless I'm missing something.

**Comment by reduz** [comment]
@endragor Current check is against the source file, what I want to do is check against source AND imported file.

**Comment by akien-mga** [comment]
We should not forget to fix this for 3.0 RC1.

**Comment by endragor** [comment]
This is already fixed by 988d29bdd8f1d6fc74280cceb76a8b4edb54138d, although the implementation caused #15316 to be a problem. But closing this one anyway.

**Comment by akien-mga** [comment]
Are you sure it's fixed? Maybe I misunderstood what this issue was about, but I still get such diffs in the demos:
```
diff --git a/3d/kinematic_character/white_wood.png.import b/3d/kinematic_character/white_wood.png.import
index e893dd2..8103b42 100644
--- a/3d/kinematic_character/white_wood.png.import
+++ b/3d/kinematic_character/white_wood.png.import
@@ -5,6 +5,14 @@ type="StreamTexture"
 path.s3tc="res://.import/white_wood.png-6895acd60ce97b4315494d2be377c357.s3tc.stex"
 path.etc2="res://.import/white_wood.png-6895acd60ce97b4315494d2be377c357.etc2.stex"
 
+[deps]
+
+source_file="res://white_wood.png"
+source_md5="4565f03f9b3e5ea8bbd492559e733a35"
+
+dest_files=[ "res://.import/white_wood.png-6895acd60ce97b4315494d2be377c357.s3tc.stex", "res://.import/white_wood.png-6895acd60ce97b4315494d2be377c357.etc2.stex" ]
+dest_md5="6e02a3d6e2e6c5c82a8a85db38bbb708"
+
 [params]
 
 compress/mode=2
```
