### ISSUE TITLE
Docs display error if xml has parentheses after brackets

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#15009]
**Godot version:**

Master

**OS/device including version:**

Antergos x86_64

**Issue description:**

XML:
https://github.com/godotengine/godot/blob/8b0ad17b760b6cc803edc815fe65f8de1d92bf74/doc/classes/ProjectSettings.xml#L20

Docs:
![image](https://user-images.githubusercontent.com/26753932/34328393-e3819bda-e910-11e7-91ac-0d3a5484b76e.png)

This line probably needs editing so that it escapes for parentheses too:
https://github.com/godotengine/godot/blob/8b0ad17b760b6cc803edc815fe65f8de1d92bf74/doc/tools/makerst.py#L264

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by Noshyaar** [comment]
cc: @akien-mga

**Comment by akien-mga** [comment]
Well that description is a bit weird, it should be fixed in the XML :P
But yeah, the parser should be fixed too.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by robfram** [comment]
Is this solved at least in cbb4fe45d039ad16abe992d2212011c260d6ac17?

I can't reproduce it using the XML provided by @Noshyaar https://github.com/godotengine/godot/blob/8b0ad17b760b6cc803edc815fe65f8de1d92bf74/doc/classes/ProjectSettings.xml#L20.

The resulting reStructuredText file is show as this in [http://rst.ninjs.org](http://rst.ninjs.org)
![screenshot-2018-3-4 projectsettings - online restructuredtext editor](https://user-images.githubusercontent.com/35065795/36945215-11701c62-1fab-11e8-8a63-fba9e27b5d95.png)

Maybe the problem is not the generation of the file but the later parsing?

**Comment by reduz** [comment]
Can anyone re check?

**Comment by Noshyaar** [comment]
Still reproducible, see http://docs.godotengine.org/en/latest/classes/class_projectsettings.html#member-function-description

**Comment by akien-mga** [comment]
That's easy to fix (and the faulty description should really be rewritten, it doesn't comply with our style guides), but definitely not high priority for 3.1.

**Comment by JoaoAlvaroFerreira** [comment]
Hi, I'm going to try and give this a fix

**Comment by akien-mga** [comment]
Fixed by #24266.
