### ISSUE TITLE
Camera2D: update not in sync

### ISSUE THREAD

**Issue by poke1024** [godotengine/godot#15044]
**Godot version:**
Godot 3.0 beta 2

**OS/device including version:**
macOS 10.13.2

**Issue description:**
I came across this while using `Camera2D` on a simple, constantly moving object, and saw this:

![flickering](https://user-images.githubusercontent.com/11859538/34340771-9bf1dae4-e98a-11e7-8153-494bf775a963.gif)

Upon further investigation, it turns out that `Camera2D` updates its scroll position during `NOTIFICATION_PHYSICS_PROCESS` and is sometimes randomly called out of order (i.e. sometimes the object's `_process` comes before the camera's physics process, but sometimes - rarely - it is the other way round, resulting in flickering).

Using the attached sample project you see a sudden random flipping of the order of execution of the process calls to camera and the player object resulting in the flickering (the cam position changes by 100 by default, but then it changes by 0 and updates in the next frame by 200 due to the missed event):

```
camera physics process False
100
camera physics process False
100
camera physics process False
100
camera physics process False
camera physics process False
100
0
camera physics process False
200
camera physics process False
100
camera physics process False
100
``` 

Now, if this is a user error (expecting the node tree notification order/camera update call to be stable), I think we should fix the `Camera2D` API to update its scroll value upon any transformation change, since this is an annoying effect that happens randomly.

Just wanting to assert that this flipping of order is not something more fundamentally fishy here (I saw that the node tree's callbacks are sorted and should thus always be in order AFAIK).

**Steps to reproduce:**
Run sample project:

[Camera2D.zip](https://github.com/godotengine/godot/files/1585944/Camera2D.zip)

**Minimal reproduction project:**
See sample project

**Comment by poke1024** [comment]
Found the problem. `_process` is called from the idle process, while `Camera2D`'s update is in the physics process. Now, sometimes the idle process gets called twice in a row, with no physics process between:

```
entering physics_process 2
inspecting root
notifying root
inspecting Camera2D
notifying Camera2D
camera physics process False
leaving
entering idle_process 1
inspecting Sprite
notifying Sprite
100
leaving
entering idle_process 1
inspecting Sprite
notifying Sprite
0
leaving
```

**Comment by groud** [comment]
Everything you describe is normal. The physics process is for handling physics while process is for all other things, thus executed in the idle time (whenever the engine can). The order of the calls is not guaranteed. Usually the physics is executed 20 times per second while the process is at 60 times per second. 

So if you want to move something you have to do it in the _physics_process function, and not the _physics one.

**Comment by groud** [comment]
https://godotengine.org/qa/4309/whats-the-difference-between-_process-and-_fixed process

**Comment by eon-s** [comment]
I can't find it but I'm sure there was an issue or pr for adding idle process as an option option on cameras.

And moving non physics nodes on idle is ok and camera should support that.

**Comment by Dillybob1992** [comment]
@eon-s Yeah, I suggested this feature as an update mode property for `Camera2D`, so we can utilize the camera's built in smoothing, drag, etc.

@groud Is correct, however I think more people with higher monitor rates are starting to use Godot and will end up with this because they'll naturally use the camera node, instead of updating via _process with `canvas_transform`

**Comment by poke1024** [comment]
My view is that a lot of people will run into this and will spend a lot of time debugging their own code, as this happens randomly and first looks like some calculation glitch or performance problem. Also, I think for 2D games, it's very common to not use any discrete physics step at all, so the natural thing is to use `_process` unless there is a big warning disclaimer in Godot that you must not.

**Comment by groud** [comment]
I'm probably wrong on this one. Forget my comment ^^.

**Comment by groud** [comment]
I'm probably wrong on this one. Forget my comment ^^.

**Comment by akien-mga** [comment]
Fixed by #15060.

**Comment by behelit2** [comment]
I know this issue is closed... But I'm still experiencing it with the latest version of Godot with smoothing enabled. I don't understand why this is happening, smoothing was 100% rock solid for me in Godot 2. It's not constant like in the example, but rather it happens randomly. It's just annoying enough to be a deal breaker, I'm about to switch back to Godot 2.1.4

**Comment by eon-s** [comment]
@behelit2 can you try a master build to see if solves your problem? the fix is not on 3.0

**Comment by akien-mga** [comment]
The fix is in 3.0 already. Could you open a new issue about it?

**Comment by eon-s** [comment]
Is on 3.0.2? then I will check some issues I think are related to this.

**Comment by akien-mga** [comment]
It's in 3.0-stable even, it was merged in January.

**Comment by eon-s** [comment]
I may be confusing it with another PR then :sweat_smile:

**Comment by behelit2** [comment]
Should I open a new issue with an example?

**Comment by akien-mga** [comment]
That would be great yes. You can refer to this issue in the new one, but as the original bug is supposed to be fixed in 3.0, it's better to keep track of potential regressions or similar bugs in a new bug report.

**Comment by behelit2** [comment]
Okay, I created a new issue! [#17823](https://github.com/godotengine/godot/issues/17823)
