### ISSUE TITLE
Godot 3.0 Beta 1 and Beta 2 keeps crashing!

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#15142]
**Godot version:**
3.0 Beta 2

**OS/device including version:**
Windows 10

**Issue description:**
Plenty of times when I keep adding a new directory or update a file within the project folder outside of Godot, Godot will freeze up and crash.

**Comment by poke1024** [comment]
Can you provide a crash log or does it just freeze?

**Comment by Raj2032** [comment]
It just freezes up and I get a Windows message that states whether you want
to close or debug the program.

**Comment by Calinou** [comment]
What's your graphics card model? It needs to support OpenGL 3.3 at least. Supported GPUs include (at least):

- NVIDIA GeForce 400 series or newer
- AMD Radeon HD 6900 series or newer
- Intel Ivy Bridge or newer

Older GPUs may work, but are not as thoroughly tested.

**Comment by Raj2032** [comment]
I don't think I ever got this issue with Godot 2 series.

**Comment by capnm** [comment]
> Plenty of times when I keep adding a new directory or update a file within the project folder outside of Godot, Godot will freeze up and crash.

That should already be fixed (I guess it didn't make it in the beta): https://github.com/godotengine/godot/issues/13976

**Comment by akien-mga** [comment]
Many crashes have been fixed since Beta 2, it should be better in RC 1. Please test again when it's released, and if you can still make it crash, open one issue per crash with specific reproduction steps as asked.

**Comment by Raj2032** [comment]
I have been using Beta 2 and it still continues to crash, just like in Beta
1 and Alpha, and it just happens randomly when you simply add a directory
or make changes to the sub directories of where the project is set.
