### ISSUE TITLE
Wait cursor being displayed when changing mouse mode from CAPTURED to VISIBLE

### ISSUE THREAD

**Issue by stwupton** [godotengine/godot#15678]
**Godot version:**

Master 702e28f26

**OS/device including version:**

Windows 10

**Issue description:**

When switching the mouse mode from `MOUSE_MODE_CAPTURED` to `MOUSE_MODE_VISIBLE` with a left button mouse click, the cursor shows the "wait" icon (blue spinning circle on Windows) instead of the "arrow". Even when trying to set the cursor with `mouse_default_cursor_shape = Control.CURSOR_ARROW`, it still displays the "wait" cursor. This seems to only be a problem with the "arrow" cursor as all the other cursors show fine, and if you leave the game window while the mouse mode is `MOUSE_MODE_VISIBLE` the cursor will be an "arrow" and work as expected from then on.

**Minimal reproduction project:**

[minimal.zip](https://github.com/godotengine/godot/files/1628651/minimal.zip)

**Comment by guilhermefelipecgs** [comment]
I think I already fixed that, can you test again?

**Comment by stwupton** [comment]
@guilhermefelipecgs Tested it on master 9a5950ace52c4ebb575d452d6451259d6f2323e3 and it's still occurring.

**Comment by guilhermefelipecgs** [comment]
@stwupton Thanks, I submited a new pull request to fix that.
