### ISSUE TITLE
Using Viewport Texture causes "node not found" error

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#16067]
**Godot version:**
v3.0.rc3.official

**OS/device including version:**
Ubuntu 16.04

**Issue description:**
I'm using the canvas 2D drawing functions to create a texture and then using that texture on other nodes. Instancing a 2D scene that uses local viewport textures causes runtime errors in the Output and Debugger panes but the project still runs correctly. The errors are:

`Node not found: Viewport`
`ViewportTexture: Path to node is invalid`

The errors show in the Output pane when the parent scene is loaded and in the Debugger when the project runs. It makes testing tedious because I never know if the error in the Debugger is real or not.

I'm not sure if my node setup is correct for what I'm trying to accomplish but it works.

**Steps to reproduce:**
I've attached a project that repros the problem.

- Open the project, open the main scene, and you should see the errors in the Output pane
- Run the project and you should see the errors in the Debugger pane

**Minimal reproduction project:**
[node-not-found-example.zip](https://github.com/godotengine/godot/files/1665135/node-not-found-example.zip)

**Comment by jotson** [comment]
Just discovered that if the Viewport node is moved above the nodes that use its texture then the issue goes away. Not sure if it's a bug or not.

**Comment by Cygon** [comment]
This issue is driving me nuts, too.

I have two viewports in my game that I use to display 3D UI:

![ViewportTexture at creation time](https://i.imgur.com/gKgr5md.png)

When I close Godot and later load the scene again, I get this:

![ViewportTexture after saving and loading](https://i.imgur.com/c5SNt6m.png)

To fix it, I remove a character from the ViewportPath field, hit enter, then add the character back and hit enter.

Using the 'Assign' menu also results in Bug #16035:

![Weird path](https://i.imgur.com/C1ssOUM.png)

**Comment by Cygon** [comment]
After discussing this on Discord, @bojidar-bg recommended to set the ViewportTexture and SpatialMaterial to 'Local to Scene' (as mentioned in related issue #7998) and this seems to avoid the issue.

**Comment by bojidar-bg** [comment]
Just note that you might have to set any Materials, etc. in which it is used to 'Local to Scene' as well.

**Comment by jotson** [comment]
Setting Local to Scene doesn't prevent the issue for me. Only moving the Viewport node above the nodes that use its texture avoids it for me.

**Comment by Keetz** [comment]
I have encountered similar errors.
When a viewport is added to a scene, the scene file gets a _viewport_path_
`viewport_path = NodePath("Path/To/The/Viewport")`
This _viewport_path_ is "set in stone". It doesn't update if you for example rename a node in that path, or moves the viewport in the scene tree.

And because we can change the path as we want in the editor but the actual path in the scene file doesn't change, we get:
```
Node not found: Viewport
ViewportTexture: Path to node is invalid
```

**Comment by volzhs** [comment]
I'm facing same issue.

![screenshot from 2018-02-26 00-52-36](https://user-images.githubusercontent.com/8281454/36643517-b22676b8-1a8f-11e8-9664-1c755a99a4ed.png)
pretty simple scene setup.

[Sprite3D viewport texture.zip](https://github.com/godotengine/godot/files/1756355/Sprite3D.viewport.texture.zip)

**Comment by volzhs** [comment]
I found that error is gone if I moved `Viewport` node to above `Sprite3D` node which uses `ViewportTexture`

**Comment by henriiquecampos** [comment]
Facing the same issue, but with normal `Sprite` and the solution (move the `Viewport` above the ) worked too.

I think this is related to the instancing order, the Sprite resource, `ViewportTexture`, is trying to use a node and may be instantiated yet, that maybe why it points this error just once. I also figured out that manually setting the `ViewportTexture.viewport_path` through a script makes nothing but display this error:

```
0:00:01:0841 - Condition ' !vp ' is true. returned: Size2()
----------
Type:Error
Description: 
Time: 0:00:01:0841
C Error: Condition ' !vp ' is true. returned: Size2()
C Source: scene\main\viewport.cpp:106
C Function: ViewportTexture::get_size
```

If you try to save a `ViewportTexture` in disk and set it on the `_ready` callback, you will get the above error, but you you set, the same `.tres` `ViewportTexture` saved in disk in the editor, you won't get this error.

Also, I think this error/logic messes with the root `Viewport` as you can see in an issue reported to a game I made (https://github.com/pigdevstudio/bard-lesson/issues/9)

**Comment by reduz** [comment]
This is an usability problem, I fixed it earlier today in 7c00f0599e56137523f2ec6669b980d11423e9a0 so it should be more obvious when you are doing something wrong. Closing.

**Comment by creikey** [comment]
I am still having this issue even if the viewport texture resource is local to scene on 01e24447a

**Comment by dmaz** [comment]
this issue still occurs on 3.2.3 stable.... the work around is still to move the viewport above the textures

**Comment by Calinou** [comment]
@dmaz Please continue the discussion in https://github.com/godotengine/godot/issues/27790.

**Comment by WhalesState** [comment]
the issue still exists in 3.4 stable release , by default the viewport texture is local to scene, only moving the viewport scene above the 3d sprite have fixed the issue for me, i was having like 140 errors of node not found "Sprite3D/Viewport".

**Comment by ArcTropics** [comment]
I was facing the same issue. I tried everything in Godot 3.4 and the Viewport issue just doesn't resolve. I tried the suggestion where I make the Viewport the parent of the Sprite3D. But that also had issues. It stopped showing me the viewport contents if I was reusing the "Scene with the Viewport" in other nested scenes. Still don't know how to fix it.

**Comment by Calinou** [comment]
Reopening, as https://github.com/godotengine/godot/pull/52365 does not seem to fully resolve this issue. cc @jitspoe

**Comment by jitspoe** [comment]
Ah, bummer.  Unfortunately, I don't have time to dig into this right now.

**Comment by gustavopergola** [comment]
> I was facing the same issue. I tried everything in Godot 3.4 and the Viewport issue just doesn't resolve. I tried the suggestion where I make the Viewport the parent of the Sprite3D. But that also had issues. It stopped showing me the viewport contents if I was reusing the "Scene with the Viewport" in other nested scenes. Still don't know how to fix it.

I managed to make the error disappear it not by making `Viewport` a parent of `Sprite3D`, but by making it a sibling that comes before it.
One thing I was missing though is that you have to reassign ViewPortTexture on `Sprite3D` after the change. 

I don't really know why, I'm kinda new on Godot 😄 
But it did make the errors disappear

**Comment by shafnaz** [comment]
> > I was facing the same issue. I tried everything in Godot 3.4 and the Viewport issue just doesn't resolve. I tried the suggestion where I make the Viewport the parent of the Sprite3D. But that also had issues. It stopped showing me the viewport contents if I was reusing the "Scene with the Viewport" in other nested scenes. Still don't know how to fix it.
> 
> I managed to make the error disappear not by making `Viewport` a parent of `Sprite3D`, but by making `Viewport` a sibling that comes before `Sprite3D` on scene tree. One thing I was missing though is that you have to reassign ViewPortTexture on `Sprite3D` after the change.
> 
> I don't really know why, I'm kinda new on Godot 😄 But it did make the errors disappear

True. Just place the Viewport node above the mesh that will be using it

**Comment by Nekuromu** [comment]
I also ran into this issue making 3D text, some errors about node path not found. I tried creating the ViewportTexture via code and pulling the viewport path after the scene was created.

While printing this value did show an accurate node path that was not the case with the debug output; The debug output was filled with many segments along the path with @@5\@83\ for about double the actual node path size.

I tried a few of the solutions here, but didn't have much luck up until I tried this hierarchy.

![image](https://user-images.githubusercontent.com/30809120/180622456-31fd00e1-92da-4e71-b8e1-c58731d24c60.png)

> I managed to make the error disappear not by making `Viewport` a parent of `Sprite3D`, but by making `Viewport` a sibling that comes before `Sprite3D` on scene tree. One thing I was missing though is that you have to reassign ViewPortTexture on `Sprite3D` after the change.

This looks like it works, and doesn't create errors. However I am not altering paths at all. This alignment of nodes seems to do the trick on it's own in v3.4.4.stable.official [419e713a2]

**Comment by Calinou** [comment]
@Nekuromu [3.5.rc7](https://godotengine.org/article/release-candidate-godot-3-5-rc-7) has a Label3D node, so you don't need to use a Viewport anymore for that.

**Comment by Nekuromu** [comment]
> @Nekuromu [3.5.rc7](https://godotengine.org/article/release-candidate-godot-3-5-rc-7) has a Label3D node, so you don't need to use a Viewport anymore for that. It should be safe to upgrade now, but make sure to backup your project files before just in case.

Good to know, I thought while I was researching 3D Text I saw doc pages related to "Label3D" but figured it was coming in 4.0 or some later release. I'll be sure to backup and move into 3.5.rc7 to check out Label3D. Thanks again!

**Comment by firebelley** [comment]
I am experiencing this issue on `3.5.1.stable.mono`. The suggestion to move the viewport above the Sprite that uses it did not work. I am working in 2D, here is my setup: 
![image](https://user-images.githubusercontent.com/4622925/199381091-9e4e8b0b-6116-4aef-952c-4de27b29b5af.png)

Here's some of the errors:
```
E 0:00:00.591   get_path: Cannot get path of node as it is not in a scene tree.
  <C++ Error>   Condition "!is_inside_tree()" is true. Returned: NodePath()
  <C++ Source>  scene/main/node.cpp:1780 @ get_path()
E 0:00:00.591   get_node: (Node not found: "" (relative to "").)
  <C++ Error>   Method failed. Returning: nullptr
  <C++ Source>  scene/main/node.cpp:1465 @ get_node()
E 0:00:00.591   setup_local_to_scene: ViewportTexture: Path to node is invalid.
  <C++ Error>   Condition "!vpn" is true.
  <C++ Source>  scene/main/viewport.cpp:70 @ setup_local_to_scene()
```

Interestingly the viewport still renders the contents to the texture as expected, so perhaps this is just a false error? These errors print ass soon as the scene is added to the SceneTree.

**Comment by gu-fan** [comment]
same as prev comment:
If you set viewport texture in editor it will show node not found.
If you set viewport by code, like 

var vwtex = ViewportTexture.new()
vwtex.viewport_path = NodePath('%OffViewport')

will show 


E 0:00:07.821   get_height: Viewport Texture must be set to use it.
  <C++ Error>   Condition "!vp" is true. Returned: 0
  <C++ Source>  scene/main/viewport.cpp:105 @ get_height()

**Comment by cameronsteele** [comment]
As gu-fan points out, you can work-around having to place the SubViewport above the node that needs the ViewportTexture if you set the texture in code using i.e.

```
func _ready():
    $Sprite3D.texture = $SubViewport.get_texture();
```

**Comment by isaaccp** [comment]
@gustavopergola when i do that, it somehow outputs a different error instead:
E 0:00:08:0528   highlight.gd:19 @ _init(): Condition "proxy.is_valid()" is true.
  <C++ Source>   scene\main\viewport.cpp:89 @ ViewportTexture::setup_local_to_scene()
 
This is mentioned in this bug https://github.com/godotengine/godot/issues/60350 too, which I think is a duplicate of this one.

**Comment by BluesM18A1** [comment]
> @gustavopergola when i do that, it somehow outputs a different error instead: E 0:00:08:0528 highlight.gd:19 @ _init(): Condition "proxy.is_valid()" is true. <C++ Source> scene\main\viewport.cpp:89 @ ViewportTexture::setup_local_to_scene()
> 
I am getting this sort of error message as well. What I have noticed is that the viewport texture seems to work fine when running the project in the editor, but on exported builds, the texture is garbled or pitch black depending on the graphics hardware I've tested on. Even if I made sure that the subviewport loads before my nodes using the texture in the hierarchy.

> As gu-fan points out, you can work-around having to place the SubViewport above the node that needs the ViewportTexture if you set the texture in code using i.e.
> 
> ```
> func _ready():
>     $Sprite3D.texture = $SubViewport.get_texture();
> ```

Doing this seems to get rid of the error message described above, but my ViewportTexture is still corrupted.

**Comment by Flynsarmy** [comment]
> As gu-fan points out, you can work-around having to place the SubViewport above the node that needs the ViewportTexture if you set the texture in code using i.e.
> 
> ```
> func _ready():
>     $Sprite3D.texture = $SubViewport.get_texture();
> ```

The unfortunate issue with this is that you no longer get to see the viewport in-editor. If I set the Sprite3D's texture in-editor I get to see what the viewport will show in-game but with the downside of the error in console:
![image](https://user-images.githubusercontent.com/334808/233552066-30ffb5ae-bfa0-4451-80e2-5d14614ef1c7.png)

If I clear out the Sprite3D's texture and just have it assigned in `_ready` no more error but now I don't see the viewport in-engine while developing.
![image](https://user-images.githubusercontent.com/334808/233552123-5bb2c9e1-657b-4e82-b23d-ece96c0daf2e.png)

Is there no way to get the best of both worlds?
