### ISSUE TITLE
CanvasItem.draw_polyline draws incorrect, distorted geometry

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#16466]
**Godot version:**
cbdd410

**Issue description:**
![image](https://user-images.githubusercontent.com/3036176/35912186-e56e36e6-0c0c-11e8-8b37-fc689e023f0a.png)

the problem is inside
https://github.com/godotengine/godot/blob/cbdd410a6f476503ee4bc27ac2f475a73960236d/servers/visual/visual_server_canvas.cpp#L464

**Minimal reproduction project:**
[PolylineBug.zip](https://github.com/godotengine/godot/files/1702711/PolylineBug.zip)

**Comment by Zylann** [comment]
It doesn't look like a bug, when you think about it. You would need to expand those corners so that the segment has the same thickness, however it can lead to infinitely sized turns in some cases.

It lool like `draw_polyline` is not using the algorithm used by the `Line2D` node, which is able to render this kind of line better IMO

**Comment by simonpuchert** [comment]
This is a fundamental problem of the idea used in the function ("replace every point by two points").

If there is a very small angle at some point, the replacement points either extend far into outer space or the lines attached to this corner are very thin. However, you can use three points (one for the inner corner, two for the outer almost-180°-"bend") to reduce these problems to sane levels.

After that, there might be some adjustments to make, depending on whether you want to keep the directions (in which case the original vertices might get cut off) or the points (in which case you have to move the above construction "outwards", changing the direction of the lines).

It's similar to planning a racetrack using the points as guidance for the straight segments vs. fitting a racetrack through the given points (or, Bézier curves vs. splines; in the sense that Bézier curves need not hit the intermediate points).

**Comment by Chaosus** [comment]
Yeah other method for smooth lines should be used.

**Comment by Zylann** [comment]
@Chaosus what do you mean? There is no fix planned? Should users just use `Line2D` to have better results?

**Comment by Chaosus** [comment]
Yeah, I suspect Line2D is better choise

**Comment by Zylann** [comment]
But it's not if you want custom draw (note that the Line2D node actually uses a LineBuilder, which can also be used as implementation for draw_polyline, not sure why it wasn't done)

**Comment by Chaosus** [comment]
Zylann, got it, should I reopen this ?

**Comment by Zylann** [comment]
Yeah, although it's possible to use LineBuilder with some predefined params to get a better looking line, I wonder why it wasn't used in the first place (`draw_polyline` was added long after `Line2D`)

**Comment by reduz** [comment]
May be improved in 3.2

**Comment by Spartan322** [comment]
Redirected from #34073 

**Godot version:**
Mono 3.2 Beta 2

**OS/device including version:**
Manjaro Arch Linux "Juhraya" 18.1.2

**Issue description:**
draw_polyline draws the start and end points wider then the rest of the points.
![](https://cdn.discordapp.com/attachments/342056330523049988/651299486462902272/unknown.png)
This is using the draw_polyline_color function but it results in the same shape
![image](https://user-images.githubusercontent.com/4315446/70025690-c5a79680-156b-11ea-8a6e-eb600fb0313e.png)

**Steps to reproduce:**
* Add a `_draw` override to a CanvasItem
* Add `draw_polyline([Vector2(), Vector2(0, 100), Vector2(100, 100), Vector2(100, 0), Vector2(-25, 0)], Color.white, 50, false)`
* Have the node draw either in editor or in game

**Minimal reproduction project:**
[polyline_issue_project.zip](https://github.com/godotengine/godot/files/3914928/polyline_issue_project.zip)

**Comment by Xrayez** [comment]
Wanted to open a bug report but seeing this, so attaching my own reproduction project.

GLES2, GLES3, Godot 3.2.4 beta.

### `draw_polyline` vs `draw_line`, width `3.0`

![Screenshot 2020-11-16 112005](https://user-images.githubusercontent.com/17108460/99234916-db09e500-27fd-11eb-8372-29b1e14e5fb9.png)

### `draw_polyline` vs `draw_line`, width `20.0`

![Screenshot 2020-11-16 112049](https://user-images.githubusercontent.com/17108460/99234928-dcd3a880-27fd-11eb-8b73-58d2872c6089.png)

So, currently `draw_polyline` is not useful to use in most cases (I'd expect it to work like `draw_line` at least), and I think `draw_line` is kind of expected to draw rectangles with `width > 5.0`, so indeed `Line2D` is superior out of them all, unfortunately I just cannot allow myself to use `Line2D` as a dependency of other similar class for line drawing.

**Minimal reproduction project:**
[draw_polyline_malformed.zip](https://github.com/godotengine/godot/files/5545294/draw_polyline_malformed.zip)

**Comment by Calinou** [comment]
This is fixed as of 4.0.rc2, closing.

![image](https://user-images.githubusercontent.com/180032/220203080-fd0e489d-f7ca-49fa-b32d-007d61f18ef6.png)

Updated MRP: [draw_polyline_malformed_1.zip](https://github.com/godotengine/godot/files/10787969/draw_polyline_malformed_1.zip)

**Comment by A404M** [comment]
The bug still exists
![Uploading Screenshot from 2023-12-28 02-52-11.png…]()

**Comment by A404M** [comment]
The bug still exists
![Screenshot](https://github.com/godotengine/godot/assets/59058087/1b3f12c3-6d27-478e-83e2-cddcfe2d3127)

**Comment by ComputerErika** [comment]
Yea this bug definitely still exists, Im using Godot 4.2.1-1

What I was doing:
I was playing around with drawing lines, and did an old thing I did way back with Python turtle, where I draw lines with points at random heights from evenly spaced points along the x axis

Anyways heres the screenshot, its really noticeable to me
![image](https://github.com/godotengine/godot/assets/42761313/73ea9f8f-f21e-4e08-8992-59e1970ceab6)

And also heres the code I was using for the screenshot (truncated to only the affecting code)
`var window = Vector2i(1280, 720)
var points: PackedVector2Array = []

func _ready():
	for i in range(64+1):
		points.append(Vector2(i*20, randi_range(0,720)))

func _draw():
	if points.size() >= 2:
		draw_polyline(points, Color.BLUE, 3, true)`

**Comment by enetheru** [comment]
I'm observing the same thing as @ComputerErika using 4.2.1

**Comment by Casums22** [comment]
I'm seeing this issue in v4.6.2 as well. You can reproduce it fairly easily by making a basic polygon shape but have some of the edges of your shape be a few pixels long like 2 or 3.
