### ISSUE TITLE
Tiles rendering odd with lines interfering:

### ISSUE THREAD

**Issue by WatIsDeze** [godotengine/godot#1682]
![screen shot 2015-04-13 at 16 10 48](https://cloud.githubusercontent.com/assets/10252874/7117323/329f4726-e1f8-11e4-999a-9cf269c5836e.png)
![screen shot 2015-04-13 at 16 13 15](https://cloud.githubusercontent.com/assets/10252874/7117322/32996f7c-e1f8-11e4-8975-39aa0858f525.png)
![screen shot 2015-04-13 at 16 14 18](https://cloud.githubusercontent.com/assets/10252874/7117328/353f3fae-e1f8-11e4-9777-179f649e7b62.png)

**Comment by reduz** [comment]
try disabling filter and mipmaps in the image loader (project settings ->
image loader)

**Comment by WatIsDeze** [comment]
![screen shot 2015-04-13 at 16 20 46](https://cloud.githubusercontent.com/assets/10252874/7117460/116c2f96-e1f9-11e4-8a8d-efe861394560.png)

**Comment by WatIsDeze** [comment]
They were off already. The is unrelated to either these. It may be worth noting that I have a drag value setup of 0.1 in my Camera2D for each direction.

Nonetheless, this seems like a typical texturing issue. Never had this myself with OpenGL programming. Only seen it with DirectX strangely enough.

**Comment by WatIsDeze** [comment]
Looking at the source code of scene/2d/tile_map.cpp I notice there is a variable, fp_adjust with a value of 0.01.

So what happens is, I notice it is adding this value to the position, size, and sometimes multiplying it by 2.

Not really sure what this is for, but it would make sense that this possibly is causing the lines? I'm not at home atm so I can't test it.

**Comment by reduz** [comment]
That is supposedly to avoid them due to numerical error..  Did you change
anything that created those lines?

**Comment by WatIsDeze** [comment]
Just got home, compiling as we speak. Will report back in a few ^^

**Comment by WatIsDeze** [comment]
Although it seems as if every tile is possibly drawn as a separate object, and somehow possibly stutters a bit while moving. I now am not suffering from bad rendering issues while moving around.

Have I confirmed the problem lies in those lines of code? I haven't done anything to add these lines myself. In fact, these are in the Git code as we speak:

https://github.com/okamstudio/godot/blob/master/scene/2d/tile_map.cpp#L341

**Comment by WatIsDeze** [comment]
@reduz I'm not really sure what this code was about, or what the point is of this 0.01. It's only going to give more imprecision, isn't casting to int a better idea? I'm kind of clueless what the point is about this :D

**Comment by WatIsDeze** [comment]
Also 0.1 is 1 tenth of a pixel, not? That's probably causing nasty rounding issues at times thus the light displays but no tile displays, hence the lines showing? Man I'm confused, sorry for the amount of comments.

**Comment by UsernameIsAReservedWord** [comment]
@WatIsDeze : have you try to enable the "use_pixel_snap" option into the Scene / Project Settings to see if it improve things ?

**Comment by UsernameIsAReservedWord** [comment]
also, could you provide a minimal example project exhibiting this issue  ?

**Comment by WatIsDeze** [comment]
The pixel snap option had no use. As for an example, I'll try to work one out in the following days.

Meanwhile anyone whom is interested, the problem has always been around for me with the Tilemap. However it became extremely obviously visible after having added lights. Somehow, as I mentioned before, adjusting the code by removing the *= fp_float; seems to solve the problem.

There's a but BUT though, I'm not (yet) submitting this as a bug fix though. The reason being that in all honesty I would like to understand what is going on here precisely inb4 possibly even breaking something else.

I'm tired, will try to get an example going in the following two days and share it with you all. This problem is really a pain.

**Comment by Cybolic** [comment]
I think I'm seeing the same issue; the lines only show up when the lightmap is active, mipmapping and filter is off everywhere, but use_pixel_snap seems to work when running the game, but not in the editor.
![godot-tile-light-lines](https://cloud.githubusercontent.com/assets/1196197/7242363/7bafccf6-e7ca-11e4-801d-dc2bf406cfca.png)

**Comment by SuperUserNameMan** [comment]
@Cybolic : could you provide a minimal example project exhibiting the issue ?

**Comment by Cybolic** [comment]
Absolutely. Here's an example project and included screenshots from my system (Ubuntu 14.04, NVIDIA GTX 660 Ti) using three different sprite/tile map sizes:
 + 32x16, no division between tiles
 + 33x16, 1px transparent divide between tiles
 + 48x16, 1px transparent divide between tiles, Po16 image size.

https://drive.google.com/file/d/0B2mB5cFTxznfT2F4dXoxeldNbkk/view?usp=sharing

And here are the results for easy reference:

32x16:
![screenshot_tile_issue_using_32x16](https://cloud.githubusercontent.com/assets/1196197/7250524/cb7cce76-e82b-11e4-9984-f144fb8e3b8b.png)
33x16:
![screenshot_tile_issue_using_33x16](https://cloud.githubusercontent.com/assets/1196197/7250527/cb86caca-e82b-11e4-91f5-6df0dcb99117.png)
48x16:
![screenshot_tile_issue_using_48x16](https://cloud.githubusercontent.com/assets/1196197/7250526/cb8400e2-e82b-11e4-9f76-2dbce1c7c9a5.png)

**Comment by Cybolic** [comment]
Lights also turn off or clip at certain zoom levels. If you zoom out enough on the example project I linked to, the light will disappear; in the project I included a screenshot of earlier, the light texture will clip so only  the upper half, third, etc. will show depending on the window size (run) or zoom level (edit) - zoom out enough and it will also disappear completely.

**Comment by WatIsDeze** [comment]
@Cybolic The same happened to me, however, are you currently using the most recent git release? Because I believe it should've solved the problem.

Nonetheless the only reason I am aware of this entire += and *= fp_float business is going on, is in relation to certain old mobile devices.

Solving this, in my opinion, is done by a nice #ifdef that disables this on Desktops. I don't think it is nescessary.

**Comment by SuperUserNameMan** [comment]
@Cybolic : thanks for the example. @WatIsDeze  is right. it is solved in the latest github version.

**Comment by Cybolic** [comment]
@WatIsDeze and @SuperUserNameMan, you're right, I can confirm that the edge issue is fixed in the latest git version.

The clipping/disappearing light maps are still happening for me though. If you duplicate the light in my example a few times and move them so they aren't all in the same location and then zoom out, they disappear one after the other. Maybe this should be in a different issue report though?

**Comment by SuperUserNameMan** [comment]
Yes I think you could open an other issue.
I noticed the light disapearing only when zooming-in-out into the editor.
But when I add a camera with the script below and zoom-in-out in runtime, the light does not disapear like into the editor.

````
extends Camera2D

func _ready():
	# Initialization here
	set_fixed_process(true)
	pass


func _fixed_process(delta): #{
	if Input.is_action_pressed("ui_up") : #{
		set_zoom( get_zoom() * 0.95 )
	#}
	if Input.is_action_pressed("ui_down"): #{
		set_zoom( get_zoom() * 1.05 )
	#}
#}
````

**Comment by Cybolic** [comment]
@SuperUserNameMan, I tried your solution and while it works in a "normal" sized window, the clipping shows up again when maximising the runtime window.

I've created it as issue #1722.

**Comment by reduz** [comment]
i think this should be solved, please confirm

**Comment by Cybolic** [comment]
It can still happen in the latest git version, but much less.
![godot engine - issue_tilegap - issue scn - _001](https://cloud.githubusercontent.com/assets/1196197/7339727/3334a5ac-ec82-11e4-8bec-a37a9334cedb.png)

**Comment by WatIsDeze** [comment]
@reduz For clarity, have you removed the fp_float math, or have you changed its value to FP_EPSILON?

Because given the fact you mentioned it is there, just for mobile reasons, I suggest we remove this code from PC rendering and use an ifdef to enable it for (sorry, I hate android) android systems.

**Comment by reduz** [comment]
@Cybolic: keep in mindt hat you have to disable filters and mipmaps for tilemap to work properly

**Comment by Cybolic** [comment]
@reduz: I always have those disabled; the screenshot above is a quick modification of the example project I posted earlier, where mipmap is on disallow and filter and gen_mipmaps are set to off.

**Comment by okamstudio** [comment]
can you make a small example scene where this problem is shown, so I can
try to see how to fix it?


On Tue, May 5, 2015 at 2:03 PM, Christian Dannie Storgaard <
notifications@github.com> wrote:

> @reduz <https://github.com/reduz>: I always have those disabled; the
> screenshot above is a quick modification of the example project I posted
> earlier, where mipmap is on disallow and filter and gen_mipmaps are set to
> off.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1682#issuecomment-99142022>.
>



-- 

*OkamStudio*

**Comment by Cybolic** [comment]
Sure, it's basically the same as the last example project I posted though: https://drive.google.com/file/d/0B2mB5cFTxznfR0Q0dGU5Z29hSk0/view?usp=sharing

The issue appears when using a tile sprite with a transparent 1 px gap between the tiles.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch? (I don't remember any attempt to fix it, but one never knows)

@reduz There is a minimal example to reproduce the bug in https://github.com/godotengine/godot/issues/1682#issuecomment-99167999

**Comment by slapin** [comment]
Yeah, I confirm this, it is still there.
https://github.com/godotengine/godot/issues/4747 is duplicate.

**Comment by oliver-ruehl** [comment]
I also see this in the platformer demo on 2.0.3.

**Comment by oliver-ruehl** [comment]
Actually this setting fixed my problems:

![screenshot 2016-06-05 00 44 49](https://cloud.githubusercontent.com/assets/1587355/15802594/55fc1eca-2ab7-11e6-9953-f7e06485ebc1.png)
**use_2d_pixel_snap=true**

It can be found in the official manual as a "workaround".

**Comment by akien-mga** [comment]
Indeed, there were several improvements in the GLES3 renderer to workaround this kind of issue.
