### ISSUE TITLE
Graphic artifact when environment Glow is turned on

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#17036]
**Godot version:**
3.0.1, but the issue is present in 3.0 as well

**OS/device including version:**
Ubuntu 17.04, gpu: GTX1060

**Issue description:**
I noticed that rarely in my game some elements are starting to shine for one frame when camera is moving around, after investigation it turns out that it's caused by GLOW in environment node. I was able to record short gif of it with still camera: 
![shine_artifact](https://user-images.githubusercontent.com/6129594/36666103-e1fcc3ec-1ae9-11e8-915c-c22d98c9f0a1.gif)
the effect is immediately appearing/disappearing if I move camera in any direction, it's the most noticeable when camera moves (one frame brightness), but it's impossible to capture it in such motion on gif

**Steps to reproduce:**
1. For the most visible effect download reproduction project (little modified materials demo). Or alternatively you can open material demo and turn GLOW on in environment node.

**Minimal reproduction project:**
https://www.dropbox.com/s/ga20u9qq9vpbf84/MaterialTesterGlowArtifacts.7z?dl=0 (file to big to upload on github)

**Comment by reduz** [comment]
This usually happens due to specular blobs.. maybe I should add something to limit specular strength in some materials.

**Comment by clayjohn** [comment]
I think this is fixed in 4.0 already. Realistically it is not something that can be "fixed" but the impact is reduced by improvements to specular aliasing (roughness limiter and FXAA) and to the glow effect itself.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/54409

**Comment by Calinou** [comment]
For people finding this issue via a web search, note that a variant of this issue still exists in `3.x`: https://github.com/godotengine/godot/issues/15756
