### ISSUE TITLE
Regression: enums can't be used as export hint if they are declared in another file

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#17039]
**Godot version:**
3.0.1

**OS/device including version:**
Ubuntu 17.04

**Issue description:**
In 3.0.1 there is no way to use enum that's declared in another file as an hint for export variable.
In 3.0 it was possible to do this:
` export(preload("res://enum.gd").ENUMERATOR) var enumeration`
In 3.0.1 in such situation he throws `Invalid index 'ENUMERATOR' in constant expression`

**Steps to reproduce:**
1. Crate new script, lets call it 'EnumScript.gd'
2. Put enum inside `enum SomeEnum{FIRST, SECOND};
3. Create another script, put `export (preload("res://EnumScript.gd).SomeEnum) var enumValue;`
4. Observe syntax error.

**Minimal reproduction project:**

**Comment by kubecz3k** [comment]
Duplicate of https://github.com/godotengine/godot/issues/17025

**Comment by hpvb** [comment]
The functionality still works this is a cosmetic error in the editor. It's not great but you could continue work on your game with 3.0.1, or revert to 3.0 until we've fixed this for 3.0.2

Sorry for the regression!

**Comment by kubecz3k** [comment]
@hpvb no problem, thanks! Sorry for not catching this one sooner - I missed the 3.0.1 rc1

**Comment by jordanlis** [comment]
Hey, has this issue been corrected ? 
I still get a blank list... 

![Uploading 2021-03-01 01_28_47-Adobe Photoshop CC 2018.png…]()
