### ISSUE TITLE
No copy and paste

### ISSUE THREAD

**Issue by samgj** [godotengine/godot#1704]
Copy and paste (both keyboard and menu) isn't working on Windows 7, for Godot 1.0 and 1.1 beta.

**Comment by WatIsDeze** [comment]
Sadly, not a proper descriptive bug report, not working in what way? In the entire editor? Script editor? If it is the script editor, probably related to selecting all text?

**Comment by Ace-Dragon** [comment]
Copy and paste for various text selections work for me for copying to a forum post or copying back into the script editor (when using Ctrl-C / Ctrl-V). However, there are two cases where it doesn't work.

 - Selecting all of the text using the *select all* command and doing Ctrl-C will not copy anything to the clipboard
 - Copying via the menu item doesn't seem to do anything.

**Comment by WatIsDeze** [comment]
@Ace-Dragon in my specific tests it seems as if it fails only if you select the first, and last character of the entire script data. Can you confirm this? Or is it specific to only the first char?

**Comment by reduz** [comment]
can't reproduce at all (am on linux) tried many ways of copy and paste and it works...

**Comment by WatIsDeze** [comment]
On OsX, I can rest assure you, this is reproduce-able, possibly something related to length counts and OS APIs?

**Comment by samgj** [comment]
For me it won't work at all on Windows 7 within Godot, or between Godot and other programs.

**Comment by reduz** [comment]
i still lack an osx device, can anyone with such check this code?
https://github.com/okamstudio/godot/blob/master/platform/osx/os_osx.mm#L1189

**Comment by xFlaye** [comment]
Happens as well on a Windows machine. In the script editor, neither CTRL-C/CTRL-V nor Edit>Copy / Edit>Paste work. 
Tried it on beta, rc1,rc2
Surprisingly, CTRL-Z does work.

**Comment by NateWardawg** [comment]
@xFlaye Does this happen when you drag select with the mouse then copy/paste. Under Linux if I Ctrl+A then copy/paste it doesn't work, but if I drag select and copy/paste it does work.

**Comment by okamstudio** [comment]
thatś really weird, will have to test next time i'm on windows, but never
seen this behavior

On Wed, May 6, 2015 at 10:09 PM, xFlaye <notifications@github.com> wrote:

> Happens as well on a Windows machine. In the script editor, neither
> CTRL-C/CTRL-V nor Edit>Copy / Edit>Paste work.
> Tried it on beta, rc1,rc2
> Surprisingly, CTRL-Z does work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1704#issuecomment-99666683>.
>



-- 

*OkamStudio*

**Comment by xFlaye** [comment]
@NateWardawg yes, when dragging, highlighting and either CTRL-C or Edit>Copy. None of it works. Tried it on 3 separate Windows machines (2 desktops, 1 laptop) with same results. No access to Linux or Mac, unfortunately.

**Comment by xFlaye** [comment]
So here's the thing (on Windows)...CTRL-C does copy, but CTRL-V doesn't paste. CTRL-X cuts, CTRL-A selects all.
I copied text from the script editor and pasted it externally, and it worked.

Any ideas?

**Comment by reduz** [comment]
Sorry guys, I tried, tried and tried this on Windows and Linux without any issues. 
Everything works fine. The only case is the one mentioned by @Ace-Dragon , because by using the menu to select all, the text editor loses focus. This has been resolved now by forcing it to regain focus.

@xFlaye There has to be something strange in your windows configuration, do you use any specific input method or anything not present on regular Windows?

**Comment by reduz** [comment]
Next time you are testing this and it doesn't work, pease make sure the text editor control is selected (white outline) THEN try ctrl-c and ctrl-v and let me know at that point if it works or not

**Comment by NateWardawg** [comment]
Hi Juan, for me it's if there isn't a blank line at the end of my script it seems to cause selection issues with Ctrl+A. Ctrl+A will still hilight everything, but nothing will work as if nothing is actually selected. For instance if I hit backspace the selection drops but the content of the script remains. Likewise, if I hit Ctrl+C it doesn't copy anything. If there is a blank line at the end of the script it all works fine. This is all running the latest version built from source.

**Comment by xFlaye** [comment]
I don't think I have any special input methods in my windows configuration. The only additional input method I have is an Wacom Intuos tablet, but that shouldn't affect it, I think.

**Comment by reduz** [comment]
ok fixed the ctrl-a bug.. does this issue persist in some other way?

**Comment by NateWardawg** [comment]
@reduz Just checked it here too and is fixed... thanks!

**Comment by xFlaye** [comment]
Just installed v1.1. The paste function (ctrl-V on windows 7 system) still isn't working. I can copy from the script editor and paste it outside of Godot (i.e. on notepad) without any issues, but within Godot itself, it's still not working.
Thanks!

**Comment by reduz** [comment]
xFlaye could be more specific of what you do to test?

**Comment by xFlaye** [comment]
Everything seems to work now. I've deleted Godot from my system, restarted my computer, and re-installed it...and now it's working perfectly.

I've tested it with a few different scenes (highlighted the text with the mouse, pressed CTRL-C to copy, clicked on an empty space in the editor, and pressed CTRL-V).

Thanks for looking into this and fixing it.

**Comment by vnen** [comment]
Closing, since it's reported as being fixed.
