### ISSUE TITLE
OS.get_screen_orientation() returns LANDSCAPE, although project is set to PORTRAIT on android.

### ISSUE THREAD

**Issue by footurist** [godotengine/godot#17109]
Both Project>Export>Screen>Orientation and Project>Project Settings>General>Handheld>Orientation are set to Portrait and when I call the above function on device it always returns 0, which stands for Landscape. Is the bug from Godot 1 somehow back or am I missing something?

**Comment by aaronfranke** [comment]
@Footurist Does this still happen with Godot 3.1?

**Comment by KoBeWi** [comment]
Still happens in 3.1 stable.

Tested on Xiaomi Redmi Note 4 with Android 7.

**Comment by shrewdlogarithm** [comment]
I just ran into something like this - my setup is Godot 3.2 deploying to an Android 10 device.

If I set Project display mobile orientation to 'sensor' I can deploy and the game will 'rotate' as I turn the phone (as I'd expect) however OS.screen_orientation is ALWAYS 0 - which is clearly wrong.

I'd add that even if I lock the rotation (e.g. setting PORTRAIT or LANDSCAPE) I would still like to know what orientation the device THINKS it's in - that would allow me to make a game 'locked' to an orientation but with a UI which adjusts depending on how the user is holding the phone.

e.g. OS.screen_orientation should tell what the PHONE thinks the screen should be and not what it actually is - e.g. it's "which way is the user holding the phone" (I cannot think why I'd need to know which way I told it to be as - erm - I told it to be that!?)

**Comment by HEAVYPOLY** [comment]
Confirmed here, using 3.2.3 stable and Samsung note 9
Project Settings:
    Orientation:Sensor

Export Settings:
    Android:
        Orientation: Portrait (no option for auto?  Only Portrait or Landscape)

OS.get_screen_orientation() is always 0, even though the app is switching orientations based on phone orientation.

Also switches orientation regardless of the phone's Android OS Lock Rotation setting being on or off

**Comment by m4gr3d** [comment]
The issue is already fixed on the main branch by https://github.com/godotengine/godot/commit/e167af37373dd14e9d1fe888bcc482d0bd071951. The fix will be backported to `3.2` by https://github.com/godotengine/godot/pull/43022.

**Comment by akien-mga** [comment]
@m4gr3d FYI, the `cherrypick:3.2` label is only for PRs which are meant to be cherry-picked once merged in `master`.

There's no way currently to provide information about an issue being fixed both in 4.0 and in a 3.2.x release via a cherry-pick. In this case we just set the milestone of the first branch where it's fixed from the start (4.0).

**Comment by anisc** [comment]
Is this fixed or going to be fixed ? I'm using 3.2.3 and still have the same issue OS.get_screen_orientation() return the same value (0).

**Comment by m4gr3d** [comment]
@anisc It's fixed on the master branch, and the fix will be backported to Godot 3.2.4 by https://github.com/godotengine/godot/pull/43022

**Comment by anisc** [comment]
@m4gr3d Hopefully,  just checked the changelog for Godot 3.2.4 beta 1, there is no mention of it :( 
But of course there is more pressing issue, thank you so much!

**Comment by Calinou** [comment]
@anisc That pull request was merged after 3.2.4beta1 was released.

**Comment by ChildLearningClub** [comment]
I'm getting OS.get_screen_orientation() returning the value (0) in 3.4.2.stable. I'm I missing something?

**Comment by KoBeWi** [comment]
Well, did you change the orientation? :P
I tested and it works fine in 3.5 beta4. However the description is a bit misleading. It returns whatever you have set in Project Settings, not the current orientation (i.e. using sensor doesn't change the value).

**Comment by ChildLearningClub** [comment]
Sure enough, it just spits out what you have set in the project settings. Thank you for clarifying @KoBeWi

**Comment by Zireael07** [comment]
I guess this should be labeled as a documentation fix?

**Comment by KoBeWi** [comment]
I'd open a new issue.
Also we might consider changing the behavior or adding a new method that returns the actual orientation..

**Comment by hiulit** [comment]
Did someone open a new issue? I can't find it and the "issue" of `OS.get_screen_orientation()` not returning the current screen orientation but rather the property set in Project Settings it's still present in 3.5. Should I open a new issue?

The problem I'm facing is having to deal with notches and whatnot, so the game fits the screen properly. Having a function to detect the current orientation would be very helpful, in conjunction with `OS.get_window_safe_area()`, to detect where the notch is and apply the proper margins.
