### ISSUE TITLE
.tscn node definitions occasionally gain `index` attributes even though nothing was changed, leading to version control fuzziness

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#17562]
**Godot version:**
v3.0.2.stable.official on macOS (without C#)

**OS/device including version:**
macOS 10.13.3 on a 2017 MacBook Air (Intel HD Graphics 6000)

**Issue description:**
Godot occasionally adds `index="0"` to a node definition within a .tscn file, even though nothing was changed. While not a big issue per se, this can mess with your version history when using a SCM (I use git.)

**Expected behavior:**
If no data changes, the related files should also not change.

**Steps to reproduce:**
I don't know if it happens in _every_ project, but I've provided my current toybox project where it does happen. Steps to reproduce:

1) Open the project in Godot
2) Open the "Test" scene
3) Edit any of the contained scripts (eg. FunkyCam2D) within the Godot editor
4) Immediately save the script without making any change
5) Check your `git status`, and you will see the `index="0"` added in `Test.tscn`.

I don't know what the relevance of the `index` attribute is, but I suspect it is a UI concern (like open tab order?) that should not be leaking into the data files. If it actually _id_ data, the bug possibly was that the attribute was not saved to begin with?

**Minimal reproduction project:**
[SpaceRage2-master.zip](https://github.com/godotengine/godot/files/1819675/SpaceRage2-master.zip)

**Comment by Zireael07** [comment]
I am seeing the same thing, index=0 loves getting added apparently.

**Comment by akien-mga** [comment]
I've seen this too, I'm not sure what this `index` parameter is meant to represent, but it does mess with the version history.

**Comment by akien-mga** [comment]
I was about to blame @reduz as usual, but this time `git blame` knew better :P

This new index comes from #14406 by @hoelzl. It does had a lot of noise in scene files for what it's trying to solve... if we can't find an alternative which does not need keeping an index on each node, we at least need to ensure that it's deterministic and doesn't change all the time without motive.

**Comment by hoelzl** [comment]
The purpose of the index is to ensure that nodes added to instanced scenes appear in the correct position with regards to their siblings. (Without #14406 they always appear after the instanced nodes when the scene is loaded, no matter where you originally placed them.)

Thus, to get rid of some of the spurious `index = 0` outputs, i believe the easiest fix would be to change the check in [line 1635 of `scene_format_text.cpp`](https://github.com/godotengine/godot/pull/14406/files#diff-ca943b3fdfe8e2b0c3400613da59592aR1635) to only output the index entry if the node is a non-instanced child of an instanced node.

A check that get rids of all unnecessary `index = ...` would additionally check whether there is an instanced sibling to the right of the non-instanced node and only output the index entry if this is true. If the non-instanced node is to the right of all its instanced siblings it should be restored to the correct position anyway.

**Comment by menip** [comment]
Can confirm I've seen this as well

**Comment by KoBeWi** [comment]
Happened to me too. Especially disturbing when you for some reason have a scene open, which someone else changes and you make a commit without changing the scene and then the index appears and it causes conflict. Absolutely terrible.

**Comment by aaronfranke** [comment]
Happened to me [here](https://github.com/godotengine/godot/issues/20651). Either `index` should always be present, or it should never be present. I think it may be better to always have it present.

**Comment by chanon** [comment]
I believe index=0 appearing and disappearing is still happening. Not sure if others still experience it.

**Comment by salvob41** [comment]
yes in macOS and Godot3.0.6stable keeps happening

**Comment by akien-mga** [comment]
This was fixed in the master branch (3.1), not in 3.0.6.

**Comment by chanon** [comment]
Actually it is happening for me using master branch. Again, not sure if anyone else is getting it, but just wanted to say that it is for me.

**Comment by reduz** [comment]
Index should still appear, but only on very specific situations, like inherited scenes or when you put a node within the editable children of an instanced scene.

**Comment by reduz** [comment]
@chanon if this is not your case, please make a small test scene that creates these when you save

**Comment by organicpencil** [comment]
Using a master build from today: I had an index removed after saving with no changes. Did a git reset and saved again, couldn't replicate the problem.
The diff:
```diff
@@ -118,7 +118,7 @@ proximity_fade_enable = false
 distance_fade_mode = 0
 _sections_unfolded = [ "Albedo", "Flags" ]
 
-[node name="Cruiser" index="0" instance=ExtResource( 1 )]
+[node name="Cruiser" instance=ExtResource( 1 )]
 mass = 200.0
 script = ExtResource( 2 )
 rigid_shape = NodePath("CollisionShape")
```
It was a root node inherited from a dae scene. Seems quite random. Haven't been able to reproduce yet.

**Comment by organicpencil** [comment]
Well it's been over a month and hasn't happened since. Might have been some leftovers from converting my project from 3.0 -> 3.1. Or I was just really lucky. Or not perceiving things properly.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Comment by ArdaE** [comment]
For steps to reproduce the issue for inherited scenes, please see #28309. (Godot 3.1 still suffers from this issue for inherited scenes).
