### ISSUE TITLE
Saving a scene with MultiMesh spams an 'multimesh_instance_set_color' error

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#17850]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/38112536-8a25e1e0-33a2-11e8-8857-f58f9040eb4c.png)

**OS/device including version:**
Windows 10 64

**Steps to reproduce:**
Create scene with MultiMesh and default setup, using the 'Populate' option from the header, on saving spams error per mesh instance (makes saving super slow with large amounts of multi mesh instances):
![image](https://user-images.githubusercontent.com/7307968/38112613-d89ccb2c-33a2-11e8-8ea0-12b572bdaaee.png)

**Minimal reproduction project:**
[MultiMeshTest.zip](https://github.com/godotengine/godot/files/1861910/MultiMeshTest.zip)

**Comment by reduz** [comment]
The right fix for here is overriding:
```
	void _validate_property(PropertyInfo &property) const;
```
in MultiMesh. In that function, check the color array and transform array and:
1) change the property type (vector2 or vector3 array for transform depending on type)?
2) unexpose color if not used

**Comment by reduz** [comment]
This may have been fixed, can anyone test?

**Comment by akien-mga** [comment]
See also [MultiMeshInstance_Error.zip](https://github.com/godotengine/godot/files/2138542/MultiMeshInstance_Error.zip) from #19788, which also still reproduces the error in 6d7a8a6ca.

**Comment by reduz** [comment]
This is not really a bug, the old scene was saved wrong due to a bug. If you re-save it, the error goes away.
Closing.
