### ISSUE TITLE
Pivot tool doesn't compensate Control node position correctly

### ISSUE THREAD

**Issue by nattanielgrape** [godotengine/godot#17890]
**Godot version:**

3.0.2.stable.official

**Issue description:**
Using the pivot tool ![pivot_tool](https://user-images.githubusercontent.com/35730957/38164385-195fd950-34da-11e8-9fb9-c6a997557967.png) to change the pivot offset of a rotated Control node causes it to move northwest through the screen (I'm using a TextureButton as an example):

![control_rotated](https://user-images.githubusercontent.com/35730957/38164443-56ca3fbe-34db-11e8-8313-df0f81255390.gif)

At 0°, this issue doesn't occur:

![control_0_degrees](https://user-images.githubusercontent.com/35730957/38164457-8b4ae8ba-34db-11e8-9b95-278e7d9f4f1a.gif)

At 360°, the pivot tool now also changes the node's size:

![control_360_degrees](https://user-images.githubusercontent.com/35730957/38164460-93cdd6f0-34db-11e8-93b3-00454998b99a.gif)

The same doesn't happen when changing the offset of a Sprite node, as its position is compensated correctly:

![sprite_rotated](https://user-images.githubusercontent.com/35730957/38164462-9bdb6b14-34db-11e8-8f2d-19fdc1549d72.gif)

**Steps to reproduce:**
1. Add a node that inherits the Control class;
2. Change its rotation to any degree other than 0;
3. Select the pivot tool in the toolbar and change the node's pivot offset.

**Edit:**

I thought that the issue was related to **Control::_edit_set_pivot**, but it seems to affect the Control node in-game too. Here's a demo project where you can click to change the pivot offset of a TextureButton and the offset of a Sprite, based on the local mouse position. The Sprite stays fixed in its place while the TextureButton moves up and left:

![control_pivot](https://user-images.githubusercontent.com/35730957/38167262-a785b9c4-3508-11e8-9344-d29f1efa93e0.gif)

[control_pivot.zip](https://github.com/godotengine/godot/files/1865888/control_pivot.zip)

**Comment by groud** [comment]
That's normal, and there's actually nothing we can do about it. 
This is due to the fact that Control nodes are meant to be used with Integer positions (Integer margins actually), so when you move the pivot in a rotated node it move it to closets Integer it finds (Probably using floor I guess, we might use round instead).

The size change is weird with the 360° rotated node. I'll investigate that.

**Comment by groud** [comment]
And in fact this is fixed on master :)
So closing I guess.

**Comment by nattanielgrape** [comment]
I tested a nightly build, the 360° rotation issue still exists, all the others are fixed.

**Comment by nattanielgrape** [comment]
Actually, the other issues still happen when multiples of 45 are used as the rotation angle.

**Comment by reduz** [comment]
One smart workaround for this would be to not snap controls to integer if a
rotation != 0,90,180,etc exists

**Comment by reduz** [comment]
or scale

**Comment by groud** [comment]
That could work. I didn't wanted to introduce such inconsistancy but it probably makes sense

**Comment by nattanielgrape** [comment]
Only 0° is unaffected, using right and square angles as the rotation still makes the Control go up and left when using the pivot tool. So making them an exception may not fix the issue.

**Comment by nattanielgrape** [comment]
And dragging the pivot makes the Control to shake (180° rotation in the example):

![180_degrees](https://user-images.githubusercontent.com/35730957/38201619-4b625bd0-366f-11e8-88ca-760281ef28be.gif)

**Comment by groud** [comment]
OK I managed to reproduce on master by zooming in the editor. Else it was not visible.

**Comment by Ridote** [comment]
I didn't want to open another ticket cause this is close enough to what is happening to me. When I move the pivot to around the center it moves the whole image for no reason

**Comment by reduz** [comment]
@groud I remember we discussed a potential solution to this, but i now don't remember..

**Comment by groud** [comment]
Yeah, making the control node position internally float values but snap the values just before the rendering.

**Comment by nattanielgrape** [comment]
**Godot version:**
Godot 3.1 alpha 3

It still happens when the button has a scale other than 1,1:

![button_scaled](https://user-images.githubusercontent.com/35730957/49873513-34dc2600-fe03-11e8-8e1a-34f4520745a0.gif)

**Comment by akien-mga** [comment]
CC @groud @DualMatrix
