### ISSUE TITLE
WindowDialog can be dragged around without holding down any mouse buttons

### ISSUE THREAD

**Issue by MennoMax** [godotengine/godot#19154]
**Godot version:**
Godot 3.0.2-stable_win64

**OS/device including version:**
Windows 10.0.17134 Build 17134

**Issue description:**
When holding both right and left mouse button on the upper bar of a window dialog like the project settings window and then releasing them, the window can be dragged around without holding down any mouse buttons.

**Steps to reproduce:**

1. right click the upper bar of a window dialog
2. left click the upper bar of a window dialog
3. release the right mouse button
4. release the left mouse button
5. drag the window around without holding down any mouse buttons

**Minimal reproduction project:**
This can be reproduced in any project by performing the steps above on the project settings window.

**Comment by akien-mga** [comment]
Assumed fixed by #19151 in the master branch, please comment if it's not the case so that we can reopen it.

**Comment by MennoMax** [comment]
Built godot from source 30 minutes ago, this issue is still present.

**Comment by mhilbrunner** [comment]
Reopening.

**Comment by nightblade9** [comment]
Why is this issue closed? I can still reproduce it in 3.0.6.

**Comment by akien-mga** [comment]
As the milestone says, it was closed in 3.1.
