### ISSUE TITLE
Resources not updating automatically in the internal filesystem cache before Android export

### ISSUE THREAD

**Issue by JacobSobolev** [godotengine/godot#1926]
_BugSquad edit: it's still present in 2.0 b2f9acb8c96aed0505cbac21661e21e4acef710f build_

App won't start if using 2d shader, the fix is to restart the engine and recompile the game

**Comment by bojidar-bg** [comment]
I think you should include some more details, so the issue can be reproduced.

**Comment by JacobSobolev** [comment]
at the time i was on the irc and @reduz told me he knew the problem and always forgot to fix it, so he suggested to post an issue

**Comment by bojidar-bg** [comment]
I see...

**Comment by reduz** [comment]
i forgot what it was :(

**Comment by JacobSobolev** [comment]
lol, when i created a new canvas item shader, and pasted the code from the demos and compiled the game to android the game wouldn't start, the splash screen was just blinking over and over,if i restart the engine it fixes the problem

**Comment by okamstudio** [comment]
yeah this is the known bug of resources sometimes not updating in the
internal filesystem cache, should be properly fixed in 1.2


On Sat, May 23, 2015 at 10:31 AM, RudeJake <notifications@github.com> wrote:

> lol, when i created a new canvas item shader, and pasted the code from the
> demos and compiled the game to android the game wouldn't start, the splash
> screen was just blinking over and over,if i restart the engine it fixes the
> problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1926#issuecomment-104896630>.
>



-- 

*OkamStudio*

**Comment by kubecz3k** [comment]
Bug still is present in 2.0 alpha b2f9acb8c96aed0505cbac21661e21e4acef710f build. 
In case if anyone is dealing with it: before export you just need to click "re-scan filesystem" in "File System" tab.
