### ISSUE TITLE
Game crashes when minimized (Windows 10)

### ISSUE THREAD

**Issue by JoaoNSE** [godotengine/godot#19293]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
I am making a networking game. When i open two or more game windows (in test mode or when is exported) and minimize any of them, the game window crashes.

The console tell to show this:
![image](https://user-images.githubusercontent.com/19472626/40790426-473bbd46-64cb-11e8-9b49-fb9f5d12845c.png)

**Steps to reproduce:**
Just open two (or more)

 game instances and set one player as host and the other as join. It is not necessary to put the informations of ip and port, as the game considerer it as localhost connection. After that, go to desktop by clicking on the bottom right corner of the screen (in the toolbar).
![image](https://user-images.githubusercontent.com/19472626/40790806-49c096da-64cc-11e8-9706-21aa460b6ae1.png)

**Minimal reproduction project:**

[RPG_Online.zip](https://github.com/godotengine/godot/files/2058796/RPG_Online.zip)

**Comment by vnen** [comment]
I remember fixing an issue like this a long time ago. Window size becomes (0, 0) when minimized and some code paths are not expecting that.

**Comment by sketchyfun** [comment]
This happens for me on windows 7 too, the only thing I get in the console though is this:

ERROR: Transform2D::affine_invert: Condition ' det == 0 ' is true.
   At: core\math\transform_2d.cpp:51

**Comment by sketchyfun** [comment]
Okay, for my particular case I've managed to narrow it down to having a GraphEdit node as a child of a TabContainer. I'll investigate a bit more.

**Comment by reduz** [comment]
A reproduction case would be very appreciated

**Comment by sketchyfun** [comment]
Unfortunately(?) I'm unable to reproduce it anymore, which is really strange considering I could make it happen without fail before :/

It appeared to only happen when I used a dynamic font in my GUI's theme, but now I'm trying it again and everything is fine, not even the "Transform2D::affine_invert: Condition ' det == 0 ' is true.
At: core\math\transform_2d.cpp:51" error anymore.. 

I'll be sure to post an example as soon as it happens again.

**Comment by marcelofg55** [comment]
I guess this should be fixed now that #24078 was merged. Please re-test, thanks!

**Comment by akien-mga** [comment]
Closing as fixed by #24078 so that we don't forget, but please comment to confirm that it does work as expected. If not, we can reopen the issue.

**Comment by IamRyusei** [comment]
The problem still exists in 3.1.stable.official under Windows 10. Whenever I get the game (not the editor) minimized, some sprites of the 3DScene disappears and I get multiples 

ERROR: project_ray_origin: Condition ' viewport_size.y == 0 ' is true. returned: Vector3()
   At: scene/3d/camera.cpp:284

I must specify that this happens only when I click on the bottom-right button on the Windows 10 bar (the one to show the Desktop) because it causes the Window size to go (0,0). But it does not happen when i reduce the window to icon via the window button itself.

**Comment by guilhermefelipecgs** [comment]
@IamRyusei It looks like you've encountered a different problem. Can you open a new issue with a reproduction project, please?
