### ISSUE TITLE
Shaders are not autosaving when pressing Play

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#1942]
Shaders are not autosaving when pressing Play ( F5 ).

**Comment by okamstudio** [comment]
did you check rc3? I thnk this was fixed then

On Mon, May 18, 2015 at 5:40 PM, Siewio <notifications@github.com> wrote:

> Shaders are not autosaving when pressing Play ( F5 ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1942>.
>



-- 

*OkamStudio*

**Comment by Krzycho666** [comment]
I was using RC3 while writing this issue =]
No. It's not fixed.

**Comment by reduz** [comment]
can you explain the steps to reproduce? I'm trying here and they get saved
fine.. or you mean text shaders?

**Comment by okamstudio** [comment]
tested both shader graph and text shaders and they save fine

On Tue, May 19, 2015 at 11:40 AM, Juan Linietsky <notifications@github.com>
wrote:

> can you explain the steps to reproduce? I'm trying here and they get saved
> fine.. or you mean text shaders?
>
>
> On Tue, May 19, 2015 at 7:15 AM, Siewio <notifications@github.com> wrote:
>
> > I was using RC3 while writing this issue =]
> > No. It's not fixed.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/1942#issuecomment-103427139
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1942#issuecomment-103529152>.
>



-- 

*OkamStudio*

**Comment by Krzycho666** [comment]
How to reproduce: change shader ( checked only on 2D text shaders ), hit play. Shader won't autosave.
I'm using Windows 7.

**Comment by okamstudio** [comment]
how do you change shader, you mean change the text?

On Tue, May 19, 2015 at 5:12 PM, Siewio <notifications@github.com> wrote:

> How to reproduce: change shader ( checked only on 2D text shaders ), hit
> play. Shader won't autosave.
> I'm using Windows 7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1942#issuecomment-103654035>.
>



-- 

*OkamStudio*

**Comment by Krzycho666** [comment]
Yes. I mean change the shader's text itself anywhere. It just doesnt autosave it on "Play"

**Comment by okamstudio** [comment]
ah wait another question.. are you using the shader or material as a
separate resource on disk?


On Tue, May 19, 2015 at 5:17 PM, Siewio <notifications@github.com> wrote:

> Yes. I mean change the shader's text itself anywhere. It just doesnt
> autosave it on "Play"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1942#issuecomment-103656374>.
>



-- 

*OkamStudio*

**Comment by Krzycho666** [comment]
In this particular example - as an in-scene resource.
By the way... why there is no option to reuse such resources. I mean use them in a couple of places in the same scene. They are visible in the Recources tab, but there is no way to use them again.

**Comment by reduz** [comment]
You have copy and paste options in the resource menu to reuse..  In 1.2
drag and drop will be added

**Comment by reduz** [comment]
I can't reproduce this.. Testing this, two images and the one on top with a shader:

![as](https://cloud.githubusercontent.com/assets/6265307/7716632/1d460196-fe6b-11e4-961c-b933a531d617.png)

and each time i change the shader, it's properly saved and displayed when running the scene. Is what you do any different? do you maybe have autosave disabled from the editor settings?

**Comment by adolson** [comment]
On that built-in resource tangent, it'd definitely be nice to be able to browse the internal resources somehow.

On topic, if autosave is not disabled and works correctly elsewhere, perhaps try making a small test case project that you could zip and link here so others (Juan, specifically) could test it. Or a video to demonstrate the behavior.

**Comment by Krzycho666** [comment]
Oh... copy params... I've forgot about this option. But it gets all of the data. How about making a copy of only one property ( or a group of properties ) at once.

**Comment by okamstudio** [comment]
no, not copy params, just click the resource property and you cand copy and
paste it individually

On Wed, May 20, 2015 at 7:37 AM, Siewio <notifications@github.com> wrote:

> Oh... copy params... I've forgot about this option. But it gets all of the
> data. How about making a copy of only one property ( or a group of
> properties ) at once.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1942#issuecomment-103839080>.
>



-- 

*OkamStudio*

**Comment by ratsdiov** [comment]
I see the same issue in 1.1 stable on Windows 7 64 bit... editing the code for a CanvasItemShader and hitting the run button or f5 does not autosave the changes so they do not take effect until you do an explicit save.

**Comment by reduz** [comment]
question, are both the material and canvasitemshader external files?

**Comment by ratsdiov** [comment]
Neither are external.

**Comment by akien-mga** [comment]
I think an example project that triggers the issue would be useful, since it's apparently not affecting all configurations.

**Comment by reduz** [comment]
this was fixed recently
