### ISSUE TITLE
Godot Mono doesn't rebuild solution when ran with --build-solutions

### ISSUE THREAD

**Issue by xfactor2000** [godotengine/godot#19581]
**Godot version:**
3.0.3.stable.mono.official

**OS/device including version:**
Manjaro Linux 17.1.10 Hakoila

**Issue description:**
Godot doesn't rebuild solution when `--build-solutions` flag is set

**Steps to reproduce:**

1. Make some changes to your project
2. Run `godot-mono --build-solutions`
3. Changes are ignored.

It is my understanding that this flag was added to let the user test new code with Godot without having to rebuild it manually first.

**Comment by akien-mga** [comment]
Duplicate of #18799 I guess? You need to use `godot-mono -e --build-solutions`.

CC @NathanWarden @neikeq Second user misinterpreting how to use it, and if `--build-solutions` *requires* the editor to run, maybe it should set `editor = true` so that `-e` is not mandatory?

**Comment by xfactor2000** [comment]
Just tried it, Godot window opened, closed and then got a stacktrace.

```/proc/self/maps:
00400000-03531000 r-xp 00000000 08:01 20709468                           /opt/godot-mono-bin/godot/Godot_v3.0.3-stable_mono_x11.64
03730000-0373c000 r--p 03130000 08:01 20709468                           /opt/godot-mono-bin/godot/Godot_v3.0.3-stable_mono_x11.64
0373c000-03759000 rw-p 0313c000 08:01 20709468                           /opt/godot-mono-bin/godot/Godot_v3.0.3-stable_mono_x11.64
03759000-03789000 rw-p 00000000 00:00 0
04537000-17665000 rw-p 00000000 00:00 0                                  [heap]
4081c000-4082c000 rwxp 00000000 00:00 0
4084e000-40850000 r-xs 00000000 00:29 31                                 /tmp/.glFKms47 (deleted)
413be000-413ce000 rwxp 00000000 00:00 0
41459000-41469000 rwxp 00000000 00:00 0
41bd6000-41c77000 rw-p 00000000 00:00 0
41e32000-41eb7000 rwxp 00000000 00:00 0
7fe0c8000000-7fe0c8021000 rw-p 00000000 00:00 0
7fe0c8021000-7fe0cc000000 ---p 00000000 00:00 0
7fe0d0000000-7fe0d0021000 rw-p 00000000 00:00 0
7fe0d0021000-7fe0d4000000 ---p 00000000 00:00 0
7fe0d4000000-7fe0d4021000 rw-p 00000000 00:00 0
7fe0d4021000-7fe0d8000000 ---p 00000000 00:00 0
7fe0d8000000-7fe0d802a000 rw-p 00000000 00:00 0
7fe0d802a000-7fe0dc000000 ---p 00000000 00:00 0
7fe0dc000000-7fe0dc021000 rw-p 00000000 00:00 0
7fe0dc021000-7fe0e0000000 ---p 00000000 00:00 0
7fe0e0000000-7fe0e0021000 rw-p 00000000 00:00 0
7fe0e0021000-7fe0e4000000 ---p 00000000 00:00 0
7fe0e4000000-7fe0e4063000 rw-p 00000000 00:00 0
7fe0e4063000-7fe0e8000000 ---p 00000000 00:00 0
7fe0e8000000-7fe0e804f000 rw-p 00000000 00:00 0
7fe0e804f000-7fe0ec000000 ---p 00000000 00:00 0
7fe0edffe000-7fe0f0000000 rw-p 00000000 00:00 0
7fe0f0000000-7fe0f0021000 rw-p 00000000 00:00 0
7fe0f0021000-7fe0f4000000 ---p 00000000 00:00 0
7fe0f59fb000-7fe0f59fc000 ---p 00000000 00:00 0
7fe0f59fc000-7fe0f59fd000 rw-p 00000000 00:00 0
7fe0f59fd000-7fe0f5a05000 ---p 00000000 00:00 0
7fe0f5a05000-7fe0f5bfc000 rw-p 00000000 00:00 0
7fe0f5bfc000-7fe0f5bfd000 ---p 00000000 00:00 0
7fe0f5bfd000-7fe0f5bfe000 rw-p 00000000 00:00 0
7fe0f5bfe000-7fe0f5c06000 ---p 00000000 00:00 0
7fe0f5c06000-7fe0f5dfd000 rw-p 00000000 00:00 0
7fe0f5dfd000-7fe0f5dfe000 ---p 00000000 00:00 0
7fe0f5dfe000-7fe0f5dff000 rw-p 00000000 00:00 0
7fe0f5dff000-7fe0f5e07000 ---p 00000000 00:00 0
7fe0f5e07000-7fe0fc000000 rw-p 00000000 00:00 0
7fe0fc000000-7fe0fc021000 rw-p 00000000 00:00 0
7fe0fc021000-7fe100000000 ---p 00000000 00:00 0
7fe1000fc000-7fe1000fd000 ---p 00000000 00:00 0
7fe1000fd000-7fe1000fe000 rw-p 00000000 00:00 0
7fe1000fe000-7fe100106000 ---p 00000000 00:00 0
7fe100106000-7fe1002fd000 rw-p 00000000 00:00 0
7fe1002fd000-7fe1002fe000 ---p 00000000 00:00 0
7fe1002fe000-7fe1002ff000 rw-p 00000000 00:00 0
7fe1002ff000-7fe100307000 ---p 00000000 00:00 0
7fe100307000-7fe1004fe000 rw-p 00000000 00:00 0
7fe1004fe000-7fe1004ff000 ---p 00000000 00:00 0
7fe1004ff000-7fe100500000 rw-p 00000000 00:00 0
7fe100500000-7fe100508000 ---p 00000000 00:00 0
7fe100508000-7fe1006ff000 rw-p 00000000 00:00 0
7fe1006ff000-7fe100700000 ---p 00000000 00:00 0
7fe100700000-7fe100701000 rw-p 00000000 00:00 0
7fe100701000-7fe100709000 ---p 00000000 00:00 0
7fe100709000-7fe100a00000 rw-p 00000000 00:00 0
7fe100a32000-7fe100c32000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe100c32000-7fe1017fe000 rw-p 00000000 00:00 0
7fe1017ff000-7fe101bff000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe101bff000-7fe102bff000 rw-p 00000000 00:00 0
7fe102bff000-7fe102c00000 ---p 00000000 00:00 0
7fe102c00000-7fe103800000 rw-p 00000000 00:00 0
7fe103854000-7fe103a54000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe103af9000-7fe103afa000 ---p 00000000 00:00 0
7fe103afa000-7fe103b3a000 rw-p 00000000 00:00 0
7fe103b3a000-7fe103b3b000 ---p 00000000 00:00 0
7fe103b3b000-7fe103b7b000 rw-p 00000000 00:00 0
7fe103b7b000-7fe103b7c000 ---p 00000000 00:00 0
7fe103b7c000-7fe103b7d000 rw-p 00000000 00:00 0
7fe103b7d000-7fe103b85000 ---p 00000000 00:00 0
7fe103b85000-7fe103dfc000 rw-p 00000000 00:00 0
7fe103dfe000-7fe108000000 rw-p 00000000 00:00 0
7fe108000000-7fe108021000 rw-p 00000000 00:00 0
7fe108021000-7fe10c000000 ---p 00000000 00:00 0
7fe10c02f000-7fe10c030000 ---p 00000000 00:00 0
7fe10c030000-7fe10c071000 rw-p 00000000 00:00 0
7fe10c071000-7fe10c0d1000 ---p 00000000 00:00 0
7fe10c0d1000-7fe10c111000 rw-p 00000000 00:00 0
7fe10c111000-7fe10c191000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe10c191000-7fe10df21000 rw-p 00000000 00:00 0
7fe10df21000-7fe10df22000 ---p 00000000 00:00 0
7fe10df22000-7fe10df62000 rw-p 00000000 00:00 0
7fe10df62000-7fe111f62000 rw-s 00000000 00:05 136974                     /memfd:pulseaudio (deleted)
7fe111f62000-7fe115f62000 rw-s 00000000 00:05 18878                      /memfd:pulseaudio (deleted)
7fe115f62000-7fe119f62000 rw-s 00000000 00:05 141463                     /memfd:pulseaudio (deleted)
7fe119f62000-7fe11df62000 rw-s 00000000 00:05 141463                     /memfd:pulseaudio (deleted)
7fe11df62000-7fe11df63000 ---p 00000000 00:00 0
7fe11df63000-7fe11e0bc000 rw-p 00000000 00:00 0
7fe11e0bc000-7fe11e13c000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e13c000-7fe11e1bc000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e1bc000-7fe11e23c000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e2eb000-7fe11e2fb000 rw-p 00000000 00:00 0
7fe11e2fb000-7fe11e2fc000 ---p 00000000 00:00 0
7fe11e2fc000-7fe11e33c000 rw-p 00000000 00:00 0
7fe11e33c000-7fe11e35c000 rw-s 00000000 00:06 431                        /dev/nvidia0
7fe11e35c000-7fe11e39c000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e39c000-7fe11e3bc000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e3bc000-7fe11e3fc000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e3fc000-7fe11e43c000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e43c000-7fe11e5ed000 rw-p 00000000 00:00 0
7fe11e5ed000-7fe11e5fe000 r-xp 00000000 08:01 3155099                    /usr/lib/libdrm.so.2.4.0
7fe11e5fe000-7fe11e7fd000 ---p 00011000 08:01 3155099                    /usr/lib/libdrm.so.2.4.0
7fe11e7fd000-7fe11e7fe000 r--p 00010000 08:01 3155099                    /usr/lib/libdrm.so.2.4.0
7fe11e7fe000-7fe11e7ff000 rw-p 00011000 08:01 3155099                    /usr/lib/libdrm.so.2.4.0
7fe11e7ff000-7fe11e904000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe11e904000-7fe11f9db000 r-xp 00000000 08:01 3153686                    /usr/lib/libnvidia-glcore.so.396.24
7fe11f9db000-7fe11f9fc000 rwxp 010d7000 08:01 3153686                    /usr/lib/libnvidia-glcore.so.396.24
7fe11f9fc000-7fe1200bd000 r-xp 010f8000 08:01 3153686                    /usr/lib/libnvidia-glcore.so.396.24
7fe1200bd000-7fe1202bd000 ---p 017b9000 08:01 3153686                    /usr/lib/libnvidia-glcore.so.396.24
7fe1202bd000-7fe1205bf000 rw-p 017b9000 08:01 3153686                    /usr/lib/libnvidia-glcore.so.396.24
7fe1205bf000-7fe1205d8000 rw-p 00000000 00:00 0
7fe1205d8000-7fe1205db000 r-xp 00000000 08:01 7995454                    /usr/lib/tls/libnvidia-tls.so.396.24
7fe1205db000-7fe1207db000 ---p 00003000 08:01 7995454                    /usr/lib/tls/libnvidia-tls.so.396.24
7fe1207db000-7fe1207dc000 rw-p 00003000 08:01 7995454                    /usr/lib/tls/libnvidia-tls.so.396.24
7fe1207dc000-7fe1208a5000 r-xp 00000000 08:01 3153966                    /usr/lib/libGLX_nvidia.so.396.24
7fe1208a5000-7fe1208d9000 rwxp 000c9000 08:01 3153966                    /usr/lib/libGLX_nvidia.so.396.24
7fe1208d9000-7fe1208ed000 r-xp 000fd000 08:01 3153966                    /usr/lib/libGLX_nvidia.so.396.24
7fe1208ed000-7fe120aed000 ---p 00111000 08:01 3153966                    /usr/lib/libGLX_nvidia.so.396.24
7fe120aed000-7fe120b12000 rw-p 00111000 08:01 3153966                    /usr/lib/libGLX_nvidia.so.396.24
7fe120b12000-7fe120b19000 rw-p 00000000 00:00 0
7fe120b19000-7fe120b8d000 rw-p 00000000 00:00 0
7fe120b90000-7fe120b94000 rw-p 00000000 00:00 0
7fe120b94000-7fe120ba7000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe120ba7000-7fe120bc7000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe120bc9000-7fe120be7000 rw-p 00000000 00:00 0
7fe120be7000-7fe120c07000 rw-s 00000000 08:01 24930143                   /home/anton/#24930143 (deleted)
7fe120c07000-7fe120c27000 r-xs 00000000 08:01 24930143                   /home/anton/#24930143 (deleted)
7fe120c27000-7fe120fa9000 rw-p 00000000 00:00 0
7fe120fa9000-7fe120fc8000 r-xp 00000000 08:01 3165729                    /usr/lib/libgpg-error.so.0.24.2
7fe120fc8000-7fe1211c7000 ---p 0001f000 08:01 3165729                    /usr/lib/libgpg-error.so.0.24.2
7fe1211c7000-7fe1211c8000 r--p 0001e000 08:01 3165729                    /usr/lib/libgpg-error.so.0.24.2
7fe1211c8000-7fe1211c9000 rw-p 0001f000 08:01 3165729                    /usr/lib/libgpg-error.so.0.24.2
7fe1211c9000-7fe1211dc000 r-xp 00000000 08:01 3147339                    /usr/lib/libresolv-2.27.so
7fe1211dc000-7fe1213dc000 ---p 00013000 08:01 3147339                    /usr/lib/libresolv-2.27.so
7fe1213dc000-7fe1213dd000 r--p 00013000 08:01 3147339                    /usr/lib/libresolv-2.27.so
7fe1213dd000-7fe1213de000 rw-p 00014000 08:01 3147339                    /usr/lib/libresolv-2.27.so
7fe1213de000-7fe1213e0000 rw-p 00000000 00:00 0
7fe1213e0000-7fe12146d000 r-xp 00000000 08:01 3160776                    /usr/lib/libvorbisenc.so.2.0.11
7fe12146d000-7fe12166c000 ---p 0008d000 08:01 3160776                    /usr/lib/libvorbisenc.so.2.0.11
7fe12166c000-7fe121688000 r--p 0008c000 08:01 3160776                    /usr/lib/libvorbisenc.so.2.0.11
7fe121688000-7fe121689000 rw-p 000a8000 08:01 3160776                    /usr/lib/libvorbisenc.so.2.0.11
7fe121689000-7fe1216b3000 r-xp 00000000 08:01 3160774                    /usr/lib/libvorbis.so.0.4.8
7fe1216b3000-7fe1218b3000 ---p 0002a000 08:01 3160774                    /usr/lib/libvorbis.so.0.4.8
7fe1218b3000-7fe1218b4000 r--p 0002a000 08:01 3160774                    /usr/lib/libvorbis.so.0.4.8
7fe1218b4000-7fe1218b5000 rw-p 0002b000 08:01 3160774                    /usr/lib/libvorbis.so.0.4.8
7fe1218b5000-7fe1218ba000 r-xp 00000000 08:01 3151702                    /usr/lib/libogg.so.0.8.3
7fe1218ba000-7fe121aba000 ---p 00005000 08:01 3151702                    /usr/lib/libogg.so.0.8.3
7fe121aba000-7fe121abb000 r--p 00005000 08:01 3151702                    /usr/lib/libogg.so.0.8.3
7fe121abb000-7fe121abc000 rw-p 00006000 08:01 3151702                    /usr/lib/libogg.so.0.8.3
7fe121abc000-7fe121b32000 r-xp 00000000 08:01 3160914                    /usr/lib/libFLAC.so.8.3.0
7fe121b32000-7fe121d32000 ---p 00076000 08:01 3160914                    /usr/lib/libFLAC.so.8.3.0
7fe121d32000-7fe121d33000 r--p 00076000 08:01 3160914                    /usr/lib/libFLAC.so.8.3.0
7fe121d33000-7fe121d34000 rw-p 00077000 08:01 3160914                    /usr/lib/libFLAC.so.8.3.0
7fe121d34000-7fe121e49000 r-xp 00000000 08:01 3162347                    /usr/lib/libgcrypt.so.20.2.2
7fe121e49000-7fe122048000 ---p 00115000 08:01 3162347                    /usr/lib/libgcrypt.so.20.2.2
7fe122048000-7fe12204a000 r--p 00114000 08:01 3162347                    /usr/lib/libgcrypt.so.20.2.2
7fe12204a000-7fe12204f000 rw-p 00116000 08:01 3162347                    /usr/lib/libgcrypt.so.20.2.2
7fe12204f000-7fe122050000 rw-p 00000000 00:00 0
7fe122050000-7fe12206c000 r-xp 00000000 08:01 3164499                    /usr/lib/liblz4.so.1.8.2
7fe12206c000-7fe12226b000 ---p 0001c000 08:01 3164499                    /usr/lib/liblz4.so.1.8.2
7fe12226b000-7fe12226c000 r--p 0001b000 08:01 3164499                    /usr/lib/liblz4.so.1.8.2
7fe12226c000-7fe12226d000 rw-p 0001c000 08:01 3164499                    /usr/lib/liblz4.so.1.8.2
7fe12226d000-7fe122292000 r-xp 00000000 08:01 3147113                    /usr/lib/liblzma.so.5.2.4
7fe122292000-7fe122491000 ---p 00025000 08:01 3147113                    /usr/lib/liblzma.so.5.2.4
7fe122491000-7fe122492000 r--p 00024000 08:01 3147113                    /usr/lib/liblzma.so.5.2.4
7fe122492000-7fe122493000 rw-p 00025000 08:01 3147113                    /usr/lib/liblzma.so.5.2.4
7fe122493000-7fe122498000 r-xp 00000000 08:01 3161220                    /usr/lib/libasyncns.so.0.3.1
7fe122498000-7fe122697000 ---p 00005000 08:01 3161220                    /usr/lib/libasyncns.so.0.3.1
7fe122697000-7fe122698000 r--p 00004000 08:01 3161220                    /usr/lib/libasyncns.so.0.3.1
7fe122698000-7fe122699000 rw-p 00005000 08:01 3161220                    /usr/lib/libasyncns.so.0.3.1
7fe122699000-7fe12270c000 r-xp 00000000 08:01 3161845                    /usr/lib/libsndfile.so.1.0.28
7fe12270c000-7fe12290b000 ---p 00073000 08:01 3161845                    /usr/lib/libsndfile.so.1.0.28
7fe12290b000-7fe12290e000 r--p 00072000 08:01 3161845                    /usr/lib/libsndfile.so.1.0.28
7fe12290e000-7fe12290f000 rw-p 00075000 08:01 3161845                    /usr/lib/libsndfile.so.1.0.28
7fe12290f000-7fe122911000 rw-p 00000000 00:00 0
7fe122911000-7fe122993000 r-xp 00000000 08:01 3158107                    /usr/lib/libsystemd.so.0.22.0
7fe122993000-7fe122b93000 ---p 00082000 08:01 3158107                    /usr/lib/libsystemd.so.0.22.0
7fe122b93000-7fe122b96000 r--p 00082000 08:01 3158107                    /usr/lib/libsystemd.so.0.22.0
7fe122b96000-7fe122b97000 rw-p 00085000 08:01 3158107                    /usr/lib/libsystemd.so.0.22.0
7fe122b97000-7fe122b98000 rw-p 00000000 00:00 0
7fe122b98000-7fe122b9d000 r-xp 00000000 08:01 3155330                    /usr/lib/libXdmcp.so.6.0.0
7fe122b9d000-7fe122d9c000 ---p 00005000 08:01 3155330                    /usr/lib/libXdmcp.so.6.0.0
7fe122d9c000-7fe122d9d000 r--p 00004000 08:01 3155330                    /usr/lib/libXdmcp.so.6.0.0
7fe122d9d000-7fe122d9e000 rw-p 00005000 08:01 3155330                    /usr/lib/libXdmcp.so.6.0.0
7fe122d9e000-7fe122da0000 r-xp 00000000 08:01 3147530                    /usr/lib/libXau.so.6.0.0
7fe122da0000-7fe122fa0000 ---p 00002000 08:01 3147530                    /usr/lib/libXau.so.6.0.0
7fe122fa0000-7fe122fa1000 r--p 00002000 08:01 3147530                    /usr/lib/libXau.so.6.0.0
7fe122fa1000-7fe122fa2000 rw-p 00003000 08:01 3147530                    /usr/lib/libXau.so.6.0.0
7fe122fa2000-7fe122fe4000 r-xp 00000000 08:01 3148404                    /usr/lib/libGLdispatch.so.0.0.0
7fe122fe4000-7fe122ffd000 r-xp 00042000 08:01 3148404                    /usr/lib/libGLdispatch.so.0.0.0
7fe122ffd000-7fe123010000 r-xp 0005b000 08:01 3148404                    /usr/lib/libGLdispatch.so.0.0.0
7fe123010000-7fe12320f000 ---p 0006e000 08:01 3148404                    /usr/lib/libGLdispatch.so.0.0.0
7fe12320f000-7fe123237000 r--p 0006d000 08:01 3148404                    /usr/lib/libGLdispatch.so.0.0.0
7fe123237000-7fe123238000 rw-p 00095000 08:01 3148404                    /usr/lib/libGLdispatch.so.0.0.0
7fe123238000-7fe123258000 rw-p 00000000 00:00 0
7fe123258000-7fe123268000 r-xp 00000000 08:01 3149530                    /usr/lib/libGLX.so.0.0.0
7fe123268000-7fe123467000 ---p 00010000 08:01 3149530                    /usr/lib/libGLX.so.0.0.0
7fe123467000-7fe123468000 r--p 0000f000 08:01 3149530                    /usr/lib/libGLX.so.0.0.0
7fe123468000-7fe123469000 rw-p 00010000 08:01 3149530                    /usr/lib/libGLX.so.0.0.0
7fe123469000-7fe123489000 rw-p 00000000 00:00 0
7fe123489000-7fe1234d7000 r-xp 00000000 08:01 3146193                    /usr/lib/libdbus-1.so.3.19.7
7fe1234d7000-7fe1236d7000 ---p 0004e000 08:01 3146193                    /usr/lib/libdbus-1.so.3.19.7
7fe1236d7000-7fe1236d9000 r--p 0004e000 08:01 3146193                    /usr/lib/libdbus-1.so.3.19.7
7fe1236d9000-7fe1236da000 rw-p 00050000 08:01 3146193                    /usr/lib/libdbus-1.so.3.19.7
7fe1236da000-7fe12375a000 r-xp 00000000 08:01 4075601                    /usr/lib/pulseaudio/libpulsecommon-11.1.so
7fe12375a000-7fe12395a000 ---p 00080000 08:01 4075601                    /usr/lib/pulseaudio/libpulsecommon-11.1.so
7fe12395a000-7fe12395c000 r--p 00080000 08:01 4075601                    /usr/lib/pulseaudio/libpulsecommon-11.1.so
7fe12395c000-7fe12395d000 rw-p 00082000 08:01 4075601                    /usr/lib/pulseaudio/libpulsecommon-11.1.so
7fe12395d000-7fe12396e000 r-xp 00000000 08:01 3155331                    /usr/lib/libXext.so.6.4.0
7fe12396e000-7fe123b6d000 ---p 00011000 08:01 3155331                    /usr/lib/libXext.so.6.4.0
7fe123b6d000-7fe123b6e000 r--p 00010000 08:01 3155331                    /usr/lib/libXext.so.6.4.0
7fe123b6e000-7fe123b6f000 rw-p 00011000 08:01 3155331                    /usr/lib/libXext.so.6.4.0
7fe123b6f000-7fe123b74000 r-xp 00000000 08:01 3147588                    /usr/lib/libXfixes.so.3.1.0
7fe123b74000-7fe123d73000 ---p 00005000 08:01 3147588                    /usr/lib/libXfixes.so.3.1.0
7fe123d73000-7fe123d74000 r--p 00004000 08:01 3147588                    /usr/lib/libXfixes.so.3.1.0
7fe123d74000-7fe123d75000 rw-p 00005000 08:01 3147588                    /usr/lib/libXfixes.so.3.1.0
7fe123d75000-7fe123d7e000 r-xp 00000000 08:01 3161199                    /usr/lib/libXrender.so.1.3.0
7fe123d7e000-7fe123f7e000 ---p 00009000 08:01 3161199                    /usr/lib/libXrender.so.1.3.0
7fe123f7e000-7fe123f7f000 r--p 00009000 08:01 3161199                    /usr/lib/libXrender.so.1.3.0
7fe123f7f000-7fe123f80000 rw-p 0000a000 08:01 3161199                    /usr/lib/libXrender.so.1.3.0
7fe123f80000-7fe123fa7000 r-xp 00000000 08:01 3150109                    /usr/lib/libxcb.so.1.1.0
7fe123fa7000-7fe1241a7000 ---p 00027000 08:01 3150109                    /usr/lib/libxcb.so.1.1.0
7fe1241a7000-7fe1241a8000 r--p 00027000 08:01 3150109                    /usr/lib/libxcb.so.1.1.0
7fe1241a8000-7fe1241a9000 rw-p 00028000 08:01 3150109                    /usr/lib/libxcb.so.1.1.0
7fe1241a9000-7fe1241ec000 r-xp 00000000 08:01 3149531                    /usr/lib/libGL.so.1.0.0
7fe1241ec000-7fe124205000 r-xp 00043000 08:01 3149531                    /usr/lib/libGL.so.1.0.0
7fe124205000-7fe124219000 r-xp 0005c000 08:01 3149531                    /usr/lib/libGL.so.1.0.0
7fe124219000-7fe124418000 ---p 00070000 08:01 3149531                    /usr/lib/libGL.so.1.0.0
7fe124418000-7fe124432000 r--p 0006f000 08:01 3149531                    /usr/lib/libGL.so.1.0.0
7fe124432000-7fe124433000 rw-p 00089000 08:01 3149531                    /usr/lib/libGL.so.1.0.0
7fe124433000-7fe124434000 rw-p 00000000 00:00 0
7fe124434000-7fe124483000 r-xp 00000000 08:01 3155836                    /usr/lib/libpulse.so.0.20.2
7fe124483000-7fe124682000 ---p 0004f000 08:01 3155836                    /usr/lib/libpulse.so.0.20.2
7fe124682000-7fe124684000 r--p 0004e000 08:01 3155836                    /usr/lib/libpulse.so.0.20.2
7fe124684000-7fe124685000 rw-p 00050000 08:01 3155836                    /usr/lib/libpulse.so.0.20.2
7fe124685000-7fe12475c000 r-xp 00000000 08:01 3146149                    /usr/lib/libasound.so.2.0.0
7fe12475c000-7fe12495c000 ---p 000d7000 08:01 3146149                    /usr/lib/libasound.so.2.0.0
7fe12495c000-7fe124964000 r--p 000d7000 08:01 3146149                    /usr/lib/libasound.so.2.0.0
7fe124964000-7fe124965000 rw-p 000df000 08:01 3146149                    /usr/lib/libasound.so.2.0.0
7fe124965000-7fe124974000 r-xp 00000000 08:01 3161193                    /usr/lib/libXi.so.6.1.0
7fe124974000-7fe124b74000 ---p 0000f000 08:01 3161193                    /usr/lib/libXi.so.6.1.0
7fe124b74000-7fe124b75000 r--p 0000f000 08:01 3161193                    /usr/lib/libXi.so.6.1.0
7fe124b75000-7fe124b76000 rw-p 00010000 08:01 3161193                    /usr/lib/libXi.so.6.1.0
7fe124b76000-7fe124b80000 r-xp 00000000 08:01 3158987                    /usr/lib/libXrandr.so.2.2.0
7fe124b80000-7fe124d7f000 ---p 0000a000 08:01 3158987                    /usr/lib/libXrandr.so.2.2.0
7fe124d7f000-7fe124d80000 r--p 00009000 08:01 3158987                    /usr/lib/libXrandr.so.2.2.0
7fe124d80000-7fe124d81000 rw-p 0000a000 08:01 3158987                    /usr/lib/libXrandr.so.2.2.0
7fe124d81000-7fe124d83000 r-xp 00000000 08:01 3162696                    /usr/lib/libXinerama.so.1.0.0
7fe124d83000-7fe124f82000 ---p 00002000 08:01 3162696                    /usr/lib/libXinerama.so.1.0.0
7fe124f82000-7fe124f83000 r--p 00001000 08:01 3162696                    /usr/lib/libXinerama.so.1.0.0
7fe124f83000-7fe124f84000 rw-p 00002000 08:01 3162696                    /usr/lib/libXinerama.so.1.0.0
7fe124f84000-7fe124f8d000 r-xp 00000000 08:01 3159461                    /usr/lib/libXcursor.so.1.0.2
7fe124f8d000-7fe12518c000 ---p 00009000 08:01 3159461                    /usr/lib/libXcursor.so.1.0.2
7fe12518c000-7fe12518d000 r--p 00008000 08:01 3159461                    /usr/lib/libXcursor.so.1.0.2
7fe12518d000-7fe12518e000 rw-p 00009000 08:01 3159461                    /usr/lib/libXcursor.so.1.0.2
7fe12518e000-7fe1252c7000 r-xp 00000000 08:01 3151376                    /usr/lib/libX11.so.6.3.0
7fe1252c7000-7fe1254c7000 ---p 00139000 08:01 3151376                    /usr/lib/libX11.so.6.3.0
7fe1254c7000-7fe1254c8000 r--p 00139000 08:01 3151376                    /usr/lib/libX11.so.6.3.0
7fe1254c8000-7fe1254cd000 rw-p 0013a000 08:01 3151376                    /usr/lib/libX11.so.6.3.0
7fe1254cd000-7fe125680000 r-xp 00000000 08:01 3147640                    /usr/lib/libc-2.27.so
7fe125680000-7fe12587f000 ---p 001b3000 08:01 3147640                    /usr/lib/libc-2.27.so
7fe12587f000-7fe125883000 r--p 001b2000 08:01 3147640                    /usr/lib/libc-2.27.so
7fe125883000-7fe125885000 rw-p 001b6000 08:01 3147640                    /usr/lib/libc-2.27.so
7fe125885000-7fe125889000 rw-p 00000000 00:00 0
7fe125889000-7fe125a1c000 r-xp 00000000 08:01 3147293                    /usr/lib/libm-2.27.so
7fe125a1c000-7fe125c1c000 ---p 00193000 08:01 3147293                    /usr/lib/libm-2.27.so
7fe125c1c000-7fe125c1d000 r--p 00193000 08:01 3147293                    /usr/lib/libm-2.27.so
7fe125c1d000-7fe125c1e000 rw-p 00194000 08:01 3147293                    /usr/lib/libm-2.27.so
7fe125c1e000-7fe125c25000 r-xp 00000000 08:01 3147322                    /usr/lib/librt-2.27.so
7fe125c25000-7fe125e24000 ---p 00007000 08:01 3147322                    /usr/lib/librt-2.27.so
7fe125e24000-7fe125e25000 r--p 00006000 08:01 3147322                    /usr/lib/librt-2.27.so
7fe125e25000-7fe125e26000 rw-p 00007000 08:01 3147322                    /usr/lib/librt-2.27.so
7fe125e26000-7fe125e29000 r-xp 00000000 08:01 3147306                    /usr/lib/libdl-2.27.so
7fe125e29000-7fe126028000 ---p 00003000 08:01 3147306                    /usr/lib/libdl-2.27.so
7fe126028000-7fe126029000 r--p 00002000 08:01 3147306                    /usr/lib/libdl-2.27.so
7fe126029000-7fe12602a000 rw-p 00003000 08:01 3147306                    /usr/lib/libdl-2.27.so
7fe12602a000-7fe126043000 r-xp 00000000 08:01 3147875                    /usr/lib/libpthread-2.27.so
7fe126043000-7fe126242000 ---p 00019000 08:01 3147875                    /usr/lib/libpthread-2.27.so
7fe126242000-7fe126243000 r--p 00018000 08:01 3147875                    /usr/lib/libpthread-2.27.so
7fe126243000-7fe126244000 rw-p 00019000 08:01 3147875                    /usr/lib/libpthread-2.27.so
7fe126244000-7fe126248000 rw-p 00000000 00:00 0
7fe126248000-7fe12626d000 r-xp 00000000 08:01 3147641                    /usr/lib/ld-2.27.so
7fe12626d000-7fe12626e000 rw-p 00000000 00:00 0
7fe12626e000-7fe12626f000 rw-s 00000000 00:15 121                        /dev/shm/mono.13017
7fe12626f000-7fe126271000 rw-s 00000000 00:29 31                         /tmp/.glFKms47 (deleted)
7fe126271000-7fe126272000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe126272000-7fe126276000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe126276000-7fe126277000 rw-s 00000000 00:06 431                        /dev/nvidia0
7fe126277000-7fe126414000 r--p 00000000 08:01 3165726                    /usr/lib/locale/locale-archive
7fe126414000-7fe126427000 rw-p 00000000 00:00 0
7fe126427000-7fe126428000 rw-s 00000000 00:06 431                        /dev/nvidia0
7fe126428000-7fe126429000 rw-s 00000000 00:06 431                        /dev/nvidia0
7fe126429000-7fe12642a000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe12642a000-7fe12642b000 rw-s 00000000 00:06 430                        /dev/nvidiactl
7fe12642b000-7fe12642c000 ---p 00000000 00:00 0
7fe12642c000-7fe12646c000 rw-p 00000000 00:00 0
7fe12646c000-7fe12646d000 r--p 00024000 08:01 3147641                    /usr/lib/ld-2.27.so
7fe12646d000-7fe12646e000 rw-p 00025000 08:01 3147641                    /usr/lib/ld-2.27.so
7fe12646e000-7fe12646f000 rw-p 00000000 00:00 0
7ffc19069000-7ffc19071000 ---p 00000000 00:00 0
7ffc19840000-7ffc19868000 rw-p 00000000 00:00 0                          [stack]
7ffc1995c000-7ffc1995f000 r--p 00000000 00:00 0                          [vvar]
7ffc1995f000-7ffc19961000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Native stacktrace:

        godot-mono() [0xadaff3]
        godot-mono() [0xa55670]
        godot-mono(_ZN12GDMonoMethod6invokeEP11_MonoObjectPPK7VariantPS1_+0x14) [0xd5b864]

Debug info from gdb:

[New LWP 13018]
[New LWP 13020]
[New LWP 13021]
[New LWP 13022]
[New LWP 13023]
[New LWP 13024]
[New LWP 13025]
[New LWP 13026]
[New LWP 13027]
[New LWP 13032]
[New LWP 13033]
[New LWP 13034]
[New LWP 13035]
[New LWP 13036]
[New LWP 13037]
[New LWP 13050]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fe12603b3ea in waitpid () from /usr/lib/libpthread.so.0
  Id   Target Id         Frame
* 1    Thread 0x7fe126414800 (LWP 13017) "godot-mono" 0x00007fe12603b3ea in waitpid () from /usr/lib/libpthread.so.0
  2    Thread 0x7fe12646b700 (LWP 13018) "godot-mono" 0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  3    Thread 0x7fe11dfa2700 (LWP 13020) "godot-mono" 0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  4    Thread 0x7fe10df61700 (LWP 13021) "godot-mono" 0x00007fe12603ae00 in nanosleep () from /usr/lib/libpthread.so.0
  5    Thread 0x7fe10c110700 (LWP 13022) "godot-mono" 0x00007fe1255928b0 in nanosleep () from /usr/lib/libc.so.6
  6    Thread 0x7fe1033ff700 (LWP 13023) "SGen worker" 0x00007fe126036ffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  7    Thread 0x7fe103d7b700 (LWP 13024) "Finalizer" 0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  8    Thread 0x7fe10c06f700 (LWP 13025) "godot-mono" 0x00007fe12603ae00 in nanosleep () from /usr/lib/libpthread.so.0
  9    Thread 0x7fe103b7a700 (LWP 13026) "godot-mono" 0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  10   Thread 0x7fe103b39700 (LWP 13027) "godot-mono" 0x00007fe12603ae00 in nanosleep () from /usr/lib/libpthread.so.0
  11   Thread 0x7fe1008ff700 (LWP 13032) "godot-mono" 0x00007fe1260373f6 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  12   Thread 0x7fe1006fe700 (LWP 13033) "Thread Pool Wor" 0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
  13   Thread 0x7fe1004fd700 (LWP 13034) "Thread Pool Wor" 0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
  14   Thread 0x7fe1002fc700 (LWP 13035) "Thread Pool Wor" 0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
  15   Thread 0x7fe0f5ffd700 (LWP 13036) "Thread Pool Wor" 0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
  16   Thread 0x7fe0f5dfc700 (LWP 13037) "Thread Pool Wor" 0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
  17   Thread 0x7fe0f5bfb700 (LWP 13050) "Thread Pool Wor" 0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0

Thread 17 (Thread 0x7fe0f5bfb700 (LWP 13050)):
#0  0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe126039b63 in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x0000000000c19370 in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 16 (Thread 0x7fe0f5dfc700 (LWP 13037)):
#0  0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe126039b63 in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x0000000000c19370 in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 15 (Thread 0x7fe0f5ffd700 (LWP 13036)):
#0  0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe126039b63 in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x0000000000c19370 in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 14 (Thread 0x7fe1002fc700 (LWP 13035)):
#0  0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe126039b63 in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x0000000000c19370 in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 13 (Thread 0x7fe1004fd700 (LWP 13034)):
#0  0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe126039b63 in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x0000000000c19370 in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 12 (Thread 0x7fe1006fe700 (LWP 13033)):
#0  0x00007fe126039a52 in do_futex_wait () from /usr/lib/libpthread.so.0
#1  0x00007fe126039b63 in __new_sem_wait_slow () from /usr/lib/libpthread.so.0
#2  0x0000000000c19370 in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 11 (Thread 0x7fe1008ff700 (LWP 13032)):
#0  0x00007fe1260373f6 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000000000ca23be in ?? ()
#2  0x0000000000ca9ba9 in ?? ()
#3  0x0000000000c19edb in ?? ()
#4  0x0000000000c27993 in ?? ()
#5  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 10 (Thread 0x7fe103b39700 (LWP 13027)):
#0  0x00007fe12603ae00 in nanosleep () from /usr/lib/libpthread.so.0
#1  0x00000000023560bb in ?? ()
#2  0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7fe103b7a700 (LWP 13026)):
#0  0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007fe126039958 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x000000000202d25d in ?? ()
#3  0x0000000005301ac0 in ?? ()
#4  0x00000000013bf55c in EditorResourcePreview::_thread() ()
#5  0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7fe10c06f700 (LWP 13025)):
#0  0x00007fe12603ae00 in nanosleep () from /usr/lib/libpthread.so.0
#1  0x00000000023560bb in ?? ()
#2  0x0000000000000000 in ?? ()

Thread 7 (Thread 0x7fe103d7b700 (LWP 13024)):
#0  0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007fe126039958 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x0000000000b7bd8c in ?? ()
#3  0x0000000000c27993 in ?? ()
#4  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7fe1033ff700 (LWP 13023)):
#0  0x00007fe126036ffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000000000c91543 in ?? ()
#2  0x00007fe126031075 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007fe1255c553f in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fe10c110700 (LWP 13022)):
#0  0x00007fe1255928b0 in nanosleep () from /usr/lib/libc.so.6
#1  0x00007fe1255bda04 in usleep () from /usr/lib/libc.so.6
#2  0x0000000001136253 in JoypadLinux::monitor_joypads() ()
#3  0x706e692f7665642f in ?? ()
#4  0x746e6576652f7475 in ?? ()
#5  0x0000000000003133 in ?? ()
#6  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7fe10df61700 (LWP 13021)):
#0  0x00007fe12603ae00 in nanosleep () from /usr/lib/libpthread.so.0
#1  0x00000000023560bb in ?? ()
#2  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7fe11dfa2700 (LWP 13020)):
#0  0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007fe126039958 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x000000000202d25d in ?? ()
#3  0x00007fe11dfa3020 in ?? ()
#4  0x0000000001ed05dc in VisualServerScene::_gi_probe_bake_thread() ()
#5  0x0000000004822090 in ?? ()
#6  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7fe12646b700 (LWP 13018)):
#0  0x00007fe126039856 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007fe126039958 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x000000000202d25d in ?? ()
#3  0x00000000045bc630 in ?? ()
#4  0x00000000021ee216 in _IP_ResolverPrivate::_thread_function(void*) ()
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7fe126414800 (LWP 13017)):
#0  0x00007fe12603b3ea in waitpid () from /usr/lib/libpthread.so.0
#1  0x0000000000adb0bc in ?? ()
#2  0x0000000000a55670 in ?? ()
#3  0x0000000000d5b864 in GDMonoMethod::invoke(_MonoObject*, Variant const**, _MonoObject**) ()
#4  0x00007ffc19864cc0 in ?? ()
#5  0x0000000000000098 in ?? ()
#6  0x00000000174c76a8 in ?? ()
#7  0x00007ffc19864cc4 in ?? ()
#8  0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================```

**Comment by NathanWarden** [comment]
@akien-mga  Yep, I think that's a great idea. I'll try and tackle that tonight :)

**Comment by akien-mga** [comment]
The "enhancement" part of this issue is fixed by #19589, but I'm still concerned about this crash @xfactor2000 had.

**Comment by xfactor2000** [comment]
Hi, the problem still persists in Godot 3.0.5. The `--build-solutions` just runs the binary without rebuilding it. The rebuild only happens when I run `--build-solutions -e`, but then I get exception similar to the one posted above.

**Comment by xfactor2000** [comment]
The problem also persists in 3.0.6 `--build-solutions` now opens the editor window and tries to run the project, but then crashes with stacktrace similar to the one above

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch or latest beta build?

**Comment by akien-mga** [comment]
No answer, and I can't reproduce it in 3.2 beta 5, so closing.
