### ISSUE TITLE
New 3.1 slider boxes work terribly with a Wacom tablet

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#19692]
**Godot version:**
current master of 3.1

**OS/device including version:**
Win10 960m

**Issue description:**
The new slider boxes in 3.1 don't work at all with a Wacom tablet. I am using an Intuos Pro, but this problem likely exists with all models. The sliders with the circle work ok, but the slider boxes with no graphical slider just jump to a random location in the positive direction, regardless of how much I move the cursor or in which direction.

As illustrated in this gif, I am only very slightly moving the cursor for these massive jumps. I should note that every other piece of software I use works with a Wacom correctly, including non graphic apps like DAWS and browsers.

![wacom_sliders](https://user-images.githubusercontent.com/7741669/41698923-703e6da2-7564-11e8-8f84-083cfc758271.gif)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by speckledsea** [comment]
It seems that I'm also having issues.  For me towards, with the stylus on the left or right side the number jumps either to min or max value respectively, without moving the stylus at all.  Moving the stylus up or down does nothing and neither does the _y_ position.  It feels like the absolute _x_ position (with origin being the center of the tablet) is being added directly to the value every update.

**Godot version:**
3.1.dev.custom_build.2365fe4
**OS:**
Arch Linux (4.17.2-1-ARCH)
**Tablet:**
Wacom Co., Ltd CTE-650 [Bamboo Fun (medium)]

**Comment by fracteed** [comment]
@speckledsea yeah, for me in 3.1 I can barely click on a sliderbox to be able to even type in a value. As soon as you try to click a box to get the cursor it will jump to a random value. As seen at the very start of the gif above, it even does this with the standard circle slider.

I have been using an Intuos almost exclusively in Godot pre 3.1 and it mostly works. except for the stuck cursor bug which happened on sliders. This was not related to the Wacom though as it also happened with mouse/trackpad for me. With 3.1 the stuck cursor bug has gone, but the aforementioned issues have taken it's place.

**Comment by reduz** [comment]
this has been fixed in master, with the switch to RawInput

**Comment by guilhermefelipecgs** [comment]
Linux still have this issue. @reduz's modifications 2db4942 should be able to be implemented after #19191.

CC @cosmicchipsocket

**Comment by cosmicchipsocket** [comment]
I'll see if I can get my PR fixed tonight. What about macOS and Haiku? Will they be getting raw input support?

**Comment by guilhermefelipecgs** [comment]
Only if someone knows/wants to implement for these platforms.
