### ISSUE TITLE
export doesn't work with enums from another script/class

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19704]
neither of the following work, where `g` is set to autoload
```gdscript
export var type = g.BMW
export(g.Type) var type = g.BMW
```
gives error:
```
built-in:7 - Parse Error: invalid index 'BMW' in constant expression
modules/gdscript/gdscript.cpp:583 - Method/Function Failed, returning: ERR_PARSE_ERROR
```
this works tho':
```gdscript
var type = g.BMW
```

See attached project 
[godot-dbg.zip](https://github.com/godotengine/godot/files/2124482/godot-dbg.zip)

*edit*
although it seems that if you close&reopen the project (possibly the scene, didn't try that one) the error disappears so you might have to recreate from scratch the simple project I attached.

**Comment by mhilbrunner** [comment]
On master or 3.0.3? Or both?

**Comment by vnen** [comment]
Isn't this the same as #14681?

**Comment by razvanc-r** [comment]
I found something perhaps related. Like the above, `g` is a singleton script and doing something like

```gdscript
export(g.EntityType) var type setget _set_type
```
triggers the setter with a `null` value in all cases (before the children nodes etc. are ready).

In my script I have

```gdscript
export(g.EntityType) var type setget _set_type

func _set_type(val):
	# I'm forced to use this otherwise game crashes, even if I don't set `type` anywhere
	# in the script or inspector, it gets called by itself with `val = null` when
	# $Pattern (in this case) isn't present in the scene tree
	if val == null:
		return

	var type = val
	$Pattern.entity_type = type
```

**Comment by chaigler** [comment]
Confirmed - still an issue as of 3.1 alpha 4.

**Comment by joaquin-montesdeoca** [comment]
Sorry to bother you but, was this released with the v3.1.beta3.official?

In said version, it doesn't seem to work properly yet. But I don't know if this commit was included in said version or if it will be included in the following one?

**Comment by akien-mga** [comment]
The fix was included in 3.1 beta 3, but the bug is indeed still reproducible in the current master branch.

**Comment by jabcross** [comment]
This also seems to happen with built-in enums.

`export (Tween.TransitionType) var transition_type := Tween.TRANS_CUBIC`

gives me the error

`invalid index 'TransitionType' in constant expression`

**Comment by akien-mga** [comment]
Another MRP from #26537:

> Confirmed in 49d82f2:
>
> ```
> SCRIPT ERROR: GDScript::reload: Parse Error: invalid index 'TEXT_SPAM_BASIC' in constant expression
>    At: res://Node2D.gd:3.
> ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
>    At: modules/gdscript/gdscript.cpp:580.
> ```
> 
> Interestingly, it actually works fine when you run the game.
>
> MRP: New Game Project.zip

**Comment by that-richard** [comment]
Still happens to me? 
![image](https://user-images.githubusercontent.com/11839880/80120039-bd87dc00-858a-11ea-95a3-8a2b7ea03d9f.png)

**Comment by Zireael07** [comment]
@that-richard: I believe this was a fix for GDScript, not c#

**Comment by that-richard** [comment]
> @that-richard: I believe this was a fix for GDScript, not c#

That is GDScript, I just have an external editor (VSCode) :D

**Comment by eastrd** [comment]
Hi, this issue is still happening in my 3.2.2

**Comment by ArjunNair** [comment]
Can confirm I see this issue v3.2.3 stable. Steps to reproduce:
1) Declare an enum in one class:
`
class A:
....
enum Something {
   BORING,
   INTERESTING
}
`
Then try to export a variable of Something type in a different class:
`
class B:
....
export(Something) var stuff = Something.BORING <- Doesn't work
`
even if class A is declared with a class_name and accessed in class B:
`
export(A.Something) var stuff = A.Something.BORING <- Doesn't work
`
The only way to get the above to work is not assigning a default value to the export var (as mentioned by someone before):
`
export(A.Something) var stuff
`

Can we re-open this issue please?

**Comment by akien-mga** [comment]
It would be better to open a new issue with a new minimum reproduction project. This was fixed in 3.1 so what you're experiencing might be a different bug, even if the symptoms are similar.

**Comment by jh62** [comment]
Still happens to me un 3.2.3 if I autoload a class with an enum and use it somewhere else. Look at this, happens everytime i restart Godot and then goes away if I do this:

![aNt58GsX9G](https://user-images.githubusercontent.com/22467336/117103752-46feec00-ad51-11eb-9c06-dfcf14a9629b.gif)

**Comment by akien-mga** [comment]
I've already asked that new reports should go to a new issue. Locking this one.
