### ISSUE TITLE
On Android whole screen or part of it flickers all the time.

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot#19820]
**Godot version:**
eeab3502d5eec68dbce2d7b7ff822a14e6a3599c
it also happens on the official 3.0 release (downloaded today from https://downloads.tuxfamily.org/godotengine/) but I didn't see this in versions before release 3.0. last correctly working version 3.0-beta2

**OS/device including version:**
Meizu m1 metal, OnePlus One.
Android 5.1, Android 7.0.
MTK MT6795, Qualcomm Snapdragon 801.

**Issue description:**
On meizu flickers only the left side of the screen.
On the oneplus one, the whole screen flickers.
But now I can choose GLES2 on android and it works correctly.

(First is GLES2 and second GLES3)
![bug](https://user-images.githubusercontent.com/7782218/42015301-72b63ccc-7aaf-11e8-94e4-4772bfaa8fa1.gif)

**Steps to reproduce:**
create project and export it for android with GLES3 render

**Comment by Tarkenton** [comment]
My phones been hacked it’s iOS and I cannot figure out how to stop them any ideas anyone

**Comment by CereEnder** [comment]
The flickers I have fixed' using less resolution, setting "viewport" and stretch mode to "fit_width", but you will have black bars.

**Comment by Calinou** [comment]
@DmitriySalnikov Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

Note that we no longer recommend using GLES3 on mobile for the time being.

**Comment by DmitriySalnikov** [comment]
@Calinou same in 3.2.1 and 3.2.2 (official release and version from [https://downloads.tuxfamily.org/](https://downloads.tuxfamily.org/godotengine/3.2.2/beta4/))
But if not whole screen filled with image everything ok. (stretch aspect option)
Test project: [TestFlickering.zip](https://github.com/godotengine/godot/files/4743255/TestFlickering.zip)
A_I - aspect ignore
A_KH - aspect keep height

https://yadi.sk/i/DQBBrnrSO5n6Cg

**Comment by DmitriySalnikov** [comment]
No one has reported such behavior and I won't be able to reproduce it anymore, so I'm closing the issue.
