### ISSUE TITLE
Godot doesn't start External Editor when clicking on error messages in Debugging panel

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot#19838]
**Godot version:**
3.0.4

**OS/device including version:**
Windows 8.1

**Issue description:**
When setting Godot to use a external editor for editing scripts it won't run the external editor when clicking on the Stack Frames in the Debugger/Debugger tab.

It does run the editor when clicking on the entries in the stack trace of the Debugging/Error tab but many issues don't cause a stack trace to be generated.

**Comment by API-Beast** [comment]
Found two more situations in which neither the external editor nor the internal editor is not launched:
- If the script is internal the external editor won't launch
- When using the "Make Function" setting in the Signal Editor

**Comment by rcorre** [comment]
>- When using the "Make Function" setting in the Signal Editor

I don't have a computer with me, but I'm pretty sure that does launch the external editor for me. It doesn't generate the function, but I think I filed a separate issue about that.

- Ryan

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by rcorre** [comment]
@akien-mga yes, just tried `3.1.beta.custom_build.16d4021` with `exec_path=st`, `exec_flags=nvim {file} +{line}`. One of these shows up in "errors" every time I double-click a line in the stack:

```
E 0:00:04:0725   Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
  <C Source>     modules/gdscript/gdscript_editor.cpp:321 @ debug_get_stack_level_instance()
```

**Comment by KoBeWi** [comment]
Still valid in 3.2.2 rc1. Tested with VS Code, clicking Stack Frames doesn't even open the file.

The issues mentioned in https://github.com/godotengine/godot/issues/19838#issuecomment-404545993 are fixed.

**Comment by duane-r** [comment]
In v3.2.4.rc2, nothing happens when I click on a stack frame in the debugger tab -- neither the internal nor external editors open -- as long as the external editor is enabled.

**Comment by painttist** [comment]
Hi, in v4.2.2.rc, I am still having this issue.

After some digging around, I found out that this is related to `ScriptEditor::edit` inside `editor>plugins>script_editor_plugin.cpp`, in line 2308, there is an if statement that prevents debugger script being opened in an external editor unless an option DEBUG_WITH_EXTERNAL_EDITOR is checked. To my understanding, this toggleable option is currently only accessible by setting a shortcut for item "Debug with External Editor".

I suspect that there used to be a checkbox that could be used to toggle this setting but is now removed?

I would love to contribute further and submit a PR to fix this issue but I am uncertain if I should simply remove part of the if statement in line 2308 or should I attempt to add back a checkbox?

**Comment by drakmirv** [comment]
This seems to work if this option is enabled in the Script Editor panel:

![Image](https://github.com/user-attachments/assets/9fb0ddab-dc65-4bed-8c71-87e9b550c4b7)

**Comment by chrisl8** [comment]
> This seems to work if this option is enabled in the Script Editor panel:
> 
> ![Image](https://github.com/user-attachments/assets/9fb0ddab-dc65-4bed-8c71-87e9b550c4b7)

@drakmirv  Thank you! Yes. this seems to "fix" it? It seems odd that this buried checkbox has to be selected to obtain the functionality we hoped to get from setting the editor to external in the regular settings.
