### ISSUE TITLE
Class cannot inherit enum

### ISSUE THREAD

**Issue by pikadon92** [godotengine/godot#20008]
**Godot version:**

3.0.4

**Issue description:**

I created two classes: Class A and Class B. B extends from A. A has an enum. I tried calling the enum in class B, but an error message "Expected a constant expression" pops up. Does that mean that B cannot inherit enum from A?

**Steps to reproduce:**
So in Class A, I have typed the following:

`enum NUMBER{`
`    ONE,`
`    TWO,`
`    THREE`
`}`

`export(NUMBER) number_a`

No issue so far. In Class B, it has the following code:

`extends "res://Class_A.gd"'
'export(NUMBER) number_b`

At the "export(NUMBER) number_b" line, the error message "Expected a constant expression" pops up.

**Comment by romlok** [comment]
I've been able to replicate this. It certainly seems like something which should work.

From what I can tell, the issue seems to be that Godot does not recognise `NUMBER` as a valid hint when it parses the export statement for validity. Every other access of `NUMBER` or its values at any other point inside Class_B seems to work as expected.

**Comment by bojidar-bg** [comment]
Was this fixed by #20468

**Comment by romlok** [comment]
Just tested with the latest master (96d37769d) and this problem still occurs.

**Comment by cgxeiji** [comment]
Just updated to the latest master (https://github.com/godotengine/godot/commit/0239d8bd9fa03965439aac2482d18746f807bd00) and the problem is still present.

> "res://ChildScript.gd:3 - Parse Error: Expected a constant expression."

when trying to refer to the parent class' enum.

**Comment by Angular-Angel** [comment]
Aye, same thing here. 3.1 Stable Official, still happening.

**Comment by jw-0** [comment]
Issue persists when importing enum defined in a singleton class (v3.2.dev.custom_build.2931b4d)
`enum Alignment { Player, Enemy, None }` 
defined in unit_enums.gd, set up as an autoload singleton and then called from script as

`onready var enums = get_node("/root/unit_enums")`
`export (enums.Alignment) var alignment = enums.Alignment.None`

**Comment by bojidar-bg** [comment]
Cannot confirm on 4cb0887660861402fe6857662e622488adb86514.
Cannot find which change fixed it, going to do a quick rebase now.

**Comment by bojidar-bg** [comment]
Hmm, that's bad, I cannot confirm on 0239d8b either.

@cgxeiji Could you provide a sample project and some OS details?

**Comment by cgxeiji** [comment]
@bojidar-bg Hello, and no problem! I just recompiled to https://github.com/godotengine/godot/commit/0239d8bd9fa03965439aac2482d18746f807bd00 and got:

> Godot Engine v3.2.dev.custom_build (c) 2007-2019 Juan Linietsky, Ariel Manzur & Godot Contributors.
> Switch Scene Tab
> - res://Child.gd:3 - Parse Error: Expected a constant expression.
> - modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR

The sample project is [here](https://github.com/cgxeiji/Godot-Enum-Test).

OS details:
`Linux 5.1.12-arch1-1-ARCH x86_64 GNU/Linux`

The scripts I am using are:
```
# Parent.gd
extends Node

class_name ParentNode

enum Type {
	ONE,
	TWO,
	THREE
}

# This works
export(Type) var TypeExport

func _ready():
	pass
```
```
# Child.gd
extends ParentNode

# This raises an error
export(Type) var TypeExportChild

func _ready():
	pass
```

**Comment by cgxeiji** [comment]
@bojidar-bg It's fixed in master (2293c612e)! :D Thank you for your amazing work!

**Comment by akien-mga** [comment]
Thanks for testing, closing as fixed by #30289.

**Comment by CJCarns** [comment]
The issue of enums and "expecting constant expressions" has suddenly remerged in the latest version of Godot. I closed my editor and reopened it to find my entire project, which heavily relies on enums for keys in constant dictionaries, broken.
