### ISSUE TITLE
Organizing Godot 3.1 Alpha

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#20313]
We should start organizing work for 3.1 alpha. I myself am done with what I was working with, so opening this issue with the intention of making sure we are all on the same page and what needs to be done is done.

#### GLES2
@karroffel Is working on GLES2. I think his work is more or less complete, or in a good enough state so users can start testing it. What is missing?

#### Mono
@neikeq Has been doing a lot of fixes to export and debugging. Is there anything else that should be included?

#### Typed GDScript
@vnen's work on typed GDScript is more or less done, is there anything missing for merging?

#### Physics improvements
@AndreaCatania has working PRs for IK and softbodies, which should be completed and merged. Both where more or less done.

#### Visual script UX improvements
@fire was working on several VS improvements, i think his work was almost ready for merging

#### Android Export
@hpvb fixed the exporter, and is working on adding built-in signing support, so we don't depend on installing Java if you want to do basic exports. Also working on some Godot optimizations.

What am I missing?

**Comment by vnen** [comment]
Typed GDScript is pretty much done and ready to merge. I want some broader testing to catch potential issues.

**Comment by suptoasty** [comment]
Does @djrm have any theme improvements for 3.1 or is it just focused on usability improvements? Also before this thread gets flooded with them...are issue numbers okay to post here?

**Comment by CCODE05B** [comment]
@reduz you promised this will be in 3.1 https://github.com/godotengine/godot/issues/9786 :( 

![please](https://user-images.githubusercontent.com/34812055/43034868-d59ce9a2-8ce4-11e8-84c4-df9edefe81b9.jpg)

**Comment by reduz** [comment]
@CCODE05B No. No further 3D work will be done until port to Vulkan happens after 3.1 is out.

**Comment by CCODE05B** [comment]
![cry_pc](https://user-images.githubusercontent.com/34812055/43035648-fc494e88-8cf3-11e8-91fc-7a590ea2f89a.jpg)

**Comment by Zylann** [comment]
@gaudecker I need to update that tracker, some things in it have been solved since.

Also, #19501 ?

**Comment by mhilbrunner** [comment]
@gaudecker @Zylann Yes, the issue/that tracker will likely have to wait until reduz can work on renderer features again after 3.2/Vulkan.

**Comment by mhilbrunner** [comment]
@reduz Updates on your bullet points:

**Physics improvements** were merged
**VisualScript UX improvements** were merged

Typed GDScript was also merged, warnings are still missing: https://github.com/godotengine/godot/pull/19993

**Comment by volzhs** [comment]
what about converting text resource to binary when exporting?

**Comment by vnen** [comment]
I need to fix #19935 before alpha (besides finishing the warnings thing).

**Comment by mhilbrunner** [comment]
Seems I was wrong, Inverse Kinematics (IK) was not yet merged: https://github.com/godotengine/godot/pull/18699

**Comment by eon-s** [comment]
@Zireael07 CPU particles are already on master, but 2D version is still missing, it seems?

**Comment by efornara** [comment]
@reduz 

>  have on my todo list a bunch of pretty cool culling techniques, but as always out of time for 3.0 #9786

> No. No further 3D work will be done until port to Vulkan happens after 3.1 is out.

Of course, it makes sense to delay these (most likely GPU assisted) techniques until Vulkan, but am I right in assuming that they would not be useable in mobile / low-end anyway?

Just as for particles, wouldn't make sense to also have a CPU culling technique available? Something like the room / portal technique of Godot 2?

**Comment by Geequlim** [comment]
@karroffel @reduz  Will  batching for 2D is still missing in 3.1 ?

**Comment by reduz** [comment]
@Geequlim There is someone working on it

**Comment by Zireael07** [comment]
So what are we missing at this point?

**Comment by starry-abyss** [comment]
How about qwerty scancodes: https://github.com/godotengine/godot/pull/18020 ?

**Comment by AntohaRDNS** [comment]
Amazing work!
Still missing some mesh cache (alembic, etc) handling

**Comment by starry-abyss** [comment]
Also BTW is GSOC work going to get in 3.1?

**Comment by eon-s** [comment]
There are many (old) issues on 2D physics, those will start being addressed for 3.1 or kicked to 3.2?

**Comment by akien-mga** [comment]
As we're nearing beta, closing.
