### ISSUE TITLE
Shaders uniform variables are broken in GL|ES 2 compatibility mode

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#20485]
**Godot version:**
Godot v3 (master - using commit `cfcb6e`)

**OS/device including version:**
- Linux (Ubuntu).
- NVidia GTX960M

**Issue description:**
GL|ES 2 compatibility mode on Godot v3 disables every uniform variables on shaders; they will show as a "[NULL]" not-editable variable, and `set_shader_param()` methods won't work anymore.

**Minimal reproduction project:**
Using the space_shaders demo on master, just change the GL|ES version (top-right button on Godot Editor) to 2; than, checking the uniform variables of each shader, it will just show as [NULL] and it won't be editable anymore.

**Comment by karroffel** [comment]
This is fixed on my branch, this will be fixed once my branch gets merged into master.

**Comment by karroffel** [comment]
Should be fixed now.

**Comment by henriquelalves** [comment]
It's fixed! Unfortunately Particles2D are still broken on GL|ES 2, though. I'll create another issue about it to keep track.
