### ISSUE TITLE
Boot splash loading in main.cpp triggers deprecation warning (regression from ef50957)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#21072]
**Godot version:**
Current master (de0fb079), regression from ef50957.

**OS/device including version:**
Any.

**Issue description:**
When you set an image file as Texture for a Sprite node, the following warning is shown:
```
WARNING: load: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
   At: core/image.cpp:1587.
```

**Steps to reproduce:**
- Drag and drop `icon.png` in the 2D viewport to instantiate a Sprite, or
- Instantiate a Sprite and assign `icon.png` as Texture

**Minimal reproduction project:**
[test_icon_warning.zip](https://github.com/godotengine/godot/files/2316344/test_icon_warning.zip)

**Comment by reduz** [comment]
This was fixed recently, so closing

**Comment by akien-mga** [comment]
You mean this was *introduced* recently, it's a new bug and still not fixed.

**Comment by akien-mga** [comment]
Adding MRP if needed: [test_icon_warning.zip](https://github.com/godotengine/godot/files/2316344/test_icon_warning.zip)

Just run the project from the editor and check console output.

**Comment by volzhs** [comment]
This is what I did.

1. create new project
2. make an empty scene (just only one Node2D)
3. make it default scene
4. run project

then... I got the same error.
```
WARNING: load: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
   At: core/image.cpp:1731.
```

**Comment by akien-mga** [comment]
This is caused by https://github.com/godotengine/godot/blob/08f452d1a95d7f171472c33a60983d95adf1665d/main/main.cpp#L1099-L1105

How should it be done now that `Image.load()` is deprecated?

**Comment by volzhs** [comment]
consider https://github.com/godotengine/godot/commit/ef5095720b56e72d99b8ca2773e2a5fa24f7097d#commitcomment-30084239 also...

> @sketchyfun
> 
> Would that include images outside of the project? Like if a user wanted to load a custom image from their home directory?

**Comment by capnm** [comment]
Currently df73d26314382829e4a7668bc254d7e11bc31f7d  I have 2 warnings when I press play in the editor. One for the project icon, second for the splash image:
```
0:00:00:0152 - Loaded resource as image file, this will not work on export: 'res://splash.png'. Instead, import the image file as an Image resource and load it normally as a resource.
----------
Type:Warning
Description: 
Time: 0:00:00:0152
C Error: Loaded resource as image file, this will not work on export: 'res://splash.png'. Instead, import the image file as an Image resource and load it normally as a resource.
C Source: core/image.cpp:1734
C Function: load
```

```
0:00:00:0719 - Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
----------
Type:Warning
Description: 
Time: 0:00:00:0719
C Error: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
C Source: core/image.cpp:1734
C Function: load
```

**Comment by reduz** [comment]
Yeah, basically need to make an exception for those files only, so will probably add a private function or something.

**Comment by spkingr** [comment]
How to solve this issue? I encountered the same warning in Godot 3.1 alpha version.
