### ISSUE TITLE
Clicking "Occlusion" in the TileSet editor crashes the editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21504]
**Godot version:**
 6b10e37

**Issue description:**
@MarianoGnu 
```
ERROR: get_polygon: Index p_idx=0 out of size (polygons.size()=0)
   At: scene/2d/navigation_polygon.cpp:148.
ERROR: canvas_item_add_polygon: Condition ' pointcount < 3 ' is true.
   At: servers/visual/visual_server_canvas.cpp:668.
ERROR: canvas_item_add_polygon: Condition ' pointcount < 3 ' is true.
   At: servers/visual/visual_server_canvas.cpp:668.
ERROR: operator[]: FATAL: Index p_index=0 out of size (size()=0)
   At: ./core/dvector.h:505.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x37e00) [0x7f0a6142ae00] (??:0)
[2] PoolVector<Vector2>::operator[](int) const (??:0)
[3] TileSetEditor::draw_polygon_shapes() (??:0)
[4] TileSetEditor::_on_workspace_draw() (??:0)
[5] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[7] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[8] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[9] CanvasItem::_update_callback() (??:0)
[10] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[11] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[12] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (??:0)
[13] MessageQueue::flush() (??:0)
[14] SceneTree::idle(float) (??:0)
[15] Main::iteration() (??:0)
[16] OS_X11::run() (??:0)
[17] /home/michael/git/godot/bin/godot.x11.tools.64(main+0xd5) [0x55dd218413fe] (??:0)
[18] /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f0a61417223] (??:0)
[19] /home/michael/git/godot/bin/godot.x11.tools.64(_start+0x2e) [0x55dd2184125e] (??:0)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by MarianoGnu** [comment]
> Issue description:
> @MarianoGnu

Me: Okay 😿

**Comment by drako0812** [comment]
This might be related, but when I've been trying to add colliders to tiles in the TileSet editor, sometimes the Godot Editor crashes. Here's the output from my most previous crash.

```
OpenGL ES 3.0 Renderer: AMD Radeon HD 86
50C:\godot\godot\bin>G
WARNING: Control::grab_focus: This control can't grab focus. Use set_focus_mode() to allow a control to get focus.
     At: scene\gui\control.cpp:2067
WARNING: FileAccessWindows::_open: Case mismatch opening requested file 'code.CMD', stored as 'code.cmd' in the filesystem. This file will not open when exported to other case-sensitive platforms.
     At: drivers\windows\file_access_windows.cpp:104
ERROR: TileSet::tile_get_tile_mode: Condition ' !tile_map.has(p_id) ' is true. returned: SINGLE_TILE
   At: scene\resources\tile_set.cpp:412
ERROR: TileSet::tile_get_region: Condition ' !tile_map.has(p_id) ' is true. returned: Rect2()
   At: scene\resources\tile_set.cpp:399
ERROR: TileSet::tile_get_tile_mode: Condition ' !tile_map.has(p_id) ' is true. returned: SINGLE_TILE
   At: scene\resources\tile_set.cpp:412
ERROR: TileSet::tile_get_shape: Condition ' !tile_map.has(p_id) ' is true. returned: Ref<Shape2D>()
   At: scene\resources\tile_set.cpp:610
ERROR: TileSet::tile_get_light_occluder: Condition ' !tile_map.has(p_id) ' is true. returned: Ref<OccluderPolygon2D>()
   At: scene\resources\tile_set.cpp:671
ERROR: TileSet::tile_get_navigation_polygon: Condition ' !tile_map.has(p_id) ' is true. returned: Ref<NavigationPolygon>()
   At: scene\resources\tile_set.cpp:715
ERROR: TileSet::tile_get_region: Condition ' !tile_map.has(p_id) ' is true. returned: Rect2()
   At: scene\resources\tile_set.cpp:399
ERROR: TileSet::tile_get_tile_mode: Condition ' !tile_map.has(p_id) ' is true. returned: SINGLE_TILE
   At: scene\resources\tile_set.cpp:412
ERROR: TileSet::tile_get_shape: Condition ' !tile_map.has(p_id) ' is true. returned: Ref<Shape2D>()
   At: scene\resources\tile_set.cpp:610
ERROR: TileSet::tile_get_light_occluder: Condition ' !tile_map.has(p_id) ' is true. returned: Ref<OccluderPolygon2D>()
   At: scene\resources\tile_set.cpp:671
ERROR: TileSet::tile_get_navigation_polygon: Condition ' !tile_map.has(p_id) ' is true. returned: Ref<NavigationPolygon>()
   At: scene\resources\tile_set.cpp:715
ERROR: PoolVector<struct Vector2>::operator []: FATAL: Index p_index=-1 out of size (size()=0)
   At: C:\godot\godot\core/dvector.h:505
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] PoolVector<Vector2>::operator[] (c:\godot\godot\core\dvector.h:505)
[1] TileSetEditor::draw_polygon_shapes (c:\godot\godot\editor\plugins\tile_set_editor_plugin.cpp:1870)
[2] TileSetEditor::_on_workspace_draw (c:\godot\godot\editor\plugins\tile_set_editor_plugin.cpp:780)
[3] MethodBind0<TileSetEditor>::call (c:\godot\godot\core\method_bind.gen.inc:140)
[4] Object::call (c:\godot\godot\core\object.cpp:968)
[5] Object::emit_signal (c:\godot\godot\core\object.cpp:1254)
[6] Object::emit_signal (c:\godot\godot\core\object.cpp:1308)
[7] CanvasItem::_update_callback (c:\godot\godot\scene\2d\canvas_item.cpp:340)
[8] MethodBind0<CanvasItem>::call (c:\godot\godot\core\method_bind.gen.inc:140)
[9] Object::call (c:\godot\godot\core\object.cpp:968)
[10] MessageQueue::_call_function (c:\godot\godot\core\message_queue.cpp:256)
[11] MessageQueue::flush (c:\godot\godot\core\message_queue.cpp:302)
[12] SceneTree::iteration (c:\godot\godot\scene\main\scene_tree.cpp:477)
[13] Main::iteration (c:\godot\godot\main\main.cpp:1770)
[14] OS_Windows::run (c:\godot\godot\platform\windows\os_windows.cpp:2736)
[15] widechar_main (c:\godot\godot\platform\windows\godot_win.cpp:150)
[16] _main (c:\godot\godot\platform\windows\godot_win.cpp:174)
[17] main (c:\godot\godot\platform\windows\godot_win.cpp:184)
[18] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[19] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by YeldhamDev** [comment]
This has been fixed. Closing it.

**Comment by DocoDan** [comment]
I am still having this crash in Godot alpha2 3.1 with mono Support 😭

![image](https://user-images.githubusercontent.com/2548272/49691414-dd5b6300-fb41-11e8-87d7-8cd397ff9f1a.png)
