### ISSUE TITLE
3D grid axis lines z-fighting (?).

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#21648]
**Godot version:**
3.1 Alpha 1, x64, Mono

**OS/device including version:**
Windows 10, Nvidia GTX 970, driver version 399.07

**Issue description:**
The axis and grid lines are z fighting or something.
In still shots the grid usually wins out:
![image](https://user-images.githubusercontent.com/8107459/44943589-004edc00-adc9-11e8-829d-9e991accfabe.png)

Sometimes it barely doesn't though, especially while moving.

![image](https://user-images.githubusercontent.com/8107459/44943603-3db36980-adc9-11e8-9407-13203e3a8faa.png)

**Comment by PJB3005** [comment]
Nevermind

**Comment by aaronfranke** [comment]
It was fixed in https://github.com/godotengine/godot/pull/21129, surprised you experienced the issue at all.

**Comment by Calinou** [comment]
I can still reproduce this as of commit https://github.com/godotengine/godot/commit/3a8f8381f210aebf6cb2279f14f8377706438d9c (after starting the editor), even though https://github.com/godotengine/godot/pull/21559 has already been merged. Hiding the origin then displaying it again solves the issue temporarily.

**Comment by PJB3005** [comment]
@aaronfranke it was broken for me in Alpha 1 so I made the report, then realized it was already fixed. I later did check with a master build and it IS fixed on master for me, so I just assumed that that commit just barely didn't make it into the alpha.

**Comment by ludorverr** [comment]
The Raycast line is hidden here, z-fighting with blue axis line.
![raycast_line](https://user-images.githubusercontent.com/15337628/51513876-387eb600-1e61-11e9-850c-c72cdef286c6.png)

Seems like a small issue but as someone new to the engine it really helped me out seeing the raycast line point out from the camera. But you can only see it 50% of the time.
