### ISSUE TITLE
Fullscreen Breaks With Multi Monitors With Different Resolutions

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#21674]
**Godot version:**
3.1 alpha 1

**OS/device including version:**
Windows 10

**Issue description:**
I turned on fullscreen for my game. It opts for the 4K resolution of my second monitor and attempts to display on my primary 1080p monitor. This image is the result.

![2018-09-01](https://user-images.githubusercontent.com/21234930/44950348-5b4cf700-adfa-11e8-8bb8-15e18872fe8c.png)

**Comment by marcelofg55** [comment]
This should be fixed by #23926

**Comment by 11clock** [comment]
Note that for replicating this issue, the primary monitor must be the smaller one.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

This might be related to #21746 somehow

**Comment by Chaosus** [comment]
Yeah, still a valid issue.

**Comment by Chaosus** [comment]
Seems like it's fixed on the master... but I'm not sure

**Comment by emptyhead** [comment]
> Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
> 
> This might be related to #21746 somehow

Can confirm this issue still exists in 3.2.3. Win 10 x64
Some more info, just to make it a bit more complicated.

Two monitors connected by DVI ports on a GTX980:
If "Main" monitor is the larger of the two - game displays on the main monitor centred and clamped to the resolution of the smaller extended monitor.
If "Main" monitor is the smaller of the two - game displays on the smaller main monitor correctly.

Large monitor (Main) connected by DVI to GTX980, small monitor (extended) connected by DVI to Intel HD530 onboard:
Exactly the same, except game wont run when the HD530 monitor is set to main (maybe gpu doesn't support Open GLES 2?).

Now for the fun bit.
Large monitor connected by DVI on GTX980. Smaller monitor connected by HDMI on GTX980:
Works correctly if large DVI monitor is "Main".
If Smaller HDMI monitor is set as "Main" then it attempts to draw it on the smaller monitor. The splash screen appears, but it gets partially drawn on the extended monitor. It then fails on the small Main monitor and draws correctly on the larger (extended) monitor!

Interestingly, where it gets drawn on the larger extended monitor will depend on how the screens are arranged in the Display Settings on Windows. ie. if the small main monitor is to the left of extended monitor it will draw onto the left of extended monitor. If it's above it, it will draw at the top. To the right, it will draw on the right.

If both of these monitors are set at the same resolution it works correctly no matter which monitor is Main or Extended.

Happy to do any further testing if it helps.

**Comment by KoBeWi** [comment]
@emptyhead  Can you check in [Godot 3.2.4 rc1](https://godotengine.org/article/release-candidate-godot-3-2-4-rc-1) too? Quite a lot changed since then.

**Comment by emptyhead** [comment]
Still the same sadly.

I am wondering if it's my GPU as it doesn't really behave consistently with multi-monitor set-up. Sometimes the "night light" doesn't work on one monitor after waking from sleep. The odd bit of corruption - rare, but happens.

More details:
Main monitor (DVI from gtx980) and small monitor (DVI from onboard Intel hd530) - fullscreen clamps it to the resolution of the smaller monitor.
Remove small monitor from intel HD530 - fullscreen works correctly.
Reattach smaller monitor to intel HD530 - fullscreen clamps to resolution of small monitor again.
Add TV (HDMI from gtx980) and set it to same resolution as Main monitor - again, fullscreen clamps it to the resolution of the smaller monitor.
Disconnect smaller monitor - fullscreen now works correctly.
Reattach smaller monitor - fullscreen still works correctly.
Remove TV - fullscreen still works correctly until PC is restarted !!!!

So if I connect a TV to the HDMI port on the 980 it fixes the problem, even if I then remove it afterwards.

Would be interesting to know what was common with everyone who has this issue.

Spec:
GPU: gtx 980 - driver version 461.40 (latest as of 05 Feb 2021) prev 457.xx
OS: Win 10 Pro version 1909 x64
CPU: i5 6600 (with the intel hd530)
Doubt it would be mobo chipset related, but just in case
MOBO: ASRock h170m-itx

**Comment by NanitesNanites** [comment]
Issue still exists with 3.4 (Win 10 21h2, GTX 1080ti)

My setup: main monitor 3440x1440 landscape mode, secondary 1920x1080 portrait mode

If I select Fullscreen in Project Settings->Dispay->Window it will start with a 1080 wide window that is full 1440 main screen high.

**Comment by akien-mga** [comment]
Fixed by #59982.
