### ISSUE TITLE
net_socket warning well running a scene 

### ISSUE THREAD

**Issue by chaosdrop** [godotengine/godot#22038]
**Godot version:**
master as of 2018-09-13

**OS/device including version:**
windows 10

**Issue description:**

I'm getting this warning in the output any scene ran:
 drivers\unix\net_socket_posix.cpp:232 - Condition ' _sock == (SOCKET)(~0) ' is true. returned: FAILED
 core\io\tcp_server.cpp:56 - Condition ' err != OK ' is true. returned: ERR_CANT_CREATE
 Error listening on port 6007

**Steps to reproduce:**
make a scene -> add node2D -> Save -> Run 

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
>  master as of 2018-09-13

What commit? A fix was merged 2 hours ago for a related issue.

**Comment by chaosdrop** [comment]
Yep fixed it. I had just barely missed the patch I was on the commit right before it.

**Comment by Plopsiskopsis** [comment]
Still happening for me. Build 9c0cc0d
![image](https://user-images.githubusercontent.com/35765659/45593439-4c844980-b98f-11e8-9903-c663d8b9117b.png)
Tried also changing ports but no luck.

**Comment by akien-mga** [comment]
@Plopsiskopsis Well, that's because the fix was merged after 9c0cc0d...
