### ISSUE TITLE
iOS export errors / streamlining export process

### ISSUE THREAD

**Issue by RedwanFox** [godotengine/godot#22197]
**Godot version:**
3.0.6

**OS/device including version:**
Mac OS X 10.13.6 / Xcode 9.4.1

**Issue description:**

First of all, sorry. I am not familiar with ios development and google-fu didn't help.

I tried creating and exporting "hello world" project (1 scene, 1 "press me" button in gdscript) using official [tutorial](http://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_for_ios.html) and official export templates.

Got problems on every step:

0. (minor) Export menu has no sane defaults for bundles, app name, etc. 
1. Linking problem if target is emulator 

```
ld: warning: ignoring file /Users/user/Documents/projects/mobile/project/xcode/project.a, missing required architecture x86_64 in file /Users/user/Documents/projects/mobile/project/xcode/project.a (3 slices)
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
"Fixed" this via targeting real device. 
2. https://github.com/godotengine/godot/issues/18359 this
3. *now here*  dsymutil error

```
error: cannot parse the debug map for "/Users/user/Library/Developer/Xcode/DerivedData/project-hjgvqxxbzgxuszbkfklkeekwagvq/Build/Products/Debug-iphoneos/project.app/project": Is a directory
```
I think this is related to step 6 of exporting tutorial (referencing project folder to xcode project).

Questions:
How to deal with problems 1 and 3? 
How to export godot native application to ios?

**Comment by thebartyparty** [comment]
A quick web search shows that you generally get linker errors such as `clang: error: linker command failed with exit code 1 (use -v to see invocation)` due to missing libraries. For me it was the `StoreKit.framework`. This is solved by going to _Build Phases > Link Binary With Libraries_ And pressing the plus button to add a library. In my case I just searched for `StoreKit` and added the library.

For the dsymutil error, the only thing I can suggest is going to _Product > Clean Build Folder_ in the menu bar (⌘ ⇧K)

**Comment by Redwan13** [comment]
>This is solved by going to Build Phases > Link Binary With Libraries And pressing the plus button to add a library. In my case I just searched for StoreKit and added the library.

Thanks. On the long run it is better to remove storekit from default link in export template .

>For the dsymutil error, the only thing I can suggest is going to Product > Clean Build Folder in the menu bar 

It didn't help as far I remember. I'll try again.

**Comment by vini-guerrero** [comment]
Having the same issue, adding  StoreKit to Build Phases > Link Binary With Libraries in XCode didn't solve the problem:

![image](https://user-images.githubusercontent.com/18181786/56829041-1407f080-6839-11e9-99a9-8e44ce52b43e.png)

**Comment by KoBeWi** [comment]
Closing due to lack of update. Please comment if you can still reproduce this issue in the latest stable version of Godot.
