### ISSUE TITLE
The find/search selection highlight for the built in documentation is very hard to see.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#22552]
Alpha 3.1 6cbdeedf57c7383827416da19b6026e3721f2812

Small enhancement request.  When doing a search/find within editor documentation, the selection highlight is very difficult to find.  Most the time I wonder if it was deselected.  I'm not sure what to recommend as far as a highlight color.

Take a look at this screenshot and see how long it takes you to find the selection.

![godot_master_2018-09-29_21-42-29](https://user-images.githubusercontent.com/13004169/46256842-1d0a2c80-c4b9-11e8-95fa-d08e9998b65a.png)

**Comment by groud** [comment]
This happened to me too, I agree the highlight color is too subtle.

**Comment by neikeq** [comment]
I give up. I rather find Wally.

**Comment by avencherus** [comment]
@neikeq Haha, here he is!  XD

![one_highlight](https://user-images.githubusercontent.com/13004169/46258415-e8a36a00-c4d2-11e8-8365-328e2f70cf88.png)

**Comment by AlexHolly** [comment]
:+1: 
![image](https://user-images.githubusercontent.com/4741886/46296752-5e730880-c59b-11e8-9b42-3a93f279ea4f.png)

:-1: 
![image](https://user-images.githubusercontent.com/4741886/46296804-7fd3f480-c59b-11e8-9c55-355f13c55333.png)

Something else?
:heart:

**Comment by Calinou** [comment]
I think it would make sense to reuse the text editor's selection color.

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/issues/21000 ?

**Comment by avencherus** [comment]
@AlexHolly Would say green is certainly clearer of the two, but maybe what calinou suggested works out just fine.  I'm fairly unqualified to vote on UI color choices though, so take it with a grain of salt.  X)

**Comment by AlexHolly** [comment]
The TextEditor color looks kind of the same and adding a Border like the CodeEditor has would be a bit work.

**Comment by rodolforg** [comment]
I'd suggest to choose a color that satisfies this 'algorithm':
http://www.w3.org/TR/AERT#color-contrast

It checks if two colors have enough contrast including for color-blinded people.

**Comment by avencherus** [comment]
@rodolforg Interesting resource, and it also had an amusing typo.  XD

> The **rage** for color brightness difference is 125.

**Comment by btn0s** [comment]
I agree with @rodolforg, the color should be WCAG 2.0 compliant.

**Comment by Zireael07** [comment]
WCAG 2.0 is brilliant in general, for a default theme green or yellow should be good to go.

**Comment by swarnimarun** [comment]
Planning on giving it a go, so should I make it green with white text?

**Comment by btn0s** [comment]
#252C3B is the color of the background, which passes on all WCAG thresholds with #00FF79 as the green.

I'd do text #252C3B
with background #00FF79

**Comment by avencherus** [comment]
> I'd do text #252C3B
with background #00FF79

@btn0s This?
![untitled-1](https://user-images.githubusercontent.com/13004169/46439348-0a1d8380-c769-11e8-8007-e3ac0d59f1a5.png)

**Comment by akien-mga** [comment]
No need to reinvent the wheel, as @Calinou said:

> I think it would make sense to reuse the text editor's selection color for this.

If you then want to review text editor default colors to match UX best practices, that's fine, but the fix for this issue should just be to reuse the existing selection color.

**Comment by metaphoricalsasquash** [comment]
While we are on it, is there a reason the built in documentation does not have the same color coding as the online documentation? I never use the build in documentation, because I find the online version much easier to differentiate.

**Comment by samgreen** [comment]
Does #21195 resolve this or is it still available for hacktoberfest?

**Comment by Calinou** [comment]
> While we are on it, is there a reason the built in documentation does not have the same color coding as the online documentation?

The built-in documentation is themed to match the Godot editor, which means it uses a dark theme by default.

**Comment by metaphoricalsasquash** [comment]
The dark two tone coloring may be pretty, not the best choice to learn, imho. Because both online documentation as well as GDscript inside the editor are using other color coding. Because it is multi colored, it's a lot easier to grasp. Ideally, I wish all three had the same color coding.

**Comment by bojidar-bg** [comment]
Bump. Is this resolved with #21195? (so, 3.1)

**Comment by Zireael07** [comment]
Not 100% sure but this is what I see in alpha 3:
![godot_v3 1-alpha3_win64_2018-12-13_12-52-51](https://user-images.githubusercontent.com/4525388/49937191-46dac900-fed6-11e8-8a43-9010f11a84e1.png)

I haven't changed any settings in alpha 3 itself and IIRC settings should be version-independent, but definitely not the greenish color that it should be after #21195.

**Comment by akien-mga** [comment]
That's the expected color from #21195, `40808080` is ARGB, so it's gray with low opacity.
I agree that it's still not visible enough though. The background rect should likely be made a bit taller too to be easier to spot.

**Comment by Zireael07** [comment]
Ah, I put 40808080 in a html picker so it outputted a nice contrasting green, probably the picker interpreted it as RGBA :)

**Comment by girng** [comment]
apparently the colors yellow and orange  don't exist
