### ISSUE TITLE
"Force Blinn over GGX" option not useful anymore

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#22637]
The optimized GGX merged in #22483 is faster than Blinn (which uses exp2 and pow), so this option should be removed, or at least should be disabled by default in GLES2.

An alternative and useful option would be to force low-quality approximation for GGX over the usual one.

**Comment by tagcup** [comment]
@reduz Similar optimization (from Filament docs) for the anisotropic case was also adapted in that same PR so it's now too slow now. Maybe anisotropy can be enabled in GLES2 now (assuming there aren't any other limitations)?

**Comment by tagcup** [comment]
I went ahead and refactored the calculation of H, L.H and N.H #22639 to avoid double calculations

**Comment by fire** [comment]
This has been completed correct?

**Comment by tagcup** [comment]
Yes

**Comment by fire** [comment]
Solved by #22639.

**Comment by tagcup** [comment]
Ah, no, it's not solved. What I mean is everything required for obsoleting forced Blinn+Lambert is done.

This issue is about actually making them obsolete (or removing them altogether) which hasn't been done

**Comment by elvisish** [comment]
Is Lambert Over Burley and Blinn over GGX in Godot 3.6 still faster or should I just leave those unchecked for performance improvements?

**Comment by clayjohn** [comment]
> Is Lambert Over Burley and Blinn over GGX in Godot 3.6 still faster or should I just leave those unchecked for performance improvements?

Its going to be hardware dependent. But in general using both "Lambert over Burley" **and** "blinn over GGX" should result in the lowest instruction count. If already using Burley, then "blinn over GGX" is slower than using GGX (which is what this issue is referencing). The reason for that is that the expensive parts of GGX are shared with Burley. So if you are using Burley, then doing GGX only adds a few instructions. But if you are using Lambert, then GGX adds a lot. 

The reason it is hardware dependent is that Blinn uses `exp2` and `pow` which can be very expensive on some hardware.
