### ISSUE TITLE
Auto-complete not working for autoloaded global scripts

### ISSUE THREAD

**Issue by isHaacK** [godotengine/godot#22824]
**Godot version:**

Godot Engine v3.0.6.stable.official

**OS/device including version:**

Windows 8.1 Pro & Windows 10 Home

**Issue description:**

Member functions not auto-completing when the variable is in autoload global.gd 

**Steps to reproduce:**
global.gd

`var array = ["zero", "one", "two"]`

script.gd

`print(global.array.size())` global.array autocompletes correctly but it doesn't complete the function size()

**Minimal reproduction project:**

[minimal reproduction.zip](https://github.com/godotengine/godot/files/2453886/minimal.reproduction.zip)

**Comment by ThakeeNathees** [comment]
this issue has been fixed and should be closed

**Comment by Calinou** [comment]
Closing per @ThakeeNathees's comment.

**Comment by ShivamMukherjee** [comment]
Still getting this behaviour.
[PluginsTemplate.zip](https://github.com/godotengine/godot/files/5020140/PluginsTemplate.zip)

**Comment by Calinou** [comment]
Related to #40537.
