### ISSUE TITLE
Scaled popup dialog not centered when popup_centered is called 

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#23127]
**Godot version:**
Alpha 3.1 official

**OS/device including version:**
Windows 10, Intel Integrated

**Issue description:**
If popup dialog scale is other than (1,1) it's not centered when calling popup_centered function

**Steps to reproduce:**
a) Add a popup dialog (AcceptDialog in the sample project)
b) Change rect scale (0.1, 0.1 in the sample project)
c) Call popup_centered to display the dialog

**Minimal reproduction project:**
[Popup.zip](https://github.com/godotengine/godot/files/2493746/Popup.zip)

**Comment by KoBeWi** [comment]
Dialogs no longer have scale property in 4.0, so this is resolved.

**Comment by David-Ochoa** [comment]
Really? Version 3.x is still supported and removing it from v4.0 this doesn't solve anything

**Comment by KoBeWi** [comment]
IMO this is not really critical issue and scale in Controls is a not-well supported hack anyways, but the fix is trivial so I opened a PR for 3.2: #45509
