### ISSUE TITLE
Bug Condition ' !target ' is true. Continuing..: when make scene root

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23554]
**Godot version:**
3.1 3cf3c41

**OS/device including version:**
Windows 10

**Issue description:**
When I save a Noise texture and try to make this scene root then this error occurs:
> ERROR: emit_signal: Condition ' !target ' is true. Continuing..:
   At: core/object.cpp:1203

When I close project and delete this file Map.tscn-folding-8e8b22d8d23c1bbb339e47e1360047d1.cfg from Roaming\projects\GQE... folder and then open project, this error doesn't show

This is the contents of the file which provide this error: "Map.tscn-folding-8e8b22d8d23c1bbb339e47e1360047d1.cfg"
> [folding]
node_unfolds=[ NodePath("."), PoolStringArray( "Transform" ), NodePath("Sprite"), PoolStringArray( "Animation", "Offset", "Region", "texture" ) ]
resource_unfolds=[ "res://Map.tscn::2", PoolStringArray( "Flags", "noise" ) ]

This is the file which was created after delete file from above and with this file error doesn't occur:
> [folding]
node_unfolds=[ NodePath("."), PoolStringArray( "Transform" ) ]
resource_unfolds=[ "res://Map.tscn::2", PoolStringArray(  ) ]

**Steps to reproduce:**
https://streamable.com/ag05q

**Comment by remorse107** [comment]
I thought I was going nuts with a plugin that I've been working on.  But I can confirm that collapsing the sections allows the node to removed without reporting an error.

**Comment by reduz** [comment]
The make scene root bug is fixed, so this should now be solved. closing.

**Comment by reduz** [comment]
bug report is confusing, though, so please let me know if you find something else.

**Comment by DualMatrix** [comment]
This is still reproducable and I think this isn't related to the 'make scene root' function but instead seems to be a problem with some inspectors. 

To reproduce: Create a sprite with a sprite with a NoiseTexture, select the texture in the inspector. Make the sprite root or switch scenes in the scenes tab.

**Comment by DualMatrix** [comment]
The issue seems to be with the connection of the 'node_removed' signal in editor_inspector.cpp. I can't figure out why it's going wrong though, maybe someone else can take a look?

```
if (p_what == NOTIFICATION_ENTER_TREE) {
	get_tree()->connect("node_removed", this, "_node_removed");
	if (use_sub_inspector_bg) {
		add_style_override("bg", get_stylebox("sub_inspector_bg", "Editor"));
	} else if (is_inside_tree()) {
		add_style_override("bg", get_stylebox("bg", "Tree"));
	}
}
if (p_what == NOTIFICATION_EXIT_TREE) {
	get_tree()->disconnect("node_removed", this, "_node_removed");
	edit(NULL);
}
```
