### ISSUE TITLE
Adding a shortcut to a button adds extra text to the tooltip.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#23617]
**Godot version:**
3.1 Alpha 2

**Issue description:**
When a shortcut is added to a button the button's tooltip gets extra text describing the shortcut, but there's no way to disable the shortcut from adding extra text to the tooltip. It's also kind of ugly and doesn't really inform the player of anything.

![button_tooltip](https://user-images.githubusercontent.com/11450875/48284791-81ac9580-e42e-11e8-94e8-f7771d3e3b29.png)

**Steps to reproduce:**
Create a button. Add a shortcut to it.

**Comment by akien-mga** [comment]
Fixed by #23731.

**Comment by rKinson** [comment]
When completing the beginner game 'Dodge' on the Godot manual website, adding a shortcut to the button produces the tool tip as with op.

Godot Engine v3.0.6.stable.official.8314054

**Comment by CowThing** [comment]
It was fixed in 3.1, not in 3.0

**Comment by sszigeti** [comment]
I'm still getting this unwanted tooltip in 3.1.1.stable.official.

**Comment by akien-mga** [comment]
See the referenced Pull Request, it was made optional, so you have to disable it with `shortcut_in_tooltip` if you don't want shortcuts in tooltips.

**Comment by LuckyB4stard** [comment]
Is it possible to add this boolean in theme in Godot 3.5.1?
