### ISSUE TITLE
BakedLightmap does not react to ambient lighting if no sky is used

### ISSUE THREAD

**Issue by BlueCannonBall** [godotengine/godot#23948]
**Godot version:**
v3.0.6.stable.official

**OS/device including version:**
Microsoft Windows 10 Home
Lenovo IdeaPad 32015IKB Touch
Intel(R) Core(TM) i7-8550U @ 1.80GHz
Intel(R) UHD Graphics 620
Tensor 1.0 Graphics Drivers - https://imo32.weebly.com/

**Issue description:**
So I'm having a problem where if I create a BakedLightmap node and bake the lightmaps, then the meshes inside the extents of the BakedLightmap no longer react to the environment.

**Steps to reproduce:**
1. Create a scene with a directional light, a cube, and a plane
2. Make sure the scene has a default procedural sky
3. Add a BakedLightmap node with extents that cover the whole scene
4. Bake it!

**Minimal reproduction project:**
https://drive.google.com/file/d/1MDJdG_IjoVn2hkawRbI9KhbkdXHtDETO/view?usp=sharing

**Comment by Ace-Dragon** [comment]
I don't think the BakedLightmap supports environmental lighting right now.

It would be good to have, as it would become a powerful tool for making indoor/outdoor scenes with high quality lighting.

**Comment by MmTtDeveloper** [comment]
It would definitely be a great feature to have because GI is very slow on my hardware.

**Comment by BlueCannonBall** [comment]
Fixed in 3.1

**Comment by ShiftyAxel** [comment]
I'm still seeing this behavior as of 3.1.2.

If I add meshes to a scene, unwrap their UVs, set up some hidden lights in 'bake all' mode and use a BakedLightmap to bake lighting, none of the meshes respond to changes in the WorldEnvironment's ambient light setting.

**Comment by BlueCannonBall** [comment]
You forgot to set the meshes to "use in baked lighting"

**Comment by ShiftyAxel** [comment]
@BlueCannonBall I wouldn't be seeing any baked lighting in the first place if that was turned off.

WorldEnvironment with excessive pink lighting set for example's sake:

![image](https://user-images.githubusercontent.com/1253239/70939235-ba5e6b80-203f-11ea-9527-160ae691bbd0.png)

Checkerboard mesh (floor, cylinder, etc) with baked light enabled and built:

![image](https://user-images.githubusercontent.com/1253239/70939307-e1b53880-203f-11ea-802b-7056e08f2e2a.png)

**Comment by ShiftyAxel** [comment]
It does appear to work with Background > Mode > Sky set on the WorldEnvironment, which can be used to work around it by setting up a single-colored sky, but I'd still consider this an issue since the ambient light settings don't work.

**Comment by Calinou** [comment]
This should be fixed in the [new lightmapper](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper), but I haven't had time to test it yet.

**Comment by akien-mga** [comment]
> This should be fixed in the [new lightmapper](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper), but I haven't had time to test it yet.

Assuming fixed then. Please comment if you can still reproduce the issue, and attach a reproduction project (since the one in the OP apparently was fixed a while ago already).
