### ISSUE TITLE
Add option to opt in or out of saving a node's folded state

### ISSUE THREAD

**Issue by puzzud** [godotengine/godot#24139]
**Godot version:**
v3.0.6.stable.official.8314054

**Issue description:**
Sometimes (most of the time for me, currently) it is desired to not persist the state of which nodes are folded in a scene. This concern comes mostly from the unnecessary changes to a TSCN file when using version control.

I know that using instantiated scenes in other scenes mitigates this problem somewhat, but it does not remove it completely.

Personally, I think in most applications, folded state is a local & personal one; so I'd like to see it (attempted to be) maintained in Godot Editor cache files (like thumbnails and such). However, I know that if someone is using Godot tree widgets in their application, they may want to enforce or persist node folded states.

**Proposed solution:**
I can think a good compromise is to add an option to a node which can disable the persistence of folded states on it an any of its children, unless of course any of those children have that option explicitly set to not inherit from its parent and override it to something else, in which case it and its children behave as such.

**Comment by bojidar-bg** [comment]
Fixed since e647342140d8eb960b2a72d83b4b86e43aef4fc7.

**Comment by Zylann** [comment]
I still get folding info saved in my scenes, is it an option I need to check?

**Comment by akien-mga** [comment]
> I still get folding info saved in my scenes in Godot 3.1 beta7, is it an option I need to check?

Are you sure it's not old info saved from alpha builds? The logic in `editor/editor_folding.cpp` does save this in `project_settings_dir`, which is outside of the project folder.

**Comment by Zylann** [comment]
@akien-mga no, it's a new project I created from 3.1 beta6, and I noticed it had folding info.

**Comment by akien-mga** [comment]
That's for SceneTreeEditor, not the inspector properties. SceneTree folding is still saved in the scenes, yes.

**Comment by bojidar-bg** [comment]
Ah, wait, I messed up in this case.

Reopening as per the above comments: while property folding state is not saved in the scene, node folding state is.

**Comment by KoBeWi** [comment]
Already fixed in 3.2. Folding is stored outside project, even for nodes.
