### ISSUE TITLE
Cannot select and copy godot version from the about window

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24317]
**Godot version:**
11d7738

**Issue description:**
Every time i open an issue, the Godot version is required. The current way of finding out your own Godot version is either:
1. Open the about window and manually copy the commit hash (very annoying without 2 screens)
2. Git log
3. Check my last opened issue for the Godot version

**Proposal:**
Allow the Godot version in the "about" window for selecting and copying (or add a "copy to clipboard" button)

**Comment by akien-mga** [comment]
The "usual" way to make this work is to replace the `Label` with a non-editable `LineEdit`, and then override the `LineEdit`'s styles with that of `Label` (to fake a selectable `Label`).

It's a bit annoying though, so it might be worth adding support for selection in `Label` directly... should be discussed with @reduz to confirm that it'd be a good idea.

**Comment by QbieShay** [comment]
I imagine it might be worth to have a "selectable label" class instead, so that the common use case remains untouched, but for when selection is needed there is a more specific node that handles that (I doubt that is easy to implement in GDScript..)

**Comment by starry-abyss** [comment]
Would also be great to have this in the project manager as well

**Comment by KoBeWi** [comment]
Is this still relevant now that we have Godot version printed in the console?

**Comment by akien-mga** [comment]
It's less needed now, but it would still be good to have more stuff that can be selected and copy pasted in the editor generally-speaking.

**Comment by KoBeWi** [comment]
> The "usual" way to make this work is to replace the Label with a non-editable LineEdit, and then override the LineEdit's styles with that of Label (to fake a selectable Label).

RichTextLabel supports selecting too.

**Comment by strattonbrazil** [comment]
I took a quick look as this (as a "junior" ticket).  

_LineEdit_ has some rendering issues with newlines, so it didn't seem like a good fit, but I may have given up too early.  

I tried _RichTextLabel_ that seems promising, but either due to the API or my inexperience with it I can't match the dynamic positioning.  _RichTextLabel_ will not provide a minimum size without a fixed width.  This is needed for the layout to center the logo and the label.  I can hard-code the minimum width, but if it's too low it wraps and if it's too high it it pushes the logo to the left.  I could update _RichTextLabel_ to support getting the content width (without wrapping) or some way to force no wrapping when computing the width, but wanted to follow-up here first to make sure either of these suggestions makes sense since it's a bigger change.

**Comment by Calinou** [comment]
This could also be solved by making the version label a dedicated LinkButton node, with a `pressed` action that copies the text (with a tooltip to suggest the action). This is what I have in [my branch](https://github.com/Calinou/godot/tree/version-click-to-copy), but there are alignment issues with the rest of the text.

**Comment by strattonbrazil** [comment]
@Calinou sounds good.  Here's my change for reference.  

```
-       Label *about_text = memnew(Label);
-       about_text->set_v_size_flags(Control::SIZE_SHRINK_CENTER);
+       RichTextLabel *about_text = memnew(RichTextLabel);
+       about_text->set_custom_minimum_size(Size2(500, 1));
+       about_text->set_selection_enabled(true);
+       about_text->set_scroll_active(false);
```
That doesn't fix the style box, but it makes it selectable:
![some_selection](https://user-images.githubusercontent.com/786471/72693274-fa07ef80-3ae4-11ea-9de4-1f9e81bc431f.jpg)

**Comment by KoBeWi** [comment]
> That doesn't fix the style box, but it makes it selectable:

You could probably add an override for the stylebox to make it invisible.
