### ISSUE TITLE
We should be able to change a mesh's transform origin

### ISSUE THREAD

**Issue by foumfo** [godotengine/godot#24602]
**Godot version:**
Godot Engine v3.0.6.stable.official.8314054

**OS/device including version:**
Windows 10

**Issue description:**
We should be able to change a mesh's transform origin, so that we don't have to do things like e.g. adding a spatial as a parent. Besides that doesn't even work with meshLibraries and gridmaps

**Comment by Zylann** [comment]
Meshes don't have a transform to begin with, so this would either be a destructive import step, or an extra transform on every mesh instance but I'm not sure how it would be manipulated / if everyone want to pay the price of this on every single mesh.

**Comment by foumfo** [comment]
Just to clarify, because English isn't my mother language, I meant the pivot point also

**Comment by Toshiwoz** [comment]
It will be useful in at least one case, in the GridMap's Mesh Library, or in the GridMap itself, to have a sort of offset in order to change the rotation poit (pivot) of the single tile.
I had to chage it one by one in my case, I was using one of @KenneyNL free asset packs:
https://kenney.nl/assets/space-kit
Because the origin was set in a corner of some of the elements and I couldn't do that within Godot.

**Comment by Zylann** [comment]
For gridmaps, I actually find it way easier to set this up in Blender, but Godot doesn't consider pivots set that way and expect everything to be relative to the origin https://github.com/godotengine/godot/issues/13980

**Comment by Toshiwoz** [comment]
> 
> 
> For gridmaps, I actually find it way easier to set this up in Blender

Can you please let me know how you did it? I have this space kit that consists of dozens of elements (yes I use almos everything as tile, even if with different scale) and I did it, but it was quite painful:

- I had to figure out which options to select for export (for example uncheck Y is up, or else I'd have the mesh wrongly rotated, I know I can rotate within the editor, but it does not look good in the preview)
- I had to figure out how to move the origin, and do it for each element

... and I'm not going to mention other issues I had with the importer too as it is not related to this issue.
Of course each asset is provided not thinking about the game engine it will be used in.
Hopefully, being able to use GDScript within the import process will probably help doing almost anything.

**Comment by akien-mga** [comment]
Fixed by #35006.

**Comment by Shadowblitz16** [comment]
@akien-mga This doesn't solve the issue with built in godot mesh shapes
