### ISSUE TITLE
Hidden / invisible nodes still receive Input events.

### ISSUE THREAD

**Issue by Skyfish1** [godotengine/godot#24699]
**Godot version:**
3.0.6-stable

**OS/device including version:**
Windows 10

**Issue description:**
Hidden nodes still recieve _unhandled_input(). Not only could this lead to performance issues, but it leads to totally unexpected behaviours. Hidden nodes should not do anything. 

In my case I have two nodes with a GDScript attached. Both handle _unhandled_input(event) and consume the event with get_tree().set_input_as_handled(). I use unhandled because I want the UI handle input first, but this doesn't matter for this issue. Although the other node was hidden, it still stole the input events, the other node never received anything and I was wondering what was going on until I finally figured out the problem. Only one node can be visible at the same time. I switch them on and off with show() and hide().

My Workaround for now is if(not visible): return in every event handling method. 

**Steps to reproduce:**
In attached project if you move the mouse in the empty game window you see "HiddenNode" steals all events. Only if you delete it, "VisibleNode" prints "I got the event" in the console.

**Minimal reproduction project:**
[HidenNodesStillReceiveEvents.zip](https://github.com/godotengine/godot/files/2719532/HidenNodesStillReceiveEvents.zip)

**Comment by CowThing** [comment]
This isn't an issue. If a node is inside the scene tree it should be processed whether it's visible or not. If you want it to stop processing while hidden that should be up to you to code. You can set it to stop handling inputs by setting `set_process_inputs` or `set_process_unhandled_inputs` when the visibility changes.

**Comment by girng** [comment]
same for _process and _physics_process as well. you can disable/toggle inputs, processing,etc when you hide teh node

**Comment by Skyfish1** [comment]
That's what I did in the end. I made my own disable() and enable() method which I expected from show/hide. Is there any reason for processing hidden nodes? I think its not intuitive and from a design standpoint it leads to unexpected behaviour especially if you are new to godot and don't know the specific "workarounds". If you hide a button you can't press it anymore. If you hide a sprite why should it collide with something or receive input etc. :)

**Comment by girng** [comment]
power of gdscript. working as intended imo. just part of learning the engine

**Comment by FlamyAT** [comment]
> If you hide a sprite why should it collide with something or receive input etc. :)

Maybe you want to hide an entity but still process it's behaviour e.g. they have an ability to turn invisible but that shouldn't mean they can't move

**Comment by Skyfish1** [comment]
I like that Godot is that flexible and I understand now, the may be use cases, but these seem intentional - meaning you know you want them still processing even if hidden and therefore should require addional methods for enable processing. The default behavior shoud in my opinion be the intuitive case - disabling everything, because someone would not expect something to do anything if its not there - like the button example I made. Maybe I have a different intuition, but that's just me being confused with the design choice :)

**Comment by girng** [comment]
@Skyfish1 yeah there's good points on both sides..

**Comment by Skyfish1** [comment]
As I have a complex tree of Node2Ds and Sprites in a multilayer Map I had to come up with a flexible solution to deactivate all subnodes if I hide the parent (Map layer) node. Here is my script in case someone has the same Issue:

You need to extend all your Node2Ds with this script:

`extends "res://scripts/DeactivatableNode2D.gd"`

if you also want access to Sprite methods like texture in your script, you also need a second script which extends Sprite instead of Node2D because you can not extend Sprite and my script at the same time as far as I know.

```
extends Node2D

# mask for activation eg. (A_PROCESS | A_INPUT)
const A_PROCESS = 0x1
const A_PHYSICS = 0x2
const A_INPUT = 0x4
const A_UNHANDLED_INPUT = 0x8
const A_ALL = A_PROCESS | A_PHYSICS | A_INPUT | A_UNHANDLED_INPUT

var _mask = A_ALL 

# to override call super(=dot) method: ._ready()
func _ready():
	if(not visible):
		_deactivate()
	connect("visibility_changed", self, "on_visibility_changed")
		
func set_mask(mask):
	_mask = mask
	
func _deactivate():
	hide()
	set_process(false)
	set_physics_process(false)
	set_process_unhandled_input(false)
	set_process_input(false)
	for node in get_children():
		if(node.has_method("_deactivate")):
			node._deactivate()
	
func _activate(mask=null):
	var m = _mask if (mask == null) else mask
	show()
	if(m & A_PROCESS): set_process(true)
	if(m & A_PHYSICS): set_physics_process(true)
	if(m & A_UNHANDLED_INPUT): set_process_unhandled_input(true)
	if(m & A_INPUT): set_process_input(true)
	for node in get_children():
		if(node.has_method("_activate")):
			node._activate()

func on_visibility_changed():
	if(visible):
		_activate()
	else:
		_deactivate()
```

All you need in your code is then:

```
func _ready():
	._ready() #call super method
	.set_mask(A_PROCESS|A_UNHANDLED_INPUT | ...)
```

**Comment by mitchcurtis** [comment]
Thanks for sharing that code, @Skyfish1.

In my case I have a Control that handles input and that Control is a child of a Popup. I noticed that the visible property of the Control was always true in on_visibility_changed, so I had to use is_visible_in_tree() instead, as that would return the effective visibility of the Control:

```
extends Control

func _ready():
    if (!visible):
        _disable_input()
    connect("visibility_changed", self, "on_visibility_changed")
    
func _disable_input():
    set_process_input(false)

func _enable_input():
    set_process_input(true)
    
func on_visibility_changed():
    if (is_visible_in_tree()):
        _enable_input()
    else:
        _disable_input()
```

While browsing the docs I also noticed this:

https://docs.godotengine.org/en/3.1/classes/class_visibilityenabler2d.html

It doesn't have any way to disable input though, so I guess it's useless here?

**Comment by Skyfish1** [comment]
@mitchcurtis I noticed the same thing. I updated my code above.

**Comment by Szesan** [comment]
Why do you need two separate methods for activate/deactivate?

You can simply do:

```
	private void setActiveStatus(bool isActive)
	{
          SetPhysicsProcess(isActive);
          SetProcess(isActive);
          SetProcessUnhandledInput(isActive);
          SetProcessInput(isActive);
          Visible = isActive;
	}
```
Other than that, setting processing on a node doesn't stop it's children from processing input, so I made an extension method that handles this issue:

  ```
     public static void SetProcessingInputResursive(this Node node, bool enable)
        {
            foreach (var child in node.GetChildren())
            {
                var item = child as Node;
                if (item != null)
                {
                    item.SetPhysicsProcess(enable);
                    item.SetProcess(enable);
                    item.SetProcessUnhandledInput(enable);
                    item.SetProcessInput(enable);
                }
            }
        }
```
Now my activation looks like this:

	private void setActiveStatus(bool isActive)
	{
	  SetProcessingInputResursive(isActive);
          Visible = isActive;
	}

**Comment by BennieBe** [comment]
> > If you hide a sprite why should it collide with something or receive input etc. :)
> 
> Maybe you want to hide an entity but still process it's behaviour e.g. they have an ability to turn invisible but that shouldn't mean they can't move

I have an example for that, I need to have my node hidden but the process should still continue in the background, so it really depends on the use case you have.

**Comment by betalars** [comment]
`is_visible_in_tree()` is a lot more useful when checking for visibility in this context btw. You may otherwise run into issues where parents are hidden but a child is still processing.
