### ISSUE TITLE
Distribute 64-bit Android templates (arm64-v8a and x86_64) for all supported releases

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#25030]
**Godot version:**
All supported branches:
- `master`: ffcb5cd
- `3.0`: 49929c1
- `2.1`: f2a42e1

**OS/device including version:**
Android 9.0+

**Issue description:**
Google's Android team [just announced](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) new requirements for 64-bit support in Android APKs, starting in August 2019.

The gist of it is that we need to include 64-bit libraries in the official templates APKs for our supported releases. By [64-bit architectures](https://developer.android.com/distribute/best-practices/develop/64-bit), Android implies `arm64-v8a` and `x86_64`. They do not deprecate 32-bit, so we should still provide `armeabi-v7a` and `x86` libraries.

As far as I can tell, the current state of our releases is:
- 3.1 beta 1: `armeabi-v7a`, `arm64-v8a`, `x86`: **needs `x86_64`**
- 3.0.6: `armeabi-v7a`, `arm64-v8a`, `x86`: **needs `x86_64`** ([source](https://notabug.org/hp/godot-scripts/src/master/build-godot.sh#L375-L381))
- 2.1.5: `armeabi-v7a`, `arm64-v8a`, `x86`: **needs `x86_64`** ([source](https://github.com/GodotBuilder/godot-builds/blob/2.1/.travis.yml#L46-L51))

So it seems like we're all set for 64-bit ARM already, but we need to add `x86_64` support. Currently `platform/android/detect.py` doesn't support `x86_64` at all, but it should be trivial to add, then backport to the `3.0` and `2.1` branches to eventually prepare new releases.

**Comment by hpvb** [comment]
3.1-beta2 ships x86_64 templates

**Comment by akien-mga** [comment]
This is OK for 3.1, so assigning to 3.0 milestone so that we remember about it for the next 3.0.x release.

**Comment by wombatwingdings** [comment]
Is there any plans for Godot to support [Android App Bundles](https://developer.android.com/platform/technology/app-bundle/) to combat the problem of growing .apk package size once we must include 64 bit libraries?

**Comment by SMaiLubis** [comment]
my android app got warning from google about 64bit requirement, my app is use 2.1.5 release.
![google warning 64nit](https://user-images.githubusercontent.com/46646098/57182106-71094380-6ed6-11e9-8793-b432d536048a.png)
is there a solution for this warning?

**Comment by volzhs** [comment]
@SMaiLubis are you using official android templates?

**Comment by SMaiLubis** [comment]
@volzhs if you mean Godot_v2.1.5-stable_export_templates.tpz, yes i already use it.

**Comment by volzhs** [comment]
so you are using your own template for android. 
you need to compile arm64 and build apk.

**Comment by akien-mga** [comment]
I'm not sure we backported the `arm64` build support to the 2.1 branch yet, needs to be done and release 2.1.6 soon-ish.

**Comment by SMaiLubis** [comment]
I hope it will release soon (before August). 
Is the only other way are migrate to 3.0 or 3.1?

**Comment by akien-mga** [comment]
> I'm not sure we backported the arm64 build support to the 2.1 branch yet, needs to be done and release 2.1.6 soon-ish.

Actually it's referenced right above, the PR I made for arm64 support has been cherry-picked to the 2.1 and 3.0 branches. So you can compile the current 2.1 branch with `android_arch=arm64`.

**Comment by akien-mga** [comment]
I updated the docs for 2.1 and 3.0 (will be up in ~30 min): http://docs.godotengine.org/en/2.1/development/compiling/compiling_for_android.html

**Comment by SMaiLubis** [comment]
> > I'm not sure we backported the arm64 build support to the 2.1 branch yet, needs to be done and release 2.1.6 soon-ish.
> 
> Actually it's referenced right above, the PR I made for arm64 support has been cherry-picked to the 2.1 and 3.0 branches. So you can compile the current 2.1 branch with `android_arch=arm64v8`.

The current 2.1 branch is 2.1.5 stable? 



> I updated the docs for 2.1 and 3.0 (will be up in ~30 min): http://docs.godotengine.org/en/2.1/development/compiling/compiling_for_android.html

It still doesn't mention about arm64.

**Comment by akien-mga** [comment]
Current status:

- Solved in the `2.1` branch with `2.1.6-stable`.
- Support merged in the `3.0` branch, but we still need to release `3.0.7` with `x86_64` binaries.
- Solved in the `master` and `3.1` branches since `3.1-stable`.

**Comment by aaronfranke** [comment]
Just a reminder, we're way past 2019 August 1st, and it has been over 1 year since Godot 3.0.6.

**Comment by name-here** [comment]
Does this issue still need to be open?

**Comment by akien-mga** [comment]
https://github.com/godotengine/godot/issues/25030#issuecomment-513464715

**Comment by wombatstampede** [comment]
Google just sent me a "last-minute" reminder:
[Action Required] Create a 64-bit compliant version of your app(s) by February 1, 2020

My (3.1) apk included arm x86_64 but only x86 (as it wasn't available in the 3.1 template set).
Before I try it: It is possible (by switch) to build the x86_64 template in the 3.1 release branch?

If not then I'd either have to release a version/apk without x86 or build my game with some beta brach by Februrary 1.

**Comment by akien-mga** [comment]
@wombatstampede Release your game with 3.1.2-stable.

**Comment by aaronfranke** [comment]
@akien-mga What's the status of this? 3.0 is no longer linked from the main site. Since the work has already been done for 3.0 anyway, perhaps you should just do a 3.0.7 release (at which point we can just never touch the 3.0 branch again...?).

**Comment by akien-mga** [comment]
There isn't a lot of demand for a new 3.0.7 release, so indeed, I think we can consider this fixed.

**Comment by Isradin2011** [comment]
**__**

**Comment by Isradin2011** [comment]
Me is what to there
