### ISSUE TITLE
KinematicBody2D issues when using more than one RayShape2D for collisions

### ISSUE THREAD

**Issue by theboyboy** [godotengine/godot#25050]
**Godot version:** 3.1 Beta

**OS:** Windows 10 Home Build 17134

**Issue description:** When using more than 1 RayShape2D shapes for collisions on a KinematicBody2D while not on the floor, the console returns the following error while calling move_and_slide and the game experiences extreme frame drops and the slide part of move_and_slide seems to function strangely as well on walls and ceilings, while the body is on the floor it has no issues. The issue also goes away if `stop_on_slope` parameter of move_and_slide is set to true, but then the body slowly sinks into the floor until a "real" collision (i.e. not a ray shape) collides with the surface.
```
E 0:00:03:0630   Condition ' !p_normal.is_normalized() ' is true. returned: Vector2()
  <C Source>     core/math/vector2.cpp:170 @ slide()
```

**Steps to reproduce:**
1. Create a KinematicBody2D
2. Add two or more CollisionShape2D nodes as children of the body with the RayShape2D shape
3. Run the project

**Additional notes:** I am unsure how/if this effects 3d kinematic bodies, I have not tested it there. May be worth looking into.

**Minimal reproduction project:** [RayShape Error Reproduction.zip](https://github.com/godotengine/godot/files/2766590/RayShape.Error.Reproduction.zip)
I put together a little test level and basic platforming controller so you can mess around with how it reacts to different collisions, move left/right with the arrow keys and jump with spacebar.

**Comment by piratesephiroth** [comment]
I think this was already fixed by e5b335d367103f4052fc5fd435a54ad635ec447c.
I can use multiple rayshapes just fine in the most recent builds.

Try a recent nightly: https://hugo.pro/projects/godot-builds/

**Comment by theboyboy** [comment]
@piratesephiroth I tried the build you linked (64-bit editor zip archive, specifically) and the issue persists.

**Comment by piratesephiroth** [comment]
Ah yeah, it sem to only work when stop_on_slope is set to true and the rays are pointing down.

The rayshapes were already partially broken and then stop_on_slope added a new layer of issues.

**Comment by theboyboy** [comment]
As an update, in 3.1 Beta 2 using multiple ray collision shapes in 3D also causes the errors and frame drops, and they also don't work at all for depenetration on the 3D kinematic body

**Comment by piratesephiroth** [comment]
👀

**Comment by piratesephiroth** [comment]
OK, I tested it and they are ALMOST perfect.
There's a new minor problem: if we rotate them, their collision normals stay the same.
So a rayshape point up still behaves like it was pointing down and gets stuck in ceilings.

I'l create a new issue.
