### ISSUE TITLE
No autocompletion for some singleton classes in an "if" statement 

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26114]
**Godot version:**
3.1 beta 5

**Issue description:**
There is no autocompletion list for Engine class

**Example:**
In _ready function type "if Engine." and wait for autocompletion list / hit ctrl+space. 
Result: no list. 
This is strange - works ok for AudioServer, AudioEffect, IP etc.

Not reproduces in 3.0.6

_Bugsquad edit:_
by @Chaosus - checked all of singletons for this problem

	#if ARVRServer # ok
	#if AudioServer # ok
	#if ClassDB # bad
	#if Engine # bad
	#if Geometry # bad
	#if IP # ok
	#if Input # ok
	#if InputMap # ok
	#if JSON # ok
	#if JavaScript # ok
	#if Reference # ok
	#if OS # bad
	#if Performance # ok
	#if Physics2DServer # ok
	#if PhysicsServer # ok
	#if ProjectSettings # ok
	#if ResourceLoader # bad
	#if ResourceSaver # bad
	#if TranslationServer # ok
	#if VisualScriptEditor # bad
	#if VisualServer # ok

**Comment by groud** [comment]
I was able to reproduce, but only if you start the line with `if (`. I'll adjust the title.

**Comment by Chaosus** [comment]
Detectable for all singleton classes(OS, Engine etc)

**Comment by somnivore** [comment]
This also applies to autoloads.  Furthermore, those singletons which don't autocomplete under if statements, when used outside of if statements, also don't show autocomplete for function parameters, though will show for the function itself.

**Comment by ptrojahn** [comment]
Seems to be fixed when applying #26922

**Comment by bojidar-bg** [comment]
@ptrojahn What about applying #26990?

**Comment by ptrojahn** [comment]
The behavior of #26922 and #26990 is the same, so applying #26990 should work as well.

**Comment by KoBeWi** [comment]
So what's with this issue? It's on 3.2 milestone and seems important, but the PR fixing it is for 4.0.

**Comment by mbrlabs** [comment]
Any chance this can be fixed for the next maintenance release?

**Comment by mbrlabs** [comment]
Actually it's worse. For me all custom defined classes that don't inherit from a Godot class have no autocompletion right after the `if` keyword. I declared the custom class variable statically and used `class_name`.

**Comment by me2beats** [comment]
btw autocomletion works after `while`: `while Engine` etc (see #43737)

**Comment by KoBeWi** [comment]
Fixed on master, likely by #51627

**Comment by iamjoeysox** [comment]
This still isn't really fixed on 3.5, when you try to access certain singletons inside an if statement then the autocomplete doesn't popup as it should. If you access OS on it's on for example:

`OS.set_window_fullscreen(true)`

But the following does not work:

`if OS.is_stdout_verbose():`
