### ISSUE TITLE
Failed to build GodotSharp solution

### ISSUE THREAD

**Issue by Antokolos** [godotengine/godot#26167]
**Godot version:**
3.1 beta 5 Mono x64
3.1 beta 6 Mono x64
3.1 beta 7 Mono x64
3.1 beta 8 Mono x64

**OS/device including version:**
Windows 10 / Acer Aspire E15

**Issue description:**
C# build fails

**Steps to reproduce:**
1) Clone the following project
https://github.com/StStep/ink-godot-example
2) Open it in Godot
3) Observe build error:

Проект "GodotSharp.sln" (целевые объекты Build):
	Message: Создание конфигурации решения "Release|Any CPU".
	Проект "GodotSharp.csproj" (целевые объекты по умолчанию):
		C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2126,5): error MSB4018: непредвиденная ошибка при выполнении задачи ResolveAssemblyReference".
System.NullReferenceException: Object reference not set to an instance of an object

**Comment by akien-mga** [comment]
The linked project was made for Godot 3.0 alpha 2, it's not unexpected that it would no longer be compatible with 3.1 beta 6.

I would advise to open an issue on https://github.com/StStep/ink-godot-example asking to update the project for compatibility with Godot 3.1.

I'll let @neikeq review if something should be done on Godot's end, but IMO this needs to be debugged in https://github.com/StStep/ink-godot-example first.

**Comment by Antokolos** [comment]
[test1.zip](https://github.com/godotengine/godot/files/2897157/test1.zip)
OK, here is new test project, just created in this new 3.1 beta 6
One spatial node & default cs script
![image](https://user-images.githubusercontent.com/7196697/53290631-f97db080-37d0-11e9-9f45-333503420e5a.png)

**Comment by Antokolos** [comment]
test1.zip project above works nicely in 3.1 beta 4

**Comment by Antokolos** [comment]
...but failed to build with the same error in 3.1 beta 5

**Comment by akien-mga** [comment]
The attached project builds fine for me with 3.1 beta 6 on Linux, with MSbuild 16.0.0.0 from Mono.

**Comment by Antokolos** [comment]
C:\Program Files\Mono\bin>msbuild.bat
Microsoft (R) Build Engine версии 15.7.224.30163 (xplat-master/d375bb6e Sat Jun 30 05:26:28 EDT 2018) для Mono

My Mono MSbuild version, hope that helps

**Comment by Antokolos** [comment]
There is also message in the log output:
ERROR: initialize: The loaded Core API assembly is out of sync
   At: modules/mono/mono_gd/gd_mono.cpp:356
Mono: Proceeding to unload scripts domain because of invalid API assemblies.

**Comment by Antokolos** [comment]
The same error is in the recent build 3.1 beta 7

**Comment by Antokolos** [comment]
The same error is in the recent build 3.1 beta 8
Error in log:
ERROR: call_build: A Godot Engine build callback failed.
   At: editor/editor_node.cpp:4532
This time the project was opened successfully, but failed at the build stage when I tried to run the game,

**Comment by akien-mga** [comment]
Tested on Linux with 3.1 beta 8, still works fine for me. I guess it's specific to Windows or your configuration.

**Comment by neikeq** [comment]
Can you try changing `Editor Settings > Mono > Builds > Build Tool` to `MSBuild (VS Build Tools)` and see if it builds correctly? It requires Visual Studio or Visual Studio Build Tools to be installed.
We've experienced several issues with Mono's `msbuild.bat` on Windows so it's not recommended for now.

**Comment by Antokolos** [comment]
When I changed it the first time, it was an error MSB3644 for ".NETFramework,Version=v4.5", then I edited the csproj file and manually changed
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
to
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
After that, the project was built and ran successfully!
By the way, maybe there is some option for selection of target framework version from within the Godot? :)

**Comment by neikeq** [comment]
Hmm, I had a similar issue yesterday. I had to delete the `.mono/temp` folder. Not sure if running the "clean solution" command would work as well.

**Comment by Antokolos** [comment]
Just tried on the latest beta 9, running with Mono still causing the same errors.
BUT changing to the MS Build tools indeed helps, with the only downside that I need to change target framework from v4.5 to v4.5.2 manually. Maybe it is really viable workaround for Windows system, then...

**Comment by neikeq** [comment]
Have you tried my last suggestion instead of switching the TargetFramework to v4.5.2?

**Comment by Antokolos** [comment]
Yes, I tried to delete `.mono/temp` folder, but this does not help, unfortunately
Visual Studio's msbuild complains about missing NETFramework,Version=v4.5, Mono's msbuild complains about System.NullReferenceException: Object reference not set to an instance of an object

**Comment by piratesephiroth** [comment]
Yeah, I guess I'm a victim of this now as well.
The first commits of v3.2 worked fine but now I'm getting this all the time.

![image](https://user-images.githubusercontent.com/10672233/55676301-c850cf80-58a8-11e9-8d34-86cd8d3633e0.png)

That's the Visual Studio output because it looks cleaner.
It the same that gets written to mono's logs anyway.

**Comment by neikeq** [comment]
@piratesephiroth That's a different issue which was fixed by #27729

**Comment by piratesephiroth** [comment]
oh thanks, I'll try again

**Comment by akien-mga** [comment]
@Antokolos Can you still reproduce this issue in the latest Godot 3.2 builds?

**Comment by Antokolos** [comment]
Yes, without changing the target framework from v4.5 to v4.5.2 manually in the csproj file the project does not compile. Deletion of .mono/temp folder does not help either.

**Comment by neikeq** [comment]
@Antokolos have you tried installing that version of the .NET Framework? MSBuild on Windows does not use Mono's framework when resolving assemblies (not even the MSBuild version Mono ships). So you need to install the .NET Framework.

**Comment by Antokolos** [comment]
@neikeq , I don't remember quite well, but I tried to install v4.5, and it seems that it does not help. Or maybe I've done something wrong :)
Anyway, I'm OK with changing the target framework from v4.5 to v4.5.2 manually in the csproj file workaround, it is fixing the issue for me.
So we can close this issue, if it does not bother significant number of people.

**Comment by akien-mga** [comment]
Seems like an issue specific to a partial installation of the .NET Framework, so let's close. If the docs are not clear on what needs to be installed exactly, they might need some improvement.
