### ISSUE TITLE
Fog obscures unshaded materials in GLES2, also affects Gizmos.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#26235]
**Godot version:**
Godot_v3.1-beta7
Also tested in 3.1-RC1, still present.

**OS/device including version:**
Linux Mint 19.1
NVIDIA GP106 [GeForce GTX 1060 6GB], Driver version: 415.27

**Issue description:**

As the title says, unshaded objects get obscured by fog in GLES2. 
I'm not sure what the correct behaviour is here, but the GLES3 backend always renders unshaded meshes the same way, whether fog is enabled in the scene or not.

**Steps to reproduce:**
1. Switch to GLES2.
2. Enable fog in WorldEnvironment node.
3. Add a MeshInstance with an unshaded material to the scene.
4. View the mesh from a greater distance by zooming out.
5. Compare to GLES3.

Screenshots:
GLES3:
![gles3](https://user-images.githubusercontent.com/781121/53301045-97fc2700-384e-11e9-8c59-7e768648520d.jpg)

GLES2:
![gles2](https://user-images.githubusercontent.com/781121/53301049-a34f5280-384e-11e9-8a21-d35e7bfcf506.jpg)

**Comment by EzraT** [comment]
This same problem also happens to Gizmo's, I'm guessing they use the same unshaded render mode. (?)
Look at the camera gizmo turning dark when zooming out:

![02](https://user-images.githubusercontent.com/781121/54122598-c9075a80-43fd-11e9-8d12-a6d169c842df.gif)

**Comment by EzraT** [comment]
Can this issue be re-opened? This still affects editor gizmo's in GLES2:
![blackgizmos](https://user-images.githubusercontent.com/781121/63638627-0d747300-c68b-11e9-9ac1-e145c9f72f8a.gif)

**Comment by clayjohn** [comment]
Could be related to https://github.com/godotengine/godot/issues/31019 

Can you rebuild from master but delete the ".gen.h" files from drivers/gles2/shaders first?

**Comment by EzraT** [comment]
I'm not using a self compiled build of Godot at the moment, but I will re-test this as you described.

**Comment by akien-mga** [comment]
> I'm not using a self compiled build of Godot at the moment, but I will re-test this as you described.

What version are you using then? This issue was fixed in the master branch in May, the fix is not in any stable release yet.

**Comment by akien-mga** [comment]
I see you added

> This happens in the official 3.1 build.

So it's normal, this was fixed in master, and cherry-picked for 3.1.2.

**Comment by EzraT** [comment]
Ah, good to know, thank you for clarifying @akien-mga.

**Comment by the-sink** [comment]
Not sure if I should open a new issue since this one is so old, but the problem of the 3D editor selection gizmo being obscured by fog has resurfaced (at least as of 4.0, and still appears on the latest commit in the master branch):

https://github.com/godotengine/godot/assets/18225391/57c537ab-8514-499a-8172-6f7613f183aa

Also affected by volumetric fog:

![image](https://github.com/godotengine/godot/assets/18225391/1ae4b921-c06b-4996-afd8-1d0207fd98f2)

**Comment by Calinou** [comment]
This is a known issue, which is already tracked in https://github.com/godotengine/godot-proposals/issues/2138.

That said, now that [xxx](https://github.com/godotengine/godot/pull/81286) is merged, we can use the `disable_fog` render mode for gizmo materials (lines, handles, icons).
