### ISSUE TITLE
Unable to select texture as default import preset for PNG is BitMap

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#26340]
Unable to select texture 
1.step
![default](https://user-images.githubusercontent.com/2855349/53476410-4bfaed80-3aad-11e9-8f81-c593c49ed902.png)
2.step
![default](https://user-images.githubusercontent.com/2855349/53479505-2d4c2500-3ab4-11e9-92ff-153559da55d1.png)
3.step
![default](https://user-images.githubusercontent.com/2855349/53479562-4b198a00-3ab4-11e9-892b-c793522be6a4.png)
4.step
![default](https://user-images.githubusercontent.com/2855349/53479589-5967a600-3ab4-11e9-9c47-018decbd7b45.png)

**Godot version:**

![default](https://user-images.githubusercontent.com/2855349/53476426-587f4600-3aad-11e9-8a26-8890c4576b73.png)

**Comment by akien-mga** [comment]
It works fine for me, can you be more explicit?

**Comment by akien-mga** [comment]
Also, there's no commit 6241e82 in the master branch, do you have custom made changes?

**Comment by akien-mga** [comment]
> Also, there's no commit [6241e82](https://github.com/godotengine/godot/commit/6241e82d8ad4eb51459ad73521c90096c2232959) in the master branch, do you have custom made changes?

Ah I see it's a custom PR on your fork for 0ba75c195. I'd advise to use `git pull --rebase` instead of keep the same git history as the upstream project and just rebase your own changes on top of it.

I haven't built that commit/HEAD yet today, will do in a bit. Might be a bug from #26331.

**Comment by cjmxp** [comment]
I don't need to change it.

**Comment by akien-mga** [comment]
Can't reproduce on Mageia 7 Linux x86_64 with 8889089. Might be Windows-specific, maybe related to #26342.

> Issues arising from today's update

Thanks. Please mention that from the start next time, it's very useful information to find what cause an issue :)

**Comment by hpvb** [comment]
I can't reproduce this on current master on Win 10 home

**Comment by hpvb** [comment]
Can you please try on this build: https://tmm.cx/nextcloud/s/9riMKz9iHNZYGqJ

**Comment by cjmxp** [comment]
@hpvb 
![default](https://user-images.githubusercontent.com/2855349/53490391-8f198880-3ace-11e9-9c75-f2ef525a4efc.png)
![default](https://user-images.githubusercontent.com/2855349/53490427-a0629500-3ace-11e9-8517-68a438f9d8eb.png)
![default](https://user-images.githubusercontent.com/2855349/53490441-a9536680-3ace-11e9-83e8-6703be15242f.png)
![default](https://user-images.githubusercontent.com/2855349/53490456-b1130b00-3ace-11e9-8e25-fa5a29e41781.png)

**Comment by cjmxp** [comment]
@hpvb I downloaded and used https://tmm.cx/nextcloud/s/9riMKz9iHNZYGqJ

**Comment by cjmxp** [comment]
![default](https://user-images.githubusercontent.com/2855349/53490566-f3d4e300-3ace-11e9-81ef-83a6f8322b25.png)

**Comment by hpvb** [comment]
I don't understand what you are trying to do. Can you make a screen capture video?

**Comment by reduz** [comment]
This is probably fixed now, please test again.

**Comment by cjmxp** [comment]
@reduz @hpvb 
The bug still exists。
![aa](https://user-images.githubusercontent.com/2855349/53491806-3c41d000-3ad2-11e9-953b-9b96223574dd.gif)

**Comment by akien-mga** [comment]
Could you upload that `icon.png`? The error message references `BitMap`, it sounds like it might not be a PNG.

**Comment by volzhs** [comment]
hm. I'm facing same issue.

I found that default import preset for png is `BitMap` not `Image`.
So, thumbnail for newly added png is B&W.

Changing import preset for png asks me to restart editor which is odd.
after restarting, preset is changed but no options for Image preset.
also can't assign it to texture either.

by creating new project, I faced same situation with @cjmxp

**Comment by volzhs** [comment]
Here's demonstration.

https://streamable.com/oetln
