### ISSUE TITLE
Add ADB error output when using one-click deploy

### ISSUE THREAD

**Issue by Nolkaloid** [godotengine/godot#26579]
**Godot version:**
Godot 3.1 beta-10

**OS/device including version:**
Ubuntu 18.04
Xiaomi Redmi 6 - Android 8.1

**Issue description:**
Currently when the one-click deploy to Android fails, there is just a generic message `could not install to device`, however when using ADB directly in the command line there is an explicit error that helps to solve the problem. Example: 
`Failed to install SecretOfTheUniverse.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl2050218568.tmp/base.apk: File assets/Sounds/Méchant.ogg.import in manifest does not exist]
`

**Expected Behaviour:**
When failing to install to the device, the message should display an explicit error.

**Comment by nightblade9** [comment]
I'm getting this too. Do you have a work-around for the actual issue?

**Comment by lurppa** [comment]
> I'm getting this too. Do you have a work-around for the actual issue?

In case someone is still interested: renaming assets to not contain any non-English characters solved this for me.

**Comment by mrkdji** [comment]
I believe this is solved in 3.4 @akien-mga

**Comment by Calinou** [comment]
This was fixed in 3.4.3rc and 3.5beta by https://github.com/godotengine/godot/pull/56517, closing.

**Comment by Nolkaloid** [comment]
I believe #56517 it doesn't fix the "issue" I raised 3 years ago. To be honest it was more of a quality of life proposal : "Display the output from ADB when directly installing to an Android device". But I understand that this issue in not a priority an that there a dozens of critical issues waiting to be fixed^^
