### ISSUE TITLE
Audio busses only work in editor and don't save volume (when not in root)

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#26683]
**Godot version:**
3.1 Beta 10

**OS/device including version:**
Windows 10

**Issue description:**
Audio busses only work in the editor. When you run the game, almost no effects work (I found chorus to work slightly though). Also, the volume doesn't save.

**Steps to reproduce:**
1. Create a new audio bus in default_bus_layouts.
2. Add Reverb to it.
3. Create an AudioStreamPlayer, attach an audio stream to it and change the bus to be the bus with reverb.
4. Enable playing. Note that the reverb works.
5. Turn on autoplay and play the scene with the stream player. Listen as no reverb can be heard.

**Comment by 11clock** [comment]
More testing and I found out that it doesn't work when not in the root folder.

**Comment by Xrayez** [comment]
Yeah I think I've had similar issue, audio buses won't load either if creating and using non-default bus layout. It only works on editor restart for me.

**Comment by Anutrix** [comment]
@11clock  Can you provide a minimal test project?

**Comment by Anutrix** [comment]
Isn't this fixed in #27644?
Because couldn't reproduce in latest master https://github.com/godotengine/godot/commit/8a1dc8393a68be8dc17d74e8b2441d298eb42ded.

**Comment by YeldhamDev** [comment]
@11clock Can you still reproduce this?

**Comment by Ranoller** [comment]
Well, i have similar problems in a compilation from october/2019. It's seem some kind of incoherences between the buses resource file and the editor. Sometimes the editor changes are not stored in the file, sometimes the file is not loaded in the execution and is loaded the editor configuration. Sometimes if the file is loaded by the "load" button in the Audio bottom panel, the editor load some "catched" data that is not stored in the file... is really strange. I have a node structure to reply the mixer and make mixer changes in game and i having some headache with this. Bug is erratic, not easy to have common pattern. But i confirm that the bug is alive.

**Comment by Ranoller** [comment]
Some test:

Having 2 bus layouts... this sequence fails:

1- Load bus layout 1
2- Change bus 1 in editor (changes are stored on disk in every mixer change).
3- Load layout 2
4- Load layout 1 other time

Fail: Changes stored in disk are not reloaded in the editor mixer. Bus layout 1 maintains same mixer configuration stored on godot start (but data abstraction was modificated in pass 2, and changes was stored in disk). So, godot is not refreshing the mixer when layout is loaded, only at start.

**Comment by akien-mga** [comment]
A minimal project that reproduces the issue would be very helpful.

**Comment by Xrayez** [comment]
Changing audio buses works both in editor and in-game (this might have been fixed already). As noticed by @Ranoller, it seems like the cached resource is being reloaded despite making changes to the bus.

1. Go to Audio, delete the `Reverb` bus.
2. <kbd>Ctrl</kbd> + <kbd>S</kbd> to save.
3. Load the `default_bus_layout.tres` via the FileSystem dock.
4. Notice the bus is there again with the same effect. In some cases I've seen it being titled differently as `New Bus` for instance (probably if you test this enough times, this is where the `AudioStreamPlayer` node might fallback the bus property to `Master`, so it won't work 
 while running the project because of it as a side effect).

I can only save the bus layout if I quit the editor. Might also be related to what particular bus is selected as default in project settings.

**Minimal project**
[audio-bus-layout-not-saved.zip](https://github.com/godotengine/godot/files/4064269/audio-bus-layout-not-saved.zip)

**Comment by lukaskotik** [comment]
Maybe I am missing something, but for me the issue still remains in 3.2.1. Just in a simple scene with AudioStreamPlayer with ogg audio file. Whatever bus I set in editor as bus property, the audio is always send to Master bus when playing in the editor. If playing scene, everything works as expected.
