### ISSUE TITLE
Soft bodies do not collide with each other

### ISSUE THREAD

**Issue by puchik** [godotengine/godot#27039]
**Godot version:**

3.1 Stable

**OS/device including version:**

Windows 10 1809 64bit, ver 17763.316
GTX 1080, driver 418.81

**Issue description:**

Soft bodies do not collide with other soft bodies. Expected them to collide.

**Steps to reproduce:**
1. Create a soft body and add a plane mesh (Godot internal).
2. Create a soft body sphere (mesh from Blender).
3. Pin the edges of the plane so it acts as a "net".
4. Move the ball on top of the plane and press play. Ball falls through without colliding/getting caught.

Spheres do not collide with each other either (minimal project has 2 spheres and 1 plane).

**Minimal reproduction project:**

[softbodytest.zip](https://github.com/godotengine/godot/files/2964990/softbodytest.zip)

(Performance is also fairly slow but I'm not sure if it's expected with soft bodies like these. Once both balls are on the ground in the example project I get a lot of lag with an r5 2400g and GTX 1080. Would it be fixed by #22448 ?)

**Comment by AndreaCatania** [comment]
Last time I tried it I saw that is not possible make the soft body collide each other, I tried ask it to the Bullet github and they answered that the soft part is broken.

**Comment by puchik** [comment]
Was it recently broken? I don't know much about Bullet but I found these 2 videos before submitting this and figured Bullet supports it. Could be something else entirely for all I know...

https://www.youtube.com/watch?v=9sh-D0nejUY
https://www.youtube.com/watch?v=sEyDcVjkc9U 

Makes sense if it has to be fixed in Bullet first though! Would this be closed or left open until then?

As for the performance should there be an issue created for that as well? The reproduciton project lags badly for me but if someone else can try and let me know if it's expected or just me.

**Comment by Chaosus** [comment]
> Would this be closed or left open until then?

Better keep it opened, its indeed a non-desirable behavior which should be fixed soon or later, with Bullet or not

**Comment by akien-mga** [comment]
Still reproducible in 3.2.2 RC 2.

Note that using PlaneMesh as a collider is not supported, as Plane is an infinite and infinitely thin shape so colliders pass through. It's better to use QuadMesh for this purpose, or a thin CubeMesh.

But that doesn't change anything to the non-working soft body collisions.
