### ISSUE TITLE
Engine is not of type Object

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27131]
**Godot version:**

3.1

**OS/device including version:**

Windows

**Issue description:**

https://cdn.discordapp.com/attachments/342056330523049988/556535791699099675/unknown.png

**Steps to reproduce:**
https://cdn.discordapp.com/attachments/342056330523049988/556535791699099675/unknown.png

Temporary fix: `var eng = Engine`

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Probably because it is `_Engine` internally, like a few other singletons (e.g. `_OS`). Might also explain why auto completion is iffy for `Engine`.

**Comment by isaacremnant** [comment]
This is fixed in master and tweening `time_scale` works; now` typeof(Engine) == 17` which is `TYPE_OBJECT`.

**Comment by akien-mga** [comment]
Thanks, closing as fixed then.

**Comment by anissen** [comment]
This error still occurs if you write this:
```gdscript
Tween.new().interpolate_property(Engine, "time_scale", ...
```

But not if you write this:
```gdscript
var tween = Tween.new()
tween.interpolate_property(Engine, "time_scale", ...
```

🤷‍♂

**Comment by isaacremnant** [comment]
It works with `var e = Engine ...interpolate_property(e...`

This looks like some sort of parsing bug, maybe because there are two class names on the same line? Should open a new issue.

**Comment by akien-mga** [comment]
A new issue would be good indeed.

**Comment by anissen** [comment]
I've created a new issue for this specific error: https://github.com/godotengine/godot/issues/32302
