### ISSUE TITLE
Complex model render incorrectly in 3.1 using GLES3

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#27390]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10, Vega 8 and Intel integrated, latest drivers

**Issue description:**
Imported model is not completly rendered when using GLES3, but it does when using GLES2, it also rendered correctly in versin 3.0.6

**Steps to reproduce:**
I'm linking a Git project because of model complexity project size is too big. I'm importing models using Fuse CC->Mixamo->Custom Script, 
[In this video](https://youtu.be/QYfEXgkOYnE) a few gaps are visible in the forehead and the neck areas.
[In this video](https://youtu.be/yzclSGAC4s4) the full left arm is missing.
The models have the same base body mesh, with 65 bones and about 80 blenshapes, second has more animations, meshes and materials (meshes were added trying to hide as much skin as possible, and skull polygons were removed too).

**Minimal reproduction project:**
[Git project](https://gitlab.com/DavidOC/GodotJam062018)

**Comment by David-Ochoa** [comment]
I found the solution was increasing the Blend Shape Max Buffer Size Kb property. (rendering/limits/buffers/blend_shape_max_buffer_size_kb). I just doubled it from 4096 Kb to 8192 Kb. The question now is how do I calculate optimal size? What should I considerate? Docs say "Max buffer size for blend shapes. Any blend shape bigger than this will not work." Is it the size for the bigger blend shape or for all the blend shapes? I guess it should be something like Vertex Array size + Triangles Array Size multiplied by sctruct size

**Comment by akien-mga** [comment]
CC @clayjohn @fire - would you know how to document what relation can be used to figure out a suitable max buffer size for the transform feedback for a given model?

**Comment by fire** [comment]
I'm not able to dedicate much attention to this, but can check in with clayjohn.

**Comment by MJacred** [comment]
Could this have been fixed by https://github.com/godotengine/godot/pull/60832 ?

**Comment by Calinou** [comment]
@David-Ochoa Can you (or anyone else) still reproduce this bug in [Godot 3.5rc6](https://godotengine.org/article/release-candidate-godot-3-5-rc-6) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by David-Ochoa** [comment]
> @David-Ochoa Can you (or anyone else) still reproduce this bug in [Godot 3.5rc6](https://godotengine.org/article/release-candidate-godot-3-5-rc-6) or any later release?

It is still present:
![image](https://user-images.githubusercontent.com/13645633/180238875-e123666e-b55e-4caa-bc1f-42f2aa2438e8.png)

**Comment by aaronfranke** [comment]
Is this bug only for 3.x, or does it also occur in 4.x?
