### ISSUE TITLE
Compile issue on OSX for platform iphone error with Xcode 7+ (templates must have C++ linkages)

### ISSUE THREAD

**Issue by rssqian** [godotengine/godot#2740]
With no code changes, and on master code.
Many thanks.

```
users-MacBook-Pro:godot username$ scons p=iphone
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o platform/iphone/game_center.iphone.debug.o -c -fno-objc-arc -arch armv7 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -Wno-trigraphs -fpascal-strings -Wmissing-prototypes -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk -gdwarf-2 -fvisibility=hidden -Wno-sign-conversion -mthumb "-DIBOutlet=__attribute__((iboutlet))" "-DIBOutletCollection(ClassName)=__attribute__((iboutletcollection(ClassName)))" "-DIBAction=void)__attribute__((ibaction)" -miphoneos-version-min=5.1.1 -MMD -MT dependencies -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/ -D_DEBUG -DDEBUG=1 -gdwarf-2 -Wall -O0 -DDEBUG_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -fblocks -DGAME_CENTER_ENABLED -DSTOREKIT_ENABLED -DICLOUD_ENABLED -DDEBUG_MEMORY_ENABLED -DIPHONE_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DMPC_FIXED_POINT -fexceptions -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -DGLES2_OVERRIDE -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/iphone -Iplatform/iphone/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/AudioUnit.framework/Headers -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Iplatform/iphone/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes -Idrivers/opus/silk/float -Idrivers/opus -Idrivers/opus/celt -Idrivers/opus/silk -Idrivers/opus/silk/float platform/iphone/game_center.mm
In file included from platform/iphone/game_center.mm:34:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//System/Library/Frameworks/GameKit.framework/Headers/GameKit.h:47:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/simd.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/vector.h:46:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/logic.h:226:5:{226:5-226:33}: error: templates must have C++ linkage [2]
     template <typename inttypeN> static __SIMD_INLINE__ __SIMD_BOOLEAN_TYPE__ all(const inttypeN predicate) { return ::vector_all(predicate); }
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/logic.h:227:5:{227:5-227:33}: error: templates must have C++ linkage [2]
     template <typename inttypeN> static __SIMD_INLINE__ __SIMD_BOOLEAN_TYPE__ any(const inttypeN predicate) { return ::vector_any(predicate); }
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/logic.h:228:5:{228:5-228:51}: error: templates must have C++ linkage [2]
     template <typename inttypeN, typename fptypeN> static __SIMD_INLINE__ fptypeN select(const fptypeN x, const fptypeN y, const inttypeN predicate) { return ::vector_select(x,y,predicate); }
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/logic.h:229:5:{229:5-229:49}: error: templates must have C++ linkage [2]
     template <typename inttypeN, typename typeN> static __SIMD_INLINE__ typeN bitselect(const typeN x, const typeN y, const inttypeN mask) { return ::vector_bitselect(x,y,mask); }
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from platform/iphone/game_center.mm:34:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//System/Library/Frameworks/GameKit.framework/Headers/GameKit.h:47:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/simd.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/vector.h:47:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/math.h:202:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/cmath:51:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:76:3:{76:3-76:52}: error: templates must have C++ linkage [2]
   template<typename _Iterator, typename _Container>
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:90:3:{90:3-90:25}: error: templates must have C++ linkage [2]
   template<typename _Tp>
   ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:92:3:{92:3-92:25}: error: templates must have C++ linkage [2]
   template<typename _Tp>
   ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:100:3:{100:3-100:17}: error: templates must have C++ linkage [2]
   template<bool>
   ^~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:105:12:{105:24-105:30}: error: explicit specialization of non-template struct '__truth_type' [4]
     struct __truth_type<true>
            ^           ~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:110:3:{110:3-110:33}: error: templates must have C++ linkage [2]
   template<class _Sp, class _Tp>
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:118:3:{118:3-118:31}: error: templates must have C++ linkage [2]
   template<typename, typename>
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:126:12:{126:22-126:32}: error: explicit specialization of non-template struct '__are_same' [4]
     struct __are_same<_Tp, _Tp>
            ^         ~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:125:3:{125:3-125:25}: error: templates must have C++ linkage [2]
   template<typename _Tp>
   ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:133:3:{133:3-133:25}: error: templates must have C++ linkage [2]
   template<typename _Tp>
   ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:141:12:{141:21-141:27}: error: explicit specialization of non-template struct '__is_void' [4]
     struct __is_void<void>
            ^        ~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:150:3:{150:3-150:25}: error: templates must have C++ linkage [2]
   template<typename _Tp>
   ^~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:161:12:{161:24-161:30}: error: explicit specialization of non-template struct '__is_integer' [4]
     struct __is_integer<bool>
            ^           ~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:168:12:{168:24-168:30}: error: explicit specialization of non-template struct '__is_integer' [4]
     struct __is_integer<char>
            ^           ~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:168:12: error: redefinition of '__is_integer' [2]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk//usr/include/c++/4.2.1/bits/cpp_type_traits.h:161:12: note: previous definition is here
     struct __is_integer<bool>
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
scons: *** [platform/iphone/game_center.iphone.debug.o] Error 1
scons: building terminated because of errors.
```

**Comment by romulox-x** [comment]
I see from your comment on the closed PR that fixed this, you're on Xcode 7.  You can fix this by moving the offending lines outside the 'extern C' blocks, but it's unclear how it's going to affect building in Xcode 6, since no one I've talked to so far has it.  In the example error you've posted, this means moving the GameKit.h line outside that extern C scope.  It's the same for the other errors that will follow.  Only a few files have this problem.  You can see them in the closed PR, mixed in with the other changes.

I'm starting to think we should just commit the change that fixes this, and see if anyone in Xcode 6 has a problem.  I'm not a big fan of this "just use it and see what breaks" approach, but since no one with Xcode 6 has chimed in yet, we have no other way to test these changes.  We know it's broken in 7.  I suppose fixing it in 7 and possibly breaking it in 6 is better than leaving it definitely broken in 7.

**Comment by punto-** [comment]
What is the latest non-beta version of xcode at the moment?

**Comment by romulox-x** [comment]
Seems to be 7.1, with a 7.2 beta available.

**Comment by rssqian** [comment]
Hi, @romulox-x 

after remove "extern c" in related files eg. game_center.mm and icloud.mm.
as U said, moving the "GameKit.h" and t "app_delegate.h" line outside that extern C scope.
Successfully Compiled with Xcode 7.1.

Also,I agree that It's a good idea to fix it to make 7.+ work well. as backward compatibility sometimes is much simpler.

Many thanks from Feng.

**Comment by rssqian** [comment]
resolved. Close this issue

**Comment by akien-mga** [comment]
Reopening, as it's not resolved but only worked around. We still need a proper fix pushed in the repo if we want to support Xcode 7+.

**Comment by akien-mga** [comment]
@romulox-x Could you make a PR to fix this? @punto- seems fine with your proposal, see https://www.facebook.com/groups/godotengine/permalink/689705551166042/?comment_id=689723601164237&reply_comment_id=689726034497327&total_comments=2&comment_tracking={%22tn%22%3A%22R%22}

**Comment by akien-mga** [comment]
@kurikaesu Did your 402c24e commit fix this issue?

**Comment by punto-** [comment]
didn't we merge the one with #ifdefs for this the other day?

**Comment by akien-mga** [comment]
Yeah I believe it was 402c24e. So let's close.
