### ISSUE TITLE
Configurable debugging information refresh rate

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#2794]
Currently, the debugging information (like FPS) updates every second, both in debugger and game. This can make the FPS reporting less accurate.

The refresh rate of debugging information could be configurable in the project settings.

**Comment by akien-mga** [comment]
@Calinou If you're still interested in this change, I think you could have a go at implementing it, shouldn't be hard :)

**Comment by mhilbrunner** [comment]
Done by https://github.com/godotengine/godot/pull/18998

**Comment by Calinou** [comment]
Note that this was reverted in https://github.com/godotengine/godot/pull/18998#issuecomment-392506052, which means this feature is still not implemented as of today.
