### ISSUE TITLE
Godot_v3.1-stable_linux_headless.64 re-imports all resources when exporting

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#27963]
**Godot version:**
3.1

**OS/device including version:**
linux_headless

**Issue description:**

When run with `--export` the headless version will re-import all resources, causing the export to take 20x longer than before.

```
~/bin/Godot_v3.1-stable_linux_headless.64 --export Linux/X11 Kinematic\ Character\ 3D.x86_64 
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:518.
ERROR: poll: /home/jpate/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/resource_format_text.cpp:561.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: /home/jpate/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:285.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:872.
reimport: begin: (Re)Importing Assets steps: 2
	reimport: step 0: purple_wood.png
	reimport: step 1: white_wood.png
savepack: begin: Packing steps: 102
	savepack: step 2: Storing File: res://cubelib.res
	savepack: step 14: Storing File: res://cubio.gdc
	savepack: step 27: Storing File: res://follow_camera.gdc
	savepack: step 39: Storing File: res://.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
	savepack: step 39: Storing File: res://icon.png.import
	savepack: step 52: Storing File: res://level.scn
	savepack: step 64: Storing File: res://.import/purple_wood.png-ae65a206e7a59edf759728c3bad04e56.s3tc.stex
	savepack: step 64: Storing File: res://purple_wood.png.import
	savepack: step 77: Storing File: res://purplecube.scn
	savepack: step 89: Storing File: res://.import/white_wood.png-6895acd60ce97b4315494d2be377c357.s3tc.stex
	savepack: step 89: Storing File: res://white_wood.png.import
	savepack: step 102: Storing File: res://cubio.gd.remap
	savepack: step 102: Storing File: res://follow_camera.gd.remap
	savepack: step 102: Storing File: res://icon.png
	savepack: step 102: Storing File: res://project.binary
savepack: end
reimport: end
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```
**Steps to reproduce:**
Download attached modified version of *kinematic_character* demo
extract
```
cd kinematic_character_export/kinematic_character
path/to/Godot_v3.1-stable_linux_headless.64 --export Linux/X11 Kinematic\ Character\ 3D.x86_64
```

**Minimal reproduction project:**
[kinematic_character_export.zip](https://github.com/godotengine/godot/files/3075038/kinematic_character_export.zip)

**Comment by jamie-pate** [comment]
looks like it's getting tripped up here

Can we warn on invalid import settings? It doesn't seem to reimport them when i use the non-headless version.

```if (!ResourceFormatImporter::get_singleton()->are_import_settings_valid(p_path)) {
		//reimport settings are not valid, reimport
		return true;
	}```

**Comment by aaronfranke** [comment]
When you say "than before", are you comparing to Godot 3.0?

**Comment by jamie-pate** [comment]
Yes, with 3.0 I could use --export with the headless build and export each platform and it did not re-import every resource.

With 3.1 it fails to accept the resource file as up to date and re-imports every resource. (Because `VSG::storage->has_os_feature()` always returns false on the headless build.

**Comment by Mithul** [comment]
Facing the same as @jamie-pate  for "Linux/X11" as well. Using headless Godot `Godot_v3.1.1-stable_linux_headless.64`

Command
`./Godot_v3.1.1-stable_linux_headless.64 --export "Linux/X11" builds/`

Output
```
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:523.
ERROR: poll: /home/mithul/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/resource_format_text.cpp:561.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: /home/mithul/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:285.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:871.
ERROR: copy: Failed to open 
   At: core/os/dir_access.cpp:300.
ERROR: _fs_changed: Project export failed with error code 12.
   At: editor/editor_node.cpp:495.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```

Using regular Linux build fails with 
```
> ./godot --export "blah" `readlink -f builds/`
ERROR: initialize: X11 Display is not available
   At: platform/x11/os_x11.cpp:126.
```

The non-headless server also fails with
```
ERROR: _load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:285.
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1739.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2095.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:425.
ERROR: cleanup: Condition ' allocs_used > 0 ' is true.
   At: core/pool_vector.cpp:70.
```

**Comment by Mtaethefarmer** [comment]
I was able to get rid of the re-importing issue by being inside the project folder and specifying the 'project.godot' file.

```
godot project.godot -v -q --export "Linux/X11" ~/project/build/linux/$EXPORT_NAME.x86_64
```

There is still the 
```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: ./core/self_list.h:111.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:70.
```
 but that is a different issue all together.

**Comment by jamie-pate** [comment]
`Godot_v3.2-stable_linux_headless.64 project.godot --export Linux/X11 '../export/tmp/$EXPORTNAME-linux'` does not solve the problem for me.

**Comment by Calinou** [comment]
> -q got rid of the re-import

It probably just silenced the re-import as it's the *quiet* mode ;)

**Comment by jamie-pate** [comment]
Well it also silenced the exported files. Are you sure it's not --quit?

**Comment by Calinou** [comment]
@jamie-pate No, `--quit` has no shorthand, unlike `--quiet` whose shorthand is `-q`.

**Comment by akien-mga** [comment]
> @jamie-pate `--quit` doesn't have a shorthand, unlike `--quiet` whose shorthand is `-q`.

Hm ;)

```
$ godot-git --help | egrep "\-\-(quit|quiet)"
  --quiet                          Quiet mode, silences stdout messages. Errors are still displayed.
  -q, --quit                       Quit after the first iteration.
```

**Comment by Calinou** [comment]
@akien-mga Seems like I was wrong then. It's kind of unexpected, `-q` should probably have been a shorthand for `--quiet` as it's a more common operation.

**Comment by fire** [comment]
Can we recreate this on the latest stable?

**Comment by asheraryam** [comment]
@fire  I'll try again in the weekend with the most recent 3.2 release

 It was happening to me on CI for version 3.2.2 (or 3.2.3) last spring.

**Comment by KoBeWi** [comment]
Is this maybe fixed in 4.0?

**Comment by jamie-pate** [comment]
https://github.com/godotengine/godot/issues/69511 maybe it's worse in godot 4? :D

Still an issue on 3.5.2-rc1 with `--export-pack`

```Bash
$ ./test.sh 
Godot Engine v3.5.2.rc1.official.f5f0543ae - https://godotengine.org
 
reimport: begin: (Re)Importing Assets steps: 1
	reimport: step 0: icon-texture.png
```

[repro-headless-png-always-reimports.zip](https://github.com/godotengine/godot/files/10315441/repro-headless-png-always-reimports.zip)
