### ISSUE TITLE
Children list of inherited scene doesn't update after add/delete nodes in parent scene

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#28090]
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64

**Prerequisites:**
1. Create scene 1 - "Level",
2. Create scene 2 - "Parent",
3. Create scene 3 - "Something" as "New inherited scene" of "Parent"

**Steps to reproduce:**
1. In "Level" scene make instance of "Something",
2. Set "Editable children" is ON,
3. Add one or more child nodes in "Parent" scene and save this scene,
4. Go back to "Level" scene tab

**Result:**
Created nodes in step 3 are not shown. They will appear only if you close and re-open "Level".
Meanwhile, if you change tab to "something" you will see new nodes imediately.

**Note:** same result if you delete node in step 3

**Expected:**
Nodes list updated imediately, don't need to re-open tab to see changes.

**GIF:**
![bug16042019](https://user-images.githubusercontent.com/1552169/56231884-2d19e000-6088-11e9-8646-c7ea45ee86ce.gif)

**Minimal reproduction project:**
This project contains only prerequesites. You should open all three scenes and repeat 3-4 steps.
[test16042019.zip](https://github.com/godotengine/godot/files/3086184/test16042019.zip)

**Comment by breakmt** [comment]
Offtopic:
As I see, every issue around mine is tagged as bug or something. Except this one. Why so? Is it very complicated or bad written?

**Comment by bojidar-bg** [comment]
@breakmt chill. There are untagged issues from last July as well. It sometimes occurs that no one is sure how to tag an issue exactly.

**Comment by breakmt** [comment]
@bojidar-bg I just saw that every issue in first 3 pages are taged except this one and I thought maybe something wrong with it and I should fix it.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta3

**Comment by cidwel** [comment]
Still valid in 4.2 Beta3. If I delete a node in parent, it still appears in children and it doesn't let you remove it because it says it is being inherited. Doesn't feel like a correct behaviour

**Comment by ta-david-yu** [comment]
Still valid in 4.3.
