### ISSUE TITLE
Editor sometimes crashes when I change image. 

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#28539]
**Godot version:**

Godot 3.1.2-devel (e802da4)

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

I'm preparing my textures for pvrtc conversion. I extend some textures to square and make atlas textures in my scenes to use the part of this square.
Sometimes the editor doesn't show preview of changed image. When I do something with it (for example use it as atlas texture) the editor crashes with this log:

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff7686af5a _sigtramp + 26
[2] 2   ???                                 0x000070000503f810 0x0 + 123145386457104
[3] Image::get_rect(Rect2 const&) const (in godot.osx.tools.64) (image.cpp:1915)
[4] EditorTexturePreviewPlugin::generate(Ref<Resource> const&, Vector2) const (in godot.osx.tools.64) (editor_preview_plugins.cpp:101)
[5] EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) (in godot.osx.tools.64) (editor_resource_preview.cpp:151)
[6] EditorResourcePreview::_thread() (in godot.osx.tools.64) (editor_resource_preview.cpp:224)
[7] EditorResourcePreview::_thread_func(void*) (in godot.osx.tools.64) (editor_resource_preview.cpp:94)
[8] ThreadPosix::thread_callback(void*) (in godot.osx.tools.64) (thread_posix.cpp:76)
[9] 9   libsystem_pthread.dylib             0x00007fff76874661 _pthread_body + 340
[10] 10  libsystem_pthread.dylib             0x00007fff7687450d _pthread_body + 0
[11] 11  libsystem_pthread.dylib             0x00007fff76873bf9 thread_start + 13
-- END OF BACKTRACE --
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
A minimal reproduction project or detailed reliable reproduction steps would be nice.

**Comment by DrMoriarty** [comment]
It's not easy to find reproduction steps queue. For example, now I reimport 8 textures (with pvrtc encoding). Editor complete importing without errors, when it shows preview for changed textures. And after several minutes it crashes (I did'n do anything with godot, I only waited for importing and then I edit some code in my external editor)

**Comment by noidexe** [comment]
I'm having the same issue. Sometimes it crashes, sometimes it doesn't. Now I'm trying to open the same project cloned in a different computer and it always crashes on reimport with the following error:
```
Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce GTX 1050/PCIe/SSE2
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms
CORE API HASH: -7323055289690356460
EDITOR API HASH: 4311324559216891413
Loading resource: C:\Users/lisan/AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
EditorSettings: Save OK!
Loaded builtin certs
Editing project: C:/Users/lisan/Documents/GitHub/button-city/src (C:::Users::lisan::Documents::GitHub::button-city::src)
EditorSettings: Save OK!

C:\Users\lisan\Documents\Godot>OpenGL ES 2.0 Renderer: GeForce GTX 1050/PCIe/SSE2
Assertion failed!

Program: C:\Users\lisan\Documents\Godot\Godot_v3.1.1-stable_win64.exe
File: thirdparty/pvrtccompressor/PvrTcEncoder.cpp, Line 388

Expression: bitmap.GetBitmapWidth() == bitmap.GetBitmapHeight()
```
It seems it crashes when trying to import a file called cyan_building.png with the following settings in it's companion .import file
```
[remap]

importer="texture"
type="StreamTexture"
path="res://.import/cyan_building.png-44dd14dd42e8d0aa94f0e3a26003ae41.stex"
metadata={
"vram_texture": false
}

[deps]

source_file="res://textures/cyan_building.png"
dest_files=[ "res://.import/cyan_building.png-44dd14dd42e8d0aa94f0e3a26003ae41.stex" ]

[params]

compress/mode=2
compress/lossy_quality=0.7
compress/hdr_mode=0
compress/bptc_ldr=0
compress/normal_map=0
flags/repeat=true
flags/filter=true
flags/mipmaps=true
flags/anisotropic=false
flags/srgb=2
process/fix_alpha_border=true
process/premult_alpha=false
process/HDR_as_SRGB=false
process/invert_color=false
stream=false
size_limit=0
detect_3d=false
svg/scale=1.0
```
I'll attach the files generated in the .import folder

[dotimport.zip](https://github.com/godotengine/godot/files/3168470/dotimport.zip)

**Comment by noidexe** [comment]
Forgot to add the actual file. It is a square image and a power of 2
![cyan_building](https://user-images.githubusercontent.com/526829/57563230-d1363480-7371-11e9-8f4b-bf8896d63f3f.png)

I've tested this with 3.1-beta3 and 3.1.1-stable and it crashes with the same error as in the latest 3.2 from Calinous daily builds.

**Comment by noidexe** [comment]
This is the png file in question. As you can see. It is not square, which seems to be triggering the assertion in question. As you can see it is not square and that seems to be failing an assertion in PvrTcEncoder.cpp which is taking down the whole engine.

![cyan_building](https://user-images.githubusercontent.com/526829/57563449-5d495b80-7374-11e9-86a9-45c853045f2f.png)

**Comment by DrMoriarty** [comment]
@noidexe Your issue already fixed by https://github.com/godotengine/godot/pull/28563
It will be in version 3.1.2 and in 3.2

**Comment by akien-mga** [comment]
@DrMoriarty Can you still reproduce this issue in the current master branch / 3.2 builds?

**Comment by DrMoriarty** [comment]
@akien-mga No, I didn't see this bug in 3.2 betas

**Comment by akien-mga** [comment]
Thanks, let's close then.
