### ISSUE TITLE
Node names overlap on bottuns in scene tree when the width is minimum

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot#28823]
**Godot version:** 3.1.1

**OS/device including version:** Linux (manjaro)

**Issue description:**
Node names overlap on bottuns in scene tree when the width is minimum otherwise it is normal.

**Steps to reproduce:**
Reduce the size of the secne panel to its minimum size.
![Screenshot from 2019-05-11 15-30-01](https://user-images.githubusercontent.com/29702428/57568245-2cb00300-7402-11e9-9c45-31d34e7d3bfd.png)

*Bugsquad edit (keywords for easier searching):* scene dock, small, narrow

**Comment by YeldhamDev** [comment]
I don't see what much can be done about this, since if we just make the minimum size larger, it will still happen with larger children chains.

**Comment by Zireael07** [comment]
Maybe collapse icons somehow to the right (so you only get a single icon at very low screen widths, click on the icon to see a menu of all the icons)?

**Comment by Janglee123** [comment]
![Peek 2019-05-11 21-25](https://user-images.githubusercontent.com/29702428/57572058-782ed500-7433-11e9-8d9a-3b9691791eee.gif)

**Comment by menip** [comment]
I like the idea from Zireael07. Could collapse icons into some + button.  
Could also fix the issue visible above where names become visible after being completely covered, and have them stay hidden. However, I'd rather see my names and have icons be collapsed.

**Comment by KoBeWi** [comment]
Fixed in 3.2

**Comment by volzhs** [comment]
![node_name](https://user-images.githubusercontent.com/8281454/91234569-76933880-e76e-11ea-907e-8582a18d0e9e.gif)
I can still reproduce it with 3.2.3.rc4 6b5102cf90

**Comment by KoBeWi** [comment]
Uh, then provide some minimal project.

**Comment by volzhs** [comment]
![Screenshot_20200826_074510](https://user-images.githubusercontent.com/8281454/91235240-17cebe80-e770-11ea-9100-f157739b4e99.png)

[node name glitch.zip](https://github.com/godotengine/godot/files/5126641/node.name.glitch.zip)

**Comment by YeldhamDev** [comment]
This is fixed on 4.0, but I guess the fix wasn't cherry-picked.

**Comment by KoBeWi** [comment]
In 4.0 icons still overlap though
![image](https://user-images.githubusercontent.com/2223172/91236933-90feef00-e739-11ea-9f6e-dae7d31edc12.png)
Maybe adding some background for them would make it better.
