### ISSUE TITLE
[Linux] Computer freezes some times when I open a project

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#29044]
**Godot version:**
3.1.1 stable

**OS/device including version:**
MX Linux 18, 64 bits

**Issue description:**
This has been happening to me since I started using godot and godot is the only program that does this.
**Steps to reproduce:**
Open godot, load a project and it'll randomly work or freeze my computer.

**Comment by qarmin** [comment]
Which graphics card and which driver version do you have?

**Comment by MightyPrinny** [comment]
I have an integrated Intel HD Graphics Bay Trail and I'm using the open source drivers.

**Comment by clayjohn** [comment]
Driver version too please.

**Comment by MightyPrinny** [comment]
lspci -k says kernel driver in use: i915

**Comment by akien-mga** [comment]
The driver version would be the version of Mesa that you have installed. You can find it with `glxinfo | grep OpenGL`.

**Comment by MightyPrinny** [comment]
I have Mesa 18.2.6

**Comment by akien-mga** [comment]
This seems to be the same bug as #24783 / https://bugs.freedesktop.org/show_bug.cgi?id=109229 which affected Mesa 18.3 and was fixed in 18.3.3. Reports at that time mentioned that Mesa 18.2.x was not affected, but your issue seems pretty similar so maybe things regressed in later 18.2.x versions.

**Comment by MightyPrinny** [comment]
I can't upgrade to 18.3.3+ from the package manager yet and when I installed it from source it didn't change the version shown by glxinfo so I'm not sure if that would fix it. I'm also using gles2 right know and godot only causes freezes at the moment I open a project, after that everything works fine.

**Comment by MightyPrinny** [comment]
Somehow glxinfo started saying that I have mesa 18.3.6 after I installed 18.2.8 from debian backports, but godot still freezes my computer randomly when I open a project, it also kept freezing right after I installed 18.3.6 when glxinfo was still showing it as 18.2.6.

**Comment by yusdacra** [comment]
I have a Bay Trail iGPU too, using Mesa 19.0.5 and I don't have any problems.

**Comment by MightyPrinny** [comment]
I updated to mesa 19.0.4 and the problem persists. Is there a way I can debug this even though my computer completely freezes?.

**Comment by MightyPrinny** [comment]
@akien-mga  @clayjohn Stepping through the code I was able to find that my computer freezes in Main::Start in the line with `editor_node = memnew(EditorNode);` I was able to step through everything inside memewn but when it returned everything froze.

**Comment by MightyPrinny** [comment]
I stepped through EditorNode::EditorNode(), my computer froze at line 5094 `GLOBAL_DEF("editor/main_run_args", "");` I couldn't step into it.

**Comment by MightyPrinny** [comment]
I don't think this is worth keeping open since it seems to be a hardware specific issue and doesn't happen on windows.

**Comment by MightyPrinny** [comment]
I found the source of the problem, this only happens on UEFI systems running in legacy mode, I never thought something like that would matter.
