### ISSUE TITLE
Selecting material cause that a lot of scripts are loaded

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29226]
**Godot version:**
3.2.dev.custom_build. 86f9d1b

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I try to choose/create new material, then a lot of gd scripts had loaded(Godot must be open with -v flag)
(Open gif in new window)
![file](https://user-images.githubusercontent.com/41945903/58428351-76574980-80a2-11e9-962c-096a0b5fca8f.gif)

**Comment by KoBeWi** [comment]
Any reproduction project? It might be related to some plugin.

**Comment by qarmin** [comment]
Minimal project - https://github.com/qarmin/Sea-of-Ground

**Comment by KoBeWi** [comment]
Reproducible with the project (just add material to any 2D node). Doesn't happen in 3.1.1 stable.

**Comment by KoBeWi** [comment]
Seems fixed in 3.2.4 beta4, but tried in a different project (the MRP is dead).

Can someone confirm?

**Comment by qarmin** [comment]
Still happens with 3.2.4.beta.custom_build. 68013d239
New(old) minimal project - [SeaOfGround.zip](https://github.com/godotengine/godot/files/5718245/SeaOfGround.zip)

**Comment by KoBeWi** [comment]
Can't reproduce again in 4.0 alpha7, tested with the above project.

**Comment by qarmin** [comment]
Also can't reproduce with 3.5 beta
