### ISSUE TITLE
Button text ignores breakline (\n) (fixed in `master`)

### ISSUE THREAD

**Issue by purpleorangegames** [godotengine/godot#2967]
If I set a text with a breakline like "Hello\nthere" and set this text to the Button text and tooltip, the breakline works on the tooltip but is ignored on the text.

**Comment by StraToN** [comment]
I confirm this if the texts are set by GDScript.
But when setting tooltip's text "Hello\nthere" directly in the editor, no breakline appears in the tooltip.

**Comment by purpleorangegames** [comment]
Straton: I really did just tested this on GDScript.
Are saying that when using the Editor neither the text button nor the tooltip breaks the line?

**Comment by StraToN** [comment]
@purpleorangegames Exactly.

**Comment by reduz** [comment]
tooltip should have line break, but button does not. The code in Label should be somehow abstracted to work in other controls.

**Comment by StraToN** [comment]
@reduz ok then we should only focus on having line breaks working for tooltips (using both editor setting out GDscript)

**Comment by purpleorangegames** [comment]
I agree that buttons should not have line breaks unless it's a button for a game.
I have seen plenty of game buttons specially in smartphone games that use linebreaks but it's nothing something major, would be nice to have but I can live without it and use a custom solution.

**Comment by StraToN** [comment]
How should line breaks be managed if they were working in Buttons? I guess the button's height should be updated according to the text, right?

**Comment by purpleorangegames** [comment]
I guess it should, to match the behavior of automatically adjusting the width with the text length.
Although I don't like it very much, I prefer the button to have a fixed size no matter the text, so I can manually adjust it if needed. It is a nice feature if set as optional.
The text is already set as centered and shouldn't change.
What we wouldn't need here is word wrap, as it could cause a lot of confusion and also it should be used in places where you have a lot text being displayed which isn't the case of a button.

Actually, for me the only change necessary would be to the break line code to work.

**Comment by StraToN** [comment]
If nobody resolves this until Tuesday, I'll have a look for fixing this.

**Comment by StraToN** [comment]
Some precisions after further investigations.
As @reduz said, line breaks in Buttons' captions won't work for the moment. I will leave this apart.

Concerning tooltips, there are 2 ways to set them: in the editor, and by GDScript.
- in the editor, line breaks work, but you actually need to effectively break the line in the text editor of the tooltip (see image 1). 
![tooltip_editor_linebreak](https://cloud.githubusercontent.com/assets/1289207/11797001/385a84a8-a2c0-11e5-89bf-0445f505f5c9.gif)

Inserting "\n" will thus print "\n" (image 2)
![tooltip_editor_backslashn](https://cloud.githubusercontent.com/assets/1289207/11797000/38564992-a2c0-11e5-87b0-bcfab48cfc3c.gif)

- By GDScript, the only way is to set the tooltip with:
```python
extends Button

func _ready():
	set_tooltip("Hello\nthere")
	pass
```
So this actually works correctly.

**Comment by akien-mga** [comment]
As #4327 shows, there's also a related issue with ``\t`` not working in Labels (and presumably also in Buttons and Tooltips as debugged here).

**Comment by q00u** [comment]
So is there _still_ no way to have two lines of text on a button?

**Comment by FrancisXIrizarry** [comment]
I have looked into the issue and have a solution to it (Unless someone states otherwise/comes up with a better one). I will be uploading it later tonight/tomorrow (Forking + Pull Request)/(Need to read Documentation). It will do as requested, and can handle both /n and /t. If you want more escape characters added please comment them here. Thanks.

**Comment by asheraryam** [comment]
Proposed solution: https://github.com/godotengine/godot/pull/24048

**Comment by Aaron-Fleisher** [comment]
This can be done with a Button->Label hierarchy 
![](https://i.gyazo.com/74f689fbf41f68c36668a9aec6574b6d.gif)

**Comment by q00u** [comment]
That seems to put text over a button, but doesn't inherit the buttons enabled/disabled behavior. Unless I'm missing something.

It's NOT the same thing as having a line-break on the button itself.

**Comment by FrancisXIrizarry** [comment]
![2018-11-29_02-33-11](https://user-images.githubusercontent.com/24619207/49237895-42d68380-f3cd-11e8-9741-6b2714eaf1d8.gif)
So.. Was it more like this? I was not sure if I understood the problem correctly.

**Comment by Aaron-Fleisher** [comment]
> That seems to put text over a button, but doesn't inherit the buttons enabled/disabled behavior. Unless I'm missing something.
> 
> It's NOT the same thing as having a line-break on the button itself.

Yeah, that's true. Was just showing the power of the UI System (extremely underrated) in Godot.  To achieve the same effect visually

**Comment by cesarpinho** [comment]
#24374

**Comment by MEBonham** [comment]
This thread makes it look like this issue got fixed, but I'm still experiencing it.

**Comment by StraToN** [comment]
@MEBonham PR #24374 could help but is not merged yet (conflicts).

**Comment by Sslaxx** [comment]
Bump. Is this still an issue, can anyone reproduce this with 3.2.2?

**Comment by Calinou** [comment]
@Sslaxx I can still reproduce this in 3.2.2, even when setting the button's text by code.

**Comment by rmasp98** [comment]
Is anyone working on this? It looks like #24374 had the right idea but just never got merged. I am happy to pick this up

**Comment by Calinou** [comment]
@rmasp98 Since there's no open pull request for it, feel free to work on a fix for this :slightly_smiling_face:

**Comment by rmasp98** [comment]
I was wrong. That pull request doesn't fix buttons, which I think is the only thing that is still broken. I guess the solution, is probably in how the button text is rendered. I may need a little help in finding where in the code this happens

**Comment by Waridley** [comment]
I just got this working with `\n`, just need to make sure I'm not missing any corner cases, and will probably try to make sure it works with `\r\n` and other line break character combinations as well before submitting a PR.

**Comment by rmasp98** [comment]
Umm ok... I guess I will chuck the stuff I have been working on away then

**Comment by Waridley** [comment]
@rmasp98 Sorry, didn't mean to step on your toes. I actually just did it for my own use before even checking this thread. And I've **only** implemented it for buttons, no other controls, so if you're still trying to clean up that stale PR for the others, go for it.

**Comment by Waridley** [comment]
Also it's entirely possible your method is better than mine. Wouldn't hurt to see another solution.

**Comment by golddotasksquestions** [comment]
I also need buttons with line breaks. This issue is already 5 years old ...

**Comment by Calinou** [comment]
@golddotasksquestions Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by golddotasksquestions** [comment]
However there is a point to be made that someone requesting this feature _is_ in fact significant new information ;)
Especially if it is requested periodically over the last 5 years. Emojis don't show a timestamp. It's impossible to see if there is still demand for this feature 5 years later if people would use reaction emojis to express their need. They could be all from the first day this issue went public.

**Comment by mudbile** [comment]
I can understand why people would want newlines in buttons, but the more general problem is being able to put _any_ content inside a button (I've never been happy with the icon feature). Honestly, I think this amount of freedom is better expressed using existing controls and passing through/mimicking what features you need for a particular use case, which is why I've never really thought of this as a real problem before. In essence, I think particular "workarounds" offer more expression than any single fix would, at the cost of a little more effort. I'll upload a project that demonstrates a simple script that covers most use cases for me, allowing you to put basically whatever you want inside the MarginContainer: 

[New Game Project.zip](https://github.com/godotengine/godot/files/5611566/New.Game.Project.zip)



![demo](https://user-images.githubusercontent.com/29006839/100530645-41502800-3240-11eb-9fbb-6bd61307505e.gif)

**Comment by me2beats** [comment]
This would be useful!
![multiline text button](https://user-images.githubusercontent.com/16458555/140006689-f85d5c13-760a-4dce-9177-5e02c0ac05a3.JPG)

I decided to split the text into 2 lines because it's too long, but I can't.

**Comment by me2beats** [comment]
Using a Label as a child would be a bit less efficient and would require some extra code and signal connections to make it look consistent with other buttons

![multiline text button1](https://user-images.githubusercontent.com/16458555/140007631-7e732918-875a-4e26-b06b-e7aa76aa0595.JPG)

**Comment by KoBeWi** [comment]
This is fixed on master
![image](https://user-images.githubusercontent.com/2223172/142465034-8905ae32-afe3-4981-9b76-361b3ec0c13c.png)

**Comment by Silver-Golden** [comment]
> This is fixed on master ![image](https://user-images.githubusercontent.com/2223172/142465034-8905ae32-afe3-4981-9b76-361b3ec0c13c.png)

I know that you closed out the issue but this is still broken on 3.4.3 Mono.  
The textbox in the editor does not allow multiline in buttons nor using \n in C#.

**Comment by kdiduk** [comment]
If no one has started working on it yet, I can take care of fixing this issue in 3.5 :slightly_smiling_face:

**Comment by akien-mga** [comment]
Fixed by #41464.
