### ISSUE TITLE
Shaders modified on disk don't get reloaded

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#29687]
Godot 3.1.1
Windows 10 64 bits

My project contains a shader which I edited in Godot with some test code.
Later on, while I removed that code from an external text editor. However, Godot still saves that shader with the extra test code.

This is similar to this fixed issue https://github.com/godotengine/godot/issues/19852

Project:
[ShaderNotReloading.zip](https://github.com/godotengine/godot/files/3277863/ShaderNotReloading.zip)

Reproduction case 1:

1) Open main.tscn
2) Double-click on `test.shader` to see it in the shader editor. Notice it has a comment in it.
3) Remove the comment from an external text editor and save it
4) Go back to Godot: notice the comment is still there.

Reproduction case 2:

1) Open main.tscn
2) Double-click on `test.shader` to see it in the shader editor. Notice it has a comment in it.
3) Click on the root node, which makes the shader editor close (however, I suspect it still holds a reference to the edited shader. Not necessarily a bad idea, but the resource should still be able to reload!)
4) Remove the comment from an external text editor and save it
5) Go back to Godot and edit the shader: notice the comment is still there.

**Comment by Paulb23** [comment]
This should be fixed by #22863

**Comment by akien-mga** [comment]
Fixed by #22863.

**Comment by hmans** [comment]
I'm seeing the same erroneous behavior in 3.2.2b4, both in my own project as well as the test project supplied above. (Tested both reproduction cases.)

BTW, I wasn't sure if I was supposed to just add a comment to this issue (closed in June 2019) or create a new issue to report the regression. I couldn't find anything in the issue template about reporting regressions. Please let me know if I should open a new issue instead.

**Comment by KoBeWi** [comment]
This should've been fixed by #45903, but apparently it's still valid in 9b637fa

**Comment by KoBeWi** [comment]
Still valid in daec6e6
It works fine with external shader, but built-in shaders aren't reloaded.

**Comment by hmans** [comment]
Just a quick heads-up that this is still happening in the release version of 4.0 (at least on macOS — haven't tried the other operating systems yet.)

**Comment by KoBeWi** [comment]
Fixed in 4.4.
