### ISSUE TITLE
Integrated graphics cause weird glitches in GLES3 (3D grid disappearing depending on the angle and meshes turning black)

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot#30330]
Godot 3.1.1

Windows 10 64-bit with Intel 620HD/AMD 430m

When dealing with meshes, the grid randomly disappears and meshes start turning black and back to normal again on random angles and positions. 

Only occurs with dedicated graphics. I used Intel 620HD by default; switching to dedicated fixed the issue.

**Comment by clayjohn** [comment]
Could you upload an MRP or steps to reproduce so other users can try to reproduce this issue?

**Comment by Altair1234** [comment]
Base 3d node->RigidBody->MeshInstance

In the mesh instance, change the mesh to anything (I used Box Shape). This makes the grid disappear.

As for the meshes going black, I imported a gltf file into the scene and that made the other meshes and itself randomly go black at positions or when they were viewed from different angles. At one time, I had two Box Rigid bodies and a gltf file. If one particular box came into the viewport (let's call it BoxA), the gltf body would go black and the grid would disappear. Interestingly enough, once the mesh went black and then BoxA was removed from the viewport (not by changing its own position but by viewing the scene from a different angle), the grid would appear again after it went away the first time. Then I restarted the program and now zooming or viewing the scene from different angles would make Box B go black. 

Finally, when playing the scene, when BoxA or the gltf was moved to certain places, either or both would go black. Changing the position of BoxA in the editor made it really random, earlier it went back only when it was moved to a certain part of the scene when playing through the scene.

**Comment by Zireael07** [comment]
I believe meshes going black on Intel integrated cards was already reported?

**Comment by Anutrix** [comment]
@Altair1234 I'll  start guessing now. You have at least one object(like mesh instance) without a material. You are using GLES3.
Trying adding a material to objects with them. Or try GLES2.
Either option I think will fix your issue.
I have the same issue on OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 620 combination.

**Comment by Altair1234** [comment]
>  You have at least one object(like mesh instance) without a material.
Yep. I just switched to dedicated graphics. Dunno why it didn't automatically.

**Comment by CT-noise** [comment]
Hope this is fixed soon. It's impossible for me to use Godot with OpenGL 3.0 while this isn't fixed.

**Comment by clayjohn** [comment]
@CT-noise If you can provide an MRP or do some testing on your own you greatly increase the chances this will get fixed. As it is, the information above isn't enough for other users to reproduce and thus debug. Most issues like this just die in the issues list as a result.

**Comment by Anutrix** [comment]
@CT-noise Upload a minium project that shows your issue.

**Comment by maesi321** [comment]
I have the same/similar issue

I can confirm:
1. the problem exists only on integrated graphics (UHD Graphics 620), on dedicated (GeForce GTX 980) everything works as expected
2. assigning a material fixes the problem (like @Anutrix suggested)
3. the issue exists on the current release (3.2.1)
4. the issue exists with GLES3, GLES2 works fine


description (only integrated graphics & GLES3)(the issue exist without the GridMap aswell)
In a 3D-Scene GridMap is not always displayed when WorldEnvironment/BackgroundMode is on "Clear Color".
It seems it can display the GridMap or Meshinstances (without material) but not both at the same time.
Camera-Symbol and Editor-Grids also disappear.
When the WorldEnvironment/BackgroundMode is on "Canvas" both are displayed. Same when a Light is active in the scene.
When using GLES2 there is no problem at all.

![a](https://user-images.githubusercontent.com/63539289/79066191-31d29d80-7cb6-11ea-9507-262562a12b86.jpg)
light off and WorldEnvironment Background "clear color"

![b](https://user-images.githubusercontent.com/63539289/79066195-4dd63f00-7cb6-11ea-9b1c-f8998f8459ed.jpg)
light off and WorldEnvironment Background "canvas"

![c](https://user-images.githubusercontent.com/63539289/79066203-634b6900-7cb6-11ea-8746-49889ff3136d.jpg)
light on and WorldEnvironment Background "clear color"


Workaround:
1. WorldEnvironment BackgroundMode "canvas"
2. Light in scene active
3. using GLES2
4. when Meshinstance has a Material

reproduce:
(integrated graphics & GLES3)
-Node
--WorldEnvironment (Backgroundmode "clear colou")
--DirectionalLight(off)
--MeshInstance (without Material)

change visibility of MeshInstance
add Material to MeshInstance
add Light to scene
move viewport around (MeshInstance not visible)

[test.zip](https://github.com/godotengine/godot/files/4466153/test.zip)

**Comment by Animatical** [comment]
@maesi321 That fixes the disappearing grid for me, but not the transform arrows. Am I missing something, or is this just not able to be worked around?

**Comment by maesi321** [comment]
@Animatical honestly, I'm not the best one to ask (still a godot-beginner)
The best workaround was for me to add a Shader-Material or to change to GLES2.
Make sure everything in the viewport has a Material...

**Comment by clayjohn** [comment]
I recently bought a laptop with intel 620 graphics and can confirm this issue!

Now that I can reproduce, I can try to fix it. My guess is that some memory is not initialized properly.

**Comment by Animatical** [comment]
is this place dead?

**Comment by Calinou** [comment]
@Animatical No (see the rest of this issue tracker). It's just that people can become busy with life sometimes :slightly_smiling_face:

**Comment by gamepad-coder** [comment]
Here are a few more details in case it helps narrow down the cause.

**PC Information :**

Godot 3.2.2.stable
Laptop with no dedicated GPU.
Processor : Intel Core i7-7600U CPU
Integrated Graphics : Intel HD Graphics 620

No problem at all on my machine when using Godot with GLES2.

All of the following describe a default environment with GLES3 enabled.



**Scene's Node Tree Setup :**

Spatial
-> Mesh Instance (with basic Cube, no Material)
-> OmniLight
-> Camera

<hr> 

### Glitch Related to Mouse Interaction :

Hovering over certain elements seems to cause a refresh where the 3D Viewport's grid either appears or disappears, but usually(?) causes the grid to disappear. 

Elements that seem to trigger the grid toggling 
(Not comprehensive)

- 3D Transform Widgets (mouse hover) or (click)
- Objects in the scene (click)
- the resize "<->" arrow between Docks (mouse hover) or (mouse drag)
- fields in the Inspector (mouse hover) or (click)

### Screencap 1, various UI -> triggering glitch :

I only click five times in the following screen capture: 
- I click to select the node named "Cube" in the Scene dock
- I click to turn "Cast Shadow" off
- I  middle click to change the Viewport
- I click to toggle the visibility of the Light node
- I click to drag the transform gizmo.

Everything else is just by mouse hover:

![github godot 30330 upload1 reducedSize_reducedDuplicates_trimmedQuarter](https://user-images.githubusercontent.com/65138515/90990448-1da58380-e567-11ea-94a8-a14a84a1cd9a.gif)

<hr> 

### Glitch Related to Lightsource :

When the Light node has its visibility toggled off via the Scene's node tree, the grid is permanently invisible.

### Glitch Related to MeshInstance's "Cast Shadow" :

Details on initial setup:
- I added a MeshInstance to the scene.
- I added a "New Cubemesh" via the Mesh field in the Inspector.
- I added no Material.

When MeshInstance -> Geometry -> Cast Shadow is On (default)
the glitch is present.

When MeshInstance -> Geometry -> Cast Shadow is set to "Off"
this glitch does not appear and Godot functions normally.

Similarly, if the MeshInstance has its visibility toggled off on the Scene Tree (& all other nodes still visible) the glitch does not occur.

If there are multiple MeshInstance nodes, no glitch if all of them have ..->Cast Shadow set to "Off", or if they all have their visibility toggled off via the Scene dock.

### Screencap 2, demonstration of these lighting settings :


![github godot 30330 upload2 reducedSize_reducedDuplicates](https://user-images.githubusercontent.com/65138515/90990950-0d8fa300-e56b-11ea-902c-c57c6ecb41b3.gif)




<hr>

Hope this is useful.

Infinite thanks to everyone who contributes to Godot.
This engine is my favorite software in the world.


Have a wonderful day.

**Comment by PL3B3** [comment]
I'm having a similar issue. I'm using a gridmap, and if I get too far away from my tiles, all the meshes are rendered black.

Specs:
Intel i7-6700
Intel HD 530 integrated graphics

My Project is here:
[Pumlet3DClient.zip](https://github.com/godotengine/godot/files/5212192/Pumlet3DClient.zip)

And here's a video:
![distanceglitch](https://user-images.githubusercontent.com/19691468/92987482-552d8e80-f488-11ea-859e-6da167fc4ad1.gif)

**Comment by Animatical** [comment]
no info in about 2 months?

**Comment by Calinou** [comment]
@Animatical We don't know exactly what's causing this issue.

**Comment by Animatical** [comment]
@Calinou It's just that I'm not sure if anyone is still trying to figure it out, or if it's just forgotten. I'd love to use Godot, but when it seems like no one is trying to fix a problem, it can be pretty demotivating.

**Comment by Animatical** [comment]
@Calinou at least we can rule out outdated drivers, because I've updated them like 5 times today lol

**Comment by Arnklit** [comment]
Strange I've been having similar issues on my Dell laptop with UHD620 graphics. I realised that the "newest" driver Dell was giving me was a year and a half old. When I finally went on Intel's homepage and downloaded their latest beta driver from a few weeks ago and force installed that my issues disappeared.

**Comment by Animatical** [comment]
Which beta drivers?

**Comment by Arnklit** [comment]
This one https://downloadcenter.intel.com/download/29950/Intel-Graphics-BETA-Windows-10-DCH-Drivers?product=126789

Be aware I had to download the .zip file, unzip it and tell windows to update the display driver looking in that folder as trying to install the driver with the exe it refused with a message about how I should get the driver from my vendor instead.

**Comment by Animatical** [comment]
Just tried it, doesn't work for me, but this is a good start.

**Comment by Anutrix** [comment]
Maybe we should list out Integrated GPUs that still have or if they fixed so we can better track this issue.

**Comment by Animatical** [comment]
^ I have 620, tried that beta driver and it didn't work. Maybe it's like a 50/50 chance of it working?

**Comment by Arnklit** [comment]
Bad news from my side as well. I'm still seeing issues again as well. For me it only seems to happen when a mesh is in the scene that has no material assigned, so it's pretty easy for me to work around now that I realise that. I just assign a new Spatial Material.

**Comment by kreaninw** [comment]
In Godot v3.2.4-beta2, this issue is not occurring to me anymore, as shown [here](https://photos.app.goo.gl/7DmSncirJGn79NeL7) (comparing between Godot v3.2.3-stable, in which this issue is occurring, and Godot v3.2.4-beta2).

**My device:**
- Windows 10 (64-bit) version (build) 2009 (10.0.19042).
- Intel® UHD Graphics 620 driver version 27.20.100.8935.

**Comment by Calinou** [comment]
Did the new GLES3/GLES2 batching accidentally fix this? :thinking:

**Comment by clayjohn** [comment]
@Calinou it's possible that the issue came from certain memory being overwritten by the editor. In that case batching could very well have fixed it!

**Comment by maesi321** [comment]
I can confirm what kreaninw postet
UHD Graphics 620 / Win10
Godot v3.2.3-stable --> issue exists
Godot v3.2.4-beta2 --> issue gone

**Comment by kreaninw** [comment]
> @kreaninw @maesi321 Out of curiosity, is the issue still gone if you disable batching for the editor in the Project Settings?

This issue doesn't appear to me even after disabled the batching, as shown [here](https://photos.app.goo.gl/33wauqauaxqz28jY7).

**Comment by Calinou** [comment]
Thanks for checking :slightly_smiling_face: Closing as resolved in 3.2.4beta2 then.

**Comment by gamepad-coder** [comment]
Also confirming, the issue is resolved for me!
Windows 10 / Intel HD Graphics 620 (slightly different from UHD 620)
Godot_v3.2.3-stable_win64 --> issue exists
Godot_v3.2.4-beta3_win64 --> issue resolved

**Comment by return2monki** [comment]
https://github.com/godotengine/godot/issues/25512#issuecomment-1204544117

This issue still exists, described everything there. [Good thing it's still mentioned in Godot docs @ troubleshooting](https://docs.godotengine.org/en/stable/about/troubleshooting.html#the-grid-disappears-and-meshes-turn-black-when-i-rotate-the-3d-camera-in-the-editor)

It's not as serious of an issue as it looks because directional light or gles2 fixes it as far as I've seen but still.
