### ISSUE TITLE
Interrupting the initial search in the AssetLib causes errors

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#30642]
**Godot version:**
 22c843b

**Issue description:**
Pressing enter while having the search bar focused in the initial search for assets will cause the AssetLib to show no assets. Outputting this error:
`editor/plugins/asset_library_editor_plugin.cpp:1206 - Condition ' !category_map.has(r["category_id"]) ' is true.`

Switching out and back to the AssetLib will fix this.

**Comment by KoBeWi** [comment]
Still valid in 3.2.3

**Comment by theraot** [comment]
Is this still valid?

**Comment by YeldhamDev** [comment]
@KoBeWi Can't either, seems fixed in both stable and master. Closing.

**Comment by clifftor** [comment]
I can still see this error in Godot version `v3.4.stable.official [206ba70f4]`

To reproduce: search something before the default search result loads.

**Comment by theraot** [comment]
I can confirm too. On Godot 3.4 (64 bits). However, it appears to be fixed on 3.4.1 rc 2 (64 bits).

**Comment by Calinou** [comment]
This was already reported in https://github.com/godotengine/godot/issues/53996 – please continue the discussion there.
