### ISSUE TITLE
[Bullet] Problems with physics in 3D when using the units as intended

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#30742]
**Godot version:**
3.1 stable

**OS/device including version:**
GNU/Linux

**Issue description:**
Working at the scale Godot is expecting for 3D models, which is 1 unit = 1 meter, causes problems with physics, specially with Godot Physics, I'd like to avoid bullet because Godot Physics feels more precise, however it starts working well when my character is 4 meters tall, I was previously using a 1 meter tall character and also tried making it 2 meters tall but the physics weren't precise enough for me.
Working with bigger numbers seems ok(I hope this is the case), but then other parts of the editor cause problems, the automatic texture size for baked lightmaps are too big(I couldn't even see the progress bar move when I tried to bake a lightmap for a low poly level scene), the camera's default values are very off and probably other things have bad default values too which is a bit annoying, and I can only hope there aren't any performance issues for whatever reason.

I think there should be a way of making physics more precise while working with models that use the intended scale or maybe there could be settings to change the scale of the units so we can make 1 unit = 0.5 meters on a project if we want.

Update:

The problem I was having was mostly because of a generated trimesh collision shape, however there's still a less important precision problem that causes objects to move a bit into the ground when they move, here's a project with the code I'm using,  in this case the camera moves with the player so it's easier to notice, this only works with Godot Physics and this is why I think it's more precise than bullet, in bullet the objects slide down slopes event though I'm using move_and_collide which makes them climb slopes slowly and go down slopes very fast.
[3DKinematicTest.zip](https://github.com/godotengine/godot/files/3419915/3DKinematicTest.zip)

**Comment by aaronfranke** [comment]
Can you provide a minimal reproduction project and point out what to look for?

**Comment by MightyPrinny** [comment]
I was making a test scene and found out that the generated trimesh collision for the map was the cause of most problems, now the character only looks like it moves a bit into the ground while it's moving due to my ground snapping code

**Comment by eon-s** [comment]
Check if the problem appears on master (compile or get a daily build), some issues with trimesh and disabled shapes were solved already.

**Comment by Calinou** [comment]
@MightyPrinny Can you still reproduce this on [3.2 beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-4)?

**Comment by MightyPrinny** [comment]
I think godot physics works well enough, but bullet is still weird.

**Comment by KoBeWi** [comment]
Looks still valid in 3.2.4 beta2

**Comment by aaronfranke** [comment]
@MightyPrinny Have you tried decreasing the margin value?

**Comment by akien-mga** [comment]
No answer, and I don't really understand what the bug was from the way it's described. I tried the MRP and didn't really understand what was supposed to be the issue.
