### ISSUE TITLE
Battery Notification

### ISSUE THREAD

**Issue by avarisclari** [godotengine/godot#314]
Is there any form of battery monitor built in? If not, how much work would it be to add such a feature. I know it's not a major feature, but still nice to be able to say in an application "Your battery is low, please save and quit, or find the nearest power source."

**Comment by StraToN** [comment]
WINDOWS AND OSX TESTERS NEEDED PLEASE ! SEE LIST BELOW.
This feature is currently in development on this fork branch : https://github.com/StraToN/godot/tree/314-battery-notification
Current status:
* X11 : done, tested
* OSX : done, **not tested**
* IOS (iphone) : not done, WIP
* Windows : done, **not tested**
* WinRT : not done, will have to wait for experienced WinRT dev...
* Android : partially done, the platform-specific code is ready but I don't know where to put it, so it's commented out atm (https://github.com/StraToN/godot/blob/314-battery-notification/platform/android/power_android.cpp#L38)
* bb10 : not done
* Haiku : not done
* isim : not done
* javascript : not done (is that a platform?? :s )
* server : not done (is that a platform?? what is the difference between this and X11??)

**Comment by Calinou** [comment]
> server : not done (is that a platform?? what is the difference between this and X11??)

Technically, yes. `server` is designed for running on headless GNU/Linux (and BSD) operating systems, without requiring any X11 dependency. It can also be faster in many cases. That makes it suitable for dedicated game servers, running scripts like asset conversion…

**Comment by punto-** [comment]
"javascript" is html5, I don't know if there's apis to expose the battery
status to a website

**Comment by SuperUserNameMan** [comment]
@punto-  : there is a new javascript Battery Status Web API, but it is still a W3C Proposed Recommendation. It is mainly available on Firefox and Chrome (on Android and PC)

https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API
https://w3c.github.io/battery/

**Comment by StraToN** [comment]
@Calinou OK, so ```server``` would actually work the exact same way as X11. I suppose that, of course a server should never run on battery, but hey, people mind their own business ;)

@punto- @SuperUserNameMan I guess we should then simply wait for this one. Keeping it warm.

**Comment by vnen** [comment]
I'll test this for Windows.

**Comment by vnen** [comment]
@StraToN first, there's an error on [line 13 of the SCsub file for Windows](https://github.com/StraToN/godot/blob/9d4c1892e3a05d34ee82fa09e80f230d6f3dc2d2/platform/windows/SCsub#L13). It is now `'power_windows.cpp",` when it should be `"power_windows.cpp"` (without comma at the end).

Even after this fix I can't compile though. Got a bunch of errors:

```
c:\users\george\workspace\godot\godot-src\platform\windows\os_windows.h(133) : e
rror C2143: syntax error : missing ';' before '*'
c:\users\george\workspace\godot\godot-src\platform\windows\os_windows.h(133) : e
rror C2143: syntax error : missing ';' before '*'
c:\users\george\workspace\godot\godot-src\platform\windows\os_windows.h(133) : e
rror C4430: missing type specifier - int assumed. Note: C++ does not support def
ault-intc:\users\george\workspace\godot\godot-src\platform\windows\os_windows.h(
133) : error C4430: missing type specifier - int assumed. Note: C++ does not sup
port default-int

platform\windows\power_windows.cpp(34) : error C2065: 'SYSTEM_POWER_STATUS' : un
declared identifier
platform\windows\power_windows.cpp(34) : error C2146: syntax error : missing ';'
 before identifier 'status'
platform\windows\power_windows.cpp(34) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(35) : error C2065: 'FALSE' : undeclared ident
ifier
platform\windows\power_windows.cpp(38) : error C2065: 'status' : undeclared iden
tifier
scons: *** [platform\windows\godot_win.windows.opt.tools.32.obj] Error 2
platform\windows\power_windows.cpp(38) : error C3861: 'GetSystemPowerStatus': id
entifier not found
platform\windows\power_windows.cpp(42) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(42) : error C2228: left of '.BatteryFlag' mus
t have class/struct/union
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xlocale(337) : wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled. S
pecify /EHsc
        type is 'unknown-type'
platform\windows\power_windows.cpp(44) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(44) : error C2228: left of '.BatteryFlag' mus
t have class/struct/union
        type is 'unknown-type'
platform\windows\power_windows.cpp(45) : error C2100: illegal indirection
platform\windows\power_windows.cpp(46) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(46) : error C2228: left of '.BatteryFlag' mus
t have class/struct/union
        type is 'unknown-type'
platform\windows\power_windows.cpp(47) : error C2100: illegal indirection
platform\windows\power_windows.cpp(48) : error C2065: 'TRUE' : undeclared identi
fier
platform\windows\power_windows.cpp(49) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(49) : error C2228: left of '.ACLineStatus' mu
st have class/struct/union
        type is 'unknown-type'
platform\windows\power_windows.cpp(50) : error C2100: illegal indirection
platform\windows\power_windows.cpp(51) : error C2065: 'TRUE' : undeclared identi
fier
platform\windows\power_windows.cpp(53) : error C2100: illegal indirection
platform\windows\power_windows.cpp(54) : error C2065: 'TRUE' : undeclared identi
fier
platform\windows\power_windows.cpp(60) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(60) : error C2228: left of '.BatteryLifePerce
nt' must have class/struct/union
        type is 'unknown-type'
platform\windows\power_windows.cpp(61) : error C2065: 'status' : undeclared iden
tifier
platform\windows\power_windows.cpp(61) : error C2228: left of '.BatteryLifeTime'
 must have class/struct/union
        type is 'unknown-type'
platform\windows\power_windows.cpp(71) : error C2065: 'TRUE' : undeclared identi
fier
scons: *** [platform\windows\power_windows.windows.opt.tools.32.obj] Error 2
c:\users\george\workspace\godot\godot-src\platform\windows\os_windows.h(133) : e
rror C2143: syntax error : missing ';' before '*'
c:\users\george\workspace\godot\godot-src\platform\windows\os_windows.h(133) : e
rror C4430: missing type specifier - int assumed. Note: C++ does not support def
ault-int
scons: *** [platform\windows\joystick.windows.opt.tools.32.obj] Error 2
platform\windows\os_windows.cpp(989) : error C2065: 'power_manager' : undeclared
 identifier
platform\windows\os_windows.cpp(989) : error C2061: syntax error : identifier 'P
owerWindows'
scons: *** [platform\windows\os_windows.windows.opt.tools.32.obj] Error 2
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Tested on X11, it seems to work fine. Like @StraToN reported, I also get -1 for ``get_power_seconds_left``, I'll see if I have more luck with the SDL API directly and/or if they have a bug report about it.

With the cable plugged in and the battery fully charged, I got POWERSTATE_UNKNOWN instead of POWERSTATE_CHARGED. I'm now charging it fully again to see if I can reproduce it.

Also the enums in the help are sorted alphabetically instead of by value, it would be nice to fix that.

**Comment by StraToN** [comment]
@vnen Thanks a lot for your tests ! There was a missing include (I forgot windows.h). This is corrected now, please pull and try again. 

@akien-mga You just need to compile libsdl and run make in src/tests. There lies a test program for power management testing.

**Comment by vnen** [comment]
@StraToN still missing the `platform/windows/SCsub` correction. Other than that it seems to be working perfectly. Unfortunately, my Windows laptop is not showing the remaining battery time (only percentage), so I can't tell if `OS.get_power_seconds_left()` is working as intended (I'm always getting -1, since the OS is not calculating it).

As a note, it shows the power state as `NO_BATTERY` on my desktop, which I guess is intended behavior.

**Comment by StraToN** [comment]
@vnen Ah, I see the error now. My eyes were closing yesterday, I didn't see it. I'll correct this ASAP.

Concerning get_power_seconds_left(), I invite you to compile SDL as well as demo programs it features, to see if it succeeds.

Other than than, no PR until most platorms are tested and compile. We can't merge code thats breaks Godot. Looking at OSX users here in particular 😊

**Comment by StraToN** [comment]
ping
Still needing OSX testers.

**Comment by vnen** [comment]
@trollworkout uses OSX, I believe.

**Comment by reduz** [comment]
ah I have a mac now, i could test..

**Comment by trollworkout** [comment]
I got OSX. I'm looking above see how I can test this.

**Comment by akien-mga** [comment]
@StraToN I'd suggest your cleanup your branch (merge some of the commits together, 16 commits is too much for this feature), rebase on top of master HEAD and make a pull request. Right now your work is kind of hidden, and forgotten.

**Comment by bojidar-bg** [comment]
Was the PR merged in the end?

**Comment by trollworkout** [comment]
I never ended up checking this :D

**Comment by vnen** [comment]
@bojidar-bg no, still open: #5871

**Comment by wt** [comment]
The last comment on #5871 seems to indicate that it was merged. Maybe this one can be closed?

**Comment by akien-mga** [comment]
It still needs to be implemented on various platforms. @StraToN, I leave it up to you to either update this issue with the current implementation status, or maybe close it and open a new one for that, as it might be clearer.

**Comment by StraToN** [comment]
@akien-mga I'll create a new issue with the current implementation status & what's missing. That's cleaner this way ;)
