### ISSUE TITLE
Basis.get_euler() can return pitch outside of [-π/2, π/2] range

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#31417]
**Godot version:**
v3.2.dev.custom_build.188a10df8 de8ce3e

**OS/device including version:**
Linux Mint 19.2 x86_64

**Issue description:**
Euler angles are supposed to be returned in the [-π, π] range for yaw and roll, and [-π/2, π/2] range for pitch.
However, when yaw and roll are both zero, pitch is returned in the [-π, π] range.

**Steps to reproduce:**
* Write a script that can rotate an object.
* Print the angles returned by basis.get_euler()

**Minimal reproduction project:**
[EulerTest.zip](https://github.com/godotengine/godot/files/3510055/EulerTest.zip)
This project contains two Aircraft nodes, which are identical except for their overall orientation, and their script which print either "Aircraft 1" or "Aircraft 2".
You can rotate both planes with the arrow keys and page up/down keys, and you can reset them by pressing R.
If you pitch up or down, you will notice that pitch values will differ when passing π/2 (90°). Any amount of rotation along roll and yaw will make the incorrect pitch value jump to the correct value.

Aircraft 2 is for demonstration purposes, it is rotated such that its axes follow the XYZ convention the get_euler() function is based upon: X forward, Y to the right, Z down. When rotated back to the same orientation as Aicraft 1, pitch is returned in the expected range. This might be related to the rotation not being exactly 90°, though.

 The pitch issue might come from the rotation back to Godot orientation of Y up.

**Comment by aaronfranke** [comment]
Relevant code: https://github.com/godotengine/godot/blob/master/core/math/basis.cpp#L511

It seems that the code currently checks if the rotation can be represented purely with X, and if so, uses atan2 (which returns -π to π). I don't know why this check exists in the first place, maybe the `get_euler_xyz` code was written first, and `get_euler_yxz` is just following the example of that?

If anything, this should *also* check if it can be a pure Y rotation, since Godot is Y-is-up and such rotations are common. It would need to check if `x.y`, `y.x`, `y.z`, and `z.y` are zero.

Pinging @tagcup since the git blame points to his commits.

**Comment by KoBeWi** [comment]
Not sure how to interpret the printed values, but it seems fixed in [Godot 3.2.3 rc6](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6).

@Cykyrios Can you confirm?

**Comment by Cykyrios** [comment]
I just pulled the latest 3.2 commit , and the issue is still there. Do note though that this is an edge, as it only appears when you rotate around the X axis only while other rotations are exactly zero, the slightest rotation about the Y or Z axes changes the wrong value back to its intended range.
The printed values are the Euler angles of the nodes, and when pitching up or down, the X value should never go over PI/2 (or below -PI/2).
In my MRP, the second aircraft is rotated in its scene, and rotated back in the main scene, which makes it print the correct values.

**Comment by Cykyrios** [comment]
For what it's worth, I downloaded the MRP and converted it to Godot 4, and could not reproduce the issue (although the "planes" themselves got half-broken as the capsules got rotated 90 degrees), so I will close this.
I have not tested again in a more recent Godot 3 version.
