### ISSUE TITLE
Vector3::angle_to() does not return a signed angle

### ISSUE THREAD

**Issue by Cheeseness** [godotengine/godot#31519]
**Godot version:**
3.1.1

**OS/device including version:**
Fedora 29

**Issue description:**
Unlike Vector2.angle_to(), the current implementation of Vector3.angle_to() always returns a positive value regardless of which direction the resulting angle is meant to indicate.

**Steps to reproduce:**
Execute the following gdscript and note that both statements return the same value (positive pi/2):
```
    print(Vector3(-1, 0, 0).angle_to(Vector3.FORWARD))
    print(Vector3(1, 0, 0).angle_to(Vector3.FORWARD))
```

For comparison, the following two statements return different values (positive pi/2 and -pi/2):
```
    print(Vector2(-1, 0).angle_to(Vector2.UP))
    print(Vector2(1, 0).angle_to(Vector2.UP))
```

**Comment by akien-mga** [comment]
I'm not sure this is a bug, nor that it can be fixed. I did some research on the topic and the formula we use it:
```cpp
real_t Vector3::angle_to(const Vector3 &p_b) const {
        return Math::atan2(cross(p_b).length(), dot(p_b));
}
```

See https://stackoverflow.com/a/10145056
What we'd need to get the signed angle would be the "signed norm" `|a x b|`, i.e. `|a|*|b|*sin(theta)`, but that's not what `Vector3::length()` gives us, since it's the absolute norm.

One could probably try to find out the sign after getting the absolute angle by doing some extra computation, but we'd still have to define what is the reference place for the signedness.

**Comment by lawnjelly** [comment]
The direction of the cross product may be of interest, this flips at 180 degrees, and may be the equivalent of what happens in the 2d version with the sign. But agree with Akien, I think you need some kind of frame of reference for the chirality.

**Comment by Zylann** [comment]
Shouldn't `(a - b).angle()` provide that signed angle?

**Comment by akien-mga** [comment]
> Isn't `(a - b).angle()` providing that signed angle?

That method doesn't seem to exist for `Vector3`.

**Comment by Anutrix** [comment]
Also, is there a reason why the function angle_to(), for **Vector3** is defined in **vector3.h** and not vector3.cpp but for **Vector2** it is defined in **vector2.cpp** and not vector2.h. Shouldn't it be consistent?
Also, just a reminder: slerp() has a normalization check for Vector2 but not for Vector3.

**Comment by Zylann** [comment]
> Also, is there a reason why the function angle_to(), for Vector3 is defined in vector3.h and not vector3.cpp but for Vector2 it is defined in vector2.cpp and not vector2.h.

For this kind of things it's usually decided by if the method should be inlined or not, it doesnt have a relation to "in Vector2 it's that way so Vector3 should". Different dimension, different problem. (or could as well just be random).

**Comment by lawnjelly** [comment]
> Also, is there a reason why the function angle_to(), for **Vector3** is defined in **vector3.h** and not vector3.cpp but for **Vector2** it is defined in **vector2.cpp** and not vector2.h. Shouldn't it be consistent?

Agree with Zylann, inlining is a key factor for me (although with whole program optimization modern compilers can inline from cpp, it makes it nice and easy for them if the function definition is in the header). Also whether the function itself calls functions which would require including more headers to the .h file, which can slow down compilation.

Large functions also tend to be more candidates for going in the cpp, because the relative cost of the function call versus the code within will be relatively small. And the compiler would probably choose not to inline them anyway.

Of course also every time you edit a function in a header file all the dependencies need to recompile, so iteration time can be slower.

**Comment by kakoeimon** [comment]
This is not a bug.
Vector3::angle_to will "Returns the minimum angle to the given vector." (from the docs)
This can be used to know if an object is facing another object and etc.
It is not for getting an angle to rotate an object.
In 3d we have 3 axis of rotation (pitch, yaw, roll). So even if this function was returning a signed value it will had turned useless as we do not know the axis. You may say that your objects are using only one of the rotation axis and by this you know witch one you want to rotate but if this is true, you can just use 2d math to find the angle.

**Comment by bojidar-bg** [comment]
It is possible to make a `signed_angle_to(other, up = Vector3.UP)` function, which calls `angle_to`, and then flips the sign if `this.cross(other).dot(UP) < 0`.

**Comment by lawnjelly** [comment]
> It is possible to make a `signed_angle_to(other, up = Vector3.UP)` function, which calls `angle_to`, and then flips the sign if `this.cross(other).dot(up) < 0`.

Or simply have a function that returns axis angle between the two vectors (if there isn't one already), as this is generally a useful function anyway. That way the calling code can do a cheaper check according to which 'up' vector is being used (just test the sign of e.g. y in the axis rather than dot product).

**Comment by aaronfranke** [comment]
@Zylann On the topic of inlining, it seems strange that the smaller functions (for Vector2) are in the cpp, while the larger functions (for Vector3) are in the header.

> @lawnjelly Or simply have a function that returns axis angle between the two vectors

Returning an axis-angle would be tricky without [Vector4](https://github.com/godotengine/godot/issues/20907). It could be done in C# via out parameters.

**Comment by Zylann** [comment]
> Returning an axis-angle would be tricky without Vector4. It could be done in C# via out parameters.

@aaronfranke isn't this a Quaternion?

**Comment by olivierdalang** [comment]
> It is possible to make a signed_angle_to(other, up = Vector3.UP) function, which calls angle_to, and then flips the sign if this.cross(other).dot(up) < 0.

As a reference, unity3D has `static Vector3.SignedAngle(Vector3 from, Vector3 to, Vector3 axis)`. Indeed quite useful (e.g. to sort vertices clockwise). Worth adding to Godot IMO !

**Comment by JestemStefan** [comment]
Hi! I had similar issue with my recent project and that's how I ended up here.

I added signed_angle_to() function for Vector3.

The sign is based on the direction of the axis pointing out of the plane created by angles. In  edge case where axis is aligned with the plane it returns positive sign.

It's my first contribution to the source code, so I will be glad to hear your feedback.

**Comment by akien-mga** [comment]
Fixed by #45807 adding `Vector3.signed_angle_to()`.

**Comment by Oyusi** [comment]
In version 3.3.2.stable the added method does not exist, as far as I can tell. It seems to only have been added to the 4.x master branch. Can it be added to 3.x? Otherwise this issue is still present there.

**Comment by JestemStefan** [comment]
@Oyusi Sorry I missed your comment. I had notifications turned on. I made a PR for 3.x version. Hopefully it will be cherry-picked into 3.4 🚀
