### ISSUE TITLE
Cannot load Ogg Vorbis with Cover Image

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#32145]
**Godot version:**
3.2 Mono
(Mono should not affect this)

**OS/device including version:**
Ubuntu 18.04, Kernal 5.0.0-27

**Issue description:**
Godot will fail to load an ogg file if it contains a cover image

What it looks like in VLC Media Player (for context)
![image](https://user-images.githubusercontent.com/14253836/64916408-09e08300-d743-11e9-9b8f-10945fa0fc1d.png)

```
ERROR: bind: Method/Function Failed, returning: ERR_UNAVAILABLE
   At: drivers/unix/net_socket_posix.cpp:367.
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:196.
ERROR: import: Condition ' !ogg_stream->get_data().size() ' is true. returned: ERR_FILE_CORRUPT
   At: modules/stb_vorbis/resource_importer_ogg_vorbis.cpp:102.
ERROR: _reimport_file: Error importing: res://BROKEN_Kevin_MacLeod_Action.ogg
   At: editor/editor_file_system.cpp:1784.
```

**Steps to reproduce:**
Either:
- Open the Test Reproduction Project
- Get an ogg with a cover image, and then remove it with `ffmpeg -i sound.ogg -q 1 -map a sound.ogg`. Compare import results

**Minimal reproduction project:**
[GodotTestProject.zip](https://github.com/godotengine/godot/files/3613376/GodotTestProject.zip)

**Comment by Calinou** [comment]
I wonder if this is a bug in stb_vorbis (the library Godot uses to decode Ogg Vorbis files). Can you reproduce this with the same file in any other application that uses stb_vorbis?

**Comment by nathanwfranke** [comment]
No longer reproducible in master

**Comment by Sslaxx** [comment]
Been re-reported with 3.2.2 in #40460.

**Comment by EIREXE** [comment]
> Been re-reported as an issue with 3.2.2 in #40460. Regression?

I don't think it's a regression, from what it looks like it's been fixed in master but not in 3.2?

**Comment by akien-mga** [comment]
> No longer reproducible in master

It's still reproducible in `master` for me.
Doesn't seem related to #40460 which was a regression in stb_vorbis in 3.2.2.

**Comment by akien-mga** [comment]
I'm not sure this is a bug, as the "broken" file in the attached project is actually recognized as an Ogg Theora video (with Ogg Vorbis audio):
```
$ file *.ogg
BROKEN_Kevin_MacLeod_Action.ogg:  Ogg data, Theora video
WORKING_Kevin_MacLeod_Action.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~80000 bps
```

PulseAudio can't open it either:
```
$ paplay BROKEN_Kevin_MacLeod_Action.ogg
Failed to open audio file.
```

Here's what ffmpeg says:
```
$ ffmpeg -i BROKEN_Kevin_MacLeod_Action.ogg -hide_banner
Input #0, ogg, from 'BROKEN_Kevin_MacLeod_Action.ogg':
  Duration: 00:03:15.21, start: 0.000000, bitrate: 92 kb/s
    Stream #0:0: Video: theora, yuv444p, 400x400 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Other
      encoder         : Lavc57.107.100 libtheora
      title           : Action
      artist          : Kevin MacLeod
      track           : 14/15
      album           : Scoring: Action
      TBP             : 116
      genre           : Soundtrack
      encoded_by      : iTunes v6.0.2.23
      iTunNORM        :  00000024 00000041 00000259 000003FB 00018929 0001A292 000032FA 000049B1 0002C668 0002AE1F
      iTunSMPB        :  00000000 00000210 00000765 000000000083530B 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
      TCM             : Kevin MacLeod
      date            : 2006
    Stream #0:1: Audio: vorbis, 44100 Hz, stereo, fltp, 112 kb/s
    Metadata:
      encoder         : Lavc57.107.100 libvorbis
      title           : Action
      artist          : Kevin MacLeod
      track           : 14/15
      album           : Scoring: Action
      TBP             : 116
      genre           : Soundtrack
      encoded_by      : iTunes v6.0.2.23
      iTunNORM        :  00000024 00000041 00000259 000003FB 00018929 0001A292 000032FA 000049B1 0002C668 0002AE1F
      iTunSMPB        :  00000000 00000210 00000765 000000000083530B 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
      TCM             : Kevin MacLeod
      date            : 2006
```

I tested `stb_vorbis` directly upstream and confirmed that it's not able to load the "BROKEN" file. It could possibly be implemented if there's a real need for it. It's the first time I see an OGG Vorbis audio track with a hardcoded cover as video channel though, are those really common?

**Comment by akien-mga** [comment]
Yeah the file in the MRP is just bogus. I can't reach incompetech.com right now to confirm that it's the one Kevin MacLeod generated, but it should be fixed to use the proper VorbisComment feature to embed cover art, not a separate video stream.

Starting from the "WORKING" file, I used [EasyTAG](https://wiki.gnome.org/Apps/EasyTAG) to embed a new image as cover, and the resulting file works fine and is still recognized as an OGG Vorbis stream:
```
$ file FIXED_Kevin_MacLeod_Action.ogg
FIXED_Kevin_MacLeod_Action.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~80000 bps

$ ffprobe -hide_banner FIXED_Kevin_MacLeod_Action.ogg
Input #0, ogg, from 'FIXED_Kevin_MacLeod_Action.ogg':
  Duration: 00:03:15.21, start: 0.000000, bitrate: 66 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 80 kb/s
    Metadata:
      TITLE           : Action
      ARTIST          : Kevin MacLeod
      ALBUM           : Scoring: Action
      DATE            : 2006
      track           : 14
      TRACKTOTAL      : 15
      GENRE           : Soundtrack
    Stream #0:1: Video: mjpeg (Progressive), yuvj444p(pc, bt470bg/unknown/unknown), 720x500 [SAR 300:300 DAR 36:25], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
      title           : godot-debug.jpg
```

EasyTAG would also report the "BROKEN" file as invalid, and would not be able to display any of its tags:

![Screenshot_20200720_133842](https://user-images.githubusercontent.com/4701338/87933893-5cd74500-ca8e-11ea-8990-10bbd4d1fc9b.png)
![Screenshot_20200720_133905](https://user-images.githubusercontent.com/4701338/87933907-6496e980-ca8e-11ea-8c42-d7aeb555e7a5.png)
![Screenshot_20200720_133918](https://user-images.githubusercontent.com/4701338/87933918-6b256100-ca8e-11ea-92b2-8c2aa5167f99.png)
![Screenshot_20200720_133957](https://user-images.githubusercontent.com/4701338/87933973-83957b80-ca8e-11ea-9d59-51263b0154db.png)

So IMO this is a *wontfix*, that file is just invalid. Some support for it *could* be added to `stb_vorbis`, but we'd need a clear specification on how such a file with theora stream for the cover is meant to be parsed. As it stands it just seems to be a bogus chimera created by iTunes in 2006, possibly before the VorbisComment specification for cover art was finalized.

**Comment by db0** [comment]
For anyone running into the same issue in the future, you can quickly fix this by removing the cover images (either when converting to ogg, or by doing a quick convertion anew) with ffmpeg. I was running into this issue after trying to convert some mp3 to reduce their size. 

My original command was

```
IFS=$'\n'; for f in $(ls *.mp3); do ffmpeg -i $f "/c/Projects/hypnagonia/assets/music/shop/$(echo $f | sed 's/\.mp3//g').ogg"; done
```

And this created ogg files Godot could not read. Adjusting my command like this

```
IFS=$'\n'; for f in $(ls *.mp3); do ffmpeg -i $f -map a "/c/Projects/hypnagonia/assets/music/shop/$(echo $f | sed 's/\.mp3//g').ogg"; done
```

Removed the covers and Godot imported normally.

**Comment by Calinou** [comment]
Note that the `master` branch replaced stb_vorbis with libogg + libvorbis, so uncommon OGG files should load better now.
