### ISSUE TITLE
Timer was not added to the SceneTree! when exiting Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#32366]
**Godot version:**
3.2.alpha.custom_build. 04032a944
**OS/device including version:**
Ubuntu 19.04
**Issue description:**
This error shows when I exit Godot:
```
ERROR: start: Timer was not added to the SceneTree!
   At: scene/main/timer.cpp:111.
```
This happens in 
https://github.com/godotengine/godot/blob/dec10dd776fca2994277faa3a97b13e70317f784/scene/gui/text_edit.cpp#L4022-L4024
and
https://github.com/godotengine/godot/blob/dec10dd776fca2994277faa3a97b13e70317f784/scene/gui/text_edit.cpp#L3968-L3970

(Github images not working for me now)
https://imgur.com/a/mLLGH32

**Steps to reproduce:**
Run editor and exit game
**Minimal reproduction project:**
https://github.com/KoBeWi/The-Soulhunter

**Comment by rafaelgdp** [comment]
I'm still getting this error all over the place in MacOS Catalina. Has it really been solved??? I'm at commit 28294b1f1979e2c39423dab6767fa6b159841e7d.

**Comment by qarmin** [comment]
The error in this issue was fixed, but same error message you can get when do different things, and if you are sure that this isn't your fault, then create new issue.

**Comment by rafaelgdp** [comment]
I'm still not sure what was causing it, but after editing some scenes and scripts, it stopped showing. It was very weird, though. Maybe it was my fault, indeed.

**Comment by boquetipo** [comment]
Hello.

I'm using Linux 64-bit standard, 3.2.2.stable.official and I got this very error.

**Comment by qarmin** [comment]
Please create a new issue and provide minimal project, because without it we can't see if issue is valid or not.
