### ISSUE TITLE
3.1.1.  2D Mouse zoom does not behave same as 3D on Mac OS X.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#32520]
**Godot version:**
3.1.1 stable

**OS/device including version:**
Mac OS X Mojave

**Issue description:**
Magic Mouse zooming does not work in 2D editor at all. However works fine in 3D Editor

Holding down CTRL+Mouse finger slide, zooms properly in 3D. There is even a setting in Editor Settings.

However CTRL+Mouse finger slide in 2D does NOT zoom. Instead it scrolls the viewport up/down left or right instead of zooming.  Also there are no Editor settings for zoom 2D.

**Editor settings available for keyword Zoom**
![image](https://user-images.githubusercontent.com/930478/66129422-e41a0180-e5bd-11e9-9d22-864addb5e0da.png)

**Comment by wyattbiker** [comment]
Maybe someone with more understanding can look at this code and give me a hint as to the issue. Keeping in mind that CTRL+Magic Mouse wheel works for 3D. I can compile and test if needed. Thanks.

and in _godot/platform/osx/os_osx.mm_
`- (void)scrollWheel:(NSEvent *)event`

In _godot/editor/plugins/canvas_item_editor_plugin.cpp_
Method: `bool CanvasItemEditor::_gui_input_zoom_or_pan(const Ref<InputEvent> &p_event)`

**Comment by asmaloney** [comment]
Just ran into this as well with 3.2.1. Not a great UX when the very first thing you try with a new engine doesn't work as expected ;-)

I've seen a variety of issues brought up for this, but no solutions. Is it addressed in anything more recent than 3.2.1?

If not, maybe someone with some in-depth knowledge of the code can give an outline of what needs to be done to fix it?

**Comment by lukaskrepel** [comment]
This issue still exists on v4.1.2
I cannot zoom with the mouse in 2D like in 3D.

**Comment by asmaloney** [comment]
I tried with 4.1.1 and it does indeed look like zooming with the magic mouse in 2D has broken since my fix.

In addition, the actions when scrolling via scroll wheel and magic mouse seem inconsistent:

|| mouse ||action |
|--|--|--|--|
|3D| normal | | zoom|
|3D| normal | <kbd>control</kbd>| zoom|
|3D| magic | | tilt|
|3D| magic | <kbd>control</kbd>| zoom|
|2D| normal | | zoom|
|2D| normal | <kbd>control</kbd>| pan vertical|
|2D| magic | | pan vertical|
|2D| magic | <kbd>control</kbd>| pan vertical|

I would suggest this issue be reopened.
