### ISSUE TITLE
[Android] Godot is crashing while creating apk when i put a plugin.

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#32553]
3.2 master
Win10

Godot is crashing while creating apk, not during the build stage but the last stage when it starts show the merging of  the project into apk it crashes at the beginning of the last stage.
 
I am using admob from Shin-Nil - https://github.com/Shin-NiL/Godot-Android-Admob-Plugin
Although it gives an error for layout in the banner section but I null it down.

It might be occurring due to the merging of plugin into the project.

**Comment by DisDoh** [comment]
It seems this issue has been resolved on this github admob plugin: 
https://github.com/kloder-games/godot-admob 
The plugin that you are using was inspired by this one and an other one.
This github has a new commit 17 days ago: 

fixes #72 which caused crash during app startup

**Comment by akien-mga** [comment]
Please report module-specific issues to the module's own repo. As seen here this might well be a bug in the module and not in the engine.

The developers of the module can then debug and estimate with you whether that's something they can fix, or if it's an engine bug which should be reported here.

**Comment by akien-mga** [comment]
Nevermind, I was misled by https://github.com/godotengine/godot/issues/32553#issuecomment-538648202, but if the crash happens in the editor while exporting, there's indeed something to fix in Godot itself.

**Comment by akien-mga** [comment]
Can you start Godot from a terminal and paste the output when it crashes?

**Comment by DisDoh** [comment]
Sorry miss understood the problem...

**Comment by gamergamesz** [comment]
![error](https://user-images.githubusercontent.com/13883739/66256199-22274900-e7a9-11e9-8c65-a4c673447846.gif)

The editor crashes here
![vlcsnap-2019-10-05-19h50m04s192](https://user-images.githubusercontent.com/13883739/66256242-6dd9f280-e7a9-11e9-8715-ef0f521573d5.png)

**Comment by gamergamesz** [comment]
``` 
ERROR: _update_custom_build_project: Not adding application attributes as the expected tag was not found in '<application': android:icon="@drawable/icon"
   At: platform/android/export/export.cpp:1897
ERROR: get: FATAL: Index p_index=-1 out of size (size()=58)
   At: ./core/cowdata.h:151
```

**Comment by akien-mga** [comment]
You should update your custom build template (delete the "android" folder and re-install the template), this has been fixed already.

**Comment by gamergamesz** [comment]
@akien-mga It still crashes at the same spot but now it's giving this error
```
ERROR: get: FATAL: Index p_index=-1 out of size (size()=59)
   At: ./core/cowdata.h:151
```

**Comment by akien-mga** [comment]
Can you share the project, or make a simple new one that triggers the issue?

**Comment by gamergamesz** [comment]
Well I am using demo project of admob from Shin-Nil but here is the one with plugin( i have deleted build folder and only the plugin is in the Android folder) @akien-mga 
[demo.zip](https://github.com/godotengine/godot/files/3694637/demo.zip)

**Comment by gamergamesz** [comment]
Has the bug been confirmed ?

**Comment by akien-mga** [comment]
I can reproduce the crash on the master branch on Linux:
```
Add: src:/home/akien/tmp/godot/bug/demo/android/admob-plugin/src
Section: APPLICATION
Section: DEPENDENCIES
ERROR: get: FATAL: Index p_index=-1 out of size (size()=60)
   At: ./core/cowdata.h:152.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3caf0) [0x7f4cc78d2af0] (??:0)
[2] CowData<String>::get(int) const (/home/akien/Projects/godot/godot.git/./core/cowdata.h:152 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/akien/Projects/godot/godot.git/./core/vector.h:85)
[4] EditorExportPlatformAndroid::_fix_manifest(Ref<EditorExportPreset> const&, Vector<unsigned char>&, bool) (/home/akien/Projects/godot/godot.git/platform/android/export/export.cpp:838 (discriminator 5))
[5] EditorExportPlatformAndroid::export_project(Ref<EditorExportPreset> const&, bool, String const&, int) (/home/akien/Projects/godot/godot.git/platform/android/export/export.cpp:2096)
[6] ProjectExportDialog::_export_project_to_path(String const&) (/home/akien/Projects/godot/godot.git/editor/project_export.cpp:965 (discriminator 1))
[7] MethodBind1<String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/./core/method_bind.gen.inc:775 (discriminator 12))
[8] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/core/object.cpp:921 (discriminator 1))
[9] Object::emit_signal(StringName const&, Variant const**, int) (/home/akien/Projects/godot/godot.git/core/object.cpp:1218 (discriminator 1))
[10] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/akien/Projects/godot/godot.git/core/object.cpp:1274)
[11] EditorFileDialog::_action_pressed() (/home/akien/Projects/godot/godot.git/editor/editor_file_dialog.cpp:451 (discriminator 4))
[12] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/./core/method_bind.gen.inc:61 (discriminator 4))
[13] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/core/object.cpp:921 (discriminator 1))
[14] Object::emit_signal(StringName const&, Variant const**, int) (/home/akien/Projects/godot/godot.git/core/object.cpp:1218 (discriminator 1))
[15] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/akien/Projects/godot/godot.git/core/object.cpp:1274)
[16] AcceptDialog::_ok_pressed() (/home/akien/Projects/godot/godot.git/scene/gui/dialogs.cpp:401 (discriminator 2))
[17] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/./core/method_bind.gen.inc:61 (discriminator 4))
[18] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/core/object.cpp:921 (discriminator 1))
[19] Object::emit_signal(StringName const&, Variant const**, int) (/home/akien/Projects/godot/godot.git/core/object.cpp:1218 (discriminator 1))
[20] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/akien/Projects/godot/godot.git/core/object.cpp:1274)
[21] BaseButton::_pressed() (/home/akien/Projects/godot/godot.git/scene/gui/base_button.cpp:135 (discriminator 2))
[22] BaseButton::on_action_event(Ref<InputEvent>) (/home/akien/Projects/godot/godot.git/scene/gui/base_button.cpp:174)
[23] BaseButton::_gui_input(Ref<InputEvent>) (/home/akien/Projects/godot/godot.git/scene/gui/base_button.cpp:64 (discriminator 3))
[24] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/./core/method_bind.gen.inc:775 (discriminator 12))
[25] Object::call_multilevel(StringName const&, Variant const**, int) (/home/akien/Projects/godot/godot.git/core/object.cpp:763 (discriminator 1))
[26] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/akien/Projects/godot/godot.git/core/object.cpp:864)
[27] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/akien/Projects/godot/godot.git/scene/main/viewport.cpp:1524 (discriminator 2))
[28] Viewport::_gui_input_event(Ref<InputEvent>) (/home/akien/Projects/godot/godot.git/scene/main/viewport.cpp:1904 (discriminator 3))
[29] Viewport::input(Ref<InputEvent> const&) (/home/akien/Projects/godot/godot.git/scene/main/viewport.cpp:2680 (discriminator 2))
[30] Viewport::_vp_input(Ref<InputEvent> const&) (/home/akien/Projects/godot/godot.git/scene/main/viewport.cpp:1301)
[31] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/./core/method_bind.gen.inc:775 (discriminator 12))
[32] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/akien/Projects/godot/godot.git/core/object.cpp:921 (discriminator 1))
[33] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/akien/Projects/godot/godot.git/core/object.cpp:848)
[34] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/akien/Projects/godot/godot.git/scene/main/scene_tree.cpp:264)
[35] SceneTree::input_event(Ref<InputEvent> const&) (/home/akien/Projects/godot/godot.git/scene/main/scene_tree.cpp:419 (discriminator 6))
[36] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/akien/Projects/godot/godot.git/main/input_default.cpp:416)
[37] InputDefault::parse_input_event(Ref<InputEvent> const&) (/home/akien/Projects/godot/godot.git/main/input_default.cpp:260)
[38] InputDefault::flush_accumulated_events() (/home/akien/Projects/godot/godot.git/main/input_default.cpp:679)
[39] OS_X11::process_xevents() (/home/akien/Projects/godot/godot.git/platform/x11/os_x11.cpp:2626)
[40] OS_X11::run() (/home/akien/Projects/godot/godot.git/platform/x11/os_x11.cpp:3191)
[41] /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64(main+0x104) [0x1438146] (/home/akien/Projects/godot/godot.git/platform/x11/godot_x11.cpp:57)
[42] /lib64/libc.so.6(__libc_start_main+0xeb) [0x7f4cc78bcb0b] (??:0)
[43] /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64(_start+0x2a) [0x1437f9a] (/home/iurt/rpmbuild/BUILD/glibc-2.29/csu/../sysdeps/x86_64/start.S:122)
-- END OF BACKTRACE --
Aborted (core dumped)
```

CC @godotengine/android

**Comment by gianllucah** [comment]
I don't know why but when i remove `<meta-data>` tag from my AndroidManifest.conf works. Maybe a character?

My AndroidManifest.conf has the following code:

This don't works:
![dontwork](https://user-images.githubusercontent.com/28108603/66519554-e7315800-eabd-11e9-989c-539fae8306ad.png)


This works:
![work](https://user-images.githubusercontent.com/28108603/66519612-0203cc80-eabe-11e9-900d-06b86b68e8f7.png)

**Comment by LillyByte** [comment]
> Well I am using demo project of admob from Shin-Nil but here is the one with plugin( i have deleted build folder and only the plugin is in the Android folder) @akien-mga
> [demo.zip](https://github.com/godotengine/godot/files/3694637/demo.zip)

I can confirm, this compiles for me, but the Godot 3.2 alpha 1 crashes while building the final APK.
 
Exactly the same for as in the GIFs-- running Windows 10 Pro, hard crash to desktop.

**Comment by akien-mga** [comment]
@m4gr3d I'm having a look at it now, just co-assigned you for feedback if you have any :)

**Comment by akien-mga** [comment]
@gianllucah That's because the crash happens here, so if you don't have `meta-data`, it doesn't go beyond the first condition (it crashes on the second, index out of size):
https://github.com/godotengine/godot/blob/781e4f8673857b2b318e919ecb780bfad972a5a6/platform/android/export/export.cpp#L838-L843

**Comment by akien-mga** [comment]
@m4gr3d So for some reason `attr_value` is `0xFFFFFFFF` here and we thus crash trying to index the table. This works it around, and it seems to still allow inserting the right values when using Oculus VR `xr_mode`. That's a hack though :)
```diff
diff --git a/platform/android/export/export.cpp b/platform/android/export/export.cpp
index b61575e2aa..0e8e635b6d 100644
--- a/platform/android/export/export.cpp
+++ b/platform/android/export/export.cpp
@@ -828,14 +828,14 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
                                                        encode_uint32(min_gles3 ? 0x00030000 : 0x00020000, &p_manifest.write[iofs + 16]);
                                                }
 
-                                               if (tname == "meta-data" && attrname == "name" && string_table[attr_value] == "xr_mode_metadata_name") {
+                                               if (tname == "meta-data" && attrname == "name" && attr_value != 0xFFFFFFFF && string_table[attr_value] == "xr_mode_metadata_name") {
                                                        // Update the meta-data 'android:name' attribute based on the selected XR mode.
                                                        if (xr_mode_index == 1 /* XRMode.OVR */) {
                                                                string_table.write[attr_value] = "com.samsung.android.vr.application.mode";
                                                        }
                                                }
 
-                                               if (tname == "meta-data" && attrname == "value" && string_table[attr_value] == "xr_mode_metadata_value") {
+                                               if (tname == "meta-data" && attrname == "value" && attr_value != 0xFFFFFFFF && string_table[attr_value] == "xr_mode_metadata_value") {
                                                        // Update the meta-data 'android:value' attribute based on the selected XR mode.
                                                        if (xr_mode_index == 1 /* XRMode.OVR */) {
                                                                string_table.write[attr_value] = "vr_only";
```

Interestingly it fails only on the second one (`value`), so it seems like the parser handles the first `android:name` find but then treats `android:value:` as a resource (`0xFFFFFFFF`) instead of a string?

BTW there's related dead code here:
https://github.com/godotengine/godot/blob/781e4f8673857b2b318e919ecb780bfad972a5a6/platform/android/export/export.cpp#L769-L779

Not sure what a correct fix would be here as I'm not so familiar with this black magic @hpvb wrote :D Also CC @BastiaanOlij.

---

And to be explicit, here's the `AndroidManifest.conf` from the plugin that triggers this issue:
```
[application]
        <activity android:name="com.google.android.gms.ads.AdActivity"
                android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>

        <meta-data android:name="com.google.android.gms.version"
                android:value="@integer/google_play_services_version" />

        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
```
It doesn't seem malformed, though even if it were, we should not crash.

**Comment by akien-mga** [comment]
I'm pushing my temporary workaround as #32740 as I want to release 3.2 alpha 2 today with this fix (and others). Let's keep this issue open though as we should still figure out the real issue and fix it.

**Comment by m4gr3d** [comment]
@akien-mga That's actually the correct solution. 

The [`android:name` attribute](https://developer.android.com/guide/topics/manifest/meta-data-element.html#nm) of the [meta-data element](https://developer.android.com/guide/topics/manifest/meta-data-element.html) only accept `raw` string values, that's why it's not affected by the issue.

The [`android:value` attribute](https://developer.android.com/guide/topics/manifest/meta-data-element.html#val) on the other hand can accept both a `raw` string value or a [`string resource value`](https://developer.android.com/guide/topics/resources/string-resource) which underneath the hood is just an integer value used by the Android build system to point to the actual value.
The bug surfaced by having the string resource `@string/facebook_app_id` in the `android:value` attribute. If you were to replace that string resource by the actual string value being pointed at, the issue would vanish.

A slightly cleaner fix would be to remove the check on [line 833 for the `android:name` attribute](https://github.com/godotengine/godot/blob/197be41cca6f24798e542398437f5dc35923c2f1/platform/android/export/export.cpp#L833) and use the [`value` variable defined on line 769](https://github.com/godotengine/godot/blob/197be41cca6f24798e542398437f5dc35923c2f1/platform/android/export/export.cpp#L769) since it would only pass our check for the `xr_mode_metadata` if `attr_value != 0xFFFFFFFF`.
Though what you have is semantically correct as well so we could keep it as is if desired.

**Comment by akien-mga** [comment]
Thanks for the explanations about the Android string resources, that makes sense.

> A slightly cleaner fix would be to remove the check on [line 833 for the `android:name` attribute](https://github.com/godotengine/godot/blob/197be41cca6f24798e542398437f5dc35923c2f1/platform/android/export/export.cpp#L833) and use the [`value` variable defined on line 769](https://github.com/godotengine/godot/blob/197be41cca6f24798e542398437f5dc35923c2f1/platform/android/export/export.cpp#L769) for the check on [line 840 for the `android:value` attribute](https://github.com/godotengine/godot/blob/197be41cca6f24798e542398437f5dc35923c2f1/platform/android/export/export.cpp#L840) since it would only pass our check for the `xr_mode_metadata` if `attr_value != 0xFFFFFFFF`.

Sounds good, do you want to PR this as a cleanup of my previous PR, fully fixing this issue?

**Comment by m4gr3d** [comment]
Sounds good. I'll create a follow-up cleanup PR.

**Comment by m4gr3d** [comment]
Fixed by PR #32752
