### ISSUE TITLE
3.2.alpha1.official produces multiple debug errors when breakpoint in load() script.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#32633]
**Godot version:**
3.2.alpha1.official

**OS/device including version:**
Mac OS X Mojave

**Issue description:**
Multiple debug errors when breakpoint set in a loaded script from the main scene.
```
E 0:00:01:0044   is_refusing_new_network_connections: No network peer is assigned. Unable to get 'refuse_new_connections'.
  <C++ Error>    Condition ' !network_peer.is_valid() ' is true. returned: false
  <C++ Source>   core/io/multiplayer_api.cpp:822 @ is_refusing_new_network_connections()
  <Stack Trace>  somescript.gd:4 @ _init()
                 TestScript.gd:5 @ _ready()
```

**Main Scene**
![image](https://user-images.githubusercontent.com/930478/66356471-05ba1680-e939-11e9-8f37-9568a7011fe7.png)

**Loaded script**
![image](https://user-images.githubusercontent.com/930478/66356391-cdb2d380-e938-11e9-8db9-232f7f3f84c4.png)

**Steps to reproduce:**
Create a Main Control scene and add the following code:
```
extends Control
func _ready():
	var MySomescript = load("somescript.gd")
	var myInst = MySomescript.new()
	pass
```
Then create the script somescript.gd and add the following code:
```
extends SceneTree
var somevar = 20
var foo1='abcd'
func _init():
	print(foo1)
```

Run without breakpoints, no `is_refusing_new_network_connections` errors appear.

Set a breakpoint on the `var somevar = 20` line. Run the project and notice the multiple debugger errors.

**Comment by akien-mga** [comment]
CC @Faless @Geequlim

**Comment by akien-mga** [comment]
To clarify, does this happen together with https://github.com/godotengine/godot/issues/32533#issuecomment-539228135?

If so that's probably just a consequence of #32533 and should now be fixed. You could not set up the debugger so debugging then doesn't work (it could however be handled more gracefully by Godot).

**Comment by Faless** [comment]
> To clarify, does this happen together with [#32533 (comment)](https://github.com/godotengine/godot/issues/32533#issuecomment-539228135)?

Yes, it still happens.

This is partly a regression, in part it's been like this in `3.1` too.

Specifically, there are 2 issues, with the live edit and debugger (both related to the fact that `refuse_new_network_connections` shows the error when no `network_peer` is set in the `SceneTree`):

1
----
(Also present in `3.1`) `SceneTree.refuse_new_network_connections` spits an error as soon as there is a breakpoint inside the SceneTreee script as the debugger tries to send all it's property to the editor (happen once, right after breakpoint).

```
#0  MultiplayerAPI::is_refusing_new_network_connections (this=0x6433db0) at core/io/multiplayer_api.cpp:822
#1  0x0000000002b2111e in SceneTree::is_refusing_new_network_connections (this=0x938a570) at scene/main/scene_tree.cpp:1795
#2  0x00000000015a8f03 in MethodBind0RC<bool>::call (this=0x69ffd70, p_object=0x938a570, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:593
#3  0x00000000038941de in ClassDB::get_property (p_object=0x938a570, p_property=..., r_value=...) at core/class_db.cpp:1069
#4  0x00000000039178ed in Object::get (this=0x938a570, p_name=..., r_valid=0x0) at core/object.cpp:494
#5  0x0000000003b03513 in encode_variant (p_variant=..., r_buffer=0x0, r_len=@0x7fffffffbc28: 152, p_full_objects=true) at core/io/marshalls.cpp:1107
#6  0x0000000003965393 in ScriptDebuggerRemote::_put_variable (this=0x57b8a30, p_name=..., p_variable=...) at core/script_debugger_remote.cpp:111
#7  0x0000000003966587 in ScriptDebuggerRemote::debug (this=0x57b8a30, p_script=0x6500340, p_can_continue=true, p_is_error_breakpoint=true) at core/script_debugger_remote.cpp:240
#8  0x00000000014f0547 in GDScriptLanguage::debug_break (this=0x6500340, p_error=..., p_allow_continue=true) at modules/gdscript/gdscript_editor.cpp:241
#9  0x00000000015166f3 in GDScriptFunction::call (this=0x6f273e0, p_instance=0x6caa270, p_args=0x7fffffffc9c0, p_argcount=0, r_err=..., p_state=0x0)
    at modules/gdscript/gdscript_function.cpp:1503
#10 0x00000000014b5b84 in GDScript::_create_instance (this=0x938c0f0, p_args=0x7fffffffc9c0, p_argcount=0, p_owner=0x938a570, p_isref=false, r_error=...)
    at modules/gdscript/gdscript.cpp:114
#11 0x00000000014b5f7f in GDScript::_new (this=0x938c0f0, p_args=0x7fffffffc9c0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:165
#12 0x00000000014dadf8 in MethodBindVarArg<GDScript>::call (this=0x6b87ed0, p_object=0x938c0f0, p_args=0x7fffffffc9c0, p_arg_count=0, r_error=...) at ./core/method_bind.h:344
#13 0x000000000391a2c9 in Object::call (this=0x938c0f0, p_method=..., p_args=0x7fffffffc9c0, p_argcount=0, r_error=...) at core/object.cpp:921
#14 0x00000000014b94ae in GDScript::call (this=0x938c0f0, p_method=..., p_args=0x7fffffffc9c0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:655
#15 0x00000000039bf3bb in Variant::call_ptr (this=0x7fffffffc960, p_method=..., p_args=0x7fffffffc9c0, p_argcount=0, r_ret=0x7fffffffc9a8, r_error=...) at core/variant_call.cpp:1083
#16 0x0000000001513abc in GDScriptFunction::call (this=0x6fc06d0, p_instance=0x74b83e0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:1079
#17 0x00000000014bd045 in GDScriptInstance::_ml_call_reversed (this=0x74b83e0, sptr=0x93cd1a0, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gdscript.cpp:1195
#18 0x00000000014bd0cd in GDScriptInstance::call_multilevel_reversed (this=0x74b83e0, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gdscript.cpp:1202
#19 0x0000000002ae6de8 in Node::_notification (this=0x933fe20, p_notification=13) at scene/main/node.cpp:149
#20 0x000000000147fed0 in Node::_notificationv (this=0x933fe20, p_notification=13, p_reversed=false) at ./scene/main/node.h:46
#21 0x0000000001480517 in CanvasItem::_notificationv (this=0x933fe20, p_notification=13, p_reversed=false) at ./scene/2d/canvas_item.h:166
#22 0x0000000001480bc7 in Control::_notificationv (this=0x933fe20, p_notification=13, p_reversed=false) at ./scene/gui/control.h:48
#23 0x000000000391a442 in Object::notification (this=0x933fe20, p_notification=13, p_reversed=false) at core/object.cpp:931
#24 0x0000000002ae71d6 in Node::_propagate_ready (this=0x933fe20) at scene/main/node.cpp:196
#25 0x0000000002ae715a in Node::_propagate_ready (this=0x6d09490) at scene/main/node.cpp:188
#26 0x0000000002af40f6 in Node::_set_tree (this=0x6d09490, p_tree=0x6aee870) at scene/main/node.cpp:2550
#27 0x0000000002b193d4 in SceneTree::init (this=0x6aee870) at scene/main/scene_tree.cpp:454
#28 0x0000000001400d7e in OS_X11::run (this=0x7fffffffd5b0) at platform/x11/os_x11.cpp:3180
#29 0x00000000013f0a3f in main (argc=8, argv=0x7fffffffdd48) at platform/x11/godot_x11.cpp:56
```

2
-----
(Only present in `3.2`) That same error is spammed by the debugger which constantly sends the properties of the selected object ID to the remote inspector.

```
#0  MultiplayerAPI::is_refusing_new_network_connections (this=0x6433db0) at core/io/multiplayer_api.cpp:822
#1  0x0000000002b2111e in SceneTree::is_refusing_new_network_connections (this=0x938a570) at scene/main/scene_tree.cpp:1795
#2  0x00000000015a8f03 in MethodBind0RC<bool>::call (this=0x69ffd70, p_object=0x938a570, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:593
#3  0x00000000038941de in ClassDB::get_property (p_object=0x938a570, p_property=..., r_value=...) at core/class_db.cpp:1069
#4  0x00000000039178ed in Object::get (this=0x938a570, p_name=..., r_valid=0x0) at core/object.cpp:494
#5  0x000000000396aada in ScriptDebuggerRemote::_send_object_id (this=0x57b8a30, p_id=1184) at core/script_debugger_remote.cpp:640
#6  0x00000000039669a5 in ScriptDebuggerRemote::debug (this=0x57b8a30, p_script=0x6500340, p_can_continue=true, p_is_error_breakpoint=true) at core/script_debugger_remote.cpp:291
#7  0x00000000014f0547 in GDScriptLanguage::debug_break (this=0x6500340, p_error=..., p_allow_continue=true) at modules/gdscript/gdscript_editor.cpp:241
#8  0x00000000015166f3 in GDScriptFunction::call (this=0x6f273e0, p_instance=0x6caa270, p_args=0x7fffffffc9c0, p_argcount=0, r_err=..., p_state=0x0)
    at modules/gdscript/gdscript_function.cpp:1503
#9  0x00000000014b5b84 in GDScript::_create_instance (this=0x938c0f0, p_args=0x7fffffffc9c0, p_argcount=0, p_owner=0x938a570, p_isref=false, r_error=...)
    at modules/gdscript/gdscript.cpp:114
#10 0x00000000014b5f7f in GDScript::_new (this=0x938c0f0, p_args=0x7fffffffc9c0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:165
#11 0x00000000014dadf8 in MethodBindVarArg<GDScript>::call (this=0x6b87ed0, p_object=0x938c0f0, p_args=0x7fffffffc9c0, p_arg_count=0, r_error=...) at ./core/method_bind.h:344
#12 0x000000000391a2c9 in Object::call (this=0x938c0f0, p_method=..., p_args=0x7fffffffc9c0, p_argcount=0, r_error=...) at core/object.cpp:921
#13 0x00000000014b94ae in GDScript::call (this=0x938c0f0, p_method=..., p_args=0x7fffffffc9c0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:655
#14 0x00000000039bf3bb in Variant::call_ptr (this=0x7fffffffc960, p_method=..., p_args=0x7fffffffc9c0, p_argcount=0, r_ret=0x7fffffffc9a8, r_error=...) at core/variant_call.cpp:1083
#15 0x0000000001513abc in GDScriptFunction::call (this=0x6fc06d0, p_instance=0x74b83e0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:1079
#16 0x00000000014bd045 in GDScriptInstance::_ml_call_reversed (this=0x74b83e0, sptr=0x93cd1a0, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gdscript.cpp:1195
#17 0x00000000014bd0cd in GDScriptInstance::call_multilevel_reversed (this=0x74b83e0, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gdscript.cpp:1202
#18 0x0000000002ae6de8 in Node::_notification (this=0x933fe20, p_notification=13) at scene/main/node.cpp:149
#19 0x000000000147fed0 in Node::_notificationv (this=0x933fe20, p_notification=13, p_reversed=false) at ./scene/main/node.h:46
#20 0x0000000001480517 in CanvasItem::_notificationv (this=0x933fe20, p_notification=13, p_reversed=false) at ./scene/2d/canvas_item.h:166
#21 0x0000000001480bc7 in Control::_notificationv (this=0x933fe20, p_notification=13, p_reversed=false) at ./scene/gui/control.h:48
#22 0x000000000391a442 in Object::notification (this=0x933fe20, p_notification=13, p_reversed=false) at core/object.cpp:931
#23 0x0000000002ae71d6 in Node::_propagate_ready (this=0x933fe20) at scene/main/node.cpp:196
#24 0x0000000002ae715a in Node::_propagate_ready (this=0x6d09490) at scene/main/node.cpp:188
#25 0x0000000002af40f6 in Node::_set_tree (this=0x6d09490, p_tree=0x6aee870) at scene/main/node.cpp:2550
#26 0x0000000002b193d4 in SceneTree::init (this=0x6aee870) at scene/main/scene_tree.cpp:454
#27 0x0000000001400d7e in OS_X11::run (this=0x7fffffffd5b0) at platform/x11/os_x11.cpp:3180
#28 0x00000000013f0a3f in main (argc=8, argv=0x7fffffffdd48) at platform/x11/godot_x11.cpp:56
```

**Comment by wyattbiker** [comment]
> To clarify, does this happen together with [#32533 (comment)](https://github.com/godotengine/godot/issues/32533#issuecomment-539228135)?
> 
> If so that's probably just a consequence of #32533 and should now be fixed. You could not set up the debugger so debugging then doesn't work (it could however be handled more gracefully by Godot).

For me #32533 happens when I Quit To Project and then re Edit again. I don't know if that is related to this.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 3.2 builds?

**Comment by GoDotMad** [comment]
yes it is still reproducible.

**Comment by GoDotMad** [comment]
it is now fixed after the 3.2.1 update

**Comment by Faless** [comment]
I can still reproduce in `3.2.1 stable`.

**Comment by MikeSchulze** [comment]
got same error on 3.2.2.stable.mono.official
`
E 0:00:00.932   is_refusing_new_network_connections: No network peer is assigned. Unable to get 'refuse_new_connections'.
  <C++-Fehler>  Condition "!network_peer.is_valid()" is true. Returned: false
  <C++-Quellcode>core/io/multiplayer_api.cpp:833 @ is_refusing_new_network_connections()
  <Stacktrace>  MeshUtils.gd:112 @ rotate()
                testMeshUtil.gd:19 @ testRotateNotEqual()
                testMeshUtil.gd:9 @ _ready()
`

**Comment by Gnumaru** [comment]
This still happens on 3.2.3

I have noted that this happens whenever you hold a reference to the scene tree. The script below illustrates the behavior:
```gdscript
extends Node
func _ready():
	breakpoint
	var the_tree = get_tree()
	breakpoint
```
Prior to getting the scene tree reference, there is no error. But as soon as there is a scene tree reference, for every step in the debugger, the message below will be printed
```
ERROR: No network peer is assigned. Unable to get 'refuse_new_connections'.
   At: core/io/multiplayer_api.cpp:833
```

**Comment by Arkadeievitch** [comment]
Hi, 
I think that I'm getting the same issue in Godot 3.3 (stable).
As suggested above, the following line seem to trigger the error : 
	var tree = get_tree()
Workaround : Using only get_tree() without referencing it in a variable.
