### ISSUE TITLE
Generated UV2s are not saved

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#32746]
**Godot version:**
Latest 3.2 Alpha aad4d86

**OS/device including version:**
Linux Mint 18.2

**Issue description:**
When you use the menu option Mesh->Unwrap UV2 for Lightmap/AO this successfully generates second set of UVs which can be viewed with Mesh->View UV2 and can be used for lightmapping.

The problem is that this is not registered as a change to the scene (the * does not appear on the scene tab) and it is not autosaved, as Godot thinks there have been no changes. Then next time you load the project, the lightmapping is gone, because the UV2 coords are not saved.

It took me a while to figure out what was going wrong here. When I was using a mesh stored in a tscn file, I could force it to save by explicitly choosing Scene->Save Scene from the menu. With an obj file I can't seem to get it to save UV2 at all.

**Steps to reproduce:**
Add a MeshInstance mesh that has no second set of UVs. Choose 'Unwrap UV2', verify they are there with 'View UV2'. Press Ctrl-S to save, then quit godot, and reopen the project. The UV2s are gone.

**Minimal reproduction project:**
[UV2Bug.zip](https://github.com/godotengine/godot/files/3717130/UV2Bug.zip)

**Comment by Hackmet** [comment]
I have the same issue, also with .obj models. Did it work in other versions of Godot? This bug makes the generate-lightmap-uv function essential useless :(

**Comment by wombatwingdings** [comment]
Same problem here in Godot 3.2.2 Beta [#39134](https://github.com/godotengine/godot/pull/39134) (from 8 June 2020). Not using .OBJ files.

**OS/device including version:**
Windows 10

UV2 seem to be stored in memory only. They don't appear to be stored in the scene. Explicitly saving (ctrl+S) due to scene not being marked as modified (no "*" appearing on title). Reloading tscn; UV2 are there. Restart Gogot; UV2 are gone. 

Maybe this is by design?

**Comment by huhund** [comment]
Doh, I stumble on the same issue, thanks for writing this bug report. I noticed that something else also gets broken after generating UV2. Because the material is not loaded after generating UV2 and saving. Unfortunately this makes it impossible to use this feature currently.

I wonder if this will change with Godot 4.0. As rumours tells me it will get a new light mapper.

Does anybody use authored UV2s? Is that working better?

**Comment by Calinou** [comment]
This should already fixed in the `master` branch now. Also, https://github.com/godotengine/godot/pull/40035 will fix this if it's merged into the `3.2` branch.

**Comment by lawnjelly** [comment]
You can author UV2s in blender / other modelling packages. But you can't import them as obj, as it only supports 1 uv channel, you will have to use another format (e.g. dae). This can work if you are e.g. building a level in blender. But if you are constructing the level out of objects within godot, it might not work well.

You can also do uv mapping with LLightmap if you are prepared to use a module, depending on what you are trying to do:
https://github.com/lawnjelly/godot-llightmap

**Comment by a3p169** [comment]
So, should we wait for the new light-mapper? Or the new light mapper is 4.0 exclusive? What's the direction here? Is using authored UV2, final solution?

**Comment by lawnjelly** [comment]
At present you can write code (in c++ or gdscript etc) to manually copy the vertices, uvs etc to a new mesh, and save that. That's the approach I ended up using, I don't know if there is any easier way (perhaps some duplicate mesh command or something).

**Comment by a3p169** [comment]
Well, it's better to use 'gltf' then. I like to create nodes with obj cause they give me more control over hierarchy. Currently with gltf I have to create hierarchy PLUS copy the parameters for 'meshinstance'. In any case, the bug is not major issue of other formats are working.

**Comment by akien-mga** [comment]
Fixed by #44628.

**Comment by Favkis** [comment]
godot 3.5 bug is not fixed, I cannot bake gridmap because UV2 arent saved at all.

**Comment by Calinou** [comment]
> godot 3.5 bug is not fixed, I cannot bake gridmap because UV2 arent saved at all.

If you're using OBJ meshes as tiles, see https://github.com/godotengine/godot/issues/52508.
