### ISSUE TITLE
CPUParticles2D renders wrong with GLES2 on iOS if scene uses NinePatchRect, Panel, Button or ProgressBar

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#32837]
**Godot version:**
Godot 3.1.1-stable official
Godot 3.1.2-alpha 8f3fea2058
Godot 3.2-alpha 48d3458f74

**OS/device including version:**
iPad 6th gen / 12.3.1

**Issue description:**
CPUParticles2D renders wrongly when scene has NinePatchRect on GLES2.
Here is a table to show if it renders correctly.

| CPUParticles2D        | GLES2 | GLES3 |
|-----------------------|-------|-------|
| with NinePatchRect    | X     | O     |
| without NinePatchRect | O     | O     |

![IMG_0002](https://user-images.githubusercontent.com/8281454/66778048-8ebaea00-ef05-11e9-911f-ea67b8172c62.PNG)
on GLES3

![IMG_0003](https://user-images.githubusercontent.com/8281454/66778054-9084ad80-ef05-11e9-886d-c2378d6244b7.PNG)
on GLES2

**Steps to reproduce:**
1. Add `NinePatchRect` and `CPUParticles2D`
2. run in on iOS device.

**Minimal reproduction project:**
[test particle.zip](https://github.com/godotengine/godot/files/3726128/test.particle.zip)

**Comment by volzhs** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
Is this a regression from 3.1.1? Or is the issue present there as well?

**Comment by volzhs** [comment]
@clayjohn 3.1.1-stable (official) has the same problem.

**Comment by volzhs** [comment]
3.2-alpha 48d3458f74 also has the same issue.

**Comment by volzhs** [comment]
@clayjohn would you have a look for this? :smiley:

**Comment by volzhs** [comment]
thank you for your time anyway. :+1:

**Comment by akien-mga** [comment]
Comment from @klimi15 in #34637:

> I have traced down the Bug a little more. Since I had no NinePatchRect , it also effects Panels,Buttons,Progress Bars. Not Canvas Items in generell though with Labels in the scene it works.
>
> When those are in the Scene, the GLBindTexture does not seem to work. I have no idea why though.

**Comment by akien-mga** [comment]
NinePatchRect, Panel, Button and ProgressBar are all GUI elements which can use nine-patch slicing feature for their stylebox textures, so the issue is probably related to that codepath.

**Comment by clayjohn** [comment]
I would like for this to get fixed, but unfortunately we don't have anyone stepping up that can work on iOS, so bumping to 4.0.

**Comment by clayjohn** [comment]
Good news! I am fairly certain this is the same underlying bug as #38318 which seems to be solved by https://github.com/godotengine/godot/issues/38318#issuecomment-622975336

If it is, we should have a fix on the way shortly. :)

**Comment by akien-mga** [comment]
Can you confirm if this is now fixed in 3.2.3 / 3.2.4-beta1?

**Comment by volzhs** [comment]
tested with 3.2.4-beta 150f9ce807e7b9be45bf8c030faa80510aea8407
it still happens, but a little bit different.

![image](https://user-images.githubusercontent.com/8281454/96793276-0a177b80-1437-11eb-973d-a21d6dcc1596.png)

**Comment by clayjohn** [comment]
@volzhs did you disable half floats using the added project setting?

**Comment by volzhs** [comment]
@clayjohn all settings are default.

**Comment by clayjohn** [comment]
@volzhs do you mind trying again with the disable_half_float setting?

**Comment by volzhs** [comment]
@clayjohn yeah. that made it work. I just read the description of this option.

![image](https://user-images.githubusercontent.com/8281454/96808543-fd555080-1453-11eb-8e02-0957d2d787ea.png)

**Comment by clayjohn** [comment]
@volzhs thanks for trying again! 

I will close this as it is fixed by #38318
