### ISSUE TITLE
Vulkan: GIProbe crashes when more than 64 subdiv used to bake

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#33337]
Windows 10 64 bits
Nvidia GTX 1060
Intel i7 8750H 16G RAM
Godot vulkan branch 20191104

Setting a GiProbe with more than 64 subdiv crashes when baking

steps:
.-create a scene 3D
.-add a GIProbe
.-add a Mesh, set it to anything (sphere)
.-set GIProbe subdiv to 128
.-bake GIProbe, this crashes

<details>
  <summary>Log</summary>

```
Godot Engine v4.0.devel.custom_build.a39cd6916 - https://godotengine.org
ERROR: VulkanContext::_debug_messenger_callback: WARNING : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 000002820AF3B350

   At: drivers\vulkan\vulkan_context.cpp:125
VK_KHR_incremental_present extension NOT AVAILABLE

VK_GOOGLE_display_timing extension NOT AVAILABLE

Vulkan physical device creation success o_O
uniform total: 0
uniform total: 0
uniform total: 0
compilation success

Editing project: C:/Users/Sistemas/Documents/Godot/projects/VK_prueba00 (C:::Users::Sistemas::Documents::Godot::projects::VK_prueba00)
Godot Engine v4.0.devel.custom_build.a39cd6916 - https://godotengine.org
ERROR: ShaderRD::~ShaderRD: 3 shaders of type SceneForwardShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type GiprobeDebugShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type GiprobeShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: RasterizerCanvasRD::~RasterizerCanvasRD: Some texture bindings were not properly freed (leaked canvasitems?
   At: servers\visual\rasterizer_rd\rasterizer_canvas_rd.cpp:2525
ERROR: ShaderRD::~ShaderRD: 1 shaders of type CopyShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type TonemapShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type SkyShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type CubemapRoughnessShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: ShaderRD::~ShaderRD: 1 shaders of type GiprobeSdfShaderRD were never freed
   At: servers\visual\rasterizer_rd\shader_rd.cpp:490
ERROR: 3 RID allocations of type 'struct RasterizerStorageRD::Material' were leaked at exit.
ERROR: 3 RID allocations of type 'struct RasterizerStorageRD::Shader' were leaked at exit.
WARNING: RenderingDeviceVulkan::_free_rids: 2 RIDs of type 'StorageBuffer' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::_free_rids: 4 RIDs of type 'UniformBuffer' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::_free_rids: 2 RIDs of type 'Framebuffer' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::_free_rids: 1 RIDs of type 'Sampler' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7231
WARNING: RenderingDeviceVulkan::finalize: 2 RIDs of type 'Texture' were leaked.
     At: drivers\vulkan\rendering_device_vulkan.cpp:7374
ERROR: VulkanContext::_debug_messenger_callback: WARNING : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 00000225093CA150

   At: drivers\vulkan\vulkan_context.cpp:125
VK_KHR_incremental_present extension NOT AVAILABLE

VK_GOOGLE_display_timing extension NOT AVAILABLE

Vulkan physical device creation success o_O
uniform total: 0
uniform total: 0
uniform total: 0
compilation success

uniform total: 0
uniform total: 36
ERROR: In Object of type 'EditorNetworkProfiler': Attempt to connect nonexistent signal 'break_request' to method 'ScriptEditorDebugger._profiler_seeked'.
   At: core\object.cpp:1452
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
uniform total: 124
erasing C:\Users\Sistemas\AppData\Roaming/Godot/projects/VK_prueba00-884b35e7c7ed6aaf7c9353f2682e14bc/filesystem_update4
subdiv: 6
ERROR: VulkanContext::swap_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
   At: drivers\vulkan\vulkan_context.cpp:1283
ERROR: VulkanContext::swap_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
   At: drivers\vulkan\vulkan_context.cpp:1283
ERROR: VulkanContext::_debug_messenger_callback: ERROR : VALIDATION - Message Id Number: 3 | Message Id Name: NVIDIA
        vkAcquireNextImageKHR: An attempt was made to acquire an image when the maximum number of images are already acquired.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_SWAPCHAIN_KHR, Handle 0000022510AD61A0

   At: drivers\vulkan\vulkan_context.cpp:125
ERROR: VulkanContext::prepare_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
   At: drivers\vulkan\vulkan_context.cpp:1219
ERROR: VulkanContext::swap_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
   At: drivers\vulkan\vulkan_context.cpp:1283
ERROR: VulkanContext::_debug_messenger_callback: ERROR : VALIDATION - Message Id Number: 3 | Message Id Name: NVIDIA
        vkAcquireNextImageKHR: An attempt was made to acquire an image when the maximum number of images are already acquired.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_SWAPCHAIN_KHR, Handle 0000022510AD61A0

   At: drivers\vulkan\vulkan_context.cpp:125
ERROR: VulkanContext::prepare_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
   At: drivers\vulkan\vulkan_context.cpp:1219
ERROR: VulkanContext::swap_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
   At: drivers\vulkan\vulkan_context.cpp:1283
ERROR: VulkanContext::_debug_messenger_callback: ERROR : VALIDATION - Message Id Number: 3 | Message Id Name: NVIDIA
        vkAcquireNextImageKHR: An attempt was made to acquire an image when the maximum number of images are already acquired.
```

</details>

***This last message repeats over and over

**Comment by qarmin** [comment]
For me this branch crashes a lot even when importing basics project because this is still WIP, so I would wait to alpha or merging branch with master to post issues.

**Comment by rubenjavier** [comment]
Juan is going on vacation for a month an asked if we (anyone who could) could compile and test GI because the vulkan branch was going to become master, and also the improvements on GI were "done", so its testing time. The branch hasnt been updated since this was done 3 days ago, so Im starting the tests today

**Comment by qarmin** [comment]
Then test as much as you like.
When you add a terminal output, place it between \``` because this look better
```
ERROR: VulkanContext::swap_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
At: drivers\vulkan\vulkan_context.cpp:1283
```
than:
ERROR: VulkanContext::swap_buffers: Condition ' err ' is true. returned: ERR_CANT_CREATE
At: drivers\vulkan\vulkan_context.cpp:1283

**Comment by rubenjavier** [comment]
Thanks for the advise ;)
will do

**Comment by ShyRed** [comment]
Might also want to have a look at https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f so you can put long sections of log between "spoilers". Totally optional, but helps with readability imho... :)

**Comment by bruvzg** [comment]
Can't reproduce it in on macOS 10.15.1.

Godot 5271e79896447208e83f960b3c4febe5e6584c40
AMD FirePro D300
MoltenVK 1.0.38, Vulkan SDK 1.1.126, Xcode 11.2

All available `GIProbe` subdiv options work, console outputs only `subdiv: x` (where x is `6-9` depending on subdiv) without any errors (apart from the same `EditorNetworkProfiler` which is clearly irrelevant here and `~ShaderRD ... were never freed` errors on exit).

![Screenshot 2019-11-05 at 19 00 44](https://user-images.githubusercontent.com/7645683/68228854-d57c9b00-fffe-11e9-81bb-aaad04f2789f.png)

**Comment by qarmin** [comment]
On Ubuntu 18.04 I don't have a crash, but only integer overflow:
```
servers/visual/rasterizer_rd/rasterizer_scene_rd.cpp:1799:46: runtime error: signed integer overflow: 67108864 * 64 cannot be represented in type 'int'
servers/visual/rasterizer_rd/rasterizer_scene_rd.cpp:1821:45: runtime error: signed integer overflow: 67108864 * 64 cannot be represented in type 'int'
```

**Comment by bruvzg** [comment]
```
ERROR: VulkanContext::_debug_messenger_callback: WARNING : GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.

        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 00000225093CA150

   At: drivers\vulkan\vulkan_context.cpp:125
```

It might be related to the old version of the built-in Vulkan loader Godot uses (IIRC it's unable to correctly detect some newer Windows 10 drivers), since https://github.com/KhronosGroup/Vulkan-Loader/issues/215 is resolved we should update it to 1.1.126.

**Comment by rubenjavier** [comment]
OK
1st: can bake now up to 512 on windows
2nd: found various reasons why baking GI can crash

I will make a list for future documentation

Reasons I have found GI baking can crash:
.-you dont have at least one Mesh with "Geometry->Use In Baked Light" enabled
.-your only Mesh with "Geometry->Use In Baked Light" and the GIProbe are child of different Nodes
.-the scene crashed baking previously and you dont remove GIProbe->Data and also dont delete the .res file trying to overwrite it

Steps to allways bake correctly
.-Have at least one Mesh with  "Geometry->Use In Baked Light" enabled (this would be static geometry for your level)
.-Have GIProbe and your static geometry as childs of the same Node
.-If you are unsure of the last baking, remove data from GIProbe->Data (use Clean), and also delete the .res file with the GIProbe data, dont overwrite it

Im gonna open an issue about the different nodes, just in case this was not the intended behaviour

Thats it, happy GI everyone

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
