### ISSUE TITLE
TextEdit: scrolling broken with Wrap Enabled unless empty line at end

### ISSUE THREAD

**Issue by finchMFG** [godotengine/godot#33509]
**Godot version:**
v3.2.alpha.calinou.dc114fa2e

**OS/device including version:**
OS: Ubuntu 19.04 x86_64 
Kernel: 5.0.0-13-generic 
WM: i3 
CPU: Intel Celeron N3450 (4) @ 2.200GHz 
GPU: Intel Device 5a85 
Memory: 2634MiB / 5351MiB 

**Issue description:**
TextEdit scrolling only works if you have a blank line at the end. This is most prominent with a single paragraph. When scrolled to the bottom of the text, attempting to scroll up does not show earlier text, only the last line. This issue is solved by adding a blank line at the end, though this is not ideal.

**Steps to reproduce:**
1. Create new TextEdit node
2. Turn on text wrap
3. Insert large amount of text ( like Lorem Ipsum )
4. Ensure there is no blank line at the end
5. Scroll to bottom of TextEdit node
6. Attempt to scroll back up
7. Observe only the last line displays on the screen

Workaround:
1. Add blank line at end of document
2. Scroll to bottom of TextEdit
3. Attempt to scroll back up
4. Observe scrolling now works as intended

**Minimal reproduction project:**
[TextEditBug.zip](https://github.com/godotengine/godot/files/3828163/TextEditBug.zip)

Thanks Godot team and contributors for everything you do! :beers:

**Comment by akien-mga** [comment]
Sounds like an issue which was fixed already, can you try a more recent build?

**Comment by finchMFG** [comment]
I can confirm the bug is still present as of last nights daily build:
```v3.2.beta.calinou.28294b1f1```

**Comment by finchMFG** [comment]
Closing because #32229 appears to be the same issue and #33492 did indeed fix it. After compiling from `master` the issue is no longer present. It appears that the merge did not make it in time to be incorporated in Calinous' daily build.

Thanks team!
