### ISSUE TITLE
GLES2 shading issue

### ISSUE THREAD

**Issue by kaadmy** [godotengine/godot#33633]
**Godot version:**

Godot 3.2 beta 1, GLES2 renderer

**OS/device including version:**

Motorola G4 (Android 7)

**Issue description:**

Serious fragment shading issues on surfaces.

![GLES2 shading issue](https://cdn.discordapp.com/attachments/575907327052480515/644738773837545502/Screenshot_20191114-192135.png)

**Steps to reproduce:**

1. Create a GLES2 project
2. Add a `MeshInstance` with a default sphere shape
3. Give the `MeshInstance` a material with very low roughness (I used 0.06, any value will work but lower roughnesses have more visible issues)
4. Place a camera very close to the sphere (As close as you can, keeping the sphere on screen)
5. Export for Android and run on your device

**Minimal reproduction project:**

[gles2_fprec.zip](https://github.com/godotengine/godot/files/3849731/gles2_fprec.zip)

**Comment by kaadmy** [comment]
There is already an [open issue](https://github.com/GodotVR/godot_oculus_mobile/issues/68) for this in the Godot Oculus mobile repository, but since I can reproduce it on a regular Android device the issue is more relevant here.

**Comment by clayjohn** [comment]
CC @NeoSpark314

**Comment by NeoSpark314** [comment]
This is related also to https://github.com/godotengine/godot/issues/32813 (and https://github.com/GodotVR/godot_oculus_mobile/issues/60)

This is a floating point precision issue due to the fact that `medp` is using 16bits. Some more details are in the oculus mobile issue https://github.com/GodotVR/godot_oculus_mobile/issues/68 including a small performance benchmark of enabling high precision for all computations on the oculus quest. @clayjohn suggested in a discussion on discord that the agreed solution is providing a project setting to enable high precision. 
I will look into creating a PR for this.

**Comment by avril-gh** [comment]
look at the spotlight shadows images in https://github.com/godotengine/godot/issues/33551

**Comment by kaadmy** [comment]
I just tried forcing high precision locally (same method as the PR above), and this issue still persists, albeit in a slightly different form.

![GLES2 high precision still broken](https://cdn.discordapp.com/attachments/575907327052480515/644993692750446622/Screenshot_20191115-121358.png)

**Comment by NeoSpark314** [comment]
@kaadmy can you try disabling in the project quality settings the mobile approximations like shown below?:

![Screenshot from 2019-11-15 21-57-04](https://user-images.githubusercontent.com/1610621/68975208-ef825e80-07f2-11ea-92b5-51033b12fb57.png)

**Comment by NeoSpark314** [comment]
@kaadmy I was able to reproduce the issue now also on my oculus quest. Changing the settings did not help. The precision fix in the PR gets rid of the noise; but the dark reflections seem to be an additional issue not fixed by the precision increase.

**Comment by kaadmy** [comment]
Same issue occurs here, I've also tried disabling all shading options to no avail. I'll try fixing it locally since I can easily reproduce the issue.

**Comment by NeoSpark314** [comment]
I think I found the cause of the issue: Mip Map level 1 of the prefiltered sky environment map is black!; all other mip levels look correct: here is a render doc trace from the quest with the mip levels visualized:
Mip 0, 1, 2:

![Screenshot from 2019-11-15 22-32-13](https://user-images.githubusercontent.com/1610621/68977160-e21ba300-07f7-11ea-9add-c82df8ea9fcd.png)

![Screenshot from 2019-11-15 22-32-18](https://user-images.githubusercontent.com/1610621/68977165-e5169380-07f7-11ea-8fe3-eccbe8c8e714.png)

![Screenshot from 2019-11-15 22-32-21](https://user-images.githubusercontent.com/1610621/68977168-e778ed80-07f7-11ea-8eef-714d431ae7cf.png)

**Comment by kaadmy** [comment]
I tried disabling mipmap generation (always source from panorama texture and don't blur) and I seem to get much better results:
![GLES2 lowp partial fix](https://cdn.discordapp.com/attachments/575907327052480515/645026161612816385/Screenshot_20191115-142321.png)

This is with the default precision (mediump), highp looks very similar but still has some shading discrepancies.

**Comment by Calinou** [comment]
@NeoSpark314 Sorry to interrupt, but since you seem knowledgeable about mipmapping, would you know if it's possible to fix #33519 without too much trouble?

**Comment by akien-mga** [comment]
Fixed by #33646.

**Comment by eastrd** [comment]
Hi, this issue still seems to persist under both 3.2.2 and 3.3.3, tested on Oculus Quest 2.
![image](https://user-images.githubusercontent.com/13502460/96418114-07056b00-123e-11eb-9b57-d0709644cf5c.png)

![image](https://user-images.githubusercontent.com/13502460/96418140-0e2c7900-123e-11eb-9ba7-b700a4d0dcf9.png)

**Comment by Zireael07** [comment]
Open a new issue, as it's likely something in the VR code.

**Comment by akien-mga** [comment]
@eastrd It's fixed in 3.2.3 (3.2.2 was released long before this issue was closed).
You have to enable a setting to use it, see #33646.

**Comment by Filippopotamus** [comment]
The issue still remains in 3.2.3, even when setting the high precision float flag. It goes away if I change the WorldEnvironment to be `Color`. But if it is set to `Sky` or `Sky+Color`, the issue is still present.

**Comment by akien-mga** [comment]
Please open a new issue with a reproduction project.

**Comment by Filippopotamus** [comment]
@akien-mga issue created: https://github.com/godotengine/godot/issues/43667
