### ISSUE TITLE
Tween does not finish with the final value due to precision loss in conversion of big integers to float

### ISSUE THREAD

**Issue by dekaravanhoc** [godotengine/godot#33813]
**Godot version:**
3.1.1 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Tween does not end with final value

**Steps to reproduce:**

- Create a Linear Tween to call a method with a value from 99999999 to 999999999
- Method prints the values
- The final printed value will be larger than 999999999

Note: This is also the case for the printed starting value. Where a larger number is to be expected but a smaller number not. 

Note2: Time does not influence the result.

Note3: I also saw this problem with floats, where the final value was also not the expected one, but with some rounding issues. It only seems to work correctly on floats with a larger number of decimals

**Minimal reproduction project:**
[tween_values.zip](https://github.com/godotengine/godot/files/3882320/tween_values.zip)

**Comment by Xrayez** [comment]
Is it any different if you set `Playback Process Mode` to `Physics`? This might help with timing to be more deterministic. Floats are expected to have rounding issues due to error accumulation. Perhaps some parts use mixed `float/double` internally so that conversion loses precision as well?

**Comment by dekaravanhoc** [comment]
I added a Project to reproduce it. It does not matter in Process Mode the Tween runs and how long it goes. The problem is with the last output. It is to be expected the last output is the final value, but it is not. Also I just use the linear transition, where it is to be expected the numbers in between the start and final value are not larger/smaller then the final/starting value.
Here is the output of the example project:
[output.txt](https://github.com/godotengine/godot/files/3882330/output.txt)

**Comment by Keetz** [comment]
Duplicate issue with some more info: #40237 
This issue is indeed caused by using float/double internally by the tween.

**Comment by akien-mga** [comment]
As described in #40237, the value is converted to `real_t`, which is `float` currently in Godot 3.2.x.

There's plan to add support for double precision in Godot 4.0 which might alleviate this issue, but a better fix would be to see how to have a dedicated code path to treat integer values as such.

**Comment by akien-mga** [comment]
@KoBeWi Was this fixed in your Tween rewrite?

**Comment by KoBeWi** [comment]
No, the interpolation code didn't change for the most part, so it's still reproducible. Here's some test code:
```GDScript
@tool
extends EditorScript

func twee(v, o):
	o.set_meta("tw", v)

func _run() -> void:
	print(self)
	var ref = RefCounted.new()
	var tween = get_editor_interface().create_tween()
	tween.tween_method(twee.bind(ref), 99999999, 999999999, 1)
	await tween.finished
	print(ref.get_meta("tw"))
```
Compiling with `float=64` fixes the issue though.

There's however a simple fix I could try for 32-bit floats.
