### ISSUE TITLE
AtlasTexture does not work with some Objects and Ressources

### ISSUE THREAD

**Issue by dekaravanhoc** [godotengine/godot#33855]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10

**Issue description:**
Using the AtlasTexture on some Objects and Ressources does not use the selected region but the whole image. I found this to be the case with AnimatedTexture and CPUParticles2D, but I am prety shure, this is are not the only two cases. 

**Steps to reproduce:**

- Create a AnimatedTexture or CPUParticles2D
- Use a AtlasTexture as the Texture
- The whole AtlasTexture is used instead of the selected Region

Note: The AtlasTexture is shown correctly in the Editor

**Minimal reproduction project:**

**Comment by genericFJS** [comment]
I get the same issue with Godot 3.2 beta 2 on Windows 10.

I created a minimal project:
[AtlasTextureIssue.zip](https://github.com/godotengine/godot/files/3883968/AtlasTextureIssue.zip)

Reproduce by:
- Add frames to spriteframes via sprite sheet

![1_spritesheet](https://user-images.githubusercontent.com/3334361/69499177-ad8ea200-0eef-11ea-8aba-3a4723bf9760.png)
- Select atlas texture with only green part of image 

![2_atlastexture](https://user-images.githubusercontent.com/3334361/69499184-bed7ae80-0eef-11ea-9397-50e2a0aa4758.png)
- Select some (green) frames

![3_frames_green](https://user-images.githubusercontent.com/3334361/69499194-e62e7b80-0eef-11ea-9f34-970271f35f21.png)
- Observe unexpected red frames
![4_animationframes_red](https://user-images.githubusercontent.com/3334361/69499227-44f3f500-0ef0-11ea-97d6-c30fa748aacb.png)

**Comment by clayjohn** [comment]
There is a PR already to fix this for CpuParticles2D already. https://github.com/godotengine/godot/pull/32496

**Comment by arkology** [comment]
I really think that all these problems are due to bad design/implementation of AtlasTexture. For example: https://github.com/godotengine/godot/issues/25895. Also it has bugs with progress bar node.

**Comment by KoBeWi** [comment]
AFAIK, AnimatedTexture will never support atlases due to how it works, but in exchange it has an excellent performance. Also docs state that it's not supported, so this case is ok.

As for others, we should probably find all places where AtlasTextures don't work and either fix this or document that it's impossible (if it's impossible ofc).

**Comment by dekaravanhoc** [comment]
Were do the docs state it is not supported? It only states the textures should be the same size or they will be cropped.
And why should it not work? AnimatedTexture just animates the provided textures and AtlasTexture should just provide this texture. AnimatedTexture does not work with Atlases, thats wthat the AtlasTexture should be for.
I think arkology is right, that the implementation of AtlasTexture seems to be the problem here and in all the other cases.

**Comment by KoBeWi** [comment]
> Where do the docs state it is not supported?

https://docs.godotengine.org/en/latest/classes/class_animatedtexture.html#description
Last paragraph. Might be not in 3.1.
> And why should it not work?

See the reduz's comment here: https://twitter.com/reduzio/status/1018869909781180427

> I think arkology is right, that the implementation of AtlasTexture seems to be the problem here

Which doesn't mean it can be implemented in a better way. Especially without sacrificing performance.

**Comment by dekaravanhoc** [comment]
Ah great, thank you. I'm using stable and the docs in that version, so I do not get anything mixed up - also thanks for the twitter post. 
If it does not work together, thats fine by me. Just felt like a bug, as it is selectable and seem to work except for the result - and also for the other places where AtlasTexture does not seem to work as intended. 
I am with you on the performance part, if it means worse performance overall. If it just means worse performance with AtlasTextures than with eg. StreamedTextures, I dont see the problem - as it is no performance at all at the moment. But as AnimatedTextures are a special issue and not connected to the rest, I think ressources should be spend elsewhere - as the pain is also not that big on this one, at least for me.

**Comment by geekrelief** [comment]
Wow I just wasted an hour on this. The limitation of AnimatedTexture not being able to use AtlasTexture should be made much clearer in the docs.  Right now it's the last sentence in Description.  There should be a section labeled Warning or Limitations stating this.

**Comment by belzecue** [comment]
AtlasTexture certainly doesn't behave as one would expect.  I suspect I'm not using it correctly in the way described below, but if that's the case then there should be an error message or the behavior should not be permitted.

1. Create an AtlasTexture resource file and configure a  clipped TextureRegion, which correctly shows in the Inspector as only the clipped part of the full texture.

2. Create a quad mesh, add a SpatialMaterial, and drop the AtlasTexture resource file you created in Step 1 onto the material's texture param.  In the Inspector, the texture param only displays the clipped texture region as you would expect.  The assumption at this stage is, the material will only use the texture region from the AtlasTexture.

3. But the quad mesh texture actually displays the entire texture atlas, not the clipped texture region used in the AtlasTexture, which is unexpected because the texture param also correctly displays only the clipped texture region.

![Screenshot at 2021-09-11 18-03-05](https://user-images.githubusercontent.com/1931303/132944527-cc9b3b6f-0d0b-4c8f-af2c-6f4ecd59179b.png)

**Comment by Calinou** [comment]
AtlasTexture is only meant for use in 2D, not 3D.

**Comment by Shadowblitz16** [comment]
Godot should support any sort of texture nested into any sort of texture
Either support it or get rid of the animated texture resource and find us a alternative.
Godot doesn't need anymore edge cased, right not it feels like its nothing but edge cases.

**Comment by TamerSoup625** [comment]
I also had problem when trying to use AtlasTexture inside a ShaderMaterial.
I fixed it by creating my own version of it as a child of ImageTexture:
```gdscript
tool
extends ImageTexture
class_name ImageAtlasTexture


### NOTE: This script is far from being used as part of a plugin
### It basically gets a Texture's Image, uses Image.get_rect() on it and sets is as the image


export var atlas: Texture setget set_atlas
export var region: Rect2 setget set_region


func _init():
	update_image()


func set_atlas(val):
	atlas = val
	if atlas and not atlas.is_connected("changed", self, "update_image"):
		var __ = atlas.connect("changed", self, "update_image")
	update_image()
	emit_changed()


func set_region(val):
	region = val
	update_image()
	emit_changed()


func update_image():
	if !atlas: return
	if !region.size: return
	var p_flags = flags
	# Here is where the magic happens
	var p_image = atlas.get_data().get_rect(region)
	create_from_image(p_image)
	flags = p_flags
```
I've tested it and it works with materials, AnimatedTexture and Sprite3D and should work on everything else by the design of it (However I had to reload project for it to work on AnimatedTexture), I may turn this into a plugin.
The way I would fix this issue is by keeping the normal AtlasTexture but creating another version of it that is more focused on flexibility than performance, naming it to something like `VersatileAtlasTexture`, and maybe rename the current one to something like `FastAtlasTexture` so the difference between the `*AtlasTexture`s is clearer.

**Comment by myyk** [comment]
This issue seems still present on GPUParticles2D with AtlasTexture in Godot 4.1.

**Comment by hamitozdemir** [comment]
Still present in Godot 4.2.2. As mentioned even if you edit region to display a certain part of the AtlasTexture, it just doesn't apply the textures to the object surface. Doesn't work on QuadMesh or BoxMesh. Also possibly related (?) changing UV1 offset doesn't do anything, at all.

![godot windows opt tools 64-old8_2024-05-11_19-30-13](https://github.com/godotengine/godot/assets/12991847/c868597a-730a-4e7e-8ccd-21a104575eff)

**Comment by fleetfoxx** [comment]
Still present in Godot 4.4 rc1 when using Decals.

![Image](https://github.com/user-attachments/assets/8209bcda-6345-4405-ba71-33cb29b72c6a)

**Comment by lucastucious** [comment]
Still happening in 4.5 beta1

<img width="1237" height="851" alt="Image" src="https://github.com/user-attachments/assets/78e5e125-838e-4c01-b83e-aaae468a5e9b" />

**Comment by 45DegreeAngl** [comment]
https://github.com/godotengine/godot/pull/123128

Just made this PR hoping to solve some of the problem, made it so that Nested Atlas Textures work with the particle2D nodes (CPU and GPU)
