### ISSUE TITLE
Glow on GLES2 does not work on Windows 7 Intel integrated GPU

### ISSUE THREAD

**Issue by chalcosoma** [godotengine/godot#34055]
**Godot version:**
3.2 Beta 2
**OS/device including version:**
Windows 7 x64 Intel HD Graphics 3000
**Issue description:**
The glow does not work on the viewport and on play mode neither.
**Steps to reproduce:**
Create a project as the screenshot

![2019-12-01 20_17_02](https://user-images.githubusercontent.com/20130832/69922133-38cfe080-1478-11ea-8c12-4fe385172ca4.jpg)

**Minimal reproduction project:**
The scene is the same as the screenshot

**Comment by chalcosoma** [comment]
Here is a warning I didn't see when I was posting the error.
![2019-12-01 20_38_12](https://user-images.githubusercontent.com/20130832/69922402-b98fdc00-147a-11ea-8b9a-e29a54c65fca.jpg)

**Comment by clayjohn** [comment]
Could be the same as https://github.com/godotengine/godot/issues/33825 which was fixed by https://github.com/godotengine/godot/pull/33844

**Comment by chalcosoma** [comment]
I downloaded the nightly build from here: https://hugo.pro/projects/godot-builds/
and the problem persists.

**Comment by chalcosoma** [comment]
I forgot to show the material settings. It is here:
![2019-12-01 20_59_32](https://user-images.githubusercontent.com/20130832/69922716-a5011300-147d-11ea-9553-80a27f81c050.jpg)

**Comment by clayjohn** [comment]
I have a feeling that something like 

https://github.com/godotengine/godot/blob/e64a663c59141f972345852f0bce613e3f13dd3a/drivers/gles2/rasterizer_storage_gles2.cpp#L5213-L5217

Needs to be added to
https://github.com/godotengine/godot/blob/e64a663c59141f972345852f0bce613e3f13dd3a/drivers/gles2/rasterizer_storage_gles2.cpp#L4917

**Comment by clayjohn** [comment]
@chalcosoma If I send you some code, can you rebuild the engine and test if the change helps?

**Comment by chalcosoma** [comment]
@clayjohn Yes, I will try. It will be the first time I compile the engine but no problem.

**Comment by chalcosoma** [comment]
@clayjohn  I'm compiling the engine now to get comfortable with this. When you send me the code I will be ready to re-compile and test.

**Comment by clayjohn** [comment]
@chalcosoma Great! Build from [this](https://github.com/clayjohn/godot/tree/GLES2-mip-buffers-debug) branch/fork and let me know what the result is when you run your scene. It should print out what form of error occurs that is keeping the buffer from completing.

**Comment by chalcosoma** [comment]
@clayjohn I compiled and all the glow blend modes are working now and the engine does not show any error related to glow. But I noticed another error:

![2019-12-09 17_10_50](https://user-images.githubusercontent.com/20130832/70469026-01c88300-1aa7-11ea-8429-58439a3cd249.jpg)

**Comment by clayjohn** [comment]
@chalcosoma thanks for building and checking! Glad to hear it's working for you. 

As for that second error. It is just reporting that your hardware does not support MSAA. Devices that support GLES2 arent required to support MSAA as MSAA is technically a GL 3+ feature. Your hardware is just so old that it doesn't support MSAA. So that is not a bug.
