### ISSUE TITLE
[WASM] IndexDB dependency breaks app if run under latest Tor alpha: [IndexedDB not available: A mutation operation was attempted on a database that did not allow mutations.]

### ISSUE THREAD

**Issue by RobertoMalatesta** [godotengine/godot#34102]
**Godot version:**
3.1.2 / 3.2b1 / git-pulled latest as well

**OS/device including version:**
app built as web wasm / testing on Tor 9.5a2 desktop / (with godot on ubuntu server 18.04)

**Issue description:**

**Steps to reproduce:**
- export any application as html project
- publish it on any site
- access it with Tor Browser 9.5a2 (first one that has wasm and webgl enabled support)
- the app will crash with the error:
`IndexedDB not available: A mutation operation was attempted on a database that did not allow mutations.`

(The app will work with Brave Browser Tor impl. since Brave is more relaxed).

 

**Minimal reproduction project:**
Here: [If it works it shows a button](https://www.exedraos.com/minimal_repro_wasm/)

It takes some time to load. More than the usual abysmal since is a debug build.

For the impatient here there are two 

**Screenshots**

On Tor alpha 2 :  
![image](https://user-images.githubusercontent.com/11835025/70155543-ba12b780-16b2-11ea-9889-84603bca0dd1.png)

On Brave + Tor network:
![image](https://user-images.githubusercontent.com/11835025/70155187-175a3900-16b2-11ea-8359-fd988b916ec3.png)

**Volunteering and other considerations**

IndexedDB writes on disk, so the Tor Project has severely limited it.
Besides, I don't see a real reason to use it as mandatory in a web-based application.
I know the Godot devs are overwhelmed with issues to fix and features to implement so,
time permitting, I'd like to give a hand.

Just a start: is there any document with the exports modules rationale or some pointers to where in the code export modules are implemented?

Thank you for the time and the fantastic work!

Roberto

**Comment by akien-mga** [comment]
That's a relatively niche use case, and I'd tend to say that it works as intended, huge JS games in the browser is definitely something that privacy-minded Tor users should avoid.

Still, it should be possible to have things work without filesystem access indeed, so IDBFS could be made opt-out. Relevant code is here:
https://github.com/godotengine/godot/blob/73fb08289af1260669a3ce118b9866a11c06a0eb/platform/javascript/javascript_main.cpp#L37-L49

As we can see IDBFS support is already optional, but the way Tor blocks it is probably not handled gracefully.

**Comment by RobertoMalatesta** [comment]
On a quick inspection of index.js:
IDBFS is tested against undefined but  i seem to recall  Tor supporting some sanitized form of it.
![image](https://user-images.githubusercontent.com/11835025/70165188-c141c180-16c2-11ea-81ff-aff3eba21642.png)

(Tor console:)
![image](https://user-images.githubusercontent.com/11835025/70165363-167dd300-16c3-11ea-9b60-0308258fe1b9.png)

Aesthetically it seems the same of Firefox 73:
![image](https://user-images.githubusercontent.com/11835025/70165720-ade32600-16c3-11ea-8a53-c8c1bdccbc3a.png)

ASAP I'll try bruteforcing a NULL return instead of the check to see if it proceeds.
One thing to consider is that Tor just introduced wasm defaulted yes in the latest alpha.
Then can revert their mind in the release version, or change the logic altogether.
It happened for asm.js (*) some time ago: it was in then out then in again.

(*) Even more nicher: has anyone compiled godot for asm.js ? A couple of months ago I succeeded in compiling and running the entire engine for webassembly with some minimal effort so an asm.js could be in theory feasible (taking out maybe some pieces).

-- R

**Comment by Calinou** [comment]
> (*) Even more nicher: has anyone compiled godot for asm.js ? A couple of months ago I succeeded in compiling and running the entire engine for webassembly with some minimal effort so an asm.js could be in theory feasible (taking out maybe some pieces).

This was supported in Godot 2.x, but has been removed in Godot 3.0 thanks to WebAssembly support becoming widespread enough. That said, someone made a [pull request to reintegrate asm.js support](https://github.com/godotengine/godot/pull/31383) due to Safari iOS' WebAssembly support being problematic.

**Comment by RobertoMalatesta** [comment]
Hi @Calinou ,

> This was supported in Godot 2.x

I remember that. Somewhere I have a 2d test project on it.

> Safari iOS' WebAssembly support being problematic.

Agreed. Safari is the problematic child of the WWW, but even more (and remaining in the rotten corpses league) I was thinking about IE11.
IE11 will be supported until 2025 at least, and it's still in use inside banking institutions and industries.
The point is that Godot is such a wonderful tool that some of us not involved in game development see it as a fantastic tool for almost every type of application.

As a side note asm.js could be an escape plan for the day when again some serious sec flaw will be discovered in wasm.

--R

**Comment by Calinou** [comment]
> The point is that Godot is such a wonderful tool that some of us not involved in game development see it as a fantastic tool for almost every type of application.

We think there are tools more suited than Godot to make Web applications, so it's not a priority for us :slightly_smiling_face:

**Comment by RobertoMalatesta** [comment]
@Calinou

>I wouldn't see it as a priority

Indeed it's not.

short somehow OT:

> See also A Business Case for Dropping Internet Explorer.

Fun! It seems taken straight from the Rant Department! 
Even funnier:
[The big winner was, shockingly...](https://www.zdnet.com/article/in-the-new-browser-war-microsoft-edge-is-losing-internet-explorer/)


Before we get rid of IE11 in 2025 (maybe), two other major browsers will drop stone dead, or will be emasculated like Edge.

--R

**Comment by akien-mga** [comment]
@Faless I guess this is related to #39495 and might have been fixed similarly?

**Comment by Faless** [comment]
@akien-mga partially, Tor browser still doesn't work since it does not support AudioContext.
I don't really think we can support it given all the limitation it has (and will have). WebAssembly is not even available unless you use the `standard` (lowest) security option (which is not the default).

**Comment by Calinou** [comment]
@Faless We should still attempt to fail gracefully in this case (if possible). Other than that, I don't think we can support HTML5 exports in Tor Browser either.

**Comment by Faless** [comment]
Fixed via #39495 and #40018 .
