### ISSUE TITLE
[Bullet] KinematicBody: move_and_slide_with_snap intersection edges problem

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#34436]
**Godot version:**
3.2 beta 4

**OS/device including version:**
Zorin OS 15 (Ubuntu 18.04)

**Issue description:**
Wen moving from a staticbody to another (as a floor) is like the kinematicbody goes trough a bump on the intersection edges of the staticbodies. This only happens with move_and_slide_with_snap.

**Steps to reproduce:**
See project.

**Minimal reproduction project:**
[MASWS-Problem.zip](https://github.com/godotengine/godot/files/3979734/MASWS-Problem.zip)

**Comment by Janders1800** [comment]
I should add this does not happens on 3.1

**Comment by jamie-pate** [comment]
https://streamable.com/mdr3r

**Comment by madmiraal** [comment]
This is also fixed with #35945 and its 3.2 version #37498.

**Comment by Janders1800** [comment]
But those PRs are not merged, will they be to 3.2.3-beta-2?

**Comment by hoontee** [comment]
@Janders1800 No, he's just saying that the bug is confirmed fixed in the PRs themselves. They're currently awaiting approval.

**Comment by pouleyKetchoupp** [comment]
Can be still reproduced in 3.2.4 beta 5, but occurs only when using Bullet Physics (default settings). Switching to Godot Physics 3D fixes the issue.

**Comment by akien-mga** [comment]
Fixed by #34436.
