### ISSUE TITLE
GLES2 CPU-Particles inconsistent lighting

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#34877]
**Godot version:**
3.2 beta 5

**OS/device including version:**
Zorin OS 15

**Issue description:**
Depending on the angle of the camera, CPU-Particles change lighting influence.
![ParticlesBug](https://user-images.githubusercontent.com/27329423/71856471-5bdb5900-30e4-11ea-8a9f-f449d02c47c8.gif)
Its most noticeable with billboard activated for the material, but it also happens if billboard is disabled.

**Steps to reproduce:**
- Add a light source
- Add CPU-Particles

**Minimal reproduction project:**
[ParticlesBug.zip](https://github.com/godotengine/godot/files/4028201/ParticlesBug.zip)

**Comment by clayjohn** [comment]
Looks like it may be the same as https://github.com/godotengine/godot/issues/17542

**Comment by Janders1800** [comment]
Done some more digging, this only happens to overlapping meshes, which I think it is more a thing on how GLES2 renders that a bug, feel free to close this issue if this is the case.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
I tried the attached project and looks ok, not sure what is the issue.

**Comment by Janders1800** [comment]
I suspect is a case of Z fighting. As I commented before I don't think is a bug, but I'm not an expert.

**Comment by KoBeWi** [comment]
> As I commented before I don't think is a bug

So should be fine to close. Doesn't seem like anyone else faced this issue.
