### ISSUE TITLE
glBufferData causing lag in GLES3

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#35311]
**Godot version:**
3.0 to 3.2

**OS/device including version:**
Windows 10 1909
Radeon VII - Adrenalin 20.1.1

**Issue description:**
GLES3 projects running on a Radeon VII experience infinitely increasing memory usage that eventually resets upon OpenGL garbage collection and causes a lag spike.
Does not occur in the editor.

The issue arises from `glBufferData` calls in three key locations:
`RasterizerCanvasGLES3::reset_canvas, line 2002`
`RasterizerSceneGLES3::_setup_environment, lines 2696 and 2704`

![image](https://i.gyazo.com/46976c23ac72caaf8aca5fa71d8d8c56.gif)
![image](https://user-images.githubusercontent.com/5272529/72690620-ae087b00-3ae3-11ea-8555-f10e265eda8a.png)
![image](https://user-images.githubusercontent.com/5272529/72690495-8cf35a80-3ae2-11ea-86b6-b4f973c60f6a.png)

**Comment by hoontee** [comment]
Previously this issue was a part of #35264 but I found out that it's actually unrelated.

**Comment by hoontee** [comment]
Also see https://stackoverflow.com/questions/41422077/very-slowly-increasing-resetting-memory-in-c-and-opengl-vs-debugger

**Comment by clayjohn** [comment]
Looks like there's nothing we can do I guess. 

Is the memory consumption causing issues in your project?

**Comment by hoontee** [comment]
@clayjohn Yes, it's causing lag spikes.

**Comment by hoontee** [comment]
Interestingly this issue doesn't occur in the editor, and doesn't occur on GLES2 projects. What do you think could be the reason for that?

**Comment by hoontee** [comment]
@clayjohn I've identified three `glBufferData` calls that, once commented out, fix the memory issue:
`RasterizerCanvasGLES3::reset_canvas, line 2002`
`RasterizerSceneGLES3::_setup_environment, lines 2696 and 2704`

**Comment by clayjohn** [comment]
Does this occur in release builds or just in editor builds when running the project?

**Comment by hoontee** [comment]
@clayjohn Both release and editor.

**Comment by hoontee** [comment]
@clayjohn Replacing them with `glBufferSubData` calls didn't improve anything.

**Comment by lawnjelly** [comment]
See the comments here #33527 regarding the pros / cons of either orphaning or use of circular buffer of pre-allocated buffers and glBufferSubData, this may be relevant in terms of stalls etc. Also, how is 'OpenGL memory' being measured? Is this CPU side or GPU?

**Comment by hoontee** [comment]
@lawnjelly System memory, i.e. CPU side.

**Comment by hoontee** [comment]
I swapped my CPU from a Ryzen Threadripper 1950X to a Ryzen 9 3950X. Memory usage still increases indefinitely, but I no longer experience any lag spikes whatsoever. Could it be a bug related to first gen Threadripper's memory controller?

**Comment by clayjohn** [comment]
@hoontee maybe it was a caching issue that is solved by a larger CPU cache?

**Comment by hoontee** [comment]
Could also be the case. I'll do some additional testing when I'm able.

**Comment by hoontee** [comment]
Disabled the 2nd CCX which halves the available cache (64MB > 32MB.) Lag spikes still not present.

**Comment by hoontee** [comment]
The lag spikes reappeared today. I added a shader that used a lot of SCREEN_TEXTUREs and had `framebuffer_allocation` set to `3D Without Effects` in the project settings. The spikes went away when I set `framebuffer_allocation` to `3D`.

**Comment by clayjohn** [comment]
@hoontee that is extremely odd, the only different between the two options is that "without effects" allocated fewer textures (and can't handle effects). If anything it should be faster and less likely to lead to spikes like what you are seeing. 

I have a feeling it is something else that may have changed around the same time (maybe an OS update in the background you didn't notice, Windows 10 is bad for that).

At any rate, please keep us updated if anything changes

**Comment by lawnjelly** [comment]
Have we tried just calling
```
glBufferData(GL_UNIFORM_BUFFER, 0, 0, GL_DYNAMIC_DRAW);
```
before the new glBufferData call? Doubt it is that but just checking.

**Comment by lawnjelly** [comment]
> The lag spikes reappeared today. I added a shader that used a lot of SCREEN_TEXTUREs while `framebuffer_allocation` was set to `3D Without Effects` in the project settings.
> The spikes went away when I set `framebuffer_allocation` to `3D`.

When you say 'projects' in the original post, do you mean a blank project? Or was it a specific project?

The cost of using SCREEN_TEXTURE with different framebuffer formats may vary presumably if it has to copy and convert the frame buffer to a texture? (I don't know the _copy_screen code but presumably this must be true if the destination texture is a fixed format)

**Comment by hoontee** [comment]
@clayjohn
> I have a feeling it is something else that may have changed around the same time (maybe an OS update in the background you didn't notice, Windows 10 is bad for that).

Tested it again today, results still hold up.

@lawnjelly
> When you say 'projects' in the original post, do you mean a blank project? Or was it a specific project?

All projects; blank and not-so-blank.

I do have a small update. These new lag spikes occur much more frequently, about once every four seconds. They also seem to only drop one frame instead of two.

I think this is the same underlying memory issue as before, just in a different area. Switching to GLES2 fixes the new lag spikes as well.

**Comment by hoontee** [comment]
I'll just say that this is a driver issue that can't be fixed. Feel free to reopen if I'm wrong.
