### ISSUE TITLE
Softbody always spawns from world center [GLES2 only]

### ISSUE THREAD

**Issue by gyrosp** [godotengine/godot#35373]
**Godot version:** 3.2 RC 2

**OS/device including version:** Windows 10 / PC

**Issue description:** No matter where you place a Softbody, it always spawns at the center of the scene.

**Steps to reproduce:**
1. Place a Softbody somewhere in the scene
2. Launch

**Minimal reproduction project:**
[Soft Body.zip](https://github.com/godotengine/godot/files/4087383/Soft.Body.zip)

**Comment by akien-mga** [comment]
Confirmed, even when moving the parent Node to another location, the child SoftBody will be instantiated at `(0, 0, 0)`.

**Comment by nathanwfranke** [comment]
I've also had issues where I spawn the soft body ~200 meters away from the origin and the SoftBody mesh spawns at the origin and gets stuck like that

**Comment by ericrybick** [comment]
This does only happen if the project uses GLES2.

**Comment by akien-mga** [comment]
> This only happens if the project uses GLES2.

That's correct, though it's pretty surprising. I wonder how the rendering backend can influence physics and location this way. CC @clayjohn

**Comment by rulijoh** [comment]
New user of Godot here, getting familiar with some of the 3d features.

I know the fix was merged and the issue was closed over 5 months ago, but I'm seeing this very same bug with GLES2 softbody location in v3.2.stable.custom_build which is available in Ubuntu 20.04 LTS, as well as v3.2.2.stable.official Linux 64-bit build.

Is the minimal example included above really working for everyone else now?

**Comment by akien-mga** [comment]
The bug still seems reproducible indeed in 3.2.2-stable with the OP's MRP. CC @ericrybick.

**Comment by akien-mga** [comment]
Closing as duplicate of #41390 (more recent but has more debugging info).
