### ISSUE TITLE
Change MessageQueue to a page allocator to prevent overflow

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#35653]
**Godot version:**
Master (3cfb67e0f)

**OS/device including version:**
Any

**Issue description:**
As discussed a few times on IRC, and exemplified by many bug reports, our current fixed size for the Message Queue is problematic.

It currently defaults to `1024` (see `memory/limits/message_queue/max_size_kb`), and many users need to increase it to prevent overflow when handling a large amount of messages (which can happen easily in the editor when using e.g. large TileSets #29238 or Skeletons #35652).

As discussed with @reduz, Message Queue should be changed to use a page allocator so that its size can grow as needed, preventing overflows.

Situations which can cause a Message Queue overflow like #29238 or #35652 should however be fixed in the Inspector itself, as even increasing the MQ will just make things functional again, but it will still freeze a long time while populating all those controls.

**Comment by akien-mga** [comment]
For the reference, I fixed the outdated setting name in the error message with cab555bb, so from now on errors will be:
```
Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
```

**Comment by staddy** [comment]
My commit doesn't fix #35652 though.
`_call_function(target, message->target, args, message->args, message->type & FLAG_SHOW_ERROR);`
in MessageQueue::flush() corrupts memory; think it's not my fault, but not 100% sure.

**Comment by Xrayez** [comment]
How about increasing the default value to something like `2048` (while we wait for page allocator to get merged/implemented)? I've set this value to `2048` in my own project and I've never got to experience those errors again. I can only guess though. Just see the number of "duplicate" bug reports with the same underlying issue (unless you're interested in collecting the use cases this limitation has on people's projects).

**Comment by Atlinx** [comment]
Hey all I'm getting this error in 3.x, 
```
Failed method: MarginContainer:_update_callback target ID: 613365
Failed method: RichTextLabel:_update_callback target ID: 9387
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
...
TOTAL BYTES: 4194288
NULL count: 185
CALL : 174575
CALL _update_callback: 2
ERROR: Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
```
I'm not sure if this is related to this issue.

**Comment by wecybin** [comment]
Related to this issue I also posted in recently : https://github.com/godotengine/godot/issues/71929#issue-1553566775 

I started off with receiving :

> ERROR: Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.

After turning on SDFGI and a few other settings, then trying to change their quality to be lower in the project settings resulted in this + an out of memory exception windows error. I ended up increasing the kb to 10,000 and it seemed to fix it, however I started getting the issue I linked above resulting in this error printing on the console over and over while godot is unresponsive :

> ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
> at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:2280)
> ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
> at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2357)

So fast forward 2-3 days of this error popping up, I just created a master scene with a canvas layer and crashed. Now I am unable to open the project and I'm receiving the original memory limit error in the console.

**Comment by wecybin** [comment]
Little update:

Haven't received the previous errors in a while (fingers crossed), but now I am consistently hard crashing the editor when I open a specific scene I just created that's just a small map area, no scripts or environments or anything super fancy just some fairly low poly models. This error looks a bit different too, and seems to point towards things that aren't in the scene I'm trying to load. In fact, the scene I'm loading is just 3d with no 2d elements at all.

Here's the output in the console milliseconds before it crashes:

`ERROR: Failed method: VBoxContainer::_update_minimum_size. Message queue out of memory. Try increasing "memory/limits/message_queue/max_size_kb" in project settings.
 at: push_callablep (core/object/message_queue.cpp:120`

It gives me 4 total of those lines and the other 3 just have CanvasItem::_redraw_callback" instead of the vbox container update minimum size. I have one Canvaslayer node and it's in a completely different scene. I also have a vbox container in that other scene but not in the one I'm trying to open. 
Still messing around trying to fix this, but feel like it keeps randomly popping up in some form on every scene I work on. It's like one day I'll work on a scene and everything seems fine, then the next day it becomes a cursed object and I can't open it anymore.
