### ISSUE TITLE
Render "GLES2" does not draw Polygon2D on Android 

### ISSUE THREAD

**Issue by Valeryn4** [godotengine/godot#35772]
godot 3.1.2-stable

Android 6.0 (BF166_BOOST3-SE_L010)

If you use the "GLES2" render, then the Polygon2D is not drawn!
If you use the "GLES3" render, then everything works
Textures imported as Loss

GLES2:
![image of GLES2](https://i.imgur.com/rOo9p6c.jpg)

GLES3:
![image of GLES3](https://i.imgur.com/Pil2Gfr.jpg)

PS:
I need [it for beautiful animations](https://www.youtube.com/watch?v=4YfzkH1RHsg)

**Comment by Valeryn4** [comment]
scenes that use Polygon2D produce the following errors:

```
PS D:\Dev\Android\Sdk\platform-tools> adb logcat -s godot
--------- beginning of system
--------- beginning of crash
--------- beginning of main
01-31 18:18:08.860 27637 27656 I godot   : Loading Android module: org/godotengine/godot/GodotShare
01-31 18:18:08.886 27637 27656 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
01-31 18:18:09.028 27637 27656 I godot   : Godot Engine v3.1.2.stable.custom_build - https://godotengine.org
01-31 18:18:09.039 27637 27656 I godot   : OpenGL ES 2.0 Renderer: Mali-T720
01-31 18:18:09.775 27637 27656 D godot   : AdMob: init with content rating options
01-31 18:18:09.775 27637 27656 I godot   : AdMobAPI: Init adMob
01-31 18:18:09.779 27637 27656 I godot   : Global INFO: fps change to 60
01-31 18:18:11.560 27637 27656 E godot   : **ERROR**: R float texture not supported, converting to RGB8.
01-31 18:18:11.560 27637 27656 E godot   :    At: drivers\gles2\rasterizer_storage_gles2.cpp:162:_get_gl_image_and_format() - R float texture not supported, converting to RGB8.
01-31 18:18:11.560 27637 27656 E godot   : **ERROR**: R float texture not supported, converting to RGB8.
01-31 18:18:11.560 27637 27656 E godot   :    At: drivers\gles2\rasterizer_storage_gles2.cpp:162:_get_gl_image_and_format() - R float texture not supported, converting to RGB8.
01-31 18:18:11.733 27637 27656 E godot   : **ERROR**: RG float texture not supported, converting to RGB8.
01-31 18:18:11.733 27637 27656 E godot   :    At: drivers\gles2\rasterizer_storage_gles2.cpp:176:_get_gl_image_and_format() - RG float texture not supported, converting to RGB8.
01-31 18:18:11.734 27637 27656 E godot   : **ERROR**: RG float texture not supported, converting to RGB8.
01-31 18:18:11.734 27637 27656 E godot   :    At: drivers\gles2\rasterizer_storage_gles2.cpp:176:_get_gl_image_and_format() - RG float texture not supported, converting to RGB8.
01-31 18:18:11.739 27637 27656 E godot   : **ERROR**: R float texture not supported, converting to RGB8.
01-31 18:18:11.739 27637 27656 E godot   :    At: drivers\gles2\rasterizer_storage_gles2.cpp:162:_get_gl_image_and_format() - R float texture not supported, converting to RGB8.
01-31 18:18:11.739 27637 27656 E godot   : **ERROR**: R float texture not supported, converting to RGB8.
01-31 18:18:11.739 27637 27656 E godot   :    At: drivers\gles2\rasterizer_storage_gles2.cpp:162:_get_gl_image_and_format() - R float texture not supported, converting to RGB8.
```

**Comment by lawnjelly** [comment]
Info that might be useful, what Android devices are you testing this on, and does it work when you try in 3.2? (Or just a simple test case for Polygon2D that exhibits the problem, not necessarily your whole project)

**Comment by akien-mga** [comment]
Could you try with Godot 3.2? This might have been fixed in that release.

**Comment by Valeryn4** [comment]
> Не могли бы вы попробовать с Годо 3.2? Это могло быть исправлено в этом выпуске.

I have not migrated to version 3.2 yet. Because it is necessary to rebuild all the templates.
In a couple of days I can check.



> what Android devices
BOOST3-SE
Android 6.0 (BF166_BOOST3-SE_L010)

**Comment by Valeryn4** [comment]
> Could you try with Godot 3.2? This might have been fixed in that release.

There is a problem on 3.2

To repeat the error you need: Cut a part of the texture using "Polygon 2D"

**Comment by clayjohn** [comment]
@Valeryn4 I wonder if the issue is caused by the texture and not by the Polygon2D. From the errors you reported it looks like you are using a unique type of texture. 

Could you please try running the same scene with the texture removed to see if the issue is still present?

**Comment by Valeryn4** [comment]
> @Valeryn4 I wonder if the issue is caused by the texture and not by the Polygon2D. From the errors you reported it looks like you are using a unique type of texture.
> 
> Could you please try running the same scene with the texture removed to see if the issue is still present?

EXAMPLE PROJECT: https://github.com/Valeryn4/GodotPolygon2DBug

I am using PNG. Imported as "LOSS" or as "VRAM"
I found that this error is present only if "Skeleton2D" + "Polygon2D" is used

If you do not use Skeleton2D and do not deform the polygon, there is no such problem.

**Comment by Valeryn4** [comment]
There is no such problem on a PC.

Also, the "GLES3" render does not send the correct colors to some devices. If you use a polygon and a skeleton:
Auto-Test in FireBase (Google Pixel)
https://youtu.be/jCuqU34pT7I

**Comment by clayjohn** [comment]
@Valeryn4 Thanks for the updates! I did a search through existing issues as well and it seems that using Skeleton2D with Polygon2D has many bugs right now. For example, your color bug is reported here https://github.com/godotengine/godot/issues/27919

Soon I will put together a big issue tracker so we can properly track all the Skeleton2D issues on GLES2. At this point it appears we need to do a lot of work to make it work properly.

**Comment by Valeryn4** [comment]
What is the alternative?
I have a lot of similar animation!: https://www.youtube.com/watch?v=4YfzkH1RHsg
It works well in GLES3, but does not work in GLES2

**Comment by clayjohn** [comment]
@Valeryn4 Unfortunately, I don't think there is an alternative right now. It seems that it is just broken. It needs to be fixed.

**Comment by Valeryn4** [comment]
Using the stable version, I expect everything to work there.
And it is not very pleasant to detect malfunctions at the end of development.

Why are there no warnings when using the Polygon or Skeleton that it does not work on some devices?

**Comment by clayjohn** [comment]
Unfortunately it is a bug the we were unaware of. Because we did not know it was a problem we couldn't fix it in time for 3.2. 

Please understand that Godot is not made by a large professional team. It is made by a handful of volunteers. It is impossible for us to test every combination on every device out there. Unfortunately it turns out that your device has trouble with this combination of features. 

We will do our best to fix it in a reasonable amount of time.

**Comment by Valeryn4** [comment]
I came across such a device! HUAWEI Y6 Prime 2018
It does not work "GLES3" with 4096 textures. (mode : 2d, expand) - Game freezes on boot splash
It WORKS "GLES2" with textures 4096 and Skeleton2D.

example GLES3: https://github.com/Valeryn4/GodotBugGles2OnSpecificDevice
![Skype_Picture_2020_02_11T11_22_02_355Z](https://user-images.githubusercontent.com/12483173/74232620-e67f2b80-4d14-11ea-991f-21e672f42f56.jpeg)

other games on this site work!

**Comment by lawnjelly** [comment]
There's a good chance we can fix this as part of the new GLES2 2d renderer, I'm putting in software transform paths for most of the primitives (have done rects, lines, ninepatches so far). May possibly be done by 3.2.2 although it depends how many other regressions there are to fix.

**Comment by Valeryn4** [comment]
> There's a good chance we can fix this as part of the new GLES2 2d renderer, I'm putting in software transform paths for most of the primitives (have done rects, lines, ninepatches so far). May possibly be done by 3.2.2 although it depends how many other regressions there are to fix.

Are there any developments?
I would make my own changes to the source code for my product, which is already in the release and does not work on GLES2

**Comment by lawnjelly** [comment]
Sorry this has been delayed both by a rewrite (because regressions were very problematic to deal with in the old version) and more importantly dealing with coronavirus.

New version only deals with rects so far and I'd prefer to get that in testing before the other primitives (the logic is simpler for quads). So I can't give any promises or definite timescale for this. On the other hand if you are prepared to build from source you will be able to get it sooner when I do get around to it (probably some weeks yet). In any case I'll try and link to this thread when there is something available.

**Comment by Valeryn4** [comment]
> On the other hand if you are prepared to build from source you will be able to get it sooner when I do get around to it (probably some weeks yet). In any case I'll try and link to this thread when there is something available.

sure!
to collect from source codes of work will not make)
I am building a build with 3D disabled, on android and iOS)

**Comment by Valeryn4** [comment]
I had to abandon the skeleton = (
Now the animation is not very beautiful = (

OLD (Use skeleton): https://www.youtube.com/watch?v=4YfzkH1RHsg
NEW (Disable skeleton): https://youtu.be/rbvmBEoqrFk

**Comment by Valeryn4** [comment]
> Sorry this has been delayed both by a rewrite (because regressions were very problematic to deal with in the old version) and more importantly dealing with coronavirus.
> 
> New version only deals with rects so far and I'd prefer to get that in testing before the other primitives (the logic is simpler for quads). So I can't give any promises or definite timescale for this. On the other hand if you are prepared to build from source you will be able to get it sooner when I do get around to it (probably some weeks yet). In any case I'll try and link to this thread when there is something available.

Good afternoon! Any news?)

**Comment by lawnjelly** [comment]
> Good afternoon! Any news?)

I won't be able to look at it until the regressions for the rects are all sorted, and as it requires writing a completely new path it is quite likely to be after 3.2.2. There's also the need to start work on a GLES renderer for 4.x.

It needs two features essentially:
1) Poly software batching
2) New software skinning path

**Comment by dnadan2** [comment]
Hey, just wanted to bump this thread and ask if it did get fixed in 3.2.2 or if it is planned in future releases? I am still seeing it not draw and wanted to check its the same issue.

**Comment by Calinou** [comment]
@dnadan2 This wasn't fixed in 3.2.2, and it may take a while for it to be fixed. That said, since [Polygon2D rendering is much slower than sprite rendering](https://github.com/godotengine/godot/issues/19943), you may not want to rely on it on mobile in the first place anyway.

**Comment by kjav** [comment]
Hi @Calinou  - does this mean that 2d skeletons are currently not supported on GLES 2? Thanks.

**Comment by Calinou** [comment]
@kjav Probably not.

**Comment by lawnjelly** [comment]
Had forgotten about this, but it's on my roadmap. Currently I've had a pause on work on the batching until 3.2.3 is released (which is meant to be just bug fixes for 3.2.2), then a couple of PRs for light angles need to get merged and I can get stuck in for GLES3 batching. This has taken a lot longer than expected due to the delay on 3.2.3.

Once GLES2 and GLES3 both use the unified path I can look at batching the other primitives and this software path. Otherwise it just means trying to work on several different forks simultaneously and having to throw out a lot of work.

**Comment by akien-mga** [comment]
Note that you can still work on features/PRs which will be merged after 3.2.3 is released. The earliest we get big changes merged in prevision of 3.2.4, the better :)

**Comment by lawnjelly** [comment]
I've now added a software path as part of batching in #42119. It will probably be a project setting to switch between sofware and hardware 2d skinning.

Sorry took so long to get round to it! :blush:

**Comment by akien-mga** [comment]
Fixed by #42119.

**Comment by Valeryn4** [comment]
BUMP!
The problem is still relevant.
The error pops up on some devices.

Version 3.3
![image](https://user-images.githubusercontent.com/12483173/133201566-f0fd1af8-821e-4330-b1e5-5c7a7686ef28.png)
![image](https://user-images.githubusercontent.com/12483173/133201512-d7ff138c-b4cf-4695-af8f-3595d356aa87.png)

**Comment by lawnjelly** [comment]
If you have `batching` on, and your project setting `rendering/2d/options/use_software_skinning` switched on, also make sure the Polygon2D does not have `anti-aliasing` switched on (I don't think this ever is active on mobile but it's worth checking if it disrupts the software skinning path, it may well do). I'll double check what happens if AA is switched on in this case.

The other possibility is that there is something the skinning doesn't like, but if it is using software on desktop it should run the same on mobile. So at the moment it seems most likely culprit is that you have AA set and it is disrupting things.

**Comment by clayjohn** [comment]
@lawnjelly I don't think we have added checks everywhere for hardware dependent max texture sizes. So it could indeed be a texture size issue.
