### ISSUE TITLE
Mouse released immediately after dragging range property of ArrayPropertyEdit

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#3648]
I could only reproduce this issue with range properties of ArrayPropertyEdit (I am not sure if this issue happen in other situations).
After dragging the spinbox and releasing the left mouse button, the mouse remains captured.

You can quickly check this with a Polygon2D node, by editing its polygon property (Vector2Array) and dragging the _Size_.

**Comment by neikeq** [comment]
I could test it again now that #4608 was fixed. I cannot longer reproduce it. However, now the mouse is instantly released after dragging the dragged property while still maintaining the left mouse button pressed. Could this be related to the property failing to be set (returning `false`)?

**Comment by DualMatrix** [comment]
This is still buggy in master, now the mouse remains captured for rather long while after releasing the mouse button.

**Comment by KoBeWi** [comment]
This seems to be fixed.
