### ISSUE TITLE
"Duplicate key found in Dictionary literal" false error in 4.0 branch

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36511]
**Godot version:**
4.0.dev.custom_build. 5e181ac9f

**Issue description:**
When I use this code
```
var rr = {x=5, y=2, type=55}
```
then I got this error 
```
SCRIPT ERROR: Parse Error: Duplicate key found in Dictionary literal
```
This worked fine in Godot 3.2

**Comment by nathanwfranke** [comment]
I can reproduce this. Interestingly, this works fine `var rr = {"x": 5, "y": 2, "type": 55}`

**Comment by KoBeWi** [comment]
Seems like it's broken after Variant/StringName changes. This
https://github.com/godotengine/godot/blob/376a8255a9b65b016fcd81634bfd54fb7fa029df/modules/gdscript/gdscript_parser.cpp#L1106
returns true for different StringNames. Using "" works, because then the keys are Strings instead of StringNames.

**Comment by nathanwfranke** [comment]
I'm already working on a fix for this, it should be complete in 8 hours when I'm back from school

**Comment by qarmin** [comment]
Issue is fixed with GDScript 2.0

**Comment by stupidinternet** [comment]
still happens for me....   like it doesnt want me to use it such
