### ISSUE TITLE
random crashes not sure.

### ISSUE THREAD

**Issue by jjbob1234** [godotengine/godot#36586]
**Godot version:**
3.20-Stable
**OS/device including version:**
Xubuntu Linux?
**Issue description:**
Random Crashes
**Steps to reproduce:**
Not sure.
**Minimal reproduction project:**
Not sure.

Every thing works great, but sometimes when i'm testing out my game after a random period of time i get this error log:

```
`Game FPS: 30
ERROR: operator[]: FATAL: Index p_index = 4 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
   At: ./core/vector.h:49.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f4ba04eef20] (??:0)
[2] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x29a35b4] (<artificial>:?)
[3] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x29c2b00] (<artificial>:?)
[4] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x192829f] (??:?)
[5] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x2883b26] (??:?)
[6] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0xbc4624] (??:?)
[7] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x183b97e] (<artificial>:?)
[8] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x187b0ce] (??:?)
[9] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x292e850] (??:?)
[10] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x84877d] (??:?)
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f4ba04d1b97] (??:0)
[12] /home/jay/Programs/Godot v3.2.0 Stable/Godot_v3.2-stable_x11.64() [0x855b0e] (??:?)
-- END OF BACKTRACE --
`
```

Is this something i'm doing wrong with my programming or is this just a random error? the software its self tell's me nothing is wrong during the crash, it just happens (like i closed the window), the only way i'm able to get this log is via Linux terminal.
i have no idea how to reproduce this other then just using the software.

**Comment by clayjohn** [comment]
Could you upload a minimal reproduction project so that other users can try to reproduce the crash?

**Comment by jjbob1234** [comment]
> Could you upload a minimal reproduction project so that other users can try to reproduce the crash?

Sorry, Do you want me to post my full personal project in a zip? or something?

**Comment by dreamsComeTrue** [comment]
It doesn't have to be FULL project, just extract the part: scene, script or smth which in your opinion breaks Godot if you wan't to stay private with it :)

**Comment by clayjohn** [comment]
Nope. Just a minimal reproduction project. 

A minimal reproduction project is the smallest possible project that reproduces the bug. Without one we can't really help you. You haven't given enough information for a contributor to be able to reproduce your bug so contributors have no place to start looking. 

Try to identify what elements of your project cause the error. Then isolate them in a new project and upload that.

If you need more info see http://docs.godotengine.org/en/latest/community/contributing/ways_to_contribute.html#filing-an-issue-on-github and https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by jjbob1234** [comment]
> Nope. Just a minimal reproduction project.
> 
> A minimal reproduction project is the smallest possible project that reproduces the bug. Without one we can't really help you. You haven't given enough information for a contributor to be able to reproduce your bug so contributors have no place to start looking.
> 
> Try to identify what elements of your project cause the error. Then isolate them in a new project and upload that.
> 
> If you need more info see http://docs.godotengine.org/en/latest/community/contributing/ways_to_contribute.html#filing-an-issue-on-github and https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs

I'm sorry i can't reliably reproduce the crash, it happens in my game randomly for seemingly no reason, my game is an infinite plane (a small plane that follows the screen) no gravity with random enemy spawns, they enemies leave a puddle when they die and self.free() when they're either too far away or after the puddle shrinks to 0 or below. 

if i avoid all of the enemies then it doesn't seem to crash, but if i kill 1 enemy it has a chance of crashing, not consistent at that point, i could continue moving for awhile before the crash, or seemingly no crash at all, if i constantly kill enemies its like a 9/10 chance of crashing.

I have constant spawning enemies with sprites pointing to them on screen all the time with-in a distance of the player, (they do get free'd aswell like the puddles when they're far away) and there can be 45-46 of them (before/during the crash) on the scene at once. (later more will spawn but i cant get that far)

And a label that counts enemies killed and active combo's if you kill them within 3 seconds of eachother. using a Timer()

i haven't been given enough information to narrow down whats causing the crash exactly but it must be something my enemies are using, but my enemies code is pretty long so far for random generation purposes and it would be hard to sift through every single possibilty mainly because this is my first project to this scale (i'm pretty new-ish to development)

**Comment by jjbob1234** [comment]
I tried spawning just infinite meshes instead of spawning enemies and the crash doesn't happen anymore so i think i've narrowed it down to this code

```
extends Area

var new_death = preload("res://prefab/splat01.tscn")
var new_death2 = preload("res://prefab/splatr01.tscn")
var spl1 = preload("res://snd/splat01.wav")
var spl2 = preload("res://snd/splat02.wav")
var spl3 = preload("res://snd/splat03.wav")
var spl4 = preload("res://snd/splat04.wav")
var spl5 = preload("res://snd/splat05.wav")
var scr1 = preload("res://snd/scream01.wav")
var scr2 = preload("res://snd/scream02.wav")
var scr3 = preload("res://snd/scream03.wav")
var scr4 = preload("res://snd/scream04.wav")
var scr5 = preload("res://snd/scream05.wav")
var scr6 = preload("res://snd/scream06.wav")
var r = preload("res://mat/Material_001.material")
var g = preload("res://mat/Material_G.material")
var b = preload("res://mat/Material_B.material")

var hascolor = false
var hasscream = false

var red = false
var green = false
var blue = false
var special = false
#var vars 

var permaf = false
var fear = false
var fearc = 0
var fearcr = false
var dead = false
#var tset = tset

var t = Timer.new()
onready var colobj = get_node("/root/world/player")
var dist = 20
var velocity = Vector3()
var player = null
# Declare member variables hepre. Examples:
# var a = 2
# var b = "text"


const ENSPEED = 2
const ENACCEL = 1
const ENDEACCEL = 1

# Called when the node enters the scene tree for the first time.
func _ready():
	if !hascolor:
		var color = rand_range(0,3)
		if color <= 1:
			red = true
		else:
			if color <= 2:
				green = true
			else:
				if color <= 3:
					blue = true
#				else:
#					if color > 3:
#						special = true
		hascolor = true
	if green:
		$col/testmesh.material_override = g
		$pointer/spr.modulate = Color(0,1,0)
	if blue:
		$col/testmesh.material_override = b
		$pointer/spr.modulate = Color(0,0,1)
	if red:
		$pointer/spr.modulate = Color(1,0,0)
	#var t = Timer.new()
	#var tset = tset
	translation.y = 0.046
	add_to_group("enemy", true)
	#vars = get_node("/root/enemyvar")


# Called every frame. 'delta' is the elapsed time since the previous frame.
# warning-ignore:unused_argument
func _process(delta):
	if (not dead):
		
		#var work = randi() % 6
		#var sound = $snd.stream
		var splatsnd = [spl1, spl2, spl3, spl4, spl5]
		var scream = [scr1, scr2, scr3, scr4, scr5, scr6, null, null, null, null, null, null, null, null, null, null]
		
		
		var dir = Vector3()
		#var epos = Vector3()
		#epos = self.global_transform
#		var esca = Vector3()
#		esca = self.scale
		if(get_tree().get_nodes_in_group("dead").size() >= 10):
			permaf = true
			if !hasscream:
				$snd.stream = scream[randi() % scream.size()]
				$snd.set_volume_db(-15)
				$snd.play(0)
				hasscream = true
		
		if(not dead):
			if(overlaps_area(get_node("../player/fear")) or permaf):
				
				dir = -(colobj.transform.origin - transform.origin).normalized()
				fear = true
#				$snd.stream = scream[randi() % scream.size()]
#				$snd.play(0)
			else:
				dir = Vector3.ZERO
				velocity = Vector3.ZERO
				fear = false
				
				
		else:
			dir = Vector3.ZERO
		dir.y = 0
		dir = dir.normalized()
		
		
		var hv = velocity
		hv.y = 0
		
		var new_pos = dir * ENSPEED
		var accel = ENDEACCEL
		
		if (dir.dot(hv) > 0):
			accel = ENACCEL
			
		hv = hv.linear_interpolate(new_pos, accel * delta)
		
		velocity.x = hv.x
		velocity.z = hv.z
		
		if not dead && fear or permaf && not dead:
			transform.origin += velocity * delta
			if fearcr && not permaf:
				fearc += 1
				#print(fearc)
				if fearc >= 25:
					#if vars.screams <= 5:
					$snd.stream = scream[randi() % scream.size()]
					$snd.play(0)
						#vars.screams += 1
					permaf = true
				fearcr = false
		
		if(not dead):
			if(overlaps_body(get_node("../player"))):
				#Die Splatter WIP
				add_child(new_death.instance(), true)
				var splat = new_death2.instance()
				if red:
					splat.get_child(0).material_override = r
				if green:
					splat.get_child(0).material_override = g
				if blue:
					splat.get_child(0).material_override = b
				splat.rotation = get_node("/root/world/player").rotation / get_node("/root/world/player").rotation
				get_node("/root/world/player").add_child(splat)
				
				$"/root/world".combo += 1
				$"/root/world".combo_reset()
				dead = true
				$col.hide()
				var r = rand_range(0,50)
				$snd.stream = splatsnd[randi() % splatsnd.size()]
				$snd.set_volume_db(1)
				$snd.play(0)
				if r >= 40:
					$snd2.stream = scream[randi() % scream.size()]
					$snd2.set_volume_db(-7.5)
					$snd2.play(0)
				
			
			
		
	else:
		if is_in_group("enemy"):
			remove_from_group("enemy")
		add_to_group("dead")
		
	var prange = transform.origin.distance_to(colobj.transform.origin)
		#var prange = self.translate.distance_to(get_node("../player").translate)
	if (prange > 16): 
		#self.free()
		get_parent().remove_child(self)
		return #end process
	
#	if !dead:
#		if special:
#			if !red && !blue && !green:
#				$col/testmesh.material_override = r
#				$pointer/spr.modulate = Color(1,0,0)
#				red = true
#				blue = false
#				green = false
#				return
#			else:
#				if !blue && !green:
#					$col/testmesh.material_override = b
#					$pointer/spr.modulate = Color(0,0,1)
#					blue = true
#					red = false
#					green = false
#					return
#				else:
#					if !green:
#						$pointer/spr.modulate = Color(0,1,0)
#						$col/testmesh.material_override = g
#						green = true
#						red = false
#						blue = false
#						return
#					else:
#						if green:
#							green = false
#							return

	if not fearcr && not fear:
		#if not tset:
		#yield(get_tree().create_timer(1.0), "timeout")
		#t.start()
		#if t.get_time_left() == 0:
			
		fearcr = true

	pass

```

Sorry for the messy comments and stuff lol.
lots of trial and error in my programming.

**Comment by clayjohn** [comment]
@jjbob1234 Great work! Now just create a minimal project using that code and upload here so that other users can test it our and hopefully reproduce your crash!

**Comment by jjbob1234** [comment]
> @jjbob1234 Great work! Now just create a minimal project using that code and upload here so that other users can test it our and hopefully reproduce your crash!

sorry i wasn't able to recreate it in a separate project, but i fixed it.
It was crashing because i was setting a bool on the child to true after freeing the node's parent.
(it wasn't that script above but rather a script on a node that script was spawning)

When i move the bugged scripts to another project it doesn't crash anymore though so
I'm not sure what conditions need to be met exactly to cause the crash.

Wish i could be more help, i apologize.

the section of the code that was causing the crash was.

```
if !elapse:
		if scale <= Vector3(0,scale.y,scale.z) && direx or scale <= Vector3(scale.x,scale.y,0) && direz:
			get_parent().remove_from_group("dead")
			get_parent().free()
			...Bug testing stuff that was already commented...
			elapse = true #(commenting out this fixes the crash)
			return

```
this part of the code is useless and i must have been pretty tired when i programmed it, but no matter what i do in a different project it doesn't reproduce the crash. even just putting the node in question and all its dependencies in another project.

**Comment by Calinou** [comment]
@jjbob1234 Could you try running your project with one of those [debug builds](https://github.com/Calinou/godot-debug-builds) in a terminal? This way, you'll get an helpful backtrace.

**Comment by Calinou** [comment]
@jjbob1234  Can you (or anyone else) still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3), [Godot 3.2.4beta1](https://godotengine.org/article/dev-snapshot-godot-3-2-4-beta-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
