### ISSUE TITLE
cosmetics: windows description says alpha for 2.0-stable official builds

### ISSUE THREAD

**Issue by kopias** [godotengine/godot#3686]
godot 2.0 rc1 win7x64

very small cosmetic thing, but its near release:
when you pin godot to taskbar the terminal title is used from description (see screenshot)
and it says its still an "(alpha)" version.
![godot-title](https://cloud.githubusercontent.com/assets/3462746/13004912/8d8eb092-d17e-11e5-9898-8a00812189ab.png)

**Comment by akien-mga** [comment]
It's weird, I think this string is define here: https://github.com/godotengine/godot/blob/master/platform/windows/godot_res.rc#L20

This VERSION_STATUS is defined in core/version.h built by https://github.com/godotengine/godot/blob/caddcca4f468399e81fc703aa6e002e41250fdda/methods.py#L1100, and this one relies on https://github.com/godotengine/godot/blob/master/version.py#L5 which is correctly defined.

**Comment by akien-mga** [comment]
Or actually maybe this ``platform/windows/godot_res.rc`` file is no longer used since we dropped pe_bliss, and reduz still has an old binary ``godot_res.res`` file from the alpha in his clone used to build official binaries.

**Comment by tomreyn** [comment]
It does look different (but not necessarily better) on 2.0rc1:

`
Copyright: Copyright (c) 2007-2015 Juan Linietsky, Ariel Manzur
`

(should probably say "2016") and

`
File version: 2.0."custom_build
`

(incorrect version string) and

`
Description: Godot Engine Editor (alpha)
`

(this is rc1, not an alpha).

Click on the **File detail** tab at https://www.virustotal.com/de/file/a9ed7eb87a63480da1905323e3f8530068cd3860ff203fd84b10b8993be6d5ac/analysis/1455681157/#item-detail to verify these values.

**Comment by akien-mga** [comment]
@reduz For the next set of binaries, make sure you don't have a ``godot_res.res`` leftover from the alpha and/or start from a clean source clone, this issue does sound like a side effect of having removed pe_bliss.

**Comment by ScotFlux** [comment]
Use MSVC2013. And this problem will never be happening. At least for me.

**Comment by tomreyn** [comment]
The version info embedded to the binaries (as previously discussed in my previous post here) [remains wrong](https://www.virustotal.com/de/file/bb215f599f69a0201ce6b3612199cc9538d6dc892d82e94e83de0e77724e40a9/analysis/).

**Comment by akien-mga** [comment]
This should have been fixed starting with version 2.0.1, when we changed the buildsystem.

**Comment by tomreyn** [comment]
In 2.0.2 (64-bit), while _copyright_ and _description_ fields were updated,  and _file version_ says "2.0.0.0" and _product version_ is still showing what looks like a broken variable expansion.
 
![avcddbv](https://cloud.githubusercontent.com/assets/1328851/14942867/18fb098c-0fb9-11e6-907c-137801309eab.png)
