### ISSUE TITLE
TextEdit will move upward after input tens of lines on Android

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#37190]
**Godot version:**
3.2.1
**OS/device including version:**
Android 
**Issue description:**
after input tens of lines into the TextEdit, the rect_position of the TextEdit will move upward.
**Steps to reproduce:**
see the demo project

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/4360599/bug.zip)

**Comment by Calinou** [comment]
@alexzheng Can you record a video demonstrating the issue? Also, can you reproduce this on platforms other than Android?

I can't reproduce this using Godot 3.2.2 on Linux.

**Comment by alexzheng** [comment]
Mobile platform only.

[1594975262915032.mp4.zip](https://github.com/godotengine/godot/files/4936652/1594975262915032.mp4.zip)

**Comment by Calinou** [comment]
@m4gr3d Any idea why something like this would happen only on Android?

**Comment by pouleyKetchoupp** [comment]
This is due to the Android view trying to pan down to adjust the focus to the TextEdit content. I'm preparing a PR to fix it.

**Comment by m4gr3d** [comment]
@pouleyKetchoupp The primary issue is caused because we're setting the height of the edit text to `wrap_content`.  Setting a fixed size (e.g: 300pixels) should fix the issue.

@akien-mga Can the other PRs made against `master` for this issue be reverted.

**Comment by capnm** [comment]
> The primary issue is caused because we're setting the height of the edit text to wrap_content. Setting a fixed size (e.g: 300pixels) should fix the issue.

The issue description is not entirely accurate; in fact, Godot's entire viewport moves up. Your patch doesn't fix anything either. I think it damages the current UI even more ...

**Comment by m4gr3d** [comment]
@capnm The PR addresses the issue described in this bug which can be verified by running the minimal reproduction project before and after applying the changes.

If the issue's description is inaccurate, provide clarifications as to why or open another issue. If the PR introduces regressions, provide a description of the regressions and/or a reproduction project to highlight the regressions.

**Comment by capnm** [comment]
I've now checked the demo in this issue and the PR actually fixes it!

In my app I get new lines written into invisible area, but I can fix
that by manually updating the horizontal scroll position...

**Comment by m4gr3d** [comment]
> I've now checked the demo in this issue and the PR actually fixes it!
> 
> In my app I get new lines written into invisible area, but I can fix
> that by manually updating the vertical scroll position...

@capnm can you provide a recording or an example repro project. That issue should be addressable as well by configuring the edittext parameters.

**Comment by capnm** [comment]
It depends on the height of the text field and the font size. You could try the demo from https://github.com/godotengine/godot/pull/40944#issuecomment-667648780

Currently, the bigger issue for me is that the virtual keyboard height is not correctly calculated when it is above the Android navigation bar. On the mobile phone in portrait format, on the tablet always ...

**Comment by m4gr3d** [comment]
> It depends on the height of the text field and the font size. You could try the demo from [#40944 (comment)](https://github.com/godotengine/godot/pull/40944#issuecomment-667648780)
> 

@capnm Thanks for the demo; I'll take a look.

> Currently, the bigger issue for me is that the virtual keyboard height is not correctly calculated when it is above the Android navigation bar. On the mobile phone in portrait format, on the tablet always ... oddly enough, you get the negative height of the navigation bar when you close the keyboard.

@capnm Do you have an open bug to track that issue? If not can you start one since it seems that issue is sufficiently different from the one described in this bug.

**Comment by capnm** [comment]
> Do you have an open bug to track that issue? If not can you start one since it seems that issue is sufficiently different from the one described in this bug.

Damn, I thought you'd answer with another PR one-liner.
Ok, I'll challenge you now with a proper bug report ;-)
https://github.com/godotengine/godot/issues/41388
