### ISSUE TITLE
OS.execute trouble with shell evaluation ("export PATH=test && echo $PATH" doesn't work)

### ISSUE THREAD

**Issue by QiuleiWang** [godotengine/godot#37291]
**Godot version:**
3.2.1

**OS/device including version:**
macos

**Issue description:**
OS.execute("/bin/bash", ['-c',"export PATH=test && echo $PATH"], true, output,true)
print(output)
print result
[/usr/bin:/bin:/usr/sbin:/sbin
]
don't work

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
It also doesn't work in Bash...
```
$ /bin/bash -c "export PATH=test && echo $PATH"
/home/akien/Projects/godot/emscripten/emsdk:/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten:/home/akien/Projects/godot/emscripten/emsdk/node/12.9.1_64bit/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/lib64/qt5/bin:/usr/lib64/qt4/bin:/home/akien/.cargo/bin:/home/akien/.local/bin:/home/akien/bin:/home/akien/.cargo/bin
```

**Comment by akien-mga** [comment]
Actually it works when using single quotes to prevent shell expansion:
```
$ /bin/bash -c 'export PATH=test; echo $PATH'
test
```

**Comment by akien-mga** [comment]
The problem is that we use double quotes to enclose arguments passed to the executable (here `/bin/bash`), which means that shell variables get expanded. That's likely what most users would expect, but in this case it makes things tricky.

https://github.com/godotengine/godot/blob/5fede4a81c67961c6fb2309b9b0ceb753d143566/drivers/unix/os_unix.cpp#L283-L296

You can work it around by closing the double-quoted string and concatenating with a single-quote enclosed string:
```
OS.execute("/bin/bash", ['-c', "\"'export PATH=test && echo $PATH'\""], true, output, true)
```

I'm not sure what we can do to improve this. One solution would be to switch to using single quotes by default (no shell expansion), and then add a boolean parameter to toggle shell expansion (thus using double quotes as delimiter instead of single quotes).

**Comment by QiuleiWang** [comment]
> /bin/bash -c 'export PATH=test; echo $PATH'
gdscript don't work
OS.execute("/bin/bash", ['-c','export PATH=test && echo $PATH'], true, output,true)

[/usr/bin:/bin:/usr/sbin:/sbin
]

**Comment by QiuleiWang** [comment]
> The problem is that we use double quotes to enclose arguments passed to the executable (here `/bin/bash`), which means that shell variables get expanded. That's likely what most users would expect, but in this case it makes things tricky.
> 
> https://github.com/godotengine/godot/blob/5fede4a81c67961c6fb2309b9b0ceb753d143566/drivers/unix/os_unix.cpp#L283-L296
> 
> You can work it around by closing the double-quoted string and concatenating with a single-quote enclosed string:
> 
> ```
> OS.execute("/bin/bash", ['-c', "\"'export PATH=test && echo $PATH'\""], true, output, true)
> ```
> 
> I'm not sure what we can do to improve this. One solution would be to switch to using single quotes by default (no shell expansion), and then add a boolean parameter to toggle shell expansion (thus using double quotes as delimiter instead of single quotes).

OS.execute("/bin/bash", ['-c', "\"'export PATH=test && echo $PATH'\""], true, output, true)
That's right.

**Comment by akien-mga** [comment]
I'll keep it open for now as we might want to change the method, or at least improve the documentation to mention this caveat.

**Comment by blinry** [comment]
So @bleeptrack and I just stumbled over this problem – we definitely had expected that `OS.execute` would pass the arguments to the command literally, without any modification. A more stable implementation (using C's `execv`?) would sure be nice!

@akien-mga, your workaround was helpful and worked, thanks! To preserve single quotes inside the command, we ended up replacing all of them by `'"'"'`, like this:

```gdscript
var command = "echo \"hello 'world'\""
command = '"\''+command.replace("'", "'\"'\"'")+'\'"'
OS.execute("/bin/bash, ["-c",  command])
```

**Comment by akien-mga** [comment]
I believe this was fixed for Windows with #38856, but might still be a problem for Linux and macOS. It would be good to clean this up before 4.0. (CC @bruvzg)

**Comment by akien-mga** [comment]
Still reproducible on Linux.
```gdscript
var output = []
OS.execute("/bin/bash", ['-c', "export PATH=test && echo $PATH"], output)  # Prints system PATH
print(output)
output = []
OS.execute("/bin/bash", ['-c', "\"'export PATH=test && echo $PATH'\""], output)  # Prints ["test\n"]
print(output)
```

**Comment by kobligo** [comment]
Hello, anyone? This bug is still reproducible in the latest version of Godot. Is nobody looking into this?
IMO this severely limits what you can do with OS.execute().

**Comment by Calinou** [comment]
> Is nobody looking into this?

To my knowledge, nobody is currently looking into this. It's a difficult area to resolve bugs in, since it's prone to regressions (PRs have been merged and reverted in the past).

**Comment by Desyncfy** [comment]
Please work on this, it creates a lot of problems in the program I'm working on.
