### ISSUE TITLE
Mobile VR: Rendering Stretched Vertically

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot#37582]
**Godot version:**
`v3.2.1.stable.flathub`

**OS/device including version:**
PC: Arch Linux
Phone: Xiaomi Mi Note 2, 16:9 1920x1080 display

**Issue description:**
Mobile VR rendering is stretched vertically. It can be noticed when rotating the phone, where the image becomes instead vertically squished when rotated 90° to a side (to the point where the phone becomes "in portrait orientation" relative to the real world).
"Vertical" here is relative to the virtual world.
![Screenshot_20200404-180104_3dworld](https://user-images.githubusercontent.com/36982494/78452816-a6964e00-769e-11ea-86d9-28f6e04357d3.png)
![Screenshot_20200404-180112_3dworld](https://user-images.githubusercontent.com/36982494/78452822-ae55f280-769e-11ea-8545-f605769ee5fd.png)

It seems as if it is assuming a 2:1 aspect ratio, where each eye display has a 1:1 ratio, and since with a 16:9 ratio the single eye display is thin and tall, it stretches the image accordingly.
I've tried all options in Project Settings > Window > Stretch but nothing changed.

**Steps to reproduce:**
Any VR scene with `Native mobile` interface should do.
Launch the game, then rotate the phone while following it (either in or out of the headset). You'll notice that the vertical axis of the virtual world starts stretched when the phone is in landscape orientation, then starts getting skewed and distorted as you rotate, till when you get to 90°, where it becomes squished instead.

**Comment by BastiaanOlij** [comment]
Unfortunately the mobile interface knows nothing about you phone or the headset you plug your phone into, you have to provide that information. After you call ARVRServer.find_interface to obtain your mobilevr interface an instance of this object is returned:
https://docs.godotengine.org/en/3.2/classes/class_mobilevrinterface.html

Note the various settings on the object you can change. The defaults here are based on a GearVR with a Galaxy Note inserted which indeed has a 2:1 screen. 

If you have a cardboard compatible headset there should be a QR code on your headset that you can scan.  You can use a tool like:
https://wwgc.firebaseapp.com/
to decode the code in the QR code to get all the settings (minus the width of your phone). 

Let me know if you can set things up correctly with those for your device.

**Comment by BastiaanOlij** [comment]
@Tooniis already reacted on trying the settings on Discord so not entire sure what is going on. 

Just tracking through the code these are the important bits we need to look at: 

https://github.com/godotengine/godot/blob/3.2/modules/mobile_vr/mobile_vr_interface.cpp#L338
`get_render_target_size` obtains the resolution at which we want to render each eye, which becomes half your screen size upscaled by oversample. Our viewport is automatically adjusted to this.
When Godot renders one eye it will use the aspect ratio formed by that viewport which will be half your screen width in pixels divided by your screen height in pixels.

https://github.com/godotengine/godot/blob/3.2/modules/mobile_vr/mobile_vr_interface.cpp#L404
`commit_for_eye` gets the image rendered by Godot and outputs it with lens distortion applied. This is called twice, once for each eye. We get our original screen size here so we horizontally half it again, and then output to either left or right side of the eye by calling `output_lens_distorted_to_screen`.

https://github.com/godotengine/godot/blob/3.2/drivers/gles3/rasterizer_canvas_gles3.cpp#L2017
`draw_lens_distortion_rect` gets called from `output_lens_distorted_to_screen`.
Here we see our shader being setup including calculating the aspect ratio used, which is again based on half our screen width divided by our screen height (that size of the rectangle provided to us by `commit_for_eye`. 

https://github.com/godotengine/godot/blob/3.2/drivers/gles3/shaders/lens_distorted.glsl#L41
Finally we see the only place where the aspect ratio is used while outputting. As our uv_interp goes from (0,0) - (1,1) we need to divide our Y by our aspect ratio so we can properly apply our lens distortion, after our lens distortion is applied we multiply by our aspect ratio.

OK, now for the weird bit, we can simulate everything on desktop, even helps stuff out. Changed my vehicle tutorial project to use the mobile VR output, set oversample to 1.0 (no oversample), and set both k1 and k2 to 0, which turns off lens distortion. We should now get two nicely looking renders for each eye:
![image](https://user-images.githubusercontent.com/1945449/78467543-3b598400-7751-11ea-8cb1-99af3f5ef92a.png)

That does not look right to me and this definitely worked correctly before... I'm going to do some more testing to see where this may be going wrong.

**Comment by BastiaanOlij** [comment]
@Tooniis damn that was a stupid mistake in the hmd projection code. See PR. Looks good now:
![image](https://user-images.githubusercontent.com/1945449/78468126-e3724b80-7757-11ea-812e-e29a5ab16d5b.png)

I gave you some more info on Discord for the next issue you will run into and how to work around it, I never got to finish #22644

**Comment by akien-mga** [comment]
Fixed by #37601 (cherry-picked in `master` as 94fab21348).

**Comment by Tooniis** [comment]
#37601 actually fixed another bug that was similar to this. I patched `v3.2.1.stable` with it, and this specific bug is still there:
![Screenshot_20200413-182958_3dworld](https://user-images.githubusercontent.com/36982494/79129124-b526e880-7db5-11ea-95e5-a32dd9acc7ca.png)
![Screenshot_20200413-183006_3dworld](https://user-images.githubusercontent.com/36982494/79129180-c8d24f00-7db5-11ea-8486-e151d4ce0338.png)
![Screenshot_20200413-183018_3dworld](https://user-images.githubusercontent.com/36982494/79129205-d8519800-7db5-11ea-842b-aedf88e7329d.png)

The bug it fixed was reproduced by making the window resizable then resizing the preview window on PC.

**Comment by Tooniis** [comment]
I've made sure it really didn't fix this bug, and it isn't some sort of cached pre-compiled parts that were being put back when I export to Android with the patched version, by clearing all Gradle cache. It took much longer to build without the cache.

I did it twice just to be sure that I weren't possibly using the unpatched version.

**Comment by clayjohn** [comment]
@BastiaanOlij

**Comment by Tooniis** [comment]
Actually #37601 should fix this. I don't understand why it has no effect on Android.
Changing the display resolution on Android through the ADB shell with `wm size` yields similar behavior to what it fixed on PC.

**Comment by Zireael07** [comment]
IIRC you should always export to an empty folder otherwise some things can get unexpectedly reused?

**Comment by Tooniis** [comment]
> IIRC you should always export to an empty folder otherwise some things can get unexpectedly reused?

I export straight to my phone through ADB (the button with the Android icon next to the run button), and I have "Clear Previous Install" enabled. I also deleted Gradle cache to be sure as I mentioned before. I don't know if this is enough.

**Comment by Tooniis** [comment]
I tried exporting an apk then manually installing it but nothing changed

**Comment by Tooniis** [comment]
I tried rebuilding the export template, but that changed nothing either.

**Comment by BastiaanOlij** [comment]
Gradle is a pain in the but.

ALWAYS run `gradle clean` before running gradle to build your APK or you often end up with old code still in there.

**Comment by Tooniis** [comment]
I think the new export template made the sensor lag patch work actually. The difference is very slight so it's hard to tell, and I'm still not certain about it.
I guess it's because it's in the platform-specific Java code for Android.

**Comment by Tooniis** [comment]
I added a `print_line()` to `CameraMatrix::set_for_hmd()`:

    void CameraMatrix::set_for_hmd(int p_eye, real_t p_aspect, real_t p_intraocular_dist, real_t p_display_width, real_t p_display_to_lens, real_t p_oversample, real_t p_z_near, real_t p_z_far) {
	    // we first calculate our base frustum on our values without taking our lens magnification into account.
	    real_t f1 = (p_intraocular_dist * 0.5) / p_display_to_lens;
	    real_t f2 = ((p_display_width - p_intraocular_dist) * 0.5) / p_display_to_lens;
	    real_t f3 = (p_display_width / 4.0) / p_display_to_lens;

	    // now we apply our oversample factor to increase our FOV. how much we oversample is always a balance we strike between performance and how much
	    // we're willing to sacrifice in FOV.
	    real_t add = ((f1 + f2) * (p_oversample - 1.0)) / 2.0;
	    f1 += add;
	    f2 += add;
	    f3 *= p_oversample;

	    // always apply KEEP_WIDTH aspect ratio
	    f3 /= p_aspect;
	    print_line("f3 /= p_aspect"); // <- Added this

	    switch (p_eye) {
		    case 1: { // left eye
			    set_frustum(-f2 * p_z_near, f1 * p_z_near, -f3 * p_z_near, f3 * p_z_near, p_z_near, p_z_far);
		    }; break;
		    case 2: { // right eye
			    set_frustum(-f1 * p_z_near, f2 * p_z_near, -f3 * p_z_near, f3 * p_z_near, p_z_near, p_z_far);
		    }; break;
		    default: { // mono, does not apply here!
		    }; break;
	    };
    };

It prints on PC but doesn't on Android.
Now its confirmed that the patch isn't being applied on Android. As for why, I have absolutely no idea. I rebuilt both the debug and release templates, cleaned Gradle cache, tried multiple export methods, but nothing changed anything.

**Comment by akien-mga** [comment]
Did you set a Custom Debug Package in the export preset which points to a different APK? It seems quite likely that the issue is that you're using outdated code. If `git clean -fxd` and rebuild from scratch doesn't solve it, then you're using another APK that the one you're building, or you're not building the correct commit.

**Comment by Tooniis** [comment]
> Did you set a Custom Debug Package in the export preset which points to a different APK? It seems quite likely that the issue is that you're using outdated code. If `git clean -fxd` and rebuild from scratch doesn't solve it, then you're using another APK that the one you're building, or you're not building the correct commit.

I had Custom Build on for a plugin. Turning it off fixed it finally. I tried turning it off before but it didn't change anything back then, but I also didn't rebuild the export template back then so I think that was why.

Trying to use Custom Build again with a new custom build template is causing some trouble with Gradle now, but I doubt it is related to this.
