### ISSUE TITLE
Rect2D .has_point() breaks with negative size values

### ISSUE THREAD

**Issue by iway1** [godotengine/godot#37617]
**Godot version:**
3.2
**OS/device including version:**
MacOS Catalina 10.5.3

**Issue description:**
Rectangles .has_point() returns false when it should return true. In my case, I'm calculating a rectangle based on two points. This is done with subtraction, which results in the rectangle having negative size when one of the points is above or to the left of the other.

**Minimal reproduction project:**
```
var rect = Rect2D(Vector2(100, 100), Vector2(-100, -100));
if rect.has_point(Vector2(50, 50)):
    print("This should print");
else:
    print("But this prints instead");
```

**Comment by pycbouh** [comment]
Related to #23711 and #25829

**Comment by ThakeeNathees** [comment]
would this be a good fix for?
```c++
Rect2(real_t p_x, real_t p_y, real_t p_width, real_t p_height) {
    position.x = MIN(p_x, p_width); 
    position.y = MIN(p_y, p_height);

    size.width  = MAX(p_x, p_width);
    size.height = MAX(p_y, p_height) ;
}
```

**Comment by pycbouh** [comment]
@ThakeeNathees Size is still relative, whether positive or negative. You cannot compare it to the position.

**Comment by ThakeeNathees** [comment]
@pycbouh oops, I was forget to add size to position, now I've edited it could you have a look at it

**Comment by pycbouh** [comment]
@ThakeeNathees Yeah, your code makes sense now. I'm not sure about a solution itself, though. Judging by other problems with negative sized `Rect`s, such values result in an undefined behavior. As discussed in #23711, you can either fix the problem for a particular function, or document behavior.

It may be worth normalizing values automatically, like you do in your first snippet, but that means that something unexpected by a user can happen. He passes a position, but in the end it's different. This creates a point of confusion.

Another way may be to require users to sanitize their size beforehand and deny negative sizes. Most of programmers would do that anyway, but it makes it less convenient for those who actually get into these corner cases.

Then there is fixing this specific function and other functions that have related problems. Then your second snippet seems like a correct solution. Though I'm not sure patching holes is a good way to handle such cases.

**Comment by iway1** [comment]
I fixed this by creating an equivalent rectangle that uses positive size values. It is exactly like @ThakeeNathees solution, I believe it would work in every situation since it creates a rectangle that should be equivalent to the desired one, except using valid size values.

**Comment by TamtamHero** [comment]
So, IIUC this hasn't actually been solved, https://github.com/godotengine/godot/pull/37626 since has been reverted ?
I still have the issue with the latest Godot 4.2.3
