### ISSUE TITLE
Mac error -10810 on exported game

### ISSUE THREAD

**Issue by Levrault** [godotengine/godot#37725]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Mac IOs 10.15.2 

**Issue description:**
Hi all, I got a strange issue while exporting my game. Windows/Linux version works great but the MacOs version keep triggering an error **10810** (unknow error). I do not own a Mac so it was pretty hard to understand why the build was failing.

So I manage to get a remote access to a Mac and re-export the project directly with the Godot Mac version (3.2.1 stable). The build fail again. So I try to make it run through the terminal, to see if some fancy errors would pop up but I still got the 10810 message :/. 

The problem could probably came from my project, but without any error/warning, I just don't know what to do. I run it directly from Godot and everything was running smoothly :/

**Steps to reproduce:**
- Get a access to a mac
- The project should run fine when playing through the in-game editor
- Export the project with the following config
![image](https://user-images.githubusercontent.com/1162446/78936537-0b8ee100-7aaf-11ea-8225-0738e8de6ded.png)
- Export a debug or release version
- Execute

**Minimal reproduction project:**
I'm really sorry but a minimal project is pretty hard to produce since I do not own a Mac. 

But here to source code of the project https://github.com/Levrault/godot-maximilien-adventure and the Mac OS build
https://drive.google.com/open?id=1z7BYik6_3BJM6Qi0E-jqXXLCOYeoV0Cj that fail. 
Thanks a lot

**Comment by bruvzg** [comment]
See #527, `.ZIP` exports are not setting `+x` file attribute on the executable, try exporting as `.DMG`.

**Comment by Levrault** [comment]
Thanks for the reply, How can we export in .DMG? I read the doc 

> When exporting for macOS, if you export on a macOS computer, you’ll end up with a .dmg file, while using Linux or Windows produces a .zip. In either case, the compressed file contains a macOS .app that you can double-click and run.

But when I exported on the Mac, I still got a .zip file.

**Comment by bruvzg** [comment]
> How can we export in .DMG?

Select DMG in the file type dropdown of the save dialogue, or just add ".dmg" at the end of export filename.

**Comment by Levrault** [comment]
Exporting to DMG solve the issue thanks a lots!

**Comment by bruvzg** [comment]
#33447 was merged and cherry-picked to 3.2.2, macOS ZIP exports should work now.

**Comment by keyle** [comment]
FyI I'm on 3.2.2 stable official, with a blank project, a camera and a cylinder: ZIP export still doesn't work. DMG does work.

Contents/MacOS/ : 
-rw-------  1 k  staff    38M 22 Aug  2020 TestOSX

Manually chmod +x the file does make it work...

**Comment by akien-mga** [comment]
There was a regression later on that made it in 3.2.2.stable.
Can you try 3.2.3.beta1 which should solve it? https://godotengine.org/article/dev-snapshot-godot-3-2-3-beta-1
