### ISSUE TITLE
OS.execute returns ERR_CANT_FORK

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#38808]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
I need to run a batch file, which sets some env vars and launches a java applet, from inside Godot. The only way how is to use OS.execute:
`OS.execute("C:/build/gateway/bin/run.bat", [], false)`

Contents of the .bat file:
```
set JAVA_HOME=c:\jdk
set PATH=%JAVA_HOME%\bin;%PATH%
set config_file="C:\build\gateway\root\conf.yaml"
set config_path="C:\build\gateway\root\"
set RUNTIME_PATH="C:\build\gateway\root\;dist\ibgroup.web.core.iblink.router.clientportal.gw.jar;build\lib\runtime\*"
java -Djava.net.preferIPv4Stack=true -Dvertx.disableDnsResolver=true -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -Dnologback.statusListenerClass=ch.qos.logback.core.status.OnConsoleStatusListener -Dnolog4j.debug=true -Dnolog4j2.debug=true -classpath %RUNTIME_PATH% ibgroup.web.core.clientportal.gw.GatewayStart
```
When the OS.execute method is called in an exported Godot project with debugging, the debug window throws the following error:
```
ERROR: execute: Condition "ret == 0" is true. Returned: ERR_CANT_FORK
   At: platform/windows/os_windows.cpp:2749
```
As much as I have been able to learn from searching through the archives, this error is earliest from Oct 30, 2017 and it still has not been fixed!

I'm very disappointed what a flaming trainwreck GDScript is.

**Comment by Calinou** [comment]
> I'm sad and very disappointed that GDScript continues to be a flaming trainwreck.

I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by bojidar-bg** [comment]
Well, flaming or not, running a bat file as a command-line application should probably work, or if it is impossible to make it work without ugly hacks, a note in the documentation could be added telling users to use e.g. cmd.exe to run bat files.

**Comment by TheDuriel** [comment]
Did you try?

OS.execute("CMD.exe", ["C:/build/gateway/bin/run.bat"])

**Comment by aspenforest** [comment]
> Did you try?
> 
> OS.execute("CMD.exe", ["C:/build/gateway/bin/run.bat"])
> 
> Or running Godot as admin?

Okay, I did it now, and the debug window gives the following error:
`'un2.bat"' is not recognized as an internal or external command,
operable program or batch file.`

Can someone please explain how can this result be even remotely possible?

**Comment by TheDuriel** [comment]
Seems like a Windows issue at that point. Make sure not to escape the characters.

**Comment by RevoluPowered** [comment]
windows is fun, maybe this?
```OS.execute("CMD.exe", ["C:\\build\\gateway\\bin\\run.bat"])

**Comment by aspenforest** [comment]
> Seems like a Windows issue at that point. (Since thats not a Godot error at all.) Make sure not to escape the characters.

I also tried 
`OS.execute("C:\\build\\gateway\\bin\\run.bat", [], false)`
But this does not run anything, it only produces:
`Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.`
as if I had not given it any parameters at all.

**Comment by TheDuriel** [comment]
Meaning it ran the CMD and your command just fine. Leaving the result up to Windows.

What even is this bat?

**Comment by aspenforest** [comment]
I think I figured out why it's impossible to make this work:
Godot needs to use escape characters to portray \ chars in strings, but when calling OS.execute, 
the escape



> Meaning it ran the CMD and your command just fine. Leaving the result up to Windows.
> 
> What even is this bat?

No, it did not run anything fine, as the bat is supposed to start a server on localhost, and on success it writes a confirmation log to cmdline.

**Comment by aspenforest** [comment]
I think I figured out why it's impossible to make it work:
We can't use neither / nor \ characters in OS.execute args, as Godot messes up their translation into the cmdline. 
For example: arg ["C:/remedy"] is interpreted by the cmdline as "C:emedy", but we can't use \ neither, because Godot needs \\ to pass a \, but in OS.execute does not remove the escape char and the cmdline goes tits up when it reads \\ in an arg.

**Comment by TheDuriel** [comment]
use a multiline string and only escape \ once.

**Comment by TheDuriel** [comment]
Also do remember that Windows does not care. And that / is valid too in most cases.

**Comment by aspenforest** [comment]
> > Did you try?
> > OS.execute("CMD.exe", ["C:/build/gateway/bin/run.bat"])
> > Or running Godot as admin?
> 
> Okay, I did it now, and the debug window gives the following error:
> `'un.bat"' is not recognized as an internal or external command, operable program or batch file.`
> 
> Can someone please explain how can this result be even remotely possible?

If windows doesn't care about /-s, then how would you explain this result?

**Comment by name-here** [comment]
It seems like Godot replaces backslash+character sequences in strings (ex. \\t -> [TAB]), though syntax highlighting does not show this (unlike other code editors, where such sequences are shown in a different color).  I think the built in editor's lack of syntax highlighting here is one of the things causing confusion.

**Comment by bojidar-bg** [comment]
Godot uses [`CreateProcessW`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) in  [`OS::execute`](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L473). The `CreateProcessW` documentation has the following line when explaining the parameters of `CreateProcessW`:

> To run a batch file, you must start the command interpreter; set lpApplicationName to cmd.exe and set lpCommandLine to the following arguments: /c plus the name of the batch file. [(link)](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw#parameters)

The [documentation of `cmd.exe`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd) also confirms the fact that the `/c` flag is necessary to run the command.

As Godot does not change the executable to `CMD.exe` or add the `/c` flag in any way, it is necessary to do both manually. Like this:
```gdscript
OS.execute("CMD.exe", ["/c", "C:\\build\\gateway\\bin\\run.bat"])

# instead of OS.execute("C:\\build\\gateway\\bin\\run.bat")
```

(Note: [`OS.execute`](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L433) can also use [`_wpopen`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=vs-2019) when `blocking` is set to true. I'm unable to find documentation which explains how it works with batch files, however.)

**Comment by Ev1lbl0w** [comment]
I didn't see this mentioned anywhere in the thread: maybe Godot is interpreting `/r` as a carriage-return?

**Comment by bojidar-bg** [comment]
@Ev1lbl0w `/r` could be interpreted as something else than just characters in 4 places: GDScript, OS.execute, whatever API OS.execute uses, and the executed application.

* It is not GDScript, since `print("/r")` does not print a carriage return (`print("\r")` would, though).
* The code in [`OS_Windows::execute()`](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L418) does not do any string processing that might account for this -- it just concatenates the whole command line, representing it as a string containing `"command" "arg1" "arg2"`.
* [`CreateProcessW`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw)'s documentation does not mention "escape codes" or something like that. Likewise for [`_wpopen`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=vs-2019)
* `CMD.exe` might be parsing `/r` as a flag, given that it is part of its first argument. Even though its documentation does not specify an `/r` flag, who knows what lurks in its code..

**Comment by name-here** [comment]
I think there may have been some confusion between backslashes and slashes in the comments above.  Also, unfortunately, the Godot editor shows no indication that it is going to replace `\r` and the like.  It seems like better syntax highlighting might avoid the `'un.bat"'` confusion.  Does anyone know where the syntax highlighting settings are in Godot's code?

**Comment by Calinou** [comment]
> Does anyone know where the syntax highlighting settings are in Godot's code?

https://github.com/godotengine/godot/blob/master/modules/gdscript/editor/gdscript_highlighter.cpp

**Comment by girng** [comment]
Great explanation @bojidar-bg! @aspenforest  did you try `OS.execute("CMD.exe", ["/c", "C:\\build\\gateway\\bin\\run.bat"])`?

**Comment by ditikos** [comment]
I don't suppose this works on windows, right? OS.execute("CMD.exe", ["/c", @"c:\build\gateway\bin\run.bat"]).

I recall having the @ in front of windows string paths would translate the path correctly in visual c#, I don't know if this is passed in cmd.exe as well, the way I wrote it. ---
Ah --- probably a syntactic sugar for c#: https://docs.microsoft.com/en-us/dotnet/api/system.io.path?view=netcore-3.1

Maybe implement the program in mono/c# ? (long shot suggestion)

**Comment by Anutrix** [comment]
@aspenforest Now that https://github.com/godotengine/godot/issues/38803 is fixed by https://github.com/godotengine/godot/pull/38856, can you test again?

**Comment by filipworksdev** [comment]
This is still an issue btw. Seems on Windows you need special magical Windoze way to run things:
 
`OS.execute("powershell", ["code"], false)`

Could not get it to run using "cmd.exe" or "cmd" but works fine with "powershell" option.
