### ISSUE TITLE
iOS spot light / point light shadows not showing on device

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot#39014]
![Screenshot](https://user-images.githubusercontent.com/4403212/82758301-9fa5d500-9ddd-11ea-9ab5-484e4b4d2238.png)

![iPhone](https://user-images.githubusercontent.com/4403212/82758308-ab919700-9ddd-11ea-9d8a-455118261cba.PNG)

**Godot version:**
3.2.1 standard and 3.2.2 beta 3 standard

**OS/device including version:**
iOS 13.5 iPhone 11

**Issue description:**
iOS spot light / point light shadows not showing on device

**Steps to reproduce:**
minimal project using cube meshes and a few lights and only shadows from direction lights are shown on device when running

**Minimal reproduction project:**
[iOS Shadows.zip](https://github.com/godotengine/godot/files/4673833/iOS.Shadows.zip)

**Comment by clayjohn** [comment]
Is this in GLES2 or GLES3?

**Comment by ViktorEvil** [comment]
Sorry it’s the same in both

**Comment by volzhs** [comment]
seems similar to #24710

**Comment by ViktorEvil** [comment]
Disabling vertex shading on mobile appears to fix the problem but may effect performance on slower mobiles

**Comment by fantomac** [comment]
Hello,
Someone find a solution to have for good 3d performances and shadows ijn iOS ??

**Comment by Calinou** [comment]
> Hello,
Someone find a solution to have for good 3d performances and shadows ijn iOS ??

Real-time lights will always be expensive on mobile devices, especially when shadows are enabled.

Also, consider rendering the viewport at a lower resolution using the `viewport` stretch mode. This improves performance tremendeously. See [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/rendering/multiple_resolutions.html) in the documentation for more information.

**Comment by ViktorEvil** [comment]
This is still an issue on all versions of Godot up to 3.2.4 rc 2.

Are developers not supposed to use spot / point lights on mobile? If that is the case maybe we should have an option in the editor to be able to display how the game will look when exported to mobile. It’s very disappointing to set everything up in the editor only to have it look like garbage on high end mobiles

**Comment by Calinou** [comment]
> Are developers not supposed to use spot / point lights on mobile? If that is the case maybe we should have an option in the editor to be able to display how the game will look when exported to mobile. It’s very disappointing to set everything up in the editor only to have it look like garbage on high end mobiles

It's recommended to use baked lights on mobile with the bake mode set to All. This way, you get the best possible performance and no issues with real-time shadows.

**Comment by ViktorEvil** [comment]
> > Are developers not supposed to use spot / point lights on mobile?
> 
> It's recommended to use baked lightmaps on mobile with the omni/spot lights' bake mode set to **All** (instead of the default **Indirect**). This way, you get the best possible performance and no issues with real-time shadows. On mobile (and even on desktop sometimes), a lot of the most popular games are still doing this for point lights in 2021.
> 
> > If that is the case maybe we should have an option in the editor to be able to display how the game will look when exported to mobile. It’s very disappointing to set everything up in the editor only to have it look like garbage on high end mobiles
> 
> Unfortunately, there's no way to emulate all the rendering bugs that may occur on mobile on a desktop platform.

I have done some digging into the settings for mobiles and think that some of the defaults should be disabled or at least documented in the settings a little better.

this is a prototype with settings unchanged, note how there is no specular.
![image2](https://user-images.githubusercontent.com/4403212/109178406-bae4ad00-7780-11eb-9b20-fbc1b847ff0f.PNG)

this has had “Force Vertex Shading.mobile” disabled it brings back the specular but is massively overblown 
![image1](https://user-images.githubusercontent.com/4403212/109178546-dfd92000-7780-11eb-9c22-840527d60945.PNG)

this now displays the same as in the editor with nice smooth shading with specular highlights etc but I had to disable “Force Blinn Over Ggx.mobile” and “Force Lambert Over Burley.mobile”.
![image3](https://user-images.githubusercontent.com/4403212/109178646-fd0dee80-7780-11eb-85cc-0dfddd25fc16.PNG)

I had to disable/enable settings one by one and export to my iPhone until I had found the correct settings. Somebody new to engine is not going to do that. They are going to export the game to mobile and see how it looks nothing like the scene in the editor then instantly dismiss the engine and switch to another one that has better defaults.

**Comment by Zireael07** [comment]
Blinn and Lambert are enabled on mobile for performance reasons.

**Comment by ViktorEvil** [comment]
> Blinn and Lambert are enabled on mobile for performance reasons.

I understand that, but my argument still stands, there are lots of things that could be disabled for performance reasons.

A new user will still think that the engine looks like crap by default without lots of tinkering and move on to other things

**Comment by Calinou** [comment]
I'm not sure if defaulting to settings that perform really poorly on mobile is a better thing to do...

Keep in mind that iOS devices are significantly faster than nearly all Android devices out there, for two reasons:

- Faster CPUs and GPUs.
- More optimized OS.
- Lower resolution display, leading to less pixels to compute shaders for and less fill rate pressure.

**Comment by clayjohn** [comment]
The vertex lighting issue will probably be solved by https://github.com/godotengine/godot/pull/42543

**Comment by ViktorEvil** [comment]
> I'm not sure if defaulting to settings that perform really poorly on mobile is a better thing to do...

maybe you're right. I was incredibly frustrated and spent a very long time trying to get something running on my phone at a reasonable quality that I knew the device could run with ease. (I even downloaded Unity again)

I suspect that other iOS devs would have the same issue and just give up and move on which is a shame because the rest of the engine is very easy to use and is a joy to work in.

**Comment by ViktorEvil** [comment]
> The vertex lighting issue will probably be solved by #42543

Thanks :)

**Comment by fantomac** [comment]
Hello, for me I have a scene with dices rolled with dynamic shadows.
With your settings my iPhone 6+ is lagging.
I have to activate "Force Lambert Over Burley.mobile" and it's better.
Calinou is right.
With an iPhone 8 it's ok without "Force Lambert Over Burley.mobile".

**Comment by ViktorEvil** [comment]
> Hello, for me I have a scene with dices rolled with dynamic shadows.
> With your settings my iPhone 6+ is lagging.
> I have to activate "Force Lambert Over Burley.mobile" and it's better.
> Calinou is right.
> With an iPhone 8 it's ok without "Force Lambert Over Burley.mobile".

IPhone 6+ is over 6 and a half years old, at some point I think it’s foolish to have settings enabled so that old tech still works, surely it’s better to have a good middle ground in the settings so that scenes actually resemble what’s in the editor. Instead we a settings that try to run on everything and we are left disappointed when we export.

I would much prefer to export my project and actually see what I designed in the editor and then if it runs like crap on my hardware I know that I need to dial it down a bit. At the moment when we export it runs great but looks nothing like what is in the editor and we have no way of knowing if it’s a hardware or Godot limitation and what settings if any I need to toggle to get good visuals.

**Comment by clayjohn** [comment]
To summarize, there are 2 remaining problems here. 

1. Blinn is broken (both in Vertex and in Fragment lighting modes)
2. Vertex lighting always uses Blinn

Fragment Blinn is fixed here: https://github.com/godotengine/godot/pull/51410
Vertex lighting still needs a fix (similar to https://github.com/godotengine/godot/pull/51410 but will involve more changes)

**Comment by Calinou** [comment]
@ViktorEvil Can you (or anyone else) still reproduce this bug in [Godot 3.4.3](https://godotengine.org/article/maintenance-release-godot-3-4-3) or any later release?

**Comment by ViktorEvil** [comment]
it looks fixed for me I have just re-enabled “Force Vertex Shading.mobile”, “Force Blinn Over Ggx.mobile” and “Force Lambert Over Burley.mobile” and I get a similar looking results

all mobile settings disabled
![IMG_0221](https://user-images.githubusercontent.com/4403212/156026969-2895dd66-f1de-4ce7-877f-a8482ea42abd.jpg)


all mobile settings enabled
![IMG_0222](https://user-images.githubusercontent.com/4403212/156027055-0b86297a-d3b3-4d78-91b2-0f371e849e13.jpg)

with the mobile settings enabled I use about 30MB less RAM but with slightly worse visuals, frame rate is roughly the same with only a 0.2 ms frame time difference

**Comment by clayjohn** [comment]
Wonderful, thank you for following up!

Closing as fixed.
