### ISSUE TITLE
OS.execute run in the editor executes the wrong binary target if the target is another Godot app

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#39036]
**Godot version:**

v3.2.stable.official

**OS/device including version:**

N/A

**Issue description:**

Running "app1" in the Godot editor. App1 calls OS.execute to launch "app2.exe" which is another Godot app created using Windows Desktop export template with debug turned off. Instead of running app2.exe, a second instance of app1 ran.

When I export app1 using the Windows Desktop export template and run the app1.exe, OS.execute launches the correct app (app2.exe)

**Steps to reproduce:**
1) Create a simple project and export to "_path_/app2.exe" using Windows Desktop export template with debug turned off. Verify this app runs correctly when launched manually.

2) Create a second simple projected called "app1" with a button that when clicked calls OS.execute("_path_/app2.exe",[],false).

3) Run app1 in the editor, click the button. A second instance of app1 appears.

4) Export app1 to "_path_/app1.exe" using the Windows Desktop export template with debug turned off.

5) Launch app1.exe and click the button. app2.exe is executed correctly.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Maybe this is because the project data takes priority over the PCK file?

Also, did you check the "embed PCK in executable" option in the export dialog? This is a [known bug](https://github.com/godotengine/godot/issues/37568) which has been fixed in the 3.2.2 betas.

**Comment by tx350z** [comment]
Thanks. Embedding the PCK is a good idea but did not solve the problem. The interesting thing is if the target app is not a Godot app, the correct binary is run. The correct binary is also run if I export both apps to Windows and run the exe. So it has to be a bug in the editor/debugger.

I'm putting together very simple projects to demonstrate the problem. Will add the zips when I can.

**Comment by akien-mga** [comment]
The correct binary is properly run, but Godot binaries are all the same, it's the presence of a `.pck` or `project.godot` file in the current folder which determines which project will run.

If you want to start a different project from your current Godot project, you can even reuse the current Godot binary (`OS.get_executable_path()` -- provided it's a project for the same Godot version), but you need to give it the `--main-pack` argument pointing to the `.pck` you want to load. Otherwise it will load your current project's `project.godot` from your current working directory.
