### ISSUE TITLE
Angular damp inside Area is far too strong

### ISSUE THREAD

**Issue by Garmelon** [godotengine/godot#39059]
**Godot version:**
3.2.1-stable (b0eca5828ccd3a5c07b77e82e567c45937de9056, self-compiled)
Also happens in the latest version on the 3.2.2 branch (757d8b56721f856e4bd5ec7f27b8bc619ddc2bca)

**OS/device including version:**
Arch linux

**Issue description:**

Expected behaviour:
A `RigidBody` inside an `Area` with default settings and spatial override set to `Replace` behaves the same as a `RigidBody` outside of the `Area`, if the project physics settings have not been changed.

Actual behaviour:
The `Area` seems to apply very high actual angular damp even though it is set to the same value as the project physics settings (0.1).

**Steps to reproduce:**

1. Create a new project with a 3D scene
2. Add a floor `StaticBody`, a camera and maybe some lights
3. Add an `Area` and give it a collision shape. Set its spatial override to `Replace`
4. Add `RigidBody`s about to tip over inside and outside of the `Area`
5. Run the scene

**Minimal reproduction project:**
[bug_area_angular_damp.zip](https://github.com/godotengine/godot/files/4681600/bug_area_angular_damp.zip)

**Demo gif:**
![0001-0193](https://user-images.githubusercontent.com/11077553/82892070-5620cb80-9f3e-11ea-843b-a4ea4508968c.gif)

**Comment by madmiraal** [comment]
Only happens with Bullet physics. Godot physics is fine.

**Comment by AndreaCatania** [comment]
This is already fixed in 4.0 by this PR: https://github.com/godotengine/godot/pull/37314
Can we back port that change?

**Comment by akien-mga** [comment]
It requires updating bullet to a non-stable version, I'm not sure it would be a good idea for 3.2.x.
Might be better to document the bug then.

**Comment by madmiraal** [comment]
I've created a 3.2 backport of #37314: #39084. However, this issue still remains.

**Comment by Garmelon** [comment]
Well, that was quick. Thanks for the fix
