### ISSUE TITLE
Delete or rename files in browsing popups

### ISSUE THREAD

**Issue by Krzycho666** [godotengine/godot#3948]
It would be great, if we could delete file from browsing popups ( like 'Save Scene As' or 'Open Scene' ) by pressing Del ( so as it is made in FileSystem tab ), or rename it by pressing F2

**Comment by RayKoopa** [comment]
I implemented a menu to do some typical file and folder operations there, but I have an issue exactly with the deletion operation.

It would require calling the `DependencyRemoveDialog` to warn and fix any references, which in turn could open a search file `EditorFileDialog`, in which files could get deleted again, opening another `DependencyRemoveDialog`... that's ugly by itself, but even worse is I have no clue how to fix the stupid C++ include order there.

**Comment by Omaranwa** [comment]
lol c++ is ugly i prefer c# anyway

**Comment by Anutrix** [comment]
So this is partially fixed. Just  rename option is remaining.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
