### ISSUE TITLE
Godot integers are sliced to 32-bit integers when marshalled to Mono/C#

### ISSUE THREAD

**Issue by MichaelBelousov** [godotengine/godot#39609]
**Godot version:**

3.2 (hash: be5a47e75d), somewhat specifically a custom editor build with godot steam 3.2
which has no modifications except for the addition of the godot steam module to the trunk. It is a public github repository and I can link to it/include it if anyone wants to investigate.

**Issue description:**

When marshaling a godot int variant to the mono runtime/C#, a boxed 32-bit int is returned, slicing integers that only fit in a 64-bit integer, which godot supports. I am trying to use the GodotSteam engine module with C#, but SteamIds are 64-bit integers, and they are sliced when results are returned to C#. The engine code at: `modules/mono/mono_gd/gd_mono_marshal.cpp:557` (at line 557) marshals ints to a boxed 32-bit integer in the mono runtime. I have made some experimental changes sending to 64-bit. I wouldn't mind making a PR, but certainly pending discussion since I'm new to the godot engine, and this sounds like it could be a breaking change if all C# projects now
need to use the `long` type in C# to refer to godot ints.

```Cpp
case Variant::INT: {
  int32_t val = p_var->operator signed int();
  return BOX_INT32(val);}
```

**Steps to reproduce:**
1. Create any Godot project
2. add a C# script
3. access any godot function that returns an int (in my case it was GodotSteam's LobbyId)

**Minimal reproduction project:**
I can upload an example if necessary, but GodotSteam is rather intense of a minimal viable reproduction, and admittedly I'm having csproj issues building on my windows machine with a freshly installed mono-capable release version of 3.2, But here is my untested MVR.
[mvr-godot-slices-mono-ints.zip](https://github.com/godotengine/godot/files/4790075/mvr-godot-slices-mono-ints.zip)

**Comment by Calinou** [comment]
cc @neikeq

**Comment by neikeq** [comment]
The lines you mentions should indeed be changed to return an `long`:

https://github.com/godotengine/godot/blob/02f7908d460bea7d580fe7526949be7f294e6783/modules/mono/mono_gd/gd_mono_marshal.cpp#L628

However, that is for assigning `Variant::INT` to something that expects `object` (anything). In your example project that's not what's happening. Your method receives an `int` instead of a `long` so it's correct to slice it.
I think your example project doesn't reflect correctly the actual issue you're experiencing with GodotSteam.

**Comment by MichaelBelousov** [comment]
I think my problem is then in iterating an array (Godot.Collections.Array) of SteamIds returned from godotateam. I tried to use array.OfType<long>() (which obviously doesn't work). But why slice to a 32-bit integer when in a dynamically typed context?

**Comment by neikeq** [comment]
Yes, in a dynamically typed context it should be fixed to return `long` instead.

**Comment by MichaelBelousov** [comment]
I created a very small starting pull request #39629, please let me know if/how you want me to proceed, I drafted it for now.

**Comment by akien-mga** [comment]
Fixed by #39629.

**Comment by redthing1** [comment]
Pretty sure this is still broken:

In Godot 3.4.4

C# in debugger:
![image](https://user-images.githubusercontent.com/54390138/165689545-1471ad5e-b8c6-4213-8f66-bd4061deb787.png)

![image](https://user-images.githubusercontent.com/54390138/165689684-5474e2ba-9887-4fc7-b5d2-ca696d84fe9f.png)


output: 
![image](https://user-images.githubusercontent.com/54390138/165689703-3bd6eddb-8d9f-4725-b605-e3b69891d275.png)


GDScript:
![image](https://user-images.githubusercontent.com/54390138/165689736-fd7f3768-7b29-451c-82a4-b5d5fdc90e55.png)

**Comment by redthing1** [comment]
AH yes. https://github.com/godotengine/godot/blob/3.4/modules/mono/mono_gd/gd_mono_marshal.cpp#L576-L579
