### ISSUE TITLE
TileMap/GridMap breaks UndoRedo and makes the editor unusable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#39802]
**Godot version:**

4c0b077 and 3.2.2

**Issue description:**

This is related to #24970 #21528 and likely #39393

When you draw on TileMap or GridMap and Alt+Tab while holding mouse button, you will not be able to undo anymore when you refocus editor and click. Also any action that uses UndoRedo (including changing scenes) will fail and throw these errors
```
 core/undo_redo.cpp:373 - Condition "action_level > 0" is true. Returned: ""
 core/undo_redo.cpp:346 - Condition "action_level > 0" is true. Returned: false
```

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4826410/ReproductionProject.zip)

**Comment by akien-mga** [comment]
This is fixed for TileMap in #42489.

**Comment by Lucas-Pichette** [comment]
I'm currently still having the issue, version 3.2.3. I was alt-tabbing between Aseprite and Godot. Perhaps I clicked an Aseprite hotkey in Aseprite that caused some kind of weird mode? No visual queue popped up that I could tell, and a mode where you can't "undo" seems important to flag to the user.
