### ISSUE TITLE
C# Extension for VSCode generates an unresolvable "There are unresolved dependencies. Execute the restore command to continue" warning in a C# script upon opening.

### ISSUE THREAD

**Issue by Gustavo23** [godotengine/godot#39907]
**Godot version:**

3.2.2

**OS/device including version:**

 Windows 10 Pro Insider Preview, build 19603

**Issue description:**

I tried migrating my project from 3.2.1 to 3.2.2, and started receiving this warning no matter what I did. Then, I tried creating a blank project, and could reproduce the bug as well.

**Steps to reproduce:**
1) Setup VSCode for Godot + C# (like this tutorial from gamesfromscratch: https://www.youtube.com/watch?v=Do0YZocTu80
2) Create a new project on 3.2.2
3) Create any node, attach a .cs script
4) Open it on VSCode

**Minimal reproduction project:**

[sfsfssfsf.zip](https://github.com/godotengine/godot/files/4841637/sfsfssfsf.zip)

**Comment by JupiterRider** [comment]
Had the same "issue": https://github.com/godotengine/godot/issues/39874

**Comment by akien-mga** [comment]
As mentioned in #39874, building the project in Godot 3.2.2 should fix it.

**Comment by ratkingsminion** [comment]
If by "building the project" is meant to click on the "Build" button in Godot, that doesn't fix it for me. I have Windows 10 and Godot 3.2.2 as well. The "There are unresolved dependencies" dialog always appears for me, no matter what I try.

**Comment by Gustavo23** [comment]
@ratkingsminion yeah, the button didn't work for me either. What ended up working was downloading nuget and running nuget restore. And I must do it for every new project on 3.2.2

**Comment by ratkingsminion** [comment]
Yeah, same. I tried dotnet restore first, believing it does the same, but that wasn't the case.

**Comment by LordBrkica** [comment]
Hi,

I am using Newtonsoft.Json in my project and I have the same problem in Visual studio code.
I work in Windows 10 and in editor have MSBuild selected.

The thing is - I am able to build the project in Godot, but when I go to VSC my
`using Newtonsoft.Json`
is not recognized. 

I tried using _nuget restore_ and _nuget install_ but to no avail.

Is dotnet CLI supported ?
