### ISSUE TITLE
CircleShape2D weird behavior with Moving Platforms

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#40256]
**Godot version:**

3.2.2.stable.official

**OS/device including version:**

Solus 4.1 Gnome 3.36.3

**Issue description:**

Using a CollisonShape2D with a CircleShape2D causes KinematicBody2D to behave weirdly when dealing with moving platforms. Check the minimal reproduction project for implementation details.

Bugs noticed:
- When the platform moves up the Player can't jump
![moving-platform-jump-bug](https://user-images.githubusercontent.com/10171059/87155463-604e1d80-c291-11ea-9cd3-8f9ab667b8f8.gif)

- If `CollisionShape2D.one_way_collision = true` the above bug is fixed but the KinematicBody2D some times passes through the platform
![one-way-collision-bug](https://user-images.githubusercontent.com/10171059/87155473-63e1a480-c291-11ea-8ab6-ee3d22446479.gif)

Both problems are fixed when using a RectangleShape2D

![rectangle-fix](https://user-images.githubusercontent.com/10171059/87155617-a1463200-c291-11ea-9432-776c19c9af32.gif)

**Steps to reproduce:**
1. Implement basic movement using `KinematicBody2D.move_and_slide_with_snap()`
2. Implement moving platforms with `KinematicBody2D.sync_to_physics = true` and an `AnimationPlayer`, optionally set the `AnimationPlayer.playback_process_mode = ANIMATION_PROCESS_PHYSICS`
3. Use `CircleShape2D` on the Player's `KinematiBody2D/CollisionShape2D.shape`
4. Animate the Platform moving up and down
5. Jump on the platform and try to jump on it when it goes up
6. Set the Platform's `KinematicBody2D/CollisionShape2D.one_way_collision = true`
7. Repeat step 5 with quick hops

**Minimal reproduction project:**

[circleshape-bug-minimal-project.zip](https://github.com/godotengine/godot/files/4903142/circleshape-bug-minimal-project.zip)

**Comment by Xrayez** [comment]
Perhaps could be fixed by #36280?

**Comment by henriiquecampos** [comment]
> Perhaps could be fixed by #36280?

Maybe the second issue, but I can't see how it would fix the first one, the one that prevents jumping when the platform moves up.

**Comment by pouleyKetchoupp** [comment]
Both issues are fixed by #42574, closing.

**Comment by henriiquecampos** [comment]
> Both issues are fixed by #42574, closing.

Just tested Godot 3.3.stable.official, and they are not fixed. On top of that, now moving platforms with one-way collision also squash players, which makes so that the `one_way_collision` property is useless

**Comment by pouleyKetchoupp** [comment]
> When the platform moves up the Player can't jump

Indeed, I can confirm this is still not fixed.

> If `CollisionShape2D.one_way_collision = true` the above bug is fixed but the KinematicBody2D some times passes through the platform

This one seems to be fixed though. Are you still able to reproduce it?
