### ISSUE TITLE
Poor GPU Performance in Editor

### ISSUE THREAD

**Issue by thedaneeffect** [godotengine/godot#40499]
**Godot version:**
v3.2.2.stable.official (Steam)

**OS/device including version:**
Intel i7 9750H @ 2.60GHz
16GB DDR4 @ 1333MHz
NVIDIA GeForce RTX 2060 6GB
Windows 10 Pro 64-bit (Build 18362)
[CPU-Z Dump](https://puu.sh/G8v7h/ca22fc91be.html)
GLES 3 **and** 2

**Issue description:**
High GPU usage in empty editor.

[2D View](https://puu.sh/G8v4A/87425aa7a9.png)
[Task Manager](https://puu.sh/G8v61/1a67527397.png)
[RenderDoc Dump](https://puu.sh/G8vcn/53d71fdcd7.rdc)

[3D View](https://puu.sh/G8v3d/efd028715c.png)
[Task Manager](https://puu.sh/G8v6t/6524d6f35f.png)
[RenderDoc Dump](https://puu.sh/G8vcz/8598aad76e.rdc)

**It appears this is a non-issue in 3.1.**

**Steps to reproduce:**
Create a new project and analyze Task Manager.

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
I'll take a look at your render doc dumps in more detail. But I'll be honest, the issue likely lies in your hardware, drivers, or some combination of both. The fact that the issue is present in 3D, 2D, GLES2 and GLES3 points to it being an issue on your end. 

Do you get good performance running other GPU intensive programs? I'd try profiling while running a game and profiling while running blender. 

Another thing. Make sure VSync is on. If VSync is off, GPU programs will saturate your GPU because they will just render more frames. So check in your Godot project settings, and check in the Nvidia control panel to make sure you haven't forced VSync off.

**Comment by Calinou** [comment]
Try enabling **Editor > Interface > Show Update Spinner** in the Editor Settings. Does the spinner in the top-right corner spin continously? If so, this hints at the "redraw only when needed" feature being broken.

**Comment by thedaneeffect** [comment]
> I'll take a look at your render doc dumps in more detail. But I'll be honest, the issue likely lies in your hardware, drivers, or some combination of both. The fact that the issue is present in 3D, 2D, GLES2 and GLES3 points to it being an issue on your end.
> 
> Do you get good performance running other GPU intensive programs? I'd try profiling while running a game and profiling while running blender.
> 
> Another thing. Make sure VSync is on. If VSync is off, GPU programs will saturate your GPU because they will just render more frames. So check in your Godot project settings, and check in the Nvidia control panel to make sure you haven't forced VSync off.

I get pretty good performance (100fps+) running most modern games on high levels of detail.

VSync hasn't been overridden. Just in-case I overrode it in my control panel to enable. That didn't change anything.

> Try enabling **Editor > Interface > Show Update Spinner** in the Editor Settings. Does the spinner in the top-right corner spin continously? If so, this hints at the low-processor mode being broken. I changed how the sleep duration is calculated in #36052, but I haven't heard of any regressions before.

It does appear to be spinning continuously. After I clicked and set it to **Update when Changed** then it appears to solve the high GPU usage when idle and in an empty scene.

I wonder if that has to do with my monitor being 144Hz?

**Comment by clayjohn** [comment]
@thedaneeffect That does sound like the cause. To check, you can enable "View FPS" which is in the "Perspective" menu in the top left corner when you are in the 3D viewport.

**Comment by Calinou** [comment]
@thedaneeffect Did you check **Editor > Interface > Update Continuously** in the Editor Settings? If so, that's why the editor is constantly redrawing.

This option should be used for debugging purposes only. Since 3.2.2, there's no practical reason to enable it anymore.

**Comment by thedaneeffect** [comment]
> @thedaneeffect That does sound like the cause. To check, you can enable "View FPS" which is in the "Perspective" menu in the top left corner when you are in the 3D viewport.
> 
> @Calinou Funny enough, I have a 60hz monitor and when I have the update thing showing it doesnt move, but my FPS hovers at 144. It appears to still update as well because the FPS changes slightly periodically.

Yeah my FPS sticks to whatever interface/editor/low_processor_mode_sleep_usec is set to, which I'm sure was the goal. I can lower my GPU usage by increasing that to say 16666 to cap at 60FPS.

I'm having a difficult time pinpointing what could possibly be optimized as I find it hard to believe that my GPU (even at 144Hz) would have higher usage with a 2D scene than a 3D.

(Same exact shader used, except set to Spatial in 3D)

[2D Scene](https://puu.sh/G8wwk/6276f00194.png) (2 Quads)
[GPU Usage](https://puu.sh/G8wx2/199eac2528.png) 96.8%

[3D Scene](https://puu.sh/G8wtL/c20f4c5073.png) (4 Quads)
[GPU Usage](https://puu.sh/G8wuC/17a2868181.png) 33.8%

**Comment by clayjohn** [comment]
I have run your reproduction project. Initially there was no noticeable GPU usage so I turned **Editor > Interface > Update Continuously** on. 

Test scene - default:
2D: 0%
3D: 0%

With the editor updating continuously I got:
2D: 17%
3D: 7%

With Vsync turned off:
2D: 60%
3D: 45%

My hardware is:
CPU: FX-6300
GPU: RX 5600 xt (roughly equivalent to RTX 2060)

I think there are 2 problems.

#### 1. Editor is updating continuously for you even when set to off.

It seems your editor is updating at 144 FPS even while set not to update at all. This is causing much higher GPU usage than it should.

#### 2. Vsync not working

Given that our GPUs are roughly equivalent, we should see similar performance. However, you are still maxing out your GPU on a relatively simple scene. Given that your MRP has vsync enabled. I am guessing Vsync just isnt working at all. Try enabling "vsync with compositor" in the project settings to see if that helps at all.

#### Additional thoughts

Im not sure that the task manager even provides an accurate reading of GPU usage.

**Comment by thedaneeffect** [comment]
@clayjohn I enabled VSync with Compositor with no difference.

On your thought about Task Manager, I believe it is accurate. I tested with GPU-Z and they have identical results. https://puu.sh/G8x91/b2c6bb57d7.png

**Comment by lawnjelly** [comment]
Part of the difference in GPU between 2D and 3D could well be fill rate and blending in the editor.

2D relies on painter's order and possibly a lot more blending than necessary - there could be a lot of overdraw. I don't know whether this is the reason for the 3D / 2D difference, but it's something we might investigate in 4.x. Using z buffer for opaque 2d rather than relying on painters order could potentially be a lot faster because of early Z, I don't know though, it needs investigation.

**Comment by Hromon** [comment]
Maybe this problem is related to GPU offloading?
When high power is not required from the video card, it drops the frequency to save energy and, accordingly, the load at a reduced frequency is higher in percentage than at a normal frequency.

**Comment by thedaneeffect** [comment]
> Maybe this problem is related to GPU offloading?
> When high power is not required from the video card, it drops the frequency to save energy and, accordingly, the load at a reduced frequency is higher in percentage than at a normal frequency.

Unfortunately, while that sounds like a reasonable explanation, it is evident in this [screenshot](https://puu.sh/G8x91/b2c6bb57d7.png) that my GPU actually raised its frequency and increased power usage to compensate for the load.

**Comment by TheDuriel** [comment]
Still likely that its a windows issue combined with your godot configuration. It may be that windows fullscreen optimizations are interfering with things. As they often can do.

The renderdoc output is kinda funny. Not doing anything fancy. But drawing the empty selection highlight in the file dock takes up nearly the entire frame worth of time.
![image](https://user-images.githubusercontent.com/44248915/87885209-720f8d80-ca14-11ea-95c1-041983e5e670.png)

**Comment by clayjohn** [comment]
@TheDuriel You can't trust renderdoc frame timings. Each time you measure timings you will get different draw commands stalling in the above capture. The fact that it is periodic stalls could point to the issue being a memory transfer issue or a GPU/CPU sync issue.

**Comment by hazarek** [comment]
<img width="913" alt="cap 1" src="https://user-images.githubusercontent.com/36481442/89049184-8a0ed780-d359-11ea-839d-0fa78dd1c55f.png">
GPU is 100%. macbook fans runs at full speed when play animation tree.

**Comment by mg979** [comment]
By the way I have a similar problem. Godot 3.2.3 on Windows 10, gpu is NVIDIA GeForce GTX 1050 on a Dell laptop.

#### with a loaded (non empty) 2d scene:

The update spinner spins continuously, in the 3d view it shows ~145 fps, even if I set vsync on. GPU __on idle__ usage can vary:

- empty 3d: 5-15%
- 2d without grid: about the same
- 2d with grid: 25-30%

I don't understand why the editor is continuosly redrawn even if I don't touch a button and I don't even move the mouse.

#### with a new empty scene:

The update spinner spins occasionally, gpu usage is 0-5%. In the 3d view, it still shows ~145 FPS

**Comment by clayjohn** [comment]
@mg979 thanks for adding your report. I wonder if this could be an issue with systems running both intel integrated chips and NVidia chips.

 If I were you I would dig around in your NVidia control panel and see if you are overriding vsync anywhere. You also might have luck digging around in power management settings.

**Comment by lawnjelly** [comment]
The editor spinning continuously is usually either because you have something animated in the scene, or because of a bug causing continuous updates such as the one I fixed here #43272. Although that one I don't think was in 3.2.3.

I've been in favour of splitting these update requests into 2 categories, essential (e.g. GUI), and non-essential (e.g. animations), and giving the user the option to switch off the latter.

But as clayjohn says ultimately here it seems like the vsync (or the editor low process sleeping is not working, or both). Maybe the request overrules the low processor stuff in which case vsync is normally the rate limiter, I'm not sure, @Calinou would know.

This seems to be similarish to the problem often seen on Macs.

**Comment by Calinou** [comment]
> But as clayjohn says ultimately here it seems like the vsync (or the editor low process sleeping is not working, or both). Maybe the request overrules the low processor stuff in which case vsync is normally the rate limiter, I'm not sure, @Calinou would know.

Constant redrawing will always be taxing, no matter if it's done at 60 FPS or 145 FPS.

**Comment by Calinou** [comment]
@thedaneeffect Can you (or anyone else) still reproduce this bug in [Godot 3.3.3](https://godotengine.org/article/maintenance-release-godot-3-3-3) or any later release?

**Comment by thedaneeffect** [comment]
> @thedaneeffect Can you (or anyone else) still reproduce this bug in [Godot 3.3.3](https://godotengine.org/article/maintenance-release-godot-3-3-3) or any later release?

I reopened my project attached above and it doesn't seem to have high GPU usage anymore! This is with Editor>Interface>Update Continuously toggled on and off. 

Update Continuously off: 
![image](https://user-images.githubusercontent.com/3468354/136040353-daf52ebf-a622-4a06-85a2-e5d134127696.png)

update Continuously on: (expected, since my GPU isn't overclocking itself yet)
![image](https://user-images.githubusercontent.com/3468354/136040514-52710c99-57ba-4f63-a75f-d68bd0368e37.png)

It hovers around 10-20% but I agree with clayjohn, the reading in task manager might not be accurate since it's probably based on the current clocking on my GPU.

Definitely a huge difference either way!

**Comment by Calinou** [comment]
Alright, closing then :slightly_smiling_face:
