### ISSUE TITLE
Sprite3D View Frustum Culling Issue on Android

### ISSUE THREAD

**Issue by Ralf12358** [godotengine/godot#40531]
**Godot version:**
Head on Branch 3.2; 89f57ae12244f3269c9e3fe4684e16ec1fd2c989

**OS/device including version:**
GLES2, Android. Tested with Galaxy S7 Edge and Amazon Fire HD 8 

**Issue description:**
On Android Sprite3D Is culled as soon as the origin is out of the view frustum - without considering the size of the sprite. Works correct on Desktop (Linux) and Browser. Other platforms (iOS) are not tested

**Steps to reproduce:**
Create new 3D Scene. Add camera. Add Sprite3D. Position Sprite3D to have the origin outside of the view frustum, but parts of the sprite inside the view frustum. View Scene: On Desktop the partial sprite is shown correctly, whereas on Android the complete sprite is culled.

**Minimal reproduction project:**
See attached minimal project:

[GodotBug.zip](https://github.com/godotengine/godot/files/4945994/GodotBug.zip)

**Comment by Calinou** [comment]
This has most likely been fixed in https://github.com/godotengine/godot/pull/39867 (in addition to performance improvements). In the meantime, you should use MeshInstance + PlaneMesh or QuadMesh to improve performance and avoid this issue.

**Comment by Ralf12358** [comment]
Just to be sure: I'm on **head** on the 3.2 branch. This should include all fixes from the 3.2.3beta1, right? So, it is probably not fixed. 
With the regular 3.2 release: Sprite3D was unusable with less than 1 FPS.
As you suggested I'm now using a QuadMesh, I experiencing a new Android specific issue with pngs with alpha channels. I would like to report a new bug, but before doing so I would make sure to use the newest 3.2 branch.

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
@Calinou are you sure? The OP says that it works fine on desktop but fails on Android. Sprite3D does have an AABB and I think the VisualServer generates another one when the mesh is set. 

I'll have to look in more detail.

**Comment by clayjohn** [comment]
Confirmed on Windows 10.

**Comment by akien-mga** [comment]
Fixed by #40559.
