### ISSUE TITLE
Camera3D view visible in 2D editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40553]
**Godot version:**

173ebe487

**Issue description:**

Title.
![image](https://user-images.githubusercontent.com/2223172/87994060-58da1000-caec-11ea-9456-e7ef2d9ef532.png)
![image](https://user-images.githubusercontent.com/2223172/87994070-60011e00-caec-11ea-9244-eaf5adce6e62.png)

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/4950381/ReproductionProject.zip)

**Comment by Calinou** [comment]
This has been the case since the beginning of the `vulkan` branch. This might be intended behavior (for those designing HUDs in 3D games), so we may want to keep it as an option.

**Comment by akien-mga** [comment]
It seems fixed in a4f70d7e6cb2b83f152717a69c9c042dd9424fc9, or I can't reproduce. Can you confirm?

**Comment by KoBeWi** [comment]
I can still reproduce in 5bb7c7c36
Just run the MRP and switch to 2D view.

**Comment by KoBeWi** [comment]
This might be caused by the fact that Viewport has no longer 2D/3D usage property.
Also I didn't mention it, but it only happens when there is a Camera3D on the scene.
