### ISSUE TITLE
Tooltips target the wrong item and keep blinking in scene tree and script list

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#41261]
**Godot version:**
Master d3b5c0948c943b3fbcb4b5322262c59c92abfa83

**OS/device including version:**
Windows 10

**Issue description:**
On Windows, tooltips in the scene tree or script list show information about the wrong item and keep blinking.
Example in the scene tree:
<img src="https://user-images.githubusercontent.com/1075032/90272004-04148580-de5d-11ea-8d31-65bb5f11b25e.gif" width="200" />

**Steps to reproduce:**
Case 1. In any scene, hover on a node in the scene tree panel.
Case 2. In the script editor, hover on a script in the list.

**Minimal reproduction project:**
Can be easily reproduced in any project.

**Comment by akien-mga** [comment]
Is this also caused by #41164 / fixed by #41332?

**Comment by EricEzaM** [comment]
Can reproduce on Win 10 1903.

Sometimes the tooltip doesn't even show for me in the scene tree dock. Seems like the offset is wrong or something. Also, the tooltip doesn't always flicker for me. See the latter half of this video, where I hover some buttons which do not flicker:

![image](https://user-images.githubusercontent.com/41730826/90453687-a15d0b80-e134-11ea-9eab-141eef55ad1a.png)

Additionally, during testing of my PR #41321 I noticed that when I hovered over the buttons in the output log, those with shortcuts set did flicker, but those without shortcuts did not flicker. See below:

![flickring_shorcuts](https://user-images.githubusercontent.com/41730826/90453884-1defea00-e135-11ea-8f30-86704a4cc3aa.gif)

**Comment by pouleyKetchoupp** [comment]
@akien-mga It's not related, I can still reproduce the issue after reverting #41164.

**Comment by Xrayez** [comment]
Yes I've seen this before, but never got to report the issue, assumed it's still WIP.

**Comment by EricEzaM** [comment]
Is this specific to windows (issue has label `platform:windows`)? I have a PR with a fix ready to go but I did not touch any windows specific code. Could someone with Mac/Linux please test to see if they experience this too?

**Comment by pouleyKetchoupp** [comment]
@EricEzaM I thought it was all Windows only when I entered the issue, but it appears the blinking is Windows specific, while the tooltip targeting the wrong item is also on Mac and Linux. You can ping me on your PR and I'll test on Mac/Linux.

**Comment by EricEzaM** [comment]
@pouleyKetchoupp dang it... the above PR did not solve all flickering issues. I still get flickering under certain conditions - not sure on specifics.

![flickering1](https://user-images.githubusercontent.com/41730826/93411539-b5845c00-f8de-11ea-9e73-c621d8837fa6.gif)
![flickering2](https://user-images.githubusercontent.com/41730826/93411568-c634d200-f8de-11ea-9700-2e9a9bd1387f.gif)
