### ISSUE TITLE
Negative lights not working as expected

### ISSUE THREAD

**Issue by Hevedy** [godotengine/godot#41901]
**Godot version:**
v3.2.2.stable (Mono version)

**OS/device including version:**
Windows 10 Pro
Intel i7 (Old Gen)
Nvidia 970GTX with 441.20 driver.

**Issue description:**
At using negative lights at any Tonemap other than linear one the negative lights don't work anymore (Only work on 1 of 4).
Affects all lights.

**Steps to reproduce:**
1.) Download the provided project.
2.) Check the first scene in the project and the projected light from the spotlight.

**Minimal reproduction project:**
[ShowcaseIssues.zip](https://github.com/godotengine/godot/files/5195098/ShowcaseIssues.zip)

**Comment by clayjohn** [comment]
It looks like values are getting written below 0. I guess there needs to be a check to ensure that values are clamped at 0

**Comment by Yetizone** [comment]
Hello, I'm interested in working on this. I've downloaded the project and I see the light working as follows:
![Screenshot from 2020-09-10 18-09-22](https://user-images.githubusercontent.com/43905913/92751809-0224e000-f391-11ea-9c06-6886fee6dd4a.png)
From what I'm understanding this behaviour is undesired.
What's the expected one ? Should the red circle in the middle not be there and instead just be black ?

**Comment by Hevedy** [comment]
Yeah should all black, the red circle happen because is overflow of the values outside of linear postprocess

**Comment by clayjohn** [comment]
@Yetizone set the tonemap mode to ``linear`` and you will see the desired outcome. It is just an all black circle.

**Comment by Yetizone** [comment]
I see, thanks for the tip !

**Comment by akien-mga** [comment]
Fixed by #42056.

**Comment by Yetizone** [comment]
This issue still happens in master. I think it should remain open for now.

I noticed the PR targeting 3.2 with a fix got merged so I'll write one for master now.
