### ISSUE TITLE
MultiMeshInstance's Populate function resets the Color Format to None

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#42223]
**Platform**
Windows 10, Godot 3.2.3

**Steps to Reproduce**
1. Create a MultiMeshInstance and two meshes to use as Target and Source.
2. In the MultiMeshInstance set the Color Format to Byte or Float.
3. Use the populate function to generate instances with your meshes.
4. Observe how Color Format is set back to None (be aware you cannot set the Color Format after populating, since Instance Count has to be zero to change Color Format).

**Comment by Calinou** [comment]
@Arnklit Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by clayjohn** [comment]
Looks like this line just needs to pull color format from the existing multimesh https://github.com/godotengine/godot/blob/ebf3bad571c56fff37bfbc697596dbe503ea5fab/editor/plugins/multimesh_editor_plugin.cpp#L161

**Comment by Arnklit** [comment]
Ah it looks like clayjohn might have already found the issue, but I created the reproduction project if you need it.

Simply open the attached project and the test scene and look at the MultiMesh in the MultiMeshInstance. You'll see that its Color Format is set to Float, then if you use the Populate function on the MultiMeshInstance you'll see that the Color Format get's reset to None and there'll be no way of changing it without removing the instances.

[MultiMeshInstanceExample.zip](https://github.com/godotengine/godot/files/5256936/MultiMeshInstanceExample.zip)

**Comment by gvekan** [comment]
Hello! I would like to try to fix this issue. I'm new to developing on Godot Engine and after looking at this issue I saw that the master branch does not contain any Color Format options. Am I supposed to work on and push to the 3.2 branch then?

**Comment by gvekan** [comment]
After some investigation, I found that when Populating the MultiMeshInstance:

- Transform Format is set to 3D
- Color Format is set to None (this issue)

Because the instance count goes up when populating, we are prevented to change Color Format, Transform Format and Custom Data Format.

Are these expected behaviors (except this issue)? 

@clayjohn Is this a good solution? `multimesh->set_color_format(node->get_multimesh()->get_color_format());`

**Comment by clayjohn** [comment]
@gvekan I think so. You should also do something similar with custom_format. 

Once you make a PR also make sure to test and make sure that there are no issues from having uninitialized memory. If there are, you may have to set the colors to white when populating the multimesh.

**Comment by Hyperion101010** [comment]
Interesting in solving it can someone assign me this issue @Calinou

**Comment by akien-mga** [comment]
Fixed by #42298.

**Comment by wrstldev** [comment]
Problem is still occurring on **4.51 stable**.

Steps to reproduce are the same as above. You press the populate surface button, and the custom color and custom data boxes are reset to their unchecked state. Wouldn't it be easier just to let the user set their desired state in the populate surface dialog itself?

**Comment by Calinou** [comment]
@wrstldev Please open a new issue with a minimal reproduction project attached.
