### ISSUE TITLE
Imported FBX materials get cullmode set to disabled by default

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#42294]
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 x64

**Issue description:**

Imported Materials (from scenes) have their Cull Mode toggle set/changed to disabled by default (revertible)
![grafik](https://user-images.githubusercontent.com/8841352/94108046-e1ec2b00-fe3e-11ea-8f5f-75932ab49c54.png)

**Steps to reproduce:**
Open the attached project and reimport the 'Human.fbx'.  (This also happens with gltf), then check the newly created material parameters.

**Minimal reproduction project:**

[ReportProject.zip](https://github.com/godotengine/godot/files/5273858/ReportProject.zip)

**Comment by akien-mga** [comment]
What is the actual issue though? That the value is non-default, or that Cull Mode "Disabled" is not a good default for this material?

**Comment by Flavelius** [comment]
Both. And backface culling is the most reasonable default and standard.

**Comment by akien-mga** [comment]
All importers have code to set the Cull Mode to `CULL_DISABLED` if the original materials are double sided. Is this the case with this FBX?

**Comment by Flavelius** [comment]
Backface culling is enabled in blender on the material 
![grafik](https://user-images.githubusercontent.com/8841352/94118881-698d6600-fe4e-11ea-8466-8179e10b83eb.png)

**Comment by akien-mga** [comment]
Well in the case of FBX it forces `CULL_DISABLED` actually, and that seems to be an implementation bug:
https://github.com/godotengine/godot/blob/a6bb4f70e07edc52cb969548876a0b57abeef546/modules/assimp/editor_scene_importer_assimp.cpp#L979-L996

CC @RevoluPowered @fire 
Might be fixed in #41985?

For glTF or Collada, it seems fine:

https://github.com/godotengine/godot/blob/a6bb4f70e07edc52cb969548876a0b57abeef546/editor/import/editor_import_collada.cpp#L445-L447

https://github.com/godotengine/godot/blob/a6bb4f70e07edc52cb969548876a0b57abeef546/editor/import/editor_scene_importer_gltf.cpp#L1477-L1482

About having a non-default value in the first place, it's not a bug as shown by the above code, it's intended. Depending on the model's metadata, different options will be used, and this is one of them which gives a non-default cull mode.

**Comment by fire** [comment]
There was a bug with normal directions in the current code there should be an improvement  in latest pr. This settting is more hacky than desired.

On Sep 24, 2020, at 1:13 AM, Rémi Verschelde <notifications@github.com> wrote:

﻿
Well in the case of FBX it forces CULL_DISABLED actually, and that seems to be an implementation bug:
https://github.com/godotengine/godot/blob/a6bb4f70e07edc52cb969548876a0b57abeef546/modules/assimp/editor_scene_importer_assimp.cpp#L979-L996

CC @RevoluPowered @fire
Might be fixed in #41985?

For glTF or Collada, it seems fine:

https://github.com/godotengine/godot/blob/a6bb4f70e07edc52cb969548876a0b57abeef546/editor/import/editor_import_collada.cpp#L445-L447

https://github.com/godotengine/godot/blob/a6bb4f70e07edc52cb969548876a0b57abeef546/editor/import/editor_scene_importer_gltf.cpp#L1477-L1482

About having a non-default value in the first place, it's not a bug as shown by the above code, it's intended. Depending on the model's metadata, different options will be used, and this is one of them which gives a non-default cull mode.

**Comment by fire** [comment]
Can you review the newly merged FBX code? I think you'll have to use a nightly build.

**Comment by Flavelius** [comment]
with:
![grafik](https://user-images.githubusercontent.com/8841352/99395073-344a4500-28e0-11eb-973c-71c396f1258a.png)
it works as expected

**Comment by fire** [comment]
Can you also check the 3.2 branch?

**Comment by Flavelius** [comment]
I can't find a way to download a 'nightly' of it. Maybe someone else can do that.

**Comment by Calinou** [comment]
> I can't find a way to download a 'nightly' of it. Maybe someone else can do that.

Check this folder: https://archive.hugo.pro/builds/godot/3.2/

It's not exposed on my web page yet, but I've been meaning to do that.

**Comment by Flavelius** [comment]
It seems to work ~partially, it does not respect the backface culling setting in the material, but atleast it's set to 'back' by default.

And now that i retested both cases in 4.0 it seems i have misinterpreted something there (i clicked the restore arrow which set it to back which i thought to be the imported default, but it seems the override comes from the importer actually). It's set to disabled in either case there, so it is not working correctly. Plus, the material colors don't transfer correctly (materials are just plain white), which works for the 3.2.4 one though.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Comment by Calinou** [comment]
This likely still occurs with glTF due to https://github.com/godotengine/godot/issues/39936, but there's no point in having a separate issue open for FBX as this is the same underlying issue.
