### ISSUE TITLE
Using GDNative, NativeScript::_update_placeholder: generates unhelpful error message about !script_data

### ISSUE THREAD

**Issue by geekrelief** [godotengine/godot#42948]
**Godot version:**
3.2+

**Issue description:**
When using GDNative, placeholder scripts are used when the editor loses focus, and this error appears:
```
ERROR: _update_placeholder: Condition "!script_data" is true.
   At: modules/gdnative/nativescript/nativescript.cpp:92
```
I think it occurs when a library is unloaded. The failing condition doesn't seem to harm the execution of the app, and the error gives no clue as to how to resolve the error.

Questions about this error message come up repeatedly on Discord's gdnative-dev.  Can we comment out this error check, come up with better messaging, and or document it in the GDNative docs?  

The more gdnative libraries you have in your project the more of these errors are spammed, cluttering up the console output.

https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L91-L106
Looking at the engine code, I'm not sure what this is supposed to do.  script_data is not accessed in the function, and the error is not fatal.

**Steps to reproduce:**
Use gdnative, unfocus the editor, refocus the editor.

**Comment by Anutrix** [comment]
Should the two lines https://github.com/godotengine/godot/blob/6c173e2f7ffdb972ec3754b3d78fe51bfbfb4f22/modules/gdnative/nativescript/nativescript.cpp#L92-L94 really even be there?

**Comment by geekrelief** [comment]
They don't seem to do anything.  I just commented them out in my engine build.  And everything seems to be working fine.

**Comment by geekrelief** [comment]
Did some debugging and narrowed the issue.  It's caused by using multiple libraries / dlls and unfocusing and refocusing the editor.  https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L1895-L1920
In this loop, the GDNative library is reloading and loops through NSL->library_script_users to update placeholders, but if another library was unloaded and its script is looped over the error is triggered. 

I think the fix is to add a check inside of the library_script_users loop: if (L.key() != U.key()) continue;

**Comment by colugomusic** [comment]
Would be great if this could also be backported to 3.2. This message is so annoying that I am currently using a custom build with #43312 merged in.

**Comment by KoBeWi** [comment]
This is already resolved in 4.0, no?

**Comment by akien-mga** [comment]
Probably yes, since NativeScript is replaced by GDExtension in 4.0.

AFAICT it's not fixed in `3.x` yet though, as the PR aiming to solve it was targeting the `master` branch and wasn't remade for `3.x`: #46514.

**Comment by akien-mga** [comment]
Fixed by #66255.
