### ISSUE TITLE
KinematicBody2D doesn't collide with group of one way collision bodies

### ISSUE THREAD

**Issue by Rhathe** [godotengine/godot#43346]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

A KinematicBody2D enters the corner of a one way collision static body and doesn't register as a collision, which allows it to go through another one way collision static body that it will usually collide with.

![phase](https://user-images.githubusercontent.com/1882199/98318374-7bfdd200-1fac-11eb-9b7f-d76a24994d8d.gif)

It's expected to hit the right-most one way collision static body, as shown when the left one is disabled.

![collision](https://user-images.githubusercontent.com/1882199/98318410-9172fc00-1fac-11eb-9816-cacbc7b55ba5.gif)

**Steps to reproduce:**

Run the test project.

**Minimal reproduction project:**

[test_move_one_way_diagonal_phase.zip](https://github.com/godotengine/godot/files/5498546/test_move_one_way_diagonal_phase.zip)

**Comment by Rhathe** [comment]
This should be fixed by #38471

**Comment by madmiraal** [comment]
Also fixed with #42574.

**Comment by Rhathe** [comment]
> Also fixed with #42574.

I tested on the 3.2 version of #42574(#42575) and the bug still seems to be there.

**Comment by madmiraal** [comment]
You're right, it's not fixed by #42574.
