### ISSUE TITLE
Variants can be unintendedly reassigned to other objects (dangling Variants)

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#43422]
**Godot version:**
4.0 (b4a066188579458412159e35c697070cb5e77070)

**OS/device including version:**
N/A

**Issue description:**
A `Variant` can be reassigned to a different object if the one it was pointing to is freed and a new one is created afterward.
There's a protection against that, but only works on debug/release_debug with the debugger attached.

In 3.2 the situation is quite the same, so this proposal was created: https://github.com/godotengine/godot-proposals/issues/1589

**Steps to reproduce:**
Run the MRP directly from the command line, so the debugger is not attached, and therefore the checks that prevent the bug aren't active.
A non-tools, release build would work the same, but I think it's not working yet in 4.0.

**Minimal reproduction project:**
[Dangling Variant.zip](https://github.com/godotengine/godot/files/5513047/Dangling.Variant.zip)

For me, this project is enough to trigger the buggy behavior. For me, it prints `24377295608 24377295608` (the same number).

Note that depending on the compiler. OS, etc. the problem may require a more complicated example to show up.

**Comment by akien-mga** [comment]
Please include the exact commit, Variant has been changed twice a day lately :)

**Comment by SkanerSoft** [comment]
I confirm the error in my project. Godot 3.2.4.b1.
Everything is fine in debug mode, erroneous behavior only in release export.

**Comment by akien-mga** [comment]
The MRP gives me an error in current `master` (0a38d5c), so maybe the issue is fixed?
```
Attempt to call function 'get_instance_id' in base 'null instance' on a null instance.
```

**Comment by RandomShaper** [comment]
The problem happens by running it from the command line, so the debugger is not attached.

I've compiled latest _master_ and I still get the problem (same value). I've needed to tweak the project a bit to make it work after recent changes in Godot, but the script is the same.

**Comment by reduz** [comment]
It kinda looks like the wrong error is being thrown, though. In debug it should check the validity of the ID before calling the function.

**Comment by akien-mga** [comment]
Is this still relevant in any form nowadays?

**Comment by RandomShaper** [comment]
Not last time I checked, and it was long ago. I'll check once more tomorrow and close it myself if I can confirm it belongs to the past.

**Comment by RandomShaper** [comment]
Not reproducible anymore.
