### ISSUE TITLE
Rainbow sparks in the Visual Script editor

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#43702]
**Godot version:**

Godot v3.2.4-beta2

**OS/device including version:**

- Windows 10 (64-bit) version (build) 2009 (10.0.19042).
- Intel® UHD Graphics 620 driver version 27.20.100.8935.
- GLES3

**Issue description:**

In some of my scripts, rainbow sparks appear in the Visual Script editor, as shown [here](https://photos.app.goo.gl/BpysV88FfxUGrTEV6). I expected to see no sparks in the editor.

**Note:** I don't know if this will be related. In Godot v3.2.4-beta1, the Visual Script editor crashed on me every time which I reported in #43108. In Godot v3.2.4-beta2, it's not crashing anymore. However, I got the sparks as I had described.

In Godot v3.2.3-stable, no crash and no rainbow sparks occur.

**Steps to reproduce:**
1. Open the project.
2. Open the script (Look.vs). The rainbow sparks will appear.

**Minimal reproduction project:**

[3D Targeting System.zip](https://github.com/godotengine/godot/files/5570287/3D.Targeting.System.zip)

**Comment by Calinou** [comment]
It's likely a regression from GLES3 batching. cc @lawnjelly

**Comment by lawnjelly** [comment]
I can't actually see it reproducing but it may be similarish to this issue I fixed the other day:
https://github.com/godotengine/godot/issues/42899#issuecomment-726597797

I can probably track it down with some extra asserts for this condition, so I'll take a look.

**Comment by kreaninw** [comment]
I disabled the batching in the project setting. However, the issue still appears as shown [here](https://photos.app.goo.gl/o7MGYjBNBBakDeLe9).

**Comment by lawnjelly** [comment]
Yes I was coming round to the conclusion maybe it wasn't to do with the batching input data. Could have been the attribute inputs to the shader being uninitialized. But doh yeah should have asked you earlier to test without batching! :grin: 

That does narrow it down somewhat. You say you couldn't open the project in 3.2.4 beta 1, where there any earlier version of Godot you tried that it didn't or did exhibit this graphical behaviour?

**Comment by lawnjelly** [comment]
Just having a look in what time I had available this evening, the only thing I can think of is the buffer orphaning in the legacy renderer, it is possible I changed something I will look over tomorrow and see if anything could be problematic in comparison to any previous code. But in the meantime there are settings in the beta for changing buffer orphaning method:

`project_settings->rendering->options`

When not using batching (which should be the focus for finding this bug as it simplifies things), try different combinations of the bools in `api_usage_legacy`. They were primarily put in for mac users but it is worth trying in this case.

There was a refactoring from 3.2.3 to 3.2.4 for unified batching, but that shouldn't (hopefully) have affected any of the functionality or logic in the legacy renderer. So hopefully there are only a few possibles that could be causing this difference.

**Comment by kreaninw** [comment]
> Just having a look in what time I had available this evening, the only thing I can think of is the buffer orphaning in the legacy renderer, it is possible I changed something I will look over tomorrow and see if anything could be problematic in comparison to any previous code. But in the meantime there are settings in the beta for changing buffer orphaning method:
> 
> `project_settings->rendering->options`
> 
> When not using batching (which should be the focus for finding this bug as it simplifies things), try different combinations of the bools in `api_usage_legacy`. They were primarily put in for mac users but it is worth trying in this case.
> 
> There was a refactoring from 3.2.3 to 3.2.4 for unified batching, but that shouldn't (hopefully) have affected any of the functionality or logic in the legacy renderer. So hopefully there are only a few possibles that could be causing this difference.

With the batching and the buffer orphaning turned off, the issue still appears as shown [here](https://photos.app.goo.gl/4QHmwdQhLvuj8VR16).

Turning on flag stream will not help either, as shown [here](https://photos.app.goo.gl/RcjdV5cFu9k7zZR99). 

I tried different combinations as suggested by:

- With both the flag stream and the buffer orphaning turned on while the batching is turned off, the issue still appears as shown [here](https://photos.app.goo.gl/cts3GeCXG6msNQKx9).
- With the flag stream turned off and the buffer orphaning turned on (default setting) while the batching is turned off, the issue still appears as shown [here](https://photos.app.goo.gl/o7MGYjBNBBakDeLe9).

**Comment by lawnjelly** [comment]
Thanks for testing! :+1: 

There are some small differences since 3.2.3 I'll go over it with a fine toothed comb today, and add some error checking on the calling parameters and see if we can find out what is causing it.

Notably a couple of the old drawing funcs did not use buffer orphaning at all, which could lead to stall (which we were trying to prevent on mac), but may have ensured the buffer was filled with stale data which hid calling bugs.

**Comment by lawnjelly** [comment]
I'm just making a windows build which I'll post here which should emulate the old legacy behaviour when you switch `rendering->options->api_usage_legacy->orphan_buffers` to false. I'll post it up here when ready.

Then it will be interesting for you to try it (with batching switched off). 
I'm not holding out massive hopes on it fixing the issue, because orphaning should at worst cause a stall and performance problems, it shouldn't affect the visual result. But it may indirectly affect it if there was another existing bug depending on the old behaviour.

If it doesn't have an effect then I'm getting stumped. There weren't really a lot of changes in the legacy renderer. And it is also possible that it is something outside the renderer that is causing the problem (being called incorrectly, or driver problem). Really this is falling into that category of problems that is hardest to fix because I can't reproduce it here, and we haven't pinned down what is causing it - even knowing the primitive type would help massively. I am slightly suspecting the grid in the visual script editor but I'm not sure you can turn it off. So if you notice any problems in running projects or outside this particular feature in the editor that would help massively.

Just to double check, did you restart when turning off batching in the editor? The editor needs to restart for the change to take effect. And that is kind of easy to miss.

**Comment by kreaninw** [comment]
> I'm just making a windows build which I'll post here which should emulate the old legacy behaviour when you switch `rendering->options->api_usage_legacy->orphan_buffers` to false. I'll post it up here when ready.
> 
> Then it will be interesting for you to try it (with batching switched off).
> I'm not holding out massive hopes on it fixing the issue, because orphaning should at worst cause a stall and performance problems, it shouldn't affect the visual result. But it may indirectly affect it if there was another existing bug depending on the old behaviour.
> 
> If it doesn't have an effect then I'm getting stumped. There weren't really a lot of changes in the legacy renderer. And it is also possible that it is something outside the renderer that is causing the problem (being called incorrectly, or driver problem). Really this is falling into that category of problems that is hardest to fix because I can't reproduce it here, and we haven't pinned down what is causing it - even knowing the primitive type would help massively. I am slightly suspecting the grid in the visual script editor but I'm not sure you can turn it off. So if you notice any problems in running projects or outside this particular feature in the editor that would help massively.
> 
> Just to double check, did you restart when turning off batching in the editor? The editor needs to restart for the change to take effect. And that is kind of easy to miss.

I did restart the editor when turning off batching in the editor, as well as when I turning on or off the Api Usage Legacy options because the editor prompted me with the yellow message.

I can't find any option to turn the Visual Script's grid off. 

Out of my curiosity, I downloaded the source and compiled Godot 4.0 (with target=release_debug) to test out this issue. However, I can't even open my script (Look.vs) there as it always makes the editor to crash. And in 3.2.4 beta2, **only Look.vs** shows rainbow sparks while player.vs don't show any spark at all. I don't know whether it will be related to this issue, it's just the only thing that I noticed.

**Comment by lawnjelly** [comment]
> And in 3.2.4 beta2, only Look.vs shows rainbow sparks while player.vs don't show any spark at all.

It is all good relevant info. :+1: There might be an element in one script that is causing it and not the other. Or it may be a bit of Heisenbug and only appear when the conditions are right and it is just coincidence that one script causes it.

Trying it in Godot 4 won't yield that much useful info here sadly, as the vulkan renderer is completely different (and the driver).

What is interesting is that no one else has chimed in saying they've seen the same thing. That *could* be indicative of a driver bug, or at least we should consider it. If we don't get any more info from you running the test build, I think we'll just have to leave this open for a bit and see if anyone else reports it, or you see it in a different circumstance.

Also updating your graphics drivers is always a good thing to try, just in case.

I also put a load of extra validation code in the batching and ran it on the project but it didn't pick up anything amiss.

**Comment by kreaninw** [comment]
> > And in 3.2.4 beta2, only Look.vs shows rainbow sparks while player.vs don't show any spark at all.
> 
> It is all good relevant info. 👍 There might be an element in one script that is causing it and not the other. Or it may be a bit of Heisenbug and only appear when the conditions are right and it is just coincidence that one script causes it.
> 
> Trying it in Godot 4 won't yield that much useful info here sadly, as the vulkan renderer is completely different (and the driver).
> 
> What is interesting is that no one else has chimed in saying they've seen the same thing. That _could_ be indicative of a driver bug, or at least we should consider it. If we don't get any more info from you running the test build, I think we'll just have to leave this open for a bit and see if anyone else reports it, or you see it in a different circumstance.
> 
> Also updating your graphics drivers is always a good thing to try, just in case.
> 
> I also put a load of extra validation code in the batching and ran it on the project but it didn't pick up anything amiss.

I tried the test build with the latest Intel driver, but the issue still appears as shown [here](https://photos.app.goo.gl/VRyXYkmJNGtjkjCe6).

**Comment by lawnjelly** [comment]
> I tried the test build with the latest Intel driver

Ah well it was worth a try, thank you for trying. :+1: 

Did you have any luck with the special build linked here?
https://github.com/godotengine/godot/issues/43702#issuecomment-731601461

When you try it be sure to turn legacy `orphan_buffers` to off.

**Comment by kreaninw** [comment]
> > I tried the test build with the latest Intel driver
> 
> Ah well it was worth a try, thank you for trying. 👍
> 
> Did you have any luck with the special build linked here?
> [#43702 (comment)](https://github.com/godotengine/godot/issues/43702#issuecomment-731601461)
> 
> When you try it be sure to turn legacy `orphan_buffers` to off and `use_batching_in_editor` to off.

Wow, I tried the special build with the batching turned off which I had reported doesn't fix this issue. 

However, I tried it again **with both the batching and the orphan buffers turned off**, I see no rainbow sparks anymore.

(Turning both the batching and the orphan buffers off in the current 3.2.4 beta2 won't fix this issue, it only works in your special build.)

Thanks for looking into this issue. 👍

**Comment by lawnjelly** [comment]
Ah that is great news. :partying_face: 

That really pins it down, and if worst comes to worst, we can revert the legacy behaviour regarding orphaning. My hunch is that the new rendering code may actually be correct but something calling it is giving duff parameters, and the old lack of orphaning is hiding the bug.

**Comment by lawnjelly** [comment]
If the bug is occurring with batching on as well as in the legacy renderer, by a process of elimination it could well be in the polyline drawing (which is not batched, and uses the legacy method), it was the only bit that was hitting breakpoints while drawing the visual script editor.

I've spent a couple of days writing debugging and extensive parameter checking these legacy draw functions but I can't for the life of me spot what is going wrong, perhaps it needs a second pair of eyes. I did however find a couple of other bugs which weren't causing your issue but nice to fix at the same time.

My hunch was that because it was only occurring when orphaning was being done, the draw call was relying on stale data in the buffer in order to 'work' (or not show problems, more accurately). Orphaning should essentially result in a fresh blank or uninitialized buffer ready for upload. However I can't find anything obviously amiss in the data being sent or the drawcalls.

It does seem like it could be an off by one error, perhaps in the parameters being passed to draw the grid, but I can't work out why it would not occur when orphaning is not being used. Another notable thing that it occurred in one script and not the other, is that the script where it did occur had more nodes and was using a lot more drawcalls and perhaps buffer space?

We *could* revert this to non-orphaning behaviour, however, we now believe that non-orphaning with `glBufferSubData` is bad usage practice and can lead to stalls. So I'm inclined to keep a watch on this for now, see if anyone else reports it, or whether you see it in any other areas in the editor or in projects. It sounds like it is a minor annoyance at the moment, and given that it *could* be a driver issue, I wouldn't want to risk breaking something else unless we are sure. :+1: 

Incidentally another way to track this down would be for you to use a graphics debugger such as RenderDoc, which can record a frame where it goes wrong and you can step through the drawcalls to try and work out what is happening, or whether it is repeatable when you replay the frame (if not, this can indicate a driver bug). But if you are not familiar with graphics debuggers this would be too tricky, and it may not give us definite answers anyway.

**Comment by kreaninw** [comment]
> It does seem like it could be an off by one error, perhaps in the parameters being passed to draw the grid, but I can't work out why it would not occur when orphaning is not being used. Another notable thing that it occurred in one script and not the other, is that the script where it did occur had more nodes and was using a lot more drawcalls and perhaps buffer space?
> 
Yes, in the Look.vs which the rainbow sparks appear, there are a lot more Visual Script nodes than the player.vs where the rainbow sparks don't appear.

> Incidentally another way to track this down would be for you to use a graphics debugger such as RenderDoc, which can record a frame where it goes wrong and you can step through the drawcalls to try and work out what is happening, or whether it is repeatable when you replay the frame (if not, this can indicate a driver bug). But if you are not familiar with graphics debuggers this would be too tricky, and it may not give us definite answers anyway.

I tried to analyze the issue in the frame where the rainbow sparks occur with Intel's Graphics Performance Analyzers and RenderDoc in which both of them showed the rainbow sparks, as shown in the screenshots below:
![Screenshot 2020-11-22 170013](https://user-images.githubusercontent.com/1403194/99916746-b07ec700-2cea-11eb-938e-961e9c2d1426.jpg)
![Screenshot 2020-11-22 173039](https://user-images.githubusercontent.com/1403194/99916749-b4124e00-2cea-11eb-8987-78a668ce6e64.jpg)

However, the problem is I can't understand any of the data they showed me 😂 Therefore I uploaded the captured frames [here](https://drive.google.com/drive/folders/17XLgCgvAaN8QK7zkdhmWOmJIMOgTUPOZ?usp=sharing).

Or you can point me out where to look in the debuggers. ✌

**Comment by kreaninw** [comment]
I don't know if this will be related to this issue. But I noticed that when I recorded this phenomenon with the screen recorder software (OBS Studio), the rainbow sparks happened once in a while very slowly. However, the actual phenomenon that is happening is extremely buggy as the rainbow sparks appear very frequently like it's in the party.

I recorded the actual phenomenon with my phone and uploaded it [here](https://photos.app.goo.gl/vjorzS1eBZPZJgcQ7).

**Comment by lawnjelly** [comment]
Both the capture and the phone footage could be very useful. :+1: I managed to download the renderdoc frame (had to use firefox, I think chrome was blocking the filetype) and am having a look. :nerd_face: 

Can I just confirm does this frame show a 'spark' on your machine? Does it occur every time you replay the frame?

There is none here with replay, which does seem to indicate it is a difference in drivers as suspected, rather than godot outputting different API calls.

It would seem to narrow it down to 2 things,
* More likely - mine being more fault tolerant (and there being an error from our API calls)
* Less likely - your driver having a bug

If you can let me know which EID number (API call number I guess) causes the spark on yours that will help a lot.

**Comment by lawnjelly** [comment]
Also several of the legacy drawing functions use a rather dubious update method, which I did try to change a few weeks ago but it introduced a regression so was reverted.

The problem is they use a non-interleaved format, with data coming from different streams:
Positions (1 array), Colors (1 array), UVs (1 array) etc.

Each stream is individually copied to the vertex buffer with a glBufferSubData call. This is very inefficient as we believe each glBufferSubData can be very expensive, and also expose driver errors.

What I am meaning to do is either change the API for these functions, or make a temporary copy of all the data before sending it in one upload. Changing the API would likely be best but may be a bit more involved, and may not be possible if this is exposed via the visual server.

Making a local copy could be done but it just adds an extra layer of copying for no reason.

Driver bugs could occur if multiple glBufferSubData occur on the same buffer, and it mucks up the buffer renaming somehow. This could conceivably be causing the problem in your case, but I'll wait till you can let me know the EID number, maybe we are simply sending duff comands.

**Comment by kreaninw** [comment]
> Can I just confirm does this frame show a 'spark' on your machine? Does it occur every time you replay the frame?

With the same EID #, when I replayed the frame, it either showed a different spark or it didn't show any spark at all. The resulted frame even if it's in the same EID# is not consistent at all, as shown in the screenshots below:

**EID # 13477**
![Screenshot 2020-11-23 170121](https://user-images.githubusercontent.com/1403194/100010793-935ffc00-2daf-11eb-8ae7-f12f19b91b79.jpg)
![Screenshot 2020-11-23 170159](https://user-images.githubusercontent.com/1403194/100010812-9955dd00-2daf-11eb-9b35-4aacfab224e2.jpg)

**EID # 14449**
![Screenshot 2020-11-23 170720](https://user-images.githubusercontent.com/1403194/100011007-e3d75980-2daf-11eb-83ab-b4a589019ff9.jpg)
![Screenshot 2020-11-23 170736](https://user-images.githubusercontent.com/1403194/100011020-e9cd3a80-2daf-11eb-83c6-70c1b7137294.jpg)

**EID # 14635**
![Screenshot 2020-11-23 170801](https://user-images.githubusercontent.com/1403194/100011134-0e291700-2db0-11eb-9fed-0ab4f2338fde.jpg)
![Screenshot 2020-11-23 170835](https://user-images.githubusercontent.com/1403194/100011151-12edcb00-2db0-11eb-919b-07bd285f4ec7.jpg)

I uploaded this phenomenon with my phone [here](https://photos.app.goo.gl/vdAnA7ASoEAZrAFT8).

> If you can let me know which EID number (API call number I guess) causes the spark on yours that will help a lot.

The above EID numbers are just some examples that the spark occurred. In fact, any EID number is randomly showed the spark. Some even show 3 sparks at once as shown [here](https://photos.app.goo.gl/vdAnA7ASoEAZrAFT8) (0:24).

However, I noticed that the spark will not occur before the grid is being drawn (I could be wrong though). **EID # 3472** is the first frame that I saw the spark occurred.

![Screenshot 2020-11-23 174403](https://user-images.githubusercontent.com/1403194/100013715-0d927f80-2db4-11eb-9fb0-3956d23e6ce9.jpg)

**Comment by lawnjelly** [comment]
The 14635 may be down to how renderdoc works, if it replays the whole frame each time that may just be showing some random spark from earlier. I don't really know if it does that but I wouldn't be surprised.

More interesting is the other EIDs, they seem to be on drawing rects (single rects) which is surprising. It is possible something is misconfigured for the rect drawing on those calls, but what is weird is that the rect drawing code is completely different in batching and legacy (different shaders), and yet both show the sparks.

As the rect drawing seems fine elsewhere in the editor, if it is a problem on our side it could be something screwing up the vertex attribute settings for that shader.

**Comment by kreaninw** [comment]
This is still ocurring as of Godot 3.2.4 beta4 with Intel® UHD Graphics 620 driver version _updated_ to 27.20.100.9030 (from 27.20.100.8935).

**Comment by kreaninw** [comment]
I don't know if this will help. This issue is not occuring on [Godot Web Editor beta](https://godotengine.org/editor/).

I am on Windows 10 version 20H2 build 19042.685, Google Chrome 87.0.4280.88, Intel® UHD Graphics 620 driver version 27.20.100.9030.
