### ISSUE TITLE
Error message when trying to create some resources based on custom types

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#43758]
**Godot version:**
3.2.4 beta 2
Regression from beta 1

**OS/device including version:**
Windows 10

**Issue description:**
When i try to make some specific resources, i get error message in Output, and no resources is created. Only happened on some custom resources until now, from the qodot addon.
 `editor/filesystem_dock.cpp:1784 - Condition "!r" is true.`

Copying an existing resource of the same type works.

**Steps to reproduce:**
Open the reproduction project.
Try to make one of the following resources: QodotFGD(Base, Point or Solid)Class

**Minimal reproduction project:**

[qodot_test.zip](https://github.com/godotengine/godot/files/5578535/qodot_test.zip)

**Comment by akien-mga** [comment]
I haven't bisected yet, but maybe you have an idea about this @RandomShaper.

**Comment by RandomShaper** [comment]
Isn't this already fixed in the latest beta?

**Comment by akien-mga** [comment]
This is still reproducible in the latest `3.2` commit: a18df71789a36b318c40d691efdb4da1e574bbfd.

```
ERROR: _resource_created: Condition "!r" is true.
   At: editor/filesystem_dock.cpp:1788.
```

The MRP also triggers leaks on exit, which might or might not be related to this issue (might also just be a bug in that plugin):
```
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2138.
Leaked instance: HTTPRequest:17733 - Node name: HTTPRequest
Leaked instance: ProgressBar:17732 - Node name: ProgressBar
Leaked instance: HTTPClient:17734
Leaked instance: Timer:17737 - Node name: Timer
Leaked instance: ToolButton:17729 - Node name: ToolButton3
Leaked instance: Reference:17736
Leaked instance: Label:17731 - Node name: ProgressLabel
Leaked instance: TextureRect:17726 - Node name: TextureRect
Leaked instance: StreamTexture:17581 - Resource path: res://addons/qodot/icons/icon_qodot_spatial.svg
Leaked instance: HBoxContainer:17730 - Node name: HBoxContainer
Leaked instance: ToolButton:17727 - Node name: ToolButton
Leaked instance: ToolButton:17728 - Node name: ToolButton2
Leaked instance: StreamPeerTCP:17735
Leaked instance: VSeparator:17725 - Node name: VSeparator
Leaked instance: Image:17583 - Resource path: 
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:475.
Resource still in use: res://addons/qodot/icons/icon_qodot_spatial.svg (StreamTexture)
Orphan StringName: VSeparator
Orphan StringName: ToolButton
Orphan StringName: Reference
Orphan StringName: HTTPClient
Orphan StringName: _timeout
Orphan StringName: _texture_changed
Orphan StringName: ToolButton2
Orphan StringName: ToolButton3
Orphan StringName: Label
Orphan StringName: HBoxContainer
Orphan StringName: visibility_changed
Orphan StringName: minimum_size_changed
Orphan StringName: timeout
Orphan StringName: StreamTexture
Orphan StringName: StreamPeerTCP
Orphan StringName: size_flags_changed
Orphan StringName: TextureRect
Orphan StringName: Object
Orphan StringName: Timer
Orphan StringName: changed
Orphan StringName: queue_sort
Orphan StringName: Image
Orphan StringName: ProgressLabel
Orphan StringName: HTTPRequest
Orphan StringName: ProgressBar
Orphan StringName: _child_minsize_changed
StringName: 26 unclaimed string names at exit.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69.
```
