### ISSUE TITLE
[Bullet] [Needs Bullet Update] Crashing asserts in debug when using Bullet Physics with CCD enabled

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#43868]
**Godot version:**
Master 50db0e66ac8c00f176c706cee0c3a5469453acce

**OS/device including version:**
Windows 10

**Issue description:**
Bullet raises some asserts that cause crashes in some scenarios when using continuous collision with 3D rigid bodies.

This issue only happens on Godot 4.0, in debug or release_debug configuration, because these asserts have been enabled with PR #34236.

It's actually happening even when continuous collision is disabled at the moment, until PR #43801 is merged (it fixes Bullet bodies using continuous collision when they shouldn't).

More details in https://github.com/godotengine/godot/pull/42643#issuecomment-732296444.

**Steps to reproduce:**
- Open MRP
- Start game
- Wait for a moment for rigid bodies to be created and observe assert and crash

**Minimal reproduction project:**
[bullet-ccd-4.0.zip](https://github.com/godotengine/godot/files/5599457/bullet-ccd-4.0.zip)

**Comment by qarmin** [comment]
I can't reproduce crash in 4.0.dev.custom_build. ba048b8b6

**Comment by AndreaCatania** [comment]
I've fixed this issue in bullet with this PR: https://github.com/bulletphysics/bullet3/pull/3799. However, not sure this is still relevant anyway, so we may consider to close this or change to "update bullet".

**Comment by pouleyKetchoupp** [comment]
@AndreaCatania Amazing! We can keep this open, since it's still an issue until we update Bullet. I'll add a tag in the title to make it clear.

**Comment by akien-mga** [comment]
Fixed by #48300 (and fixed included in `master`, though bullet is disabled, in #48299).
