### ISSUE TITLE
Vulkan build error when compiling from Linux to Windows using MinGW (IDXGIFactory6)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#44637]
**Godot version:** Git https://github.com/godotengine/godot/commit/169159c8aac5807725594145bf029c0ff7ac8ef1

**OS/device including version:**

- Ubuntu 20.04 on GitHub Actions, with MinGW from the `mingw-w64` package and POSIX threads configured.
- Also reproduced on Fedora 33 with the MinGW package.

**Issue description:**

I'm in the process of [porting godot-builds-ci to use GitHub Actions](https://github.com/Calinou/godot-builds-ci/tree/switch-to-github-actions) and am running into a build error on my Windows targets.

The build fails due to a Vulkan/DirectX SDK issue:

```
thirdparty/vulkan/loader/loader.c: In function 'loader_create_instance_chain':
thirdparty/vulkan/loader/loader.c:6059:5: error: unknown type name 'IDXGIFactory6'; did you mean 'IDXGIFactory1'?
 6059 |     IDXGIFactory6* dxgi_factory = NULL;
      |     ^~~~~~~~~~~~~
      |     IDXGIFactory1
thirdparty/vulkan/loader/loader.c:6060:42: error: 'IID_IDXGIFactory6' undeclared (first use in this function); did you mean 'IID_IDXGIFactory5'?
 6060 |     HRESULT hres = fpCreateDXGIFactory1(&IID_IDXGIFactory6, (void **)&dxgi_factory);
      |                                          ^~~~~~~~~~~~~~~~~
      |                                          IID_IDXGIFactory5
thirdparty/vulkan/loader/loader.c:6060:42: note: each undeclared identifier is reported only once for each function it appears in
thirdparty/vulkan/loader/loader.c:6063:21: error: request for member 'lpVtbl' in something not a structure or union
 6063 |         dxgi_factory->lpVtbl->Release(dxgi_factory);
      |                     ^~
thirdparty/vulkan/loader/loader.c: In function 'ReadSortedPhysicalDevices':
thirdparty/vulkan/loader/loader.c:7088:5: error: unknown type name 'IDXGIFactory6'; did you mean 'IDXGIFactory1'?
 7088 |     IDXGIFactory6* dxgi_factory = NULL;
      |     ^~~~~~~~~~~~~
      |     IDXGIFactory1
thirdparty/vulkan/loader/loader.c:7089:42: error: 'IID_IDXGIFactory6' undeclared (first use in this function); did you mean 'IID_IDXGIFactory5'?
 7089 |     HRESULT hres = fpCreateDXGIFactory1(&IID_IDXGIFactory6, (void **)&dxgi_factory);
      |                                          ^~~~~~~~~~~~~~~~~
      |                                          IID_IDXGIFactory5
thirdparty/vulkan/loader/loader.c:7106:32: error: request for member 'lpVtbl' in something not a structure or union
 7106 |             hres = dxgi_factory->lpVtbl->EnumAdapterByGpuPreference(dxgi_factory, i, DXGI_GPU_PREFERENCE_UNSPECIFIED, &IID_IDXGIAdapter1, (void **)&adapter);
      |                                ^~
Compiling ==> thirdparty/vulkan/loader/unknown_ext_chain.c
thirdparty/vulkan/loader/loader.c:7106:86: error: 'DXGI_GPU_PREFERENCE_UNSPECIFIED' undeclared (first use in this function)
 7106 |             hres = dxgi_factory->lpVtbl->EnumAdapterByGpuPreference(dxgi_factory, i, DXGI_GPU_PREFERENCE_UNSPECIFIED, &IID_IDXGIAdapter1, (void **)&adapter);
      |                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/vulkan/loader/loader.c:7190:21: error: request for member 'lpVtbl' in something not a structure or union
 7190 |         dxgi_factory->lpVtbl->Release(dxgi_factory);
      |                     ^~
scons: *** [thirdparty/vulkan/loader/loader.windows.debug.64.o] Error 1
scons: building terminated because of errors.
```

We should either fix this on our end, or document what to do to fix this on the user's end.

**Steps to reproduce:**

On Linux, run `scons platform=windows` to compile Godot for Windows.

**Comment by akien-mga** [comment]
This is a mingw bug fixed in 8.0.

**Comment by Al-Shahrior** [comment]
I'm Using gcc (tdm64-1) 9.2.0
![image](https://user-images.githubusercontent.com/31450209/104188710-dea79a00-5443-11eb-8518-1ef3764d7fa0.png)

**Comment by siew24** [comment]
Current on commit 122a27523da45d68b98e53dc5d6ca2b95f908ad1,

The problem persists on MinGW 9.2.0

**Comment by Calinou** [comment]
@siew24 Can you try with llvm-mingw? This is how I fixed my Godot builds: https://github.com/Calinou/godot-builds-ci/commit/8f438f4d35e6a2fbcb6517e02e62fcc375e4b8d1

**Comment by akien-mga** [comment]
> The problem persists on MinGW 9.2.0

That version hasn't been released, the latest is MinGW 8.0.0. 
9.2.0 is the version of the GCC compiler that is included in your MinGW distribution, not the MinGW headers. You likely have MinGW 6.0.0 or 7.0.0.

**Comment by siew24** [comment]
> > The problem persists on MinGW 9.2.0
> 
> That version hasn't been released, the latest is MinGW 8.0.0.
> 9.2.0 is the version of the GCC compiler that is included in your MinGW distribution, not the MinGW headers. You likely have MinGW 6.0.0 or 7.0.0.

Thanks for the heads up! Now I have the incentive to just use MSYS2 to handle package version control XD

**Comment by RenFontes** [comment]
> @siew24 Can you try with [llvm-mingw](https://github.com/mstorsjo/llvm-mingw)? This is how I fixed my Godot builds: [Calinou/godot-builds-ci@8f438f4](https://github.com/Calinou/godot-builds-ci/commit/8f438f4d35e6a2fbcb6517e02e62fcc375e4b8d1)

I'm trying to use llvm-mingw. What should I add to the path? I added only the bin folder and I'm getting this error 
`[  5%] Linking Static Library ==> modules\libmodules.windows.tools.64.a
[  5%] scons: *** [modules\libmodules.windows.tools.64.a] The system cannot find the file specified`

I guess something is missing?

**Comment by Calinou** [comment]
@RenFontes I'm not on my Windows install right now, but I remember having to add two different folders to the `PATH` for llvm-mingw to work. Also, make sure to pass `use_mingw=yes use_llvm=yes use_lld=yes` on the SCons command line.
