### ISSUE TITLE
Editing the extents of a CollisionShape2D via script causes the one-way collision to stop working

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#45090]
**Godot version:**

3.2.4-beta5 (but the bug exists in other versions too)

**OS/device including version:**

Windows 8, nvidia

**Issue description:**

If you change the size of a CollisionShape2D extents via script, the one-way collision will stop working, although this will keep saying that it is enable when you print the `CollisionShape2D.one_way_collision`.

* Either way, the one-way collision can work again if you set the one_way_collision property as true again with `collider.one_way_collision = true` right after editing the extents.

**Steps to reproduce:**
Just edit the values of a ColisionShape2D extents via script, this will cause the one-way collision to stop working even if it says it is enabled.

**Minimal reproduction project:**

[one-way-collision-extents-bug.zip](https://github.com/godotengine/godot/files/5794128/one-way-collision-extents-bug.zip)

**Comment by Calinou** [comment]
This is likely fixed by https://github.com/godotengine/godot/pull/42574.

**Comment by AttackButton** [comment]
I tested it with the https://github.com/godotengine/godot/pull/42574 build, the bug is still there too. Did you tested the MRP?

**Comment by Calinou** [comment]
cc @pouleyKetchoupp
