### ISSUE TITLE
Editor spam: `!uniform_set is true` if the last uniform has been removed from the shader

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#45213]
**Godot version:**
c7fb7674c8f9163a717beaa922cd7e6c8aeb77b6

**OS/device including version:**
Win10/GTX1060

**Issue description:**
Shader spam errors to the output if the last uniform has been removed, due to `uniform_set_owner` in `rendering_device_vulkan` lacks a reference to the `uniform_set`.

**Steps to reproduce:**
![uniform_bug](https://user-images.githubusercontent.com/3036176/104758690-d5823a00-576f-11eb-933e-a3e55e202325.gif)

**Minimal reproduction project:**
[shader_bug.zip](https://github.com/godotengine/godot/files/5822088/shader_bug.zip)

**Comment by reduz** [comment]
Can you check this bug again? It may have been fixed.

**Comment by Chaosus** [comment]
@reduz Nope, as of ff85bbc41c4f7c416c04f29d59284097a84f41c3 it still happen.
