### ISSUE TITLE
Light2D mask breaks with TileMaps with YSort enabled

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#46154]
**Godot version:**

3.2.4.rc2

**OS/device including version:**

Windows 10

**Issue description:**

Light2D mask seems to mask some tiles and not mask other tiles on a TileMap with YSort enabled.

**Steps to reproduce:**
1. Make TileMap
2. Enable YSort

3. Put down some tiles
4. Make Light2D
5. Add texture and set mode to Mask
6. Move Light2D around tiles

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/6000304/Test.zip)

**Comment by lawnjelly** [comment]
This is a batching regression, it disappears with batching off. Will investigate. :+1:

**Comment by akien-mga** [comment]
Fixed by #46163.

**Comment by ShatReal** [comment]
So I cloned and compiled the latest commit in the 3.2 branch, and... it's still broken?

**Comment by Calinou** [comment]
@ShatReal Please open a new issue with a minimal reproduction project attached.

**Comment by lawnjelly** [comment]
> So I cloned and compiled the latest commit in the 3.2 branch, and... it's still broken?

I just retested with your test project, and it's working fine on mine. Maybe someone could independently verify this, or there could be a problem in your build where it isn't using the latest version for everything.

**Comment by akien-mga** [comment]
I tested the MRP and can confirm that the bug is reproduced in 3.2.4 RC 2 and *not reproduced* in 8651838268111b0bbb66c6ab57a0f42869b0e182 (Mageia 8, testing with Intel HD Graphics 630).

**Comment by ShatReal** [comment]
Sorry, I should have clarified. Yes, the issue is solved in the test project, but in my actual project, I still have the issue. I will try to recreate the issue again in another test project.

**Comment by lawnjelly** [comment]
> Sorry, I should have clarified. Yes, the issue is solved in the test project, but in my actual project, I still have the issue. I will try to recreate the issue again in another test project.

Just as a hint, if you are still getting it, one possibility is that it is reordering commands within an item, which might be another case that needs disabling when `light_masked` is set. It's quite easy to fix but easier to find / test with a project.

**Comment by ShatReal** [comment]
Okay, so once the Light2D mask didn't work out I started using a shader. Here is the new test project.
[Shader-Test.zip](https://github.com/godotengine/godot/files/6010985/Shader-Test.zip)
Instructions: flip ysort on the tilemap on and off and watch as the shader stops and starts working. The shader should make all tiles with y pos > 500.0 partially transparent.

Light2D seems to be working though.

**Comment by lawnjelly** [comment]
> Okay, so once the Light2D mask didn't work out I started using a shader. Here is the new test project.
> [Shader-Test.zip](https://github.com/godotengine/godot/files/6010985/Shader-Test.zip)
> Instructions: flip ysort on the tilemap on and off and watch as the shader stops and starts working. The shader should make all tiles with y pos > 500.0 partially transparent.
> 
> Light2D seems to be working though.

This turns out to be a different issue. It isn't related to batching, it occurs with batching on or off, so would need a separate issue (we try and work with one bug per issue, also it affects who will investigate it, if it is not a batching bug).

**Comment by ShatReal** [comment]
Okay, I will submit another issue.
