### ISSUE TITLE
GLES2 WebGL DEPTH_TEXTURE Feedback loop error

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#46883]
**Issue description:**
I am trying to use this snippet [https://docs.godotengine.org/en/3.2/tutorials/shading/screen-reading_shaders.html#depth-texture](https://docs.godotengine.org/en/3.2/tutorials/shading/screen-reading_shaders.html#depth-texture)
to create post-processing shader which uses pixels world position to calculate new color.

It doesn't seem to work on browser with GLES2 if modifying ALBEDO and console gets filled with:
`GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.`

However it seems to work with GLES3 on HTML5 but isn't GLES3 going to be deprecated for browser? Also for me HTML5 GLES3 projects loads longer when starting it.

Here is the shader:
```
shader_type spatial;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}

void fragment() {
	// https://docs.godotengine.org/en/3.2/tutorials/shading/screen-reading_shaders.html#depth-texture
	float depth = textureLod(DEPTH_TEXTURE, SCREEN_UV, 0.0).r;
	vec4 upos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV * 2.0 - 1.0, depth * 2.0 - 1.0, 1.0);
	vec3 pixel_position = upos.xyz / upos.w;
	
	// Lines below triggers the bug (on browser only)
	ALBEDO = vec3(1.0, 1.0, 1.0) * pixel_position.x;
}
```

On native and Godot editor the shader works as expected and you should see this:
![bug](https://user-images.githubusercontent.com/80432363/110716406-c8357900-820f-11eb-9b97-c66249e4c186.png)

**Godot version:**
3.2.3.stable.official

**OS/device including version:**
Linux with Nvidia Drivers (460.39) - WebGL with GLES2
Chromium 89

**Minimal reproduction project:**
[GLES2 Webgl Bug.zip](https://github.com/godotengine/godot/files/6119626/GLES2.Webgl.Bug.zip)

**Comment by Calinou** [comment]
> However it seems to work with GLES3 on HTML5 but isn't GLES3 going to be deprecated for browser?

Not if [this proposal](https://github.com/godotengine/godot-proposals/issues/877) goes through. We can reimplement GLES3 in 4.0 with a more low-end approach to make it more compatible.

> However it seems to work with GLES3 on HTML5 but isn't GLES3 going to be deprecated for browser? Also for me HTML5 GLES3 projects loads longer when starting it.

This is because built-in shaders in GLES3 are more complex and therefore take more time to compile.

**Comment by github5435** [comment]
@Calinou Do you have any workaround ideas for this? I am trying to create shader for positional fog which affects all nodes in certain area. Similar to fog in WorldEnvironment but with static position.

**Comment by Calinou** [comment]
> Do you have any workaround ideas for this? I am trying to create shader for positional fog which affects all nodes in certain area. Similar to fog in WorldEnvironment but with static position.

You can place a procedural plane or cube in the world using MeshInstance + SpatialMaterial, then enable Proximity Fade on the SpatialMaterial and increase the fade distance. This should give you a nice fixed-position fog effect as long as the camera doesn't enter the volume.

**Comment by github5435** [comment]
I will try that, thanks!

**Comment by github5435** [comment]
Any hope for this getting fixed? I could use GLES3 but the slower shader compilation speeds are really unfortunate :(

**Comment by Calinou** [comment]
> Any hope for this getting fixed? I could use GLES3 but the slower shader compilation speeds are really unfortunate :(

Nobody knows how to fix this, so it will take a	while before this is fixed.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/80481

**Comment by singfisher** [comment]
@clayjohn I still have this issue in Godot 3.6 beta 4 and when building 3.x from source. Has the issue been reintroduced?

**Comment by clayjohn** [comment]
@singfisher Are you using the exact same code from this bug report? It is still possible to run into this error for other reasons (i.e. if you pass a ViewportTexture into a shader that is used in that Viewport).

**Comment by singfisher** [comment]
@clayjohn Yes, I just tried with the minimal reproduction project linked above and see the error in both 3.6 beta 4 and 3.x latest

**Comment by clayjohn** [comment]
I took a look at relevant PRs made after and it doesn't seem like any of them would have re-introduced this issue. 

Sorry to be excessively picky, is there any chance you are using out of date export templates. In other words, when you build from source, are you building both the editor and export templates and then using your custom export template?

**Comment by singfisher** [comment]
Thank you for checking. No problem. I built the export templates myself and copied them over to the templates folder with the appropriate names. However, I have left the "Custom Template" Debug and Release fields in the export dialog empty - do I need to do anything with those?

Only other possible irregularities: I copied the Base Class Libraries from 3.6 beta 4. I also do not have the mono module enabled in the export templates despite the editor having it enabled.

**Comment by clayjohn** [comment]
> Thank you for checking. No problem. I built the export templates myself and copied them over to the templates folder with the appropriate names. However, I have left the "Custom Template" Debug and Release fields in the export dialog empty - do I need to do anything with those?

The "Custom Template" Debug and Release fields should point towards your custom export templates. I think the engine copies the export templates to a shared location when you "install" them. So just replacing the templates won't be enough.

**Comment by singfisher** [comment]
When using the Custom Template fields I still see the issue unfortunately :(

**Comment by lawnjelly** [comment]
Oh yep, still seems to be occurring in 3.6 beta 4. I'll see if I can build the web version and work out why.
