### ISSUE TITLE
FileDialog is not translated in game

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#46950]
**Godot version:**

3.2.4 rc4 / bf309b8

**Issue description:**

![image](https://user-images.githubusercontent.com/2223172/111000387-431ea100-8382-11eb-94bd-4b51f33e7060.png)
Only title is translated. Everything else, including tooltips, is not. In editor it's translated properly.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/45887?

**Comment by KoBeWi** [comment]
I've seen that issue and it's weird. It says that dialog is translated at startup (you can even see that on the video), but for me it's not translated at all. Also it's about changing the translation in-game.

**Comment by fabriceci** [comment]
@KoBeWi should be fixed by #46735

**Comment by KoBeWi** [comment]
I actually opened this issue, because that PR doesn't fix it.

**Comment by fabriceci** [comment]
@KoBeWi I can't reproduce the issue in the PR, here is what I have: I can set a langage other than EN on startup and change the language in runtime:

https://user-images.githubusercontent.com/6397893/111068736-5177d480-84ca-11eb-8219-00e904d38b7d.mp4

**Comment by KoBeWi** [comment]
The translation is complete, as I said the localized text shows fine in the editor, but not when running.

Something is wrong here. Here's some test code:
```
func _ready() -> void:
	TranslationServer.set_locale("es")
	var fd = FileDialog.new()
	add_child(fd)
	fd.popup_centered()
```
![image](https://user-images.githubusercontent.com/2223172/111075266-7464b180-84e7-11eb-9bed-2becf5867bb4.png)

Maybe the dialogs are supposed to only use custom translations, but that doesn't explain why their titles are translated (see the screenshot in OP)

**Comment by KoBeWi** [comment]
After some discussion on the chat, I realized this is not a bug. The title was translated because of #39258. Seems like translated strings are only available in the editor, so it's expected that they won't work in the game and "fixing" this is a proposal material. Closing.
