### ISSUE TITLE
OS.execute can't spawn new cmd window

### ISSUE THREAD

**Issue by Novakasa** [godotengine/godot#47011]
**Godot version:**
v3.2.4.rc4.official x64

**OS/device including version:**
Windows 10 x64 10.0.19041 Build 19041

**Issue description:**
I am working on a Godot application that needs to interact with a Python program. I can't implement it purely using godot-python since I'm running into issues maintaining an asyncio event loop. I want to start the Python program with the Godot application automatically, and I want to create a new cmd window so I can always see the output from the python program for debugging purposes. I want to spawn a new cmd window with `start`, however, when trying to execute it using
```GDScript
OS.execute("start", ["C:/Users/lolli/miniconda3/envs/brickrail/python.exe E:/repos/brickrail/ble_server.py"], false)
```
I am getting the error `execute: Condition "ret == 0" is true. Returned: ERR_CANT_FORK` and the window is not created.
Omitting my specific command, the same error occurs if I just run
```GDScript
OS.execute("start", [], false)
```
or
```GDScript
OS.execute("start", ["cmd"], false)
```
or even
```GDScript
OS.execute("cmd", ["/K"], false)
```

Running the python program directly by executing `python` works, and executing just `cmd` works as well.
According to https://github.com/godotengine/godot/issues/10172#issuecomment-321472016 on an old issue, this command seemed to have worked in an older version.

**Steps to reproduce:**
Create a node, put either one of these in `_ready`:
```GDScript
OS.execute("cmd", ["/K"], false)
```
```GDScript
OS.execute("start", [], false)
```
```GDScript
OS.execute("start", ["cmd"], false)
```

**Comment by lolligerjoj** [comment]
If anyone has the same problem, I got it working using a workaround without OS.execute, but using the python bindings (https://github.com/touilleMan/godot-python):
```python
import subprocess

from godot import Node, exposed, export

@exposed
class BLEProcess(Node):

	def _ready(self):
		print("python ble_process is working!")

	def start_process(self):
		subprocess.run("start C:/Users/lolli/miniconda3/envs/brickrail/python.exe E:/repos/brickrail/ble_server.py", shell=True)
```
I got the idea from @uncleonka on discord, who suggested using C# for it like this:
```csharp
This worked to open up Visual studio Code:
string strCmdText = "/C code";
System.Diagnostics.Process.Start("CMD.exe", strCmdText);
```
I'm not well versed in C# so I opted for the python bindings instead.

**Comment by akien-mga** [comment]
I can reproduce it on 3.2.3 and 3.1.2, so it doesn't seem to be a recent regression.

**Comment by mhilbrunner** [comment]
`OS.execute("start", ["cmd"], output, false)` works for me to create a new console window on current Godot master on Windows 10, so this sould be fixed in Godot 4.

**Comment by Jimmio92** [comment]
This should not be closed; problem still exists; ERR_CANT_FORK with your code

> `OS.execute("start", ["cmd"], output, false)`

Is this a security "feature" of Windows now or something?
