### ISSUE TITLE
[3.2.4 rc5] Skeleton Animation has different behavior when IK enable because the recent fix about SkeletonIK

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#47086]
**Godot version:**

3.2.4 rc5 offical

**OS/device including version:**

MacOS 10.14.6 intel GPU GLES3

**Issue description:**

3.2.4 rc4

https://user-images.githubusercontent.com/64188282/111425984-e8dd6180-872e-11eb-9299-6cacec810d9b.mov

and 3.2.4 rc5

https://user-images.githubusercontent.com/64188282/111426026-f72b7d80-872e-11eb-8f0a-db1d421ed3a3.mov

https://user-images.githubusercontent.com/64188282/111426045-fdb9f500-872e-11eb-97b5-39aafb18d076.mov

I guess the recent fix about SkeletonIK cause this problem https://github.com/godotengine/godot/pull/46910

**Steps to reproduce:**

**Minimal reproduction project:**

[IK issue.zip](https://github.com/godotengine/godot/files/6154246/IK.issue.zip)

**Comment by akien-mga** [comment]
CC @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
Thanks for the report, I'll take a look.

At a glance, it looks like the issue is that the origin bone is being set to the bone rest position rather than the bone's current pose, which is why its in the correct position but is not moving when animated. That's my guess as to what is going on. I'll take a look once I have the time and see if I can get a PR that fixes the issue.

**Comment by snougo** [comment]
@TwistedTwigleg 
I have a bad news, the new PR don't fix this issue, and I have reimported the animation model from blender to make sure it's not caused by the file itself, but didn't work, the issue still appear.

then I disabled AnimationTree's active and using AnimationPlayer to check what's going on, see the below sceenshots

**3.2.4 rc4**
![Screen Shot 2021-03-19 at 18 52 11](https://user-images.githubusercontent.com/64188282/111769920-c1c89080-88e4-11eb-9fd8-db1152683030.png)


**3.3 rc6**
![Screen Shot 2021-03-19 at 18 49 57](https://user-images.githubusercontent.com/64188282/111769966-cdb45280-88e4-11eb-99a1-b1a3fac20af7.png)

**Comment by akien-mga** [comment]
That fix was merged after 3.3 RC 6 was built, it's not included in the release. You can test the latest artifacts from the `3.x` however: https://github.com/godotengine/godot/runs/2147580417

**Comment by snougo** [comment]
@akien-mga oh, that make scene, I'm just too much haste to read the changes, sorry

**Comment by snougo** [comment]
@TwistedTwigleg  the fix didn't completely solve the issue see the video


https://user-images.githubusercontent.com/64188282/113000549-82325c00-91a2-11eb-85b2-a0ca9f1903f7.mov

**Comment by TwistedTwigleg** [comment]
@snougo - I think #47441 will fix this issue :+1:

**Comment by snougo** [comment]
@TwistedTwigleg got it

**Comment by snougo** [comment]
just back to report this issue has be fixed in 3.3 rc9
@TwistedTwigleg 👍

**Comment by TwistedTwigleg** [comment]
Awesome, thanks for checking 🙂
