### ISSUE TITLE
Normal maps incorrect using draw_texture_rect() with rotation (batching related)

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#47276]
**Godot version:**
3.3 RC6

**OS/device including version:**
2020 Mac Mini
macOS Big Sur
GLES2 / GLES3

**Issue description:**
I am using polygons and draw functions (specifically draw_texture_rect(), though this issue isn't necessarily limited to that function) to create nice textured terrain. However, when a normal map is provided, and a nonzero angle is set in draw_set_transform(), the normal lighting is not correct. The issue is definitely related to batching, as turning it off fixes it, at least in GLES3.

Here are some screenshots. On the left is a sprite, and to the right is the texture as drawn from the sprite's script.

GLES3, batching ON (incorrect)
<img width="568" alt="Screen Shot 2021-03-22 at 2 22 27 PM" src="https://user-images.githubusercontent.com/33777501/112060339-4a7c4200-8b1a-11eb-9ff7-e5373019fb5e.png">

GLES3, batching OFF (correct)
<img width="500" alt="GLES3 batching OFF" src="https://user-images.githubusercontent.com/33777501/112064558-6be02c80-8b20-11eb-89d8-eacb9750a380.png">

GLES2, batching ON (incorrect)
<img width="469" alt="GLES2 batching ON" src="https://user-images.githubusercontent.com/33777501/112065676-4b18d680-8b22-11eb-852b-b013a9596249.png">

GLES2, batching OFF (what the heck?)
<img width="484" alt="GLES2 batching OFF" src="https://user-images.githubusercontent.com/33777501/112064845-db561c00-8b20-11eb-82b9-477d06ba181c.png">

The drawing code:

```
func _draw():

	draw_set_transform(Vector2(100, 0), 5, Vector2.ONE)
	var rect = Rect2(Vector2.ZERO, Vector2(128, 128))
	draw_texture_rect(icon, rect, false, Color.white, false, normal)
```

**Steps to reproduce:**
Draw a rotated texture using draw_texture_rect() with rotation and normal map as described above, and shine a Light2D on it. 

**Minimal reproduction project:**
[NormalMapIssue.zip](https://github.com/godotengine/godot/files/6185589/NormalMapIssue.zip)

**Comment by akien-mga** [comment]
Fixed by #47591.

**Comment by lawnjelly** [comment]
Incidentally, the weird behaviour in GLES2 with batching off still occurred as far back as 3.2.1 when I tested it. I haven't even attempted to fix that.
