### ISSUE TITLE
Editor is using project settings (input map actions, splash screen, etc.)

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#4739]
*Bugsquad edit:* Apparently the editor parses `engine.cfg` and reuses most of it unless there are some checks to avoid it. It should be fixed all at once, hence we'll merge related issues with this one.

-----------

**Issue description** (what happened, and what was expected):
The editor is using input map actions from the project's settings. Therefore, modifying input presets (`ui_*`) affects the editor too. This can break usability in many situations, like removing <kbd>ENTER</kbd> from the `ui_accept` (pressing <kbd>ENTER</kbd> when focusing a button will not longer press the button).

**Steps to reproduce:**
Actually, being able to remove keys from input presets may be a bug. [This comment](https://github.com/godotengine/godot/issues/4315#issuecomment-209876046) explains how to do it:

> It looks like if you add another key to that action, then you can remove the other keys and it will be saved.
· neikeq

The solution may be to forbid modifying input presets, but it stills seems weird that the editor is using the project's input map.

**Comment by akien-mga** [comment]
I think the editor should not use the project's InputMap, it's bogus.

Then I guess input presets could be made fully editable (without exploiting a bug :P), with a button to restore the default input presets for users that mess up.

**Comment by akien-mga** [comment]
Could be related to #4045.

**Comment by bojidar-bg** [comment]
Given that the other issue was just fixed (by @akien-mga), it would be nice to have a retest.

**Comment by akien-mga** [comment]
I haven't tested, but I don't think the issues were related in the end.

**Comment by neikeq** [comment]
The issue is still valid after 6fefcfd. But the cause may be the path too, since opening a project in the editor is: `godot -path /path/to/project/ -e`

**Comment by akien-mga** [comment]
I renamed the issue to make it broader, as we've noticed that the editor uses most of the project's `engine.cfg`. It should be fixed all at once by ensure the editor does _not_ use the `engine.cfg` for itself.

**Comment by neikeq** [comment]
I agree, but it's no longer using input map actions after 64fd75d, right?

**Comment by akien-mga** [comment]
Hm that's right. I guess we need some input from @reduz or @punto- to see if a global solution could be worked on, or if it's not possible to fix by design and we'd thus have to add `if (editor)` checks for all relevant settings.

**Comment by reduz** [comment]
right, this is kind of done by design, but most setting are kind of the same anyway. There are very few that might affect the functioning of the editor and those already have ifs I think. 

You can make a list of those which should be checked manually that are not currently being checked I guess

**Comment by reduz** [comment]
well, I guess this is fixed, so closing
