### ISSUE TITLE
Dualshock 4 controller accelerometer and gyroscope are the only inputs on Linux

### ISSUE THREAD

**Issue by Samdal** [godotengine/godot#47892]
**Godot version:**
Godot Engine v3.2.3.stable.official

**OS/device including version:**
Arch Linux (Kernel: 5.11.7-arch1-1)
Controller: DualShock 4 (I have not tested on any other controllers)

**Issue description:**

Accelerometer and gyroscope inputs are remapped to random inputs
When moving, shaking or tilting the controller, it outputted random buttons (R2, square etc) and analog stick movements
and the expected controller inputs that would perform their respective actions did not work.

I have tested this with my Linux Desktop and laptop, I also tested with two controllers
Bluetooth and USB had the same behavior

**Steps to reproduce:**
On linux print the inputs from the controller
```GDScript
func _input(event):
	if event is InputEventJoypadButton or event is InputEventJoypadMotion:
		print(event)
```
and move the controller

**Minimal reproduction project:**
I simply used a node2D with the above script

**Comment by Zireael07** [comment]
Related/dupe of #47874?

**Comment by Calinou** [comment]
@Samdal Can you reproduce this in [3.3rc9](https://godotengine.org/article/release-candidate-godot-3-3-rc-9)? Controller mappings have been updated there.

**Comment by Samdal** [comment]
> @Samdal Can you reproduce this on [3.3rc9](https://godotengine.org/article/release-candidate-godot-3-3-rc-9)? Controller mappings have been updated there.
Nope i can not, apparently this has been fixed

**Comment by letsgamedev** [comment]
I am using 3.3.2-stable and I having this issue still.
If connected via USB I get random spamming buttons.
If connected via BT the JoyPad is recognized by Godot but no input at all comes into the game.

**Comment by Calinou** [comment]
@letsgamedev Please open a new issue with a minimal reproduction project attached. Make sure you can't reproduce this in other software/games first.
