### ISSUE TITLE
sometimes, the 3d viewport size is corrupted after the window was reduced

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4821]
**Operating system or device - Godot version:**
Official 2.0.3stable win64
Windows 8.1
GPU AMD Radeon R7

**Issue description** (what happened, and what was expected):

Sometimes, when I resize the editor's window while displaying the 3d viewport, the content of the 3d viewport is wrongly rescaled. Pixels become gigantic, and the center of the viewport is not visible (outside the viewport)

There is no way to restore correct scale to the viewport, except quitting and opening again.

![bug_resizing_editor](https://cloud.githubusercontent.com/assets/9801802/15575203/e5522b90-2351-11e6-8b22-f45ee3532e95.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
I have never encountered this one on linux, tagging as windows-only for now.

**Comment by slapin** [comment]
I never had this one on Linux, 3D viewport is messed-up quite often, but is always fixed by clicking on 3D node and pressing F key.

**Comment by SuperUserNameMan** [comment]
When this bug occurs, centering the view on a 3d node using the F key does not solve the problem, because the center of the viewport is outside of the displayed part of the viewport.

Zooming in and out, or moving the view does not help neither.

It it a problem with the scale of the content of the viewport.

**Comment by SuperUserNameMan** [comment]
Hmm, it just happened again. So I can give you the list of what does not solve the problem :

- changing the 3d view mode (1 viewports, 3 viewports, 4 viewports, orthonormal, perspective, etc) doest not solve

- pressing 3d nodes and F key does not solve

- switching from 3d to 2D view, and back to 3d view does not solve
(note that the 2D viewport is not affected by the bug)

- resizing the editor's window does not help

- changing screen resolution does not help

- closing and reopening the 3d scene does not help

- switching to another 3d scene does not help

- switching from script to 3d view does not help

- toggling different camera previews don't help neither

The console display no special error message except a long list of "No completion".

**Comment by SuperUserNameMan** [comment]
Note : this also happen randomly when switching from one application to an other.

**Comment by Calinou** [comment]
I've had this happen once with self-compiled Godot (https://github.com/godotengine/godot/commit/9daaa709207adf77eb5cf7c440782eaad3a3f7b2), compiled using Clang on Arch Linux.

**Comment by reduz** [comment]
if you can figure out how to reproduce it, I can try to fix it, but have no idea what it might be

**Comment by SuperUserNameMan** [comment]
So far, impossible to reproduce on will.

It has just happened again after displaying these errors into the console :
````
`WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
````

**Comment by SuperUserNameMan** [comment]
Just in case it is useful information, I'm using a dual display on a Windows 8.1 64bits Laptop.

The external display resolution is 1920x1080p (but last time it was 2560x1440p, so it probably does not matter). It is set as the main display for the desktop.

THe laptop display resolution is 1366x768p.

Here is a large screenshot of my full desktop showing as much useful information as possible (editor console, editor 3d viewport, desktop setup and system and driver information)

![bug_resizing_editor_desktop](https://cloud.githubusercontent.com/assets/9801802/16042556/9bee2960-323b-11e6-80d2-8b9ddbf5af82.png)

**Comment by SuperUserNameMan** [comment]
Okay, so i'm continuing my 

**It is NOT related to dual screen.**

It happened again on my laptop single screen 1366x768.

What I've done before it happen again :
- i've opened an existing project to try the "Edit the node group" button of the Scene tab.
- i dont rememeber if I reduced the editor, or if left it into the background, but after testing the button, I switched to an other application (Gimp and Firefox).
- then I went back to Godot and noticed into the console the errors belows.
- the 3d viewport content looked normal
- then, I resized the Godot Editor window jsut to see, and the content of the 3d viewport was buggy

![bug_3dviewport_again](https://cloud.githubusercontent.com/assets/9801802/16116227/efe5cc26-33cb-11e6-84f0-947f6d9544b4.png)


````
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
lost?
````

**Comment by SuperUserNameMan** [comment]
Okay, I now know how to reproduce this bug.
It is related to #1930.

* Under windows with 2.0.3stable win 64.
* You open Godot editor and show 3D viewport.
* Press [Windows] + D to display the desktop.
* Once all windows are minimized, press [Windows] + D again to restore all the windows.
* The console will show there errors below.
* NOW, resize the Editor's window : the 3d viewport should show giant pixels.

![3dviewportbug](https://cloud.githubusercontent.com/assets/9801802/16203093/de6bb500-3718-11e6-920c-d7e1cc21ded3.gif)

````
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!, c
ode: 36054
     At: drivers\gles2\rasterizer_gles2.cpp:10503
WARNING: RasterizerGLES2::_update_framebuffer: Could not create framebuffer!!
     At: drivers\gles2\rasterizer_gles2.cpp:10539
ERROR: VisualServerRaster::_draw_viewport: Condition ' desired_rect.width<=0 ||
desired_rect.height<=0 ' is true.
   At: servers\visual\visual_server_raster.cpp:7042
````

**Comment by vnen** [comment]
@SuperUserNameMan :clap: I can reproduce this now with those steps. It's likely the same as #1930.

**Comment by SuperUserNameMan** [comment]
That's thanks to Calinou on IRC who mentioned #1930.

**Comment by SuperUserNameMan** [comment]
Indeed, this also happen with windowed games.
