### ISSUE TITLE
Language server string autocomplete place undesired quotes

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#48436]
**Godot version:**
3.3

**OS/device including version:**
Ubuntu

**Issue description:**
When autocompleting strings, the language server puts undesired quotes.

**Steps to reproduce:**
See video

https://user-images.githubusercontent.com/1168582/116951932-b1376400-ac5f-11eb-9eb5-a3d940c7ef32.mp4

**Minimal reproduction project:**
Any GD script file

**Comment by Exerionius** [comment]
Same for built-in functions autocompletion:
![171664533-5ac06f93-45b8-4c23-a5a5-d44e7617dd20](https://user-images.githubusercontent.com/13285909/171807435-9e34af26-914f-4dbb-b039-1f88e64ed70c.gif)

**Comment by mickdekkers** [comment]
I looked into this back in September 2020 after it was posted as an issue on the VS Code plugin repo. I didn't get very far with fixing it myself but my comment (though possibly somewhat out of date by now) might still provide some useful context for anyone looking to fix this bug https://github.com/godotengine/godot-vscode-plugin/issues/142#issuecomment-699625127

**Comment by PKGaspi** [comment]
Can confirm using v3.5.stable.arch_linux and visual studio code (oss).

**Comment by musjj** [comment]
Can anyone point to the commit that apparently fixes this in 4.0?
I'm still experiencing this in the `3.x` branch (ca823e16e423eb6917ee4752603785795c54fd51).

**Comment by Calinou** [comment]
> Can anyone point to the commit that apparently fixes this in 4.0?

I don't know. You could test the various [4.0 alphas and betas](https://downloads.tuxfamily.org/godotengine/4.0/) to check when this was fixed.

**Comment by DylanMurphey** [comment]
Still an issue in `4.0.2.stable` I would like to help if there is still no solution

**Comment by DylanMurphey** [comment]
Alright, after doing some digging, I fixed the problem locally by changing

https://github.com/godotengine/godot/blob/e0e93ce094d19d132f34aa5c92e892524a8125c9/modules/gdscript/gdscript_editor.cpp#L2511

to 

```
opt = opt.unquote();
```

I am *very* new to Godot (as in, I encountered this bug while following a crash course tutorial and it annoyed me enough to try to contribute) but I can't wrap my head around why "quote_style" needs to be added in this context.

I recognize that my solution isn't the kosher solution, but I am sure the ideal way to fix this issue is to update the [`lsp::CompletionItem` fields `label` and `insertText`](https://github.com/godotengine/godot/blob/master/modules/gdscript/language_server/gdscript_text_document.cpp#L187) separately.

https://user-images.githubusercontent.com/58610593/234535106-23feb08b-d7d7-4128-9c98-712acae0ad71.mp4

**Comment by 0x4448** [comment]
I have a potential fix for this issue:

https://github.com/godotengine/godot/assets/86135470/d9a01487-a5d6-4e5d-8172-62c8a9e9ea73

I'm new to Godot and C++, but after poking around the code base a bit, I was able to get it working by making two changes:

1. CompletionParams has a new `context` member. It provided an implementation for `load()` to include that data, but not one for `to_json()`. So `context` was missing from the JSON and there's already code in `GDScriptTextDocument::resolve()` that depends on that. I added `context` to the JSON so it can be used in `resolve()` in [this commit](https://github.com/0x4448/godot/commit/7b945ec50449f19275e238b17400103b5a109f71).
2. Now that `resolve()` has the context, the current bug can be fixed. If the completion was triggered with a single or double quote,  then there's already a quote (or a pair of quotes) in the external editor. The auto-complete suggestion should be returned without quotes. Here's [the commit](https://github.com/0x4448/godot/commit/461c9d4fd03346b3564fde188202c9acf69b00b6) with the change.

Both changes are in language server classes, so this change should not break the built-in editor. I did a quick test to confirm that still returns quotes.

Again, I'm new to Godot and C++, so if I'm overlooking something obvious, please let me know and I'll try to fix it.

**Comment by AeroBliss** [comment]
This issue still happens in certain situations
[2023-12-16 19-41-00.webm](https://github.com/godotengine/godot/assets/84479813/cf0beb45-83f0-4136-8573-e65959abbc88)

**Comment by RichardEllicott** [comment]
i've had this issue like a gremlin really so long is it not still found? every now and again the editor autotypes everything quotes and i have to reboot... i'm now in v4.2.1!

**Comment by Calinou** [comment]
@RichardEllicott Please continue the discussion in https://github.com/godotengine/godot/issues/86488.
