### ISSUE TITLE
Scroll speed too fast on macbook

### ISSUE THREAD

**Issue by Qwertie-** [godotengine/godot#492]
Scrolling on mac is way too fast. Scrolling 1cm on the touchpad brings you to the bottom of the page. I haven't tested this with a mouse or on windows so the problem might happen there too.

I am using a macbook air 2012 (mavericks)

**Comment by akien-mga** [comment]
pretty bump :)

**Comment by buresu** [comment]
Hi

I think this problem has been caused by that delta value is not worked to scroll event.
The easiest solution is to reflect the scroll speed to the scroll event by adding delta_x and delta_y to InputEventMouseButton.

For exmaple,
`v_scroll->set_val( v_scroll->get_val()+(v_scroll->get_page()/8)*delta_y );`

However, the mouse button events and the mouse scroll events is different originally.

So, I think the best solution is to add the InputEventMouseWheel that has delta_x and delta_y, and replacing all the scroll events.

**Comment by UgisBrekis** [comment]
Hi guys, 
I'm not sure if I did it right, but the way I fixed this issue is simply by adding line which detects if the editor runs in hidpi and, if so, then the scroll value is adjusted. Basically I have to do it for each control which uses scroll, so it feels more like a hack than a real solution, but if you can confirm that it is a good enough way to fix this, I can write those lines and submit.

**Comment by reduz** [comment]
the problem is that if you connect a mouse, it works properly so I don't
want to change any code.
If OSX has a delta value for these events, we could implement some sort of
accumulator and convert it to scroll events

**Comment by UgisBrekis** [comment]
Ok, I see. Since I'm a stack overflow kinda coder it's out of my league, but still I'll take a look. Thanks for the hint!

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Fixed by 304a1f5.

**Comment by qiulang** [comment]
I still have this problem with the latest Version 1.16.0 (1.16.0) even though I had set trackpad's scrolling speed slower.

**Comment by Foxomat** [comment]
the scrolling is just like "scrolling - on" and "scrolling - off". No matter how fast you actually scroll on your touch pad, the speed at wich the editor window scrolls is always the same. 
My abilities as a coder ar by far not enough to contribute to godot, but can somebody else maybe change the implementation to more "natural" scrolling where scrolling speed on the touch pad corresponds to the scrolling speed of the window?

**Comment by Calinou** [comment]
@Foxomat Does it work better if you disable **Text Editor → Open Scripts → Smooth Scrolling** in the Editor Settings?

**Comment by Foxomat** [comment]
@Calinou Thank you, it really makes it better. Although its still not quite as smooth as scolling in e.g. a browser window, i am really satisfied with it.
