### ISSUE TITLE
Warning: application@android:isGame was tagged to replace other declarations but no other declaration present

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#50224]
### Godot version

3.4.beta 009aa63a5723eec59256a2bcd8ee2a038d1aa958

### System information

Ubuntu 21.04

### Issue description

When building an Android AAB there is a new warning:
```
AndroidManifest.xml:16:5-27:19 Warning: application@android:isGame was tagged at AndroidManifest.xml:16 to replace other declarations but no other declaration present
```
**Note:** This does not happen when building an APK.

Regression from #50028 cherry-picked to 3.4 with #50202 cd64bcdae56ff80736a12968b236beae9b0ab720

### Steps to reproduce

Install the Android Build Template. Create an Android preset. Select `Use Custom Build`. Select `Export Format`: `Export AAB`. Try to export the project.

### Minimal reproduction project

Any project will do, but here is a simple one:
[HelloAndroid.zip](https://github.com/godotengine/godot/files/6707817/HelloAndroid.zip)

**Comment by akien-mga** [comment]
Weird, without the replace I would instead get a build error due to the replacement. Did you make sure to install the Android source template matching 009aa63? To have the actual `AndroidManifest.xml` changes from #50028.

**Comment by madmiraal** [comment]
> Did you make sure to install the Android source template matching 009aa63? To have the actual AndroidManifest.xml changes from #50028.

I've tried again: Rebuilt the editor, rebuilt the template and copied it to the `template` directory, deleted the project's `android` folder and reinstalled the template via the editor and when I export to AAB it still reports the warning.

**Comment by madmiraal** [comment]
I've just tried again with 7c8cc037ad86fe1963ce978d20200e875472fad4 i.e. with #50227, and now the Gradle build fails! :confused: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 19; columnNumber: 7; The element type "manifest" must be terminated by the matching end-tag "</manifest>".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by akien-mga** [comment]
Oops, sounds like I introduced a syntax error. I don't see it in the diff, it seems consistent to what was working before my changes... I'll look into it.

**Comment by akien-mga** [comment]
After #50230 which fixes https://github.com/godotengine/godot/issues/50224#issuecomment-875108886 (sorry for the regression), I don't reproduce the warning in the OP in a build of 031a034a2885328477424215c6583b382194e8b4. Maybe it was a side effect of the error fixed by #50227?

**Comment by akien-mga** [comment]
Ah lol, I forgot to read my own comment...

```
<!-- Any tag in this line after android:icon will be erased when doing custom builds. -->
```

So my alphabetic reordering in cd64bcdae56ff80736a12968b236beae9b0ab720 broke. That's specific to `3.x` then (and I had only tested `master`, my bad).

**Comment by akien-mga** [comment]
Confirmed that the warning is solved by #50234 and the `AndroidManifest.xml` includes:
```
    <application android:label="@string/godot_project_name_string" android:allowBackup="false" android:isGame="true" android:requestLegacyExternalStorage="false" tools:ignore="GoogleAppIndexingWarning" android:icon="@mipmap/icon">
```

**Comment by akien-mga** [comment]
Fixed by #50234.

**Comment by madmiraal** [comment]
I've just tested with ac8807bd5ab3678948c2cfc668169d9e98b78920 i.e. including #50234, and I'm still getting the same warning message.

**Comment by akien-mga** [comment]
That's puzzling... I'll retest again but with #50234 I wasn't getting it myself.
Of course make sure that you do reinstall the source template as it's the one affected (but I suppose you did).

**Comment by akien-mga** [comment]
I tried again with 31143baa578a15281c1ce81cd2d10ff309717b8e and I can't reproduce the issue.

Testing procedure:
- Built editor for Linux, release and release_debug template for Android
- Installed Android templates in `~/.local/share/godot/templates/3.4.beta`
- Created a new project
- Installed Android source template
- Exported with the following configurations:
  * Custom Build, AAB, Classify as Game ON
  * Custom Build, AAB, Classify as Game OFF
  * Custom Build, APK, Classify as Game ON
  * Custom Build, APK, Classify as Game OFF
  * Prebuilt APK, Classify as Game ON
  * Prebuilt APK, Classify as Game OFF

**Comment by madmiraal** [comment]
Okay. My bad. It was still using an old copy of the `android_source.zip`; so deleting and reinstalling the Android Build Template wasn't updating anything. I've updated my build scripts to properly copy the `android_source.zip` file to my `templates/3.4.beta/` directory and now it works. :-)
