### ISSUE TITLE
No way to edit plugin.cfg in editor

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5096]
Under the new plugin system (well, in the old too) there's no way to create nor edit the `plugin.cfg` file without an external editor.

It should be possible to develop plugins completely without leaving the Godot editor.

**Comment by reduz** [comment]
Well this makes sense but I don't think it's a bug though.. seems more like an enhancement to me. If anyone wants to make an editor, this is welcome :)

**Comment by Geequlim** [comment]
I`m adding a Resource type  named *RawText* to handle text files. So the cfg file would be edited by a plugin like ScripEditot.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Chaosus** [comment]
I guess it should be closed, as it is not critical 2.1 issue(and in 3.x engine.cfg is no longer exist)

**Comment by akien-mga** [comment]
Well it's also valid in 3.x with `project.godot`, but it's now fixed in the master branch with support for editing text-based files:
![screenshot_20180917_171343](https://user-images.githubusercontent.com/4701338/45632198-07e6d400-ba9d-11e8-9d2e-7ddad9ecbbfe.png)

**Comment by Chaosus** [comment]
Oh, so I need to reopen it ?

**Comment by akien-mga** [comment]
No need as it's fixed in 3.1 :)

**Comment by dark-penguin** [comment]
Ummmm this seems to be still an issue in 3.2.3 ??..

I would really like to be able to edit text/config files without an external editor. But neither .txt not plugin.cfg nor project.godot are showing in the filesystem dock. I have to keep my notes in the main node's script instead of a separate file...

I guess we can use "File - Open", then change the displayed file types, and then find the file, but... really?.. On top of that, there is no way to remember opened scripts between editor restarts (is there?), so doing that every time is certainly too much.

There is even "File - New Text File...", so we can create them, but not open them. If you create a text file, right-click it and choose "Show in Filesystem", that does nothing.

Also, what does "Settings - Docks - Filesystem - Display Mode" do?.. It's an integer, and the tooltop says "Property: docks/filesystem/display_mode". I've searched the help for "FileSystemDock", but it's a stub with no explanations.

**Comment by Calinou** [comment]
> Ummmm this seems to be still an issue in 3.2.3 ??..

This is now being tracked in https://github.com/godotengine/godot-proposals/issues/677 and https://github.com/godotengine/godot/issues/24187.
