### ISSUE TITLE
3.4-beta2: Using a custom theme with a button style crashes the editor

### ISSUE THREAD

**Issue by th1z** [godotengine/godot#51003]
### Godot version

Godot_v3.4-beta2_mono_win64

### System information

Windows 10

### Issue description

When setting a custom project theme (gui/theme/custom) containing a button texture style the editor crashes on restart without any error message.
The project can only be opened after the custom theme is removed from the project configuration file.

**The theme works fine on its own. The crash does only happen when the theme is set as a custom theme in the project settings.**

Maybe only the Mono version is affected. I have not tried with the standard version.

### Steps to reproduce

Create a new project.
Create a custom theme.
Import Button control item via "Manage Theme Items".
Set a custom texture style.
Use the custom theme via the editor settings (gui/theme/custom).

The editor wants to restart.
Editor crashes every time the project is opened.

### Minimal reproduction project

[CustomThemeDebug.zip](https://github.com/godotengine/godot/files/6899422/CustomThemeDebug.zip)

**Comment by qarmin** [comment]
Very strange crash 
```
Thread 1 "godot" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x0000000003ffb0ed in StreamTexture::_load_data (this=0x6dc3590, p_path=..., tw=@0x7fffffffc698: 4, th=@0x7fffffffc69c: 4, tw_custom=@0x7fffffffc6a0: 0, 
    th_custom=@0x7fffffffc6a4: 0, flags=@0x7fffffffc6a8: 4, image=..., p_size_limit=0) at scene/resources/texture.cpp:560
#2  0x0000000003ffbb28 in StreamTexture::load (this=0x6dc3590, p_path=...) at scene/resources/texture.cpp:678
#3  0x0000000003ffccde in ResourceFormatLoaderStreamTexture::load (this=0x754e9d0, p_path=..., p_original_path=..., r_error=0x0) at scene/resources/texture.cpp:832
#4  0x00000000048c4cec in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:262
#5  0x00000000048be2a4 in ResourceFormatImporter::load (this=0x6bc00f0, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_importer.cpp:130
#6  0x00000000048c4cec in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:262
#7  0x00000000048c58bd in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:376
#8  0x0000000003f91a40 in ResourceInteractiveLoaderText::poll (this=0x6ed9170) at scene/resources/resource_format_text.cpp:406
#9  0x00000000048c3184 in ResourceFormatLoader::load (this=0x754f070, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_loader.cpp:193
#10 0x00000000048c4cec in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:262
#11 0x00000000048c58bd in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:376
#12 0x00000000035fe167 in register_scene_types () at scene/register_scene_types.cpp:772
#13 0x00000000017c3d35 in Main::setup2 (p_main_tid_override=0) at main/main.cpp:1415
#14 0x00000000017c0a7e in Main::setup (execpath=0x7fffffffe3d5 "/usr/bin/godot", argc=1, argv=0x7fffffffe0d0, p_second_phase=true) at main/main.cpp:1205
#15 0x000000000177b2fb in main (argc=2, argv=0x7fffffffe0c8) at platform/x11/godot_x11.cpp:48

```

**Comment by pycbouh** [comment]
Strange indeed. See my findings in the linked PR.

**Comment by akien-mga** [comment]
Fixed by #51014.

**Comment by timothyqiu** [comment]
Doing the steps in OP still crashes the editor in 3.4.beta3 / 3.x(89313b9ed), but with a different backtrace.

<details>

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff203d6d7d _sigtramp + 29
[2] 2   ???                                 0x0000000300000020 0x0 + 12884901920
[3] EditorSpinSlider::_notification(int) (in godot.osx.tools.64) (editor_spin_slider.cpp:212)
[4] EditorSpinSlider::_notificationv(int, bool) (in godot.osx.tools.64) (editor_spin_slider.h:39)
[5] Object::notification(int, bool) (in godot.osx.tools.64) (object.cpp:927)
[6] Node::_propagate_ready() (in godot.osx.tools.64) (node.cpp:187)
[7] Node::_propagate_ready() (in godot.osx.tools.64) (node.cpp:178)
[8] Node::_set_tree(SceneTree*) (in godot.osx.tools.64) (node.cpp:0)
[9] Node::_add_child_nocheck(Node*, StringName const&) (in godot.osx.tools.64) (node.cpp:0)
[10] Node::add_child(Node*, bool) (in godot.osx.tools.64) (node.cpp:0)
[11] EditorInspector::update_tree() (in godot.osx.tools.64) (editor_inspector.cpp:1739)
[12] EditorInspector::_notification(int) (in godot.osx.tools.64) (editor_inspector.cpp:0)
[13] EditorInspector::_notificationv(int, bool) (in godot.osx.tools.64) (editor_inspector.h:251)
[14] Object::notification(int, bool) (in godot.osx.tools.64) (object.cpp:927)
[15] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[16] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[17] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[18] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[19] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[20] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[21] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[22] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[23] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[24] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[25] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[26] Node::propagate_notification(int) (in godot.osx.tools.64) (node.cpp:1736)
[27] EditorSettings::notify_changes() (in godot.osx.tools.64) (editor_settings.cpp:1596)
[28] EditorSettingsDialog::_settings_save() (in godot.osx.tools.64) (settings_config_dialog.cpp:68)
[29] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (in godot.osx.tools.64) (method_bind.gen.inc:59)
[30] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (in godot.osx.tools.64) (object.cpp:918)
[31] Object::emit_signal(StringName const&, Variant const**, int) (in godot.osx.tools.64) (object.cpp:1226)
[32] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (in godot.osx.tools.64) (object.cpp:1281)
[33] Timer::_notification(int) (in godot.osx.tools.64) (timer.cpp:61)
[34] Timer::_notificationv(int, bool) (in godot.osx.tools.64) (timer.h:37)
[35] Object::notification(int, bool) (in godot.osx.tools.64) (object.cpp:927)
[36] SceneTree::_notify_group_pause(StringName const&, int) (in godot.osx.tools.64) (scene_tree.cpp:973)
[37] SceneTree::idle(float) (in godot.osx.tools.64) (scene_tree.cpp:527)
[38] Main::iteration() (in godot.osx.tools.64) (main.cpp:2150)
[39] OS_OSX::run() (in godot.osx.tools.64) (os_osx.mm:3252)
[40] main (in godot.osx.tools.64) (godot_main_osx.mm:71)
[41] 41  libdyld.dylib                       0x00007fff203acf3d start + 1
-- END OF BACKTRACE --
Abort trap: 6
```

</details>
