### ISSUE TITLE
TabContainer emits tab_changed signal when index of the current tab is changed, not when the current tab is changed

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#51174]
### Godot version

3.3.2.stable

### System information

Windows 7

### Issue description

As title says.

Example of incorrectly not emitting `tab_changed`: removing current tab if it's not the last one, it results in current tab index not being changed and thus `tab_changed` isn't emitted although the current tab has changed (previous current tab was removed).

Example of incorrectly emitting `tab_changed`: dragging current tab to different "slot", it results in current tab index being changed and thus `tab_changed` is emitted although the current tab hasn't changed (only its index among other tabs was changed).

### Steps to reproduce

1. Create `TabContainer` with `drag_to_rearrange_enabled` set to `true`. Add 2 child `Control`s to it.
2. Connect a method to its `tab_changed` signal.
3. Make current tab be removed when triggered (e.g. by pressing <kbd>Enter</kbd>).
4. Run and drag tabs around, `tab_changed` will be emitted.
5. Trigger removing current tab, `tab_changed` won't be emitted.

### Minimal reproduction project

[TabChangedEmitting.zip](https://github.com/godotengine/godot/files/6916671/TabChangedEmitting.zip)

**Comment by kitbdev** [comment]
Can't reproduce in Godot v4.2.beta (7f884b4e0)
Probably fixed by #58687

**Comment by kleonc** [comment]
> Can't reproduce in Godot v4.2.beta ([7f884b4](https://github.com/godotengine/godot/commit/7f884b4e0017368e193d96f425aac6c2d8a86eb0))
>Probably fixed by #58687

Still reproducible in v3.6.beta3.official [21ab700f2] though (and this issue already has `3.x` milestone).
