### ISSUE TITLE
Editor plugin is not removed if changed while active

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5273]
If a plugin scene or code is changed while it's active, it won't be removed when deactivated and a new one will be added when reactivated.

![godot windows opt tools 64_2016-06-18_13-40-14](https://cloud.githubusercontent.com/assets/5599796/16172237/a11240a8-355a-11e6-92a8-45559d270ebc.png)

**Steps to reproduce:**

1. Create a project.
2. Add this plugin in the `addons/custom_dock` folder of the project: https://github.com/godotengine/godot-demo-projects/tree/master/plugins/custom_dock.
3. Activate it in project settings.
4. In `dock_plugin.gd` change `DOCK_SLOT_LEFT_UL` to `DOCK_SLOT_LEFT_UR`.
5. Deactivate the plugin. Notice the dock doesn't go away.
6. Activate the plugin again. A new custom dock is added.

**Comment by reduz** [comment]
This was probably fixed by the recent fix above, as I can't reproduce it

**Comment by vnen** [comment]
@reduz I can still reproduce 100% of the time with a build from today, the merged PR didn't fix it. Can this possibly be Windows only?

**Comment by reduz** [comment]
I have no idea, I really can't reproduce it :|

**Comment by vnen** [comment]
I get this when I deactivate it:

````
ERROR: EditorPlugin::remove_control_from_docks: Parameter ' p_control ' is null.
   At: tools\editor\editor_plugin.cpp:61
SCRIPT ERROR: _exit_tree: Invalid call. Nonexistent function 'free' in base 'Nil'.
          At: res://addons/custom_dock/dock_plugin.gd:18
````

It seems the plugin loses the reference to the dock when saved. Is the script reloaded somehow to make this happens?

**Comment by TheHX** [comment]
I can reproduce this too(on **Fedora 23**), looks like when the script is edited and then saved(with the ```text_editor/auto_reload_and_parse_scripts_on_save``` setting enabled) the variable ```dock``` in ```dock_plugin.gd``` is set to null again. When the script is reloaded only the values of exported members are kept.

**Comment by reduz** [comment]
ok, should just make it so edited plugins can't be hard-reloaded then

**Comment by reduz** [comment]
Other than soft reloading (which is much safer), there is really no fix for this.
