### ISSUE TITLE
Unable to create folder from save dialog

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#5323]
**Operating system or device - Godot version:**
Fedora 23 64bit, godot master 85d8000449be06affcd686838d498be186594c14

**Issue description** (what happened, and what was expected):
Opening the save file dialog and trying to create a folder using the create folder button results in this message
![screenshot from 2016-06-20 16-45-29](https://cloud.githubusercontent.com/assets/1103897/16211320/6dbba1f6-3706-11e6-9dc0-b0d6a157cec9.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by djrm** [comment]
@reduz The problem is here 61655d6dc2912424de937e2870b6a5ad346c3daf, the recursive directories problem is solved but disables the creation of directories from the save dialog, this happends because p_dir becomes res://SOME_DIR, and that cant be resolved by mkdir

**Comment by reduz** [comment]
I think this is fixed

**Comment by vnen** [comment]
This is not fixed though. You can create folders from the Project Manager, but not in a Save Dialog to the `res://` path.

**Comment by akien-mga** [comment]
Actually I tested against the current HEAD (a41a70ea) and it seems to be fixed. Probably thanks to ffbc2e56, as it was still broken in 729e61e1.

**Comment by djrm** [comment]
yes this has been fixed
