### ISSUE TITLE
SSL validation failure, sometimes

### ISSUE THREAD

**Issue by azurvii** [godotengine/godot#5366]
**Operating system or device - Godot version:**
Godot compiled at 842e7bf, with `p=x11 bits=64 openssl=builtin`, Xubuntu 16.04 64bit

**Issue description** (what happened, and what was expected):
It seems ssl validation sometimes fails on legit sites. I consistently got the following error when switching to the "Templates" tab in project list view. When I open the url (https://raw.githubusercontent.com/KOBUGE-Games/minilens/master/icon.png) in my browser, it showed just fine. This happened to a few other legit SSL sites.

```
REQUEST ICON FOR: 90235184
1 url: https://raw.githubusercontent.com/KOBUGE-Games/minilens/master/icon.png
yes SSL
2 url: raw.githubusercontent.com/KOBUGE-Games/minilens/master/icon.png
request string: /KOBUGE-Games/minilens/master/icon.png
3 url: raw.githubusercontent.com
4 url: raw.githubusercontent.com
Requesting:
	URL: raw.githubusercontent.com
	String: /KOBUGE-Games/minilens/master/icon.png
	Port: 443
	SSL: 1
	Validate SSL: 1
Cause: unable to get local issuer certificate
CERT STR: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
VALID: 0
CONNECTION RESULT: -1
139835301386280:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:drivers/builtin_openssl2/ssl/s3_clnt.c:1258:

```
What's weird to me was that it was able to validate some sites and grab the content, like https://github.com:

```
1 url: https://github.com
yes SSL
2 url: github.com
no request
3 url: github.com
4 url: github.com
Requesting:
	URL: github.com
	String: /
	Port: 443
	SSL: 1
	Validate SSL: 1
CERT STR: /businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=5157550/street=88 Colin P Kelly, Jr Street/postalCode=94107/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=github.com
VALID: 1
CONNECTION RESULT: 1
cert_ok: 1
```

**Comment by azurvii** [comment]
Oh, forgot to add, I was using HTTPRequest.

**Comment by azurvii** [comment]
It might be a dup of #5154. @vnen mentioned the same error message I saw in the output:
```
ERROR: _print_error: Some I/O error occurred. The OpenSSL error queue may contain more information on the error.
   At: drivers/openssl/stream_peer_openssl.cpp:433.
ERROR: _print_error: A failure in the SSL library occurred, usually a protocol error.
   At: drivers/openssl/stream_peer_openssl.cpp:435.
```

**Comment by bojidar-bg** [comment]
@azurvii You need to have certificates configured for it to work properly :)

@reduz BTW, is there any problem with using the system's certificate files?

**Comment by azurvii** [comment]
@bojidar-bg certs were all configured :) I tried using both `/etc/ssl/certs/ca-certificates.crt` and a Godot's `./tools/certs/ca-certificates.crt`.

It did work with quite a few websites, but somehow not with some others.

**Comment by reduz** [comment]
was this fixed with the addition of SNI?

**Comment by azurvii** [comment]
It looks like it's working now. A few test sites I used and didn't work are now showing contents on my test program. https://www.google.com still shows an error `unicode error: invalid skip` after grabbing the headers, but the ssl part worked just fine. My personal site still shows `unable to get local issuer certificate`, but that might be my configuration issue, which I'll take a further look.
