### ISSUE TITLE
Problems with Tweens and types

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#53879]
### Godot version

90a1e51

### System information

W10

### Issue description

This is a side-effect of #52731. Here's some perfectly valid bogus code:
```
var tween = create_tween()
tween.tween_property($Node2D, "position:x", 100, 1).as_relative()
```
So what is wrong about it? This error:
```
Trying to call a function on a null value.
```
That's pretty confusing and doesn't tell you anything. (although it should probably include method name at least, see #53878)

Your actual error is hidden in the debugger and its
```
Type mismatch between property and final value: float and int
```
Yes, `position:x` is a float, `100` is an int. Due to type validations, this is no longer valid code.

The fact that float and int are incompatible is a problem in itself. I guess int should be just converted to float in such cases, instead of throwing error that is completely unexpected.

But another problem is that the game actually stops on the first error, which isn't really related to your code, and the actual error is waiting in the debugger tab, easy to miss. This is because on type mismatch Tween methods will return null instead of Tweeners. I see a couple possible ways to fix this. Either:
- type mismatch should stop the game, so that you see it immediately. Not sure if possible, no idea what determines a stopping error
- type mismatch should result in empty Tweener instead, which would error out during animation. It defers the stopping error, not sure if the new one would be more intuitive

Or if we allow int/float interpolations, the issue won't be as prominent, because the error in my example is just unexpected.

### Steps to reproduce

Try the code above.

**Comment by KoBeWi** [comment]
Resolved by #65072
Other type conversions don't need to be supported.

**Comment by jordanlis** [comment]
Still not working in 4.2dev2 by the way, I had to code a new function to tween the shader property because of the error "Nil to float"
![image](https://github.com/godotengine/godot/assets/68544949/5d1a30e6-e314-419e-b56c-d362343c16d4)

**Comment by KoBeWi** [comment]
That's another issue: #44454
null can't be converted to float.

**Comment by jordanlis** [comment]
> That's another issue: #44454 null can't be converted to float.

I get what you mean. But why do my function initialize the value to 0 whereas the default function doesn't? It could be one way to solve this issue.
the null value should be initialized with tween_method no? It seems logical this way for me but anyway, there's a turnaround for this so it's not a blocker and the issue you mentioned should resolve the problem anyway.

**Comment by KoBeWi** [comment]
Wait, actually where is the null in your code? Is it the `value`? I don't get it.

**Comment by jordanlis** [comment]
> Wait, actually where is the null in your code? Is it the `value`? I don't get it.

No, the "amount". 

In 3.5.2, you could define the intial value of tween_property. Now it's not possible anymore. 

Previously, I was doing something like this : 
tween_blur.interpolate_property(get_node("blur").get_material(), "shader_param/amount", init_value, value, duration, Tween.TRANS_LINEAR, Tween.EASE_OUT)

In 4.x, not possible anymore, so I had to do this little trick to make it work. 

I hope i'm clear

**Comment by KoBeWi** [comment]
You can set initial value using PropertyTweener's `from()`.
