### ISSUE TITLE
Error about pointer pointing at wrong object, when opening editor

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#54075]
### Godot version

4.0 21f1ac8bf313ee7859019fd57133862e2f559ea3

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

Since https://github.com/godotengine/godot/pull/53805, this error is shown when opening any project(UndoRedo error is probably unrelated)
```
core/variant/binder_common.h:222:25: runtime error: member call on address 0x61d00008e890 which does not point to an object of type 'CanvasItem'
0x61d00008e890: note: object is of type 'PopupMenu'
 be be be be  68 e9 4e d2 49 56 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  30 af 1f 01
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'PopupMenu'
core/object/undo_redo.h:56:9: runtime error: load of value 74, which is not a valid value for type 'bool'
```

open "Open and Close editor" stage in CI to see it - https://github.com/godotengine/godot/runs/3936291968?check_suite_focus=true

CC @groud 

### Steps to reproduce

Open editor with undefined sanitizer

**Comment by KoBeWi** [comment]
Is this fixed in newest master?

**Comment by qarmin** [comment]
No, error still is visible in CI in e.g. https://github.com/godotengine/godot/commit/a837accc5d058e4eec29f4d854da8cb9f55a97cf

https://github.com/godotengine/godot/runs/6665664721?check_suite_focus=true#step:13:89

**Comment by clayjohn** [comment]
Looks like this isn't occurring anymore in latest master https://github.com/godotengine/godot/actions/runs/4007367080/jobs/6880108315
