### ISSUE TITLE
Random errors when using `ResourceLoader.load_threaded_request()`

### ISSUE THREAD

**Issue by sboron** [godotengine/godot#54151]
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

Random errors occur by using load_threaded_request (mostly on larger scenes):

```
USER ERROR: Creating buffers with data is forbidden during creation of a draw list
   at: RenderingDeviceVulkan::vertex_buffer_create (drivers\vulkan\rendering_device_vulkan.cpp:4014) - Condition "draw_list != nullptr && p_data.size()" is true. Returning: RID() 
 USER ERROR: Creating buffers with data is forbidden during creation of a draw list
   at: RenderingDeviceVulkan::vertex_buffer_create (drivers\vulkan\rendering_device_vulkan.cpp:4014) - Condition "draw_list != nullptr && p_data.size()" is true. Returning: RID() USER ERROR: Mono: FATAL ERROR '* Assertion at ..\mono\mini\debugger-agent.c:4175, condition !tls not met (in domain , error), ABORTING! Logfile: 'C:/Users/stefa/AppData/Roaming/Godot/mono/mono_logs/2021-10-23_14.25.03_40984.log'. at: GDMonoLog::mono_log_callback (modules\mono\mono_gd\gd_mono_log.cpp:92) - Mono: FATAL ERROR '* Assertion at ..\mono\mini\debugger-agent.c:4175, condition !tls' not met
 (in domain , error)', ABORTING! Logfile: 'C:/Users/stefa/AppData/Roaming/Godot/mono/mono_logs/2021-10-23_14.25.03_40984.log'.
```
 
 

### Steps to reproduce

Use load_threaded_request with larger 3D Meshes/scenes. As example from my download link. 
In my project i call load_threaded_request from a Timer Callback. Mby that can be the issue to?

### Minimal reproduction project

Here is a link to the model which e.g. regularly generates errors. Format gltf.

https://we.tl/t-igAyO10JbY

**Comment by spindlebink** [comment]
Can confirm this one. The scene instantiated from a thread-loaded resource is usually missing meshes or materials, too, as you'd expect from a failed or incomplete load. It also appears that, although error spam happens every time, the incomplete loading doesn't.

Loading works fine if the threaded load is replaced by simple `load`.

**Comment by sboron** [comment]
missing itself also appears in ResourceLoader.Load / GD.Load. but he comes very rarely. Even if I provide the method for calling GD.Load with an "Await ProcessFrame".

USER ERROR: Creating buffers with data is forbidden during creation of a draw list
    at: RenderingDeviceVulkan :: vertex_buffer_create (drivers \ vulkan \ rendering_device_vulkan.cpp: 4014) - Condition "draw_list! = nullptr && p_data.size ()" is true. Returning: RID ()

**Comment by sboron** [comment]
Background. I'm currently writing a plug-in for asynchronous loading of complete scenes. Currently there is no way to load some PackedScene without get errors sometimes. With larger scenes, the probability of the error is higher.

**Comment by akien-mga** [comment]
Might have been fixed by #54890, please confirm.

**Comment by AThousandShips** [comment]
Testing and the loading during drawing appears to be gone along with the associated broken geometry

**Comment by Calinou** [comment]
> Testing and the loading during drawing appears to be gone along with the associated broken geometry

Do you mean that https://github.com/godotengine/godot/pull/54890 resolves this issue, or is the issue still present?

**Comment by AThousandShips** [comment]
I believe it solves this issue
