### ISSUE TITLE
Vulkan: Material colors appear washed out

### ISSUE THREAD

**Issue by Whimfoome** [godotengine/godot#54846]
### Godot version

4.0.dev.mono b46a42b689ac3c7396216153799f1324ca7b6356

### System information

Arch Linux

### Issue description

Godot 3:
![image](https://user-images.githubusercontent.com/42871796/141170254-8d0f57be-f2a7-4a79-93e2-135fe7213f78.png)

Godot 4 with the same material:
![image](https://user-images.githubusercontent.com/42871796/141170350-0cd3ef68-e5f8-42c4-8447-6d85988698e5.png)

Color hex: #d65c4c

Happens with my shader materials too:
![image](https://user-images.githubusercontent.com/42871796/141170568-efdffeb1-123f-49f1-a5d3-f72fd6583898.png)
![image](https://user-images.githubusercontent.com/42871796/141170693-96efba0a-def6-4c5d-932f-f940001b8725.png)
![image](https://user-images.githubusercontent.com/42871796/141170834-c0bd28ce-a160-448f-aff3-40be3cd8ca78.png)

### Steps to reproduce

1. Create StandartMaterial3D
2. Choose color in Albedo
3. The color is not correct in the material preview and in-game

Repeat in Godot 3, to see the difference

**Comment by Calinou** [comment]
> ### Godot version
>
> 4.0

Please specify the *exact* commit hash you're using, as 4.0 isn't released yet and is a moving target.

This was already reported in https://github.com/godotengine/godot/issues/54628, but @xsellier said it was fixed recently. See also https://github.com/godotengine/godot/issues/48573.

**Comment by Whimfoome** [comment]
> Please specify the _exact_ commit hash you're using, as 4.0 isn't released yet and is a moving target.

Just tried with the latest merged commit b46a42b689ac3c7396216153799f1324ca7b6356
Got the build from [github actions](https://github.com/godotengine/godot/actions/runs/1444190800)
The same thing happens

**Comment by fire** [comment]
Can confirm that this still exists with https://github.com/Vinc3r/cornellBox

![image](https://user-images.githubusercontent.com/32321/141521168-900d7e6f-abd9-4cc0-b884-4b54ab4eac03.png)

Disable preview directional light, and world env.

Created a world env with sdfgi, enabled occlusion and enabled sky contribution.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/54628.

**Comment by asperkraken** [comment]
For the record, this seems to be happening, same effect, with 2d Texture imports too. I am seeing several people importing images from Pixelorama and Aseprite complaining about this.

In 3.5, you would fix this by toggling the sRGB option to "Enable" rather than Detect. However, this feature seems to be changed or absent in Godot 4.

**Comment by Calinou** [comment]
@asperkraken Godot 4.0 onwards no longer has a sRGB texture import option, as textures are automatically rendered correctly in 3D. This means you can use the same texture in both 2D and 3D at the same time with it looking correct in both 2D and 3D.

Please open a new issue **with a minimal reproduction project attached**.
