### ISSUE TITLE
UI focus change is triggered too often when using gamepad analog stick to navigate menus (does not occur with D-pad or keyboard)

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#54959]
### Godot version

3.4 stable

### System information

Windows10, Nvidia

### Issue description

Navigating a menu with gamepad left stick axis is impossible using the default settings. 

Cannot focus on controls in the usual manner.
I've encountered this on older versions too.

### Steps to reproduce

1)Create a few contols on a 2D scene.

2)add gamepad left stick axis down to 'ui_down' & gamepad left stick axis up to 'ui_up' in Input under project settings

3)Try to navigate the controls using the left axis

4)Note you cannot focus like normal (like the way D-Pad works OK)

### Minimal reproduction project

Small sample project: https://ufile.io/uqvtj8wq
*Bugsquad edit:* Re-uploaded to GitHub: [GamepadFocusBug3_4.zip](https://github.com/godotengine/godot/files/7618199/GamepadFocusBug3_4.zip)

Open project, run scene.

Click the first checkbox control with mouse. 
Now try to use left stick axis on gamepad to navigate up and down the controls. Its impossible!

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/31880, and it works in the projects I've developed.

**Comment by rick551a** [comment]
I just checked it on your game Escape space, the left stick navigation issue is here too.

See flv video of menu screen:
https://ufile.io/5875zngv

**Comment by Calinou** [comment]
This was confirmed here: https://godotengine.org/qa/120771/analog-stick-rapidly-changes-focus-of-ui-nodes

cc @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
It's a regression in 3.4. It works fine in 3.3.4-stable, and the issue is already present in 3.4-beta1.

The next step to investigate is to do a git bisect between faf3f883d1a25ec8a2b7a31ecc9e3363613b2478 (3.3.4-stable) and 207fb165bfd1fefd1b4339c9427a569b19d0dcae (3.4-beta1) and test with a gamepad to figure out how it broke.

**Comment by pouleyKetchoupp** [comment]
I'm adding a junior job tag for anybody who would be interested in investigating the issue (see my comment above).

Note that fixing the issue itself will probably be a bit more involved and might not be a fit for junior job.

**Comment by Calinou** [comment]
I'm looking into bisecting this issue.

**Comment by AlbeyAmakiir** [comment]
Is the current workaround to detect unhandled analogue stick events and handle their conversion to `ui_direction` actions manually?

**Comment by akien-mga** [comment]
This is a regression from #44456, CC @univeous @KoBeWi @EricEzaM.

**Comment by univeous** [comment]
Oh, that's actually my bad and I think I know how to fix it. Should I do it on master or 3.x? @akien-mga 

Also, I don't know if this is off-topic. I said I can fix it which means I can make analog stick works as before( push stick and focus will move once, release it and push again to move focus again) while keyboard input will still work as my PR's purpose. But Having to push and release and push again to move focus in UI navigation is definitely annoying and a long-term issue(Since this problem is being fixed and regressed times, See #26853, #31880, #44456). Can we find a way to actually fix this?

#26825 is a related issue, I think it should be reopened.

**Comment by akien-mga** [comment]
> Should I do it on master or 3.x?

If the code is different, you can do two PRs, one for `master` and one for `3.x`. Otherwise if the code didn't change you can do the PR only for `master` and I can cherry-pick it for `3.x` (and `3.4`).

> #26825 is a related issue, I think it should be reopened.

This should be opened as a proposal on https://github.com/godotengine/godot-proposals. Adding a delayed echo system for joypad input in the UI can definitely be interesting but it would be more of a new feature/enhancement than a bugfix.

**Comment by univeous** [comment]
Done for 3.x. Seems UI focus is broken in master, will do later.

**Comment by akien-mga** [comment]
Fixed by #55480.

**Comment by Calinou** [comment]
Reopening, as this issue is still present in `master` (https://github.com/godotengine/godot/pull/55480 was merged on `3.x`).

**Comment by univeous** [comment]
> Done for 3.x. Seems UI focus is broken in master, will do later.

Maybe it's a little too later But #59575 ;)

**Comment by Vennnot** [comment]
Is this missing from 4.0?

**Comment by KoBeWi** [comment]
no

**Comment by sketchyfun** [comment]
This still seems to be an issue in v4.2 (custom build) [571cd0eb7]

**Comment by Calinou** [comment]
Please continue the discussion in https://github.com/godotengine/godot/issues/35751 and https://github.com/godotengine/godot/issues/73241.

**Comment by rick551a** [comment]
@TheDoorworlds, make a container and make a column of buttons. Style the buttons like menu entries. The gamepad works using this method, its a clunky workaround, but it works.

**Comment by albertkun** [comment]
any chance this fix will be back ported to 3.6?? 😭
