### ISSUE TITLE
Grid map changing mesh library .tres sub resource ids when saving scene

### ISSUE THREAD

**Issue by joemicmc** [godotengine/godot#55190]
### Godot version

Godot_v4.0-dev.20211108_win64

### System information

Windows 10 64 bit

### Issue description

Setup: Scene with grid map node which has assigned mesh library resource (in default .tres format).

Issue: After saving the scene, the sub_resource ids for mesh, image and image texture change. This is an issue when using source control as the .tres file has changed on disk.

### Steps to reproduce

- Open the repro project. 
- Load game.tscn. 
- Save the scene. 
- Check the .tres file.

The .tres sub resource ids for mesh, image and image texture have changed.

### Minimal reproduction project

[godot-tres-sub-resource-bug.zip](https://github.com/godotengine/godot/files/7576239/godot-tres-sub-resource-bug.zip)

**Comment by Calinou** [comment]
This is expected in Godot 3.x due to subresource IDs using an incremental number instead of an UUID. This was resolved in `master` by https://github.com/godotengine/godot/pull/50676, but it can't be resolved be resolved in `3.x` until https://github.com/godotengine/godot/pull/50693 is merged.

If you want https://github.com/godotengine/godot/pull/50693 to be merged faster, please [test it on your project](https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html) after making a backup :slightly_smiling_face:

**Comment by joemicmc** [comment]
@Calinou I raised this against godot 4.0, so possibly still an issue?

**Comment by officialduke99** [comment]
Hey, I am having the same issue (Godot 4.0 beta 14 on Windows 10 64bit) and would like to add insight to this. I don't think @joemicmc makes it absolutely clear, but the IDs don't change with every scene save. It only happens when the project or scene is first saved after being loaded/reloaded, then you can change and save the scene however many times you want, but the IDs will stay the same.

As a workaround for version control pinging you every time the MeshLibrary changes, it seems to me you can just completely .gitignore (or equivalent for your VCS) any new changes to the .tres file, as the IDs are not referenced anywhere else, but the MeshLibrary resource itself. It's not a good system, especially if your MeshLibraries have to be changed often, but it at least stops you from pointlessly pushing every ID change everytime you save a fresh scene.

**Comment by jming422** [comment]
For reference, I've also just run into this bug on Linux (Pop!_OS) as well, on v4.0.2.stable.official [7a0977ce2]

I'll be trying your workaround @officialduke99 for now, thanks

**Comment by Rindbee** [comment]
Similar to #74001.
The reason is that the image is saved as text. See https://github.com/godotengine/godot/issues/74001#issuecomment-1713527825.

**Comment by doseonfairsutdios** [comment]
This issue is still occurring in 4.2.1.

**Comment by joancardonasa** [comment]
Still occurring in 4.3

**Comment by bigmonmulgrew** [comment]
Same issue but I've noticed you don't even need to open and save the scene

I've been trying to work out the minimum or other triggers that cause it to update the tres files.

Option 1
Closed all tabs to prevent accidentally opening them, close godot
Return to github and discard any changes
Open Godot
Run the project, mine loaded onto a splash screen that doesn't reference the grid libraries at all
Close the game before it gets chance to open any other scenes
Return to github, library files have new IDs

Option 2
Open any scene that uses the grid map
save the scene
