### ISSUE TITLE
Input.get_vector() incorrectly uses joypad axis when using keybobard

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55264]
### Godot version

3.4 / 4.0

### System information

W10

### Issue description

I have movement actions mapped both to keyboard buttons and joypad analog sticks. When I press keyboard key, the `Input.get_vector()` will report a rotated vector, as if it was reading the joypad axis. But when I don't press anything, the vector is correctly 0.

Joypad and keyboard shouldn't interfere like this. Interestingly, the issue gets fixed after I press keys for every axis.

CC @aaronfranke 

### Steps to reproduce

1. Add a set of actions using both keyboard and joypad axes
2. Make sure you have a joypad connected
3. Print `Input.get_vector()` and press the keyboard keys
4. Notice the vector isn't aligned to axis as you'd expect

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/7589465/TestProject.zip)
Hold D and check the vector. You can also press WSAD and see that the vector gets fixed.
(needs a connected controller)

**Comment by Calinou** [comment]
Related to/duplicate of https://github.com/godotengine/godot/issues/45628.

**Comment by aaronfranke** [comment]
@KoBeWi What are the raw strength values? I suspect this is related to https://github.com/godotengine/godot-docs/issues/5378

This is starting to convince me that @golddotasksquestions was right and the circular deadzone is always worse than the cross-shaped deadzones.

**Comment by KoBeWi** [comment]
#45628 looks like the same issue, but I can't reproduce it with the provided project. It uses `Input.get_action_strenght()`, which works fine for me.

**Comment by KoBeWi** [comment]
> What are the raw strength values? 

These are the values when I hold `right` action on keyboard:
```
(0.985020, -0.037025) L 0.00784301757812 R 1 U 0.03729362040758 D 0
```
(the first one is the vector)

Seems like both left and right are non-zero...

**Comment by akien-mga** [comment]
If it's a duplicate of #45628, it might be fixed by #47599. Would be worth testing to confirm.

**Comment by madmiraal** [comment]
> If it's a duplicate of https://github.com/godotengine/godot/issues/45628, it might be fixed by https://github.com/godotengine/godot/pull/47599. Would be worth testing to confirm.

This issue is more than #45628. Although things would be improved by #47599, this is primarily an issue with dead zones as discussed in godotengine/godot-proposals#3709. Specifically, should joysticks have a circular dead zone (as suggested by https://github.com/godotengine/godot/pull/42976#issuecomment-714419377), a cross-shaped dead zone (as suggested by this issue), or should the user be able to decide.

**Comment by jojorne** [comment]
Unless I'm misunderstanding, this seems like the same issue as #90515?

**Comment by ygypt** [comment]
This is essential for any game, and its astonishing that this issues been open for as long as it has. Could this be fixed with a few lines? If one device is within deadzone, don't apply it's strength to the vector

**Comment by jojorne** [comment]
The workaround works. You need to split the devices on their own entry and check the input with methods that accept names, e g., "left_kb" || "left_js".

**Comment by theMotionblur** [comment]
Godot 4.4 Beta1 - problem still exists.

I found that `Input.get_vector()` will take into account any ever so slight direction from an analog stick even with the deadzone set to 0.5.

On the other hand when using` direction = Input.get_vector("Left", "Right", "Up", "Down").normalized` you will get a compareable result but the deadzone is ignored and input works flawlessly from digital keys (WASD)

I've made a small demo project to test this. Idealy you have a joypad with a well used analog stick (and probably without hall-effect sticks) to test this on your end:
[inputaxisdrift.zip](https://github.com/user-attachments/files/18563594/inputaxisdrift.zip)

**Comment by theMotionblur** [comment]
> > If it's a duplicate of [#45628](https://github.com/godotengine/godot/issues/45628), it might be fixed by [#47599](https://github.com/godotengine/godot/pull/47599). Would be worth testing to confirm.
> 
> This issue is more than [#45628](https://github.com/godotengine/godot/issues/45628). Although things would be improved by [#47599](https://github.com/godotengine/godot/pull/47599), this is primarily an issue with dead zones as discussed in [godotengine/godot-proposals#3709](https://github.com/godotengine/godot-proposals/issues/3709). Specifically, should joysticks have a circular dead zone (as suggested by [#42976 (comment)](https://github.com/godotengine/godot/pull/42976#issuecomment-714419377)), a cross-shaped dead zone (as suggested by this issue), or should the user be able to decide.

I am not an expert in this, like at all. So I could be extremely mistaken but since get_vector uses get_action_raw_strength() the problem seems to me that any potential deadzone for the stick will always be overridden because the deadzone only triggers as long as the input is below the threshold. Since Keyboard and Gamepad drift are registered/coming from the same axis, though, the 1.0 Input strength from the keyboard will always override any deadzone filter so the raw read will always get every input for the entry.

For this to work in one Input Entry any joystick input would have the deadzone filtered out separately and before the final strength gets read. This would eliminate the purpose of the raw axis strength, though.

**Comment by Taffroi** [comment]
Problem still exists in Godot 4.4 Beta3

**Comment by tylermcbride** [comment]
Still a problem in Godot 4.4.1, with a gamepad plugged in all Input.get_vector inputs are offset by very small amounts. The Deadzone property of both Input Map & Input.get_vector do not alleviate the issue.
