### ISSUE TITLE
Children of (V,H)BoxContainer can be moved by manipulating with values in the inspector

### ISSUE THREAD

**Issue by SuperTemich2005** [godotengine/godot#55270]
### Godot version

3.2.3.stable

### System information

Windows 10

### Issue description

You can not move children of the (V,H)BoxContainer in the editor, unless you access it's values in the inspector.
Once the scene is refreshed, illegal shift is reverted.

### Steps to reproduce

1)
![image](https://user-images.githubusercontent.com/39464061/143084054-09ab720f-11b4-4e93-9a9f-ceeda2964b9c.png)
Try to move the child node of the (V,H)BoxContainer
2) Go to the inspector and change rect_position or position of the object
![image](https://user-images.githubusercontent.com/39464061/143084193-dc6b676e-36d0-4271-9c9b-45ba6c6b8150.png)
(Button labeled Разговор is a child of HBoxContainer node, yet by manipulating with rect_position.y it can be shifted N units along Y axis. Same for X axis. Button labeled Осмотреть is where it's supposed to be)
3) Switch to another tab (in my case, i switch to ahata_day1.tscn from investigation_v3.tscn)
![image](https://user-images.githubusercontent.com/39464061/143084424-ee9773d6-5346-4119-b3c6-2745edc0d73c.png)

4) return to the tab you've switched from (back to investigation_v3.tscn)
![image](https://user-images.githubusercontent.com/39464061/143084514-61c57bfb-7b39-4685-aff9-af3fb29c8bde.png)

5) Child is in place, as if it wasn't moved (button labeled Разговор teleported to where it's supposed to be, I haven't changed any values related to it myself, it did it itself)
![image](https://user-images.githubusercontent.com/39464061/143084592-e35b9a1e-5473-4f18-8f00-84d27a2cc663.png)

**Comment by SuperTemich2005** [comment]
This issue was originally discovered by InSaNe_97#4268 and he used v3.4.stable.official [206ba70f4]. It means that the bug exists at least from 3.2.3.stable and has been carried over to at least 3.4 release

**Comment by pycbouh** [comment]
This is a known issue, and it's already fixed in `master` by disabling those properties when inside of a container. We also work on the new workflow to prevent users from accessing irrelevant properties when working on children of containers.

**Comment by superPilipala** [comment]
You can't fix this bug like this.When I want to iterate a container on top of a container of my own, for example, I want to follow the arrangement of the container in the y-direction and make some offsets in the x-direction to make a radial menu. Disabling the position property of the child node complicates my ability to do this effect. And, on the other hand, I want to make a ui animation for the nodes inside the container, and not being able to change the position of the child nodes makes the effect very bad

**Comment by superPilipala** [comment]
Sorry, I didn't get it right, it's possible to extends the BoxContainer with the fit_child_in_rect() method, but the animation problem is still not known what to do.
