### ISSUE TITLE
CollisionShape2D contains unstable graphical glitches

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#56320]
### Godot version

4.0.dev (9f05867)

### System information

Windows 10

### Issue description

CollisionShape2D does not visually represent the shape as intended. Visual glitches compound when resizing or toggling "snap 2d transforms to pixel" or "snap 2d Vertices To Pixel". Present in all shapes.

https://user-images.githubusercontent.com/21325943/147687051-eda526e8-dcaa-40ae-a230-53ac05934657.mp4

### Steps to reproduce

Create new project.
Add CollisionShape2D Node to CollisionObject2D derived Node
Add any shape.

**Comment by markdibarry** [comment]
Graphical glitches confirmed for all shapes:
![image](https://user-images.githubusercontent.com/21325943/148083511-146bc44b-a4f7-47c2-b67e-b9ac1438b729.png)
![image](https://user-images.githubusercontent.com/21325943/148083546-c2004063-ca5a-4095-9a5e-7e8866f37dd3.png)

Not sure if it's just graphical or affects collisions as well, but it's only visibly noticeable if making a smaller screen game, which might be why it hasn't been noticed until now. However, if one is making a smaller screen game, it's very noticeable (ex: attached images).
Confirmed by other user in nightly build.
Going to look through to see how long this has been in the master branch, or if it's always been busted since Vulkan integration.

**Comment by markdibarry** [comment]
Just a note, that the behavior is present in-game as well when collision shapes are set to visible.

**Comment by rburing** [comment]
The pointy geometry at the edge of each shape is the polyline introduced by https://github.com/godotengine/godot/pull/34923. That polyline is not very attractive when the view is zoomed in this far, and the snapping options affect the polyline to make it look even worse.

**Comment by markdibarry** [comment]
That makes sense. The inconsistent size and shape of the polyline makes it look unintentional and harder to see where the edges are for smaller resolution games, even with snapping off. It definitely makes for a worse experience, but the snapping completely breaks the feature.

I guess there are two ways to go with this (and I probably know which it will be).

1. Get the polyline to have consistent size and angles, and find a way to get it to behave properly with pixel snap.
2. Add a checkbox to enable/disable the polyline collison outline for users with smaller resolution games.

**Comment by rburing** [comment]
A project setting to disable the outlines already exists, but the editor is hardcoded to show them always:

https://github.com/godotengine/godot/blob/c13319db8d26604bc4074883f417512138fdfc57/scene/resources/shape_2d.cpp#L112-L119

Maybe the editor should also respect the setting, or there should be an extra setting for the editor?

An alternative to the polyline (maybe not the best as a default, but maybe as an option) could be a multiline drawn with `canvas_item_add_multiline`. It has the same thickness at every zoom level, and will respect snapping without the artifacts seen with the polyline. Unfortunately it currently seems to ignore both the `p_width` and the `p_colors` parameters, always drawing 1px white lines.

**Comment by markdibarry** [comment]
I'm starting to think that this feature should be removed until a better implementation can be made. Even with some of the proposed solutions to making the issues less obvious, the core concept of using a polyline seems to be the main issue. The size/shape of the outline of a collision shape shouldn't be directly tied to the level of the zoom/resolution of the game and whether or not snapping is enabled. This isn't the case, and it makes the problem the feature intends to solve (better visibility of the collision shape edges) worse for all but certain scenarios.

**Comment by dalexeev** [comment]
As far as I remember with #41239 `RectangleShape2D` looks better. But due to rendering changes, a lot of things are rendered a little wrong. The attention of the maintainers to this part is required.

**Comment by AThousandShips** [comment]
Should we pin this? Given how ridiculously many duplicates we're seeing

**Comment by dalexeev** [comment]
The problem is probably caused by the `RendererCanvasCull::canvas_item_add_polyline` method. Here's how it's drawn now (I increased the line width for clarity):

![](https://user-images.githubusercontent.com/47700418/211498174-85c1ffcb-427f-4e44-a8ec-7b15cafd3916.png)

Notice the bulges at the ends of the polyline. They also appear in the middle of the polyline if the angle between the segments is not straight:

![](https://user-images.githubusercontent.com/47700418/211498518-605b93c5-410a-4b06-a872-bfdc67d6ab7a.png)

I'm not sure what the behavior of this method should be, but it's used here, for example, to stroke the borders:

https://github.com/godotengine/godot/blob/269fa200d04ae96b0114b788e18df638c5fb164b/scene/resources/rectangle_shape_2d.cpp#L70-L90

**Comment by markdibarry** [comment]
There is also the issue that the line gets bigger/smaller depending on the zoom level, which doesn't seem intentional, and can cause it to be difficult to see what you're doing when working with pixel/lo-res games, even if it's working correctly.

**Comment by aaronfranke** [comment]
Is this issue still present after #69851?

**Comment by dalexeev** [comment]
I think this issue is fixed by a combination of the following PRs:

* #62236
* #69851
* #71679
* #41239
* #72302

**Comment by markdibarry** [comment]
@dalexeev @aaronfranke Unfortunately, the PRs mentioned are unrelated to this issue. I just made a fresh build and the graphical bug still displays the collision shape incorrectly.

https://user-images.githubusercontent.com/21325943/215673372-5e8ef45e-d8ca-42a6-acbd-525088e57a6f.mp4

**Comment by dalexeev** [comment]
@markdibarry I cannot reproduce this (standard version, Linux). OP describes another bug that has been fixed. The bug on your video may not be related to rendering at all, it may be an error in the editor (wrong position of the handles).

**Comment by markdibarry** [comment]
@dalexeev I'm not sure why you can't reproduce it, considering it's the exact same MRP setupd since the bug was first discovered, but I've made a new project in the latest build just so we can be sure.
[CollisionDisplayBug.zip](https://github.com/godotengine/godot/files/10546986/CollisionDisplayBug.zip)

And for reference, here is the snapping behavior in 3.5.1:
 

https://user-images.githubusercontent.com/21325943/215779456-a9e63c93-2c11-4558-99b6-baf9f805ac8e.mp4

And here is the same setup in 4.x

https://user-images.githubusercontent.com/21325943/215779529-db1ad258-5ad6-467b-aa4d-248af38e6674.mp4

**Comment by dalexeev** [comment]
Yes, I see. But this bug does not reproduce for me. Maybe it's platform specific. Or depends on the graphics card/drivers. Need testing.

https://user-images.githubusercontent.com/47700418/215802244-e0d95e26-8222-48e1-a648-786bc8ff20d0.mp4

**Comment by markdibarry** [comment]
Oh interesting! Any more information about your setup? I have a `NVIDIA GeForce GTX 960` and am using `Forward+`. I remember there was a workaround setting for flickering in 3.x in regards to NVIDIA cards, but that was removed in 4.0. As mentioned earlier in the thread, it shows only when `Snap 2D Transforms to Pixel` is enabled, where I believe `Snap 2D Vertices to Pixel` more mimics the setting `Use GPU Pixel Snap` in 3.x. Though, even without it on, you end up with some very weird non-square shapes. Not sure how intentional that is.
![image](https://user-images.githubusercontent.com/21325943/215806227-d888caa4-8278-4fff-a53c-0427e4c19e44.png)
![image](https://user-images.githubusercontent.com/21325943/215806281-6fc09f60-d7e2-4199-b36a-07106e294f51.png)
![image](https://user-images.githubusercontent.com/21325943/215806350-9c71ceab-3c81-42b3-9c97-65068d732931.png)

**Comment by dalexeev** [comment]
I confirm this issue, it reproduces when these settings are enabled, at very high zoom:

![](https://user-images.githubusercontent.com/47700418/215805604-5956cc8e-0447-4909-8014-6b6a0f707eaa.png)

This detail has been removed from the issue title, so I tested without these settings.

**Comment by markdibarry** [comment]
Ah. Yeah, all of the MRPs designate that it's related to these snapping settings. Phew, thought I was going crazy!

**Comment by dalexeev** [comment]
I'm not sure if this issue is solvable due to how collision shape drawing works. No separate `SubViewport` or `CanvasLayer` is used for this purpose. The same transforms and shaders are applied. The collision shapes you see in the editor are normal canvas items. Unlike editor handles, which are drawn in a different SubViewport.

@clayjohn @kleonc What do you think about this?

**Comment by clayjohn** [comment]
> I'm not sure if this issue is solvable due to how collision shape drawing works. No separate `SubViewport` or `CanvasLayer` is used for this purpose. The same transforms and shaders are applied. The collision shapes you see in the editor are normal canvas items. Unlike editor handles, which are drawn in a different `SubViewport`.
> 
> @clayjohn @kleonc What do you think about this?

To me it looks like a floating point error. NVidia GPUs are pretty loose with floating point so if you take the floor of a whole number, you sometimes snap down to another number. (i.e. floor(7.0) may return 6.0 or 7.0). I remember a similar bug in 3.x with the ``Use GPU Pixel Snap`` setting. We solved it by adding a small "fudge" value to ensure that whole numbers were not rounding down

**Comment by kleonc** [comment]
@clayjohn I don't think that's a floating point error. Not saying these don't happen, just not the issue in here. I think @dalexeev already pointed out the problem: the collision shape's debug drawing is affected by the rendering settings like `rendering/2d/snap/snap_2d_transforms_to_pixel` but the actual collision shape is not being snapped (neither the node nor the body within the physics server; and that's good these are not snapped). Hence the discrepancy, debug drawing is incorrect / not reliable when snapping is enabled.

The same problem occurs for the in-game debug collision shapes, that's not just in-editor issue.

Regarding specific cases:

> ![image](https://user-images.githubusercontent.com/21325943/215807207-8e50e73b-b504-4aef-9a41-e637f550c475.png)

In here the handles are correctly snapped within the editor "to pixels". This results in the position of the shape (its center) possibly ending up having non-zero fractional part. Specifically, if all handles are snapped then for odd width/height the center is at `.5` / half "pixel", as seen above. When `rendering/2d/snap/snap_2d_transforms_to_pixel` is enabled this position is being snapped (by flooring) when the debug shape is being rendered, hence the result.
What's worse, seems like the transform snapping happens... in a per-canvas-item manner, not just once for the final/global transform. This means that this `.5` error above can become massive if e.g. parent is scaled. But even without scaling if the parent's transform would have some `.5` position as well then the difference between the debug rendering (the snapped one) and the actual shape (or editor handles) could still be enlarged comapred to what it's locally. The more parents up the tree, the bigger potential discrepancy.
Personally, I don't see what `rendering/2d/snap/snap_2d_transforms_to_pixel` can be useful for. I'd guess it likely causes more issues than it solves. IIRC it was added to solve some issue with Camera2D jittering but to me it looks like a band-aid fix which maybe fixed some specific use case but in general it doesn't make much sense to me. If it would be my decision I'd remove that setting right away.


> ![image](https://user-images.githubusercontent.com/21325943/215806227-d888caa4-8278-4fff-a53c-0427e4c19e44.png)

That's a correct rendering according to the settings. I mean I think rendering of the collision shapes shouldn't be affected by these settings in the first place but if they are then the result looks correct. This is a snapped circle. :laughing: What might seem strange / not intuitive is that it's producing non-symmetrical shape. The reason is snapping being done by flooring, not by rounding. If rounding would be used instead then the result should be symmetrical (besides exact "half points" / some floating point error edge cases).

---

Here's some test project showing the problem in a running project:
[collision_shape_snap_test.zip](https://github.com/godotengine/godot/files/10550639/collision_shape_snap_test.zip) (enable visible debug collision shapes)

![38i8cHCyId](https://user-images.githubusercontent.com/9283098/215874437-a8bcb054-30b0-41e6-a91d-5f8130a76b7d.gif)


Not sure what would be a proper way of fixing this.

**Comment by dalexeev** [comment]
> To me it looks like a floating point error. NVidia GPUs are pretty loose with floating point so if you take the floor of a whole number, you sometimes snap down to another number.

I reproduced this, but I have an integrated Intel graphics card, not NVIDIA.

**Comment by clayjohn** [comment]
@kleonc I should clarify. I think this is a rendering bug not a CollisionShape bug. The same bug is likely present in rendering everything that uses the same underlying primitive as the CollisionShape2D debug drawing

**Comment by dalexeev** [comment]
I think that inaccurate display of collision shapes in a running project is expected and acceptable. Shapes cannot be rendered more precisely than the `Viewport` they are in. Even with the most ideal rendering, the sizes and positions of bodies/areas do not have to fit into the pixel grid. Because of what we can easily get a visual error of 1 pixel.

But I agree that in the editor this behavior is less expected and more confusing for users, since the handles are displayed correctly.

We could probably solve this problem by rendering the collision shapes in a separate `SubViewport` (same as the handles). This is how it works for `CollisionPolygon2D`'s outline. The question is how difficult it will be to do and whether it is worth it.

**Comment by dalexeev** [comment]
https://user-images.githubusercontent.com/47700418/215885547-6ab6d4a4-71bf-43b3-bb99-6ced4fa6370b.mp4

The polygon itself and the thin stroke are drawn here:

https://github.com/godotengine/godot/blob/0810ecaafdbee3ea747219e6ab3a8de5d2216a09/scene/2d/collision_polygon_2d.cpp#L128-L152

The thick stroke that appears when a polygon is selected in the editor is drawn here:

https://github.com/godotengine/godot/blob/0810ecaafdbee3ea747219e6ab3a8de5d2216a09/editor/plugins/abstract_polygon_2d_editor.cpp#L488-L497

**Comment by markdibarry** [comment]
They all have their issues, but here's a good view of each scenario.
With neither options selected:

https://user-images.githubusercontent.com/21325943/216079869-26d6edd3-d445-4748-b228-b292835762f5.mp4

With just snap vertices:

https://user-images.githubusercontent.com/21325943/216079985-f8ec9322-dc32-4d2e-a6b4-7e294f33d8c5.mp4

With just snap transform:

https://user-images.githubusercontent.com/21325943/216080043-9e18cc4e-cc7f-41a7-ad43-4df10851e594.mp4

With both enabled:

https://user-images.githubusercontent.com/21325943/216080099-6196078b-d2b1-49e1-aff5-f07d8a8c4426.mp4

Weirdly, with both off, the rendering of the collision shape changes size as the character moves, and in all scenarios displays the collision shapes overlapping on the left, but not on the right.
