### ISSUE TITLE
Vulkan: SSIL cause partial viewport flashing when resizing the window

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56724]
### Godot version

4.0.dev (b6b81e800)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

SSIL cause partial viewport flashing when resizing the window. This flashing does not occur if SSIL is disabled. This is something I noticed while working on a minimal reproduction project for https://github.com/godotengine/godot/issues/56723.

*Warning: video below contains some flashing when the window is resized.*

https://user-images.githubusercontent.com/180032/149147667-bf901d63-5d79-45da-8dbd-f6d6722d3fb0.mp4

### Steps to reproduce

- Add some MeshInstance3Ds and a DirectionalLight3D so you can see light bounce around once SSIL is enabled.
- Add a WorldEnvironment node with a new Environment resource.
- Enable SSIL in the Environment resource.
- Resize the editor window. Observe that the 3D viewport will occasionally flash in the bottom/right corners when the rendering buffers are reallocated (as a result of the resolution change).

### Minimal reproduction project

[test_ssil_3.zip](https://github.com/godotengine/godot/files/7854794/test_ssil_3.zip)

**Comment by clayjohn** [comment]
I think this should have been fixed by Bastiaan's recent fixes. Can you confirm?

**Comment by Calinou** [comment]
I can still reproduce this on 4.0.rc 7e79aead9 and 4.0.rc e930c8d38 (which is roughly 4.0.rc4):

https://user-images.githubusercontent.com/180032/221047494-5f9f528d-8200-4e54-bc3b-e6e11b0fffea.mp4

**Comment by BastiaanOlij** [comment]
I'm going to have another look at this as I had this fixed at some point
