### ISSUE TITLE
FileSystem drag and drop can easily lead to missing dependencies issues

### ISSUE THREAD

**Issue by jaydonteh** [godotengine/godot#5684]
**Windows 10 - Godot 2.1 :**

**fileSystem usability:**
After **accidental** moving of folders using the drag & drop feature from the fileSystem, along with a manual correction to re-parent my folders will not revert their new paths and cause missing dependencies issues. Having me needed to correct all my scripts, assets and scenes that got involved prior to moving.

**Steps to reproduce:**
Move folders into folders using drag & drop from the fileSystem; folders that contain assets that were attached to scenes.

**Suggestion:**
Alert user with a message when moving a folder that contain assets that were attached to node/scenes, changing them will cause missing dependencies, even manually reverting any changes.

**Comment by vnen** [comment]
Did you do this all via the FileSystem dock, or did you correct using the OS file explorer? AFAIK any change you do in the FileSystem dock will update the references in the owners. So if you reverted through the dock it should rearrange again the dependencies (and if it's not doing it, it's a bug indeed).

If you try to delete a file it warns of the dependency breakage, maybe it should warn too if you're moving files with owners.

**Comment by jaydonteh** [comment]
All has been done through the FileSystem, indeed it never rearrange again and cause dependencies error whenever trying to open the affected scenes.

**Comment by reduz** [comment]
moving files in theory rearranges dependencies automatically, maybe it's broken?

**Comment by akien-mga** [comment]
I've played a bit with the FileSystem dock and could not reproduce the issue, though I did notice some bugs (like moving a folder inside another one, and then it won't let you move it back to `res://`, saying it can't move itself to its current location - though the error is wrong). Nothing critical for the imminent 2.1 release though, but it could be fixed in a future update when the bug has been narrowed down more precisely.

**Comment by bojidar-bg** [comment]
Pretty ping, can this be reproduced, and if so, how? :smiley:

**Comment by Zylann** [comment]
Related? https://godotengine.org/qa/14122/create-folder-move-scene-unable-scene-more-help-this-feature

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Zireael07** [comment]
I don't know if dragging a folder causes this, but I've had this problem after I moved a font to a new subfolder, Godot couldn't find it.

**Comment by vnen** [comment]
It's worse on master because the dependency checker is not working at all (#9685)

**Comment by MillionOstrich** [comment]
I may have found out how to reproduce this issue. If a project has the following folders:
```
res://
    folder 1/
    folder 2/
        file
```
Then we use the folder tree (it has to be the tree) to drag "folder 2" into "folder 1". The path to file is now `res://folder 1/folder 2/file` but the dependencies are renamed to `res://folder 1/file`.

**Comment by HummusSamurai** [comment]
Possibly fixed by https://github.com/godotengine/godot/pull/11428

**Comment by HummusSamurai** [comment]
Fixed by https://github.com/godotengine/godot/pull/13384?

**Comment by akien-mga** [comment]
Probably fixed or mitigated by the above yes. Please file a new issue if a similar bug is still reproducible in the master branch.

**Comment by trsBasicLine10** [comment]
v3.0.2 move tscn file into a folder using dock cant save. google problem, seems i can save as but i am not sure how to replace original with new. anyway above says its fixed. i have a problem moving with drag/drop and the "move to" right click option. causes crash to desk top most times
