### ISSUE TITLE
Navigation2D get_simple_path() with TileMap broken

### ISSUE THREAD

**Issue by realgdman** [godotengine/godot#56852]
### Godot version

3.5.beta1

### System information

Windows 10, GLES3

### Issue description

I have encountered numerous issues using Navigation2D with Tilemap after upgrading to 3.5 beta

1. ~~Agent seems to ignore radius. (this version does not use agents)~~
Navigation2D seems to ignore object's collision shape. In 3.4, path was laid through cell's center, in 3.5 it sticks to edge of cells, which leads to agent stuck.
2. I've noticed there are non-int coordinates along the path in 3.5. In 3.4 they are always integer, except 1st and last, which are target and object.
3. In 3.4, path was more organic and using 8-directions. In 3.5, path appears to be manhattan only.
4. In 3.5, sometimes path just bugged, sticking to some (closest?) edge upward and then cutting through cells.
![image](https://user-images.githubusercontent.com/83962805/149680732-c4943a1e-52f8-45b7-8f40-21992f2a341d.png)

This issue is about opening 3.4 project with 3.5. Currently get_simple_path() behavior have breaking changes, does that mean it will be deprecated in favor of rewriting to navserver?

### Steps to reproduce

Create Navigation2D with TileMap child
Create some enemies.
Get path from $Navigation2D.get_simple_path(global_position, target_global_position)
 

### Minimal reproduction project

This is testing project I'm using.
[basic-pathfinding-Godot.zip](https://github.com/godotengine/godot/files/7878096/basic-pathfinding-Godot.zip)

**Comment by realgdman** [comment]
Isolated scene with path going straight up first
![image](https://user-images.githubusercontent.com/83962805/149682571-ea349f84-8f87-4743-adef-b4023d440067.png)
[navbug.zip](https://github.com/godotengine/godot/files/7878176/navbug.zip)

**Comment by realgdman** [comment]
Actually I have tried rewriting to Navigation Server with NavigationAgent2D and believe encountered 1 and 4 as well.
![image](https://user-images.githubusercontent.com/83962805/149683519-d17f5bc2-df44-4760-bfec-8f7e70a5a701.png)
[navservbug.zip](https://github.com/godotengine/godot/files/7878239/navservbug.zip)

**Comment by quiyip** [comment]
I feel like the new navigation system needs a lot more work.

This is me loading the exact same project in 2 different versions:

![image](https://user-images.githubusercontent.com/95621115/150116296-2f51c8eb-a9bb-46ae-a035-b12355e3d13d.png)
![image](https://user-images.githubusercontent.com/95621115/150117096-ea732c6c-b647-45cd-874a-8b552ac8fd91.png)

[Test.zip](https://github.com/godotengine/godot/files/7896487/Test.zip)

**Comment by Scony** [comment]
The "bugs" you see are due to very large `cell_size` and `edge_connection_margin` default settings in `Navigation2D` node. With values set to `1` and `1` the polygons are connected as in Godot <= `3.4` and everything works as expected.

Regarding manhattan paths (3) - could you please create a separate issue for that? That's totally different problem.

**Comment by realgdman** [comment]
@Scony Thanks for your time! Setting another defaults indeed solving point 2.
But point 1. still stays, regarding not accounting shape of agent vs tilemap, which is game breaking for me now
I'm attaching video of expected (as of 3.4) and observed (as of 3.5b1)


https://user-images.githubusercontent.com/83962805/150685526-3c45d957-f19c-419a-a465-b939580553bf.mp4


https://user-images.githubusercontent.com/83962805/150685539-1f1164a0-f213-4728-849c-c50eccda10b5.mp4

**Comment by Scony** [comment]
@realgdman regarding point (1) - Godot was never accounting shape of agent vs tilemap. If you'd increase the size of your agent 3 times while preserving tile sizes you'd see it in any Godot 3. The only thing which is different now (in `3.x`) is how "non-optimized" paths are calculated. That's the actual issue.

**Comment by akien-mga** [comment]
Fixed by #57081.

**Comment by realgdman** [comment]
@akien-mga the 1-st issue isn't fixed, see attached videos in previous post.

**Comment by akien-mga** [comment]
It's usually preferred to have 1 bug == 1 issue so that we can track root causes and their resolutions properly.

**Comment by Scony** [comment]
I've checked the issue with paths being manhattan-only and the regression came with early commits of the new navigation.

I tested it with my custom backport of new navigation which I did back in 2020: https://github.com/Scony/godot/commits/cherry-pick-new-navigation which backports just a 6 core commits from @AndreaCatania 

The result is following:
![2022-02-05-150044_4480x1440_scrot](https://user-images.githubusercontent.com/1207385/152645324-e25d6ee9-eb62-4c90-b180-10184b362424.png)

While it should look like this:
![2022-02-05-145922_4480x1440_scrot](https://user-images.githubusercontent.com/1207385/152645330-37f31d16-85be-4ce3-aab1-35ae2cb91fce.png)

Once I got some time I'll narrow it down further and draft some fix for it.

**Comment by Scony** [comment]
I've created some simplified tests to check differences on how `3.x` paths of `get_simple_path` are calculated (`black`) vs `3.2` (`green`).

Non-optimized:
![2022-02-13-221248_4480x1440_scrot](https://user-images.githubusercontent.com/1207385/153775376-a914620c-77f3-4683-aa63-addf6c7a0c32.png)

Optimized:
![2022-02-13-221259_4480x1440_scrot](https://user-images.githubusercontent.com/1207385/153775390-caa26a8f-74c5-4de6-9381-51452c2b95ed.png)

Demos:
`2d/GetSimplePathTests.tscn` and `2d/GetSimplePathOptimizeTests.tscn` from this project:
[godot-navigation-demos.zip](https://github.com/godotengine/godot/files/8056678/godot-navigation-demos.zip)

I'll probably draft some PR in the upcoming few weeks. 
Btw. @kleonc if you have some time, this one may be potentially interesting to you.

**Comment by akien-mga** [comment]
Fixed by #58209.
