### ISSUE TITLE
Ability to declare groups

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5744]
Similar to physic layers, I would like to be able to pre-declare groups, so I can see the list when I want to add one to a node in the editor. Currently, I used groups in my project but to remember them I have to dig in the scenes where I used them, sometimes I make typos and loose time debugging this. Having a list would be handy (even more for non-coders) and reduce errors made in the editor.
I currently centralize group names in an auto-load script so I have auto-completion when writing code, but it's not very useful in the editor.

**Comment by Ace-Dragon** [comment]
Sounds like an excellent idea to me, someone please make it happen.

**Comment by kubecz3k** [comment]
Some small editor plugin I was working on that aims this need: https://www.youtube.com/watch?v=inBR5-071ko 
Will publish sources in the weekend and hopefully upload it to asset store. It's not very polished but it works.

**Comment by willnationsdev** [comment]
Perhaps just have a cache of user-defined groups and list them in a dropdown as users type out the name of the group they would like to add to a node? And have it filter as you type, similar to how the Add a Node dialogue filters out node types as you enter text?

**Comment by Zylann** [comment]
It would also relate to this PR https://github.com/godotengine/godot/pull/16502
Which however is not exactly about the same issue.

**Comment by eon-s** [comment]
I really need to stop duplicating this issue, check the second one for an idea of how can be done.

**Comment by xDGameStudios** [comment]
@eon-s, I’ll take a shot at this issue!! Will keep in touch :) taking into consideration #18861 and #20416

**Comment by akien-mga** [comment]
Fixed by #16502.

**Comment by Zylann** [comment]
#16502 does not fix the issue, because it doesn't address project-wide declaration of groups.

**Comment by akien-mga** [comment]
That's weird, what does it do then?

In any case, if it's not implemented yet, this should be moved to a GIP on [godot-proposals](https://github.com/godotengine/godot-proposals).
