### ISSUE TITLE
Vulkan: Triangle glitch on a model with a rectangle hole due to automatic mesh LOD

### ISSUE THREAD

**Issue by Acvarium** [godotengine/godot#58242]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Ubuntu 21.10. nVidia GeForce GTX 870M with 470.103.01 driver. Vulkan

### Issue description

A strange glitch, that I noticed on this model. Tested in blender, Godot 3.4.3 and F3D viewer. Does not show up in any of those, other then Godot 4.0 alpha 2 with bout Vulkan and Vulkan mobile render  

![scr2022-02-17_001](https://user-images.githubusercontent.com/463177/154504729-e8b6c57a-d6a4-43a5-8ade-2881cba4adae.png)

### Steps to reproduce

Open minimal reproduction project or import model

### Minimal reproduction project

[triangle_glitch.zip](https://github.com/godotengine/godot/files/8089493/triangle_glitch.zip)

**Comment by Calinou** [comment]
I can confirm this on `master` 171021145.

The triangle is only visible at certain viewing angles:

https://user-images.githubusercontent.com/180032/154536457-6f082ce5-b731-4b32-b6a1-bfdeca96ee6d.mp4

Disable **Generate Lods** in the Import dock after selecting the 3D scene (then reloading the saved scene) fixes this issue, so this is related to automatic mesh LOD.

**Comment by fire** [comment]
I think this is an upstream bug, might be easily fixable. 

Upstream is https://github.com/zeux/meshoptimizer

**Comment by fire** [comment]
May be fixed by https://github.com/godotengine/godot/pull/70446

**Comment by fire** [comment]
I think this is fixed by https://github.com/godotengine/godot/pull/70446. Like in the latest rc3.

**Comment by akien-mga** [comment]
Still reproducible in 4.0 RC 3:

![image](https://user-images.githubusercontent.com/4701338/220959493-5cf57856-2a60-40b0-bb99-8facfbf00f9b.png)

**Comment by fire** [comment]
Maybe fixed now I can't find the angle that fails.

**Comment by zeux** [comment]
Yeah I can't reproduce it after reimport on master. I think this was fixed by https://github.com/godotengine/godot/pull/84384 - that version has an improvement to flip detection that would have solved cases like the above. Can probably close this.

**Comment by akien-mga** [comment]
Thanks for testing!

Fixed by #84384.
