### ISSUE TITLE
SubViewport button + camera zoom issue

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#59887]
### Godot version

Godot_v3.4.4 stable

### System information

window10 GLS3

### Issue description

the mouse position for a button inside a viewPort doesnt upDate when zooming in / out a 2Dcamera.

I found several issues in gitHub concerning viewPorts and mouse position, but none were mentioning that the same problem accours when zooming the camera in or out

![gdViewPort](https://user-images.githubusercontent.com/77213594/161607349-5307b869-9b8d-4780-acff-b8c69308e853.gif)

### Steps to reproduce

node2D
-button
-viewPort Container
--viewPort
---button

onready var testBTN = get_node_or_null("ViewportContainer/Viewport/Button");
onready var VvPort = get_node_or_null("ViewportContainer/Viewport");
onready var VvContainer = get_node_or_null("ViewportContainer");

onready var testBTN2 = get_node_or_null("Button");

	if ( testBTN.is_hovered() ):
		if ( Input.is_action_just_pressed('mouse_button') ):
			Input.warp_mouse_position( VvContainer.rect_global_position +  testBTN.rect_global_position )
		
		elif ( Input.is_action_pressed('mouse_button') ):
			testBTN.rect_global_position = VvPort.get_mouse_position();
			

	if ( testBTN2.is_hovered() ):
		if ( Input.is_action_just_pressed('mouse_button') ):
			Input.warp_mouse_position( testBTN2.rect_global_position )
		
		elif ( Input.is_action_pressed('mouse_button') ):
			testBTN2.rect_global_position = get_global_mouse_position();

**Comment by Calinou** [comment]
@jonSP12 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by jonSP12** [comment]
> @jonSP12 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

I was just finishing making it... but its a very basic project

**Comment by jonSP12** [comment]
i had to upload it to google drive
https://drive.google.com/file/d/17OFt_Qdcrnv1ZJm6XphODKay0HZcOBHm/view?usp=sharing

**Comment by jonSP12** [comment]
the only way i found to solvve this problem was to scale down the project resolution instead of the camera

var selectedRes = 0;


	if ( wheel_up ):
		selectedRes -= 1;

	elif ( wheel_down ):
		selectedRes += 1;


	selectedRes = clamp(selectedRes, 0, 3);
	
	match selectedRes:
		0:
			get_viewport().set_size_override(true, Vector2(480, 270));
			#OS.set_window_size(Vector2(480,270  ));
		1:
			get_viewport().set_size_override(true,Vector2(800, 600));
			#OS.set_window_size(Vector2(800,600  ));
		2:
			get_viewport().set_size_override(true,Vector2(1024, 768));
			#OS.set_window_size(Vector2(1024,768  ));
		3:
			get_viewport().set_size_override(true,Vector2(1280, 720));
			#OS.set_window_size(Vector2(1280,720  ));

**Comment by Sauermann** [comment]
In the Godot4 master branch this issue got fixed by #59702.

**Comment by jonSP12** [comment]
> In the Godot4 master branch this issue got fixed by #59702.

iam still unable to use godot4
Iam using polyGons with bones attached to deform the image
When i add a sekeleton to the polygon the image disapears...

![GD4polygon](https://user-images.githubusercontent.com/77213594/161616029-3933532e-920d-4a7a-8cc3-c03f762a0bb2.png)

**Comment by akien-mga** [comment]
Fixed by #59892.
