### ISSUE TITLE
Vulkan: Strange white artifacts on alpha scissor material due to incorrect mipmap generation for transparent textures

### ISSUE THREAD

**Issue by VP-GAMES** [godotengine/godot#60388]
### Godot version

4.0 dev

### System information

Linux Ubuntu 20.04.3 LTS

### Issue description

Some meshes with alpha scissor material, has strange white edges. 

### Steps to reproduce

Open attached project to see the presentation.

### Minimal reproduction project

[Artifacts.zip](https://github.com/godotengine/godot/files/8519899/Artifacts.zip)

**Comment by Calinou** [comment]
I can confirm this on `master` 1d2177938:

https://user-images.githubusercontent.com/180032/164212760-ffd76166-c4c7-4813-aecd-24fb34fe9bf9.mp4

This is due to mipmap generation not being done correctly for transparent textures.

Changing the texture compression mode from **VRAM Compressed** to **Lossless** does not resolve this issue:

![image](https://user-images.githubusercontent.com/180032/164212911-752f714b-aca8-4151-a7e5-bfbab98d3aae.png)

Disabling mipmap generation will, but it will also make the texture grainy at a distance:

![image](https://user-images.githubusercontent.com/180032/164212964-3c8a2c70-3eaf-4c7e-ba5e-e47820a2465b.png)

**Comment by VP-GAMES** [comment]
In 3.4.4 (in GLES3)  i have to set Flags: Transparent to "TRUE" and change Parameters: Depth Draw Mode to "Opaque Pre-Pass" it's enough, it works good
[NoArtifactsGLSE3.zip](https://github.com/godotengine/godot/files/8521254/NoArtifactsGLSE3.zip)
.

**Comment by lyuma** [comment]
Is anyone able to reproduce this with a 4.0 release candidate? I suspect this issue was fixed sometime in the past year

**Comment by Calinou** [comment]
I can still reproduce this on 4.0.rc3 with the MRP (`.godot/` was removed to force a reimport of everything).

### Linear Mipmap

![image](https://user-images.githubusercontent.com/180032/220726763-d754fa31-ac89-4c7f-aff6-b6c3909968f4.png)

### Linear

![image](https://user-images.githubusercontent.com/180032/220726810-53b0c6d3-5306-4c51-add8-1f9010259846.png)
