### ISSUE TITLE
HiDPI Screen option on Low DPI screen will break UI

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#6130]
**Operating system or device - Godot version:**
Windows 8.1, Godot 2.1 Stable

**Issue description** (what happened, and what was expected):
I learned (tested) new functions and found HiDPI screens option. Turned it on, restart the engine and UI is now too big for my FHD screen (insane big). And godot not allowing me to resize the window big enough to get to the engine settings window. Even when I resize screen to a maximum width I see a half of UI.

Solved by resizing the window over and over again, once I got settings button in the top right corner somehow and got in the engine settings menu. But it is still a great problem.

**Steps to reproduce:**
In the description.

**Solution:**
- Make settings button always in the top right corner.
- Add some cancel button when HiDPI is setted up for the first time.
- Lock to auto/low DPI , when no 3K-4K displays found.

**Link to minimal example project** (optional but very welcome):

**Comment by ghtalpo** [comment]
I have a similiar problem.

My setup is MacBook Pro(Retina) with a FullHD external monitor.

When I start godot(v2.1), it appears on external monitor first.

It seems ok for project manager, but when I open one of demo projects, only quater screen appears on the external monitor.(it's hard to explain, but you can see it through)

When I move the window into MacBook's internal LCD, it looks fine.

This happens no matter what editor's Hidpi mode setting is.(Auto,LoDPI,HiDPI)

**Comment by deasek** [comment]
Same here.

**Comment by ghtalpo** [comment]
It seems like same as #5688. I can fix my situation with them, but don't know about Windows environment. There may be similar option in properties. You may try poking around.

**Comment by jeremyherbert** [comment]
I have this same issue on OSX high sierra, high dpi scaling is wrong on my external monitor but works fine on the macbook internal monitor which is high dpi. high dpi is set to "auto" in the editor settings settings.

Window on macbook display: https://www.dropbox.com/s/srcvdxmeacwnvvp/macbook_display.png?dl=0
Window dragged to external display (1920x1200): https://www.dropbox.com/s/3ugqq03ccs5svst/external_display.png?dl=0

**Comment by bruvzg** [comment]
Should be fixed by #40201 and #40084

**Comment by Calinou** [comment]
@bruvzg I think this can still occur if the user sets the editor scale manually to a setting that's too large for their monitor.
