### ISSUE TITLE
Transparent material is broken.

### ISSUE THREAD

**Issue by Jay7c** [godotengine/godot#61359]
### Godot version

3.5 rc1-rc2

### System information

GNU/Linux Pop Os 20.04

GPU: Nvidia GeForce GTX 1070ti.

### Issue description

- Transparent materials look bright and alpha textures don't display correctly.
![rc-bug](https://user-images.githubusercontent.com/75779389/170032101-49b77f9b-3b1c-4387-b300-72a7a75e3238.jpg)

### Steps to reproduce

- Create transparent material and press play button.

**Comment by akien-mga** [comment]
Probably caused by #54585, CC @Kinwailo @clayjohn.

**Comment by clayjohn** [comment]
I was able to reproduce the issue in #61363 and can confirm that it was caused by #54585. The issue there is transparent objects are making the viewport transparent which is causing colors to bleed through. 

I am not sure that this Issue is the same as #61363 and without an MRP I cannot confirm that the same fix will be applicable for both.

**Comment by clayjohn** [comment]
@Jay7c Could you test your scene with https://github.com/godotengine/godot/pull/61375 to see if it fixes the issue you have here? I confirmed that it fixes #61363 which is likely the same root issue that you are having.

**Comment by Jay7c** [comment]
> @Jay7c Could you test your scene with #61375 to see if it fixes the issue you have here? I confirmed that it fixes #61363 which is likely the same root issue that you are having.
> 
> Download here: https://github.com/godotengine/godot/suites/6641741035/artifacts/250735397

The materials with alpha scissor are still broken.
![ASB](https://user-images.githubusercontent.com/75779389/170128938-8dc6f992-16e5-4aee-96c5-f82b5e15d3c3.jpg)

**Comment by akien-mga** [comment]
Fixed by #61382.

**Comment by Jay7c** [comment]
> Fixed by #61382.

The problem persists, the bloom is causing artifacts. Do I open another issue?
![bp](https://user-images.githubusercontent.com/75779389/170146820-12ebe19d-972c-4cfd-ac70-4266d8aa4313.jpg)
