### ISSUE TITLE
Editor never releases focus when "Save on focus loss" is active (DisplayServer regression)

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#61875]
### Godot version

b36447f6f09ac608bfa76dda6a50ac92c7040077

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

When "Save on focus loss" is active, editor instantly grabs focus through the save popup when switching to another application.

https://user-images.githubusercontent.com/347965/172998908-024a6176-3656-48dc-8a76-890be91cb8a5.mp4

### Steps to reproduce

See above

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by jgillich** [comment]
@Calinou I can not

**Comment by Rindbee** [comment]
It should be the popup of the save progress bar that made the editor regain focus.

**Comment by akien-mga** [comment]
I don't reproduce the issue anymore on 4.0 RC 3, it might have been fixed by #72439? @bruvzg

On the other hand each time there's a focus loss, these errors are printed:
```
ERROR: Parent node is busy setting up children, `add_child()` failed. Consider using `add_child.call_deferred(child)` instead.
   at: add_child (scene/main/node.cpp:1136)
ERROR: Condition "!is_inside_tree()" is true.
   at: popup_centered (scene/main/window.cpp:1456)
```

I wonder if #73365 would fix that one too.

**Comment by Aeranuth** [comment]
Any progress on this bug? Still happening in 4.2. Always froze editor if you create a new scene and lose focus. Once it pops save window and you save the new scene, you cannot perform any action anymore.

**Comment by Calinou** [comment]
> Still happening in 4.2. it always froze the editor if you create a new scene and lose focus. Once it pops the save window and you save the new scene, you cannot perform any action anymore.

This should be fixable by making **Save on Focus Loss** ineffective if at least one of the currently open scenes hasn't been saved yet.
