### ISSUE TITLE
Function set_input_as_handled does not work

### ISSUE THREAD

**Issue by przemekd** [godotengine/godot#6194]
**Operating system or device - Godot version:** ArchLinux, Godot v2.1

**Issue description** (what happened, and what was expected): When I want to use set_input_as_handled function to mark input as handled and prevent execution of other input handlers nothing changes, and all input handlers are executed.

**Steps to reproduce:** Create project with two Sprites and Area2d and ColisionShape2d to handle mouse input. Place first sprite over second one. Despite of using set_input_as_handled function to handle the mouse input only one time, two functions are executed 

**Link to minimal example project** (optional but very welcome): https://github.com/przemekd/godot_input_handle_bug_example

**Comment by eska014** [comment]
I don't think pickable CollisionObject2D nodes are intended to participate in InputEvent propagation

**Comment by przemekd** [comment]
So, how may I solve the problem of moving sprites with mouse without picking up two or more overlapping sprites at the same time? Shouldn't it be possible?

**Comment by bojidar-bg** [comment]
Uhm. Pretty bump, this is getting overly stale. Is there a real issue to be fixed, or is it just some misunderstanding on the part of the OP?

**Comment by reduz** [comment]
I think that behaviour is intended.. you can use the space2d to query for
all things on a given point easily

**Comment by volzhs** [comment]
by what document says, http://docs.godotengine.org/en/stable/learning/features/inputs/inputevent.html#how-does-it-work
`_input_event` should not be called after calling `get_tree().set_input_as_handled()` in `_input`.
but it still calls `_input_event` after `_input`

**Comment by eon-s** [comment]
If you add a Control with `_input_event` and set the input as handled there, those are not passed to CollisionObjects, but once the event reaches the CollisionObjects, all can receive the event.

I don't know if will be possible (in a generic way) to decide which object receives the event first in case of overlapping, because processing order can be different than other things like sprites z order, this may indeed need space queries to solve things as the specific game requires.

**Comment by plucian** [comment]
the Control with _input_event does not work on Android, but it does work on Windows. So a solution would be to use Control as the sprite container, but again, doen't work everywhere.

how would solve the issue the use of the spate2d ? not seeing it..

**Comment by akien-mga** [comment]
Is this fixed by #12149?

**Comment by cwwhitfield** [comment]
I'll confirm that this problem still exists. Or else I'm misunderstanding expected behavior based on current documentation.

In my case, I have some ui control panels that I expect to consume specific mouse events in _gui_input() and stop them from propagating through to 3d node's _input(). I do have mouse_filter = Stop in these ui control nodes.

Maybe this is different than OP because it is 2d AND 3d nodes? However, in my naive opinion, set_input_as_handled() should stop any event in it's tracks. Why would it not? (It's easily possible that there is a reason and I have a very misinformed opinion.)

**Comment by cwwhitfield** [comment]
Oh my...
I'm trying to build a workaround for this, and the best I can think of is SomeSinglton.suppress_mouse_event = true at every UI script that takes a mouse input, and then use/reset that suppression flag in my 3d nodes to specifically ignore mouse events intended for control ui.

This seems very kludgy and against the spirit of event propagation as I understand it in the docs. Surely I'm not the first person to have UI nodes and 3d nodes responsive to mouse. Given the lack of activity on this thread...what am I missing that everyone else seems to know...?

**Comment by vnen** [comment]
@cwwhitfield `_input()` happens *before* `_gui_input()`. So if you mark as handled in any `_gui_input()`, all the `_input()` functions have already been called. For this case you can use `_unhandled_input()` in the 3D nodes (or `_input_event()` if they are collision objects). Check http://docs.godotengine.org/en/3.0/tutorials/inputs/inputevent.html#how-does-it-work for more information.

**Comment by cwwhitfield** [comment]
Ah thanks! I read but my comprehension was terrible. For some reason I was sure I read that gui was before everything. I'll use _unhandled_input instead of _input.

**Comment by dbenoy** [comment]
> Create project with two Sprites and Area2d and ColisionShape2d to handle mouse input. Place first sprite over second one. Despite of using set_input_as_handled function to handle the mouse input only one time, two functions are executed

I think this can be desirable. Some Area2Ds may want to know if they're being clicked even if the input was addressed by the object in front. It seems that you can use `get_tree().set_input_as_handled()` and `get_tree().is_input_handled()` during these signals.

This will give you exactly the effect you're looking for, and you can even do 'if I get clicked but something else handled it, maybe I do some other thing instead'

However, from my testing, it seems that the order in which the collision objects get signals is not documented, and may not match the developer's expectations.

I've opened #24259 with my suggestion.

**Comment by mg979** [comment]
Would it be possible for input events to have a `bool handled` property, that is set to `true` whenever an input is handled by some node, even if it propagates further, so that any other node can know if it has been handled already or not? Or/and a property with a list of nodes that already handled the event, so that nodes that handle the event add themselves to that list?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/24259 per the above comment.
