### ISSUE TITLE
Vulkan Mobile: Renderer not displaying 3D since 4.0.alpha10

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot#62343]
### Godot version

4.0 alpha 10

### System information

MacOS 12.4, Apple Silicon M1

### Issue description

Godot 4 alpha 10 fails to display any 3D object in the view port if the Vulkan Mobile renderer is selected.
 ### Alpha 10 <img width="1395" alt="Screenshot 2022-06-23 at 11 15 52" src="https://user-images.githubusercontent.com/4403212/175278377-f6bf46e3-251f-4764-a918-bde6b6247485.png">

### Alpha 9 <img width="1396" alt="Screenshot 2022-06-23 at 11 14 38" src="https://user-images.githubusercontent.com/4403212/175278455-e66b73a1-6dbe-4d07-89a7-a00c96944acf.png">

Alpha 10 interface is also extremely laggy and stalls with a beachball until force quit. If I create a project using the Vulkan Desktop renderer the 3D view port displays correctly.

```drivers/vulkan/vulkan_context.cpp:159 -  - Message Id Number: 0 | Message Id Name: 
  	VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
  program_source:391:16: warning: unused variable 'sun_scatter'
          float4 sun_scatter = float4(0.0);
                 ^
  program_source:392:15: warning: unused variable 'sun_total'
          float sun_total = 0.0;
                ^
  program_source:1096:11: warning: unused variable 'specular_amount'
      float specular_amount = spot_lights.data[idx].specular_amount;
            ^
  program_source:1171:39: error: no viable overloaded '='
      scene_data.projection_matrix_view = scene_data_block.data.projection_matrix_view;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  program_source:10:8: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'metal::float4x4 const constant[2]' to 'spvUnsafeArray<metal::matrix<float, 4, 4, void>, 2>' for 1st argument
  struct spvUnsafeArray
         ^
  program_source:10:8: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'metal::float4x4 const constant[2]' to 'device spvUnsafeArray<metal::matrix<float, 4, 4, void>, 2> &&' for 1st argument
  struct spvUnsafeArray
         ^
```

thousands of errors as above using the mobile renderer

### Steps to reproduce

create a project in Godot 4 alpha 10 and select the mobile renderer

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8966442/test.zip)

**Comment by Calinou** [comment]
> Alpha 10 interface is also extremely laggy

This is caused by the large amount of error messages being printed to the editor's Output panel.

**Comment by akien-mga** [comment]
Duplicate of #61817? If so it should be fixed in `master`.

**Comment by clayjohn** [comment]
Yeah, Will need confirmation from someone on a Mac, but it indeed looks exactly the same as #61817 (same shader logs as what bruvzg posted. If so, should be fixed by https://github.com/godotengine/godot/pull/62305

**Comment by lostminds** [comment]
I've been using the mobile renderer for a 3d project on macOS on 4.0.beta2 to beta8 builds and have not seen this problem. So I think this can be closed unless @ViktorEvil is still experiencing these problems?

**Comment by akien-mga** [comment]
Thanks, let's close. Please comment if you can still reproduce this issue in the latest beta.

**Comment by ViktorEvil** [comment]
Just tried mobile renderer on beta8 and it’s fine
