### ISSUE TITLE
VR XR PanoramaSkyMaterial rendering problem

### ISSUE THREAD

**Issue by python273** [godotengine/godot#62738]
### Godot version

4.0.dev (5f386fecf) / I think all 4 alphas too

### System information

Windows 10, Vulkan

### Issue description

If the sky takes most of the view, it looks normal. But if there's "border" around it / objects upclose, it's quite hard to focus on it

First screenshot - looks normal. Second - hard to focus on it.

[Discussed here on Discord server](https://discord.com/channels/212250894228652034/418572953912082432/993169696956371044)
> Lyuma:
> [...] It's true in the first screenshot too but the plane of focus is slightly further than the wall, while in the second it's closer.

so maybe it's related to "distance" the sky is rendered, and it breaks when there are objects "further" from the sky

![Screenshot (16)](https://user-images.githubusercontent.com/3097956/177363575-05592247-7c56-4201-ae56-71aa1ca15037.png)
![Screenshot (17)](https://user-images.githubusercontent.com/3097956/177363218-0b12991b-8b95-4f5a-bbf5-c1d78bb50038.png)

### Steps to reproduce

1. Create Environment with Panorama sky (other skys might have the same problem though)
2. Add a wall with a window
3. Get a few meters away from window

### Minimal reproduction project

[helloworld4-1_-_Copy.zip](https://github.com/godotengine/godot/files/9047647/helloworld4-1_-_Copy.zip) (21MB because of panorama texture)

**Comment by Firepal** [comment]
Haven't checked, but this sounds like a case of the sky being offset for stereo 3D when it shouldn't be. Plane of focus should be "infinite"

**Comment by Calinou** [comment]
cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
@python273 can you test #62948 and see if this resolves your issue? @Firepal is likely correct and this is due to the offset of the eyes being mixed in with the projection matrix. The way I fixed it for now is to use the unaltered projection matrices.

Let's first see if we're indeed on the right track here or if there is a different problem. If this fixes it I might see if I can simplify the solution because it does introduce a fair bit of noise.

**Comment by python273** [comment]
@BastiaanOlij hmm, still have the problem. Made this right-to-left eye transition animation, 50% opacity frame shows approximately what I see, there's this diagonal offset. Though if the sky takes most of the view, I can focus on it

![](https://user-images.githubusercontent.com/3097956/178555882-f193add6-8783-4f4b-9cc1-3a005524ab9c.gif)

**Comment by BastiaanOlij** [comment]
Hmmm, that does look wrong... I'm not sure yet whats going on.

Is this an issue on Godot 3 as well? The only difference between 3 and 4 as far as sky is concerned is the eye offset being embedded in the projection matrix. If it works correctly in Godot 3 we'll know if we've introduced another issue.

**Comment by python273** [comment]
Checked similar scene in Godot 3.4.4 with Godot OpenXR 1.3.0. Looks completely normal (only looks darker for some reason)

It seems like in Godot 4 the sky parallax is not aligned with eyes. The green cube and sky parallax directions are different

<details>
<summary>Click for animations</summary>

Animation with left and right eyes aligned on these 2 columns

![](https://user-images.githubusercontent.com/3097956/178898452-909c1b72-b028-43fe-a9bd-52844c5f4703.gif)

![](https://user-images.githubusercontent.com/3097956/178901247-d3f047ad-4342-4af5-91c5-5c33bf82adb1.gif)

![](https://user-images.githubusercontent.com/3097956/178901245-025897ae-2d42-474e-8bca-b6811af18218.gif)

![](https://user-images.githubusercontent.com/3097956/178901233-e1e45593-76aa-476e-ab48-c29aa4365df1.gif)

</details>

**Comment by python273** [comment]
@Calinou can this be added to 4.0 milestone?

**Comment by BastiaanOlij** [comment]
This may have some effect on this bug though me and Malcolm are still chasing another issue we think is involved here:
https://github.com/godotengine/godot/pull/69636

**Comment by BastiaanOlij** [comment]
Turns out that this issue is far more noticable on a quest then on an index, this PR should fix it: #70253
