### ISSUE TITLE
Godot 4: Autocompletion for relative nodes ($ selector) doesn't work

### ISSUE THREAD

**Issue by illBeRoy** [godotengine/godot#62797]
### Godot version

4.0.alpha11

### System information

MBP M1, MacOS Monterey

### Issue description

Autocomplete doesn't work for relative nodes. When using the dollar sign selector (`$MyNode`), the resolved type of any node is always `Node`, which makes type-specific variables and methods not show up in autocomplete.

Example: Take this `Sprite2D` node (called `Sprite`):
![image](https://user-images.githubusercontent.com/6681893/177647219-56069a46-8331-40e1-8b8f-6499ce2a0148.png)

The variable `flip_h` is not shown in the autocomplete dropdown (but does work in runtime).

If we explicitly create a `Sprite2D` variable, it works:
![image](https://user-images.githubusercontent.com/6681893/177647428-f53abd04-ea92-45f7-adb3-6d22c6ec1de0.png)

But if we assign a node to this variable, it goes back to not working:
![image](https://user-images.githubusercontent.com/6681893/177647509-56caf827-6655-4c46-94f5-ec58e370d49f.png)

Therefore, my conclusion is:
1. Relative nodes are not assigned the correct type
2. In general, the types themselves do work (if used explicitly)
3. But for some reason, selecting a relative node **overrides** the explicit type and reverts the variable type to `Node`

### Steps to reproduce

1. Create any scene with two nodes (parent and child)
2. Create a script for the parent
3. Try to access the child via dollar sign selector
4. Try to access a well known variable \ method of the child from the parent's script
5. Autocomplete will not show the desired variable \ method (but they will work in runtime)

**Comment by KoBeWi** [comment]
Looks similar to #42005 (if it's really a problem with resolved type)
Still valid in 95ddc8c

**Comment by cdemirer** [comment]
I think 2 and 3 have the same reason as https://github.com/godotengine/godot/issues/42005#issuecomment-717604174 (https://github.com/godotengine/godot/issues/42005#issuecomment-1177223873).
1 seems like a different problem.

**Comment by illBeRoy** [comment]
If this helps, when using `PackedScene.instantiate()`, autocompletion works perfectly for the root node (including custom method added by script):
<img width="401" alt="image" src="https://user-images.githubusercontent.com/6681893/178119576-21eedfad-76ad-4e47-a096-998983f3edf6.png">

**Comment by Warlaan** [comment]
Just confirmed the issue in v4.0.beta2.official [f8745f2f7].

In my case I tried to access an AnimationPlayer, and in that case the autocompletion neither works for the methods of the AnimationPlayer nor for the animation names. The former issue could be worked around with type hints, but the latter can't.

**Comment by midiphony** [comment]
I think I have the issue too on beta4 (build from November 1st, [got here](https://downloads.tuxfamily.org/godotengine/4.0/beta4/))

![image](https://user-images.githubusercontent.com/46935704/199850595-ecca6ce1-5b01-4e9a-8eea-e13ee36417ca.png)
![image](https://user-images.githubusercontent.com/46935704/199850605-f4774419-1ca6-42e4-83ff-80e56bc78d87.png)

**Comment by samangol** [comment]
![Screenshot from 2022-10-19 12-50-00](https://user-images.githubusercontent.com/59032924/200668223-4f46b566-0ef6-45f9-943b-48b127d2264e.png)
also it doesnt work for enums

**Comment by samangol** [comment]
![Screenshot from 2022-11-08 23-55-04](https://user-images.githubusercontent.com/59032924/200668382-8392d773-3745-4f4e-b3b1-b03221a21e6d.png)
also enums are not working

**Comment by akien-mga** [comment]
CC @Chaosus

**Comment by Warlaan** [comment]
For me it doesn't even autocomplete the node names after typing in the $. The reports so far make it sound like it was only the type of the nodes that was wrong.

**Comment by Warlaan** [comment]
I know, and I am fairly certain that I had the correct scene open, but when I retested it right now the autocompletion for node paths did work. 
I'll look into it some more. My guess is that there is some workflow other than not having the scene open that breaks it.

In any case I can confirm that the editor's autocompletion is able to detect node paths, it's indeed just the type that is not recognized.

**Comment by Haydoggo** [comment]
Looks like this issue was just fixed by https://github.com/godotengine/godot/pull/68663

**Comment by KoBeWi** [comment]
It's not fully fixed. Autocompletion does not work on $nodepaths directly.

**Comment by AndreiSchapov** [comment]
Yup. Not working for $  nodes in Beta 5.

**Comment by midiphony** [comment]
I did some debugging (I am *very* inexperienced with Godot codebase though), on latest master (f3e6750)

This is my test line (current scene contains the corresponding screen and the "VisibleOnScreenNotifier3D" node exists) :
![image](https://user-images.githubusercontent.com/46935704/205753523-c326bf19-8bbb-4240-bef3-27e1c0e28657.png)

In gdscript_editor.cpp, in GDScriptLanguage::complete_code method :

The native type is not found when trying to _get_subscript_type() (not sure what a subscript means here) :
![image](https://user-images.githubusercontent.com/46935704/205751024-d5253c9a-a27f-47e7-81d9-8427cf6e57ca.png)

After the call to _guess_expression_type(), the found type is just a native "Node" type :
![image](https://user-images.githubusercontent.com/46935704/205751256-dd949e59-5f48-46b5-bd3c-168a38c9393e.png)

I'm still overwhelmed by the editor/parser code, after some quick edit of the above methods, I can get the result below :
![image](https://user-images.githubusercontent.com/46935704/205754645-a45abb70-2cfc-421e-b329-0bd570109e60.png)

@Chaosus is it helpful anyhow ? 😅

**Comment by Chaosus** [comment]
Ah, I just missed the notification, I can take a look to fix it now.

**Comment by AndreiSchapov** [comment]
Resurfaced for me in 4.1.1, while I was doing the "Creeps" tutorial.
$AnimatedSprite2D does not autocomplete the "play" method, see attached screenshot.
![image](https://github.com/godotengine/godot/assets/68226833/16014865-fda0-416f-98b8-c0748d1302d6)

**Comment by chiptuner8bit** [comment]
This bug still occurs in v.4.2.1. Autocompletion works works **only** when using `as` keyword.
![GodotAutocompetionNoAs](https://github.com/godotengine/godot/assets/53517526/ddbf5949-40ab-41f4-9a1e-b4f9d64893af)
![GodotAutocompetionWithAs](https://github.com/godotengine/godot/assets/53517526/70f78838-495d-424c-9905-0ca6a908c819)

**Comment by KoBeWi** [comment]
It's already tracked in #86513 and related issues. It's unrelated to the issue here.

**Comment by Haydoggo** [comment]
I don't think it is the same issue; #86513 occurs in version 4.2.0, but this bug does not. This bug resurfacing since 4.2.0 is a regression. I've just done a bisect and found the regression was introduced by #79386.
