### ISSUE TITLE
Zooming with Camera2d cause sprites to disappear (both in the editor and in game)

### ISSUE THREAD

**Issue by de5car7es** [godotengine/godot#63047]
### Godot version

3.3.2.stable.mono.official

### System information

Windows 10, GLES3

### Issue description

My character is built from polygons and a skeleton.
Animated with AnimationPlayer and using AnimationTree.

When zooming with the camera, both inside the game or inside the Godot Editor, certain sprites disappears.
Moving the camera around makes them come back and disappear again.

Here is a video showing the bug.

https://user-images.githubusercontent.com/28839265/179302067-e94a41cb-aa9d-4eb7-804c-a2636e16a2d2.mp4

This issue doesnt replicate on all animations states, only on some.
Small project with this bug reproduced is attached.

I raised this issue on godotengine.org Q&A and found someone else who stumble upon this behavior
https://godotengine.org/qa/135140/camera2d-zooming-cause-sprites-polygons-to-disappear

### Steps to reproduce

- Open the attached project in Godot.
- An animated character will appear with no issues when zooming.
- Open the AnimationTree and move to the Sad2 animation
- Zoom in\out inside the editor to the face area, you can see sprites disappear. 
- When zoomed in and sprites disappear, try to move around the camera with the mouse. 
Some sprites will reappear.
- This is not an editor bug. Same bug appear inside the game.

### Minimal reproduction project

[SpritesDisappearingBug.zip](https://github.com/godotengine/godot/files/9123657/SpritesDisappearingBug.zip)

**Comment by Calinou** [comment]
This is likely caused by the nodes' visibility rects not being adjusted when skinned in a skeleton. The engine thinks the nodes are located outside the view frustum and are culled too early.

**Comment by lawnjelly** [comment]
I can confirm this happens in the latest 3.5. Last work in this area was #40869 by @clayjohn .

**Comment by de5car7es** [comment]
Any workaround to use in the meantime ?
This is basically a core feature...

**Comment by kleonc** [comment]
> Unfortunately, there is no way to set a custom AABB for CanvasItems.

I think you can do it by directly using the `VisualServer` (in `3.x`), like:
```gdscript
var ci: CanvasItem = ...
var custom_rect: Rect2 = ...

var ci_rid: RID = ci.get_canvas_item()
var use_custom_rect: bool = true
VisualServer.canvas_item_set_custom_rect(ci_rid, use_custom_rect, custom_rect)
```

**Comment by akien-mga** [comment]
Fixed by #63071.

**Comment by de5car7es** [comment]
Is this fixed in Godot 3.5?

**Comment by akien-mga** [comment]
No, it will be fixed in 3.6, and possibly in 3.5.1 if the fix doesn't introduce regressions and gets cherrypicked.

**Comment by Untailo** [comment]
Has the fix been implemented in 3.5.1 RC1? It says so in the changelogs but I still have the problem with this version.

**Comment by Untailo** [comment]
Has the https://github.com/godotengine/godot/pull/63071 fix been implemented in 3.5.1 RC1? It says so in the changelogs but I still have the problem with this version.

**Comment by hothex** [comment]
I face similar issues with v3.5.1.stable.official [6fed1ffa3]
In Rest Pose i can zoom and the polygons are still visualized./
Outside of the rest pose (i.e. while animating) the problem occurs also in game:

https://user-images.githubusercontent.com/25593722/229136269-2b4eaa46-b00a-49e0-8fc8-2fa3a5896e6c.mp4

**Comment by lawnjelly** [comment]
Please post MRP so we can investigate. :+1:

**Comment by hothex** [comment]
Here is a minimal reproduction project created with v3.5.1.stable.official [6fed1ffa3]:
[MRP_Polygon2D_SkeleAnimation.zip](https://github.com/godotengine/godot/files/11125358/MRP_Polygon2D_SkeleAnimation.zip)

Running the game with F5 the animation close to the edge of the viewport is behaving wierd. That is the green circle will disappear. While at the same scene the second instance of skele animation node is behaving as expected. It rotates and the head is visible:

https://user-images.githubusercontent.com/25593722/229215688-6765b496-4905-492a-b9f4-f8a3751d9283.mp4


The Rest Pose Zoom Observation in editor is also reproducable:

https://user-images.githubusercontent.com/25593722/229214951-3059950d-837b-4a66-b9e8-7c923ccb849b.mp4

**Comment by lawnjelly** [comment]
@hothex I'm just debugging now. I noticed a similar-ish problem just prior to yours in a related (in progress) PR and it might be the same bug.

#63071 appears to be working correctly, that is, it is recalculating the bounding rect for the polys from the bones on the fly. The problem as far as I can see so far is that there is another bug, at the moment I'm suspecting the calculation for the bound may be incorrect (this was added 3 years ago). Will output some numbers and see if this is the problem.

**Comment by lawnjelly** [comment]
@hothex Your issue is probably a duplicate of #74656 which is occurring in 4.x (I'm not so familiar with 4.x). I've worked out why the bound calculation is failing and I'm planning to adapt the canonical implementation in the batching skinning that I wrote a couple of years ago, this should fix it.

It could have probably been better as a separate issue as the bug is subtly difference from the zooming bug first described here, but we've already discussed so much it would be tricky to transplant.

The issue stems as far as I can see from the bound calculation simply applying the bone transform to the vertex positions, but not taking account of the polygon transform / offsets. It probably currently only works in a very limited set of circumstances (such as no offset) but not in the wild where there can be lots of offsets.

**Comment by hothex** [comment]
@lawnjelly Thank you for your dedication! Please let me know if I can help with anything for example with providing an "into the wild" sample project. I have one with many bones and polygons cut out of one png. I did not have to scale them but I needed to move them around a lot. The first video i posted shows it. I could add some exagerated scaling to the heads or arms.

**Comment by akien-mga** [comment]
Fixed by #75612.

**Comment by hothex** [comment]
@lawnjelly Checked the behaviour with both the MRP and the more complex example with v3.6.beta2.official [68c507f59]. Both are fine from my point of observation:

Thank you for the fix!


https://github.com/godotengine/godot/assets/25593722/eae531fd-d94a-44cb-989a-8e363feed40f


https://github.com/godotengine/godot/assets/25593722/5b17b23f-6a2a-4632-9b97-af32db48919e

**Comment by anarakinson** [comment]
Hello

I encountered strange behavior of a point light node.
When I zoom out on the camera, the light stops illuminating the back layers of the background. The light flickers and the front layers are illuminated as usual. I don't understand what's wrong.
If the zoom value is greater than 0.5, everything works fine. 
The problem occurs at lower values, 0.4 and less.
I tried changing the light and camera, but nothing helps.

video example of what is happening at the link
https://www.youtube.com/watch?v=nnoQDbWzock
