### ISSUE TITLE
Vulkan: LightmapGI exhibits light bleeding through occluded areas and face edges

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#63437]
### Godot version

4.0 Alpha 12

### System information

Windows 10, GTX1080, i7 6700

### Issue description

Godot 4 LightmapGI exhibits light bleeding through completely occluded spaces and on the edges of faces.
The latter has the appearance of insufficient padding or texel resolution but seems to happen regardless of resolution.

### Edge Leaks:
These seem to happen regardless of what resolution the meshes are brought in as. Even in this small scene, an atlas resolution of 2048x2048 wasn't enough to resolve. Both shots from Godot 4.
![LightmapLeaks_Ultra005Texels](https://user-images.githubusercontent.com/70243134/180784295-173813ae-0704-4280-9539-52dfef8e1963.JPG)
![LightmapLeaks_Ultra001Texels](https://user-images.githubusercontent.com/70243134/180784318-52c73484-4825-48b1-9a0f-88deb127a89f.JPG)

### Edge Leaks, Godot 3 vs 4:
Godot 3's mapper doesn't really exhibit the same leak issues, so this seems to be a regression.
![LightmapBleed01_Godot3](https://user-images.githubusercontent.com/70243134/180785249-02ee04ae-af76-49cd-82c6-ee2e135d46f4.JPG)
![LightmapBleed01_Godot4](https://user-images.githubusercontent.com/70243134/180785314-5df32a7b-b6f7-43bd-99cc-8ec6da21fe68.JPG)

Occluded Areas, Godot 3 vs 4:
Completely occluded areas also seem to struggle. In this area where the object intersects with the plane, light bleeds through even with Godot 4's mapper set to Ultra.
![LightmapBleed02_Godot3](https://user-images.githubusercontent.com/70243134/180785542-04beb674-4ee2-454d-b04c-397acdf3ffc2.JPG)
![LightmapBleed02_Godot4](https://user-images.githubusercontent.com/70243134/180785560-528505f9-3a65-4e04-977a-a931cdcefbad.JPG)

### Steps to reproduce

MRP provided. Settings in both projects are matched.

### Minimal reproduction project

Godot 3:
[LightmapQualityExampleG3.zip](https://github.com/godotengine/godot/files/9181454/LightmapQualityExampleG3.zip)

Godot 4:
[LightmapQualityExampleG4.zip](https://github.com/godotengine/godot/files/9181458/LightmapQualityExampleG4.zip)

**Comment by Calinou** [comment]
I can confirm this on 5fec0d232 (Linux, NVIDIA 510.68.02). I could notice increased lightmap bleeding when [updating the global illumination demo to readd lightmaps](https://github.com/godotengine/godot-demo-projects/pull/759), but haven't found any combination of settings that resolves it.

**Comment by sietse85** [comment]
![image](https://github.com/godotengine/godot/assets/10598991/a4ea5ff0-9d0e-44b0-b1fc-c6f6937111f1)
Is this the same issue? Godot 4.1 Mono on Linux

**Comment by Calinou** [comment]
> Is this the same issue? Godot 4.1 Mono on Linux

This appears to be just vertex normals lacking detail due to the mesh not being subdivided enough, so this is an unrelated issue that can't be fixed by Godot.

**Comment by jcostello** [comment]
#81872 seems to fix this issue. I would like someone else to verify @WickedInsignia

**Comment by lander-vr** [comment]
It seems like I'm still experiencing this in 4.2.1 and #81872 does not seem like a solution to this issue. Pixels that should be completely occluded still receive light, which ends up showing up after denoising. This is also discussed in #75440

Modular environment, using 1 bounce:
With denoising:
![image](https://github.com/godotengine/godot/assets/31851431/8625b322-0ec0-4835-aacb-98f0e9661941)

Without denoising: (Ignore the weird pattern that shows up in the bounced light, I'm currently trying to investigate when/why this happens, but it is not related to this issue)
![image](https://github.com/godotengine/godot/assets/31851431/1c7f728a-ec6b-4877-bc86-885100f665d2)

Inside a wall section:
![image](https://github.com/godotengine/godot/assets/31851431/6bb8aa2e-5225-40fc-babd-3f1ea5598c88)

Inside a different wall section:
![image](https://github.com/godotengine/godot/assets/31851431/100c6b3f-1140-487f-b948-f05275ca5f53)

Whether geometry is completely intersecting or just overlapping (which is the case in my environment) doesn't seem to make any difference. These screenshots use medium quality, but with quality set to ultra the same issue persists with the same severity.

**Comment by Calinou** [comment]
@lander-vr Please open a new issue with a minimal reproduction project attached.
