### ISSUE TITLE
Unpausing a scene causes a PinJoint2D to disconnect

### ISSUE THREAD

**Issue by danboo** [godotengine/godot#63814]
### Godot version

v4.0.alpha.custom_build [de53e91b8]

### System information

Windows 10

### Issue description

I have a scene that contains a `PinJoint2D`, allowing a `RigidDynamicBody2D` to rotate around a `StaticBody2d`. When I pause the scene and then enable it later (see code below), the `RigidDynamicBody2D` is no longer connected to the `StaticBody2d`, and just falls away.

My expectation is that the `RigidDynamicBody2D` will remain pinned to the `StaticBody2d` and resume rotating.

### Steps to reproduce

To reproduce the issue, play the attached project. Observe that the lever initially rotates around the pin joint for two seconds, then pauses. After two more seconds, the scene is unpaused, and instead of resuming rotation, the lever just falls away from the joint.

Scene tree layout:

![image](https://user-images.githubusercontent.com/82860/182322185-95b35923-9f63-4a05-8c82-17e5ffd8f2f6.png)

Attached script:

```gdscript
extends Node2D

func _ready():
	await get_tree().create_timer(2.0).timeout
	process_mode = Node.PROCESS_MODE_DISABLED
	await get_tree().create_timer(2.0).timeout
	process_mode = Node.PROCESS_MODE_INHERIT
```

### Minimal reproduction project

[Unpaused_Joint2d_Failure.zip](https://github.com/godotengine/godot/files/9240127/Unpaused_Joint2d_Failure.zip)

**Comment by rburing** [comment]
Apparently this happens only when the `RigidDynamicBody2D`'s `disable_mode` is set to the default `DISABLE_MODE_REMOVE`; a workaround is to set the `disable_mode` to `DISABLE_MODE_MAKE_STATIC`.

**Comment by danboo** [comment]
The suggested workaround does work for my particular case, but I can easily imagine other cases where `DISABLE_MODE_REMOVE` is preferred along with restoring the joint when the simulation is resumed. Thanks for bringing the `disable_mode` to my attention.

Perhaps it is arguable if this is actually a bug?  I could see it argued either way.

**Comment by rburing** [comment]
I think it should be classified as a bug. Actually I'm pretty sure I already fixed this once before, but I will have a look again.

**Comment by rburing** [comment]
What I looked at before was exiting and entering the scene tree; this is different. Anyway, I found the reason for the bug.

When pausing with `DISABLE_MODE_REMOVE`, `CollisionObject2D::_apply_disabled` changes the object's space to `RID()`:

https://github.com/godotengine/godot/blob/cc35a8723c4cf07bc26032f4f21d6a93f9997d20/scene/2d/collision_object_2d.cpp#L213-L223

This is great, except that changing the space also clears the constraints in the previous space:

https://github.com/godotengine/godot/blob/cc35a8723c4cf07bc26032f4f21d6a93f9997d20/servers/physics_2d/godot_physics_server_2d.cpp#L525-L540

When unpausing, `CollisionObject2D::_apply_enabled` will set the space back, but the constraints will have been cleared.

Currently, constraints are added only when the `GodotJoint2D` is constructed in the physics server, and this is done by the `Joint2D` node e.g. when the `Joint2D` node itself or one of the bodies enters the scene tree, or when `node_a` or `node_b` are set.

I'm not sure how the issue should be fixed.

**Comment by iRadEntertainment** [comment]
Bump up, this is still happening in Godot 4.7, same issue with 3D bodies and joints.

**Comment by Schnorg** [comment]
Related to #107542
