### ISSUE TITLE
Adding a doc comment to an already exported variable is not displayed until the project is reloaded

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#63997]
### Godot version

v4.0.alpha.custom_build [c81ef5150]

### System information

Windows 11

### Issue description

Pull request #62936 added display of doc comments in the inspector, but with a small problem.
If you add a doc comment to an already exported variable, it does not appear until the project is reloaded. If you add a doc comment before the variable is exported, and then export it, the doc comment will be displayed immediately.

~~Upd: 77d3ac7 breaks the display of doc comments in the inspector.~~ (fixed in #64246)

### Steps to reproduce

- create variable and export it
- add doc comment

**Comment by YuriSizov** [comment]
> If you add a doc comment to an already exported variable, it does not appear until the project is reloaded. If you add a doc comment before the variable is exported, and then export it, the doc comment will be displayed immediately.

That means that adding doc comments doesn't invalidate some cache that would trigger an inspector to update, and that https://github.com/godotengine/godot/pull/62936 wasn't a sufficient fix to begin with. Likely, there needs to be a patch for the GDScript module to execute notify_property_list_changed when you change doc comments.

**Comment by Xwdit** [comment]
> Upd: https://github.com/godotengine/godot/commit/77d3ac700d5f528c0393d6aff1306e76f07b0d83 breaks the display of doc comments in the inspector.
This problem should be fixed in #64246

**Comment by adalinesimonian** [comment]
Per https://github.com/godotengine/godot/pull/64246#issuecomment-1228953314 still experiencing this issue after the fix.

**Comment by Calinou** [comment]
I can't reproduce this in 4.1.beta 33957aee6 (Linux), likely thanks to https://github.com/godotengine/godot/pull/71843.

**Comment by anvilfolk** [comment]
Agreed with that assessment :)

**Comment by akien-mga** [comment]
Fixed by #71843.
