### ISSUE TITLE
CanvasItem modulate property not working when YSort Enabled is set to true

### ISSUE THREAD

**Issue by HexagonNico** [godotengine/godot#63994]
### Godot version

4.0 alpha 13

### System information

Manjaro Linux x86_64, Kernel 5.15.57-2-MANJARO, GPU Nvidia GeForce RTX 3050, Driver version 515.57, Vulkan Mobile

### Issue description

Children of Node2D nodes ignore the parent's 'modulate' property if 'y sort enabled' is set to true. If y sorting is not enabled, child nodes inherit the parent's color, but when it is enabled the color is ignored.

### Steps to reproduce

* Create a Node2D
* Change its 'modulate' property
* Add a Sprite2D node as a child of the Node2D and add any texture, the sprite should inherit the Node2D's modulate color
* Now set 'y sort enabled' in the Node2D to true, now the Sprite2D node no longer inherits the parent's color

### Minimal reproduction project

[Report-ModulateYSort.zip](https://github.com/godotengine/godot/files/9274790/Report-ModulateYSort.zip)

**Comment by HexagonNico** [comment]
Update: I'm trying to reproduce this issue in Beta 1.

I created a new project and it seems to be partially fixed, now the 'modulate' property only stops working if the node's parent also has 'y sort enabled' set to true.

For instance, this works as expected:

- Node2D (y sort enabled = **false**)
  - Node2D (y sort enabled = false, change modulate color)
    - Sprite2D (color is inherited)
  - Node2D (y sort enabled = true, change modulate color)
    - Sprite2D (color is inherited)

This does not:

- Node2D (y sort enabled = **true**)
  - Node2D (y sort enabled = false, change modulate color)
    - Sprite2D (color is inherited)
  - Node2D (y sort enabled = true, change modulate color)
    - Sprite2D (color is **NOT** inherited)

**Comment by HexagonNico** [comment]
Still happens in Beta 2

**Comment by HexagonNico** [comment]
Still happening in beta 3

**Comment by HexagonNico** [comment]
I have updated to version **4.0.1 stable** and this seems to have been resolved, except for **CanvasGroup** nodes, although I'm not sure if this should be considered as expected behavior for the latter. Can someone confirm that?

**Comment by eh-jogos** [comment]
> I have updated to version **4.0.1 stable** and this seems to have been resolved, except for **CanvasGroup** nodes, although I'm not sure if this should be considered as expected behavior for the latter. Can someone confirm that?

For me this is still happening, regardless of node type, tested it with plain Node2D and plain Control nodes in the issue I submitted. Did you do anything different to solve it for other nodes?

**Comment by HexagonNico** [comment]
Just checked, apparently it is working when changing the modulate color of the root node, but not for the children.

**Comment by hsandt** [comment]
Just got the bug, I'll add some pictures since there aren't any in the OP:

Tree
![image](https://user-images.githubusercontent.com/1067772/236543113-eaf22972-0830-44ae-a3d2-09af0fd49a07.png)

Y Sort disabled
![image](https://user-images.githubusercontent.com/1067772/236543171-8513e7cc-6b40-4aca-a98d-a44d2aa4d557.png)

Y Sort enabled
![image](https://user-images.githubusercontent.com/1067772/236543226-2b91cd01-211b-494b-9c5f-a13e2de7d23a.png)

The icon parent says "modulated", the children lost their color tints.

The reason why only children are affected is probably that they are temporarily "detached" from their parent from the PoV of the renderer to apply Y sorting with nodes elsewhere in the scene tree.
