### ISSUE TITLE
3.5 NavigationObstacle nodes without deprecated Navigation / Navigation2D node parents do not work

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#64185]
### Godot version

3.5.stable

### System information

Windows10

### Issue description

NavigationObstacle for 2D and 3D do not work in Godot 3.5 without a deprecated Navigation / Navigation2D node as a parent as they do not connect to the default World / World2D navigation map.

Workaround is to set the navigation map and radius manually for the obstacle node agents with the NavigationServer API.

For 3D:
`NavigationServer.agent_set_map($NavigationObstacle.get_rid(), get_world().get_navigation_map())`
`NavigationServer.agent_set_radius($NavigationObstacle.get_rid(), obstacle_radius_float)`

For 2D:
`Navigation2DServer.agent_set_map($NavigationObstacle2D.get_rid(), get_world_2d().get_navigation_map())`
`Navigation2DServer.agent_set_radius($NavigationObstacle2D.get_rid(), obstacle_radius_float)`

### Steps to reproduce

Use NavigationObstacle nodes without a Navigation / Navigation2D node as a parent.

### Minimal reproduction project

na

**Comment by akien-mga** [comment]
Fixed by #64372.

**Comment by timothyqiu** [comment]
This issue still exists in 3.5.rc2 and current 3.x branch.

https://github.com/godotengine/godot/blob/faade5f1c365362302c81721064cf4caa011313c/scene/3d/navigation_obstacle.cpp#L142-L154

The updated code in #64372 won't be executed since `navigation` is null by default and `set_navigation()` will do an early return if no `Navigation` node is found.

**Comment by akien-mga** [comment]
Fixed by #66530.

**Comment by andreas-volz** [comment]
Just a potential workaround for Godot 3.5.1 users:

Create a new derived class NavigationObstacleRadius2D.gd and then use that instead of NavigationObstacle2D and set radius on your own in the editor.

```
tool
class_name NavigationObstacleRadius2D
extends NavigationObstacle2D

export(float) var collision_radius = 0.0

func _ready() -> void:
	var parent = get_parent()
	estimate_radius = false
	
	# Workaround to set NavigationObstacle2D navigation map properly until PR gets fixed in 3.5
	# https://github.com/godotengine/godot/issues/64185
	Navigation2DServer.agent_set_map(self.get_rid(), parent.get_world_2d().get_navigation_map())
	Navigation2DServer.agent_set_radius(self.get_rid(), collision_radius)
```
