### ISSUE TITLE
CanvasItem light_mask is ignored by LightOccluder2D occluder_light_mask

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#64939]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Ubuntu, Nvidia

### Issue description

By setting CanvasItem light_mask to a different layer than LightOccluder2D light_mask, it was possible to have shadows not being drawn on top of sprites. This does no longer work.

Godot 3:

![image](https://user-images.githubusercontent.com/23386940/186956411-51c6efde-cab8-45f2-a115-fdea6b1e7fb8.png)

Identical setup in Godot 4:

![image](https://github.com/godotengine/godot/assets/23386940/c2356ef1-f9ac-4245-9ec4-c70a65e431c4)

Especially in topdown games you generally need this to work.

### Steps to reproduce

1. Set your PointLight2D's range_item_cull_mask to cover layer 1 and 2
2. Set your Sprite2D's light_mask to 2 only
3. Add LightOccluder2D that remains on default for occluder_light_mask and light_mask (layer 1)
4. have the LightOccluder2D polygon cover (part of) the sprite
5. hit F6 and note that the shadow is rendered on top of the sprite. the shadow should not be rendered on top of the sprite as is the case in Godot 3.

### Minimal reproduction project

projects for both godot 3 and 4 to compare:

[light-occluder-sprite-bug.zip](https://github.com/godotengine/godot/files/9435066/light-occluder-sprite-bug.zip)

**Comment by PoisonousGame** [comment]
In godot3, add a CanvasModulate node, and then a PointLight2d node. Set the CanvasModulate color to black and the light will illuminate things in range, this doesn't work in godot4. The documentation is also not updated and the 2D lights don't seem to be maintained!

**Comment by wattsUpJaz** [comment]
> In godot3, add a CanvasModulate node, and then a PointLight2d node. Set the CanvasModulate color to black and the light will illuminate things in range, this doesn't work in godot4. The documentation is also not updated and the 2D lights don't seem to be maintained!

Do you have a background set in your Godot 4 scene? I'm able to use the CanvasModulate node fine.

As for documentation, I think that comprehensive Godot 4 docs are still a ways off since the version is still in the early beta phase.

**Comment by wattsUpJaz** [comment]
For anyone interested, I'm working around this by :

1. Following the steps above for the bug.
2. Adding an extra light with Shadows disabled and the Item Cull Mask only set on 2 (Layer 2 is the layer of the sprite's light mask).
3. Setting the `range_item_cull_mask` for the original light to only include 1 (Layer 1 is the layer of the occluder's light masks).

This is what it looks like:
<img width="193" alt="Godot test scene" src="https://user-images.githubusercontent.com/15367315/194132305-458ae362-e82c-4003-bd87-d39fa593ce90.png">

Scene tree:
<img width="288" alt="Godot scene tree" src="https://user-images.githubusercontent.com/15367315/194133292-4554a1d4-43c3-4297-92e1-95ac36cc6917.png">

**Comment by hmturnbull** [comment]
Has there been any more attention paid to this issue since 4.0 released?  The way light occluders now always draw atop the related sprite has rendered occluders practically unusable in almost every common use case I can think of.

If a tree can't cast a shadow without that shadow obscuring the tree itself, then there's no way to make shadows at all, as far as I can tell.

**Comment by eth0net** [comment]
I'm so glad I found h0lley's video on this! Been fighting with the 2D lighting system for a top-down game and could not get it to work the way I expected... Thanks for the workaround wattsUpJazz!

**Comment by Persipaani** [comment]
Oh please fix this one! I can't really use the alternative solution suggested here so I would love to have the Godot 3 functionality....

**Comment by Calinou** [comment]
@Persipaani Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by parthipan51** [comment]
You have to set LightOccluder node's cull mode to counterclockwise/clockwise (depending on where the light should enter)  to light faces right under the LightOccluder node. Note: Disabling cull mode turns the node into a closed polygon which is the reason why no light enters into the lightoccluder node's area

**Comment by parthipan51** [comment]
> > You have to set LightOccluder node's cull mode to counterclockwise/clockwise
> 
> @parthipan51 do you mean this is something that can be done in the Godot UI directly (this ticket is desired behavior and not a bug)? Or is this something that needs to be done in C++ inside Godot source (this ticket is still a bug)?

Yes, it is a desired behavior

![theOne](https://github.com/godotengine/godot/assets/39334768/66f7104d-7f34-4844-9088-aed76e53041a)

[theVideoOne.webm](https://github.com/godotengine/godot/assets/39334768/93382bf2-7e1d-4919-a78e-662bafe0b339)

**Comment by h0lley** [comment]
@parthipan51 cool, although I am not sure that's a solution to this issue.

`show_behind_parent` doesn't do anything for me (and anyways, it my not always be feasible to place the `LightOccluder2D` as a child node to the sprite(s) it should render underneath.)

and `cull_mode` is not sufficient as soon your sprite's outline and light occluder's polygon are not identical (as is probably the case in most actual applications):

![image](https://github.com/godotengine/godot/assets/23386940/4c439be6-980b-4ca5-915c-a6226cbdae8e)

**Comment by clayjohn** [comment]
We discussed this last night in our weekly rendering meeting. 

I think the OP is a bit misleading as it mentions the light_mask and occluder_light_mask, but the problem doesn't really have to do with the occluder. The occluder is already properly culled if its mask doesn't match that of the light (as pointed out by Guilleatm: https://github.com/godotengine/godot/issues/64939#issuecomment-1746001630). 

The problem is that in Godot 3.x, CanvasItems additionally took the occluder_light_mask into account. This worked very simply in 3.x because we did a separate draw call for each light for each draw command. We could then easily filter out the shadow at the same time we filtered out the light. 

In 4.x, we render all lights in the same draw call. Which means if we want to bring back that behaviour, we need to mask out the shadow in the shader

**Comment by dmhagar** [comment]
Is there any timeline for fixing this, or is there a simple modification that could be made to Godot's source code so the fix could be built in user-side? This is pretty much game-halting when trying to design an isometric game that needs light occlusion.

**Comment by clayjohn** [comment]
While waiting for a full fix to this issue, you could merge https://github.com/godotengine/godot/pull/93881 locally. It provides a new feature that can be used to work around this problem.

**Comment by dmhagar** [comment]
Thanks... unfortunately that doesn't help me since I'm building in 2D isometric with y-sorting and I cannot change the z-index of individual tiles without breaking draw order.

Annoyingly, I also can't use the duplicate light trick outlined above by @wattsUpJaz because I programmatically use all of the existing light mask layers already, as my game generates regional maps with up to 20 potential height layers and those are all used to determine where point lights can cast, like so:

`func setup_region_tilemaps():
	# Create a TileMap for each additional height layer (1-20) containing only the relevant layer originally from TileMap 0.
	tilemap_layers[0] = self
	var layer_bitmask
	for layer in range(1,max_layer + 1):
		var layer_tilemap = TileMap.new()
		layer_tilemap.tile_set = tile_set.duplicate()
		layer_tilemap.name = str(layer)
		add_child(layer_tilemap)
		var light_layers = []
		for light_layer in range(layer + 1,layer + 4):
			if not light_layer > max_layer + 1:
				light_layers.append(light_layer)
		Global.set_light_mask_for_layers(layer_tilemap,light_layers)`

It seems like I'm kind of boned when it comes to using occluders until a fix is provided.

**Comment by clayjohn** [comment]
Alright, I've figured out a way to bring back the `shadow_item_cull_mask` I implemented my idea for the RD renderer already and it works! Commit here: https://github.com/godotengine/godot/commit/c9c3541f72ce6bf865f1ab415153648919d2fe47

It required a bit of a refactor. I just need to carry the same changes over to the Compatibility renderer and then I'll PR it!


_Screenshot for Proof ;)_
![image](https://github.com/user-attachments/assets/632156d9-1711-4622-9544-ce81905a9113)

**Comment by SlavaSTiwari** [comment]
Will this be added to Godot in the near future or is the fix just modify the files myself?

**Comment by h0lley** [comment]
> Will this be added to Godot in the near future or is the fix just modify the files myself?

a [fix](https://github.com/godotengine/godot/pull/98835) by clayjohn has been merged into master and will be in the next official build, presumably 4.4.dev6. if you need it earlier you can [compile yourself](https://docs.godotengine.org/en/stable/contributing/development/compiling/index.html).

**Comment by zeeb1337** [comment]
Issue still persists. Quite a valuable feature that worked before but no longer does.

**Comment by h0lley** [comment]
> And I'd love to be able to have e.g. walls cast shadows on other walls but not themselves.

this is difficult to achieve in 2D, as all your walls are typically the same type of entity and are therefore on the same light layer, and so the system cannot differentiate between specific walls when it draws the shadows.

for realistic shadows on pseudo 3D structures there's probably no feasible way around 3D

**Comment by c67f** [comment]
> [@zeeb1337](https://github.com/zeeb1337) don't worry, this is fixed since v4.4.dev6.official [[1f47e4c](https://github.com/godotengine/godot/commit/1f47e4c4e3a09a422e96880a7918d986dd575a63)]

Hi,  what's the new method to accomplish this? I'm still getting the shadowed effect, although maybe it's different because I'm using a tilemap and not sprites?

**Comment by jeannen** [comment]
Same issue here. It the fix already available in the lastest version?

**Comment by h0lley** [comment]
as I said it's been fixed since 4.4.dev6, so yes it is in 4.4.stable.

if you just followed the reproduction steps of OP you get a setup with the desired effect.

**Comment by Lathryx** [comment]
Is this still an issue? It still seems to be for me in Godot v4.4.1.stable.official [49a5bc7b6].

**Comment by clayjohn** [comment]
@Lathryx this issue was fixed in Godot 4.4. you are likely experiencing a different issue.

**Comment by PlexSheep** [comment]
I'm still having this on v4.4.1.stable.official [49a5bc7b6], or maybe I'm just too stupid to understand it. I followed the docs, the bug description, everything i found...

**Comment by clayjohn** [comment]
@PlexSheep did you follow the steps in the description?

**Comment by PlexSheep** [comment]
When i followed the original steps:

1. Set your PointLight2D's range_item_cull_mask to cover layer 1 and 2
2. Set your Sprite2D's light_mask to 2 only
3. Add LightOccluder2D that remains on default for occluder_light_mask and light_mask (layer 1)
4. have the LightOccluder2D polygon cover (part of) the sprite
5. hit F6 and note that the shadow is rendered on top of the sprite. the shadow should not be rendered on top of the sprite as is the case in Godot 3.

In a new scene, it did work. This must be some kind of layer 8 error on my side then. Still, thanks!

 @clayjohn

**Comment by babofitos** [comment]
I couldn't get this to work until I realized I was an idiot and that I was setting the item cull mask for Shadow and not Range, in case anyone makes the same mistake.
