### ISSUE TITLE
Renaming a node will show it's old name for a split second

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#65109]
### Godot version

4.0 Alpha15

### System information

Win

### Issue description

https://user-images.githubusercontent.com/47016402/187533407-9983827b-4fa9-4b16-8ac3-23f3197cca1e.mp4

### Steps to reproduce

1. Add a node, 
2. select it and rename it
3. hit enter
4. watch it weirdly switch back to it's old name for a split second

### Minimal reproduction project

does not require a MRP

**Comment by Mickeon** [comment]
Ah, so it's not just me. I thought it was because it's a slow, debug build. I think that to fix this, either the text editor used during the renaming should be custom, or the rename is instantaneous, or... it forces the Popup to stay up until it's complete, somehow... Hmm...

**Comment by Rindbee** [comment]
Can be reproduced in alpha15, but not in beta1/ 1d19b0750, may have been fixed.

**Comment by golddotasksquestions** [comment]
@akien-mga 
I can still reproduce this issue in Godot4.0 Beta8. (Win 10, Nvidea 765M)
