### ISSUE TITLE
Custom resource export doesn't work with script inheritance

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#66987]
### Godot version

v4.0.beta.custom_build [61021c08f]

### System information

Kubuntu 22.04

### Issue description

First-class custom resource support has been added in #62417 and other PRs. However, this does not work with script inheritance. For example:

```gdscript
# item.gd
extends Resource
class_name Item

# apple.gd
extends Item

# apple.tres (Resource with apple.gd attached)
```

Inheritance is required if you want to add/override one or more functions of the base resource class, not just change the values of exported variables. However, you still want to be able to assign the resource in the inspector.

### Steps to reproduce

Try assigning the `apple.tres` resource to the `item` variable (or `items` element) in the `test.tscn` scene (via Load since Quick Load is always empty). You will get the error "The selected resource (Resource) does not match any type expected for this property (Item).". For a resource without script inheritance this works.

### Minimal reproduction project

[user-res-inheritance-bug.zip](https://github.com/godotengine/godot/files/9725926/user-res-inheritance-bug.zip)

**Comment by dalexeev** [comment]
@willnationsdev Could you check this please?

**Comment by willnationsdev** [comment]
Ahhh. I haven't looked into this, but I'm *guessing* the problem is "fixed" the moment you add a `class_name` to the `apple.gd` file. I think the GDScript export logic just isn't accounting for situations where the script is anonymous, but still extending a supported global script.

**Comment by willnationsdev** [comment]
I have a work-in-progress fix for this on my fork's `fix-anon-export` branch. The skeleton of the solution is done already, but it still doesn't quite work yet. Unfortunately, I've run out of time for today. Will try to finish it up at my next opportunity and then open a PR once I actually have the solution finished/tested.

**Comment by akien-mga** [comment]
This seems fixed in 4.0 RC 2.

**Comment by dalexeev** [comment]
I just tested, the bug is still reproducible in RC 2, even after restarting the project.

**Comment by akien-mga** [comment]
Works fine here with your MRP and steps to reproduce:
![image](https://user-images.githubusercontent.com/4701338/219649851-9290a2b2-787b-4050-8b04-99b5e8f19f29.png)

**Comment by dalexeev** [comment]
I downloaded the `.zip`, but for some reason it doesn't work for me. I tried to delete the `.godot` folder, but got the same error.

![](https://user-images.githubusercontent.com/47700418/219650371-8c7f4043-51d2-4484-9e0f-0e505377265a.png)

**Comment by akien-mga** [comment]
What do you have in your `.godot/global_script_class_cache.cfg`? Mine is:
```
list=Array[Dictionary]([{
"base": &"Resource",
"class": &"Item",
"icon": "",
"language": &"GDScript",
"path": "res://item.gd"
}])
```

**Comment by akien-mga** [comment]
Ok I could reproduce the issue.

I was testing with drag and drop of `apple.tres` to the Inspector, which works fine.

But the "Load" menu doesn't work, and "Quick Load" doesn't recognize it.

**Comment by dalexeev** [comment]
> What do you have in your `.godot/global_script_class_cache.cfg`?

The same. I noticed 2 more things:

1. You can drag `apple.gd` (not `apple.tscn`) into `Item`, which is wrong. No error will be displayed, `item` will be `null` at runtime. `apple.gd` **cannot** be dragged into an element of the `Items` array (correct).
2. Quick Load does not work correctly. Even `no_inheritance.tres` is not displayed at first. After a restart it appears, and after another restart it disappears again.

**Comment by eisegesis-623** [comment]
It appears this is still present in v4.5.rc1.mono.official [08e9e6b29].
