### ISSUE TITLE
GDScript 2.0: Class YYY hides a global script class: Caused by "orphan" script in .tscn due to renamed files

### ISSUE THREAD

**Issue by flotos** [godotengine/godot#67056]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.beta2

### System information

Windows 10

### Issue description

I "randomly" had `class YYY hides a global script class` error, and it seems to be because .tscn files hold a copy of the attached script. Thus, if we rename or move that script (for example capitalisation which is poorly handled on windows systems) when end with a duplicated script.
If said script has a class_name, we end up with duplicated class.

Should scenes be able to have a script not stored in a .gd ? This error is really counterintuitive to find, as you'd be tempted to use find feature which do not list .tscn content.

### Steps to reproduce

Create a script with a class_name.
Attach it to a node.
Rename that script with an uppercase on windows.
Try to run your game, the error should pop up.

**Comment by Calinou** [comment]
> Should scenes be able to have a script not stored in a .gd ?

Yes, Godot supports built-in scripts (with some caveats, such as not supporting `class_name`).

**Comment by SamuelHuylebroeck** [comment]
Encountered the same problem when refactoring my folder structure on one of my projects

**Comment by ra314** [comment]
I faced the same issue after resturcting my game files as well.

**Comment by Calinou** [comment]
> I faced the same issue after resturcting my game files as well.

Which Godot version are you using?

**Comment by ra314** [comment]
> Which Godot version are you using?

Originally godot 4 beta 3, but I tried godot 4 beta 4 as well to see if that would fix it but it didn't.
I also confirmed that my friend had the same issue with my project on his machine (windows).

Also I'm not sure if this helps, but the file just contains a bunch of enums. And I noticed this weird thing, where after modifying that file to add some enum options, and then printing the available options from that enum, the new options don't show up. The file seems to have been frozen in time at the point that it started throwing that error.

**Comment by ra314** [comment]
@Calinou Turns out that while restructuring, I accidentally duplicated a class script. Hence the error. My apologies for the false positive.

@SamuelHuylebroeck Could you check for duplicate files with the same class name?

Side note, for issues cause by duplicate files, I think it'd be helpful if the error message could point to the file location that contains the duplicated class.

**Comment by Indieology** [comment]
@ra314 Thank you so much! I don't know how one of my class scripts got duplicated, but this was the case for me as well. After deleting one of them, my issue is fixed. Having a great day now :)

**Comment by Rubrickus** [comment]
I ran into this similarly to the original report, after renaming a file Movers.gd (which included a class_name) to movers.gd. A .tscn file still contained a reference to the old (capitalized) filename, creating a "ghost file" duplicate.

It's a bit unfortunate that, while Godot style guides recommend snake_case for filenames, it's very easy to end up creating a capitalized file; and then trying to rename it in the editor (to conform to the style guide) can lead to these very-hard-to-find bugs.

**Comment by Zireael07** [comment]
> It's a bit unfortunate that, while Godot style guides recommend snake_case for filenames

It's a recommendation, not a requirement.

**Comment by hsandt** [comment]
I had to close and reopen the project so the old tscn script was cleaned up and the error disappeared. I also removed .godot folder but I'm not sure if this was needed, if the issue lies inside .tscn.

**Comment by Griiimon** [comment]
Encountered this issue twice recently. The second time was interesting because I realized immediately what caused it:
I deleted my worlds save data, which is located in res://...//save

So this wasn't triggered by renaming any scripts or moving scripts around (which was likely the cause of my first encounter) but rather just some change in the projects files, which aren't referenced in any of my scenes/scripts or whatever. 

Fixed it by deleting the .godot folder and restarting the project. Custom build of rc1.

Btw, in both cases there WEREN'T actually any duplicate script files on my disk. I made sure via OS file system search.

**Comment by TakoyakiAndy** [comment]
I ran up across this issue recently using godot 4.0 rc 2. No duplicate files. occurred after renaming a file.

**Comment by cmann1** [comment]
This doesn't just seem to be from renaming files, and deleteing `.godot` doesn't fix the issue for me.
The attached project will somewhat randomly give the error `Class "Unit" hides a global script class.` but still runs.
Also it seems after modifying `unit.gd` and trying to run will stop with errors, but then closing and running again without making any changes works though the error still shows up in the editor.
[DefenceGame.zip](https://github.com/godotengine/godot/files/10844132/DefenceGame.zip)

**Comment by PrinceMerluza** [comment]
Getting this on 4.0.1 after a straightforward refactoring of files (always janky with Godot in my experience).

I can't even begin to debug it because it's showing an error and I can't find the script.

```
Parser Error: Class "Item" hides a global script class.
0 - gdscript://-92233(some random numbers).gd:2 - at function:
```

Also I haven't used any built-in scripts.

Deleting .godot also doesn't work. There's high possibility it's my own fault and an actual error in the scripts but the error message is not helping at all and I can't find the supposed gd file.

**Comment by fkeyzuwu** [comment]
> Getting this on 4.0.1 after a straightforward refactoring of files (always janky with Godot in my experience).
> 
> I can't even begin to debug it because it's showing an error and I can't find the script.
> 
> ```
> Parser Error: Class "Item" hides a global script class.
> 0 - gdscript://-92233(some random numbers).gd:2 - at function:
> ```
> 
> Also I haven't used any built-in scripts.
> 
> Deleting .godot also doesn't work. There's high possibility it's my own fault and an actual error in the scripts but the error message is not helping at all and I can't find the supposed gd file.
> 
> EDIT:
> 
> Changing the class_name does exacttly the same thing. "Class "GameItem" hides a global script class." With the exact random number gd script at line 2. So I'm assuming this script is the ACTUAL script class but somehow it's causing an error when there are no other syntax errors on the file.
> 
> EDIT2:
> 
> My issue is a different cause to orphaned scripts. Opened here: #75392

having the same issue with 4.0.2 stable, same thing after refactoring a lot which causes a lot of compile time warnings/errors until they resolve when i finish with the refactoring.

**Comment by Piratux** [comment]
Getting this on 4.0.2 stable as well after I simply rename or change directory of .gd file which has this on the top:
```
class_name FreeLookCamera extends Camera3D
```
Closing Godot and opening it again makes the issue go away.

**Comment by Omtlio** [comment]
In Godot 4.0.2 stable making a copy, through the Windows' explorer, of a script containing a class_name causes the error. The original file stays attached to the node, but the class_name instruction points to the new copy made. Closing and reopening Godot doesn't fix the issue! It works only by deleting the freshly copied file.

**Comment by SimDietrich** [comment]
I had this.  What it turned out to be in my case, was one of my scenes importing **S**cript.gd and the rest importing **s**cript.gd.  Once you rename a script, you need to check all of your scenes that may reference it.

**Comment by HunAndBun** [comment]
I experienced this bug again in v4.0.3 (flathub-stable on linux) when restructuring my filesystem in-editor. All I did is move all UI related scripts to a dedicated folder, and each custom class_name began telling me it conflicted with a global script class. 

I found a quick solution, however. Disabling all Autoload scripts, re-loading the project, then re-enabling them clears the issue. None of my Autoload scripts have any reference to the problem-scripts, so I'm not sure what the connection is.

**Comment by RudyFisher7** [comment]
Just experience this using bytes_to_var_with_objects() on a class extending Resource. 4.0.0.stable. Hope this gets resolved soon. Hard to load game saves without it.

**Comment by fkeyzuwu** [comment]
I see many people here struggle with the problem, for me the solution was said here but I guess its a bit hidden.

You have built-in temporary scripts within .tscn files that sometimes linger due to some bug. so there is the .gd file and the built-in script within a .tscn somewhere, causing a duplicate classname error. If you find the same script contents within a .tscn file and not just a reference to an existing .gd file, delete it manually from the .tscn file in a text editor. it fixed it for me.

might not be the same problem for everyone though, but throwing this out there in case it helps anyone.

**Comment by saletrak** [comment]
I'm not sure does this help anyone, but when I changed names like this:
```
res://scenes/enemy.tscn -> res://scenes/Enemy.tscn
res://scenes/Enemy.gd (kept as it was) (has class_name Enemy)
```
The entry for Enemy class_name in `.godot/global_script_class_cache.cfg` disappeared, and editor isn't throwing an error about "hiding global script class" like it was.

Btw. isn't this issue related with #77478

**Comment by DefaultHeathen** [comment]
Had the same issue start up yesterday. 
My case was accidently creating a series of folders from an addon (xr tools), and so was in a "non-critical" area, YMMV.

I fixed it by 1) removing the copies first, of course, but within the editor and not with the OS file manager, which I think led to the creation of 'ghost' srcs/tscns (I also wasn't able to find the in the affected .gd/.tscns any indication of a wrong path).

(Probably backup the project, just in case for this next part. Or the just the files affected)

I then 2) removed the files/folders that were copied within the godot editor, clicking "remove" when asked that I'm going to break everything. 
Project runs fine now. Hope this helps someone

**Comment by scotdoria** [comment]
This has been a nightmare. I was able to fix this before but the error came back for some reason after opening it recently. This bug has essentially broken my game project and ruined a lot of dependencies. Every time I get to fix the error in one class, another error appears and the error I just fixed is broken again. I've given up and will just rebuild my scenes in another project.

**Comment by hakuhan** [comment]
I got this issue too! When I rename my addons name in file manager and VSCode(without open editor).
And found a way to escape from these issues by following steps:
1. Disable my addons.
2. Close editor.
3. Remove most of my files in addons to other folder. (_eg._ Download).
4. Open editor.
5. Copy files back.
6. Enable addons.

**Comment by fkeyzuwu** [comment]
> 

popping in again just to highlight this - global_script_class_cache.cfg inside the .godot folder keeps track class_names, but it seems sometimes it doesn't get rid of them when deleting/changing files. if you manually delete the array value within the .cfg file which contains the "class": &"YourClassName", it can also work. haven't tested it a lot but it worked for my use case.

**Comment by saletrak** [comment]
But backup first, like I wrote above. This action override the file.
Hope the fix of this will be the major change in 4.2.

**Comment by Fogsight** [comment]
Appeared seemingly out of nowhere on 4.1.2, Just opened the project and created another classed script and passed as reference in the parent. But it affected different class.

The only fix that worked is detaching/reattaching script with affected class and the error was gone.

**Comment by SoapSpangledGames** [comment]
> popping in again just to highlight this - global_script_class_cache.cfg inside the .godot folder keeps track class_names...

This worked for me. I had copied an entire directory that contained aiming reticle class files to another weapon directory, then decided I didn't want the copy. I deleted the entire directory copy using Konqueror, then this error started appearing. 

I exited Godot, edited this file from the project's .godot directory (deleting the reticle array), reloaded Godot and the project, and the error was gone.

As an added note, I tried exiting and restarting Godot and the project before editing this file, and the error persisted. After editing the file, the error went away.

Thanks a bunch! This saved me many hours of frustration.

**Comment by jordanmichaelrushing** [comment]
I've been dealing with this for a number of weeks. Things worked even with the error messages so I was able to ignore it. I finally came up with a solution. Here's what happened to me:

My folder structure was previously setup like
```
Scenes/.
Scripts/.
 ...
 ```
 and I renamed them
 ```
 scenes/.
 scripts/.
 ...
 ```

Things worked but any of my scripts that had class_name were barfing. I realized that the FileSystem in the bottom left (the place where it has `res://` in a folder like structure) is not a 1:1 of your folder/file structure. This is because in that space I have both `Scripts/.` & `scripts/.` as well as `Scenes/.` & `scenes/.` and both were duplicated.

How I fixed it (before you move forward, make sure you start from a fresh git place, IE push what you have to your repo in case you need to start over):
I opened up the entire project in a separate IDE (VS Code in this instance) and did a global search for "res://Scripts" and made sure I clicked on match case (the one that looks like "Aa"). And I manually changed each one from the old uppercase style to the newer lowercase style (make sure to save each file). I did the same thing for "res://Scenes", then I closed out Godot and reopened it. Voila, no more error message about class name clashes.

I hope this helps out others, and if you mess up, just go back to your latest deployed branch on your git repo and try again.

**Comment by wpbirney** [comment]
I'm running into a similar issue where it works fine when ran from editor. But when running with an exported .pck it throws the `SCRIPT ERROR: Parse Error: Class "SmokePickup" hides a global script class.` and then the item pickup doesnt work

**Comment by KoBeWi** [comment]
Can't reproduce this in 4.3.

**Comment by SoapSpangledGames** [comment]
This happened to me again, and deleting the block from the cache file didn't work as Godot just put it back. In this case, I changed the class_name to something else (I deleted the last character) and saved. Godot wrote the new name to the cache file, and removed the error bar. I then changed the name back and saved. Godot changed the cache file to reflect the "new" old name, and did not display the error bar.
