### ISSUE TITLE
Custom resources don't appear in "quick load"

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#67119]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11, GLES3, NVIDIA GeForce GTX 1650, i5-11300H

### Issue description

Quick load doesn't detect custom resources

### Steps to reproduce

1. Create a custom resource with a class name 
2. Create a resource of the type you created 
3. Create a new node and attach a script. To that script add an export variable of the same type as the resource you created
4. Right click -> Quick load, you'll see the list doesn't contain your resource

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/9741110/Example.zip)

**Comment by TechnoPorg** [comment]
This is expected for now as a result of #66215, which disabled QuickOpen custom resource loading because a refactor is needed for editor data structures to make it work without being prohibitively slow.

**Comment by ababen1** [comment]
Oh I see. Should I close this issue then?

**Comment by akien-mga** [comment]
No the issue can stay open as a reminder that this feature is missing.

**Comment by KoBeWi** [comment]
This issue was fixed few betas ago.

**Comment by Cratesmith** [comment]
> This issue was fixed few betas ago.

I'm still experiencing this issue in both 4.0 and 4.0.1
![image](https://user-images.githubusercontent.com/4616107/227500269-338b3b44-0c8f-4215-be0a-8afa8d4b6c69.png)

**Comment by KoBeWi** [comment]
@Cratesmith Please provide a minimal reproduction project.
I tested the one attached in this issue and Resources need a `script_class` field to appear in Quick Load. If you have resources created before this issue was fixed, you need to re-save them.

**Comment by ababen1** [comment]
It was fixed for me but I noticed that when I deleted the `.godot` folder the resources disappeared again

**Comment by Cratesmith** [comment]
I'll make a minimum project for it tomorrow, but I've actually never had the resources appear in quickload. In my case, I haven't deleted the .godot folder to get this effect.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by lexusinator** [comment]
Same issue here, in Godot 4.1 custom resources still don't show in "Quick Load"

**Comment by watsaponk** [comment]
In Godot 4.1 this still happen randomly, it seem like quick load does not recognize old custom resource, and I have to recreate some resource to make it work, not sure what is the cause of this issue maybe some cache file system

**Comment by watsaponk** [comment]
addition info, let's say we have 2 custom resources in the project "A" and "B"
- when I recreate "A" the quick load will only recognize "A" ("B" is disappear from search result, you cannot find them event type the name)
- then I recreate "B" now quick load will only recognize "B" and "A" is gone from search result

**Comment by watsaponk** [comment]
These issues will gone when removing `.godot` folder and then re-import the project

**Comment by KoBeWi** [comment]
From my experience it will re-appear.

**Comment by luislodosm** [comment]
Same here. Godot 4.2.1

Custom resources:

<img width="243" alt="Captura de pantalla 2023-12-14 a las 11 14 17" src="https://github.com/godotengine/godot/assets/63356898/0e900436-e1e5-4cbb-92b6-280403b9b5bb">



Quick load menu:

<img width="600" alt="Captura de pantalla 2023-12-14 a las 11 13 57" src="https://github.com/godotengine/godot/assets/63356898/7127015a-8d3d-48d4-a639-e5f4725faa53">


It seems that **.godot/editor/filesystem_cache8** doesn't reference the rest of the resources. Deleting this file doesn't solve the problem.

Why is this issue closed?

**Comment by luislodosm** [comment]
So I made an **editor plugin** with a button that **resave** all my custom resources, so they appear again in the **quick load** menu:

```
@tool
extends Button

func _on_pressed():
	var file_paths = get_all_file_paths("res://resources")
	resave_resources(file_paths)

func get_all_file_paths(path: String):
	var file_paths = []
	var dir = DirAccess.open(path)
	dir.list_dir_begin()
	var file_name = dir.get_next()
	while file_name != "":
		var file_path = path + "/" + file_name
		if dir.current_is_dir():
			file_paths += get_all_file_paths(file_path)
		else:
			file_paths.append(file_path)
		file_name = dir.get_next()
	return file_paths
	
func resave_resources(file_paths):
	for path in file_paths:
		if ResourceLoader.exists(path):
			var resource = ResourceLoader.load(path)
			ResourceSaver.save(resource, path)
			print("Re-saved: " + path)
```

**Comment by AndreiSchapov** [comment]
I'm having the same issues as @luislodosm, only some of the custom resources are shown in the Quick Load. I think this issue should be reopened.
