### ISSUE TITLE
Crash when unsing NavigationAgent2D with unconnected Tilemap

### ISSUE THREAD

**Issue by jarissimo** [godotengine/godot#67154]
### Godot version

4.0.beta2.official (f8745f2f7)

### System information

Ubuntu 20.4

### Issue description

Godot 4.0 Beta 2 crashes when using Tilemap plus NavigationAgent2D and setting a navigation target to a disconnected map region.

### Steps to reproduce

* Create a TileSet with a tile that has a navigation set.
* Create a TileMap that has two unconnceted areas of said tile with  navigation.
* Create a player with a NavigationAgent2D.
* Set the navigation target (via set_target_location) to region that is not connected to the area the player is on.

### Minimal reproduction project

[godot_navigationagent2d_crash.zip](https://github.com/godotengine/godot/files/9742465/godot_navigationagent2d_crash.zip)

**Comment by timothyqiu** [comment]
Fixed by #66784

**Comment by smix8** [comment]
@timothyqiu This is not fixed, the test project crashes for me even with recent master.

**Comment by timothyqiu** [comment]
@smix8 I tested today on the current master (ca25c6e) and the MRP did not crash. I reverted #66784 locally and it crashed.

What's your crash log?

**Comment by smix8** [comment]
@timothyqiu 
I just rebuild Godot again with master, `NavMap::get_path()`crashes `at nav_map.cpo:168` with `ERROR: Index p-Index = 5 is out of bounds (count = 1).` with the test project for me.
