### ISSUE TITLE
Exporting to Oculus Quest 2 APK fails

### ISSUE THREAD

**Issue by mgrigajtis** [godotengine/godot#67378]
### Godot version

4.0 master branch

### System information

Windows 11, NVIDIA 3060, Vulkan Mobile

### Issue description

When attempting to export (or run) for Oculus Quest 2, the build fails when checking for duplicate classes.  Oddly enough, the official beta release 2 still works.

Output below:

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 32

This Android Gradle plugin (7.0.3) was tested up to compileSdk = 31

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=32
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 32
> Task :clean UP-TO-DATE
> Task :assetPacks:installTime:clean UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig
> Task :generateDebugResValues
> Task :generateDebugResources
> Task :checkDebugAarMetadata
> Task :createDebugCompatibleScreenManifests
> Task :extractDeepLinksDebug

> Task :processDebugMainManifest
[godot-lib.debug.aar] C:\Users\matth\.gradle\caches\transforms-3\cf7ae2ec09238bef6db7db8a479e5c5f\transformed\jetified-godot-lib.debug\AndroidManifest.xml Warning:
	Package name 'org.godotengine.godot' used in: godot-lib.debug.aar, godot-lib.template_debug.aar.
D:\Godot 4 Projects\Silver Moon\android\build\src\debug\AndroidManifest.xml:11:5-134 Warning:
	uses-feature#android.hardware.vr.headtracking was tagged at AndroidManifest.xml:11 to replace another declaration but no other declaration present

> Task :processDebugManifest
> Task :mergeDebugNativeDebugMetadata NO-SOURCE
> Task :javaPreCompileDebug
> Task :mergeDebugShaders
> Task :compileDebugShaders NO-SOURCE
> Task :generateDebugAssets UP-TO-DATE
> Task :mergeDebugResources
> Task :mergeDebugAssets
> Task :processDebugJavaRes NO-SOURCE
> Task :checkDebugDuplicateClasses FAILED
> Task :mergeDebugJniLibFolders
> Task :processDebugManifestForPackage
> Task :desugarDebugFileDependencies
> Task :compressDebugAssets

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.android.vending.licensing.ILicenseResultListener found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicenseResultListener$Default found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicenseResultListener$Stub found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicenseResultListener$Stub$Proxy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicensingService found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicensingService$Default found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicensingService$Stub found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.android.vending.licensing.ILicensingService$Stub$Proxy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.Constants found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloadProgressInfo found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloadProgressInfo$1 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderClientMarshaller found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderClientMarshaller$Proxy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderClientMarshaller$Stub found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderClientMarshaller$Stub$1 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderClientMarshaller$Stub$MessengerHandlerClient found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderServiceMarshaller found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderServiceMarshaller$Proxy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderServiceMarshaller$Stub found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.DownloaderServiceMarshaller$Stub$MessengerHandlerServer found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.Helpers found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.IDownloaderClient found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.IDownloaderService found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.IStub found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.SystemFacade found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.CustomIntentService found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.CustomIntentService$ServiceHandler found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadInfo found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadNotification found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadThread found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadThread$InnerState found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadThread$RetryDownload found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadThread$State found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadThread$StopRequest found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloaderService found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloaderService$GenerateSaveFileError found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloaderService$InnerBroadcastReceiver found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable$1 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadsDB found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadsDB$DownloadColumns found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadsDB$DownloadsContentDBHelper found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.DownloadsDB$MetadataColumns found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.HttpDateTime found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.expansion.downloader.impl.HttpDateTime$TimeOfDay found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.AESObfuscator found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.APKExpansionPolicy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.DeviceLimiter found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.LicenseChecker found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.LicenseChecker$ResultListener found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.LicenseChecker$ResultListener$1 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.LicenseChecker$ResultListener$2 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.LicenseCheckerCallback found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.LicenseValidator found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.NullDeviceLimiter found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.Obfuscator found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.Policy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.PreferenceObfuscator found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.ResponseData found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.ServerManagedPolicy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.StrictPolicy found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.ValidationException found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.util.Base64 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.util.Base64DecoderException found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class com.google.android.vending.licensing.util.URIQueryDecoder found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.BuildConfig found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.Dictionary found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.FullScreenGodotApp found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.Godot found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.Godot$ResultCallback found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotDownloaderAlarmReceiver found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotDownloaderService found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotGLRenderView found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotGLRenderView$1 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotHost found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotIO found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotLib found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotRenderView found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.GodotVulkanRenderView found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.EGLLogWrapper found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$BaseConfigChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$ComponentSizeChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$DefaultContextFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$DefaultWindowSurfaceFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$EGLConfigChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$EGLContextFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$EGLWindowSurfaceFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$EglHelper found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$GLThread found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$GLThreadManager found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$GLWrapper found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$LogWriter found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$Renderer found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GLSurfaceView$SimpleEGLConfigChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.gl.GodotRenderer found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotEditText found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotEditText$1 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotEditText$EditHandler found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotEditText$VirtualKeyboardType found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotGestureHandler found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotGestureHandler$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotInputHandler found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.GodotTextInputWrapper found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.input.Joystick found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.StorageScope found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.StorageScope$Identifier found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.AssetsDirectoryAccess found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.AssetsDirectoryAccess$AssetDir found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.AssetsDirectoryAccess$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.DirectoryAccessHandler found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.DirectoryAccessHandler$AccessType found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.DirectoryAccessHandler$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.DirectoryAccessHandler$DirectoryAccess found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.DirectoryAccessHandler$WhenMappings found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.FilesystemDirectoryAccess found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.FilesystemDirectoryAccess$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.directory.FilesystemDirectoryAccess$DirData found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.DataAccess found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.DataAccess$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.DataAccess$Companion$WhenMappings found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileAccessFlags found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileAccessFlags$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileAccessFlags$WhenMappings found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileAccessHandler found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileAccessHandler$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileData found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.FileData$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.MediaStoreData found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.MediaStoreData$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.MediaStoreData$DataItem found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.io.file.MediaStoreData$WhenMappings found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.plugin.GodotPlugin found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.plugin.GodotPluginInfoProvider found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.plugin.GodotPluginRegistry found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.plugin.SignalInfo found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.plugin.UsedByGodot found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.tts.GodotTTS found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.tts.GodotUtterance found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.utils.Crypt found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.utils.GLUtils found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.utils.GodotNetUtils found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.utils.PermissionsUtil found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.utils.ProcessPhoenix found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.vulkan.VkRenderer found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.vulkan.VkSurfaceView found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.vulkan.VkSurfaceView$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.vulkan.VkSurfaceView$vkThread$2 found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.vulkan.VkThread found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.vulkan.VkThread$Companion found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.XRMode found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.ovr.OvrConfigChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.ovr.OvrContextFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.ovr.OvrWindowSurfaceFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.regular.RegularConfigChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.regular.RegularContextFactory found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     Duplicate class org.godotengine.godot.xr.regular.RegularFallbackConfigChooser found in modules jetified-godot-lib.debug-runtime (godot-lib.debug.aar) and jetified-godot-lib.template_debug-runtime (godot-lib.template_debug.aar)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
18 actionable tasks: 16 executed, 2 up-to-date

Exit Code: 1

### Steps to reproduce

Clone the Godot 4 Open XR example project (https://github.com/BastiaanOlij/godot4_openxr_demo), configure for Oculus Quest 2, attempt to export or run. 

### Minimal reproduction project

https://github.com/BastiaanOlij/godot4_openxr_demo

**Comment by akien-mga** [comment]
Related to https://github.com/godotengine/godot/pull/66935 which changed the name of the debut AAR lib. I noticed this too while building beta 3 yesterday, I'm not sure this was a necessary change, and it likely breaks compat for existing plugins. @m4gr3d

**Comment by BastiaanOlij** [comment]
That would indeed explain it and that would totally suck, because we can now either choose between working plugins in beta 2, or working plugins in master, not both... :)

Once this change is in a beta build we'll update the name in the plugin.

**Comment by BastiaanOlij** [comment]
@m4gr3d btw, does this also mean that we have a problem if we mix a debug build of the plugin with a runtime and vise versa seeing the name of the library it expects will be different? Thats probably an existing issue atm even with the old names... Or am I missing something?

**Comment by akien-mga** [comment]
For the record, I have built 4.0-beta3 and I'm about to release, which includes #66935.

So plugins will likely need to be changed for beta3+ indeed. And if we decide to go back to the old name in beta4 then we'll have to change again. But well it's beta and early days for most Android plugins for Godot 4.0 so it's probably not too big a deal.

**Comment by mgrigajtis** [comment]
Is there anything I have to do to get it to build locally, or will it be fixed in the master branch soon?

**Comment by BastiaanOlij** [comment]
@mgrigajtis if I understand the problem correctly it's just a matter of adjusting the `godot-lib` entry here: https://github.com/GodotVR/godot_openxr_loaders/blob/master/godotopenxrmeta/build.gradle#L42

**Comment by BastiaanOlij** [comment]
Well I tried this and it didn't fix the problem for me so there is more to this....

Also @akien-mga , we only put the release build of the lib as part of our releases. As a result I'm currently just including the release build of the godot-lib (I was before in beta2 as well and that worked).
The AAR plugin system currently doesn't even allow identifying release builds and debug builds so I'm not even sure how this is supposed to work.

So yeah I'm a bit stumped as to what the correct fix it.

Anyway, the change I'm currently working on is: https://github.com/GodotVR/godot_openxr_loaders/pull/12

**Comment by konczg** [comment]
@mgrigajtis @BastiaanOlij @akien-mga I was able to reproduce the issue locally. The cause of this bug was that the Godot source was updated without cleaning the workspace, so that it contained the previously built Android libraries with the old target names (which, I suppose, is included in the apk through an `include: ['*.aar']`). To make exporting to Android work, make sure that the source folder is clean before building Godot, and that the Android build templates are reimported into the project.

**Comment by BastiaanOlij** [comment]
@konczg actually, my source folder is clean, if by the source folder you mean `res://android/build`. It was duplicated in my android_source.zip. 

Running `gradlew clean` in `platform/android/java` doesn't seem to do a full job cleaning stuff up, I had to go manually into the build folders to clean up the old AARs so there is some room for improvement there.

**Comment by konczg** [comment]
@BastiaanOlij Yeah, the aar's in question seemed to be under `platform/android/java`. Sorry, by "cleaning" I meant a full `git clean -xdf`, that seemed to do the job for me :) (but always make sure first that there is no untracked change that needs to be kept)

**Comment by BastiaanOlij** [comment]
I'm very careful running `git clean -xdf` because it blows away my VSCODE setup :(

**Comment by m4gr3d** [comment]
Closing this issue as resolved.
