### ISSUE TITLE
Editor crash when moving scene file and referenced shader

### ISSUE THREAD

**Issue by dzil123** [godotengine/godot#67970]
### Godot version

v4.0.beta3.official.01ae26d31 and v4.0.beta.custom_build.468762b3b

### System information

Arch Linux

### Issue description

When moving a scene file and a shader file (referenced by that scene) into a different folder, while that scene is open, the editor crashes.

```
Godot Engine v4.0.beta.custom_build.1fa8b3dd4 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GT 710
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:76)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:100)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (1fa8b3dd420301dd5c2ad99b6bead6cffe1d4995)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7f1d0537aa00] (??:0)
[2] ./godot/bin/godot.linuxbsd.editor.dev.x86_64(__dynamic_cast+0x2d) [0x777e1fd] (??:?)
[3] Node3D* Object::cast_to<Node3D>(Object*) (./godot/./core/object/object.h:738 (discriminator 1))
[4] Node3DEditor::_request_gizmo(Object*) (./godot/editor/plugins/node_3d_editor_plugin.cpp:7362)
[5] void call_with_variant_args_helper<__UnexistingClass, Object*, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Object*), Variant const**, Callable::CallError&, IndexSequence<0ul>) (./godot/./core/variant/binder_common.h:267 (discriminator 4))
[6] void call_with_variant_args_dv<__UnexistingClass, Object*>(__UnexistingClass*, void (__UnexistingClass::*)(Object*), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (./godot/./core/variant/binder_common.h:410)
[7] MethodBindT<Object*>::call(Object*, Variant const**, int, Callable::CallError&) (./godot/./core/object/method_bind.h:320)
[8] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (./godot/core/object/object.cpp:733 (discriminator 2))
[9] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (./godot/core/variant/callable.cpp:62)
[10] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (./godot/core/object/message_queue.cpp:230)
[11] MessageQueue::flush() (./godot/core/object/message_queue.cpp:277)
[12] SceneTree::physics_process(double) (./godot/scene/main/scene_tree.cpp:432)
[13] Main::iteration() (./godot/main/main.cpp:3140)
[14] OS_LinuxBSD::run() (./godot/platform/linuxbsd/os_linuxbsd.cpp:776)
[15] ./godot/bin/godot.linuxbsd.editor.dev.x86_64(main+0x19b) [0x25c8fb1] (./godot/platform/linuxbsd/godot_linuxbsd.cpp:75)
[16] /usr/lib/libc.so.6(+0x23290) [0x7f1d05365290] (??:0)
[17] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f1d0536534a] (??:0)
[18] ./godot/bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x25c8d55] (/build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:117)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

### Steps to reproduce

1. Open the project, containing a MeshInstance3D .tscn file referencing a .gdshader file and an empty folder.
2. Open scene.tscn if it is not opened automatically.
3. Select scene.tscn and new_shader.gdshader in the FileSystem dock.
4. Drag both files to the folder. Editor should crash.
5. If editor does not crash: save the scene, then move both files out of the folder into the root, and editor should crash.

### Minimal reproduction project

[Project.zip](https://github.com/godotengine/godot/files/9886412/Project.zip)

**Comment by Tuckertcs** [comment]
Not sure if it's caused by the same bug, or just a similar issue, but I noticed renaming a folder containing scripts also caused Godot to crash.

**Comment by Mikeysax** [comment]
Same, renaming folders crashes the editor. Godot 4 beta 4

**Comment by KoBeWi** [comment]
Can't reproduce in cd491c6

> If editor does not crash: save the scene, then move both files out of the folder into the root, and editor should crash.
Minimal reproduction project

Does not crash either.

**Comment by henriquelalves** [comment]
For me, any file refactoring on Godot 4.0 (any beta) often crashes the editor (renaming folder, moving folders, renaming scripts, etc.).  I'm not sure what causes it exactly, so I can't make an easily reproducible project; but I tend to believe it has something to do with opened scenes in the editor that have a dependency with the files being refactored (e.g. if you have a scene opened that depends on a resource you are moving from a folder to another)

**Comment by KoBeWi** [comment]
^
This should be fixed in beta 9.

**Comment by reduz** [comment]
Ping to check if this was effectively fixed

**Comment by SaracenOne** [comment]
I checked this, and it appears that the initial issue was fixed. However, with @Mikeysax's issue, I've so far not been able to reproduce it either. If it's a problem, it should be opened as a new issue.

**Comment by KoBeWi** [comment]
@dzil123 @Mikeysax Can any of you still reproduce the crash in rc2?

No matter what I try, it doesn't crash for me. I wonder if it's system-specific 🤔

**Comment by dzil123** [comment]
I cannot reproduce a crash with my original issue.
