### ISSUE TITLE
.png's not importing properly

### ISSUE THREAD

**Issue by noxhy** [godotengine/godot#69369]
### Godot version

4.0.beta6

### System information

Windows 10

### Issue description

I am trying to put a spritesheet into my game however, the image simply wont be imported at all, It doesn't show up on the Inspector upon being clicked nor is it usable for any sprite.

### Steps to reproduce

Drag image in, it picks and chooses what images it wants to work.

### Minimal reproduction project

[Image Bug.zip](https://github.com/godotengine/godot/files/10127241/Image.Bug.zip)

**Comment by MGilleronFJ** [comment]
The project you linked does not contain any PNG, and does not even contain any Godot project file. It can't be opened as a project.
I tried importing a PNG in a new project and it works. Hence why you need to provide not only a valid project but also the PNG you are trying to import, because there might be something special in it.

**Comment by noxhy** [comment]
Odd... I just edited the post. See if that helps

**Comment by noxhy** [comment]
I don't know what's wrong, there seems to be nothing wrong for the image to not be loaded

**Comment by noxhy** [comment]
![image](https://user-images.githubusercontent.com/58011428/206071462-cb0d0bd0-c3e9-4cdc-883f-98c6bd8949e2.png)
i especially do not get what this error means, this is a png not a webp

**Comment by Zylann** [comment]
I think Godot saves the imported data as webp

**Comment by noxhy** [comment]
That's exactly the stem of my confusion

**Comment by noxhy** [comment]
Another person tried the project and it worked fine for them, does Godot have some sort of grudge against my computer?

**Comment by TomSpalango** [comment]
I was able to open the project and darnboy.png acted as expected.  The file gfDanceTitle.png did not work.

SOLVED this by deleting the gdDanceTitle.**import** file in the file system.  Godot re-imported the asset and then it behaved as expected.

**Comment by noxhy** [comment]
My Godot crashes annoyingly enough, and the issue doesn't get solved.

**Comment by TomSpalango** [comment]
Not that it will necessarily matter, but I see you are on beta6.  Have you tried this on beta7?

**Comment by noxhy** [comment]
https://user-images.githubusercontent.com/58011428/206092709-f2934007-9609-4ada-9c3d-e05e1b5ad013.mp4

**Comment by TomSpalango** [comment]
I understand the frustration.  Here is a video of my experience.  I don't have the expertise to be able to offer a solution.  The PNG works fine on my computer.

https://user-images.githubusercontent.com/4755780/206093999-6ad0250d-c078-49b3-93f4-aa411bdb6d19.mp4

**Comment by akien-mga** [comment]
I could reproduce the issue, it seems there's corrupted data in the `.godot` folder. Close Godot, delete the `.godot` folder, and open Godot. It should solve it.

**Comment by Calinou** [comment]
I've tried to remove `.godot` in another project then reopen the editor, but the issue still occurs on 4.0.beta 55dae3017 (Linux).

**Comment by noxhy** [comment]
![image](https://user-images.githubusercontent.com/58011428/206292298-c7d6ce21-2382-4805-830b-16eae4771035.png)
update: it didn't crash but the issue wasn't solved

**Comment by noxhy** [comment]
Issue still remains in beta 8

**Comment by noxhy** [comment]
![image](https://user-images.githubusercontent.com/58011428/207203429-4b5e8766-005e-49ad-8400-6dd354b4ba23.png)
Another update: now darnboy doesn't work

**Comment by noxhy** [comment]
darnboy works again now, i did both strategies of removing `.godot/` and the `gfDanceTitle.png.import` file
to no avail, gfDanceTitle still wont work

**Comment by noxhy** [comment]
![image](https://user-images.githubusercontent.com/58011428/207504663-5bc5a450-c1f3-4173-9c47-57077111c675.png)
Perhaps it's a memory issue, the files on the left work with less than 1.1 MB
The ones on the right are having issues

**Comment by noxhy** [comment]
![image](https://user-images.githubusercontent.com/58011428/207506132-37cad612-929f-4c92-910b-bf9f0b8f9d0d.png)
actually, maybe not

**Comment by noxhy** [comment]
issue remains in beta 9

**Comment by noxhy** [comment]
![image](https://user-images.githubusercontent.com/58011428/208560212-45ef3668-8349-4786-a71a-e99171a907a4.png)
this is what the console looks like when i first boot up godot

**Comment by noxhy** [comment]
it seems to be the bigger my project gets, the less files work

**Comment by Zireael07** [comment]
How big is your project? How much RAM do you have? (That first error in the screen looks like Godot is failing to allocate memory...)

**Comment by noxhy** [comment]
The minimal reproduction project is 9k KB and have 16 gigs of RAM

**Comment by noxhy** [comment]
the project i am working on currently is 50.9 MB

**Comment by noxhy** [comment]
Issue still applies in beta 10

**Comment by noxhy** [comment]
Alright strangely enough, updating my video driver fixed it.
