### ISSUE TITLE
erase_cell() does not erase scene tiles cells

### ISSUE THREAD

**Issue by YaikaRace** [godotengine/godot#69596]
### Godot version

4.0.beta7

### System information

Windows 10

### Issue description

When using erase_cell() on a cell in which the TileMap set a scene from a scene collection the cell is not erased, and when this tile is moved it is impossible to put another tile in the same cell again.

### Steps to reproduce

1. Create a scene and put some sprite
2. Save the scene and put it in a scene collection in a tilemap.
3. use set_cel() to put the scene in a cell on runtime
4. use erase_cell() to delete that scene tile on runtime

### Minimal reproduction project

[Scene Collection issue.zip](https://github.com/godotengine/godot/files/10152732/Scene.Collection.issue.zip)

**Comment by KoBeWi** [comment]
The tile IS erased, it just doesn't remove the created scene instance (and you can't recreate it, because it's cached). See #67330
I think we lack a method to force re-instancing new tile.

**Comment by YaikaRace** [comment]
There is some way to clear that cache or something similar to be able to re-instantiate a scene in the same cell where was freed a previous scene?

**Comment by codingvessel** [comment]
So, is there any possibility in gdscript to remove the actual scene from the tilemap?

**Comment by KoBeWi** [comment]
No. You can `queue_free()` the node, but it will still sit in the cache. The cache can be cleared by modifying the TileSet resource. You could try doing some dummy operation on the tileset.

This issue was discussed on the chat and it was decided that `set_cell()` should remove (and free) the cached scene on that tile. Someone has to implement it (I tried and ran into some problems).

**Comment by YaikaRace** [comment]
I tried doing a dummy operation in the Tileset, but that caused the entire cache to be cleaned and all instantiated scenes to be re-instantiated and duplicated.

**Comment by Sch1nken** [comment]
Okay I got a first version running locally. I fixed a crash and so far it seems stable.

The only issue right now is that when a new scene is instantiated the Nodes name swaps between Node and @Node@<Number> when I set/clear cells repeatedly.

**Comment by aspersum** [comment]
I'm running into the same issue right now. Clearing the cache is not really a good workaround for my use case, as my scenes need to remember their state and this resets them completely.

I'm sorry to nag, but is this planned for 4.1 ? This seems like a pretty major oversight.

**Comment by TheKassaK** [comment]
It is not fully fixed on 4.2.

Now the instance is removed when we EraseCell(), but we cant add another tile on the same position.

**Comment by KoBeWi** [comment]
@TheKassaK Can't reproduce. Please open a new issue with a minimal reproduction project.

**Comment by TheKassaK** [comment]
> @TheKassaK Can't reproduce. Please open a new issue with a minimal reproduction project.

Hey, the issue is here : https://github.com/godotengine/godot/issues/82597

**Comment by VelluVu** [comment]
Constantly having problems when trying to make resource gather RTS type game with Godot 4 tilemap. First the cutting tile based physical colliders from navigation polygon, but now the erasing tile leaves the collider in ex tile position, and my rebake algorithm breaks because left collider is counted into the clipping polygon.

**Comment by AThousandShips** [comment]
As already said above, please open a new issue, after searching for existing ones 🙂 this issue has been closed and isn't the same as your problem

**Comment by johanjavier123** [comment]
When I use "erase cell" it does not erase any tiles, but I can place tiles and clean the layer
