### ISSUE TITLE
`Curve3D`: `sample_baked_with_rotation()` returns error, while otherwise behaving as expected

### ISSUE THREAD

**Issue by CousCous4** [godotengine/godot#70047]
### Godot version

4.0-beta8

### System information

Windows 11

### Issue description

Whenever I call the `sample_baked_with_rotation()` function on a `Curve3D`, the function seems to work as intended, however also throws out the error below:

    E 0:00:02:0712   _ready: The target vector can't be zero.
      <C++ Error>    Condition "p_target.is_zero_approx()" is true. Returning: Basis()
      <C++ Source>   core/math/basis.cpp:1041 @ looking_at()
      <Stack Trace>  World.gd:21 @ _ready()

Note that in my project `sample_baked_with_rotation()` is being called in `_ready()` on World node for demonstration as per the Steps to reproduce.

I'm using what I think are sensible Curve3Ds, and I'm passing it reasonable `offset` values, for example in the below Steps to reproduce.

Also a problem in 4.0-beta7.

### Steps to reproduce

    var curve = Curve3D.new()
    curve.add_point(Vector3(0,0,0))
    curve.add_point(Vector3(10000,0,0))
    var offset = curve.get_closest_offset(Vector3(5000,0,0))
    print(curve.sample_baked_with_rotation(offset))
    # returns error

### Minimal reproduction project

N/A

**Comment by AndreSacilotto** [comment]
The error is not on `sample_baked_with_rotation` or `get_closest_offset`. Is on `_bake` a internal function.
And it as nothing to do with big/small numbers or the number 0.
```gdscript
var curve = Curve3D.new()
curve.add_point(Vector3(1,2,3), Vector3.ZERO, Vector3.ZERO)
curve.add_point(Vector3(3,2,1), Vector3.ZERO, Vector3.ZERO)
curve.sample_baked(50)
```
The above will give you the same error. 

The error occurs when because of the out param of the first point is zero, this will not give you a error:
```gdscript
var curve = Curve3D.new()
curve.add_point(Vector3(1,2,3), Vector3.ZERO, Vector3.LEFT)
curve.add_point(Vector3(3,2,1), Vector3.ZERO, Vector3.ZERO)
curve.sample_baked(50)
```

TL;RD - The error occurs when the curve is linear.

**Comment by CousCous4** [comment]
Thank you for looking into it! I tested again by setting a non zero value for the out param of all of my curves, and agree that I'm not getting an error.

Does this mean that the error is intended behaviour, and I should just be specifying a start out param for every curve? Or should the error not appear?

**Comment by xiongyaohua** [comment]
@CousCous4 sorry for the late reply, I didn't check email recent days. I think could have been fixed by https://github.com/godotengine/godot/pull/69726. Can you confirm it?

**Comment by AndreSacilotto** [comment]
Tested on 4.0-beta9, it's not throwing the error anymore, and seems to be working correct.
I think the issue can be closed @Chaosus.

**Comment by AndrewBuck** [comment]
I appear to be still getting this error on Godot v4.0.2.stable.official [7a0977ce2]

I have the following code in a larger function -- I am calculating a path using the nav server and then adding the points from the returned nav path to a Curve3D.  Using the original commented out line of newCurve.add_point(pos) causes the get_baked_length call to throw the "The target vector can't be zero." error.  If I comment that out as I have and add a phony value to the "out" vector the error does not get thrown.

```
	#TODO: Adding points 1 at a time like this probably causes a malloc at every add call.  Determine if there is a way to add all the points in bulk with a single call.
	for pos in path:
		#TODO: Return to the commented out line which just adds the "pos" but does not set the "in" and "out" vectors to the curve.  This is to work around the following bug:
		# https://github.com/godotengine/godot/issues/70047
#		newCurve.add_point(pos)
		newCurve.add_point(pos, Vector3.ZERO, Vector3(0.001, 0.001, 0.001))
	
	# Store the total length in case we need it, but mainly just force the baking to happen now
	# so that the maximum amount of work is done in this function.  Keeping the work here means
	# if this function is spawned in a background thread, then we push as much as possible to the background.
	#TODO: This next line is sometimes throwing an error "The target vector can't be zero."  I think this is simply a bug in the "bake" function.  See the TODO on the add_point call a few lines above.
	# https://github.com/godotengine/godot/issues/70047
	totalLength = newCurve.get_baked_length()
```

**Comment by AndrewBuck** [comment]
Here is the full function call so you can see the above snippet in its full context.  `startVector` and `endVector` are the start/end points of the nav path we are calling.  The purpose of the function is to be called from inside a thread so I can move the nav calculations to their own thread.  I seem to get the error whether I call via a thread or call directly (although when calling through a thread the stack trace gets truncated.

```
func update(startVector : Vector3, destVector : Vector3, closeEnough : float = 5.0):
	#TODO: Move this check into a checkIfUpdateShouldHappen() function so we don't spin up a thread just to check if we
	#need to update.  Care needs to be taken to avoid the check being called twice though if called through that code path.
	var closeEnoughSquared : float = closeEnough*closeEnough
	if curve != null:
		if cachedDestVector.distance_squared_to(destVector) < closeEnoughSquared:
			return
	
	cachedDestVector = destVector
	
	var queryParams = NavigationPathQueryParameters3D.new()
	var queryResult = NavigationPathQueryResult3D.new()
	
	# Set the parameters for the navigation calculation that the nav server will do.
	queryParams.map = owner.get_world_3d().navigation_map
	queryParams.start_position = startVector
	queryParams.target_position = destVector
	queryParams.metadata_flags = NavigationPathQueryParameters3D.PATH_METADATA_INCLUDE_NONE
#	queryParams.path_postprocessing = NavigationPathQueryParameters3D.PATH_POSTPROCESSING_EDGECENTERED
	
	NavigationServer3D.query_path(queryParams, queryResult)
	var path : PackedVector3Array = queryResult.path
	
	var newCurve : Curve3D = Curve3D.new()
	newCurve.bake_interval = closeEnough
	
	#TODO: Adding points 1 at a time like this probably causes a malloc at every add call.  Determine if there is a way to add all the points in bulk with a single call.
	for pos in path:
		#TODO: Return to the commented out line which just adds the "pos" but does not set the "in" and "out" vectors to the curve.  This is to work around the following bug:
		# https://github.com/godotengine/godot/issues/70047
#		newCurve.add_point(pos)
		newCurve.add_point(pos, Vector3.ZERO, Vector3(0.001, 0.001, 0.001))
	
	# Store the total length in case we need it, but mainly just force the baking to happen now
	# so that the maximum amount of work is done in this function.  Keeping the work here means
	# if this function is spawned in a background thread, then we push as much as possible to the background.
	#TODO: This next line is sometimes throwing an error "The target vector can't be zero."  I think this is simply a bug in the "bake" function.  See the TODO on the add_point call a few lines above.
	# https://github.com/godotengine/godot/issues/70047
	totalLength = newCurve.get_baked_length()
	
	completedIndex = 0
	
	curve = newCurve
	if debugPath3D != null:
		#TODO: This should prbably be done with call_deferred or something like that to ensure thread safety since the main thread is potentially using the DebugPath3D.
		debugPath3D.curve = curve
```

**Comment by LasseSchnepel** [comment]
I'm experiencing this with Godot 4.2.2 stable (mono) as well. @akien-mga should this ticket be re-opened?
