### ISSUE TITLE
Godot 4 b8's UI-Ruler & grid getting corrupted and becomes inaccurate.

### ISSUE THREAD

**Issue by Krater107a** [godotengine/godot#70186]
### Godot version

Godot 4, beta 8 (.net c# version)

### System information

Windows 11 21H2

### Issue description

When mapping out a simple "level" in my proto-type 2d platformer, have noticed the grid becomes mis-aligned compared to the "2nd" grid provided by the tilemap. The further away from scene origin tiles are placed the greater the mis-alignment is.

### Steps to reproduce

Create a new project in godot 4 b8.
Create a new 2D scene, name it what ever.
Click on "..." configure snap.
Change grid step from it's default to some other number (ex 4px 4px).
Save the empty scene.
Using your operating system, navigate to <testproj>/.godot/editor
Using a text editor open up your scene's "editstate" config file.
Observe under section 2D={} "grid_step": Vector2(4.01, 4.01). -- grid_step is no longer a whole number but now a decimal.
Go back to godot.
Observe that your scene's ruler and grid are now more and more inaccurate the further from origin you go. Also notice your UI-Ruler now has a decimal place instead of whole numbers as markers.
This becomes very evident when placing tiles, a huge mis-alignment begins to occur.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by Krater107a** [comment]
Contents of file (Godot 3.5.1.stable.mono) C:\Users\Krater\AppData\Roaming\Godot\projects\GridTest-84bcc8e1f92452940dceff8b8d91675c\testgrid.tscn-editstate-28339fdbe73c95444f583f5d0f2bf3a8

Before Altering Configure Snap -> Grid Step (and then saving the scene): "grid_step": Vector2( 8, 8 ),
After Altering Configure Snap -> Grid Step (and then saving the scene): "grid_step": Vector2( 4, 4 ),

-- tldr: No this doesn't seem to be happening in Godot 3.5.1.

The "grid_step": Vector2 field remains decimal free. When the decimal is introduced the alignment of everything in the effected scene seems to be thrown off.

**Comment by Calinou** [comment]
This was confirmed in https://www.reddit.com/r/godot/comments/zpnfpg/is_this_just_how_godot_handles_2d_objects_in_the/j0unmvp/.

**Comment by kleonc** [comment]
Regression from #65101, now `Range` is rounding to closest `k * step + min` instead of `k * step`.

And `min` for the grid-step-SpinBoxes in the snap settings dialog is `0.01`:
https://github.com/godotengine/godot/blob/2a04b18d37de6c6e621db5a9dfd1cd0da5ccb015/editor/plugins/canvas_item_editor_plugin.cpp#L137-L153

**Comment by KoBeWi** [comment]
CC @MrPhnix

**Comment by MrPhnix** [comment]
Got it, I'll check it out tomorrow. 👍

**Comment by fractalcounty** [comment]
I suspect that [#67401](https://github.com/godotengine/godot/issues/67401), which was only ever partially fixed, could be partially responsible for this issue as there are still major kerning issues in b9 that persist depending on how far the text is from the scene origin. 


![208597250-39345ec4-ef56-43c5-98c5-d0538cfc4418](https://user-images.githubusercontent.com/121070110/208753887-e28a4a78-d0f0-4c60-81e6-eda10f7ef0a4.png)

**Comment by MrPhnix** [comment]
I double-checked the math that defines the value of the range, and it seems to be correct even with a small minimum value (0.01), I will look at the grid code.

**Comment by MrPhnix** [comment]
After looking at the SpinBoxes code, inaccuracies are fixed by setting the minimum for the grid step to zero, but if the user types a zero, it freezes the editor.

So, I tried to check the value before setting it in the grid step.
But it only checks when you click on the "configure snap" button and not when you click on the OK button in the "configure snap" window, so you can still enter zero.

Moreover, as the minimum value of the min step is 0.01, it is not displayed in the SpinBoxes of the "configure snap" window.

![grid bug fix](https://user-images.githubusercontent.com/76911907/208973388-ae6e5c94-e90e-4ad7-9a5c-d560bd6b14e9.png)

P.S. I don't know what to do about issue #67401.

**Comment by MrPhnix** [comment]
Moreover, as the minimum value of the min step is 0.01, it is not displayed correctly in the SpinBoxes of the "configure snap" window, and the grid is hard to see on the screen since it is so small.

Is the minimum step value of 0.01 important?
Can we replace it with 1 since it doesn't really matter to go below 1px, and even with a step size of 0.01, the nodes, like the points in Polygon2D, will still move as if there was a 1px grid.

**Comment by KoBeWi** [comment]
The SpinBox's step is 1, so 1 makes sense as minimum value.

**Comment by MrPhnix** [comment]
I have made a pull request (#70428) to fix this issue.

**Comment by roalyr** [comment]
Please check 3.x (https://github.com/godotengine/godot/blob/3.x/editor/plugins/canvas_item_editor_plugin.cpp)
it seems to be there as well.
I have my fork synchronized with 3.x as of 14th of December, and I have just noticed this issue there.

**Comment by kleonc** [comment]
@roalyr Indeed, #65101 was cherry-picked to 3.x (for 3.6). I've marked #70428 to be cherry-picked to 3.x as well.

**Comment by SavoVuksan** [comment]
I am not sure if this is the same issue but I notice some misalignment happening when using the new tilemap in Godot `4.10beta`. Either the snapping grid starts to slide or the tilemap grid but I am not sure which of both is sliding. 
![image](https://user-images.githubusercontent.com/12395493/210271836-65ba74e9-adee-45ef-990b-04568a12cd89.png)
The video demonstrates the issue a bit better.

[Grid Misalignment Issue Video](https://user-images.githubusercontent.com/12395493/210273573-bdc69458-3dcf-4548-afb5-6d1d8fabba91.mp4)

**Comment by KoBeWi** [comment]
It's the same issue. TileMap's grid is displaying correctly.

**Comment by iamjoeysox** [comment]
Would this be the reason I am observing an odd 1-2px gap between my character body and the floor? This was driving me absolutely mad, so glad I found this issue haha.

**Comment by Pizza-Script** [comment]
Just wanted to mention this here just in case someone else encounters this.
This misaligned grid is now fixed in 4.0 beta 11.

But if you are opening a project from 4.0 beta 10 into beta 11, the grid would still be misaligned. 
To fix this, you would just have to re-open the "Configure Snap" dialogue in the Snapping Options.
Upon pressing OK, it should "recalculate" the grid and it should now be aligned.

![grid](https://user-images.githubusercontent.com/49001332/211637819-d992e6c3-ce33-4206-bc55-fe90252ed337.gif)

**Comment by iamjoeysox** [comment]
> Just wanted to mention this here just in case someone else encounters this. This misaligned grid is now fixed in 4.0 beta 11.
> 
> But if you are opening a project from 4.0 beta 10 into beta 11, the grid would still be misaligned. To fix this, you would just have to re-open the "Configure Snap" dialogue in the Snapping Options. Upon pressing OK, it should "recalculate" the grid and it should now be aligned.
> 
> ![grid](https://user-images.githubusercontent.com/49001332/211637819-d992e6c3-ce33-4206-bc55-fe90252ed337.gif)

Thanks a ton for this, was super confused why the update didn't fix anything for me haha.

**Comment by nazgum** [comment]
It seems like this is a regression in godot 3.6

The grid displays fine in godot 3.5 if i open my project back up with it, but in godot 3.6, when zooming in the grid becomes inaccurate compared to the tilemap.  snapping still works fine and places things correctly, it seems like its just a visual bug.

heres short video showing the grid lines becoming inaccurate the more you zoom in:
[grid-inaccurate-zoomed-godot-3.6.webm](https://github.com/user-attachments/assets/b8d92367-1197-45a7-a6df-e932c4ede355)

(am on fedora linux with godot 3.6)

**Comment by AThousandShips** [comment]
Please open a dedicated issue for 3.x to track this

**Comment by nazgum** [comment]
Sure, added a new issue for this here - godotengine/godot#98466

Cheers,
