### ISSUE TITLE
GPUParticles2D color attribute not working in GLES3 (compatibility)

### ISSUE THREAD

**Issue by JonqsGames** [godotengine/godot#72847]
### Godot version

4.0 beta 17

### System information

Windows 10

### Issue description

Setting the color attribute in ParticleProcessMaterial for GPUParticles2D does not work with compatibility renderer
(works with forward+)

### Steps to reproduce

Set renderer to compatibility
Create a GPUParticles2D
Add ParticleProcessMaterial and set Color attribute (creating a particle shader and setting the `COLOR` is the same)

### Minimal reproduction project

[Particle2DColor.zip](https://github.com/godotengine/godot/files/10678236/Particle2DColor.zip)

**Comment by clayjohn** [comment]
This may have been fixed by https://github.com/godotengine/godot/pull/72681 which was merged shortly after Beta 17. At the time I made https://github.com/godotengine/godot/pull/72681 I tested both MultiMeshInstance and Particles and they appeared to be working fine. 

But, in case the issue is specific to your project, could you please upload an MRP showing the issue?

**Comment by JonqsGames** [comment]
Tested on latest master too and the color is still not applied.
I just added a MRP to the issue.
