### ISSUE TITLE
Black screen on Android editor on devices that don't fully support Vulkan

### ISSUE THREAD

**Issue by TYA017** [godotengine/godot#72888]
### Godot version

Godot engine 3 Android(Beta)

### System information

Android 12, ColorOS 12.1, Mediatek MT6765 Helio G35 (12 nm),PowerVR GE8320

### Issue description

When creating a new project, attempting to edit it brings me to a blank black screen. 
Sometimes happens in godot editor 4 beta as well

### Steps to reproduce

Open godot
Create a new project
Attempt to edit the project

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
What version are you testing on. Your first line says Godot 3 beta, but later you say Godot editor 4 beta.

For reference the latest Godot 3 release is 3.5.1 (not a beta) and the latest Godot 4 release is Godot 4 RC1 (also not a beta)

**Comment by YuriSizov** [comment]
> For reference the latest Godot 3 release is 3.5.1 (not a beta) and the latest Godot 4 release is Godot 4 RC1 (also not a beta)

I think this is in reference to the beta release of the editor for Android that we published yesterday.

**Comment by TYA017** [comment]
> What version are you testing on. Your first line says Godot 3 beta, but later you say Godot editor 4 beta.
> 
> For reference the latest Godot 3 release is 3.5.1 (not a beta) and the latest Godot 4 release is Godot 4 RC1 (also not a beta)

Its called a Beta in the play store
Im testing on android

**Comment by m4gr3d** [comment]
@TYA017 Does the issue still occur in the latest version of the Android editor?

**Comment by TYA017** [comment]
> @TYA017 Does the issue still occur in the latest version of the Android editor?

**Comment by TYA017** [comment]
> @TYA017 Does the issue still occur in the latest version of the Android editor?

**Comment by TYA017** [comment]
> @TYA017 Does the issue still occur in the latest version of the Android editor?
Now instead of the blank screen, it is just the Godot icon. Seems to be fixed though, will do further testing

**Comment by AThousandShips** [comment]
Does this still occur in a recent version?
