### ISSUE TITLE
IK preview does not work

### ISSUE THREAD

**Issue by tamagos** [godotengine/godot#72945]
### Godot version

Godot_v4.0-rc1_mono_win64.zip

### System information

Windows 10

### Issue description

in editor can not preview the IK of skeletonIK3D,
worked in December betas 

### Steps to reproduce

add skeletonIK3D node
setup
click play IK
click target node3D
IK preview mode no longer active so  can not see results of moving it

### Minimal reproduction project

N/A

**Comment by dszhblx** [comment]
Although SkeletonIK3D is not working right now, I also encountered this problem

**Comment by lobziq** [comment]
Can confirm, switching from SkeletonIK3D to any other node results IK solver stop playing (in editor).

**Comment by lobziq** [comment]
@tamagos @dszhblx ive slapped a quickfix as editor tool, attach this to your SkeletonIK node and click "playing" checkbox in properties

```
@tool
extends SkeletonIK3D

@export var playing: bool = false


func _process(delta):
	if not Engine.is_editor_hint():
		return
		
	if self.playing and not self.is_running():
		self.start()

	if not self.playing and self.is_running():
		self.stop()
```

**Comment by dszhblx** [comment]
@Calinou Since you guys decided that Godot 4.0 includes SkeletonIK3D which works fine, this little bug should also be fixed in Godot 4.0.Thanks!

**Comment by RNubla** [comment]
This issue still persist in 4.0😢 but hopefully this gets fixed on the next update 🤞

**Comment by DillonSteyl** [comment]
@lyuma 
> I'm surprised this regressed since I don't think there's been any work done on the IK node, but I am looking into issues related to SkeletonIK3D so I'll include this in my testing.

In case you're still looking at SkeletonIK3D issues, I just had a brief look into this.
```cs
void SkeletonIK3DEditorPlugin::edit(Object *p_object) {
	if (p_object != skeleton_ik) {
		if (skeleton_ik) {
			play_btn->set_pressed(false);
			_play();
		}
	}
```
If the `edit` method is called on the SkeletonIK editor plugin with a `nullptr` as the object, the SkeletonIK is disabled. 
If this particular code is removed, the issue goes away - however this hasn't been touched in years. So it almost feels like this was originally the intended behaviour?

It does look like there was some recent work done in `editor_node.cpp`. In this particular case, the method is called by the `hide_unused_editor` method:
```cs
void EditorNode::hide_unused_editors(const Object *p_editing_owner) {
	if (p_editing_owner) {
		const ObjectID id = p_editing_owner->get_instance_id();
		for (EditorPlugin *plugin : active_plugins[id]) {
			_plugin_over_edit(plugin, nullptr);  // <-- this is it
		}
		active_plugins.erase(id);
```
I'm not sure if its as simple as removing the first part of the `edit` method on the SkeletonIK editor plugin - that seems to fix the issue, but I'm not sure if it would have unintended side effects.

**Comment by lyuma** [comment]
Here's another workaround you can use today (kind of the Blender style approach, like how you'd do pose mode while editing a mesh)

![two nodes selected, play IK is enabled in the toolbar](https://github.com/godotengine/godot/assets/39946030/221008fa-5578-4058-bb7b-b1a923462fb2)
basically select two nodes, and then you get to keep the toolbar item for the SkeletonIK3D and it keeps updating.
We could theoretically mention this in the documentation. unfortunately it's not so obvious. I'll think what to do.

**Comment by dszhblx** [comment]
SkeletonIK3D woks in 4.1 beta3，but this issuestill persist
@lyuma

**Comment by tamagos** [comment]
any updates, its hard to recommend a engine when feature regression are ignored

**Comment by akien-mga** [comment]
@tamagos Please don't bump issues to make demands like this. You already clarified that the issue is still valid a week ago. Most Godot contributors are volunteers and work on their free time, and that includes all contributors knowledgeable about IK.

**Comment by tamagos** [comment]
@akien-mga 
ok but I did not bump it a week ago, I have not posted since I created this 6 months ago

**Comment by akien-mga** [comment]
My bad, I misread the handle of the user who bumped it last.

**Comment by nickbo7** [comment]
I was able to manipulate my Marker3D positions while IK was updating by pressing the relevant hotkey. 'Q', 'W', 'E', 'R'

Hope that helps someone.

**Comment by wjagodfrey** [comment]
> @tamagos @dszhblx ive slapped a quickfix as editor tool, attach this to your SkeletonIK node and click "playing" checkbox in properties
> 
> ```gdscript
> @tool
> extends SkeletonIK3D
> 
> @export var playing: bool = false
> 
> 
> func _process(delta):
> 	if not Engine.is_editor_hint():
> 		return
> 		
> 	if self.playing and not self.is_running():
> 		self.start()
> 
> 	if not self.playing and self.is_running():
> 		self.stop()
> ```

This script no longer keeps IK running when the IK node is deselected. Not sure if it ever did. Sadly makes it no better than the `Play IK` button.

**Comment by andzejsp** [comment]
Why does it have to be so difficult? Press and hold CTRL and do the other things? Why cant you press play, make checkbox to set it active? Still persists in godot 4.1.1

**Comment by warriormaster12** [comment]
![image](https://github.com/godotengine/godot/assets/33091666/7ede9ed1-a5c5-4dd0-834b-8e93caf42e41)

@andzejsp The pr should hopefully be merged soon so this won't be an issue anymore. 

https://github.com/godotengine/godot/pull/82391

Not sure if it will be cherry-picked for 4.1

**Comment by andzejsp** [comment]
> ![image](https://user-images.githubusercontent.com/33091666/271245970-7ede9ed1-a5c5-4dd0-834b-8e93caf42e41.png)
> 
> @andzejsp The pr should hopefully be merged soon so this won't be an issue anymore.
> 
> #82391
> 
> Not sure if it will be cherry-picked for 4.1

i hope its fixed in 4.2 or the next stable 4.xx version. No problems. Just difficult to follow tutorials and the feature you see in older versions is missing in the newer ones. Keep up the good work! #DEATH TO UNITY

**Comment by akien-mga** [comment]
@andzejsp I edited your last comment to remove a statement which clear broke the Godot Code of Conduct. Please keep such things out of Godot community platforms, this is not welcome.

**Comment by tamagos** [comment]
confirming IK preview works correctly on:
Godot_v4.2-dev6_mono_win64

**Comment by GeorgeS2019** [comment]
@tamagos 
Could you share a basic skeleton3DIK demo that show the IK preview works

**Comment by Wallaguiar** [comment]
SkeletonIK3D "play IK" doesn't stay in played state when selecting other nodes,
![Captura de Tela (2770)](https://github.com/godotengine/godot/assets/145673147/29e475d6-e928-47e5-baff-3245e54d3528)
![Captura de Tela (2769)](https://github.com/godotengine/godot/assets/145673147/33890425-3e26-4f19-a134-1c396acf667b)
![Captura de Tela (2772)](https://github.com/godotengine/godot/assets/145673147/b839c35e-fe27-4bdf-a927-890a72f3493d)
![Captura de Tela (2774)](https://github.com/godotengine/godot/assets/145673147/0d33f85a-b922-42e3-8497-f1d99c4f10f8)

**Comment by AstroFeline** [comment]
Issue still persists in Godot 4.3_rc2 (at least in mono version)
Reproduce: Set a Skeleton3DIK, put a Node3D target, play IK (works)
Save, close scene, reopen
Now it wont play anymore in editor.
