### ISSUE TITLE
@warning-ignore doesn't work for conditions statements

### ISSUE THREAD

**Issue by coelhucas** [godotengine/godot#73222]
### Godot version

4.0-rc1

### System information

MacOS

### Issue description

The `@warning_ignore` decorator doesn't work for condition lines. Is it expected to work only on statements?

```gdscript
@warning_ignore("some_warning")
var x: String = line_with_warning() # works

@warning_ignore("some_warning")
if line_with_warning(): # warning persist
  pass
```

### Steps to reproduce

Given as example the usage of a static function on an instance:

```gdscript
class_name MyClass
extends Node

static func get_component_name() -> String:
  return "MyComponent"
```

And `_c` being an instance of `MyClass`

![image](https://user-images.githubusercontent.com/28108272/218468741-f6263eb8-0ec1-451a-97e3-258572799be7.png)

### Minimal reproduction project

N/A

**Comment by fisheye36** [comment]
Same problem in `4.0-rc2`.

**Comment by manokara** [comment]
From what I've skimmed in the parser and analyzer code, it seems that function calls on an if node are not properly resolved (the `ignored_warnings` list is not passed down). Someone familiar with the GDScript codebase might have a better idea.

**Comment by HenryClones** [comment]
> From what I've skimmed in the parser and analyzer code, it seems that function calls on an if node are not properly resolved (the `ignored_warnings` list is not passed down). Someone familiar with the GDScript codebase might have a better idea.

Examining the code in the analyzer, the point where the `@warning_ignore` annotation is checked and the annotation is resolved, modifying the ignored warnings list is: https://github.com/godotengine/godot/blob/dfdda9629499271c447d4935b07e583650666600/modules/gdscript/gdscript_analyzer.cpp#L843-L854
in the resolve_class_member function. IF nodes are resolved in a case of `resolve_node`, which on line 1332 calls `resolve_if` defined on line 1830, which immediately afterwards (line 1831) calls `reduce_expression` defined on line 2190, handling conditions. At this time, the ignored warnings list is neither checked nor modified by some things that would need to be for the `@warning_ignore` annotation to work for conditions, since conditions are a type of expression. In this particular instance, `reduce_call`, defined on line 2685, does not check `@warning_ignore`.

Checking for warnings and ignoring them should be done on expressions as well since, as in this case, function calls (a type of expression) are generating warnings.

**Comment by Poobslag** [comment]
`@warning_ignore` also does not work for for statements, I assume this is the same bug.

```	
	var g := Vector2i(0, 0).x
	@warning_ignore("integer_division")
	for i in range(g / 2):
		pass
```

This code snippet produces an integer division warning, even though the `@warning_ignore` annotation should suppress it.

Let me know if I should open a separate issue for this, but it seemed like it probably share the same root cause.

**Comment by Deozaan** [comment]
I'm still experiencing this in v4.2.1.stable.official [b09f793f5]

Specifically, I still get a warning in the following scenario:

```
@warning_ignore("integer_division")
if (3 / 2) == 1:
	pass
```

From what I understand from #82276, this was supposed to be fixed by #83037.

**Comment by dalexeev** [comment]
* Fixed by #83037 for future 4.3.
