### ISSUE TITLE
Skeleton2D Modifications Throw Error and Warnings stating that bone index needs to be updated

### ISSUE THREAD

**Issue by SavoVuksan** [godotengine/godot#73247]
### Godot version

v4.0.rc1.mono.official [8843d9ad3]

### System information

Windows 10, Nvidia RTX 2080

### Issue description

I am using the Skeleton2D node with the modification stack to add IK bones but they seem to throw errors telling me that the target cache is out of date. But it seems that I cannot do anything against this issue since I don't have any control over the bone index or cache. 

Another issue is that the errors still get thrown even when I set the enabled flag of the ModificationStack to false.

Here is the error log of the reproduction project: 

![image](https://user-images.githubusercontent.com/12395493/218568826-5fc5aeef-c1af-43af-8f83-6bf11d3aa521.png)

### Steps to reproduce

Open provided project and start scene with F6. Debugger logs a lot of warnings and errors.

### Minimal reproduction project

[BugreportIK.zip](https://github.com/godotengine/godot/files/10726084/BugreportIK.zip)

**Comment by GeekzGamingz** [comment]
![image](https://github.com/godotengine/godot/assets/42735252/dd107469-300e-410f-9f41-230e1033e249)
Same issue.

**Comment by SaffronStreams** [comment]
Getting presumably the same errors for Fabrik IK setup in Godot 4.1.1
![image](https://github.com/godotengine/godot/assets/50481103/882cb4fb-e1bb-4fe2-b173-d9b9a957b60a)

**Comment by JeremyCarlsten** [comment]
![image](https://github.com/godotengine/godot/assets/2236570/89dd2808-71ae-410f-91e3-a0febb7a1cb2)
I'm also seeing this issue. Has anyone found any workarounds?

**Comment by Ughuuu** [comment]
Anyone knows what caused this? I know it used to work up to some version, so maybe we could find the PR that introduced this?

**Comment by SavoVuksan** [comment]
Yeah that would be a good idea to see what caused this but it could also be a side effect of some other change?

**Comment by XJustaguyX** [comment]
For me it also outputs "!is_inside_scene_tree is true" and disables the modifications completely. I have to remove and readd all the skeleton mods from scratch every time I start the engine. Very annoying, hope it is fixed soon.

**Comment by nelsonayamashita** [comment]
I had a bit of free time and tried to test the MRP with older Godot versions. The oldest Godot 4 build that was able to open the project was v4.0.alpha4.official [f47097973] (before that it was unable to load the MRP saying it was corrupted). **Even in that build, I had the same errors as the ones described in the issue.**

This leads me to believe the issue appeared in the transition from Godot 3 to Godot 4. I know this is not very informative since a lot of things changed between those versions, but it's where we should look into from now.

**Comment by IvanVuytsik** [comment]
So, the issue is still there in Godot 4.1. Are there any fixes for that?

**Comment by AThousandShips** [comment]
Can you rest in [4.2-beta3](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/)?

**Comment by IvanVuytsik** [comment]
> Can you rest in [4.2-beta3](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/)?

Just tested in 4.2 b3 - the bug is still there.

**Comment by SaffronStreams** [comment]
> Can you rest in [4.2-beta3](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/)?

Did a quick test and I get the same errors on a small test project

![image](https://github.com/godotengine/godot/assets/50481103/f15a1d8c-2a2b-40bf-8ee2-99f11e8b58ea)

(Was wondering for a second if perhaps it had something to do with projects being ported over from 3.x, but this is a fresh project so no)

**Comment by PGPereira** [comment]
I am also experiencing this as well, and noticed it occur after reordering the bones inside a skeleton.

**Comment by Soliaonline** [comment]
Still ongoing.

**Comment by GeekzGamingz** [comment]
![Skele](https://github.com/godotengine/godot/assets/42735252/3c1fef9f-565d-471a-95b3-603d2b26d3e0)
Still Ongoing.

**Comment by myyk** [comment]
I'm new to the Godot source, but I tried to do some deep diving. I hope this is helpful for someone who might know a bit more.

Got a stack trace from gdb for `4.2-stable` from `​break scene/resources/skeleton_modification_2d_twoboneik.cpp:253​` by runnint `run -e --path ~/workspace/<my-project-path>`.

It looks like some sort of initialization order which causes noisy warnings because everything seems to work afterwards as others have found. I'm to new to see if there's any initialization bug or if it's just a missing check in `set_target_node` to see if the object is setup before calling `update_target_cache`. But this wouldn't fix all the warnings I see like ones that call here: https://github.com/godotengine/godot/blob/master/scene/resources/skeleton_modification_2d_twoboneik.cpp#L42.

The common root cause seems to be that `_setup_modification` is not called sooner on all the modifications, but I'm not sure how to make that change.

Stack trace:
```
#0  SkeletonModification2DTwoBoneIK::update_target_cache (this=0x555574122230)
    at scene/resources/skeleton_modification_2d_twoboneik.cpp:253
253			ERR_PRINT_ONCE("Cannot update target cache: modification is not properly setup!");
(gdb) f 1
#1  0x000055555b1cf1fe in SkeletonModification2DTwoBoneIK::set_target_node (this=0x555574122230, p_target_node=...)
    at scene/resources/skeleton_modification_2d_twoboneik.cpp:330
330		update_target_cache();
(gdb) backtrace
#0  SkeletonModification2DTwoBoneIK::update_target_cache (this=0x555574122230)
    at scene/resources/skeleton_modification_2d_twoboneik.cpp:253
#1  0x000055555b1cf1fe in SkeletonModification2DTwoBoneIK::set_target_node (this=0x555574122230, p_target_node=...)
    at scene/resources/skeleton_modification_2d_twoboneik.cpp:330
#2  0x0000555558272de8 in call_with_variant_args_helper<__UnexistingClass, NodePath const&, 0ul> (p_instance=0x555574122230, 
    
    p_method=(void (__UnexistingClass::*)(__UnexistingClass * const, const NodePath &)) 0x55555b1cf1c4 <SkeletonModification2DTwoBoneIK::set_target_node(NodePath const&)>, p_args=0x7fffffffa3a0, r_error=...) at ./core/variant/binder_common.h:303
#3  0x000055555826e73b in call_with_variant_args_dv<__UnexistingClass, NodePath const&> (p_instance=0x555574122230, 
    p_method=(void (__UnexistingClass::*)(__UnexistingClass * const, const NodePath &)) 0x55555b1cf1c4 <SkeletonModification2DTwoBoneIK::set_target_node(NodePath const&)>, p_args=0x7fffffffa470, p_argcount=1, r_error=..., default_values=...)
    at ./core/variant/binder_common.h:450
#4  0x000055555826a9e4 in MethodBindT<NodePath const&>::call (this=0x5555646afed0, p_object=0x555574122230, 
    p_args=0x7fffffffa470, p_arg_count=1, r_error=...) at ./core/object/method_bind.h:335
#5  0x000055555c65a7b2 in ClassDB::set_property (p_object=0x555574122230, p_property=..., p_value=..., r_valid=0x0)
    at core/object/class_db.cpp:1235
#6  0x000055555c672097 in Object::set (this=0x555574122230, p_name=..., p_value=..., r_valid=0x0) at core/object/object.cpp:257
#7  0x000055555b175a9a in ResourceLoaderText::load (this=0x7fffffffa740) at scene/resources/resource_format_text.cpp:628
#8  0x000055555b1802fc in ResourceFormatLoaderText::load (this=0x5555627c2430, p_path=..., p_original_path=..., 
    r_error=0x55557d352fac, p_use_sub_threads=false, r_progress=0x55557d352fa0, 
    p_cache_mode=ResourceFormatLoader::CACHE_MODE_REPLACE) at scene/resources/resource_format_text.cpp:1653
#9  0x000055555c22335d in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., 
    p_cache_mode=ResourceFormatLoader::CACHE_MODE_REPLACE, r_error=0x55557d352fac, p_use_sub_threads=false, 
    r_progress=0x55557d352fa0) at core/io/resource_loader.cpp:261
#10 0x000055555c223acf in ResourceLoader::_thread_load_function (p_userdata=0x55557d352f58) at core/io/resource_loader.cpp:319
#11 0x000055555c2248eb in ResourceLoader::_load_start (p_path=..., p_type_hint=..., 
    p_thread_mode=ResourceLoader::LOAD_THREAD_FROM_CURRENT, p_cache_mode=ResourceFormatLoader::CACHE_MODE_REPLACE)
    at core/io/resource_loader.cpp:500
#12 0x000055555c22432e in ResourceLoader::load (p_path=..., p_type_hint=..., 
    p_cache_mode=ResourceFormatLoader::CACHE_MODE_REPLACE, r_error=0x7fffffffccb8) at core/io/resource_loader.cpp:417
#13 0x0000555559383e0a in EditorNode::load_scene (this=0x555564eff2c0, p_scene=..., p_ignore_broken_deps=false, 
    p_set_inherited=false, p_clear_errors=true, p_force_open_imported=false, p_silent_change_tab=false)
    at editor/editor_node.cpp:3789
#14 0x0000555559391063 in EditorNode::_load_open_scenes_from_config (this=0x555564eff2c0, p_layout=...)
    at editor/editor_node.cpp:5499
#15 0x000055555938df55 in EditorNode::_load_editor_layout (this=0x555564eff2c0) at editor/editor_node.cpp:5123
#16 0x000055555936e444 in EditorNode::_sources_changed (this=0x555564eff2c0, p_exist=false) at editor/editor_node.cpp:1050
#17 0x00005555593e388a in call_with_variant_args_helper<EditorNode, bool, 0ul> (p_instance=0x555564eff2c0, p_method=(void (EditorNode::*)(EditorNode * const, bool)) 0x55555936e394 <EditorNode::_sources_changed(bool)>, p_args=0x7fffffffd370, r_error=...) at ./core/variant/binder_common.h:303
#18 0x00005555593e2525 in call_with_variant_args<EditorNode, bool> (p_instance=0x555564eff2c0, p_method=(void (EditorNode::*)(EditorNode * const, bool)) 0x55555936e394 <EditorNode::_sources_changed(bool)>, p_args=0x7fffffffd370, p_argcount=1, r_error=...) at ./core/variant/binder_common.h:417
#19 0x00005555593dd8f6 in CallableCustomMethodPointer<EditorNode, bool>::call (this=0x5555740c7b20, p_arguments=0x7fffffffd370, p_argcount=1, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:98
#20 0x000055555c2e4fc8 in Callable::callp (this=0x55557d0fbf00, p_arguments=0x7fffffffd370, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:57
#21 0x000055555c67623a in Object::emit_signalp (this=0x555564f561d0, p_name=..., p_args=0x7fffffffd370, p_argcount=1) at core/object/object.cpp:1127
#22 0x000055555a3fc3ad in Node::emit_signalp (this=0x555564f561d0, p_name=..., p_args=0x7fffffffd370, p_argcount=1) at scene/main/node.cpp:3606
#23 0x00005555589e1577 in Object::emit_signal<bool> (this=0x555564f561d0, p_name=...) at ./core/object/object.h:922
#24 0x0000555559296471 in EditorFileSystem::_notification (this=0x555564f561d0, p_what=17) at editor/editor_file_system.cpp:1285
#25 0x00005555592a4410 in EditorFileSystem::_notificationv (this=0x555564f561d0, p_notification=17, p_reversed=false) at editor/editor_file_system.h:146
#26 0x000055555c674454 in Object::notification (this=0x555564f561d0, p_notification=17, p_reversed=false) at core/object/object.cpp:837
#27 0x000055555a428bdf in SceneTree::_process_group (this=0x555564e8faf0, p_group=0x555564e8fd48, p_physics=false) at scene/main/scene_tree.cpp:951
#28 0x000055555a42911d in SceneTree::_process (this=0x555564e8faf0, p_physics=false) at scene/main/scene_tree.cpp:1028
#29 0x000055555a426eec in SceneTree::process (this=0x555564e8faf0, p_time=0.1166666666666667) at scene/main/scene_tree.cpp:508
#30 0x00005555580362b3 in Main::iteration () at main/main.cpp:3636
#31 0x0000555557fa412e in OS_LinuxBSD::run (this=0x7fffffffd790) at platform/linuxbsd/os_linuxbsd.cpp:933
#32 0x0000555557f9c2a8 in main (argc=4, argv=0x7fffffffdd58) at platform/linuxbsd/godot_linuxbsd.cpp:74
```

**Comment by SaffronStreams** [comment]
I was still working in 4.1.3stable, and decided to try switching to 4.2 today. However, when opening my player character, it now gets fully locked up and I cannot move anything in the skeleton. It's as though there's another skeletonmodification than the one I see still active or something, forcing it to always return to a certain, scrunched up state.

I'm wondering if all of these problems have something to do with trying out several configurations of skeletonmodification, and deleting them but some kind of trace remaining, because even if I just plain delete the current skeletonmodificationstack2D, the whole skeleton remains scrunched up.

When starting up the game, I get these errors now.

![image](https://github.com/godotengine/godot/assets/50481103/5ec0ec0d-b2a3-4eb5-9c59-ac2a4358d8e9)

**Comment by ditiem-games** [comment]
Looking at C++ code in `scene/2d/skeleton_2d.cpp`, around line 435, there is a function, Bone2D::calculate_length_and_rotation, that is the one that prints the bug.

Why that function is called?

Do see the inspector when you click on a Bone2D, there is a flag, "auto calculate length and angle":

<img width="437" alt="image" src="https://github.com/godotengine/godot/assets/124758343/be746722-3784-452d-a77b-8163e6bd1c3b">

Few things:
1- It seems there is no documentation for this flag.
2- If you uncheck it, the warning will not appear.
3- The values requested don't have description either. I can imagine what they are asking for, but not knowing the units does not help.

**Comment by Ughuuu** [comment]
Interesting. That computes length and angle based on children nodes. Its possible that those nodes arent fully loaded yet, and that is why the warning is thrown? Maybe that calculation should happen in another place, if at all, since its already calculated in editor time, why it needs again at start of runtime.

**Comment by Ughuuu** [comment]
The `calculate_length_and_rotation` is called from
```
		case NOTIFICATION_READY: {
			if (autocalculate_length_and_angle) {
				calculate_length_and_rotation();
			}
		} break;
```

and also from `set_autocalculate_length_and_angle` which is called as a setter it feels like from editor or from api layer.

So my thoughts on this is if someone calls this method, `set_autocalculate_length_and_angle`, it will call `calculate_length_and_rotation which will get the children nodes and update the bone length and angle.

Why this function is called? It's called to update the bone length and angle based on children. What happens is sometimes you have a child bone that is the last one that doesnt have any children of it's own. In that case, it cannot compute length and angle so it's using the transform instead. Is that a bug tho? So if setting all your last bone nodes with autocalculate false, you won't get the warning anymore.

I would propose that the warning isn't thrown at all, since if you don't have children nodes, it doesn't compute length and angle but instead puts a default one, that isn't a warning state or error state(it could be a node warning, but probably not) since there are and there will be nodes that have no children and just exist as last nodes. I think having them there is normal, many people use it as a sort of indication or place to move the higher bones. Having a warning for this isn't really bringing much value.

That is however just one warning.

**Comment by Ughuuu** [comment]
Another warning/error is with the bone index.

This is called from: `scene/resources/skeleton_modification_2d_lookat.cpp` from `set_bone_index`

This function seems to do look if the stack has a skeleton member or if `is_setup` && the `stack` isn't null, eg:
`stack->skeleton`
if not throws warning.

**Comment by Ughuuu** [comment]
The `is_setup` becomes true in the `_setup_modification` function. This is called from the `setup` function on the `scene/resources/skeleton_modification_stack_2d.cpp`.

So if called from there, the is_setup is made true before getting called.

However another problem could be that `stack->skeleton` is null for any reason. This is set in the set_skeleton function of the `scene/resources/skeleton_modification_stack_2d.cpp`. So it could very well be an issue with the setter not getting called when it should?

I'll try attack a debugger and see the order of how they are called and what might cause it.

**Comment by Ughuuu** [comment]
Indeed, the `_setup_modification` function is called later. Thats the issue. So what happens is there are multiple functions like:
```
PhysicalBone2D::set_bone2d_index
SkeletonModification2DCCDIK::set_ccdik_joint_bone_index
SkeletonModification2DFABRIK::set_fabrik_joint_bone_index
SkeletonModification2DJiggle::set_jiggle_joint_bone_index
SkeletonModification2DLookAt::set_bone_index
SkeletonModification2DTwoBoneIK::set_joint_one_bone_idx
```
(The naming on these, uh)

These functions are called before the setup started, so the `is_setup` is false. However it still makes a note of this index, in all of these functions the implementation does:
```
if(is_setup) {
joint_bone_idx = p_bone_idx;
joint_bone2d_node_cache = ..
joint_bone2d_node = ..
} else {
joint_bone_idx = p_bone_idx;
}
```
So it really doesn't set the cache from the skeleton. (Now, should it? Should the even be called in some other order, I don't know)

Ok, afterwards, when the setup is called, it will do an update on the cache:
```
W 0:00:00:0545   _execute: Target cache is out of date. Attempting to update...
  <C++ Source>   scene/resources/skeleton_modification_2d_lookat.cpp:119 @ _execute()
```

If you look at the log where that is called, it's basically calling:
```
update_target_cache
```
Which in turn does what the initial function should have done.

So, to me this seems like what happens is the bone isn't setup yet when the setter is called, but no problem, because it is caching the index and restoring the node_cache later. Again these shouldn't really be warnings even, not sure though. Will try to investigate more and see if I can have a fix, but then we will need someone to review the fix and understand why that would be the fix.

**Comment by Ughuuu** [comment]
If anyone can try test, I implemented what I spoke about earlier here: https://github.com/godotengine/godot/pull/89387

Not sure if it catches all cases though. Some dissapeared and it makes sense to remove those warnings, as I wrote above. There is still some of these:

```
Cannot update Bone2D cache: modification is not properly setup!
```

Seems to be related to calls of update_node_cache when the setup is not started(or stack is null, more rare). I would say it could be because of the set_bone2d_node method that sets the bone_node but probably the setup phase isn't started yet again. In that case it's probably ok as well to do no op instead of erroring. Investigating all use cases to see i am not missing anything, but it seems in a lot of cases not erroring should be fine, as its not an error case, it's a normal use case(eg setting a value and not computing cache until execute is called).

**Comment by Ughuuu** [comment]
Seems in these cases in the setter we don't want to update if the is_setup is not true. This way the error is not thrown at startup. I'll give it a try see if all errors dissapear.

**Comment by Ughuuu** [comment]
Ok, tested locally (in the PR i linked) and i have 0 warnings and 0 errors. Things work well, I worked out through all warnings and errors and they were indeed not warnings or errors, in the sense that it was not an error case happening.

**Comment by TheLegoSensei** [comment]
I tried your build, and I'm still getting a ton of errors when loading in my project:

scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  scene\2d\skeleton_2d.cpp:620 - Condition "!is_inside_tree()" is true. Returning: 0
  Passed-in Bone index is out of range!
  scene\2d\skeleton_2d.cpp:630 - Condition "!is_inside_tree()" is true. Returning: nullptr
  scene\2d\skeleton_2d.cpp:630 - Condition "!is_inside_tree()" is true. Returning: nullptr
  scene\2d\skeleton_2d.cpp:630 - Condition "!is_inside_tree()" is true. Returning: nullptr
  scene\2d\skeleton_2d.cpp:630 - Condition "!is_inside_tree()" is true. Returning: nullptr
  scene\2d\skeleton_2d.cpp:630 - Condition "!is_inside_tree()" is true. Returning: nullptr
  scene\resources\2d\skeleton\skeleton_modification_2d_twoboneik.cpp:113 - Target cache is out of date. Attempting to update...
  scene\resources\2d\skeleton\skeleton_modification_2d_twoboneik.cpp:119 - Joint one Bone2D node cache is out of date. Attempting to update...
  scene\resources\2d\skeleton\skeleton_modification_2d_twoboneik.cpp:123 - Joint two Bone2D node cache is out of date. Attempting to update...
  
although I will admit I am new to compiling the engine so maybe I did something wrong

**Comment by Ughuuu** [comment]
Can you out a test project i can verify with? Thanks.

**Comment by TheLegoSensei** [comment]
> Can you out a test project i can verify with? Thanks.

emailed it to the email on your profile
