### ISSUE TITLE
Game using HDR texture fails to load it when exported (`texture_format/bptc` defaults to `false`)

### ISSUE THREAD

**Issue by telmotrooper** [godotengine/godot#73789]
### Godot version

4.0.rc3.official [7e79aead9]

### System information

OS: Arch Linux, CPU: i7-3770, GPU: Radeon RX 570

### Issue description

Simple project using HDR texture as PanoramaSky exported to Linux crashes when opened. Might or might not be related to #73627 and #61948.

Output displayed in the console when opening the exported game:
```
Godot Engine v4.0.rc3.official.7e79aead9 - https://godotengine.org
Vulkan API 1.3.235 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 570 Series
 
ERROR: Unable to open file: res://.godot/imported/casual_day_4k.hdr-e91263f32fd2699bdb025dc92151c608.bptc.ctex.
   at: _load_data (scene/resources/texture.cpp:846)
ERROR: Failed loading resource: res://.godot/imported/casual_day_4k.hdr-e91263f32fd2699bdb025dc92151c608.bptc.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
ERROR: Failed loading resource: res://casual_day_4k.hdr. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
ERROR: Can't load dependency: res://casual_day_4k.hdr.
   at: load (core/io/resource_format_binary.cpp:696)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-3070c538c03ee49b7677ff960a3f5195-main.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
ERROR: Failed loading scene: res://main.tscn
   at: start (main/main.cpp:2954)
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9301)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1982)
```

### Steps to reproduce

Try to export the provided project.

### Minimal reproduction project

[New Godot 4 Project.zip](https://github.com/godotengine/godot/files/10809016/New.Godot.4.Project.zip)

**Comment by Calinou** [comment]
Did you export the project using headless mode?

**Comment by telmotrooper** [comment]
@Calinou No, directly from the Editor.

**Comment by clayjohn** [comment]
The errors look suspiciously similar to the errors in https://github.com/godotengine/godot/issues/73267 which was closed as a duplicate of https://github.com/godotengine/godot/issues/72856 which was fixed by https://github.com/godotengine/godot/pull/73286

**Comment by akien-mga** [comment]
I could reproduce the issue, which is caused by the export preset having `texture_format/bptc` set to `false`.

Setting it to `true` fixes the issue (note that in RC3, the import for the `.exr` file is extremely slow - this is fixed in RC4 by #73715.

The option should probably default to `true`, at least until we have a proper detection mechanism that lets users know that they are actually using BPTC and should therefore enable export it.

I'm not sure what's the purpose of this export preset option in the first place though. It should export what it needs.

**Comment by Regrad** [comment]
The bug is still present in the RC4 version. Importing an uncompressed HDRI texture solves the problem.

**Comment by akien-mga** [comment]
Yes, it's mentioned in the RC 4 blog post with the workaround: https://godotengine.org/article/release-candidate-godot-4-0-rc-4/#known-issues
