### ISSUE TITLE
Shortcut key Ctrl+Alt+p is inserting 'p' into the "Filter Files" Searchbox

### ISSUE THREAD

**Issue by stmSi** [godotengine/godot#73978]
### Godot version

4.0 rc5

### System information

Manjaro Linux, KDE, Nvidia 2060

### Issue description

`Focus FileSystem Filter` shortcut key `Ctrl+Alt+P` is inserting `p` into searchbox `Filter Files`

See Screenshot

![image](https://user-images.githubusercontent.com/32661049/221411291-d208b0f1-ee9d-4a40-9b02-8456e4de71a6.png)

### Steps to reproduce

1. Open Blank Project
2. press `Ctrl+Alt+P`
3. see that `p` is inserted into the searchbox

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Can't reproduce on Windows.
Although maybe the issue was already fixed? @stmSi Can you test again?

**Comment by stmSi** [comment]
Tested in current master, issue still exists... I am using KDE Wayland. @KoBeWi

**Comment by KoBeWi** [comment]
Then it might be system-specific. On Windows when you hold Ctrl and Alt the LineEdit does not accept any characters.
