### ISSUE TITLE
White screen until you resize

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7443]
Experienced on Mac OS X but @reduz  mentioned this was also witnessed on Windows.

The project picker opens up fine but when Godot opens itself the screen is blank until you resize it.
I suspect the issue is related to the window opening maximised and the code missing to initialise the screen size variables.

Will investigate further, just raising this to make sure it's not forgotten as  don't have time to look into this right this minute:)

**Comment by Limb** [comment]
I am currently working on this. As of now it seems the best way to resolve this is to force a redraw at the end of the editor being setup. Right now the window sits blank because a force redraw is not requested and the application is set to low power mode.

[main.cpp#L1630](https://github.com/godotengine/godot/blob/b87a232668d9f9f3b32c2fceb60bc5f6ef46df22/main/main.cpp#L1630)

**Comment by Hinsbart** [comment]
Was this fixed by fccf2816d?

**Comment by vnen** [comment]
Ping @BastiaanOlij

**Comment by Limb** [comment]
Tried to check this on the current master for Windows, I'm getting a "Error initializing GLAD" error. So once that is resolved I will report if this issue was fixed.

**Comment by vnen** [comment]
This was certainly fixed for Windows. The question is if it still happens on Mac.

@Limb If you have another problem, feel free to open an issue about it.

**Comment by akien-mga** [comment]
Fixed AFAIK.

**Comment by ChronocideGames** [comment]
I've never seen this issue before, but suddenly started having it today on Windows with version 2.1.4. I'm not aware of anything changing on my system to cause this since the last time it worked properly. It is happening with both the version downloaded at the Godot site, and the Steam version.

**Comment by thisismike97** [comment]
This issue still happens on the latest version of OSX, we used the latest source from the 3.0 branch.

@akien-mga
