### ISSUE TITLE
`KinematicCollision3D.get_local_shape()` always returns only the zero index shape

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#75069]
### Godot version

4.0 dotnet

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

*I'd first like to say I'm not sure if this is a bug or if I'm just understanding the functionality wrong, I've been trying reddit, discord for days, nothing so I decided to come with it here.*

I'd like to get the collision shape which collided during KinematicCollision from inside a CharacterBody3D, I found there's `get_local_shape(index)` method but this method always returns only the 0 index CollisionObject.

If I'm using this wrong I'm sorry, is there some way to use this or something else to get the particular colliding shape?

Test project is in gdscript.

Thank you.

### Steps to reproduce

1. Play the project
2. Wait until objects collide
3. Read the output, it prints the first shape only (ChracterBodyShape1)
The local_shape_at_index prints the shape that should be colliding but it returns only the 0 index CollisionShape3D which is named CharacterBodyShape1, the shape which collided is CharacterBodyShape2
4. Stop the project
5. Move the CharacterBodyShape2 above CharacterBodyShape1 in the sceen tree so it's the first child of the CharacterBody3D node.
6. Play the project
7. Watch the Output again (again only the first shape this time ChracterBodyShape2 since you moved it up)

As you can see now it prints the colliding shape but only because it's the 0 index shape.

### Minimal reproduction project

[TestGetLocalShape.zip](https://github.com/godotengine/godot/files/11009578/TestGetLocalShape.zip)

**Comment by adamscott** [comment]
Be careful, you're conflating the `collision_index` of collisions with `get_slide_collision_count()`.
`collision_index` refers to `collision.get_collision_count()`, the deepest collision being 0.

**Comment by viksl** [comment]
@adamscott I've updated the code to reflect that mistake and updated teh MRP in the original post but as I mentioned previously I did check all the indices manually anyway and they all return a wrong shape. Perhaps I'm still doing something wrong? I really can't get to the colliding shape and only the 0 index one.

Thank you for pointing out my mistake but does it change anything considering the above mentioned, please?

**Comment by Raven38911** [comment]
I ran into this issue while working on an own project and also tried the MRP - I can confirm that this is still broken in 4.2.

There is also a recent comment by @r0401 under the closed 3.x issue #31144 which describes the same problem.

**Comment by Belserich** [comment]
Still buggy in 4.3 stable

**Comment by adamscott** [comment]
Thanks @Belserich ! I decided to really investigate this time and I found out the issue.
