### ISSUE TITLE
`_parse_property` autocomplete generate function signature with wrong types in parameters

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#75311]
### Godot version

4.0.1 stable

### System information

Manjaro Linux using i3, Foward+

### Issue description

When you create the `_parse_property` function and let Godot autocomplete for you you get this:
![image](https://user-images.githubusercontent.com/13070158/227706727-d942c52e-9e06-4dc3-9c30-b6d371a8e4f0.png)

And have to manually correct it to look like this:
![image](https://user-images.githubusercontent.com/13070158/227706807-876480ce-fa46-4b0d-a32e-28ee8b553e65.png)

which honestly is kind of weird because you cant use `Variant.Type`, `PropertyHint` or `PropertyUsageFlags` any where else that I know of. I even tried to use `PropertyHint.PROPERTY_` to see if it would give me a list of property hint constants, but Godot doesn't seem to recognize any of these "types" outside of the parameters of this specific function.

which makes me think the first signature is more "correct" even though the second one is the one that works and what was given as fix for #72963, so maybe it's just missing something to update the automplete?

### Steps to reproduce

Create a new `EditorInspectorPlugin` script anywhere and let godot create the `_parse_property` function.

### Minimal reproduction project

See steps to reproduce as they're minimal enough.

**Comment by dalexeev** [comment]
> because you cant use `Variant.Type`, `PropertyHint` or `PropertyUsageFlags` any where else

See #73590. Now you can use these pseudo-types as type hints:

```gdscript
@export var type: Variant.Type
@export var side: Side
@export var key: Key

func do_something() -> Error:
    return OK
```

The bug with incorrect auto-generated signature in the editor should be fixed.

Also, there may be a bug in GDScript with flags, now it should be plain `int`, because `BitField[T]` is not present in GDScript (see #74641).

**Comment by YuriSizov** [comment]
> The bug with incorrect auto-generated signature in the editor should be fixed.

Do you mean "We should fix it" or are you saying some PR has already addressed that? The one linked is already in 4.0.1, so it's not that.

**Comment by ajreckof** [comment]
I think he meant that it is something we should do because it is still reproducible in master

**Comment by eh-jogos** [comment]
> > because you cant use `Variant.Type`, `PropertyHint` or `PropertyUsageFlags` any where else
> 
> See #73590. Now you can use these pseudo-types as type hints:
> 
> ```gdscript
> @export var type: Variant.Type
> @export var side: Side
> @export var key: Key
> 
> func do_something() -> Error:
>     return OK
> ```

Oh, Ok, this seems useful, though kind of obscure since there's no autocomplete for it, so you have to know about the pseudo-types before hand, for example, typing `Variant.` only shows `new()` as an autocomplete option:
![image](https://user-images.githubusercontent.com/13070158/227724973-040c2386-e0d3-4418-9fbd-8e5be9146488.png)

Trying to ctrl-click them also doesn't take us to their documentation, nor searching for them in the help 
![image](https://user-images.githubusercontent.com/13070158/227725761-a7e8752b-51f3-42d9-a6bb-fff5058c26bb.png)

I like the idea, I use a lot of "advanced exports" and I'm always using the `PROPERTY_HINT_` constants, so I knew where to look but usability wise this seems more like something really obscure, and potentially confusing specially for someone that is seeing this for the first time and might search the help for it and find nothing.

**Comment by dalexeev** [comment]
> this seems useful, though kind of obscure since there's no autocomplete for it, so you have to know about the pseudo-types before hand, for example, typing `Variant.` only shows `new()` as an autocomplete option

> Trying to ctrl-click them also doesn't take us to their documentation, nor searching for them in the help

Yes, you're right, there's room for fixes and improvements.

> nor searching for them in the help

Enums are not displayed in Editor Help at all, only their elements (as constants).
![](https://user-images.githubusercontent.com/47700418/227727443-dba65600-8d6d-4bbe-bb30-b2430bb0620b.png)

* See also: godotengine/godot-proposals#6515
