### ISSUE TITLE
In every project opens, a plank load error popup showing

### ISSUE THREAD

**Issue by TomerconDevelopers** [godotengine/godot#75488]
### Godot version

4.0.1 stable

### System information

system: windows 10, ryzen 6 3600, rx 590, 16gb RAM, android device: OPPO A57, CPH2387, android version 12

### Issue description

![image](https://user-images.githubusercontent.com/62302722/228761471-90f1a409-38ea-4830-88d4-d348d47860d4.png)

The issue mainly started after i rearranged some project files to different folders.(not sure exact reason)
if i open project in godot console mode.it outputs like below

WARNING: res://systems/player/models/male/materials/Body.tres:3 - ext_resource, invalid UID: uid://cs2we4d60hlko - using text path instead: res://experiment/male/male_29.png
WARNING:     at:  res://UI/MainHud/MainHud.tscn:31 - ext_resource, invalid UID: uid://um15frtga5lo - using text path instead: res://systems/inventory/inventory.tscn
load (scene/resources/resource_format_text.cpp:448)
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_29.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Body.tres:4 - ext_resource, invalid UID: uid://dctgx6bjbterc - using text path instead: res://experiment/male/male_30.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_30.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Body.tres:5 - ext_resource, invalid UID: uid://do65vqddq0qt7 - using text path instead: res://experiment/male/male_28.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_28.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Body.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_29.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Body.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_29.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Body.tres. Make sure resources have been imported by opening the project in the editor at least once.
WARNING:   at:  res://UI/JoyStick/JoyStick.tscn:4 - ext_resource, invalid UID: uid://dawmvs64d45yr - using text path instead: res://UI/JoyStick/joystick_base_outline.png
(core/io/resource_loader.cpp:222)
     at: load (scene/resources/resource_format_text.cpp:448)
WARNING: res://systems/player/models/male/materials/Bottom.001.tres:3 - ext_resource, invalid UID: uid://li3g71hth2ga - using text path instead: res://experiment/male/male_465.png
WARNING:     at:  res://UI/JoyStick/JoyStick.tscn:5 - ext_resource, invalid UID: uid://cpll3277utkix - using text path instead: res://UI/JoyStick/joystick_tip.png
load (scene/resources/resource_format_text.cpp:448)
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_465.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.001.tres:4 - ext_resource, invalid UID: uid://c21scvttftjtj - using text path instead: res://experiment/male/male_466.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_466.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.001.tres:5 - ext_resource, invalid UID: uid://bc2jq0qnrd1w3 - using text path instead: res://experiment/male/male_464.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_464.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.001.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_465.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.001.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_465.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.001.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.002.tres:3 - ext_resource, invalid UID: uid://c53jigyfqpeny - using text path instead: res://experiment/male/male_19.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_19.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.002.tres:4 - ext_resource, invalid UID: uid://bwna4khk28w3h - using text path instead: res://experiment/male/male_20.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_20.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.002.tres:5 - ext_resource, invalid UID: uid://d1h1r0s2ul6py - using text path instead: res://experiment/male/male_18.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_18.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.002.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_19.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.002.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_19.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.002.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.003.tres:3 - ext_resource, invalid UID: uid://irn0qwchcw4q - using text path instead: res://experiment/male/male_8.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_8.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.003.tres:4 - ext_resource, invalid UID: uid://cr57w1egev22o - using text path instead: res://experiment/male/male_9.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_9.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.003.tres:5 - ext_resource, invalid UID: uid://ck2uk0rmowde5 - using text path instead: res://experiment/male/male_7.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_7.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.003.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_8.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.003.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_8.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.003.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.004.tres:3 - ext_resource, invalid UID: uid://dvfmggjxcwbnk - using text path instead: res://experiment/male/male_129.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_129.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.004.tres:4 - ext_resource, invalid UID: uid://1m26t7ik82mp - using text path instead: res://experiment/male/male_130.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_130.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.004.tres:5 - ext_resource, invalid UID: uid://cdnexhjbgiwl5 - using text path instead: res://experiment/male/male_128.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_128.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.004.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_129.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.004.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_129.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.004.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.005.tres:3 - ext_resource, invalid UID: uid://bafogkfig8dsv - using text path instead: res://experiment/male/male_145.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_145.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.005.tres:4 - ext_resource, invalid UID: uid://bkknvmd0yuw3w - using text path instead: res://experiment/male/male_146.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_146.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.005.tres:5 - ext_resource, invalid UID: uid://feuqutmhgocn - using text path instead: res://experiment/male/male_144.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_144.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.005.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_145.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.005.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_145.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.005.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.006.tres:3 - ext_resource, invalid UID: uid://br6crsb2sruw8 - using text path instead: res://experiment/male/male_229.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_229.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.006.tres:4 - ext_resource, invalid UID: uid://cdvnfjydu3dvk - using text path instead: res://experiment/male/male_230.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_230.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.006.tres:5 - ext_resource, invalid UID: uid://da4htxf3mi0hc - using text path instead: res://experiment/male/male_228.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_228.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.006.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_229.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.006.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_229.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.006.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.007.tres:3 - ext_resource, invalid UID: uid://1qovacgnbrgh - using text path instead: res://experiment/male/male_265.png
ERROR:     at:  Attempt to disconnect a nonexistent connection from 'GeneralSkeleton:<Skeleton3D#1901814935095>'. Signal: 'bone_pose_changed', callable: 'BoneAttachment3D::on_bone_pose_update'.
load (scene/resources/resource_format_text.cpp:448)
   at: (core/object/object.cpp:1327)
ERROR: Resource file not found: res://experiment/male/male_265.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.007.tres:4 - ext_resource, invalid UID: uid://b7chn6fjjm8fi - using text path instead: res://experiment/male/male_266.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_266.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.007.tres:5 - ext_resource, invalid UID: uid://bje6e6w27ynj4 - using text path instead: res://experiment/male/male_264.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_264.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.007.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_265.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.007.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_265.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.007.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.008.tres:3 - ext_resource, invalid UID: uid://bshwpkto1cg7s - using text path instead: res://experiment/male/male_323.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_323.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.008.tres:4 - ext_resource, invalid UID: uid://daexlvam5si4i - using text path instead: res://experiment/male/male_324.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_324.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.008.tres:5 - ext_resource, invalid UID: uid://iod6wd6pw640 - using text path instead: res://experiment/male/male_322.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_322.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.008.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_323.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.008.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_323.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.008.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.009.tres:3 - ext_resource, invalid UID: uid://jqdqtcgrbof8 - using text path instead: res://experiment/male/male_333.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_333.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.009.tres:4 - ext_resource, invalid UID: uid://ckfqsrxwxcvyo - using text path instead: res://experiment/male/male_334.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_334.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.009.tres:5 - ext_resource, invalid UID: uid://b3bfg8kxhnjnt - using text path instead: res://experiment/male/male_332.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_332.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.009.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_333.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.009.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_333.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.009.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.010.tres:3 - ext_resource, invalid UID: uid://duxgj3ibcf0lw - using text path instead: res://experiment/male/male_353.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_353.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.010.tres:4 - ext_resource, invalid UID: uid://b0dqoasnoendx - using text path instead: res://experiment/male/male_354.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_354.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.010.tres:5 - ext_resource, invalid UID: uid://cegxma0u4vbgl - using text path instead: res://experiment/male/male_352.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_352.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.010.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_353.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.010.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_353.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.010.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.011.tres:3 - ext_resource, invalid UID: uid://uvc83ybvvl8c - using text path instead: res://experiment/male/male_395.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_395.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.011.tres:4 - ext_resource, invalid UID: uid://bj61mfpoou5ij - using text path instead: res://experiment/male/male_396.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_396.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.011.tres:5 - ext_resource, invalid UID: uid://6m78s4pne4dt - using text path instead: res://experiment/male/male_394.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_394.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.011.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_395.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.011.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_395.png
   at: load (scene/resources/resource_format_text.cpp:735)
ERROR: Failed loading resource: res://systems/player/models/male/materials/Bottom.011.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:222)
WARNING: res://systems/player/models/male/materials/Bottom.012.tres:3 - ext_resource, invalid UID: uid://bkrits7im6nk6 - using text path instead: res://experiment/male/male_513.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_513.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.012.tres:4 - ext_resource, invalid UID: uid://bam20jsb61f3t - using text path instead: res://experiment/male/male_514.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_514.png.
   at: (core/io/resource_loader.cpp:227)
WARNING: res://systems/player/models/male/materials/Bottom.012.tres:5 - ext_resource, invalid UID: uid://eukqwwbu32o8 - using text path instead: res://experiment/male/male_512.png
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Resource file not found: res://experiment/male/male_512.png.
   at: (core/io/resource_loader.cpp:227)
ERROR: res://systems/player/models/male/materials/Bottom.012.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_513.png
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:174)
ERROR: res://systems/player/models/male/materials/Bottom.012.tres:12 - Parse Error: [ext_resource] referenced non-loaded resource at: res://experiment/male/male_513.png
   at: load (scene/resources/resource_format_text.cpp:735)

### Steps to reproduce

1. create new project
2. import any gltf model and some script, texture material files
3. rearrange these folders into different folders/sub folders

### Minimal reproduction project

1. create new project
2. import any gltf model and some script, texture material files
3. rearrange these folders into different folders/sub folders

**Comment by TomerconDevelopers** [comment]
update-1: Rearranging imported model gltf files from one folder to different folder also breaks material dependencies

![image](https://user-images.githubusercontent.com/62302722/228765456-bb20f6e6-9b92-40ec-8e01-75031b85bb7b.png)

**Comment by TomerconDevelopers** [comment]
update-2: very sad to see that scene file also corrupted now:

![image](https://user-images.githubusercontent.com/62302722/228767577-260e392e-5c32-41de-b762-47f36c44d793.png)
 git version control rescued my project, but this is critical, i will try to upload a video of how this happens

**Comment by AThousandShips** [comment]
Did you move the files while the editor was not running?

**Comment by TomerconDevelopers** [comment]
video footage of the problem
https://www.youtube.com/watch?v=Te4BjLFDpps

**Comment by viksl** [comment]
I'm in 4.0.0 and this happens to me too. Just had couple crashes in a row right now. I'm in the C# version if it matters to anyone on Windows 10.

**Comment by Calinou** [comment]
@TomerconDevelopers @viksl Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by viksl** [comment]
@Calinou I wish I could. I'll try to reproduce it but no promises, in my current project I was encountering these crashes so much that I just had to redo the project so I don't have an actual project to reproduce it so no promises. But when it happens it happens a lot. I have a stream vod when my godot crashed in one day with this error so many times to show that it does actually happen if nothing else.

**Comment by Snowy-Fox** [comment]
I just had this happen to me too in Godot 4.0.3. This morning, I did some tidying up and moved some files in the FileSystem, including a GLB, from one folder to another. When I started Godot up again just now, I had the empty Load Error window pop up.

![load_error_01](https://github.com/godotengine/godot/assets/6191653/fb7e9c7b-36cb-406b-ab72-518f28d827a6)

![load_error_02](https://github.com/godotengine/godot/assets/6191653/6e0eb03c-2ec8-49b5-8c55-241d8a0f753c)

After finding this issue here on Github, I tried moving the files back to their original folder and restarting Godot, and the Load Error window didn't pop up.

Seeing other people mentioning GLTF files here, I tried moving all of the files except for the GLB, and the issue did not arise again.

![load_error_03](https://github.com/godotengine/godot/assets/6191653/c9539fe8-080f-45ab-a9d4-1dbd652350e2)

I've continued playing with it, moving the GLB and other files back and forth, closing and reopening Godot, and strangely, the issue seems to have fixed itself. After a few times moving the GLB back and forth again, I've been able to move all of the files to their desired location, and the Load Error window is no longer popping up.

I'm also noticing that when I move files and close and reopen Godot, there are sometimes duplicates left sitting in their original folders.

**Comment by benn0k** [comment]
Version:  4.0 Stable

Apologies for bumping, as this may have been resolved in a post-4.0 release, but I wanted to catch any folks who might stumble upon this in the future - I also bumped into this exact issue after doing a bit of restructuring of my project (specifically, moving scenes around using the FileSystem tab) 

The Load Error pop-up was blank for me, but my **debugger was referencing a file that couldn't be located as the path was now missing.** 

Moving that file _back_ to its existing location fixed it after closing/opening Godot. I'm not going to do any further troubleshooting to see if I can nail precisely what the issue is, but I do know that after I initially ran my project after moving the files, I was presented with the 'fix errors' dialogue and I used the auto-find feature to resolve this. (apologies if this terminology isn't correct; this is the first project I've worked on 😅)

**Comment by mykola-dev** [comment]
still happens on 4.2.1
i just moved some scenes into subfolder and here we go. have no idea how to fix it

**Comment by melon-Li-SomeOneTookMyNamePluhhh** [comment]
still happening, I tried to open my project downloaded from github when it occasionally crashes and occasionally opens with an empty loading error.

**Comment by luckyhero1** [comment]
> still happening, I tried to open my project downloaded from github when it occasionally crashes and occasionally opens with an empty loading error.

My project is also now coppeled with github. It takes a half minute to load in and than there's the empty loading error. But everthing works fine after that. I don't get the problem.

**Comment by snoopsneep** [comment]
I'm on 4.3 and was having this same issue while prototyping in multiplayer. I took a ui button scene from another project, and used it for some simple things. when i picked it up the next morning, though, this empty load error began appearing. When I tried to investigate, I eventually discovered that the dependencies for that button scene were broken, and fixing them solved the issue! If anybody's crawling the internet like me looking for a solution - make sure your scenes have the correct dependencies if you moved them around!
