### ISSUE TITLE
Godot 4(master and 4.0 branch) does not open svg files that do not contains size properties in root node

### ISSUE THREAD

**Issue by EsdrasCaleb** [godotengine/godot#76175]
### Godot version

4.0 stable and dev

### System information

Manjaro LInux

### Issue description

Godot does not open svg files here.I got this errors
ERROR: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
   at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:103)
ERROR: Error loading image: res://UIpack_vector.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://UIpack_vector.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:2031)
ERROR: Resource file not found: res://.import/UIpack_vector.svg-101d3c20e536126791fcca89da4a8955.stex.
   at: _load (core/io/resource_loader.cpp:227)
ERROR: Failed loading resource: res://UIpack_vector.svg. Make sure resources have been imported by opening the project in the editor at least once.

And if I put the properties of weight and height inside the SVG it can open but it is different from the way the version 3.x open it translates it and I need to redo all mapipngs

### Steps to reproduce

Download kenny ui pack and try to open it in godot 4
https://www.kenney.nl/assets/ui-pack

### Minimal reproduction project

[testbed.zip](https://github.com/godotengine/godot/files/11252825/testbed.zip)

**Comment by Calinou** [comment]
How can the SVG size be determined if the root node doesn't have a set size?

**Comment by capnm** [comment]
@EsdrasCaleb  It is already fixed in the next svg-lib version, you have just to wait for the release (there are still other issues).

**Comment by EsdrasCaleb** [comment]
what is the branch of this fix?
I am running in master branch and the bug still happen

**Comment by EsdrasCaleb** [comment]
> How can the SVG size be determined if the root node doesn't have a set size?

Like 3.x did you pick the farthest object

**Comment by capnm** [comment]
It is an external library, when the next version is released, it will be later also updated in Godot.

**Comment by EsdrasCaleb** [comment]
oh thx
