### ISSUE TITLE
Small Deploy with Network Filesystem does not work with Gradle Build

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#76294]
### Godot version

4.0.2 / 3.5.2

### System information

Windows 10 x64

### Issue description

When you deploy to Android with Gradle Build and Small Deploy, the APK still includes all resources. Works correctly with non-Gradle build.
Also the Gradle build, despite including everything, still tries to load files over network.

### Steps to reproduce

1. Add Android export preset
2. Enable 'Use Gradle Build' in export preset
3. Enable Small Deploy in Debug menu
4. Start the project with Remote Debug option

### Minimal reproduction project

N/A

**Comment by m4gr3d** [comment]
Fixed in https://github.com/godotengine/godot/pull/76540

**Comment by almusx** [comment]
i still have this issue on Godot 4.3, enabling small deploy with remote filesystem never worked for me on my android devides. The app is deployed and start but only the Godot splash is shown then not is loaded.
