### ISSUE TITLE
Selecting a TileMap node sometimes doesn't display the TileMap tab in the editor

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#76362]
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

When working with TileMaps there is a problem when selecting the TileMap node in the Scene in order to draw tiles. Often the TileMap tab is not displayed, only the TileSet tab. Selecting a different node and reselecting the TileMap fixes the issue.

I'm not sure exactly what triggers this. It occurs often when I work with Tilemaps, but I have not figured out how to reliably replicate it.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
This bug is fixed in 4.0.1.

**Comment by dandeliondino** [comment]
This is still happening for me in 4.0.2-stable when the TileMap's TileSet subinspector is expanded. I tried to find the pull request for the fix mentioned in 4.0.1 to see if this behavior was intended to be left in, but I'm having difficulty locating it.

To reproduce: 
- Select the TileMap node
- Expand the TileSet subinspector in the right TileMap inspector
- Select another node in the scene, then select the TileMap node again
- In the bottom panel, the TileSet editor opens

To fix:
- Collapse the TileSet subinspector in the right TileMap inspector
- Select another node in the scene, then select the TileMap node again
- In the bottom panel, the TileMap editor opens

This may be working as intended, since it does make sense to open the bottom TileSet editor when you first expand the TileSet subinspector.

However, I don't usually have a need to manually close the TileSet subinspector, so it keeps tripping me up. It's not the expected behavior when selecting the TileMap node, and the TileSet and TileMap bottom editors look so similar it's not always immediately apparent that the wrong one opened.

**Comment by KoBeWi** [comment]
The issue description is misleading then. By "not displayed" I assumed you mean the button does not appear at all.

It sounds related to #65467 and probably has the same cause.

**Comment by KoBeWi** [comment]
I didn't notice you aren't the OP, sorry .-.

**Comment by FarbrorMartin** [comment]
I did mean that the tab is not visible. I’m not on the latest version so
I’ll check if updating solves the issue. It’s intermittent, so difficult to
test.
