### ISSUE TITLE
Question: Hiding/disabling the built-in script editor?

### ISSUE THREAD

**Issue by mrzapp** [godotengine/godot#7705]
Is there a good way to completely disable the built-in script editor? Selecting an external editor in the settings doesn't change its behaviour.

It feels very intrusive when you don't want to use it. It pops up every time there's an error message, slowing down the workflow every time you have to switch back to the viewport you were working in. I'm not knocking the script editor, it's probably fine, but I prefer my vim setup the way it is.

I'd be happy to submit the change as a pull request, if there's currently no way to disable it.

**Comment by neikeq** [comment]
What version of Godot are you using? The issue looks very similar to #3046 which seems to have been fixed on master.

**Comment by mrzapp** [comment]
Apologies, I am using v2.1.2.

It might not be related to #3046 though, as double clicking a script works fine, it's the focusing on errors that still persists. But I will try out the master branch anyway.
