### ISSUE TITLE
Sound import error

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7755]
Tested on Godot 2.1.2, Windows 10 64 bits

From this QA thread, there are issues with audio importing: https://godotengine.org/qa/12172/sound-fx-are-showing-as-empty-in-godot-project

For example, a file (WAV 96000Hz) could not be imported, Godot logged this error:
```
ERROR: ResourceFormatLoaderWAV::load: Format not supported for WAVE file (not PCM). Save WAVE files as uncompressed PCM instead.
   At: scene\io\resource_format_wav.cpp:114
```
Edit: same with 48000Hz files as found by a user on Discord

So I normalized and exported from Audacity as WAV PCM, under a different name: [PistolDraw_reexport44n.zip](https://github.com/godotengine/godot/files/759380/PistolDraw_reexport44n.zip)
But Godot still can't import it.
Weirder, converted to OGG under another different name, still can't import it, the same error happens.

With the following settings each time;
![image](https://cloud.githubusercontent.com/assets/1311555/22717790/584cb032-ed9d-11e6-9701-db2da1e2b2e5.png)

This error is logged:
```
ERROR: EditorSampleImportPlugin::import: Condition ' smp.is_null() ' is true. returned: ERR_CANT_OPEN
   At: tools\editor\io_plugins\editor_sample_import_plugin.cpp:423
```

The only thing that works is using the WAV file directly without import, provided that it was converted manually beforehand (which makes the importer useless).

I know sound is being reworked for 3.0 as well as a part of the import system, but I don't think this was changed yet?

**Comment by freemanfromgodotengine** [comment]
Yeah, audio converting could be much better in Godot, like I stated in #6964
But frankly - I am not a developer, just a user of Godot, so it's just imho - importing or even creating at first WAV files in 96000Hz resolution for games would be a waste of disk space and time.
Second, if I had to convert anything from 96000 Hz, I would rather use dedicated, high quality algorithms, for example one available in [SoX](http://sox.sourceforge.net/), than ask game engine developers to have such technology on board of Godot.
That way the sound quality will be the best available and game engine developers do not have to spend time on a very complex subject, programing things that will not be used or appreciated by 99.99% of game developers.
Just my $0.02

**Comment by Zylann** [comment]
Well I'm not saying that 96KHz is a good choice, it's just that sound files can be in a lot of different formats. Sometimes people just pick random sounds online for rapid prototyping, and while I saw Unity being able to eat anything, Godot is really picky to the point you have to pre-import stuff in Audacity^^"
If I had choice I would have only FLAC sounds as sources for those I do myself, but I don't think Godot supports FLAC import either :p

**Comment by freemanfromgodotengine** [comment]
I know what you are saying and the error you got is a good find, so it should be fixed somehow, even if only by pop-up informing user to use some proper converter instead. ;)

**Comment by marcelofg55** [comment]
Is this still an issue? I've tried to import that PistolDraw_reexport44n wav file and it worked fine.

**Comment by Zylann** [comment]
i think that one was supposed to work because i reexported it, good it works now.
but is the original sound also working? is it planned to support more of input formats so that it doesn't need this "pre-import" extra step?

**Comment by marcelofg55** [comment]
Could you attach the original wave file so I can try it out? I didn't see it in the first post

**Comment by Zylann** [comment]
It is in the QA thread: http://www.mediafire.com/file/w2a5ln4b52ul1y2/Pistol.zip

**Comment by marcelofg55** [comment]
Oh, didn't see that before, I've just tested them all and they all work fine now.

**Comment by Zylann** [comment]
Did you try by importing them? Do they work in 3.0?

**Comment by akien-mga** [comment]
Assumed fixed by #9983 and #10015.

**Comment by laverneth** [comment]
I still have a similar issue with a fresh 2.1 built from the sources. In my case the problem was linked to the folder where the .wav files where for the importer (in a folder/Desktop/LittleShadows1_sounds). I'm on linux and I just place them on the desktop and the import worked fine. Weird.
