### ISSUE TITLE
Point Sprites: POINT_SIZE / POINT_COORD not working in shader

### ISSUE THREAD

**Issue by Skyfish1** [godotengine/godot#7824]
**Operating system or device - Godot version:**
- Windows 7 64 Bit - NVIDIA GTX 760 (Desktop) - Godot_v2.1.2-stable_win64.exe
- Windows 7 64 Bit - NVIDIA Quadro K1100M (Laptop) - Godot_v2.1.1-stable_win64.exe

**Issue description:**
I use an ImmediateGeometry to render some random point cloud. I set a shader material

Expected: setting POINT_SIZE in Vertex Shader should increase point size
What I get: POINT_SIZE has no effect on my Desktop but on my Laptop.

Expected: using POINT_COORD in Fragment Shaders should give me either multicolored squares if I use:

`DIFFUSE = vec3(POINT_COORD.x, POINT_COORD.y, 1);`

like in this example I found: 
![image](https://cloud.githubusercontent.com/assets/25827515/23036336/b6326e80-f482-11e6-9ec6-76eb06e84869.png)

or a textured point sprite if I use:

```
uniform texture star;
DIFFUSE = tex(star, POINT_COORD).rgb;
```
like in this example:
![image](https://cloud.githubusercontent.com/assets/25827515/23036353/c95d108c-f482-11e6-808f-f0e25cdcd0c5.png)

What I get: black squares on my Laptop or black dots on my Desktop:
![image](https://cloud.githubusercontent.com/assets/25827515/23036426/1618f468-f483-11e6-8a4f-5793487cb806.png)

**Steps to reproduce:**
Start the attached projekt. You should either get black squares or black dots around white plane.

**Link to minimal example project:**
[PointSpritesTest1.gz](https://github.com/godotengine/godot/files/781200/PointSpritesTest1.gz)

.

**Comment by Skyfish1** [comment]
I got POINT_COORD to work on my Laptop in LibGDX Engine with  gl.glEnable( 0x8861 ). Is there a way in godot to set glEnable?

**Comment by bojidar-bg** [comment]
I think this might have been fixed in d6567010bf1c65abcbe09b959cde63664778d923, as it added a material flag for "Use point size", but I'm not sure... Can you check again on master/3.0?

**Comment by Skyfish1** [comment]
Is there a compiled version somewhere? Or do I have to compile myself from source.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@bojidar-bg  this is still an issue for 3.0.2 . There is no way to turn `USE_POINT_SIZE` flag from shader. You need to create a SpatialMaterial then tick `[v] Use Point Size` then make a new 2nd pass shader then `POINT_SIZE` will start to work

**Comment by Skyfish1** [comment]
With Godot 3.0.6 I got Point Sprites working. Although on a new Laptop - I don't have my old one anymore. So I guess Issue can be closed. It may still exist on Godot 2. I didn't check.

![image](https://user-images.githubusercontent.com/25827515/50550796-f0f87600-0c76-11e9-9914-914e736e2703.png)
