### ISSUE TITLE
Animation travel not working when an animation is looped

### ISSUE THREAD

**Issue by jordanlis** [godotengine/godot#79208]
### Godot version

4.1

### System information

Windows 10

### Issue description

Hi, 

I think there's an issue with looping animation and traveling in the animationtree. I think there weren't any issue in the 4.1 RC 2, or previous builds. 

I tested it and it was working perfectly fine in the previous build 4.0.3, but not in the 4.1 RC2

There's somewhere an issue with loop animation and travel in animationTree which is incompatible now...

### Steps to reproduce

- you set up an animation an select the "loop" option
![image](https://github.com/godotengine/godot/assets/68544949/b4ffcbbd-8278-496a-b917-3058686749e8)
![image](https://github.com/godotengine/godot/assets/68544949/f9696571-3a64-40f1-a0b4-a47eafd16758)
- you make a traveling state machine with an animationtree and activate transitions
![image](https://github.com/godotengine/godot/assets/68544949/042ea2bc-bb79-486a-800f-aed1a4dabd09)
![image](https://github.com/godotengine/godot/assets/68544949/18d77670-2d3e-48dd-bc95-cbe365e1e9aa)
- Make the travel transition to "At end"
![image](https://github.com/godotengine/godot/assets/68544949/0100d728-124d-42a8-b1ea-953e0fb62962)

- you launch the animation with the tree, then try in code with the state machine to travel to the next animation

Expected : the travel is done and the loop is over

Current : not working, the travel doesn't work

Again, was working perfectly fine with 4.0.3. Currently on 4.1 : seems to work with transition "Immediate". The bug is only for "at end" transitions.

### Minimal reproduction project

don't have one at the moment, too complicated to create (because I need to make the code and so on)

**Comment by viksl** [comment]
Please make a Minimal Reproduction Project so someone can test this. :)

**Comment by AThousandShips** [comment]
Agreed, please add a minimal reproduction project:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by jordanlis** [comment]
Sorry, I did et have time to make a project. If I make a project, and that we test it inside the animation tree by clicking the button, is that okay. It doesn't work with the travel function in code but I think that's the same with the play button in the animation tree.

**Comment by uguu-org** [comment]
I have a similar problem with transitions in `AnimationTree`, where auto advance doesn't work if animation is looping.  Attached is a project that demonstrates this behavior.

[animation_test.zip](https://github.com/godotengine/godot/files/12010056/animation_test.zip)

1. Open project in Godot 4.0.3
2. Click on AnimationTree in gomako/gomako.tscn
3. Observe that "idle" state eventually transitions to "yawn" state.

https://github.com/godotengine/godot/assets/2000051/ad1822a4-1eee-4da6-8072-ead7244867b4

4. Open the same project in Godot 4.1
5. Click on AnimationTree in gomako/gomako.tscn
6. Observe that we are stuck looping in "idle" state.

https://github.com/godotengine/godot/assets/2000051/84cc6760-5964-4898-8caa-4120153e450d

Note that even in Godot 4.0.3, we will get stuck if Xfade Time is set to zero.  It's possible to workaround this by disabling loop bit for the ones where we want the animation state to travel, but then those animations won't loop outside of AnimationTree.

**Comment by jordanlis** [comment]
It seems to be the same issue, but I don't understand what's the transition view that you have.

On my side, it can be seen in the animation tree : you click on play and the transition / travel doesn't happen
Is that okay with this project or should I upload mine??

**Comment by viksl** [comment]
@jordanlis preferably prepare a simple test project stripped of everything but bare minimum. These can be same issues or different. Test projects are needed to test these cases. Check what @AThousandShips asked of you above for instructions.

**Comment by jordanlis** [comment]
OK I'll spend some time preparing a demo it need to be fixed.

**Comment by uguu-org** [comment]
@jordanlis that's the "auto advance" bit.  But I could also do it with a state machine, attached:

[animation_test2.zip](https://github.com/godotengine/godot/files/12016841/animation_test2.zip)

https://github.com/godotengine/godot/assets/2000051/8e9a89c3-2c87-4767-b3d0-dbb1cff79e34


https://github.com/godotengine/godot/assets/2000051/70dd9777-50a2-4556-aacb-d082d7a4a7c9

**Comment by TokageItLab** [comment]
I remember this is an intended change. You can use `statemachine_playback.next()` to break out of the loop

**Comment by viksl** [comment]
@TokageItLab How do you break out of a looped animation at the end of that animation, next breaks immediately and looped animaitons don't trigger signals? That sounds like what they want to do.

**Comment by TokageItLab** [comment]
There are several ways to break out of the loop:

1. Use next() with AutoAdvance disabled (equivalent to using next() with AtEnd)
2. Use AdvanceCondition with Immediate mode
3. Use method track to place a function like loop_ended() before the end of the loop animation (just before the length of the xfade) to manage the possible states on the GDScript side for example:
```gdscript
func loop_ended()
	if (character.can_transition):
		statemachine_playback.next()
```

**Comment by viksl** [comment]
@TokageItLab I hope I'm not misunderstanding. I gave it a try and the 1/ did not wait until the end of the transition be it with or without AtEnd. Am I missing something, please?

**Comment by TokageItLab** [comment]
I can't see what you are trying. Even if it is 1 and 2, the xfade time of the transition should be respected. Although, there is no wait for the animation to end, so the user must determine if the animation has looped one loop or not.

**Comment by TokageItLab** [comment]
> Use next() with AutoAdvance disabled (equivalent to using next() with AtEnd)

I was a bit wrong about this. Actually they are not equivalent.

next() does not go to the next state unless there is an explicit path there. So if you want to use next(), you need to create a path to the next state with travel() or have a path to the next state with AutoAdvance before you use next().

**Comment by jordanlis** [comment]
I don't understand where there was any need to prevent the system to allow a transition in the state machine. For me it's a bug --> In the interface, the transition are not happening, what's the need behind the change ? 

Now, it's not possible to transition from one state to another in auto mode ? In code, we need to do that with "next" which is not even waiting for the end frame to happen ?
Please, could you help me by clarifying the solution to have a looped animation and transition to the next state ( and waiting for the animation first animation to end) ?

It feels like a gaz factory for nothing... Why did you even do that ? I checked in the mentioned issue and nowhere it is said that the travel function must not work when the animation is looped...

Don't want to be rude or anythting, I'm just expressing something here that doesn't feel good for me.

**Comment by TokageItLab** [comment]
> what's the need behind the change ?

This was a necessary change for nested StateMachine to xfade correctly.

In order to determine the end time of a StateMachine from outside the StateMachine, the StateMachine must have an infinite time length while it is looping. The looping animation should also have an infinite time length to be consistent with it.

Before the AnimationStateMachine rework, the loop was broken by AtEnd even though it was looping, but the looping process is redundantly and redundantly implemented in the AnimationNodeStateMachine, which is separate from the AnimationNodeAnimation, and it is not a backward loop or a pause in the looping process. In addition, it did not correctly handle backward loops and pingpong loops, so it was just breaking down.

> Please, could you help me by clarifying the solution to have a looped animation and transition to the next state ( and waiting for the animation first animation to end) ?

The implementation of 3 I have described above should work most closely with what you are intending to do. However, it is a bit tedious, and I have heard that @SaracenOne is currently working on a new SwitchMode implementation that will perform transitions when a specified time has elapsed, so it may be better to use that in the future.

However, while they may solve the problem for AnimationNodeStateMachine, they may not solve the problem for AnimationNodeTransition.

> Note that even in Godot 4.0.3, we will get stuck if Xfade Time is set to zero. It's possible to workaround this by disabling loop bit for the ones where we want the animation state to travel, but then those animations won't loop outside of AnimationTree.

To be honest, this is the cleanest way to go. However, it is not good way because Animation or AnimationTree as a Resource may be referenced by multiple Nodes.

So, in my opinion, it would make sense to implement LoopModeOverride as a parameter of AnimationNodeAnimation, since the AnimationNode parameter is stored in each AnimationTree as a node. This allows us to manage the loop state for each character, even if the same Animation or AnimationTree resource is used repeatedly. I will send a PR for this later.

**Comment by jordanlis** [comment]
Okay, not really sure to understand your first sentence.

Just to make sure that I understand : does your pr will allow looped animation + at end transition to travel to the next animation with 
- next function? 
- travel function? 
- pushing the play button in the animation tree?

Sorry, I feel that I don't understand everything so it's important for me that you clarify if you don't mind

from what I understand about the current solution I need to use next instead of travel and test if the animation has ended. I'll try to make something like that...

**Comment by TokageItLab** [comment]
No, looping animation is never AutoAdvanced by AtEnd, nor should it be.

This problem is not something that should be solved by the StateMachine, but is fundamentally caused by the fact that AnimationTree lacks an API to manage the looping state of the Animation, so I will add a parameter to manage the looping state in #79400.

**Comment by jordanlis** [comment]
No, not autoadvance. Just manually in script or in the animationtree.you see what I mean?

**Comment by jordanlis** [comment]
I still don't get your solution. Your pr will allow to disable the looped animation, so if I Want to go from the looped animation to another, I won't be able to do it until I disable it? And then I have to reactivate it if I need to play it again... And I will be able to wait the end of the animation thanks to the script you put in 3 apparently.

I really think that all of this should really stay simple.

Like for example a parameter of the next() function that allows to force the transition.
example : next(override) or some think like this that allows to break the loop and continue to the next animation but wait for the atEnd transition.

What do you think?

**Comment by TokageItLab** [comment]
> example : next(override) or some think like this that allows to break the loop and continue to the next animation but wait for the atEnd transition.

It is not possible. Since the looping animation now has infinite length, it is no longer possible to detect the end of that animation on the StateMachine side. Nor does it solve anything in NodeTransition.

As I have explained many times, you can break out of the loop in several ways.

1. Using next() and MethodTrack. This is available in 4.1.
2. By PR of https://github.com/godotengine/godot/pull/79400, you disable the loop by a loop override in NodeAnimation. If you set the loop override of NodeAnimation to No Override after the transition, the next time you play the loop animation, the loop will be enabled again - This is different from changing the loop in AnimationPlayer's Animation, where no re-caching occurs and the loop state can be managed on a per-character basis.
3. Wait for future implementation of transitions elapsed time.

**Comment by jordanlis** [comment]
Ok, I just let go for now. 

I don't understand how to transition at the end of the looped animation with your solution (I'll try to understand by trying with the code you gave, but I don't see what it does and where to put that)

Next function is just breaking the loop in my code, and the downside is that it triggers other animation when not needed (it seems to look for any available path, so weird things are done now...)

For me, the travel should just work and break the loop. That's it. I need to rework totally my code appearently, and I don't know how to make my state machine work with this new godot 4.x. 

Thanks for your time anyway.

**Comment by ratala321** [comment]
I had the same problem, what I did to solve it in one line of code : 
`state_machine.travel("myState")
state_machine.next()`

Make sure to add state_machine.next() to activate the travelling.
