### ISSUE TITLE
Screen-Space reflections (SSR) are semi-transparent.

### ISSUE THREAD

**Issue by WrobotGames** [godotengine/godot#79549]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### The screen space reflections are semi-transparent.
The problem occurs on any reflective surface (any material with a low roughness). The reflection seems to be more transparent the darker the color of the reflected object.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/287f0a28-a4c1-4143-a3c1-a33c4d279efb)
The sky should not shine through the reflection of the 2 cubes.

### Here are a few examples of what the reflections should look like
(Blender Eevee)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/1d384851-5816-4ea1-8e5e-41e2a98576ff)
(Blender Eevee, with the mirror is tinted red to show whats reflection and whats not)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/256b4190-73be-4df8-ad5f-694af796de60)
(Blender cycles)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/ae3c052a-1cf6-43b7-966a-b41cbb79ddae)

### Steps to reproduce

1. Create a mirror like object by setting the roughness to 0 and the metallic to 1 on the material.
(The issue shows up in every single material with a low roughness, but it becomes really clear with this material.)
2. Enable SSR and the issue should be visible. If not, set max steps to the highest possible and set fade in/out to 0.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@WrobotGames Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (While you're at it, please also upload the equivalent Blender project :slightly_smiling_face:)

Also, can you reproduce this in 3.5.2?

**Comment by WrobotGames** [comment]
### Reproduction projects including Godot 3 / extra examples.
The following screenshots came from Godot 4, Godot 3, Blender Eevee and Blender Cycles. I took a screenshot from 2 sides because the issue is more visible from one side in Godot 4. The issue does not show up in Godot 3.5.2.

**Godot 4:**
![afbeelding](https://github.com/godotengine/godot/assets/66079814/40a326a4-6e68-402a-8916-a2ed5df04677)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/76d0a137-ef15-41d8-808c-191393f9ec67)
**Godot 3:**
Godot 3s screen space reflections don't show color when the reflecting surface isn't metallic. It also doesn't work well with roughness, this is visible in the 'puddles'.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/2984ab42-f752-453e-9448-c5289d179ffd)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/b3a879ae-f869-4ff7-888e-c0771c8584b2)
**Blender Eevee:**
Semi-real time screen space reflections.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/cbc0af88-6881-479c-b544-b75bae3927ac)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/ed2b446a-1538-423f-9000-1ef62a771e0f)
**Blender Cycles:**
Path traced reflections.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/b544f51b-6c16-41e4-9857-fa6ad387cf76)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/695f09ed-b247-482e-a039-4d7d0e4564bc)

### Projects download:
[Godot3.zip](https://github.com/godotengine/godot/files/12068506/Godot3.zip)
[Godot4.zip](https://github.com/godotengine/godot/files/12068507/Godot4.zip)
[Blender.zip](https://github.com/godotengine/godot/files/12068512/Blender.zip)

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by mandryskowski** [comment]
First, note that the reflections on the three horizontal quads are not due to SSR (from what I gathered they come from IBL on the cubemap).
The following screenshot has been taken with SSR off:

![image](https://github.com/godotengine/godot/assets/19364312/e16afd3f-ab65-4b19-a403-b5ba47605e5e)

SSR is a post-processing effect so it is applied on top of what is seen here. The [SSR shader](https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/shaders/effects/screen_space_reflection.glsl) has an output alpha value responsible for the reflections' opacity.
In this example the Fresnel term affects the alpha value the most. I disabled the effect by commenting out a line at the end of the SSR shader like this:

		//final_color.a *= f0 + (1.0 - f0) * m; // Fresnel Schlick term.

And got this:

![image](https://github.com/godotengine/godot/assets/19364312/9430472b-fdb7-4864-af59-e2c81e379951)

This gives us more plausible results but we do not want to erase the Fresnel effect completely. In the real world, surfaces are more reflective when we look at them at small grazing angles which is exactly what this effect represents.
Looking at the code I discovered a bug with setting the F0 value in the shader (see PR #79624). This PR keeps the Fresnel but fixes it for metallic surfaces (the middle one):

![image](https://github.com/godotengine/godot/assets/19364312/f74e63c2-8cc9-4e34-8103-a8ab73dc9a94)
![image](https://github.com/godotengine/godot/assets/19364312/91b5c77e-7110-427d-be52-33be3f349f40)


Note that the non-metallic quad (on the right in all pictures except the last one where it is on the left) still shows a semi-transparent reflection. I guess you could hack it and tweak the F0 value based on roughness but it would not be physically correct.

**Comment by WrobotGames** [comment]
The alpha values coming from the SSR shader are indeed correct, with the Fresnel effect.

This transparency is not the problem, its the blending with the background reflection.
In this video is visible that the screen space reflections look right unless the HDRI reflections are enabled. 
![Gif showing the effect](https://github.com/godotengine/godot/assets/66079814/70a308f2-4c53-4371-a852-3db44fde017d)
The background reflection should never shine trough another reflection.

So... the reflection godot should show is only the screen space reflection when there is one and otherwise the sky.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/627bc6a1-aace-41e0-9b66-0f2f894ea4a7)
Taking the ssr from the 2nd image and everything else from the 1st image would result in something like the 3rd image.

The only time the reflections should be blended is when the reflective surface doesn't have a roughness of 0, of course.

**Comment by YuriSizov** [comment]
Fixed by https://github.com/godotengine/godot/pull/79624.

**Comment by WrobotGames** [comment]
The PR has really improved the look of the reflections in the metallic 'mirror', but the issue of the sky leaking isn't completely solved. 
For example the brightest parts of the hdri show up in the metallic mirror. (Captured in 4.2 dev, with PR)
![afbeelding](https://github.com/godotengine/godot/assets/66079814/5943d9a1-d4dd-4c2e-a201-1667aafdd255)

I'm not sure if this issue should be reopened. (Or if this is a new issue).

**Comment by Calinou** [comment]
I can confirm the sky reflection is still visible through, even at very low background energy:

![image](https://github.com/godotengine/godot/assets/180032/905606dc-8a4a-4bf6-8a07-9edfaecac31b)

The only way to get rid of it is to set **Reflected Light** to **Disabled**, but this disables all sky reflections.

**Comment by WrobotGames** [comment]
This issue is a lot less apparent now with the pr. (The issue is gone when setting fade in/out to 0) But its kinda still there with the default settings. (This may be the expected behavior though) Should the issue be closed?

**Comment by Calinou** [comment]
> But its kinda still there with the default settings.

That's expected, as SSR isn't fully opaque with the default settings due to fade in/out.

I think this has been resolved to the best of our abilities given the default settings (which we can't change to preserve existing projects' artistic intention).
