### ISSUE TITLE
StyleBoxFlat has a misaligned and poorly sized border when skewed.

### ISSUE THREAD

**Issue by mk56-spn** [godotengine/godot#79672]
### Godot version

4.1.1.stable.mono and 4.11.stable were tested

### System information

Fedora Linux 38 (Workstation Edition)

### Issue description

When I create a skewed romboid shape in Godot with the provided skew property in a StyleBoxFlat theme, the border does not properly align itself with the edge of the main "body" of the shape if the border is only applied to adjacent sides as such: 
![Screenshot from 2023-07-19 20-30-06](https://github.com/godotengine/godot/assets/74463310/da445502-486e-4164-b4ae-66f76671bc37)

As can be seen here, if the skew is positive it will cause overlap between the border and the body, if it is negative it will create a gap ( transparency has been added to the body to better see the overlap being caused

It does however render correctly on opposite  borders : 

![Screenshot from 2023-07-19 20-46-14](https://github.com/godotengine/godot/assets/74463310/33a0cea3-7dd4-4141-bbe8-a1bfab5624a5)

In addition to this the border on the axis that is being skewed ( in this case the X axis) does not preserve its size in pixels as it, in my opinion, should, as it is what one would expect if they have been using Figma, Inkscape or most other vector design software that people often prototype UI components in:

Inkscape: 
![Screenshot from 2023-07-19 20-35-15](https://github.com/godotengine/godot/assets/74463310/312651bf-f431-47e9-a4dc-b6b2d49d0a0e) 

And godot : 
![Screenshot from 2023-07-19 20-38-06](https://github.com/godotengine/godot/assets/74463310/9cb0a9fb-9fb0-477b-8b21-031af46b8cf0)

### Steps to reproduce

No usage explanation necessary, the supplied project just has to be opened to see the issues described.

### Minimal reproduction project

[skew.zip](https://github.com/godotengine/godot/files/12099057/skew.zip)

Note: 

this was all tested without anti aliasing. so it does not overlap with issue https://github.com/godotengine/godot/issues/61054

**Comment by Calinou** [comment]
For reference, StyleBoxFlat skewing was implemented in https://github.com/godotengine/godot/pull/58599. I don't know what would be the best way to fix this particular issues though.

**Comment by Rindbee** [comment]
The border and background seem to use different origins (which appear to be their respective center points), and the center of the background rectangle is not offset.

**Comment by Rindbee** [comment]
The border is stretched, so the thickness thinning is expected behavior. If you want to keep the thickness constant, you can change the border width.

![0](https://github.com/godotengine/godot/assets/30386067/b71c3f25-dc7c-47e9-9469-5657c8df11fd)

Perhaps an option can be provided, to preserve thickness (treat border width as border thickness).

**Comment by mk56-spn** [comment]
> The border is stretched, so the thickness thinning is expected behavior. If you want to keep the thickness constant, you can change the border width.
> 
> ![0](https://github.com/godotengine/godot/assets/30386067/b71c3f25-dc7c-47e9-9469-5657c8df11fd)
> 
> Perhaps an option can be provided, to preserve thickness (treat border width as border thickness).
> 
> 

I'm aware of why it's happening, it's just that it's not the desired outcome in most scenarios  and it's unintuitive to have to set a different border size to have equal thickness on each side which is why most other programs adjust  to keep it from happening. But yeah a setting would solve this ( imo should default to on ) 

In any case thanks for the prompt PR!

**Comment by mk56-spn** [comment]
Solved in https://github.com/godotengine/godot/pull/96285

**Comment by kleonc** [comment]
@akien-mga Note that this part reported here was not fixed/changed by #96285:

> In addition to this the border on the axis that is being skewed ( in this case the X axis) does not preserve its size in pixels as it, in my opinion, should, as it is what one would expect if they have been using Figma, Inkscape or most other vector design software that people often prototype UI components in:
> 
> Inkscape: ![Screenshot from 2023-07-19 20-35-15](https://private-user-images.githubusercontent.com/74463310/254676948-312651bf-f431-47e9-a4dc-b6b2d49d0a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMDY0NzksIm5iZiI6MTcyNjAwNjE3OSwicGF0aCI6Ii83NDQ2MzMxMC8yNTQ2NzY5NDgtMzEyNjUxYmYtZjQzMS00N2U5LWE0ZGMtYjZiMmQ0OWQwYTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDIyMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTdhYzhlM2QxNjRhZjMyYmQ2YmRjYmZiMTQ3MWZkMzE0ODk2YWZkNzUyNjViNDkzMWJlNWY2YTIyYTEyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Urhzo2jdRJEtFiIt8cuWu-L5FwWbOgMQSCv7tZORWlo)
> 
> And godot : ![Screenshot from 2023-07-19 20-38-06](https://private-user-images.githubusercontent.com/74463310/254677576-9cb0a9fb-9fb0-477b-8b21-031af46b8cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMDY0NzksIm5iZiI6MTcyNjAwNjE3OSwicGF0aCI6Ii83NDQ2MzMxMC8yNTQ2Nzc1NzYtOWNiMGE5ZmItOWZiMC00NzdiLThiMjEtMDMxYWY0NmI4Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDIyMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NjRjMjVmN2EzYWUzNzUwNTUzY2I0ZDY4Y2I4MmQ3NmE5NGM1NDAzZTFiMTQwY2I0ZTkwYTgyZTJmY2M4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVdneAldJOaMFrbWclx4LDYjcv6Z1vdaFxSxPqriQ24)
