### ISSUE TITLE
Quest 2 export in 4.2.dev2 not working

### ISSUE THREAD

**Issue by eelcor** [godotengine/godot#80120]
### Godot version

4.2.dev2

### System information

MacOS 13.5 - Godot 4.2.dev2 - Mobile

### Issue description
UPDATE: It is a Quest2 specific issue. I tried it using a regular renderer on a Android Samsung phone and it works fine in 4.2.dev2

Dear developers,

I was happy to see the XR action map working in 4.2.dev2. Unfortunately when I try to export to the Quest 2, the executable crashes on the Quest 2. Enabling debugging on the Quest 2 yields more information in version 4.1.1 of Godot than in 4.2.dev2 (see enclosed screenshots).

<img width="998" alt="Godot411" src="https://github.com/godotengine/godot/assets/3133763/219b3cee-65cd-4da8-8cb2-0af27376149e">
Debug messages from the quest 2 in 4.1.1

<img width="998" alt="Godot42dev2" src="https://github.com/godotengine/godot/assets/3133763/58d1af15-f66f-44f1-80fd-fd3b2cec8e80">
Debug messages from the quest 2 in 4.2.dev2

I tried several things to find more information:
- Renamed the export templates from 4.1.1 to 4.2dev2. Prevents crashing, but shows a black windowed screen on the quest 2.
- Used the changed files from 4.2dev2 (SCsub, config.py and OpenXR_api.cpp) to get the XR action map editor working in 4.1.1. This was stupid and did not work at all.
- Recompiled 4.2dev2. Didn't do anything.
- Tried different Android versions (30, 33, 34), which didn't work either.

I am not sure whether it is a MacOS specific issue. I haven't been able to test this on a Windows machine.

### Steps to reproduce

Just make a simple XR project, using a tutorial:
- A Node3D as root.
- XR Origin
- XRCamera3D pointing at the plane and capsule
- MeshInstance3D - Plane (10x10)
- MeshInstance3D - Capsule
- A simple OmniLight3D to light the scene.

Use standard white materials for the plane and capsule.

Loaded: XRTools, XR Loaders, Android build templates (need to change the version in gradle-wrapper.properties to 7.6 in the URL to get a working compile)
Settings: OpenXR Enabled in project settings, ASTC texture compression enabled
Export Settings: Android Export - Gradle build - Android target platform 33 - Godot OpenXR for Meta - XR Mode: OpenXR 

Connect Quest 2 headset via USB
Enable "deploy with remote debug" in the editor
Use the run remote to run the apk on the Oculus 2. 

In 4.1.1 this yields a basic scene you can navigate.  In 4.2.dev2 this crashes on the headset.

### Minimal reproduction project

Just extract the following files in a OpenXR42 directory and follow the steps written earlier.

[minimal project.zip](https://github.com/godotengine/godot/files/12230070/minimal.project.zip)

**Comment by eelcor** [comment]
Could it have some something to do with the following commit?

https://github.com/godotengine/godot/commit/29bbc17b48b6afed20c43967e9631b4e8cef04c2 , which has the following description:

Godot Android re-architecture
Decouples the Godot java entry point from the Android Fragment component. This enables the Godot component to be more easily reused across different types of Android components including Activities and Services.

Regards, 
Eelco

**Comment by clayjohn** [comment]
Cc @m4gr3d

**Comment by m4gr3d** [comment]
@eelcor This was indeed a regression introduced by the Android refactor. The issue has been resolved in https://github.com/godotengine/godot/pull/79681 and will be available in Godot 4.2 dev3.

**Comment by eelcor** [comment]
Thanks for the update!

I recompiled Godot and unfortunately I am still not able to run the application on the Quest2. It still crashes on startup. Any changes in the export templates as well?

Any ideas?
Kind regards,
Eelco

**Comment by eelcor** [comment]
Thank you!

**Comment by eelcor** [comment]
I recompiled both the android_release.apk and android_debug.apk and still crashes on the quest. I also see an android.source in the export templates, where can I find or generate that file?
