### ISSUE TITLE
GLES3: Godot game is not loading shadow_atlas_size defined in project settings

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#80186]
### Godot version

4.1.1-stable

### System information

Windows 10

### Issue description

When the project loads in editor, all the settings defined in project settings will be loaded over the default values, but when running the game nearly 95% of them will be ignored resulting in just loading the default settings.

here it's just loading only 4 variables from project setting and i have added the fifth in this pull request https://github.com/godotengine/godot/pull/80151
![image](https://github.com/godotengine/godot/assets/53877170/926168a6-e6d3-4983-b59d-7fd202db681d)

**Comment by WhalesState** [comment]
what about `rendering/2d/shadow_atlas/size` ? can you confirm that it's loaded on start ? i will search other 3d shadow settings if they are loaded too

**Comment by AThousandShips** [comment]
https://github.com/godotengine/godot/blob/237bd0a615df8a0e57bc3d299894abece7b43a0c/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L2609

**Comment by WhalesState** [comment]
this just loads it for vulkan, what about canvas_renderer_gles3 ? can you confirm that they loads in gles3 too ?

**Comment by AThousandShips** [comment]
Are you sure? This is the `rd` renderer, not the `forward` renderer AFAIK

**Comment by Calinou** [comment]
> Are you sure? This is the `rd` renderer, not the `forward` renderer AFAIK

`rd` (RenderingDevice) renderer code affects Forward+ and Mobile, but not Compatibility.

**Comment by WhalesState** [comment]
trust me i have tried it with the stable release using gles3 renderer and it doesn't load the `rendering/2d/shadow_atlas/size` will be ignored on startup

**Comment by AThousandShips** [comment]
Then it should be handled under the appropriate place in the compatibility renderer code

**Comment by WhalesState** [comment]
so i should load them in canvas_renderer_gles3 if something is messing for 2d, and also check the scene_renderer_gles3 if something is messing in 3d, right ?

**Comment by AThousandShips** [comment]
Yes exactly, look at the equivalent for rd and apply when applicable

**Comment by WhalesState** [comment]
https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp
most of the functions are left empty and it's just loading only 3 variables from project settings, this will require so much work and should be addressed in a new issue, i will just review the rasterizer_canvas_gles3 and push what's missing.

**Comment by WhalesState** [comment]
fixed in https://github.com/godotengine/godot/pull/80151, closing now

**Comment by akien-mga** [comment]
The bug is not fixed until that PR is merged, so it should be kept open. You can add "Fixes #80186" in the PR to clarify the relationship.
