### ISSUE TITLE
Crash / .tscn Corruption when moving Inherited Scenes

### ISSUE THREAD

**Issue by thygrrr** [godotengine/godot#82296]
### Godot version

4.1.2.rc1

### System information

Windows 11 - 4.1.1.stable, 4.1.2.rc1, 4.2.dev

### Issue description

When moving inherited scenes with their accompanying imported files, there are two scenarios where Godot "breaks" and may lose unsaved work.

Scenario 1:
- scenes are not open, editor 4.2 crashes to desktop, both 4.1 and 4.2 show an error once.
- error is actually inapplicable (nothing is broken)

Scenario 2:
- scenes are open
- editor does NOT crash, but does give some errors
- reopening the editor will show the data is corrupted
- the error message **is applicable**

### Steps to reproduce

Scenario 1:
![Scenario 1](https://youtu.be/vCBGSyJdksc)
- have the main scene open (reproduction.tscn) but NOT the cube-inherited-fbx.tscn
- move the cube-inherited-fbx and cube.fbx resources files to the designated folder while they are NOT open
- observe: there's an illegible error message behind the import progress bar
- observe: the editor **gives an incorrect error** on 4.1.2.rc1
- observe: the editor **crashes to desktop** on 4.2.dev
- observe: the editor gives an error message on open on 4.2.dev
- observe: unsaved work at the moment of crash may be lost
- observe: despite the error, everything works (?!?)

Scenario 2:
![Scenario 2](https://youtu.be/TXAk7vB-d9Q)
- have the main scene open (reproduction.tscn)
- have the cube-inherited-fbx scene open (cube-inherited-fbx.tscn)
- move the scenes and source files to the designated folder
- observe: the open scene is being auto-closed
- observe: there's an illegible error message behind the import progress bar
- observe: the editor does NOT crash to desktop
- close editor
- observe: error message on reopen project
- observe: scenes are now broken (the fbx inherited scene can no longer import)
- examine: the .tscn files involved, some of them will not reflect the move and reference a wrong packed scene.
- examile: sometimes, the .import file for the .fbx and the .tscn seem to reference nothing (corrupt file)

Example (cube-inherited-fbx.tscn)
```
[gd_scene format=3 uid="uid://bu60v0yuke6u"]

[node name="cube"]
``` 
*(end of file)*

Scenario 3:
- have NO scenes open
- move the scenes and source files to the designated folder
- observe: no crash, no corruption

### Minimal reproduction project

[bug-repro-crash-corrupt-inherited-scenes.zip](https://github.com/godotengine/godot/files/12713872/bug-repro-crash-corrupt-inherited-scenes.zip)

**Comment by Mickeon** [comment]
This should be fixed in master I believe?

**Comment by thygrrr** [comment]
I just checked my 4.2 build from master: I can no longer reproduce it.
Sorry about the report, my dev build just from ~15 hours earlier still showed the issue.

**Comment by thygrrr** [comment]
No repro as of df0a822323a79e1a645f0c6a17d51c7602f23166
