### ISSUE TITLE
ItemList add_item() Memory Leak Even With ItemList.clear() and ItemList.queue_free() Calls

### ISSUE THREAD

**Issue by CamarataM** [godotengine/godot#82596]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3713) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

Whenever ItemList.add_item() is called, memory usage increases for every item as expected. However, after ItemList.clear() or ItemList.queue_free() is called, memory usage still remains at the previous amount, increasing when new items are added to the ItemList. This causes a memory leak which is especially apparent if one is doing thousands of ItemList.add_item() calls every frame (even with clears), as memory will rapidly grow.

### Steps to reproduce

1. Launch the attached project below.
2. Monitor memory usage using Task Manager or Resource Monitor.
3. Observe how memory usage continuously climbs to and stays at around 1.3 GB, even with ItemList.clear() calls and a final ItemList.queue_free() call.
4. To test continuous queue_free()'s memory leak, set recreate_item_list on line 7 in item_list.gd to 'true'.

### Minimal reproduction project

[ItemListMemoryLeakTest Minimal Reproduction.zip](https://github.com/godotengine/godot/files/12775650/ItemListMemoryLeakTest.Minimal.Reproduction.zip)

**Comment by echowarp** [comment]
instead of item_list.queue_free(), you need to self.remove_child(item_list). The new list keeps getting added but never removed. So by 5000 iterations, you have 5000 children. This is what really is causing memory to skyrocket. 

The queue clear is a bit misleading and probably not doing what you meant since the list never has anything in it in the first place.

I modified this example slightly so that after another 5000 iterations after free, the object_count is printed again. 

Pre free at 5000 iterations, it was 2185
Post free at 5000 iterations, it does still show 2185
But then post-free at 10,000 iterations, it goes back down to 1180. Watching the performance graph it looks like it doesn't take nearly that long for the object count to go down, just a couple frames.

I don't know how it works under the hood, but I suspect that you need to allow a few iterations to pass before garbage collection actually shrinks the list.

**Comment by CamarataM** [comment]
> instead of item_list.queue_free(), you need to self.remove_child(item_list). The new list keeps getting added but never removed. So by 5000 iterations, you have 5000 children. This is what really is causing memory to skyrocket.
> 
> The queue clear is a bit misleading and probably not doing what you meant since the list never has anything in it in the first place.
> 
> I modified this example slightly so that after another 5000 iterations after free, the object_count is printed again.
> 
> Pre free at 5000 iterations, it was 2185 Post free at 5000 iterations, it does still show 2185 But then post-free at 10,000 iterations, it goes back down to 1180. Watching the performance graph it looks like it doesn't take nearly that long for the object count to go down, just a couple frames.
> 
> I don't know how it works under the hood, but I suspect that you need to allow a few iterations to pass before garbage collection actually shrinks the list.

Changing the finished code on line 46 of item_list.gd to
```
item_list.queue_free()
self.remove_child(item_list)
item_list = null
```
Doesn't seem to change the actual RAM consumption (still seeing 1.3GB after execution). Unless I'm misunderstanding, in my reproduction with the base code there will only ever be one instance of ItemList, the one initially added. Even if recreate_item_list is set to true, queue_free removes the node from the node tree (as confirmed with the remote viewer in the editor and via the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/nodes_and_scene_instances.html#creating-nodes) on removing nodes), so after the iterations are finished, the old one should be garbage collected and that memory should be freed (unless I'm misunderstanding something about how Godot garbage collects non-referenced nodes).

The node count doesn't change during execution, but does after the item list is removed (which makes sense, as I believe Godot is handling the node tree element additions and removals correctly, but potentially not handling the removal of the items in the C++ list Vector which ItemList uses). However, the problem I am reporting is about those removed nodes still taking up memory, even after the ItemList is either cleared, queue_free()'d, or some combination of those two.

**Comment by echowarp** [comment]
Sorry. It seems I didn't understand several things. Definitely, queue_free should remove it from the nodes also. I also tried a few other ways of clearing the memory that didn't help. I must have changed multiple things that prevented items from being added to the list before.

```
while item_list.item_count:
    item_list.remove_item(0)
```

Changing `add_item` to `move_item` actually doesn't solve the memory issue either. Still goes to 1.3GB despite not actually adding new items, but internally it's still creating a new item and removing one using `Vector.remove_at(idx)`.

Looking at the Item type though, it looks like `text_buf` may not get freed after being instantiated in the `Item.h` file. It's a `Ref<TextParagraph> text_buf;` so I think the original TextParagraph won't get deleted or reused.

I think Item needs a destructor in `item_list.h` around line 83 that removes text_buf.

**Comment by CamarataM** [comment]
This issue also occurs for TabBar and has been reported [here](https://github.com/godotengine/godot/issues/82611).

Looking at the structs at the locations mentioned by @echowarp, both ItemList's [Item](https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/scene/gui/item_list.h#L60) struct and TabBar's [Tab](https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/scene/gui/tab_bar.h#L63) struct are extremely similar and contain a Ref to TextParagraph and TextLine respectively, so that could explain why they both suffer from the same issue if that is what is causing the memory leak.

**Comment by echowarp** [comment]
I built from source with the latest head and only got 82.7MB of memory usage after the full 5000 iterations. No modifications necessary. Seems this leak must have been fixed already. I built on both Mac and Windows from the latest and neither leaked.

Out of curiosity, I tried explicitly adding
```
~Item() {
    text_buf.unref()
}
```
But there was no change in memory usage.

Setting the flag at the top of the project script to recreate the list does increase memory usage to 95MB consistently until the end, but I don't think this is a leak.

So, something changed from the release of 4.1 to the current head that seems to have fixed this.

**Comment by CamarataM** [comment]
Running the minimal reproduction on the latest release candidates 4.1.2 (v4.1.2.rc1.official [58f0cae4a]) and 4.2 (v4.2.dev5.official [e3e2528ba]), the bug still occurs, meaning that the bug was fixed somewhere between commit [e3e2528ba7f6e85ac167d687dd6312b35f558591](https://github.com/godotengine/godot/commit/e3e2528ba7f6e85ac167d687dd6312b35f558591) and [0ca8542329888e8dccba89d59d3b728090c29991](https://github.com/godotengine/godot/commit/0ca8542329888e8dccba89d59d3b728090c29991).

**Comment by Rubonnek** [comment]
I'm not able to reproduce this issue using a build at 4ebf67c12dcdffcb69242569c118a371a654b6ae.

**Comment by CamarataM** [comment]
> I'm not able to reproduce this issue using a build at [4ebf67c](https://github.com/godotengine/godot/commit/4ebf67c12dcdffcb69242569c118a371a654b6ae).

Yeah, this behaviour doesn't seem to happen in `Godot v4.5.beta6.mono`. Doing both the original 50,000 iterations and 500,000 iterations yields no visible increase in memory consumption. Thank you for testing it and letting me know! Closing the issue as solved.
