### ISSUE TITLE
Godot does not listen to microphones with over 2 channels

### ISSUE THREAD

**Issue by marc-weber1** [godotengine/godot#82823]
### Godot version

4.2 dev 5 [9ff46d0]

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - GLES3 (Compatibility) - Intel(R) UHD Graphics 620 () - Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 Threads)

### Issue description

When trying to listen to a microphone with 4 channels, godot returns this error:

```
E 0:00:06:0920   thread_func: WASAPI: unsupported channel count in microphone!
  <C++ Source>   drivers/wasapi/audio_driver_wasapi.cpp:877 @ thread_func()
```

Ideally it would just take the first 2 channels, or combine all channels into 1?

### Steps to reproduce

With a PC with a microphone with over 2 channels, create an AudioStreamPlayer, with an AudioStreamMicrophone in it, and route it to master.

Just notify me if you need to test code? I can recompile the engine.

### Minimal reproduction project

[mic test.zip](https://github.com/godotengine/godot/files/12811418/mic.test.zip)

**Comment by kus04e4ek** [comment]
Should be fixed by #90013. Can you test it?

**Comment by nekocarpet** [comment]
I still get this error in V4.2.2 stable and v4.3 dev6.
I'm using a built-in microphone on my laptop which has 4 channels.

https://github.com/godotengine/godot/issues/30313 is made a while ago also with a 4 channel mic.

**Comment by Moosil** [comment]
> Should be fixed by #90013. Can you test it?

Not sure if you've already tested it, but it does fix the issue.
