### ISSUE TITLE
Dlink-enabled web export broken with emscripten 3.1.45 (last known working version: 3.1.39)

### ISSUE THREAD

**Issue by PgBiel** [godotengine/godot#82865]
### Godot version

4.2.dev [57a6813bb8]

### System information

Godot v4.2.dev (57a6813bb) - `EndeavourOS #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 - X11 - GLES3 (Compatibility) - llvmpipe (LLVM 16.0.6, 256 bits) () - AMD Ryzen 7 5700G with Radeon Graphics (8 Threads)`

### Issue description

Hello,
I've been trying to debug WASM export with GDExtensions after the release of v4.2.dev6 (in a Linux OS), but I was using the official web export templates which don't appear to include the engine's debug symbols, so I decided to compile a web export template from source, checking out at what appears to be the latest commit to be included in v4.2.dev6 (57a6813bb8). However, when I use a **dlink-enabled** web template compiled from source at that commit, **any project fails to run** in the web (any project, even a very trivial and just created one, will do), displaying on the web browser console the errors I show below instead of the game (for both Chromium and Firefox). Disabling `dlink_enabled` works - a trivial project runs -, but then, of course, I can't test GDExtension without that option enabled.
Note that this occurs when compiling with or without debug symbols, with `template_debug` or `template_release`, and only when compiling from source (the official web export templates, downloaded through the v4.2.dev6 editor, appeared to be fine).

I've tested the export process throughout 3 different Linux distros (Debian 12 Podman container, EndeavourOS / Arch-based VM, NixOS bare metal), all with the same result. I've also tested compilation from source on both the Debian 12 container and on the EndeavourOS VM. I apologize in advance if I'm just missing some trivial flag or some other procedure (I'm mostly following the existing documentation).

The commands I've tried:
```
scons platform=web debug_symbols=yes dlink_enabled=yes target=template_debug
scons platform=web dlink_enabled=yes target=template_debug
scons platform=web dlink_enabled=yes target=template_release
```

Compiling with the command below _does_, however, work (produces a functional web export template):
```
scons platform=web target=template_debug
```

I've also compiled the editor at the same commit with:
```
scons platform=linuxbsd debug_symbols=yes target=editor
```
(Using the official v4.2.dev6 editor didn't work either.)

I'm using emsdk 3.1.45:

```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.45 (ef3e4e3b044de98e1811546e0bc605c65d3412f4)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The errors which appear on my Ungoogled Chromium v117 browser's console when trying to run the game (served on localhost with the official `serve.py` script in the Godot repository) are the following (similar errors appear on Firefox v118.0.1):

```
index.worker.js:24 worker.js onmessage() captured an uncaught exception: RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
threadPrintErr @ index.worker.js:24
index.worker.js:24 RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
    at getWasmTableEntry (index.js:4164:47)
    at Object.invokeEntryPoint (index.js:4175:15)
    at handleMessage (:8060/index.worker.js:123:35)
threadPrintErr @ index.worker.js:24
index.worker.js:24 worker.js onmesage() captured an uncaught exception: RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
threadPrintErr @ index.worker.js:24
index.worker.js:24 RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
    at getWasmTableEntry (index.js:4164:47)
    at Object.invokeEntryPoint (index.js:4175:15)
    at handleMessage (:8060/index.worker.js:123:35)
threadPrintErr @ index.worker.js:24
index.js:54496 Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
onPrintError @ index.js:54496
index.js:54496 Pthread 0x007b8a40 sent an error! http://localhost:8060/index.worker.js:155: Uncaught RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
onPrintError @ index.js:54496
index.js:3929 Uncaught ErrorEventisTrusted: truebubbles: falsecancelBubble: falsecancelable: truecolno: 5composed: falsecurrentTarget: Window {window: Window, self: Window, document: document, name: '', location: Location, …}defaultPrevented: falseerror: nulleventPhase: 0filename: "http://localhost:8060/index.worker.js"lineno: 155message: "Uncaught RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745"returnValue: truesrcElement: Window {window: Window, self: Window, document: document, name: '', location: Location, …}target: Window {window: Window, self: Window, document: document, name: '', location: Location, …}timeStamp: 1225.2700000004843type: "error"[[Prototype]]: ErrorEvent
index.worker.js:155 Uncaught RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
    at getWasmTableEntry (index.js:4164:47)
    at Object.invokeEntryPoint (index.js:4175:15)
    at handleMessage (index.worker.js:123:35)
index.js:54496 Pthread 0x008569b8 sent an error! http://localhost:8060/index.worker.js:155: Uncaught RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
onPrintError @ index.js:54496
index.js:3929 Uncaught ErrorEvent
index.worker.js:155 Uncaught RangeError: WebAssembly.Table.get(): invalid index 65417 into funcref table of size 7745
    at getWasmTableEntry (index.js:4164:47)
    at Object.invokeEntryPoint (index.js:4175:15)
    at handleMessage (index.worker.js:123:35)
```

### Steps to reproduce

1. Clone this repository
2. Ensure you have the necessary dependencies to build Godot (including emsdk 3.1.45, scons etc.)
3. Checkout to 57a6813bb with `git checkout --detach 57a6813bb8bc2417ddef1058d422a91f0c9f753c`
4. Compile the editor with `scons platform=linuxbsd target=editor` (assuming Linux host)
5. Compile the web export template with `scons platform=web dlink_enabled=yes target=template_debug` - you may have to rename the resulting `bin/godot.web.template_debug.wasm32.dlink.zip` file to `bin/web_dlink_debug.zip`.
6. Open the editor, and either create a new project (Compatibility Renderer) or import `TestProject.zip` below
7. Export the project to the web (don't forget to select your main scene, if creating a new project), selecting as custom Debug web export template the `bin/web_dlink_debug.zip` file (or place the file in the usual `~/.local/share/godot/export_templates/4.2.dev/web_dlink_debug.zip` location). **Ensure "Extensions Support" is checked.**
8. Serve the exported web files at localhost using the `platform/web/serve.py` script (e.g. `cd` to where the project's main HTML file was exported to and run `python3 /path/to/godot/platform/web/serve.py -r "$(realpath .)"`).
9. Open the game in your browser (preferably Chromium-based for more detailed errors) at `127.0.0.1:8060`
10. Expect it to run normally (show a spinning Godot icon), but instead it displays the errors listed above on the Web Developer console. (The exact error messages may differ depending on your browser, but should be at least similar.)

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/12820471/TestProject.zip)

**Comment by akien-mga** [comment]
Official templates are also built with `production=yes`, which enables LTO. This might be worth testing.

In https://github.com/godotengine/godot-cpp/pull/1247#issuecomment-1742125723 @Faless had different results based on whether LTO was enabled. But this should have been solved in 4.2-dev6 by #82633.

**Comment by PgBiel** [comment]
> Official templates are also built with `production=yes`, which enables LTO. This might be worth testing.
> 
> In [godotengine/godot-cpp#1247 (comment)](https://github.com/godotengine/godot-cpp/pull/1247#issuecomment-1742125723) @Faless had different results based on whether LTO was enabled. But this should have been solved in 4.2-dev6 by #82633.

Hello, thanks for the response! I compiled with `production=yes` (`scons platform=web production=yes dlink_enabled=yes target=template_release` and `template_debug`), and got different results, but still negative:

1. For the minimal reproduction project, execution goes 'further' (displays some audio warning and stuff), but still fails to run (vs. official build with which it runs normally) - here's the result on `template_release` for instance (it's similar on debug):

<details><summary>Browser Console Log</summary>
<p>

```

TestProject.js:54496 USER WARNING: Invalid mix rate of 0, consider reassigning setting 'audio/driver/mix_rate'.
TestProject.js:54496 Defaulting mix rate to value 44100.
at: _get_configured_mix_rate (servers/audio_server.cpp:126)

TestProject.worker.js:24 worker.js onmessage() captured an uncaught exception: RangeError: WebAssembly.Table.get(): invalid index 8671 into funcref table of size 7743
threadPrintErr @ TestProject.worker.js:24
handleMessage @ TestProject.worker.js:150

TestProject.worker.js:24 RangeError: WebAssembly.Table.get(): invalid index 8671 into funcref table of size 7743
    at getWasmTableEntry (TestProject.js:4164:47)
    at Object.invokeEntryPoint (TestProject.js:4175:15)
    at handleMessage (TestProject.worker.js:123:35)
threadPrintErr @ TestProject.worker.js:24
handleMessage @ TestProject.worker.js:151

TestProject.js:54496 Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
onPrintError @ TestProject.js:54496
warnOnce @ TestProject.js:4981
_emscripten_check_blocking_allowed @ TestProject.js:13303
$pthread_cond_timedwait @ 006d1dd6:0xb69db
$pthread_cond_wait @ 006d1dd6:0xd70f0
$_ZNSt3__221__libcpp_condvar_waitB7v160004EP14pthread_cond_tP15pthread_mutex_t @ 006d1dd6:0xfe3c2
$_ZNSt3__218condition_variable4waitERNS_11unique_lockINS_5mutexEEE @ 006d1dd6:0xfe38e
$func10965 @ 092cb0de:0x798378
$func11137 @ 092cb0de:0x7a59f8
$func11084 @ 092cb0de:0x7a0a6e
$func11088 @ 092cb0de:0x7a0c4f
$func11043 @ 092cb0de:0x79e6cd
$func11291 @ 092cb0de:0x7abf4e
$func11290 @ 092cb0de:0x7abea1
$func11312 @ 092cb0de:0x7ae56f
$func11313 @ 092cb0de:0x7aea87
$func53969 @ 092cb0de:0x164ac38
$func1877 @ 092cb0de:0x32fef3
$func1797 @ 092cb0de:0x2d678a
$func1333 @ 092cb0de:0x28dc52
$_Z14godot_web_mainiPPc @ 092cb0de:0x27fd5f
__Z14godot_web_mainiPPc @ TestProject.js:4989
$__main_argc_argv @ 006d1dd6:0xa9aff
callMain @ TestProject.js:53972
(anonymous) @ TestProject.js:54819
(anonymous) @ TestProject.js:54814
Promise.then (async)
(anonymous) @ TestProject.js:54813
Promise.then (async)
start @ TestProject.js:54792
(anonymous) @ TestProject.js:54855
Promise.then (async)
startGame @ TestProject.js:54854
(anonymous) @ TestProject.html:224
(anonymous) @ TestProject.html:244

TestProject.js:54496 Invalid UTF-8 leading byte 0x00000088 encountered when deserializing a UTF-8 string in wasm memory to a JS string!
onPrintError @ TestProject.js:54496
worker.onmessage @ TestProject.js:3918

TestProject.js:54481 𳥀
TestProject.js:54481 X|m
TestProject.js:54481 ␜ဠ
```

</p>
</details>

2. It also fails to run my separate GDExtension testing project (where I'm experimenting with a `gdext`-based GDExtension), where I'm getting an error I don't get with the official builds: it says it can't find the entry symbol, but a `wasm-objdump` run seems to reveal the `.wasm` file _does_ contain the symbol. This could, of course, be a problem with `gdext` itself, but in the official builds I get an error which is probably unrelated to this issue (some stack overflow error which appears to occur inside some internal emscripten function). Here's the logs on my non-official build:

<details><summary>Browser Console Log (`template_debug`)</summary>
<p>

```
index.js:54496 USER ERROR: Can't resolve symbol gdext_rust_init. Error: Tried to lookup unknown symbol "gdext_rust_init" in dynamic lib: hello_gdext.wasm.
onPrintError @ index.js:54496

index.js:54496    at: get_dynamic_library_symbol_handle (drivers/unix/os_unix.cpp:674)
onPrintError @ index.js:54496

index.js:54496 USER ERROR: GDExtension entry point 'gdext_rust_init' not found in library ../rust/target/wasm32-unknown-emscripten/debug/hello_gdext.wasm
onPrintError @ index.js:54496

index.js:54496    at: open_library (core/extension/gdextension.cpp:733)
onPrintError @ index.js:54496
(index):212 table index is out of bounds
displayFailureNotice @ (index):212

index.js:54496 Invalid UTF-8 leading byte 0x00000088 encountered when deserializing a UTF-8 string in wasm memory to a JS string!
onPrintError @ index.js:54496

index.js:54481 𶳀

index.js:54496 Invalid UTF-8 leading byte 0x000000b0 encountered when deserializing a UTF-8 string in wasm memory to a JS string!
```

</p>
</details>

<details><summary>Browser Console Log (`template_release`)</summary>
<p>

```
index.js:54496 USER ERROR: Can't resolve symbol gdext_rust_init. Error: Tried to lookup unknown symbol "gdext_rust_init" in dynamic lib: hello_gdext.wasm.
onPrintError @ index.js:54496
put_char @ index.js:1312
write @ index.js:1264
write @ index.js:3085
doWritev @ index.js:18134
_fd_write @ index.js:18225
$func914 @ 006d1dd6:0xaacf3
$__vfprintf_internal @ 006d1dd6:0xe81bd
$vfprintf @ 006d1dd6:0xbfe48
$func71097 @ 092cb0de:0x1de285d
$func13731 @ 092cb0de:0xa01ba1
$func71093 @ 092cb0de:0x1de2633
$func71099 @ 092cb0de:0x1de29f7
$func554 @ 092cb0de:0x239cd5
$func798 @ 092cb0de:0x25a4af
$func13722 @ 092cb0de:0xa00c58
$func68289 @ 092cb0de:0x1cc0955
$func80652 @ 092cb0de:0x1fdd961
$func71417 @ 092cb0de:0x1e041b8
$func71476 @ 092cb0de:0x1e09aac
$func47755 @ 092cb0de:0x14f6dce
$func1860 @ 092cb0de:0x32c7f9
$func1737 @ 092cb0de:0x2c7681
$func1333 @ 092cb0de:0x2847c7
$_Z14godot_web_mainiPPc @ 092cb0de:0x27fd5f
__Z14godot_web_mainiPPc @ index.js:4989
$__main_argc_argv @ 006d1dd6:0xa9aff
callMain @ index.js:53972
(anonymous) @ index.js:54819
(anonymous) @ index.js:54814
Promise.then (async)
(anonymous) @ index.js:54813
Promise.then (async)
start @ index.js:54792
(anonymous) @ index.js:54855
Promise.then (async)
startGame @ index.js:54854
(anonymous) @ (index):224
(anonymous) @ (index):244

index.js:54496    at: get_dynamic_library_symbol_handle (drivers/unix/os_unix.cpp:674)
onPrintError @ index.js:54496
put_char @ index.js:1312
write @ index.js:1264
write @ index.js:3085
doWritev @ index.js:18134
_fd_write @ index.js:18225
$func914 @ 006d1dd6:0xaacf3
$__vfprintf_internal @ 006d1dd6:0xe81bd
$vfprintf @ 006d1dd6:0xbfe48
$func71097 @ 092cb0de:0x1de285d
$func13731 @ 092cb0de:0xa01ba1
$func71093 @ 092cb0de:0x1de2657
$func71099 @ 092cb0de:0x1de29f7
$func554 @ 092cb0de:0x239cd5
$func798 @ 092cb0de:0x25a4af
$func13722 @ 092cb0de:0xa00c58
$func68289 @ 092cb0de:0x1cc0955
$func80652 @ 092cb0de:0x1fdd961
$func71417 @ 092cb0de:0x1e041b8
$func71476 @ 092cb0de:0x1e09aac
$func47755 @ 092cb0de:0x14f6dce
$func1860 @ 092cb0de:0x32c7f9
$func1737 @ 092cb0de:0x2c7681
$func1333 @ 092cb0de:0x2847c7
$_Z14godot_web_mainiPPc @ 092cb0de:0x27fd5f
__Z14godot_web_mainiPPc @ index.js:4989
$__main_argc_argv @ 006d1dd6:0xa9aff
callMain @ index.js:53972
(anonymous) @ index.js:54819
(anonymous) @ index.js:54814
Promise.then (async)
(anonymous) @ index.js:54813
Promise.then (async)
start @ index.js:54792
(anonymous) @ index.js:54855
Promise.then (async)
startGame @ index.js:54854
(anonymous) @ (index):224
(anonymous) @ (index):244

index.js:54496 USER ERROR: GDExtension entry point 'gdext_rust_init' not found in library ../rust/target/wasm32-unknown-emscripten/debug/hello_gdext.wasm
onPrintError @ index.js:54496
put_char @ index.js:1312
write @ index.js:1264
write @ index.js:3085
doWritev @ index.js:18134
_fd_write @ index.js:18225
$func914 @ 006d1dd6:0xaacf3
$__vfprintf_internal @ 006d1dd6:0xe81bd
$vfprintf @ 006d1dd6:0xbfe48
$func71097 @ 092cb0de:0x1de285d
$func13731 @ 092cb0de:0xa01ba1
$func71093 @ 092cb0de:0x1de2633
$func71099 @ 092cb0de:0x1de29f7
$func554 @ 092cb0de:0x239cd5
$func792 @ 092cb0de:0x257ef5
$func68289 @ 092cb0de:0x1cc0a1d
$func80652 @ 092cb0de:0x1fdd961
$func71417 @ 092cb0de:0x1e041b8
$func71476 @ 092cb0de:0x1e09aac
$func47755 @ 092cb0de:0x14f6dce
$func1860 @ 092cb0de:0x32c7f9
$func1737 @ 092cb0de:0x2c7681
$func1333 @ 092cb0de:0x2847c7
$_Z14godot_web_mainiPPc @ 092cb0de:0x27fd5f
__Z14godot_web_mainiPPc @ index.js:4989
$__main_argc_argv @ 006d1dd6:0xa9aff
callMain @ index.js:53972
(anonymous) @ index.js:54819
(anonymous) @ index.js:54814
Promise.then (async)
(anonymous) @ index.js:54813
Promise.then (async)
start @ index.js:54792
(anonymous) @ index.js:54855
Promise.then (async)
startGame @ index.js:54854
(anonymous) @ (index):224
(anonymous) @ (index):244

index.js:54496    at: open_library (core/extension/gdextension.cpp:733)
onPrintError @ index.js:54496
put_char @ index.js:1312
write @ index.js:1264
write @ index.js:3085
doWritev @ index.js:18134
_fd_write @ index.js:18225
$func914 @ 006d1dd6:0xaacf3
$__vfprintf_internal @ 006d1dd6:0xe81bd
$vfprintf @ 006d1dd6:0xbfe48
$func71097 @ 092cb0de:0x1de285d
$func13731 @ 092cb0de:0xa01ba1
$func71093 @ 092cb0de:0x1de2657
$func71099 @ 092cb0de:0x1de29f7
$func554 @ 092cb0de:0x239cd5
$func792 @ 092cb0de:0x257ef5
$func68289 @ 092cb0de:0x1cc0a1d
$func80652 @ 092cb0de:0x1fdd961
$func71417 @ 092cb0de:0x1e041b8
$func71476 @ 092cb0de:0x1e09aac
$func47755 @ 092cb0de:0x14f6dce
$func1860 @ 092cb0de:0x32c7f9
$func1737 @ 092cb0de:0x2c7681
$func1333 @ 092cb0de:0x2847c7
$_Z14godot_web_mainiPPc @ 092cb0de:0x27fd5f
__Z14godot_web_mainiPPc @ index.js:4989
$__main_argc_argv @ 006d1dd6:0xa9aff
callMain @ index.js:53972
(anonymous) @ index.js:54819
(anonymous) @ index.js:54814
Promise.then (async)
(anonymous) @ index.js:54813
Promise.then (async)
start @ index.js:54792
(anonymous) @ index.js:54855
Promise.then (async)
startGame @ index.js:54854
(anonymous) @ (index):224
(anonymous) @ (index):244

(index):212 null function or function signature mismatch
```

</p>
</details> 

Overall, the most concerning part for me is that it still can't run the sample project which doesn't contain any GDExtension usage at all.

**Comment by Esption** [comment]
I can reproduce this with the [godot chess](https://godotengine.org/asset-library/asset/1863) example and the same commit of (57a6813), emcc version 3.1.45
Interestingly, a template built with dlink turned off works perfectly fine. Switched over and tried a dlink export with 4.1.1 engine/template and it works just fine.  Mind you, that project doesn't actually make use of gdextension, just purely using that box to enable it.  It seems like something since 4.1.1 and dev has made enabling dlink fail at runtime.

**Comment by PgBiel** [comment]
Interesting observations @Esption . I decided to test the latest 4.1.x versions and (shiver me timbers!) they didn't seem to work either! In particular:

- **4.1.2** (`4.1.2-stable` tag): Built editor from source, and also `production=yes dlink_enabled=yes` web template, and got the same errors both with and without GDExtension usage (with some new errors on the test _with_ GDExtension usage).
- **4.1.1** (`4.1.1-stable` tag): Built editor from source, and also `production=yes dlink_enabled=yes` web template, and same thing (errors on both tests). (Note, however, that I used emsdk 3.1.45 here, while 3.1.18 was still used at that time, so I have to test that too.)

I haven't yet tested without LTO for those (maybe this could make a difference). I'll update this comment if I get to doing those tests (they take a bit with all the compilation involved :sweat_smile:).

**Comment by Faless** [comment]
> So perhaps this is a problem with the recent emsdk versions?

Yep, I can confirm also the current `4.2-dev` works when built with emsdk 3.1.18, but does not with 3.1.46.

**Comment by Faless** [comment]
Also please note that there seem to be a Firefox bug causing GDExtension not to work.
I.e. `dlink_enabled` builds runs, but if you actually use an extension the page doesn't load on Firefox. Only Chrome seems to work (safari is untested), see: https://github.com/webcompat/web-bugs/issues/127798

**Comment by PgBiel** [comment]
Okay, I have **bisected the problem to Emscripten 3.1.40** (v3.1.39 was the last working version on my tests). Others may want to confirm.

On each test, while having checked out `57a6813bb8` (the latest commit in 4.2-dev6) in my Debian 12 container, I compiled the web template with
`scons platform=web production=yes dlink_enabled=yes debug_symbols=yes target=template_debug`

- 3.1.18: Couldn't compile (Godot wanted some LLVM 18 attribute or something. Maybe just too outdated now?)
- 3.1.31: Compiled, **test project worked.**
- 3.1.38: Compiled, **test project worked.**
- 3.1.39: Compiled, **test project worked.**
- 3.1.40 - 3.1.41: Compiled, **test project gave bad table error**.
- 3.1.42 - 3.1.45: Compiled, **test project couldn't find TestProject.pck** (? - the file is there).
  - No idea why I'm getting this on those versions now (this wasn't happening with 3.1.45 even). Could be some impurity regarding dependencies in my container, but that would require more tests.
  - Here are the full logs I got on one of these tests (the others are pretty much identical).
  
<details><summary>Logs for the index.pck problem</summary>
<p>

```
index.js:54814 USER ERROR: Cannot open resource pack 'index.pck'.
onPrintError @ index.js:54814
put_char @ index.js:1304
write @ index.js:1256
write @ index.js:3053
doWritev @ index.js:18188
_fd_write @ index.js:18279
$__stdio_write @ 00b36e7e:0xaade5
$__vfprintf_internal @ 00b36e7e:0xe83d3
$vfprintf @ 00b36e7e:0xbfe85
$StdLogger::logv(char const*, void*, bool) @ 0cb0f366:0x246e617
$Logger::logf_error(char const*, ...) @ 0cb0f366:0xbfc596
$Logger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType) @ 0cb0f366:0x246e3c5
$CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType) @ 0cb0f366:0x246e7b1
$_err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) @ 0cb0f366:0x29296d
$_err_print_error(char const*, char const*, int, char const*, String const&, bool, ErrorHandlerType) @ 0cb0f366:0x2bc4d7
$ProjectSettings::setup(String const&, String const&, bool, bool) @ 0cb0f366:0x32c24d
$Main::setup(char const*, int, char**, bool) @ 0cb0f366:0x2f125b
$godot_web_main(int, char**) @ 0cb0f366:0x2edbd8
__Z14godot_web_mainiPPc @ index.js:4960
$main @ 00b36e7e:0xa9bf1
callMain @ index.js:54290
(anonymous) @ index.js:55137
(anonymous) @ index.js:55132
Promise.then (async)
(anonymous) @ index.js:55131
Promise.then (async)
start @ index.js:55110
(anonymous) @ index.js:55173
Promise.then (async)
startGame @ index.js:55172
(anonymous) @ (index):224
(anonymous) @ (index):244

index.js:54814    at: _setup (core/config/project_settings.cpp:534)
onPrintError @ index.js:54814
put_char @ index.js:1304
write @ index.js:1256
write @ index.js:3053
doWritev @ index.js:18188
_fd_write @ index.js:18279
$__stdio_write @ 00b36e7e:0xaade5
$__vfprintf_internal @ 00b36e7e:0xe83d3
$vfprintf @ 00b36e7e:0xbfe85
$StdLogger::logv(char const*, void*, bool) @ 0cb0f366:0x246e617
$Logger::logf_error(char const*, ...) @ 0cb0f366:0xbfc596
$Logger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType) @ 0cb0f366:0x246e3e9
$CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType) @ 0cb0f366:0x246e7b1
$_err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) @ 0cb0f366:0x29296d
$_err_print_error(char const*, char const*, int, char const*, String const&, bool, ErrorHandlerType) @ 0cb0f366:0x2bc4d7
$ProjectSettings::setup(String const&, String const&, bool, bool) @ 0cb0f366:0x32c24d
$Main::setup(char const*, int, char**, bool) @ 0cb0f366:0x2f125b
$godot_web_main(int, char**) @ 0cb0f366:0x2edbd8
__Z14godot_web_mainiPPc @ index.js:4960
$main @ 00b36e7e:0xa9bf1
callMain @ index.js:54290
(anonymous) @ index.js:55137
(anonymous) @ index.js:55132
Promise.then (async)
(anonymous) @ index.js:55131
Promise.then (async)
start @ index.js:55110
(anonymous) @ index.js:55173
Promise.then (async)
startGame @ index.js:55172
(anonymous) @ (index):224
(anonymous) @ (index):244

index.js:54799 Error: Couldn't load project data at path ".". Is the .pck file missing?

index.js:54799 If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).

index.js:54814 Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
onPrintError @ index.js:54814
warnOnce @ index.js:4952
_emscripten_check_blocking_allowed @ index.js:13275
$__pthread_join @ 00b36e7e:0xd9798
$std::__2::__libcpp_thread_join[abi:v160004](unsigned long*) @ 00b36e7e:0x13abb0
$std::__2::thread::join() @ 00b36e7e:0x13ab8f
$Thread::wait_to_finish() @ 0cb0f366:0x2932f9
$IP::~IP() @ 0cb0f366:0xbf0b74
$unregister_core_types() @ 0cb0f366:0x34479e
$Main::setup(char const*, int, char**, bool) @ 0cb0f366:0x2f65bc
$godot_web_main(int, char**) @ 0cb0f366:0x2edbd8
__Z14godot_web_mainiPPc @ index.js:4960
$main @ 00b36e7e:0xa9bf1
callMain @ index.js:54290
(anonymous) @ index.js:55137
(anonymous) @ index.js:55132
Promise.then (async)
(anonymous) @ index.js:55131
Promise.then (async)
start @ index.js:55110
(anonymous) @ index.js:55173
Promise.then (async)
startGame @ index.js:55172
(anonymous) @ (index):224
(anonymous) @ (index):244

index.js:54814 Invalid UTF-8 leading byte 0x00000088 encountered when deserializing a UTF-8 string in wasm memory to a JS string!
onPrintError @ index.js:54814
worker.onmessage @ index.js:3883

index.js:54799 𰭀
```

</p>
</details>

**Comment by bobziuchkovski** [comment]
I've also been testing various emscripten versions for a c++ gdextension project. The only version of emscripten I've found that compiles, loads, and correctly executes my c++ gdextension is **3.1.28**.

In my testing, emsdk versions up to 3.1.27 fail with `null function or function signature mismatch` while executing the c++ code in my gdextension, and versions 3.1.29 and beyond fail with `Can't resolve symbol [my entry_symbol]. Error: Tried to lookup unknown symbol "[my entry_symbol]" in dynamic lib: [my extension].javascript.template_ debug.wasm32.wasm.`

I tested a number of emsdk versions between 3.1.18 and 3.1.46 before finding 3.1.28 worked (manual binary search). In all of my tests, I left my project source the same and built templates against Godot 4.2 dev 6 (57a6813) and godot-cpp current master ([ef2f63a](https://github.com/godotengine/godot-cpp/tree/ef2f63a00c5496cc325e8546acd743787e87a83d)), compiling the web templates with `production=yes dlink_enabled=yes target=template_debug` and godot-cpp with `production=yes target=template_debug`.

**Comment by PgBiel** [comment]
Thank you very much for finding this @bobziuchkovski ! I can confirm that, while doing tests with the Rust GDExtension bindings (`gdext`), using emscripten 3.1.28 seems to actually get past the extension initialization phase, unlike what I observed with 3.1.18 and with 3.1.31 and later (for the latter, I'd also receive an error regarding not being able to find the entry symbol).

So, to recap, when compiling with `dlink_enabled=yes`:

1. The last known working emscripten version which **runs a basic project** (without GDExtension usage) is **3.1.39**. (For versions higher than that, the problem I report in this issue seems to occur.)
2. The last known working emscripten version which **(can) run a project with actual usage of GDExtension** is **3.1.28** (for versions earlier than that, it seems to fail with different errors, such as the aforementioned `null function or function signature mismatch`; and, for versions later than that, it seems to fail due to not being able to find the entry symbol).

I'm not sure if problem 2 (related more to actual GDExtension usage) is 100% on-topic for this issue though, perhaps it deserves a separate one. I'll leave this decision up to Godot maintainers.

**Comment by bobziuchkovski** [comment]
I'm also interested in knowing whether the GDExtension stuff should be considered separate. I've tracked down the upstream emscripten change that breaks 3.1.29, but I don't want to clutter this issue if that should be discussed elsewhere. 🤷‍♂️

**Comment by akien-mga** [comment]
I think we can keep discussing the 3.1.29 regression in this issue.

Having `dlink_enabled` builds working without supporting GDExtension isn't really a goal, as the only reason to use a `dlink_enabled` build is to load extensions.

So the problems will only be solved once we have `dlink_enabled` builds working with GDExtensions (and of course also without, for good measure, but that's just a side effect).

**Comment by Faless** [comment]
@bobziuchkovski thank you very much for tracking this down.

This appears to be indeed a problem on the Godot side then, we use a custom [`locateFile`](https://emscripten.org/docs/api_reference/module.html#Module.locateFile) (defined [here](https://github.com/godotengine/godot/blob/master/platform/web/js/engine/config.js#L294) in the Godot sources) since some file names are hard coded at compile time by emscripten (unless this changed in recent versions).

That is probably messing up with loading the extensions, now that's being used for loading dynamic libraries too.

**Comment by bobziuchkovski** [comment]
@Faless I can confirm your changes from https://github.com/godotengine/godot/pull/83165 fix GDExtension with emscripten up to **3.1.39**.

Emscripten 3.1.40 and beyond have other issues that I'm now working to track down. These probably coincide with the issues @PgBiel [reported](https://github.com/godotengine/godot/issues/82865#issuecomment-1751586191) on vanilla/non-GDExtension builds using emscripten 3.1.40-3.1.45.

**Comment by bobziuchkovski** [comment]
The remaining issue (`WebAssembly.Table.get(): invalid index [index] into funcref table of size [size]`) is a regression caused by https://github.com/emscripten-core/emscripten/pull/19390. This was introduced as part of the emscripten 3.1.40 release.

I can compile and successfully run my GDExtension project on emscripten **3.1.47** (latest stable) with that single commit reverted.

I'm still trying to make sense of how, exactly, that shared side module logic is failing with respect to godot, though. LInking with `-sDYLINK_DEBUG=1 -sPTHREADS_DEBUG=1` shows [project].worker.js starting, [project].side.wasm loading, [gdextension].wasm32.wasm loading, two new threads being created, and both threads failing almost immediately at `invokeEntryPoint: [hex addr]` with the hex addr matching the index of `invalid index [index] into funcref table of size [size]`.

**Comment by bobziuchkovski** [comment]
There's a PR open in the emscripten-core repo that fixes this issue: https://github.com/emscripten-core/emscripten/pull/19496. Hopefully that will land. I confirmed godot 4.2beta2 built against HEAD of emscripten works with the changes from https://github.com/emscripten-core/emscripten/pull/19496 applied.

**Comment by akien-mga** [comment]
For 4.2-beta3 and later I'm upgrading Emscripten from 3.1.18 (same version as used in 4.1 and earlier 4.2 builds) to 3.1.39, since it's the last known working version. We might stick to it for 4.2-stable.

**Comment by dsnopek** [comment]
Just copying from [the linked Emscripten issue](https://github.com/emscripten-core/emscripten/issues/20507): it appears the problem is fixed by PR https://github.com/emscripten-core/emscripten/pull/19496

That PR is still being actively reviewed and worked on.

**Comment by YuriSizov** [comment]
As another point of reference, I get the same `RangeError: WebAssembly.Table.get(): invalid index [...] into funcref table of size [...]` error even with 3.1.39.

That's a build of master (4.3 dev) from a couple of months ago (start of March). With the official 4.3.dev5 template I get a more cryptic error, `RuntimeError: null function or function signature mismatch`. But I believe it's the same thing. Both errors point to `invokeEntryPoint`, as mentioned above. More specifically it happens when the IP class is trying to initialize its thread.

What I managed to figure out is that the wasm tables in the main thread and in a sub-thread are different. This index exists in the much bigger main-thread table, but not in the table of a sub-thread. Frustratingly, I can't get DWARF to work in Chrome, despite compiling with debug symbols (both the engine and the extension), so there isn't much more I can comprehend.

**Comment by YuriSizov** [comment]
A small update about my case. I confirmed the issue with https://github.com/godotengine/godot-cpp-template, and also confirmed that it works in 4.2 stable. 4.3 dev 6 is still broken, however a Dlink-enabled build of current master (5708a3a02e00061e03366f2dabf8942df66fedca) actually exports! No changes to the project or the extension itself between runs. I haven't tried my actual project yet, but that's progress.

So I guess some recent changes (from Adam?) fixed it, even though I still have no idea what the source of the problem was.

**Comment by adamscott** [comment]
Good news everyone, https://github.com/emscripten-core/emscripten/pull/19496 has been merged on the emscripten side. So, technically, 3.1.62 should be able to compile with `dlink_enabled=yes`.

Based on the release tempo, the 3.1.62 release should be imminent.

**Comment by PgBiel** [comment]
Now that emscripten 3.1.62 has been released with the patch, I've recently tested the changes from https://github.com/godotengine/godot/pull/93143 (which appear to be available since 4.3-beta2) with godot-rust, and it's been a success! GDExtensions are working even on Firefox now - wonderful! I've tested both with the official 4.3-beta2 builds, as well as with web export templates built from source (commit 26d1577f3985363faab48a65e9a0d9eed0e26d86) with emscripten 3.1.62.

The only problem I had, which I'll share in case others also face this, is that I didn't realize that, since Godot now uses the `-sSUPPORT_LONGJMP=wasm` emscripten option, GDExtensions have to use the same option when building as well (which was already done for godot-cpp, for example). As a result, we faced some rather cryptic errors of the form below:

```
Aborted(Assertion failed: undefined symbol 'invoke_v'. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
```

I eventually found out that Emscripten only generates those `invoke_` functions when `-sSUPPORT_LONGJMP` is not changed from its default value of `"emscripten"` (see https://github.com/emscripten-core/emscripten/blob/34c1aa36052b1882058f22aa1916437ba0872690/tools/emscripten.py#L995-L998), so GDExtensions which didn't change that option would wrongly expect those functions to exist and fail to initialize - but it took me a bit to get there :) (Full investigation here: https://github.com/godot-rust/gdext/issues/438#issuecomment-2220887861)

Perhaps that error could be improved, but I'm not sure if there's much for Godot to do here (maybe an issue could be raised on upstream?).

Worth noting as well that `-sSUPPORT_LONGJMP=wasm` isn't enough to solve it for Rust users specifically, since the compiler appears to override that option by default, unless you specify `-Cllvm-args=-enable-emscripten-cxx-exceptions=0` (from https://github.com/rust-lang/rust/issues/112195#issuecomment-1573060218).

With that out of the way, however, the (rather simple) GDExtensions I've tested seem to be working well on the web so far. :+1:

**Comment by akien-mga** [comment]
This was indeed fixed in Emscripten 3.1.62, so closing.
