### ISSUE TITLE
[2.1.3 rc2] Parsing errors in scripts

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#8315]
**Operating system or device - Godot version:**
Regression on 2.1.3 rc2  on rc1 it was fine

**Issue description:**
My scripts in 2.1.3 rc2 are not parsing properly, I have a lot of "Error parsing expression, misplaced X"
It apply to const, sometimes functions and possibly other things as well.

**Steps to reproduce:**

1. Create new node, attach a script to it.
2. Fill the script with content:
```
extends Node

#physic layers
const LAYER_0_ALL = 0;
const LAYER_12_HERO = 12;

static func someFunc(someParam):
	if(someParam==LAYER_0_ALL): return LAYER_12_HERO;
	if(someParam==LAYER_12_HERO): return LAYER_0_ALL;

# PRICES
const PRICE_STONE_BUY = 50;  #THIS IS LINE 12
const PRICE_STONE_SELL = 25;
const PRICE_STONE_FACTORY = 75;

```
3. Observe parsing error: `error (12,1): Error parsing expression, misplaced: const`

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Likely related to the cherry-picking of the enum feature, cc @Faless.

**Comment by akien-mga** [comment]
Changelog since 2.1.3 RC1: https://hastebin.com/upepehijuz

**Comment by Faless** [comment]
> Likely related to the cherry-picking of the enum feature

Nope, I encountered that error before applying that patch.
I also reverted it, the bug is still there, I'll try a bisect to find the causing commit

**Comment by Faless** [comment]
So, after 7 bisection steps, I found this commit 0c650c2511a69dc8af1069546aad4ff4d989923d to be the one causing the issue @akien-mga @bojidar-bg .
The bug was not present in previous revisions

**Comment by akien-mga** [comment]
Thanks for bisecting @Faless. I'll probably revert 0c650c2 in the 2.1 branch. The bug might also be in master then, but I'll let @bojidar-bg check.

**Comment by akien-mga** [comment]
Fixed with f90eb87.

**Comment by bojidar-bg** [comment]
Ouch, sorry...

![image](https://cloud.githubusercontent.com/assets/5276727/24830376/90ae60c8-1c8d-11e7-9d56-15da6456b99b.png)
I can confirm it is still present on pretty-recent master. Reopening

**Comment by kubecz3k** [comment]
@bojidar-bg so you could check better, another test case for you:

```
extends Sprite
var variable;

func _notification(what):
	if (what == NOTIFICATION_INSTANCED):
		pass #all internal initialization
	elif(what == NOTIFICATION_READY):
		if("resourceTypesdf"=="asd"): variable = "no new line here is a problem";

func manualInit(in3DPos, inDest2DPoint, inAmount): #HERE is an: error parsing expresion, misplaced: func 
	var someOtherCodeHere;
```

**Comment by bojidar-bg** [comment]
Ouch, would check again tomorrow.

**Comment by bojidar-bg** [comment]
@kubecz3k Can confirm it is fixed by my changes, other ideas?

**Comment by kubecz3k** [comment]
@bojidar-bg no dont have any other ideas, thanks! :)
