### ISSUE TITLE
Loads of errors when i quit my app but no one indicates where in the script

### ISSUE THREAD

**Issue by tlloancy** [godotengine/godot#84410]
### Godot version

4.1.2

### System information

Windows 10

### Issue description

```
ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSolveIslands
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: Physics2DConstraintSetup
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: @export
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: @export_multiline
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: @export_range
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: @warning_ignore
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: @icon
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: Variant
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: BUG: Unreferenced static string to 0: GodotPhysicsDirectSpaceState2D
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: gui_focus_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: frame_pre_draw
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: frame_post_draw
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: SceneReplicationInterface
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: AudioEffectRecordInstance
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: process_frame
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: physics_frame
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: SceneCacheInterface
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: SceneRPCInterface
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: fallback_changed
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: button_down
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: button_up
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: child_exiting_tree
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: child_entered_tree
   at: unref (core/string/string_name.cpp:131)
```

### Steps to reproduce

Close the app. (I recently passed the app from godot 3.5.1 to godot 4.1.2)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
These bugs aren't in scripts, it's a leak of `StringName`s, due to some internal bug

Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by tlloancy** [comment]
just to add when i use --verbose i get this  

```
Orphan StringName: variant_booleanize
Orphan StringName: string_new_with_utf8_chars_and_len
Orphan StringName: OP_MODULE
Orphan StringName: KEY_SYSREQ
Orphan StringName: file_access_store_buffer
Orphan StringName: PROPERTY_HINT_NONE
Orphan StringName: string_operator_index_const
Orphan StringName: dictionary_operator_index
Orphan StringName: PROPERTY_USAGE_DEFERRED_SET_RESOURCE
Orphan StringName: _make_custom_tooltip
Orphan StringName: INLINE_ALIGNMENT_TO_BASELINE
Orphan StringName: JOY_BUTTON_DPAD_LEFT
```

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/81056

**Comment by tlloancy** [comment]
> These bugs aren't in scripts, it's a leak of `StringName`s, due to some internal bug
> 
> Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

4.1.3 been released ?

**Comment by AThousandShips** [comment]
> 4.1.3 been released ?

Yes, [yesterday](https://godotengine.org/article/maintenance-release-godot-4-1-3/)

But please see the other issue, which occurs on 4.2.dev as well

**Comment by tlloancy** [comment]
yes i just saw that it's more an informative bug

a more annoying one is this one do i need to open a new issue ?

```
ERROR: 1 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2047)
Leaked instance: GDScriptNativeClass:-9223014145819934213
Leaked instance: GDScript:-9222511119250226071 - Resource path: res://Client/Client.gd
Leaked instance: Object:914793674310766
Leaked instance: Control:914243918496880 - Node name:
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
Resource still in use: res://Client/Client.gd (GDScript)
```

Only thing i am thinking is i open a thread at ready and here is what i do at exit : 
```
func _exit_tree() -> void:
	thread.wait_to_finish()
```

Again this issue seems new i don't remember having it at godot 3 or if it is the case my mistake

**Comment by tlloancy** [comment]
> > 4.1.3 been released ?
> 
> Yes, [yesterday](https://godotengine.org/article/maintenance-release-godot-4-1-3/)
> 
> But please see the other issue, which occurs on 4.2.dev as well

Thanks i will gladly download it

**Comment by AThousandShips** [comment]
This has been closed though, so no need to verify it, as it has probably been solved in a few PRs, and 4.2 will be (largely) free of this, AFAIK.

**Comment by AThousandShips** [comment]
> a more annoying one is this one do i need to open a new issue ?

Please search for existing issues *first*, otherwise you can open one if you are sure it is a bug and not an error on your side

**Comment by tlloancy** [comment]
Still present in 4.1.3 but as you said 4.2 will probably get rid of it
