### ISSUE TITLE
Very small project manager window size on hiDPI displays

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#8543]
On hiDPI displays (tested only on Linux), when the DPI mode is set to hiDPI, the initial window size of the project manager is very small, probably twice as small as it should be (since hiDPI is 200% scaling). You can maximize it, but by default it's very small, and causes the window contents to be displayed in a poor fashion.

The initial window size should be adjusted depending on the DPI mode, this could also apply to projects run from the editor, as well as exported projects.

**Comment by reduz** [comment]
On my dell with 3k, hidpi on windows does not even work.. i think there ks
something strange going on

**Comment by akien-mga** [comment]
I think this might be fixed by now?

**Comment by Calinou** [comment]
This bug is still present on commit https://github.com/godotengine/godot/commit/4f39ce32b9195405f934445b20059e86632b47f9.

![Very small Project Manager on Windows 10 with hiDPI](https://user-images.githubusercontent.com/180032/31003946-8b75de5e-a4f2-11e7-9152-5382cbaa56ee.png)

**Comment by poke1024** [comment]
I believe this is fixed now?

**Comment by Calinou** [comment]
I tested commit https://github.com/godotengine/godot/commit/37ca542d2bfd9aac296e82e30a76117090dea08e on Linux, the problem still occurs:

![godot_small_project_manager_on_hidpi](https://user-images.githubusercontent.com/180032/34654097-d2af2a20-f3f6-11e7-87f0-27092e0c09a7.png)

**Comment by akien-mga** [comment]
For info:
- The logic for the "auto" DPI detection is here: https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/editor/project_manager.cpp#L1507-L1509
- The default size is set here: https://github.com/godotengine/godot/blob/master/main/main.cpp#L795-L796

IIUC, the DPI scaling is properly detected, but the default size is too small/not upscaled accordingly (screenshot does look like 1024x600 as default)?

Should we make the HiDPI scaling factor also scale the window size?

Not critical for 3.0 though, as it can be worked around by resizing the window manually.

**Comment by Calinou** [comment]
> Should we make the HiDPI scaling factor also scale the window size?

Yes.
