### ISSUE TITLE
MeshInstance not visible skeleton (Compatibility mode on mobile)

### ISSUE THREAD

**Issue by AurelienCaille** [godotengine/godot#86119]
### Tested versions

Godot 4.2

### System information

Windows 10 / Android - Godot 4.2

### Issue description

- Use both Compatibility mode on Windows and Android

![withCapture](https://github.com/godotengine/godot/assets/22189681/f5e25473-fa8d-4f36-be91-60e1b3029ba6)
With the skeleton the model is visible in editor and when playing with windows but not on mobile phone

![withoutCapture](https://github.com/godotengine/godot/assets/22189681/f942a2f3-51ea-4951-9478-d237a0e0e57a)
Without the skeleton (of course don't have the animations) model is now also visible on mobile phone

### Steps to reproduce

- model from Synty
- Rigging/animations from Mixamo

### Minimal reproduction project (MRP)

not allowed to share synty model

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.2.1 (only the latest patch version is supported, and it might already be fixed), I think this issue was posted recently and might have been fixed

**Comment by AurelienCaille** [comment]
Still have the issue on 4.2.1 (using version from official website)

I saw this issue #85752 wich is about windows and not mobile

also I use the opengl3 config as:
![param](https://github.com/godotengine/godot/assets/22189681/b1975099-27c9-41b6-a20a-b7b70294fa1f)

**Comment by Zireael07** [comment]
Are there errors in the output or in terminal?

**Comment by clayjohn** [comment]
Can you confirm that the `rendering_method.mobile` project setting is also set to "Compatibility"?

**Comment by Calinou** [comment]
> Can you confirm that the `rendering_method.mobile` project setting is also set to "Compatibility"?

@AurelienCaille Bump :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing due to lack of response. Note that this issue is likely a duplicate of https://github.com/godotengine/godot/issues/82419.
