### ISSUE TITLE
Using a texture in 3D always forces a re-import and makes it darker.

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#8684]
**Operating system or device - Godot version:**
Linux (Ubuntu 17.04), Godot 3.0 (built from master a few days ago)

**Issue description:**
I noticed something strange going on with importing textures. No matter which settings I choose, as soon as a texture is used in 3D it will get re-imported and suddenly ends up much darker (and it looks as if the colour depth is lower too). Wrong texture colours shouldn't happen in the first place, but this even happens with uncompressed import and with "detect_3d=false".

**Steps to reproduce:**
1. Load a texture, use it in 2D (everything's fine).
2. Then use the texture in 3D, it will get re-imported with wrong colors.
3. Then re-import it again - 2d view is fine. 
4. Switch back to 3D view, and it gets re-imported again.
5. repeat from step 3...

It looks like this:
![texture_import](https://cloud.githubusercontent.com/assets/15891496/25783876/e3b5074e-3363-11e7-8cc3-229dd9c16118.gif)

Again, I chose uncompressed texture import, and detect_3d is off. So there might be two issues here: Broken texture import and import settings not applied correctly?

**Comment by Zireael07** [comment]
I had the reimporting constantly thing in my attempts to use the May 3 fixnum build, too.

**Comment by Zylann** [comment]
What is detect_3d for?

**Comment by Zylann** [comment]
Similar to #8155

**Comment by reduz** [comment]
This is kind of by design and not a bug. 

It is possible to avoid it, but it won't work in many platforms if so. Basically, if a texture is used for 3D, it becomes a linear texture and it will look darker in 2D. This happens because all 3D rendering in Godot is done in linear colorspace, while 2D is done in gamma.

**Comment by DenisComtesse** [comment]
Okay, got it.
I'm not sure if this is related, but what also seems to happen is that the texture isn't just darker, it loses color depth when used 3D:

![2d](https://cloud.githubusercontent.com/assets/15891496/26403257/db286a8a-408d-11e7-9d9c-9d9eb883a1e9.png)
![3d](https://cloud.githubusercontent.com/assets/15891496/26403261/dcdcef72-408d-11e7-96b2-33063c36d55f.png)

(the cube uses an "unshaded" material)

**Comment by Zylann** [comment]
That color depth looks similar to https://github.com/godotengine/godot/issues/8683

**Comment by reduz** [comment]
The color depth issue is fixed already, so i suppose this can be closed

**Comment by LinuxUserGD** [comment]
I can still reproduce this issue on master (3.0.1) using gltf import and changing the textures from .png to .jpg.
![bug](https://user-images.githubusercontent.com/34406967/36697534-a1e289b4-1b47-11e8-8909-25907b243ff9.jpg)

**Comment by and3rson** [comment]
Sorry for bumping this ancient issue, but it currently blocks us from importing most DAE meshes because they get too dark. I can reproduce it in the exact same way as OP describes.

What's the correct way to deal with this? It renders all objects too dark and makes them unusable.

**Comment by LinuxUserGD** [comment]
Try gltf or the blender-godot-exporter. If the mesh is too dark, try to reimport with different settings.

**Comment by Megalomaniak** [comment]
@and3rson You are certain your textures were created with proper linear workflow?

https://greyscalegorilla.com/tutorials/what-is-linear-workflow-and-how-can-it-help-your-renders-look-better/

**Comment by tylerwilbanks** [comment]
2023 and I have this issue. My game is primarily 2d, but has a 3d scene that uses some textures that I'm also using in 2d. This on the fly re-import feature is a show stopper for me.

**Comment by Calinou** [comment]
> 2023 and I have this issue. My game is primarily 2d, but has a 3d scene that uses some textures that I'm also using in 2d. This on the fly re-import feature is a show stopper for me.

In Godot 3.x, you can create a second copy of the texture to use in 3D, or use a custom shader to display the texture in either 2D or 3D (to undo the sRGB/linear conversion).

This issue is resolved in Godot 4 since sRGB flags were moved from the texture to the material.
