### ISSUE TITLE
Grey rendering on Mesa/Radeon r600 (Translation from TGSI failed)

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8700]
**Operating system or device - Godot version:**
ubuntu + arch, Godot master
Card AMD Radeon 7500M/7600M

**Issue description:**
There is no lighting in the editor

**Steps to reproduce:**
Export mesh, open mesh, either dae or scene files

**Link to minimal example project:**
![screenshot_20170509_221224](https://cloud.githubusercontent.com/assets/650506/25851428/e0e87260-3504-11e7-90fd-499f650b18a2.jpg)

-----

*Bugsquad edit*: Same issue on AMD Radeon 6670, see #8774

Everything 3D is rendered grey and the terminal shows a lot of this errors:

```
EE ../../../../../src/gallium/drivers/r600/r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE ../../../../../src/gallium/drivers/r600/r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=1) -1
```

**Comment by eon-s** [comment]
Graphics card?
I have an old laptop with AMD Palm, every fixed material shows clear color only there, shadeless materials can be seen normally.

**Comment by Gibbz** [comment]
yeah good point! I forgot my gfx card.
Yeah it works fine on my other machine, its just this one... And it works ingame, just not in the editor...

AMD Radeon 7500M/7600M
opengl 3.0
http://www.amd.com/en-us/products/graphics/notebook/7500m-7600m

**Comment by Zylann** [comment]
Might be dumb to ask but better check, are your options like this?
![image](https://cloud.githubusercontent.com/assets/1311555/26026500/8828a294-37fc-11e7-8927-709513a6ecb0.png)

**Comment by Gibbz** [comment]
yep exactly the same (default) setup there.
Ive also noticed ingame only 1 light source works, any others lights in the scene dont seem to work. Where on my other machine, all the light sources work, and instead the ssao doesnt work. Not sure if thats related?

(Settings option at the bottom crashes the editor instantly)

**Comment by reduz** [comment]
This is strange, I wonder if it happens on Windows also. I tried Godot in that exact GPU but using fglrx and it works perfect, so maybe it's driver related?

**Comment by Gibbz** [comment]
Possibly, ive changed to using the official amdgpu driver on manjaro, and that looks to be working fine. 
The odd thing is, in my other machine with very similar card but non-mobile variant, has no issues.

**Comment by G392** [comment]
I have the same issue here, with an AMD APU (A6-4455M) (Antergos, XFCE)
> OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.1.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

Sorry if this doesn't help: 
I have downloaded Blender's nightly build to start playing with Eevee after seeing reduz's tweet
and found out that Blender's having a very similar issue. Only with Eevee.  
Meshes are Gray (The same colour as the backround) and I keep on getting this output:
> EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=1) -1  

This is the exact same output I get when running Godot 3 and in both cases,
this output only appears if there is a mesh in the scene.

**Comment by eon-s** [comment]
@G392 can you try on windows too in the same system? I can't test anymore but I think that the same happened there.

**Comment by G392** [comment]
@eon-s Nope, sorry. Got rid of my windows partition a few years ago.

**Comment by tuga3d** [comment]
My graphic card is a Radeon HD 6370M and i have the same problem with godot 3 and blender 2.8, it's a driver issue, it works fine in windows. The problem with linux is that the amd driver doesn't work with the current kernel (i think the last ubuntu version that worked was 14.04)

**Comment by Elinvention** [comment]
Relevant mesa bug: https://bugs.freedesktop.org/show_bug.cgi?id=99349

**Comment by akien-mga** [comment]
It's an upstream Mesa bug so there is sadly not much we can do on Godot's end. Keeping the issue open nevertheless so that affected users can find it.

**Comment by Elinvention** [comment]
For those who know how to patch and build mesa, [these patches](https://patchwork.freedesktop.org/series/26330/), solved the problem for me. You also have to set MESA_GLSL_TO_TGSI_NEW_MERGE and clean mesa's shaders cache to make it work.

**Comment by G392** [comment]
Problem solved here too. Thank you so much for sharing this!

**Comment by MarianoGnu** [comment]
Same issue, i'm commenting to get any news of this issue in case something good happens.

**Comment by johannesgunnar** [comment]
![godot3problem](https://user-images.githubusercontent.com/2924543/28995617-02d7377c-79dd-11e7-92a1-9b236871f39a.png)

Same issue. all 3D seems to be unlit. Getting the following error

```
EE ../../../../../src/gallium/drivers/r600/r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE ../../../../../src/gallium/drivers/r600/r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=1) -1
```

Interestingly enough, I am getting the same error on running the latest version of [Path of Exile](http://pathofexile.com/) through Wine. Which is actually what initially lead me to this post here. Hadn't had time to troubleshoot the Godot issue yet but they seem to be the same.

![poeproblem](https://user-images.githubusercontent.com/2924543/28995619-0655c67a-79dd-11e7-8720-f0c17b63131e.png)

**Comment by Elinvention** [comment]
@johannesgunnar Mesa currently fails to build certain types of shaders on r600.
The only thing you can do now is to build this branch https://github.com/gerddie/mesa/tree/regrename-v7 which contains patches that improve the estimation of registers life-time, thus making mesa able to build shaders with less registers.

**Comment by johannesgunnar** [comment]
Successfully built the [regrename-v7](https://github.com/gerddie/mesa/tree/regrename-v7 ) branch (I hope) and set the MESA_GLSL_TO_TGSI_NEW_MERGE env variable. (should it just be empty? or set to true? tried both without luck) and no change. Same errors.

Did the usual ./configure, make and sudo make install with regrename-v7 like mentioned in the mesa docs but no luck. Am I missing a step? Is there any way for me to double check if the correct version of Mesa is running?

Are these questions perhaps better suited for the discussion on this bug at the mesa mailing list?

**Comment by Gibbz** [comment]
I believe this bug is fixed in the 17.2 mesa release coming this month?

**Comment by G392** [comment]
@johannesgunnar you should run `export MESA_GLSL_TO_TGSI_NEW_MERGE=1`.  
Also, I recommend you clear your shader cache. I have no idea how to do this the right way, tough. I just deleted the `~/.cache/mesa` folder.

**Comment by Elinvention** [comment]
@johannesgunnar This guide explains how to build and run Mesa. https://www.gamingonlinux.com/wiki/Building_Mesa_from_source. Then you can use this script to run godot:

```
#!/bin/sh
export LD_LIBRARY_PATH=/opt/mesa-master/x86_64:$LD_LIBRARY_PATH
export LIBGL_DRIVERS_PATH=/opt/mesa-master/x86_64
export EGL_DRIVERS_PATH=/opt/mesa-master/x86_64
export MESA_GLSL_TO_TGSI_NEW_MERGE=1
export MESA_GLSL_CACHE_DISABLE=1
~/godot/bin/godot.x11.tools.64 "$@"
```

@Gibbz I don't think they merged the patch yet.

In the mean time there is a rebased version: https://github.com/gerddie/mesa/tree/regrename-v8

**Comment by johannesgunnar** [comment]
@eon-s, I've added ubuntu-x-swat/updates ppa and upgraded Mesa to 17.1.8 but I am still running into the same problem it seems.

`r_create - translation from TGSI failed !
EE ../../../../../src/gallium/drivers/r600/r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=1) -1`

**Comment by vunnysher** [comment]
Im getting same errors on Solus 64bit / Radeon HD6870

EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=1) -1

**Comment by fcobos** [comment]
This should be fixed in mesa 17.3.
The patch is in mesa git now.
https://bugs.freedesktop.org/show_bug.cgi?id=99349#c19

**Comment by johannesgunnar** [comment]
Can confirm that this bug is still present in Mesa 17.2.4. Crossing my fingers for 17.3 once it gets released.

**Comment by tuga3d** [comment]
I can confirm that is fixed in 17.3

**Comment by akien-mga** [comment]
Let's close as fixed by Mesa 17.3 then.
