### ISSUE TITLE
Godot always associates itself to the wrong monitor and font are hard to read

### ISSUE THREAD

**Issue by nvanfleet** [godotengine/godot#87015]
### Tested versions

4.2.1 stable but I believe I've seen this for some time. Not exactly sure since I was not using my external display the whole time.

### System information

MacBook Pro M1 Sonoma 14.2.1 - 4.2.1 stable - Forward+

### Issue description

If I am using Godot when I have my MacBook Pro plugged into my Apple monitor it seems to have a strange resolution. Probably it thinks it's being displayed on the MacBook Pro's screen and not the Display which is a different resolution.

Note: It's not like I moved it from one screen to another. The main screen I use is the external display and Godot displays there from the start. Though if I go into project settings it actually displays on my Macbook's screen while my main Godot window is on the external display.

### Steps to reproduce

Open a project on a Mac with two monitors which have a different resolution. Move the Godot screen to the second monitor. 

Workaround: Going into fullscreen mode seems to make it understand the actual resolution of the screen it's being displayed on

### Minimal reproduction project (MRP)

I don't think I need to provide that in this case.

**Comment by nvanfleet** [comment]
![Screenshot 2024-01-09 at 10 52 15 AM](https://github.com/godotengine/godot/assets/1486399/5510bf5a-8895-4e83-91f5-c534b42e282f)
![Screenshot 2024-01-09 at 10 54 04 AM](https://github.com/godotengine/godot/assets/1486399/27ab4416-dc4e-491e-8598-e7e340f01215)

**Comment by nvanfleet** [comment]
I attached screenshots where you can see there is something wrong and oftentimes the fonts are not so fun to read.

**Comment by AThousandShips** [comment]
The placement of the editor is controlled by `interface/editor/editor_screen` under editor settings, not the project settings

**Comment by nvanfleet** [comment]
Okay strange, most Mac apps are able to detect which screen they are actively displayed on and switch dynamically.

**Comment by AThousandShips** [comment]
You can change it to switch to the active screen, see the options

**Comment by nvanfleet** [comment]
I tried the different settings and:
1. I can get it to associate with a specific screen (in this case the external monitor)
2. It still doesn't end up with the correct resolution and still looks as bad as ever
3. Playing around with the different settings (keyboard active etc did not seem to affect this
(I restarted Godot each time)

**Comment by Calinou** [comment]
I wonder if this is resolved by https://github.com/godotengine/godot/pull/86022. Could you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) that pull request locally?

**Comment by bruvzg** [comment]
> I wonder if this is resolved by https://github.com/godotengine/godot/pull/86022.

It should be resolved by it, text issues are likely caused by downsampling from a hiDPI.

**Comment by TinyMatt** [comment]
I've just made an up-to-date macos build and it looks that the problem wasn't fixed. 
This happens on `mobile` or `forward+` renderers on external display. Keeping the editor on macbooks screen makes the text look perfectly fine.

![image](https://github.com/godotengine/godot/assets/121865850/5171f597-4414-4fe9-9840-fc5fefb7801c)

I'm not sure if this relevant but the build command is

```
scons p=macos target=editor production=true module_mono_enabled=yes mono_glue=yes vulkan_sdk_path=/Volumes/Drive/Applications/Vulkan
bin/godot.macos.editor.arm64.mono --generate-mono-glue modules/mono/glue
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos

rm -r ./Godot.app
cp -r misc/dist/macos_tools.app ./Godot.app
mkdir -p Godot.app/Contents/MacOS
cp bin/godot.macos.editor.arm64.mono Godot.app/Contents/MacOS/Godot
cp -R bin/GodotSharp Godot.app/Contents/Resources/GodotSharp
chmod +x Godot.app/Contents/MacOS/Godot
codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - Godot.app```

**Comment by Mackeriah** [comment]
Happy for this comment to be deleted if not useful, but I just wanted to chime in and say I've started encountering this same issue on Windows 10 today. I've been using Godot for perhaps 2 weeks without any problems, then from yesterday it's started opening on my 2nd monitor. I've not changed anything whatsoever.

**System**
Windows 10 Pro (no missing updates)
Godot v4.2.2.stable.official [15073afe3]
Happy to provide any other information that may be helpful.

**Issues**
- On Godot first start the project menu opens on monitor 2 instead of 1 (1 is my primary monitor)
- On opening a project it is opened on the 2nd monitor
- When I start the project game window itself that too opens on monitor 2.
- I have a forward+ project and a mobile project, both have the same issue

**Other information**
I have a feeling that this started happening after my game hung and rather than clicking the square stop button, I closed the game window. I am 99% sure the issue occurred from this point on.

**Comment by GrubLady** [comment]
Possible duplicate of #89019?

**Comment by lostminds** [comment]
@nvanfleet https://github.com/godotengine/godot/pull/93950 has now been merged in 4.3b3, fixing #89019 mentioned above, does this fix this issue as well for you?

**Comment by andysouthwell** [comment]
I'm using v4.3.stable.official [77dcf97d8] on Sonoma 14.6.1 (23G93) (Macbook M2). I don't see th font scaling issues mentioned in #89019, but Godot always opens on my internal LCD screen, even though my external monitor is currently 'primary'. I also then went into Project settings to tell Godot to open on the screen that currently has the mouse cursor (which is also my external screen), but it still opened on the internal LCD screen.

**Comment by sotornien** [comment]
I also had this issue with Godot 4.4.1 on Windows 10. The preview Window was messed up (wrong monitors, wrong positions), no matter what I set in the editor settings. Problem was my Monitor 3 was in energy saving mode. I started my 3rd Monitor and now I have the Preview Window on Monitor 2, where I wan't it to be.
