### ISSUE TITLE
The quest to get the iPhone build going

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8739]
Hey all,

I've spend a bunch of time this morning seeing if I could get the iPhone build going for Godot 3.0.
Most of that was spend on chasing a wild goose around for an issue that had been plaguing me since I got started try to get the iOS port going.

Anyway, the root problem was simply that it wasn't loading the data.pck file, as a result the initialisation of Godot starts cleaning stuff up, but the code inside of the iOS implementation kept going like nothing was wrong eventually ending in exception errors. I'll do a quick PR in a minute that at least exits the application nicely if things fail. It does give a nice message in the logs that it can't find any files to load but the exception error threw me off.

I don't know if this is a missing setting or something that hasn't changed yet in the iOS implementation but the code looking for the pck file to open is using the executable name. In the XCode template that is godot_opt.iphone which ends up in godot_opt.pck being opened, not data.pck. Simply renaming the file allowed it to load the game files.

So it boots up now, but we're still getting errors. In initializing the GLES rendered it's failing at some point:
```
GLES3: max extensions: 19
GLES3: max ubo light: 102
GLES3: max ubo reflections: 113, ubo size: 144
[1;31mERROR: initialize: [0m[1mCondition ' status != 0x8CD5 ' is true. Continuing..:
[0;31m   At: drivers/gles3/rasterizer_scene_gles3.cpp:4845.[0m
[1;31mERROR: initialize: [0m[1mCondition ' status != 0x8CD5 ' is true. Continuing..:
```

And probably as a cascade error we're getting this in every frame:
```
2017-05-13 13:20:15.399088+1000 godot_opt.iphone[16026:7192622] [MC] Reading from public effective user settings.
2017-05-13 13:20:15.640 godot_opt.iphone[16026:7192622] 506 error
[1;31mERROR: _render_target_allocate: [0m[1mCondition ' status != 0x8CD5 ' is true.
[0;31m   At: drivers/gles3/rasterizer_storage_gles3.cpp:5814.[0m
[1;31mERROR: load_image: [0m[1mError opening file: res://icon.png
[0;31m   At: core/io/image_loader.cpp:53.[0m
2017-05-13 13:20:15.755 godot_opt.iphone[16026:7192622] 506 error
2017-05-13 13:20:15.755 godot_opt.iphone[16026:7192622] 506 error
2017-05-13 13:20:15.756 godot_opt.iphone[16026:7192622] 506 error
2017-05-13 13:20:15.756 godot_opt.iphone[16026:7192622] 506 error
```

The 506 error repeats. My guess is that the opengl context isn't being instantiated properly, we're probably missing a few more hints, as it is not able to create the render target. I'll keep stepping through the code and see if I can trap where the GLES3 initialisation fails, I've found XCode to be really unfriendly when debugging if it isn't the one compiling the code...

**Comment by BastiaanOlij** [comment]
@reduz , the first issue is caused at the very end of rasterizer_scene_gles3.cpp => RasterizerSceneGLES3::initialize where it creates the exposure frame buffers. glCheckFrameBufferStatus returns error code 36054 (GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT) 

I tried checking the output of glGetError after each command to see if its not excepting any of the settings for the textures being created but it seems to be accepting them just fine so I'm guessing the textures are created correctly. Not sure (yet) why it's not happy creating those framebuffers while it is creating all the others just fine

**Comment by BastiaanOlij** [comment]
Bingo, @reduz , @punto- , ok one more down, one more to go. The problem on iOS seems to be that it doesn't support 32bit single channel floating point textures with framebuffers.

So changing:
`		glTexImage2D(GL_TEXTURE_2D, 0, GL_R32F, max_exposure_shrink_size, max_exposure_shrink_size, 0, GL_RED, GL_FLOAT, NULL);
`
to 
`		glTexImage2D(GL_TEXTURE_2D, 0, GL_R16F, max_exposure_shrink_size, max_exposure_shrink_size, 0, GL_RED, GL_FLOAT, NULL);
`
works around the problem but at the cost of lower precision. 

Do we add a platform check here or do you guys have any nicer ideas to solve this?

I'm still getting 506 errors actually rendering, haven't spend any time on that.

**Comment by BastiaanOlij** [comment]
Ok guys, things are looking better. I just compiled Godot 3.0 for iOS 11. It still comes up with a blank screen but it no longer completely falls over itself.

I've put the log on pastebin: https://pastebin.com/jbwP5p2L

The interesting bit starts at line 35. It is not able to create all the buffers for the different effects and it is not loading the texture maps and some other resources.

I think its that last bit that hints at the trouble, my guess is that I've not configured the export correctly, either that or importing the scene isn't working correctly on iOS. I don't know how this is working so not sure what to look for to fix.

@reduz am I right in assuming that if not all parts of the framebuffer is created Godot should still work but just disable the related functionality?

**Comment by BastiaanOlij** [comment]
@reduz see my post of the 14th of May, I noticed that changes was undone but iOS won't support the 32bit exposure buffer. I'm guessing it would just turn that functionality off.

Things are getting closer with a lot less errors being logged when testing on iOS but still no rendering output.

I found out that with my test project it now fails to load the project because it can't load the textures. I'm guessing the textures are exported in the wrong format. I'll start working on an iPhone export so we can embed the correct settings. 

Using a test project that doesn't use textures it successfully loads the project but then fails on compiling the shaders:

```
[1;31mERROR: _display_error_with_code: [0m[1mSceneShaderGLES3: Fragment Program Compilation Failed:
ERROR: 0:1301: Incompatible types in initialization (and no available implicit conversion)
ERROR: 0:1319: Use of undeclared identifier 'fog_amount'
ERROR: 0:1329: Use of undeclared identifier 'fog_amount'
ERROR: 0:1329: Use of undeclared identifier 'fog_amount'
ERROR: 0:1332: Use of undeclared identifier 'fog_amount'
ERROR: 0:1335: Use of undeclared identifier 'rev_amount'
ERROR: 0:1335: Use of undeclared identifier 'fog_amount'
ERROR: 0:1336: Use of undeclared identifier 'rev_amount'
ERROR: 0:1337: Use of undeclared identifier 'rev_amount'
ERROR: 0:1338: Use of undeclared identifier 'rev_amount'
```

It then crashes with an excess denied exception on this line of code:
`glBindFramebuffer(GL_DRAW_FRAMEBUFFER, storage->frame.current_rt->effects.mip_maps[0].sizes[0].fbo);`

I'm guessing that may be caused by this buffer not being created on account of the 32bit exposure buffer not being supported.

**Comment by BastiaanOlij** [comment]
Getting somewhere:
https://youtu.be/60rTMi0gKw4

So there are a few glitches in rendering and for some reasons I couldn't press the buttons.
I'm also still getting a 502 error logged but I'm not completely sure what that is coming from...

**Comment by reduz** [comment]
as far as I remember we fixed these things, so closing.

**Comment by BastiaanOlij** [comment]
@reduz, I'm still getting 502 errors every frame. It's unclear to me where the error is coming from though. Capturing a frame gives a lot of warnings but doesn't indicate any instruction that results in the error. I'm wondering if the error gets set at some point and is never cleared.

**Comment by BastiaanOlij** [comment]
@endragor do you get error 502 as well when running any of your iPhone builds?

**Comment by ViktorEvil** [comment]
I am getting very similar errors every frame

`2018-07-06 13:38:19.796571+0100 TestProject[9331:3819338] 502 error`

using godot 3.0.4 and Xcode 9.4.1 on macOS 10.13.5
