### ISSUE TITLE
SamplePlayer2D has invalid mix rate when parented to a Viewport node

### ISSUE THREAD

**Issue by vetoed** [godotengine/godot#8777]
Tested on 2 PCs:
Windows 10 x64 - Godot 2.1.3 x64
Windows 10 x64 - Godot 2.1.3 x32
Windows 10 x64 - Godot 2.1.2
Windows 7 - Godot 2.1.2

SamplePlayer2D plays only full volume, non-spatial sound. It also does not stop playback after calling stop_all(). Found very little on SoundPlayer2D so maybe it works for most people and I do something wrong way. Every sound I played so far was accompanied by the message:
```
ERROR: SpatialSound2DServerSW::update: Invalid mix rate for voice (0) check for invalid pitch_scale param.
   At: servers\spatial_sound_2d\spatial_sound_2d_server_sw.cpp:952
```
Seems similar to [this old issue](https://github.com/godotengine/godot/issues/747).

Minimal project [here](https://github.com/godotengine/godot/files/1002260/soundtest.zip). Should display the sound source at the cursor position and attenuate the sound based on this position.

**Comment by vtepe** [comment]
Sound works fine when SamplePlayer2D is not a child of Viewport node.

**Comment by akien-mga** [comment]
Can you reproduce the issue in the master branch too?

**Comment by vetoed** [comment]
Tested the minimal project in 2.1.4 x64 beta on Windows 10 x64.
Same outcome, same workaround.
`ERROR: SpatialSound2DServerSW::update: Invalid mix rate for voice (0) check for invalid pitch_scale param.
   At: servers\spatial_sound_2d\spatial_sound_2d_server_sw.cpp:949`

Will try to build the newest master and let know how it goes.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Faless** [comment]
This seems fixed in `3.0`, closing.

**Comment by xsellier** [comment]
Hey,

this still happens in version 2.1*. Have you planned to fix this bug for v2.1.*?

**Comment by akien-mga** [comment]
This was fixed as part of the complete audio systems rewrite in 3.0, so there's no easy fix to backport. One would have to make a dedicated fix for 2.1.
