### ISSUE TITLE
Godot uses old versions of Rider from Toolbox Cache

### ISSUE THREAD

**Issue by elusive-code** [godotengine/godot#88835]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19044 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3090 Ti (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 Threads)

### Issue description

When Jetbrains Rider selected in Godot as External Editor and it is installed via Jetbrains Toolbox Godot might pickup wrong version of Rider.
Jetbrains Toolbox maintains several caches, even if in Toolbox only one version is currently active some old files might be present in the system. 

In fact even when Rider removed completely Godot manages to launch it.
Note: I double checked - there's no separate version of Rider installed in the system, and Windows Task Manager says path of the executable is
....AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\231.9011.39\bin
So it is definitely some Toolbox cache

### Steps to reproduce

1. Install Jetbrains Toolbox
2. Install Rider 2023.1.1
3. Update Rider to 2023.3.3
4. Launch Godot
5. Create new project 
6. Editor>Editor Settings>Dotnet>Editor>External Editor select JetBrains Rider and Fleet
7. Create C# script, build project
8. Double click on script

E.R. Rider 2023.3.3 opened 
A.R. Rider 2023.1.1 opened

9. Close Rider
10. Go to Toolbox, remove Rider completely
11. Double click on script in Godot

E.R. Message appears that Rider not found, maybe internal editor opened
A.R. It launches Rider 2023.1.1

### Minimal reproduction project (MRP)

[Test2.zip](https://github.com/godotengine/godot/files/14397625/Test2.zip)

**Comment by paulloz** [comment]
Hello, thanks for the report. I expect this should be fixed by
- #88544

**Comment by raulsntos** [comment]
The mentioned PR should be included in [Godot 4.3 dev 4](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-4/). Can you still reproduce this in a newer version of the engine?

**Comment by elusive-code** [comment]
@raulsntos 
Hello, yes it works fine in new version.

1) Had installed Rider 2023.3.3, upgraded via toolbox to 2024.1.1.
2) Opened script from Godot 4.3 dev 4
AR=ER launched 2024.1.1
3) Closed Rider, downgraded via toolbox to 2023.3.3, opened script in Godot
AR=ER launched 2023.3.3
4) Closed Rider, removed Rider via Toolbox, opened script in Godot
AR=ER Error show in output
```
/root/godot/modules/mono/editor/GodotTools/GodotTools/Ides/Rider/RiderPathManager.cs:112 - Error when trying to run code editor: JetBrains Rider or Fleet. Could not find path to the editor.
```
