### ISSUE TITLE
HTML5 export doesn't work in 4.3 on MacOS on some projects

### ISSUE THREAD

**Issue by ZenRepublic** [godotengine/godot#88964]
### Tested versions

Reproducible in 4.3 dev 3
not reproducible in: 4.2

### System information

Windows 11 Godot 4.3 Dev 3

### Issue description

People said my web game loads a long time on macs, and thats exactly the issue 4.3 dev 3 said to have fixed with multithreading.

Well, even an empty scene doesn't work, throwing these errors in browser console

![image_2024-02-28_175226611](https://github.com/godotengine/godot/assets/102485601/593e9e94-562d-4f5a-992f-7c56f39ac42c)

### Steps to reproduce

Just create a project on godot 4.3 dev 3, import html export packages and go to "remote debug" mode.

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
No way https://github.com/godotengine/godot/pull/85939 didn't work, right?

**Comment by akien-mga** [comment]
It might be the same issue as https://github.com/godotengine/godot/issues/88249 which should be fixed in 4.3 dev 4.

**Comment by ducpt-bili** [comment]
looking for this web deploy on ios work +1 follow issue

**Comment by akien-mga** [comment]
> looking for this web deploy on ios work +1 follow issue

Please add such reactions to the OP with the :+1: emoji, not with a comment unless you have more information to add about the bug.

This should be fixed in 4.3 dev 4 which was released yesterday, please test and confirm.

**Comment by sweti-yeti** [comment]
> This should be fixed in 4.3 dev 4 which was released yesterday, please test and confirm.

This is still broken in 4.3 dev 4 @akien-mga, tested in a newly created project and ran in browser on Chrome.

**Comment by adamscott** [comment]
Tested this project and I got no errors at all. I used Godot 4.3.dev3 with the supplied export templates.
[test-html-export-4.3.dev.zip](https://github.com/godotengine/godot/files/14541075/test-html-export-4.3.dev.zip)

@ZenRepublic @sweti-yeti Could you test with my MRP?

**Comment by sweti-yeti** [comment]
> Tested this project and I got no errors at all. I used Godot 4.3.dev3 with the supplied export templates.
[test-html-export-4.3.dev.zip](https://github.com/godotengine/godot/files/14541075/test-html-export-4.3.dev.zip)

Okay, this works for me in dev3 and dev4 @adamscott , as does my original MRP after going back and retesting.

The error I reported in my previous comment is a different behavior from OP. In Brave, the first load of the game throws the `LinkError` and the game gets stuck loading. After a force-refresh the error is no longer present and the project loads fine. The error does not occur on Chrome or Firefox.

However, I just tested with a game I've been working on with 4.2, and when exporting that with 4.3-dev4 I do reproduce the errors in the screenshot of this Issue. I'll see if I can get an MRP together that reproduces.

**Comment by ZenRepublic** [comment]
Empty project web build seems to work, tested on dev5 snapshot

**Comment by iryan2** [comment]
Are y'all on Windows? I'm getting the same errors as OP with an empty project in 4.3-dev6 on macOS.

**Comment by akien-mga** [comment]
So far I could not reproduce this on Linux at all, Web exports work just fine for me.

So yes, I'll assume this is a macOS-specific issue.

Could affected users who can still reproduce this in 4.3-dev6 comment with details on tested OS and browser versions?

**Comment by iryan2** [comment]
macOS Sonoma 14.4.1, 
Microsoft Edge Version 125.0.2535.51 (Official build) (arm64)

I get similar errors in Safari Version 17.4.1 (19618.1.15.11.14):
<img width="908" alt="image" src="https://github.com/godotengine/godot/assets/5858312/712a0297-17c4-4b39-865f-5b320f22d098">

**Comment by sweti-yeti** [comment]
@akien-mga I still reproduce this error on dev6 with my project migrated from 4.2.1.

My specs:
Ubuntu 23.10
tested on Firefox 126, Brave 1.65.133, and Chrome 125

see screenshot for errors/stacktrace.

I have so far been unsuccessful in building an example project from scratch that reproduces the error, or in stripping down a copy of my main project to create a minimum reproducible example. If you'd like I could share a copy of my project with you privately to help you reproduce the issue, but would prefer not to post my whole project publicly.
![image](https://github.com/godotengine/godot/assets/92612583/4dd9843b-7ff6-43de-8ded-2cb643423ae4)

**Comment by adamscott** [comment]
@sweti-yeti Do you use GDExtension? Which export template settings do you use? Is it a threaded/non-threaded build? Does it use dlink or not?

**Comment by adamscott** [comment]
> macOS Sonoma 14.4.1, Microsoft Edge Version 125.0.2535.51 (Official build) (arm64)
> 
> I get similar errors in Safari Version 17.4.1 (19618.1.15.11.14): <img alt="image" width="908" src="https://private-user-images.githubusercontent.com/5858312/332402186-712a0297-17c4-4b39-865f-5b320f22d098.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2ODc3NzQsIm5iZiI6MTcxOTY4NzQ3NCwicGF0aCI6Ii81ODU4MzEyLzMzMjQwMjE4Ni03MTJhMDI5Ny0xN2M0LTRiMzktODY1Zi01YjMyMGYyMmQwOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMTg1NzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTZkZDVhZGQxNWU3MWI0YmIxOGM2NmE4ZjYwNjZkZDYxNjQ0MzJiZjA4MzY3Njg4ZWRjZjE5NTM0MWUxMTczNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eGqRYkkBU48j5ArNGqCd70apxujDIMDn40oCws7YINI">

Can you test on a new/empty project and on a more recent beta version of Godot 4.3?

**Comment by iryan2** [comment]
@adamscott I am pleased to report I not only got a empty project to work with 4.3-beta2, but also the (fairly simple) game that I've been working on! Huge thank you to you and anyone else involved in addressing this issue!!

**Comment by adamscott** [comment]
@iryan2 You can also just use the Remote Debug feature from the Godot Editor itself! No need to setup a custom server to debug your code.

<img width="320" alt="Capture d’écran, le 2024-06-30 à 12 41 46" src="https://github.com/godotengine/godot/assets/270928/efcb909d-034a-43f5-9730-bf3149651835">

**Comment by iryan2** [comment]
> @iryan2 You can also just use the Remote Debug feature from the Godot Editor itself! No need to setup a custom server to debug your code.
> 
> 
> 

Oh wow I had no idea about that, thanks for the tip!

**Comment by sweti-yeti** [comment]
@adamscott I have thread support enabled as my game is somewhat physics intensive, so I have the physics running on a separate thread. GDExtension support was enabled but I'm not using it. Not sure about the other settings.

After disabling extension support in the export template the game loads without the errors from before! This is on latest 4.3 beta 2, I can try on dev2 as well based on @dsnopek comment about the emscripten update to see if that's related.
