### ISSUE TITLE
Code editor scrolls to show the caret when it's window loses focus

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#89285]
### Tested versions

- occurs in v4.3.dev4.official [df78c0636]
- *does not* occur in v4.2.1.stable.official [b09f793f5]

### System information

linux

### Issue description

- when
  1. the focus leaves the window the code editor is in (either the full editor or the code editor in its own window), and
  2. the code editor is focused
- then the code editor scrolls to make the edition caret visible if it's outside the view

https://github.com/godotengine/godot/assets/71937306/bdde6001-e372-437e-8293-93a36c0a293c

### Steps to reproduce

1. get a long gdscript file
2. put the caret in a line and scroll it outside of the screen
3. give the focus to another os window
4. the code editor should scroll on its own

### Minimal reproduction project (MRP)

any

**Comment by kitbdev** [comment]
Cannot reproduce in Godot v4.3.dev4 on Windows 10.0.22621

**Comment by MrPersonDev** [comment]
I can consistently reproduce this error on my Linux system (void linux, i3wm) in Godot v4.3.dev4.

The relevant function here is `TextEdit::adjust_viewport_to_caret`, which scrolls the editor to show the caret. 
Using a debugger, I found this function was always called from `TextEdit::_notification`: (I'll keep the code snippets to just the relevant code)

```
case MainLoop::NOTIFICATION_OS_IME_UPDATE: {
	if (has_focus()) {
		adjust_viewport_to_caret(0); // <--- our problem
	}
} break;
```

The source of this IME update notification seems to be from `DisplayServerX11::process_events`

```
case FocusOut: {
	if (wd.ime_active) {
		OS_Unix::get_singleton()->get_main_loop()->notification(MainLoop::NOTIFICATION_OS_IME_UPDATE);
	}
} break;
```
Now this notification would imply that IME is active, which seems to always be the case because of `TextEdit::_update_ime_window_position`:
```
void TextEdit::_update_ime_window_position() {
	DisplayServer::get_singleton()->window_set_ime_active(true, get_viewport()->get_window_id());
}
```
And this update function is called in `TextEdit::_notification`, in the case of a draw notification:
```
case NOTIFICATION_DRAW: {
	// at the bottom of this absurdly long case...
	if (has_focus()) {
		_update_ime_window_position();
	}
} break;
```
So it seems that for the viewport to scroll to show the cursor, the flag for if IME is active must be set.
But this flag is always set as long as the window has focus and can draw.

Perhaps someone with more experience in Godot's IME interface can understand why this is the case.

**Comment by ConteZero** [comment]
I can confirm the issue, Godot 4.3 with Opensuse Tumbleweed (KDE), it's really annoying.

**Comment by kitbdev** [comment]
- possibly fixed by https://github.com/godotengine/godot/pull/96829

**Comment by Giganzo** [comment]
> * possibly fixed by [Fix project manager stealing focus on i3 #96829](https://github.com/godotengine/godot/pull/96829)

Does not look like it fixed this, still happens on v4.4.dev7.official [46c8f8c5c]

**Comment by berarma** [comment]
Still happening in 4.4-beta4.

**Comment by berarma** [comment]
Removing these lines fixes this issue and also #101693.

https://github.com/godotengine/godot/blob/e567f49cbb292dd6bb628348e67c1f3c2a3a5f99/platform/linuxbsd/x11/display_server_x11.cpp#L4893-L4901

These lines were introduced in #70052. I don't see any reason to disable IME when focus is lost. I'm not a IME user so I can't test if those lines are important. Looking at the code, it seems IME isn't disabled on Windows when loosing focus.
