### ISSUE TITLE
Custom Signal variables do not show up in editor

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#8980]
**Operating system or device - Godot version:**
3.0

**Issue description:**
When you create a custom signal on a script - it does not show indicate it take in any variables from within the editor.

This is somewhat related to https://github.com/godotengine/godot/issues/6120 - but for the editor view. :)

**Steps to reproduce:**
Create script with signal - that takes in variables.
Go to editor and check the Node -> Signals tab for the custom script.

There should be a variable, but nothing is shown.
![image](https://cloud.githubusercontent.com/assets/6776092/26548236/72e46d7c-4473-11e7-9976-a80c331dabf1.png)

**Comment by MarianoGnu** [comment]
Just checked and looks like this is already solved, can you confirm?

![imagen](https://user-images.githubusercontent.com/1776044/27352009-9fdc8c38-55d5-11e7-86bb-272c1d10da0a.png)

**Comment by akien-mga** [comment]
Assuming fixed, please comment if it's not the case and we'll reopen the issue.

**Comment by Tybobobo** [comment]
Just recompiled Godot and the issue remains. 
I have included a sample project:
[Godot3Project.zip](https://github.com/godotengine/godot/files/1105465/Godot3Project.zip)

**Comment by vnen** [comment]
It shows up after closing and reopening the scene.

**Comment by erayerdin** [comment]
I'm having this issue with C#. Just applied [this section](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/signals.html#custom-signals).

**Comment by Calinou** [comment]
@erayerdin C# is quite a different beast from GDScript, so I'd suggest opening a new issue.

**Comment by sigh-gone** [comment]
I'm running into this issue right now
I created a HUD scene. I added a signal for a button in the gdscript (start game), and its not showing up in the signals menu for the HUD scene.

main scene menu
![scene_menu](https://github.com/godotengine/godot/assets/112661044/ff76c46e-53c2-416b-97de-63b3f552e5ac)

signal list for main
![signals_screen](https://github.com/godotengine/godot/assets/112661044/e2a2386e-5193-422b-b23e-b62ab4388844)

code for my hud
```gdscript
#HUD scene gdscript
extends CanvasLayer

signal start_game

func update_score(value):
	$MarginContainer/Score.text = str(value)
	
func update_timer(value):
	$MarginContainer/Time.text = str(value)
	
func show_message(text):
	$Message.text = text
	$Message.show()
	$Timer.start()

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass


func _on_timer_timeout():
	$Message.hide()


func _on_start_button_pressed():
	$StartButton.hide()
	$Message.hide()
	start_game.emit()
	
func show_game_over():
	show_message("Game Over")
	await $Timer.timeout
	$StartButton.show()
	$Message.text = "Coin Dash!"
	$Message.show()

```
I'm following a book so i may be doing something wrong

**Comment by surajsharma** [comment]
> I'm running into this issue right now I created a HUD scene. I added a signal for a button in the gdscript (start game), and its not showing up in the signals menu for the HUD scene in the main scene.
> 
> main scene menu ![scene_menu](https://private-user-images.githubusercontent.com/112661044/311087036-ff76c46e-53c2-416b-97de-63b3f552e5ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTcwNDksIm5iZiI6MTcxMzExNjc0OSwicGF0aCI6Ii8xMTI2NjEwNDQvMzExMDg3MDM2LWZmNzZjNDZlLTUzYzItNDE2Yi05N2RlLTYzYjNmNTUyZTVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxNzQ1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzFjMzczMjIyMjgwZDlkMjRiZGZiYTBiNjFiZDMxYTA0MWYyMTZiMTdjNTlhMmQxODYxNzBhMWQ3ZDE2NGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lf74YyW2elKQhCAWAnH9dn4w5yx4xbZXktBGtGljBg0)
> 
> signal list for main ![signals_screen](https://private-user-images.githubusercontent.com/112661044/311087040-e2a2386e-5193-422b-b23e-b62ab4388844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTcwNDksIm5iZiI6MTcxMzExNjc0OSwicGF0aCI6Ii8xMTI2NjEwNDQvMzExMDg3MDQwLWUyYTIzODZlLTUxOTMtNDIyYi1iMjNlLWI2MmFiNDM4ODg0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxNzQ1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmQ2ZTQ1ZjMwMDFhNGZhMGE4NmJhMjFiOGYwMmRjZGU5YWRmMzhmNjJlNTFlZjE2M2Y1ZTZkNGE0YTU3OTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dcHOb6GaZ62TclvNImqq8atoTB_1mwyun5Eqdsuyu1A)
> 
> code for my hud
> 
> ```gdscript
> #HUD scene gdscript
> extends CanvasLayer
> 
> signal start_game
> 
> func update_score(value):
> 	$MarginContainer/Score.text = str(value)
> 	
> func update_timer(value):
> 	$MarginContainer/Time.text = str(value)
> 	
> func show_message(text):
> 	$Message.text = text
> 	$Message.show()
> 	$Timer.start()
> 
> # Called when the node enters the scene tree for the first time.
> func _ready():
> 	pass # Replace with function body.
> 
> 
> # Called every frame. 'delta' is the elapsed time since the previous frame.
> func _process(delta):
> 	pass
> 
> 
> func _on_timer_timeout():
> 	$Message.hide()
> 
> 
> func _on_start_button_pressed():
> 	$StartButton.hide()
> 	$Message.hide()
> 	start_game.emit()
> 	
> func show_game_over():
> 	show_message("Game Over")
> 	await $Timer.timeout
> 	$StartButton.show()
> 	$Message.text = "Coin Dash!"
> 	$Message.show()
> ```
> 
> I'm following a book so i may be doing something wrong

+1 i am following this book too! i have the identical issue pls open this

**Comment by akien-mga** [comment]
Please open a new issue. This was fixed in 2017, so the issue you have now is a new bug.
