### ISSUE TITLE
Moving text-files results in "No loader found for resource"

### ISSUE THREAD

**Issue by SirLich** [godotengine/godot#89996]
### Tested versions

- Reproducible in: v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When moving .txt files (or any other text file), the following log prints on *begin drag* `No loader found for resource: res://folder_a/file.txt (expected type: )`.

Note: Although this can be reproduced in a blank project, it's also possible to reproduce by creating a custom control which implementing the related drag functions, and returning your own synthetic move order: `{"type": "files", "files":[...]}`. If this contains a text file, the log ALSO prints when the drag *begins*.

### Steps to reproduce

Create a .txt file in any folder. Drag+drop the file from one place to another. View console log.

The MRP contains two folders, and a txt file for your convenience.

### Minimal reproduction project (MRP)

[no_loader_found.zip](https://github.com/godotengine/godot/files/14795966/no_loader_found.zip)

**Comment by ltecheroffical** [comment]
Confirmed

**Comment by ltecheroffical** [comment]
Fixed as of the latest build of godot

**Comment by zandwacht** [comment]
Using Godot 4.4 on MacOS: problem still exists. I moved a PNG out of a folder in Finder and got the error. Error persisted even after placing the file back.

**Comment by Goury** [comment]
Why is this closed?
4.6.2, the problems is not fixed on export.
