### ISSUE TITLE
Unsimulated PhysicalBone3D in skeleton children cannot be detected by intersect_ray

### ISSUE THREAD

**Issue by aiaimimi0920** [godotengine/godot#90468]
### Tested versions

- Godot v4.3.dev (04dd299cb), Godot v4.3.dev (6c5792806) have this issue
- Godot v4.3.dev (fd61a42e0), Godot v4.2  is no such issue

This issue is due to the commit:
[04dd299cbac614c0ff2306b8d3cD60dcd86abd8e](https://github.com/godotengine/godot/commit/04dd299cbac614c0ff2306b8d3cd60dcd86abd8e)
@TokageItLab 

### System information

windows 11

### Issue description

In previous versions(fd61a42e0), I can obtain ray_result through this code
```
extends Node3D

const RAY_LENGTH = 1000.0
var ray_result = null
func check_ray():
	var space_state = get_world_3d().direct_space_state
	var cam = %Camera3D
	var mousepos = get_viewport().get_mouse_position()

	var origin = cam.project_ray_origin(mousepos)
	var end = origin + cam.project_ray_normal(mousepos) * RAY_LENGTH
	var query = PhysicsRayQueryParameters3D.create(origin, end)
	query.collide_with_areas = true
	var result = space_state.intersect_ray(query)
	ray_result = result
	printt("ray_result",ray_result)


func _physics_process(delta):
	check_ray()
```
But in the version(04dd299cb), I couldn't get the correct result

### Steps to reproduce

1. this is correct video(fd61a42e0):

https://github.com/godotengine/godot/assets/153103332/671aaf1b-9440-465f-9712-d5cb587a8ae9

2. this is incorrect video(04dd299cb):

https://github.com/godotengine/godot/assets/153103332/8ddf3ddd-a465-4dac-a782-12015a0602a3

node tree is:
![image](https://github.com/godotengine/godot/assets/153103332/1f05ecd8-5ae3-4a31-bd05-f83e229a71e8)

Note that if the node tree is adjusted to 
![image](https://github.com/godotengine/godot/assets/153103332/09745d50-5ae7-498b-b8f6-ca461ad9c851)
 regardless of the version, ray_result can be obtained correctly
The issue should be due to the relevant modifications in Skeleton3D

### Minimal reproduction project (MRP)

[TestIntersectRay.zip](https://github.com/godotengine/godot/files/14928943/TestIntersectRay.zip)

**Comment by fire** [comment]
@TokageItLab Can you look into this?

**Comment by TokageItLab** [comment]
After the start of the simulation by `physical_bones_start_simulation`, it seems to be functioning correctly.

I think this issue is caused by the fact that the simulation is explicitly excluded from PhysicsServer3D when it is not running, so it is not detectable from there.

However, since I don't remember changing the registration process of the PhysicsServer3D, I am rather wondering why the past PhysicalBone is still detectable by PhysicsServer3D even though it is not running a simulation. There are performance concerns with having it enabled all the time.

**Comment by fire** [comment]
Maybe fixed by #92279

**Comment by akien-mga** [comment]
> Maybe fixed by #92279

Doesn't seem to be, the MRP is still reproducible in latest `master` (a6ef250f3eada5ba1f9cc3c06663b9f76c7c2279).
