### ISSUE TITLE
Crashes when launching editor on Linux. 

### ISSUE THREAD

**Issue by JoaoVitorSantiagoNogueira** [godotengine/godot#90591]
### Tested versions

- Godot Engine v4.2.1.stable.official.b09f793f5
_Works fine in:_ Godot Engine v3.5.3.stable.official.6c814135b - https://godotengine.org

### System information

Godot: 4.2.1 OS: Ubuntu 22.04.3 LTS GPU: G92 [GeForce GTS 250] Vulkan Instance Version: 1.3.204

### Issue description

When trying to edit a project, program crashes. Depending on the renderer the errors and crash stack change.

**Forward+ and Mobile:**
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.238 - _Forward+ or Forward Mobile_ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.7, 128 bits)
joao@Latin-SMI:~/Downloads$  
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2236)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f33a3e42520] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --

**Compatibility:**
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
joao@Latin-SMI:~/Downloads$ OpenGL API 3.3 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1 - Compatibility - Using Device: Mesa - NV92
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:63)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f7b16442520] (??:0)
[2] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xcf3909) [0x7f7b0fcf3909] (??:0)
[3] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xdc43c5) [0x7f7b0fdc43c5] (??:0)
[4] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xcfddf5) [0x7f7b0fcfddf5] (??:0)
[5] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xcfdf07) [0x7f7b0fcfdf07] (??:0)
[6] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xdbabd4) [0x7f7b0fdbabd4] (??:0)
[7] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xcfcc54) [0x7f7b0fcfcc54] (??:0)
[8] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x9c9e9a) [0x7f7b0f9c9e9a] (??:0)
[9] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x9d2ada) [0x7f7b0f9d2ada] (??:0)
[10] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x18266d) [0x7f7b0f18266d] (??:0)
[11] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x182e8e) [0x7f7b0f182e8e] (??:0)
[12] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x1834cb) [0x7f7b0f1834cb] (??:0)
[13] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x183a23) [0x7f7b0f183a23] (??:0)
[14] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x3d4bae) [0x7f7b0f3d4bae] (??:0)
[15] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x3d19c2) [0x7f7b0f3d19c2] (??:0)
[16] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x3b246c) [0x7f7b0f3b246c] (??:0)
[17] /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x39154f) [0x7f7b0f39154f] (??:0)
[18] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x1065ab6] (??:0)
[19] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x106877d] (??:0)
[20] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x1069b60] (??:0)
[21] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x107fc08] (??:0)
[22] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x108e813] (??:0)
[23] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x368c3d9] (??:0)
[24] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x3691cf5] (??:0)
[25] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x3642df7] (??:0)
[26] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x365c446] (??:0)
[27] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x314a816] (??:0)
[28] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x4fab02] (??:0)
[29] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x41ed28] (??:0)
[30] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f7b16429d90] (??:0)
[31] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f7b16429e40] (??:0)
[32] /home/joao/Downloads/Godot_v4.2.1-stable_linux.x86_64() [0x42aa6a] (??:0)
-- END OF BACKTRACE --

### Steps to reproduce

Launch godot 4.2.1 (Fresh installation)
Start a New Project
Give it a name
Click Create Folder
Select renderer (All will result in a crash, but with different errors)
Create and edit. Reopening the project manager and editing also results in a crash.

### Minimal reproduction project (MRP)

_Error happens prior to being able to edit a project._

**Comment by akien-mga** [comment]
Your GPU doesn't support Vulkan, so it's trying to use the llvmpipe software renderer from Mesa.
Ubuntu 22.04 in turn is pretty old and it's version of Mesa/llvmpipe has broken Vulkan support, which crashes. It's a Mesa bug, but which was fixed a long time ago.

So your options are to use only the Compatibility (OpenGL) renderer, or upgrade Mesa to a newer version.

**Comment by JoaoVitorSantiagoNogueira** [comment]
> Your GPU doesn't support Vulkan, so it's trying to use the llvmpipe software renderer from Mesa. Ubuntu 22.04 in turn is pretty old and it's version of Mesa/llvmpipe has broken Vulkan support, which crashes. It's a Mesa bug, but which was fixed a long time ago.
> 
> So your options are to use only the Compatibility (OpenGL) renderer, or upgrade Mesa to a newer version.

Thank you for your help. Updated mesa, it's now version 23.0.4 (May 2023).
Unfortunately the same errors persist for forward+, mobile and compatibility mode.

**Comment by akien-mga** [comment]
Duplicate of #74172.
