### ISSUE TITLE
Scanline-like artifacts in 3d scenes

### ISSUE THREAD

**Issue by aladvs** [godotengine/godot#91260]
### Tested versions

Reproducible in 4.2 stable & 4.1 stable.

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 31.0.24027.1012) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

Strange scan-line like visual artifacts occur randomly depending on visual settings and camera setup.

### Steps to reproduce

This occurs in the official godot 3d settings demo (copy attached in MRP) 
1. Open project
2. Run project in editor or as exported build
3. Enable 'ultra' settings

The issue can be temporarily remedied by disabling MSAA, but still can occur with it off.
Attached is an image with an example of how it looks.
![image](https://github.com/godotengine/godot/assets/78510667/c1070a93-f707-41c8-a949-5937fb49929f)

### Minimal reproduction project (MRP)

[graphics_settings.zip](https://github.com/godotengine/godot/files/15139981/graphics_settings.zip)

**Comment by TrueJole** [comment]
I've had this too, but only when I exported my project to Windows, it doesn't show in the Editor on Linux. I didn't check it long enough if it still shows after disabling MSAA but it worked for me.
Godot v4.2.2.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (amdgpu; 6.3.6) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

**Comment by clayjohn** [comment]
Can you both test with dev5 (https://godotengine.org/download/archive/4.3-dev5/)? I think this is something that we fixed in 4.3

**Comment by aladvs** [comment]
![image](https://github.com/godotengine/godot/assets/78510667/447c0d30-1252-4954-b240-78453e847ed2)
This still occurs.

https://github.com/godotengine/godot/assets/78510667/26556290-2ac7-45dc-a6bf-0a69263f74f0

**Comment by TrueJole** [comment]
Yep, also still occurs. For me it's MSAA AND VoxelGI turned on that creates this effect.

**Comment by aladvs** [comment]
For me, this occurs only due to *2 MSAA. other settings dont seem to affect it

**Comment by aladvs** [comment]
Still an issue in 4.3.
![image](https://github.com/user-attachments/assets/3d118773-779f-4d6d-a7d1-2a7b2a4f9123)
![image](https://github.com/user-attachments/assets/5cfff3f4-9ec2-46e5-bfb0-a8f6a7f4b696)

**Comment by TrueJole** [comment]
Update: This does not occur when rendering at native 4K. Rendering at a lower scale or native 1080p results in these lines.

**Comment by Calinou** [comment]
> Update: This does not occur when rendering at native 4K. Rendering at a lower scale or native 1080p results in these lines.

Can you enable **View Information** in the Perspective menu in the top-left corner of the 3D editor viewport? Check the resolution the viewport is running at.

Once this is done, try resizing the 3D editor viewport around to see if this issue only occurs with odd (or even) viewport widths/heights.

**Comment by aladvs** [comment]
> Update: This does not occur when rendering at native 4K. Rendering at a lower scale or native 1080p results in these lines.

This is not true. I run at native 1440p and the issue still occurs.

**Comment by aladvs** [comment]
> > Update: This does not occur when rendering at native 4K. Rendering at a lower scale or native 1080p results in these lines.
> 
> Can you enable **View Information** in the Perspective menu in the top-left corner of the 3D editor viewport? Check the resolution the viewport is running at.
> 
> Once this is done, try resizing the 3D editor viewport around to see if this issue only occurs with odd (or even) viewport widths/heights.

Not the one you were replying to, but figured I would test for myself. This occurs at even and odd viewport widths/heights. This occurs when runnning too, not just the viewport.
https://github.com/user-attachments/assets/a851328b-f5fe-4bfe-bbd4-312325631df7

**Comment by TrueJole** [comment]
> > Update: This does not occur when rendering at native 4K. Rendering at a lower scale or native 1080p results in these lines.
> 
> Can you enable **View Information** in the Perspective menu in the top-left corner of the 3D editor viewport? Check the resolution the viewport is running at.
> 
> Once this is done, try resizing the 3D editor viewport around to see if this issue only occurs with odd (or even) viewport widths/heights.

For me it only happens when both x and y size are even. Still, only on windows.

**Comment by TrueJole** [comment]
> > Update: This does not occur when rendering at native 4K. Rendering at a lower scale or native 1080p results in these lines.
> 
> Can you enable **View Information** in the Perspective menu in the top-left corner of the 3D editor viewport? Check the resolution the viewport is running at.
> 
> Once this is done, try resizing the 3D editor viewport around to see if this issue only occurs with odd (or even) viewport widths/heights.

Changing the resolution can hide the effect, but it doesn't depend on whether the size is odd or even. 
2599 * 1387 (no artifacts)
then 2599 * 1388 (artifacts)
back to 2599 * 1387 (suddenly, artifacts)
It varies seemingly at random whether a size will produce the artifact or not
