### ISSUE TITLE
mouse still moving despite captured on wayland, only hidden within window frame

### ISSUE THREAD

**Issue by foolmetuljakut** [godotengine/godot#91577]
### Tested versions

Godot version: v4.2.2.stable.fedora [15073afe3]

### System information

Godot version: v4.2.2.stable.fedora [15073afe3] OS: Fedora Linux 40 (Workstation Edition)

### Issue description

# Observation:
when using 
```
func _ready():
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
```
the mouse hides as expected but can be moved outside the window until it hits the screen boundary. 

- look-around-motion is smooth while within the screen but gets cut off at the boundary.
- mouse reappears outside the window frame

# SystemInformation:
Godot version: v4.2.2.stable.fedora [15073afe3]
OS: Fedora Linux 40 (Workstation Edition)
```
echo $XDG_SESSION_TYPE
wayland
```

### Steps to reproduce

hit play, move mouse to look around

- bump cursor into screen boundary
- move mouse outside of window frame

### Minimal reproduction project (MRP)

[fpsController.tar.gz](https://github.com/godotengine/godot/files/15211924/fpsController.tar.gz)

**Comment by DillBee** [comment]
I can confirm this is still true on the 4.3 release.

**Comment by JohanAR** [comment]
I think this is the same issue as https://github.com/godotengine/godot/issues/90213

Basically Wayland makes it impossible to capture the mouse pointer if it's outside the game window. As a workaround, I used to quickly move the cursor to where I know the game window will open after hitting play, and then I click while the (invisible) cursor is over my window.

I circumvented the problem by capturing the mouse only when my window is focused, e.g.
```
func _notification(what: int) -> void:
	match what:
		NOTIFICATION_APPLICATION_FOCUS_OUT:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		NOTIFICATION_APPLICATION_FOCUS_IN:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
```

**Comment by DillBee** [comment]
You are absolutley right that this falls within the real of Waylands problems.

The good news is that I found the existing bug report on the KDE forums and pushed on reddit for awareness. A developer was made aware and as of the latest KDE builds, this issue is now solved. But it's still on the cutting edge and not filtered down to most large distributions yet.

I do most of my work on KDE neon and the fix is live there.

Link to the bug report: https://bugs.kde.org/show_bug.cgi?id=483067

**Comment by leaf-node** [comment]
This is what worked for me, based on @JohanAR's answer:

``` gdscript
# res://global.gd
extends Node

signal _mouse_capture_change_signal()

var focused: bool

func _notification(what: int) -> void:
	match what:
		NOTIFICATION_WM_MOUSE_ENTER:
			emit_signal("_mouse_capture_change_signal")
		NOTIFICATION_WM_MOUSE_EXIT:
			emit_signal("_mouse_capture_change_signal")
		NOTIFICATION_APPLICATION_FOCUS_IN:
			focused = true
		NOTIFICATION_APPLICATION_FOCUS_OUT:
			focused = false
```

``` gdscript
# res://levels/pause_label.gd
extends Label

func _ready() -> void:
	Global._mouse_capture_change_signal.connect(mouse_capture_change)
	pause_level(false)

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		pause_level(!get_tree().paused)

func mouse_capture_change():
	var mouse = get_global_mouse_position()
	if !get_tree().paused and get_viewport_rect().has_point(mouse):
		Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	else:
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)

func pause_level(value: bool) -> void:
	get_tree().paused = value
	if value:
		show()
	else:
		hide()
	mouse_capture_change()
```

If you're implementing this with pausing behavior, it's also necessary to Set the label's `Process` setting to `Always`, otherwise, you won't be able to unpause the game.

As a bonus, `Global.focus` can be checked before accepting controller button inputs when another window is in focus on a desktop.

**Comment by deralmas** [comment]
Hi, this should be hopefully be fixed by #120647 now. Please give it a shot!

Edit: sorry I originally copy-pasted the wrong number above.

**Comment by Chestnut45** [comment]
Unfortunately still reproducing this issue on 4.7.2. ~~so #120647 is not a complete fix.~~

Godot v4.7.2.stable - Ubuntu 26.04 LTS 26.04 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1240P (16 threads) - 15.32 GiB memory - PulseAudio (44100 Hz, Stereo/mono)

https://github.com/user-attachments/assets/3b4e7a31-3763-4111-8cd8-435f8c2f46be

**Comment by deralmas** [comment]
@Chestnut45 unfortunately that's a separate issue. KDE itself has a bug where it can't lock on a subsurface (what we use for game embedding). For the time being the only solution is to disable embedding altogether: https://docs.godotengine.org/en/4.7/tutorials/editor/game_embedding.html

**Comment by Chestnut45** [comment]
Oh I see! Thank you for the info.

Indeed disabling embedding causes capturing to behave as expected on Wayland (once the mouse enters the window it is captured correctly from that point onward, tested on 4.7.2 and 4.7), apologies for the incorrect comment.

Do you happen to know where I can find more information about the KDE subsurface bug? Having a tough time finding information on it. With embedding enabled, I see the bug but only sometimes - on some launches (fairly rarely) it is captured correctly immediately, but on most other launches the bug persists.

**Comment by deralmas** [comment]
> Do you happen to know where I can find more information about the KDE subsurface bug? Having a tough time finding information on it. With embedding enabled, I see the bug but only sometimes - on some launches (fairly rarely) it is captured correctly immediately, but on most other launches the bug persists.

Unfortunately there isn't much, it's a pretty obscure bug! The first obcurrence I could find is [this KDE bug](https://bugs.kde.org/show_bug.cgi?id=463088) so the thing is at least reported.

Then, mahkoh did some testing in an [fdo issue](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/work_items/287#note_3167468). I also did lots of testing myself much later over at #120647.

I could have swore that I had talked about this on IRC/Matrix but I can't seem to find anything???? So I'm afraid that this is pretty much it. That said I haven't given a look at the mailing list and freenode archives.

Given the above I feel like I should bump the KDE ticket... Maybe they have no idea this bug affects Godot xD

BTW, sway/wlroots has a similar bug and I have no idea if a ticket got ever opened.

**Comment by Chestnut45** [comment]
Thanks very much for the links! FWIW I agree bumping the KDE ticket is probably a good idea so they're aware it's not *that* niche of an issue 😅
