### ISSUE TITLE
False claim that "Variable [name] was used but never assigned a value"

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#91876]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When a Vector2 variable (and probably others too) is defined separately for x and y, Godot's IDE is reporting that a variable was used but never assigned a value despite the value being assigned in the next two lines.

### Steps to reproduce

Paste this code and you will get a report that a variable "P" was never assigned a value:
```
var P : Vector2
P.x = position.x
P.y = position.y * 2
```

But this will not trigger any warnings:
```
var P : Vector2
P = Vector2( position.x, position.y * 2)
```

### Minimal reproduction project (MRP)

(see above)

**Comment by AThousandShips** [comment]
Please try with 4.2.2, some changes related to this were solved recently I believe, and if you could with [4.3.dev6](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-6/)

**Comment by AThousandShips** [comment]
Can confirm that this is fixed in 4.3, can't test 4.2.2 myself right now though, was probably fixed for 4.3 in:
* https://github.com/godotengine/godot/pull/90442

**Comment by matheusmdx** [comment]
In 4.2.2 the warning still appearing

![image](https://github.com/godotengine/godot/assets/44306054/3038bed5-a440-42db-b0d7-bbb908ea26c7)

**Comment by AThousandShips** [comment]
Then the question is if this should be backported to 4.2 or not, it's relatively harmless and you can silence it by just assigning something when declaring it anyway

**Comment by dalexeev** [comment]
> Then the question is if this should be backported to 4.2 or not

I think not, since #90442 changed even the meaning of the warning (now it's produced on the variable usages, not on the declaration). This is definitely too big a change for a patch release.

* Duplicate of #88117.
* Fixed for future 4.3 by #90442.

Thanks for reporting the bug nonetheless!
