### ISSUE TITLE
Windows input: Modifier keys get stuck after alt+tab

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#92304]
### Tested versions

- Reproducible in 4.3.beta bd2300d
- Not reproducible in 4.2.1
- Not reproducible in 4.3 2efbc6bf

### System information

Godot v4.3.beta (bd2300d77) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When alt-tabbing *into* godot (or sometimes when alt-tabbing out of godot), the alt key seems to remain stuck. Weird things start happening such as multiple carets in the text editor or keys cause bottom panels to pop up.

The user must recognize the alt key is stuck and press all the modifier keys once to clear.

This issue does not reproduce every time.

### Steps to reproduce

1. it helps to be doing something at the time, such as camera orbit (see the other related issues)
2. Alt-tab out of Godot
3. Alt-tab into Godot
4. Press the d key. If the issue has reproduced, the debugger window will pop up.
5. Any key pressed will act as if alt is held.
6. Press the alt key to clear.
7. Repeat.

### Minimal reproduction project (MRP)

Reproduces on an empty new project

**Comment by SaracenOne** [comment]
12fda2fc13426799bd4376c1fbd99b179c685559 may have caused the regression.

**Comment by zaftnotameni** [comment]
can confirm/reproduce this consistently as well (windows 10, godot 4.3-beta1)
pretty much every time I press "alt", it goes into sticky keys mode

**Comment by matheusmdx** [comment]
This was already solved in latest master [96a386f](https://github.com/godotengine/godot/commit/96a386f3c424af96d950ee5098b4b0e4907c9508) by #92415 (see https://github.com/godotengine/godot/issues/92759#issuecomment-2148797918)

**Comment by KoBeWi** [comment]
I have I think a duplicate issue #81211 and I just confirmed it's not fixed on master.
