### ISSUE TITLE
MeshInstance material is ignored in-game by PrimitiveMesh

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9234]
**Operating system or device - Godot version:** Godot 3, Linux

**Issue description:**
Material looks ok in editor, but totally white when in game.
I tried changing alpha, metallic and roughness but no difference at all.
Using a directional light. The material is on Mesh (Plane)

game:
![screenshot from 2017-06-17 08-44-13](https://user-images.githubusercontent.com/1642015/27251176-7568593a-5339-11e7-8ddf-45467094dc4c.png)

editor:
![screenshot from 2017-06-17 08-43-57](https://user-images.githubusercontent.com/1642015/27251178-76b66174-5339-11e7-86a5-4eb77747ab35.png)

**Comment by eon-s** [comment]
Not sure if is the same but when starting the project manager and editor I get

> ERROR: add_property: Invalid Setter: Environment::set_ssr_accel for property: ss_reflections_accel
>    At: core/class_db.cpp:763.

Then, the environment (a default one with procedural skybox) seems to be ignored when running:

![captura de pantalla de 2017-06-17 13-32-02](https://user-images.githubusercontent.com/10215987/27254602-e0bd4dda-5361-11e7-80ab-b99e397f9680.png)

**Comment by nunodonato** [comment]
I found (part) of the problem.

If I assign the material inside the PrimitiveMesh properties, it will work ok. But if I assign in the MeshInstance, it wont be used at all.

**Comment by nunodonato** [comment]
Upon more testing I realized that the Material Override in Geometry Instance seems to work fine. So it's just the Material in the MeshInstance that seems to be ignored by these Primitives

**Comment by BastiaanOlij** [comment]
Thats weird, I was indeed under the impression Godot takes care of this inside of the Mesh base class. I've basically using the same approach as ArrayMesh is so it may be that ArrayMesh suffers from the same issue.

@reduz any ideas where I should start looking?

**Comment by vnen** [comment]
I noticed that GIProbes don't consider the light emitted from PrimitiveMeshes (no matter if the material is set on the node or the resource), and maybe it is a consequence of this.

**Comment by reduz** [comment]
I´m confident that both these things should be fixed now, so closing. In any case test if you want and reopen.

**Comment by ZorionTen** [comment]
Still not working for me ... amterials are loaded in editor but not in game. Exported as obj from TinkerCAD online.
