### ISSUE TITLE
Crash when trying to export without a project

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92606]
### Tested versions

4.3 beta1 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When exporting from empty folder, the engine crashes:
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.beta.custom_build (705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] EditorSettings::create (C:\godot_source\editor\editor_settings.cpp:1061)
[1] EditorNode::EditorNode (C:\godot_source\editor\editor_node.cpp:6429)
[2] Main::start (C:\godot_source\main\main.cpp:3706)
[3] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:179)
[4] _main (C:\godot_source\platform\windows\godot_windows.cpp:206)
[5] main (C:\godot_source\platform\windows\godot_windows.cpp:220)
[6] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:234)
[7] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[8] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```
The culprit seems to be this code:
https://github.com/godotengine/godot/blob/705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427/main/main.cpp#L1770-L1783
If the project is found, everything works normally.
If it's not found:
- in non-editor build go to `error` and abort
- in editor build, disable editor and continue normally... 🤦‍♂️

So it continues and tries to do editor stuff without editor hint. The above crash happens in editorless EditorNode, which can't create EditorSettings, because it's not in editor. There is a variation of this crash that happens in EditorFileSystem, which tries doing filesystem scan.

### Steps to reproduce

Run `godot --headless --export-release "anything"` in an empty folder (no `project.godot`).
If you omit `"anything"` you'll get a different crash.

### Minimal reproduction project (MRP)

[New folder.zip](https://github.com/user-attachments/files/15518759/New.folder.zip)

**Comment by akien-mga** [comment]
Duplicate of https://github.com/godotengine/godot/issues/91527, or the other way around, whichever is clearer.

With several reports on beta 1, is that a recent regression?

**Comment by KoBeWi** [comment]
The comments in #91527 are unrelated to the original issue, which doesn't involve any crash. They are 2 separate bugs.

**Comment by RealMadvicius** [comment]
If you look at this section 

https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/editor/editor_settings.cpp#L1059-L1067

You can see that we call **singleton->set_path** before checking if "singleton" is null, which lead to some "undefined behaviour". To improve things, we should have the **if (singleton.is_null())** done just after the call to **singleton = ResourceLoader::load**.

Same thing here :
https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/main/main.cpp#L3704-L3709

We call **gdscript->get_documentation()** without checking if gdscript isnt a null pointer which can lead to crash aswell potentially

**Comment by jsjtxietian** [comment]
> You can see that we call **singleton->set_path** before checking if "singleton" is null, which lead to some "undefined behaviour". To improve things, we should have the **if (singleton.is_null())** done just after the call to **singleton = ResourceLoader::load**.



Yes I noticed this nullptr too.

I also has crash here, `f` is null : 
```
String extension_list_config_file = GDExtension::get_extension_list_config_file();
if (extensions.size()) {
	if (extensions_added.size() || extensions_removed.size()) { //extensions were added or removed
		Ref<FileAccess> f = FileAccess::open(extension_list_config_file, FileAccess::WRITE);
		for (const String &E : extensions) {
			f->store_line(E);
		}
	}
}
```

**Comment by KoBeWi** [comment]
The crash was fixed by #94593. Now exporting results in some errors:
```
ERROR: Class 'EditorSettings' can only be instantiated by editor.
   at: _instantiate_internal (core/object/class_db.cpp:521)
ERROR: Could not load editor settings from path: C:/Users/Tomek/AppData/Roaming/Godot/editor_settings-4.3.tres
   at: create (editor/editor_settings.cpp:1067)
ERROR: Cannot save project metadata to file 'res://.godot/editor/project_metadata.cfg'.
   at: (editor/editor_settings.cpp:1326)
ERROR: Cannot create file 'res://.godot/editor/filesystem_cache8'. Check user write permissions.
   at: (editor/editor_file_system.cpp:418)
ERROR: This project doesn't have an `export_presets.cfg` file at its root.
Create an export preset from the "Project > Export" dialog and try again.
   at: _fs_changed (editor/editor_node.cpp:1028)
```
None of them really tell what's the problem, so maybe we could detect this and print a proper error.

**Comment by jsjtxietian** [comment]
With `godot --headless --export-release` I still get a crash:

```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.rc.custom_build (3978628c6cc1227250fc6ed45c8d854d24c30c30)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] EditorFileSystem::doing_first_scan (E:\godot\editor\editor_file_system.h:341)
[1] EditorFileSystem::doing_first_scan (E:\godot\editor\editor_file_system.h:341)
[2] Main::iteration (E:\godot\main\main.cpp:4192)
[3] OS_Windows::run (E:\godot\platform\windows\os_windows.cpp:1666)
[4] widechar_main (E:\godot\platform\windows\godot_windows.cpp:181)
[5] _main (E:\godot\platform\windows\godot_windows.cpp:206)
[6] main (E:\godot\platform\windows\godot_windows.cpp:220)
[7] WinMain (E:\godot\platform\windows\godot_windows.cpp:234)
[8] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[9] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```
