### ISSUE TITLE
some operations in subresource of inspector will cause unexpected scroll behavior

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#92652]
### Tested versions

reproducible in 4.3 dev1/dev2/dev3/dev4/dev5/dev6/beta1

### System information

MacOS 14.5 Vulkan Forward+

### Issue description

if you take some operations (like check or uncheck, select item from item list) in subresource of inspector, it will automatically make value of inspector scrollbar back to like 2~3(not 0)

before beta1(I mean dev1/dev2/dev3/dev4/dev5/dev6), directly take some operations in resource file inspector will also automatically make value of inspector scrollbar back to like 2~3(I guess)

https://github.com/godotengine/godot/assets/64188282/20dbd191-15dd-4167-8173-55de5507aef5

beta1

https://github.com/godotengine/godot/assets/64188282/38bcd055-95bd-4d5a-8ee2-1a0d2b07e036

### Steps to reproduce

open editor settings
find "Disable Folding" setting and check it
test it

### Minimal reproduction project (MRP)

[godot43b1.zip](https://github.com/user-attachments/files/15522759/godot43b1.zip)

**Comment by AThousandShips** [comment]
Similar to:
* https://github.com/godotengine/godot/issues/91287

Might be that subresources weren't fixed with that

**Comment by snougo** [comment]
Still reproducible in 4.3 beta 2

**Comment by snougo** [comment]
still reproduce in Godot 4.3 rc1

**Comment by QbieShay** [comment]
Can you test in latest dev? I can't repro.

**Comment by snougo** [comment]
> Can you test in latest dev? I can't repro.

you are right, somehow this issue has be fixed in 4.4 dev4

**Comment by kpietraszko** [comment]
Still happens in 4.4.1. I've noticed it works fine when the inspector is made floating.
This is really annoying, I'd appreciate if someone could take a closer look at this.
