### ISSUE TITLE
Normal maps do not import correctly

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#9267]
**Operating system or device - Godot version:**
Mac OS X 10.12.5 - Godot 3.0

**Issue description:**
Normal maps do not import correctly, look all garbled:
![yucky normal maps](https://user-images.githubusercontent.com/1945449/27283572-41dd462e-5538-11e7-828f-6228588e0bcf.jpg)

**Steps to reproduce:**
Add a normal map to your project, use it as your normal map :)

**Link to minimal example project:**
https://github.com/BastiaanOlij/godot3_test_projects/tree/master/TestPrimitives

**Comment by reduz** [comment]
I think i fixed this eventually, did you try reimporting them if you had
them already imported?

**Comment by BastiaanOlij** [comment]
@reduz I did reimport when I tried this but it was 2 days ago, I'll retry on a fresh build tonight.

**Comment by BastiaanOlij** [comment]
Sorry @reduz, just build from master and re-imported all the maps, still the same results...

**Comment by BastiaanOlij** [comment]
I'm wondering if this is some weird issue with generating the mipmaps. Moving the camera closer/further away it goes from rendering correctly to all sorts of weirdness. This image seems to show it well:
![image](https://user-images.githubusercontent.com/1945449/27797611-a7b4eac8-6051-11e7-8f08-09b43876f971.png)
You can see the 4 and the 3 render pretty normally with the normal maps giving a nice effect.
But especially on the 2 you can see the normal map being repeated in ever smaller copies.

**Comment by BastiaanOlij** [comment]
Hey @reduz , unless you fixed this last night, this may be a Mac OS X only problem. Just tried it on Windows and it is working fine on Windows.

**Comment by toger5** [comment]
Just tried that on Mac too.
running into the same issue. Normal maps don't work properly.

compiled with current master.

<img width="730" alt="screen shot 2017-08-04 at 00 11 37" src="https://user-images.githubusercontent.com/16718859/28946091-846860ac-78a9-11e7-875c-4654ebe2efc0.png">

**Comment by akien-mga** [comment]
Maybe related to #9939.

**Comment by BastiaanOlij** [comment]
@reduz this bug is still there. At least on the master from this Saturday. May be premature to close this.

**Comment by reduz** [comment]
I fixed it 20 minutes ago

**Comment by BastiaanOlij** [comment]
@reduz you're the man! I will test tonight :)

**Comment by bojidar-bg** [comment]
@BastiaanOlij Did you get to testing it?

**Comment by toger5** [comment]
I tested and had no artifacts. But i didnt pay special attention to it... Still pretty sure it qorked.
