### ISSUE TITLE
Animation track keys shift position when selected

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92884]
### Tested versions

v4.3.beta.custom_build [e96ad5af9]
Not happening in 4.3 beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Animation keys are bugged. I had this situation, where selecting a key would shift it by a constant distance:

https://github.com/godotengine/godot/assets/2223172/192f66db-f9bb-49bf-8560-9d6894201304

Not sure how to reproduce it, but a similar bug is easy to reproduce.

### Steps to reproduce

1. Have an animation with at least 1 key
2. Right click the key (make sure it wasn't selected before clicking)
3. Left click next to the key

https://github.com/godotengine/godot/assets/2223172/bf646804-36c0-4e9d-92c3-40ab23222497

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Bisecting points to #92424 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/46ad428f-6d1c-4459-b13f-8e5ac71edced)

**Comment by TokageItLab** [comment]
I have investigated and found that the problem is probably due to the fact that `InputEventMouseMotion` at line 3049 in `animation_track_editor.cpp` is valid even though it should not be fired when closing a popup. But in BezierEdit, mouse events are not fired when closing a popup.

```cpp
if (mm.is_valid() && mm->get_button_mask().has_flag(MouseButtonMask::LEFT) && moving_selection_attempt) {
	if (!moving_selection) {
		moving_selection = true;
		emit_signal(SNAME("move_selection_begin"));
	}

	float moving_begin_time = ((moving_selection_mouse_begin_x - timeline->get_name_limit()) / timeline->get_zoom_scale()) + timeline->get_value();
	float new_time = ((mm->get_position().x - timeline->get_name_limit()) / timeline->get_zoom_scale()) + timeline->get_value();
	float delta = new_time - moving_begin_time;
	float snapped_time = editor->snap_time(moving_selection_pivot + delta);

	float offset = 0.0;
	if (abs(editor->get_moving_selection_offset()) > CMP_EPSILON || (snapped_time > moving_selection_pivot && delta > CMP_EPSILON) || (snapped_time < moving_selection_pivot && delta < -CMP_EPSILON)) {
		offset = snapped_time - moving_selection_pivot;
		moving_selection_effective = true;
	}

	emit_signal(SNAME("move_selection"), offset);
}
```

It seems that https://github.com/godotengine/godot/pull/92424 is causing the unintended firing of mouse events, but I don't have a detailed reason as to why this is happening.

@bruvzg Do you have any idea?

**Comment by bruvzg** [comment]
Check if it's fixed by https://github.com/godotengine/godot/pull/93105, might be the same issue.

**Comment by TokageItLab** [comment]
@bruvzg The issue still occurs in the latest commit after merging it, so it seems to be a different problem.

**Comment by bruvzg** [comment]
Seems like mouse move event can be received after closing popup wit
h a click and button can be still pressed, but I do not see anything wrong with it, since mouse is moving and button is pressed.

You can also do the same by opening a popup menu, holding down the left button (while hovering the menu separator) and closing the menu with ESC, the key will be moving until you release the button.
