### ISSUE TITLE
The behavior of KinematicBody2D is not consistent

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9325]
**Operating system or device - Godot version:**
godot 2.1.3

**Issue description:**

it's a very simple update method that make a body move on the ground and when it hit a wall, it will move in the opposite direction. It works sometimes.  But sometimes it will not  bounce back when hit a wall, it will just stop by the wall. 
```gdscript
func _fixed_process(delta):
	vel.y += 2000 * delta
	var motion = move(vel * delta)
	if is_colliding():
		var normal = get_collision_normal()
		if normal.x != 0:
			vel.x = -vel.x
		else:
			vel.y = 0
		motion = normal.slide(motion)
		move(motion)
```
**Steps to reproduce:**

**Link to minimal example project:**

<sub>bugsquad edit: reformatted script.</sub>

**Comment by eon-s** [comment]
Where are the last 2 lines? (no indentation makes hard to see)
How big are your walls? (2000 units/second could be high speed and get weird effects against small colliders)

If you can provide a project, it could help to test better.

**Comment by alexzheng** [comment]
fast moving body pass through an obstacle is another issue.
This is just a very common example.

**Comment by alexzheng** [comment]
[Uploading issue.zip…]()

2 issues in this simple demo:
1 the body will not bounce back, but it would bounce back if make the size of the shape a little smaller
2 the cat outside the screen should not move into the screen.

**Comment by alexzheng** [comment]
I can not upload a zip file currently, I will try it again later.

**Comment by alexzheng** [comment]
[issue.zip](https://github.com/godotengine/godot/files/1097099/issue.zip)

**Comment by alexzheng** [comment]
it seems this issue happens only when the size of the rectangle shape is set to some values.

**Comment by eon-s** [comment]
@alexzheng I think you found a new effect of an old bug, it seems that move keeps old data in the same frame, is already fixed but on 2.1.3 needs to be toggled on in `project settings>physics2d>motion_fix_enabled`.

To avoid things like this is why I have suggested #9137

**Comment by alexzheng** [comment]
yes, this fix my issue, thanks for your reply.
It seems the move api is still not ready for production yet, it has some other issues as I reported.

**Comment by akien-mga** [comment]
This is likely fixed in 3.0 already, the move() API was reworked as move_and_slide() and should be more efficient.

**Comment by RandomShaper** [comment]
Manually closing because of #9866.
