### ISSUE TITLE
3D billboards mesh shadows face light source instead of facing camera

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#936]
Hi,

Godot RC1, win64, windows8.1.

When you set the BillBoard option of a MeshInstance, the shadow is calculated with the MeshInstance facing the light source, instead of facing the active Camera.

![screencap](https://cloud.githubusercontent.com/assets/9801802/5331462/fea69cfa-7e2c-11e4-9447-0ace0aa9eeeb.png)

Into this capture, the top mesh is rotated manually to face the camera. Its shadow is correct.
The bottom mesh has its Billboard option set to On. Its shadow is incorrect.

The bottom shadow should looks like the top shadow.

The light source is Directional Light with a rotation vector set to -90, 45, 90.
The camera is looking top-down.

**Comment by akien-mga** [comment]
Hi, could you provide a scene that reproduces this issue if still valid in the current master branch?

**Comment by akien-mga** [comment]
Ping.

**Comment by SuperUserNameMan** [comment]
Sorry for the delay. I did to used godot for a while and had thousands of github notifications since then.

The bug seems still present into 2.0.2.stable official release.

HEre is a scene that I created back godot RC1 that you can import into 2.0.2.
It show a billboarded cube exhibiting the shadow bug.

[bugs - 3d billboard and shadows.zip](https://github.com/godotengine/godot/files/231776/bugs.-.3d.billboard.and.shadows.zip)

**Comment by akien-mga** [comment]
I can confirm the bug using the above project. Tagging for the 3.0 milestone so that it's fixed *at the latest* then when shadows will be reworked, but if someone wants to fix it before that, don't hesitate :)

**Comment by nunodonato** [comment]
I don't think this is really a bug.
In many cases, you want the shadows to face the light source and not the camera.
See this video for an example: https://www.youtube.com/watch?v=8Ij56E9qudI
the entire forest is made of billboard trees, and it wouldn't make any sense to have the shadows align with the camera.

Perhaps there are many different use cases for billboards, so maybe a toggle-able option that would allow both kind of shadows would be the best solution

**Comment by reduz** [comment]
This was fixed in 3.1. Besides facing the proper side, billboards are now in the vertex shader and enabled via material toggle.

**Comment by reduz** [comment]
err in 3.0 i mean

**Comment by Banderi** [comment]
This actually still happens on my end, albeit not with meshes, rather with bill-board 3D sprites.
