### ISSUE TITLE
Saving a TileMap node as scene, crashes the editor

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9367]
**Ubuntu 17.04- Godot version: 2.1.2/2.1.3**

**Issue description:**
Saving a TileMap node (on the tree) as a separate scene, crashes the editor after saving (sometimes do not save).

This only happens if the TileMap is the root of the new scene, if the TileMap is child of the node saved as scene, it works.

**Steps to reproduce:**
Can be tested with demos (kinematic character, platformer).
Select a TileMap and save it as a new scene.

**Comment by AlexHoratio** [comment]
Cannot reproduce this bug on Debian Stretch, interesting. Does the TileMap have relevant children?

**Comment by eon-s** [comment]
@AlexHoratio on both demos do not have any children.

**Comment by MrMaidx** [comment]
I tried to reproduce it with one of a latest build on Windows 7 and I was not able to reproduce it. Maybe it was already resolved?

**Comment by eon-s** [comment]
Still happens on 2.1/HEAD but on Linux only (tried on 2 different machines), tested on Windows 10 and works fine there.

So this seems to be a Linux version problem.

The crash is silent, not a single message.

**Comment by akien-mga** [comment]
Can you get a stacktrace with gdb?

**Comment by eon-s** [comment]
Got this when trying to save (gdb):

> Thread 1 "godot.x11.tools" received signal SIGSEGV, Segmentation fault.
> 0x0000555556ad97b1 in HashMap<StringName, Object::Signal, StringNameHasher, (unsigned char)3, (unsigned char)8>::get_entry (this=0x55555d7810f8, p_key=...)
>     at core/hash_map.h:198
> 198			Entry *e = hash_table[index];

**Comment by eon-s** [comment]
Tested on a recent 3 and no problems, so is just a 2.x thing.

And for some reason didn't pasted the full bt :upside_down_face: 
Anyway, got a different message too on e85be2f5d:

> 
> Thread 1 "godot.x11.tools" received signal SIGSEGV, Segmentation fault.
> 0x0000555556adecb5 in HashMap<StringName, Object::Signal, StringNameHasher, (unsigned char)3, (unsigned char)8>::get_entry (this=0x55555d7b2878, p_key=...)
>     at core/hash_map.h:203
> 203				if (e->hash == hash && e->pair.key == p_key) {
> (gdb) bt
> #0  0x0000555556adecb5 in HashMap<StringName, Object::Signal, StringNameHasher, (unsigned char)3, (unsigned char)8>::get_entry (this=0x55555d7b2878, p_key=...)
>     at core/hash_map.h:203
> #1  0x0000555556adcc58 in HashMap<StringName, Object::Signal, StringNameHasher, (unsigned char)3, (unsigned char)8>::getptr (this=0x55555d7b2878, p_key=...)
>     at core/hash_map.h:330
> #2  0x0000555556ad7215 in Object::disconnect (this=0x55555d7b2870, 
>     p_signal=..., p_to_object=0x55555ca5e9d0, p_to_method=...)
>     at core/object.cpp:1412
> #3  0x0000555555e44db6 in TileMapEditor::edit (this=0x55555ca5e9d0, p_tile_map=
>     0x0) at editor/plugins/tile_map_editor_plugin.cpp:1323
> #4  0x0000555555e496bb in TileMapEditorPlugin::make_visible (
>     this=0x55555ca5e790, p_visible=false)
>     at editor/plugins/tile_map_editor_plugin.cpp:1595
> #5  0x0000555555acf964 in EditorPluginList::make_visible (this=0x5555596e8590, 
>     p_visible=false) at editor/editor_node.cpp:6411
> #6  0x0000555555aa1e1c in EditorNode::_display_top_editors (
>     this=0x5555584864b0, p_display=false) at editor/editor_node.cpp:1527
> #7  0x0000555555aa256d in EditorNode::_edit_current (this=0x5555584864b0)
>     at editor/editor_node.cpp:1634
> #8  0x0000555555aa12dd in EditorNode::push_item (this=0x5555584864b0, 
>     p_object=0x55555d7f48f0, p_property=...) at editor/editor_node.cpp:1431
> #9  0x0000555555bcc068 in SceneTreeDock::_node_selected (this=0x55555a0b6d90)
>     editor/scene_tree_dock.cpp:724
> #10 0x00005555557baf5c in MethodBind0::call (this=0x55555a2d3470, p_object=0x55555a0b6d90, p_args=0x0, p_arg_count=0, r_error=...)
>     at core/method_bind.gen.inc:47
> #11 0x0000555556ad2f3e in Object::call (this=0x55555a0b6d90, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at core/object.cpp:853
> #12 0x0000555556a23509 in MessageQueue::_call_function (this=0x555557c66d70, p_target=0x55555a0b6d90, p_func=..., p_args=0x7fffefb2b1d0, 
>     p_argcount=0, p_show_error=true) at core/message_queue.cpp:298
> #13 0x0000555556a23775 in MessageQueue::flush (this=0x555557c66d70) at core/message_queue.cpp:343
> #14 0x00005555560c7da3 in SceneTree::input_event (this=0x5555584bf270, p_event=...) at scene/main/scene_main_loop.cpp:432
> #15 0x000055555569efd5 in InputDefault::parse_input_event (this=0x555558028f50, p_event=...) at main/input_default.cpp:349
> #16 0x000055555568797b in OS_X11::process_xevents (this=0x7fffffffda40) at platform/x11/os_x11.cpp:1392
> #17 0x0000555555689eff in OS_X11::run (this=0x7fffffffda40) at platform/x11/os_x11.cpp:1947
> #18 0x0000555555681814 in main (argc=4, argv=0x7fffffffdf98) at platform/x11/godot_x11.cpp:49
