### ISSUE TITLE
.obj material surfaces aren't imported.

### ISSUE THREAD

**Issue by DriNeo** [godotengine/godot#9445]
**Operating system or device - Godot version:**
LMDE - Godot master branch.

**Issue description:**
Godot ignore surfaces included in "Wavefront" .obj files. Whatever the amount of materials in the model there is always one material in MeshInstance inspector.

**Steps to reproduce:**
-Create a mesh with several materials in your favorite modeling software and export the model as a .obj file.
-Include this file in a MeshInstance.
-Check the number of materials in the inspector.

**Comment by bojidar-bg** [comment]
(tagging as 3.0 since the original report is for that version. I guess it also applies to 2.1 though)

**Comment by DriNeo** [comment]
There's something new today.
I import the obj file into Wings3D and create materials inside, then export the model again.
In Blender that new file are split into several objects.

![capture du 2017-07-02 19-42-17](https://user-images.githubusercontent.com/12350741/27772258-a387c234-5f5e-11e7-8550-df9a552e3b69.png)

I export the model a last time and Godot display all the materials slots.

![capture du 2017-07-02 19-53-35](https://user-images.githubusercontent.com/12350741/27772328-35c4c8c6-5f60-11e7-85b3-2bdd368b2e62.png)

I'm not experienced in 3D modeling so I can't say if it's an acceptable workflow or simply a cumbersome workaround.

**Comment by reduz** [comment]
Obj import as a single mesh, for scenes you have to use collada

**Comment by DriNeo** [comment]
Yes but .obj files allows several material surfaces in a single mesh, I noticed this in Blender, and this format is simple and can be opened everywhere.
Are you OK to ignore the surfaces stored in .obj file ?
If it is the case feel free to close.

**Comment by reduz** [comment]
No.. they should be added

**Comment by DriNeo** [comment]
No problem ! This is not an emergency, it was just to clarify.
Thanks for your posts.

**Comment by DriNeo** [comment]
Something has changed. I try to understand how to manage .obj files now. The import dock stays empty and I can't select the file for the meshinstance.

**Comment by eon-s** [comment]
@DriNeo Godot now imports the obj as scene, try to open it (double click) and create a new inherited scene like with dae files.

**Comment by DriNeo** [comment]
@eon-s The MeshInstance node still exists, how to load a mesh ?

**Comment by reduz** [comment]
The problem is that generally OBJ files may come with many objects, so this
workflow was a bit broken.
The idea, if you want individual meshes, is to import the scene, then ask
to save the meshes separatedly. At the end it should be about the same.
Will do some work today to make this clearer.

**Comment by eon-s** [comment]
An option/plugin to save meshes on a scene as resources could be handy, or an extra option in the mesh button (the one that allows to create collision shapes) as a shortcut.

**Comment by reduz** [comment]
I'm also adding an option to save children of root nodes as sub-scenes,
that should help to make multiple instantiable objects with collision easily

**Comment by reduz** [comment]
Done, added a few presets for this so you can choose your best workflow:
![image](https://user-images.githubusercontent.com/6265307/28503197-488bac1c-6fd8-11e7-8758-d9dee1e4c831.png)

**Comment by DriNeo** [comment]
Since this update the import dock displays nothing on my machine if I select an .obj file (works fine for other resources). Did I miss something ?

**Comment by reduz** [comment]
I think probably the OBJ importer code should be isolated and made to work
for both scenes and meshes then

**Comment by reduz** [comment]
the original issue is fixed, will leave this open to remind me to fix old obj workflow

**Comment by reduz** [comment]
This ability has been restored. Rejoice.

**Comment by MajorMcDoom** [comment]
This issue is back in 4.2. Importing OBJ as a mesh makes it just have one surface, even if the file contains multiple. :(
