### ISSUE TITLE
Custom actions in Input Map are not saved to PCK

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#9472]
**Operating system or device - Godot version:**
3.0 MASTER

**Issue description:**
Exported to PCK and ran indipendently.

```gdscript
func _unhandled_key_input(event):
   if event.is_action_released("toggle_fullscreen"):
      print("clicked")    
```

works when running from editor

**Steps to reproduce:**
Create a custom input map action. export to PCK and run.

**Link to minimal example project:**

**Comment by reduz** [comment]
Ah right.. no serializing of binary objects yet, need to add that

On Jul 2, 2017 1:46 PM, "Saggi Mizrahi" <notifications@github.com> wrote:

*Operating system or device - Godot version:*
3.0 MASTER

*Issue description:*
Exported to PCK and ran indipendently.

func _unhandled_key_input(event):
   if event.is_action_released("toggle_fullscreen"):
      print("clicked")

works when running from editor

*Steps to reproduce:*
Create a custom input map action. export to PCK and run.

*Link to minimal example project:*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/9472>, or mute the thread

**Comment by Sslaxx** [comment]
Note that defining custom inputs in the project settings does not save them.

**Comment by akien-mga** [comment]
This is a must have for alpha2, as right now the export workflow is kind of broken.

**Comment by HummusSamurai** [comment]
Possibly solved by https://github.com/godotengine/godot/commit/b7571582ed95e1a7530e6b4251d99098e4175cc6?

**Comment by Sslaxx** [comment]
No. Custom inputs are not saved anywhere. I would have assumed that, like with 2.1.x, they would have been stored in (what is now) project.godot, but they aren't.

**Comment by reduz** [comment]
@Sslaxx, @HummusSamurai : In theory b757158 fixes this, but I did not test it. Any testing is appreciated

**Comment by Sslaxx** [comment]
@reduz - It doesn't, I've already tried it. As I stated above, it does not save any custom defined inputs in the project, ergo they cannot be exported.

**Comment by reduz** [comment]
@Sslaxx wait, this is a different problem.. you mean custom actions don't work even within the editor? I dont see this problem..

**Comment by Sslaxx** [comment]
You can create them but it doesn't save them.

**Comment by vnen** [comment]
I can create new actions and they are saved, but adding inputs to the default actions doesn't work.

**Comment by reduz** [comment]
this issue is now fixed, but regarding adding input to default actions please open a new one

**Comment by hickop** [comment]
I'm still having issues on linux.

Those errors happens when starting the exported bin:
```
ERROR: decode_variant: Condition ' (type & 0xFF) >= Variant::VARIANT_MAX ' is true. returned: ERR_INVALID_DATA
   At: core/io/marshalls.cpp:98.
ERROR: decode_variant: Condition ' err ' is true. returned: err
   At: core/io/marshalls.cpp:542.
ERROR: _load_settings_binary: Error decoding property: input/pause
   At: core/project_settings.cpp:409.
ERROR: decode_variant: Condition ' len < 4 ' is true. returned: ERR_INVALID_DATA
   At: core/io/marshalls.cpp:93.
ERROR: _load_settings_binary: Error decoding property: g/environment/default_environment 
   At: core/project_settings.cpp:409.
```
With this basic test project: [export-test.zip](https://github.com/godotengine/godot/files/1241232/export-test.zip)

Pressing the custom pause action in exported bin:
```
ERROR: event_is_action: Request for nonexistent InputMap action: pause
   At: core/input_map.cpp:172.
```

**Comment by Sslaxx** [comment]
@reduz - looks like this might need re-opening?

**Comment by vnen** [comment]
Apparently this isn't fixed yet.
