### ISSUE TITLE
Exports from CLI return exit code 0 when failed to build project.

### ISSUE THREAD

**Issue by franciscod** [godotengine/godot#94957]
### Tested versions

- Reproducible in v4.3.rc1.mono.official.e343dbbcc
- Reproducible in v4.3.dev6.mono.official.64520fe67

### System information

Tested on Linux and macOS

### Issue description

Errors when exporting a project should be communicated via the process exit code, so that build systems can pick up the failure instead of continuing.

A workaround is to grep for error strings (either known strings that can false-negative when a new error happens, or broad generic strings that can false-positive with minor errors, from Godot or the project itself).

Related issues:
- https://github.com/godotengine/godot/issues/90646
- https://github.com/godotengine/godot/issues/83449
- https://github.com/godotengine/godot/issues/83042
- https://github.com/godotengine/godot/pull/89234
- https://github.com/godotengine/godot/pull/89229

### Steps to reproduce

Create a new project, add C# script with a syntax error, and export to Linux (any other platform should behave the same way) with:

`$ godot --headless --export-release Linux output`

The exit code (you can check it with `echo $?`) should not be 0 since there was a failure during the export. It is 0.

(see `run_export.sh` on the linked repo or zip below)

### Minimal reproduction project (MRP)

https://github.com/franciscod/godot-exit
[godot-exit.zip](https://github.com/user-attachments/files/16432162/godot-exit.zip)

**Comment by Calinou** [comment]
> A workaround is to grep for error strings (either known strings that can false-negative when a new error happens, or broad generic strings that can false-positive with minor errors, from Godot or the project itself).

The workaround is described here: https://github.com/godotengine/godot/issues/83042#issuecomment-1949445714

**Comment by franciscod** [comment]
Yes. However with that workaround any logged message containing the string `ERROR:` would also consider the Godot build as failed. I've seen other "benign" error messages that maybe shouldn't stop the build process (and not make Godot exit with != 0).

Another workaround (for C# projects) is to do a `dotnet build` or similar, and only call the godot export if that succeeds. This is limited to C# compile errors and might not detect other build errors (such as errors on the gradle phase of an android build).

**Comment by franciscod** [comment]
- Reproducible in v4.3.rc2.mono.official.3978628c6

**Comment by chsoen** [comment]
Already fixed by #89234.

**Comment by akien-mga** [comment]
> Already fixed by [#89234](https://github.com/godotengine/godot/pull/89234).

I tested in 4.4.1.stable and no, the bug is still reproducible with the MRP. It's specific to the export process for C# projects, where a compilation error doesn't seem to actually make the export fail.

**Comment by chsoen** [comment]
> > Already fixed by [#89234](https://github.com/godotengine/godot/pull/89234).
> 
> I tested in 4.4.1.stable and no, the bug is still reproducible with the MRP. It's specific to the export process for C# projects, where a compilation error doesn't seem to actually make the export fail.

My bad, I thought I got a non-zero exit code and then looked into the related issues, turns out I might have ran something in between the build and echo; can confirm it returns a zero exit code on v4.5dev4.

**Comment by brycehutchings** [comment]
I'm also seeing this and trying to ensure our CI pipeline can catch build breaks.  I also observe an exit code of 0 if I put garbage into my export_presets.cfg file which results in an error:
> ERROR: Cannot get keys from nonexistent section "preset.0.options".

Technically the export process completes but I would like to prevent developers from making a change that results in an error since they likely did something wrong.

So I will be looking into routing stderr to a file and failing if there is any content in it as a workaround.

**Comment by gambashM** [comment]
Confirmed the Android form of this bug in **Godot 4.7.2.stable.mono.official.ed1daf0bf** on Windows.

Minimal independent project:

1. A `Godot.NET.Sdk/4.7.2` project targeting `net9.0`, with one `Node` script, builds successfully (`0 warnings, 0 errors`).
2. Change only `GD.Print("valid minimal project");` to `GD.Print(MissingSymbol);`. A separate `dotnet build` then exits 1 with `CS0103`.
3. Run:

```powershell
Godot_v4.7.2-stable_mono_win64_console.exe --verbose --headless --path . --export-debug Android export/broken-signed.apk
```

Observed:

- Godot exits **0**.
- stderr contains `ERROR: Export .NET Project: Failed to build project. Check MSBuild panel for details.` and `WARNING: Project export for preset "Android" completed with warnings.`
- stdout reaches `[ DONE ] export`.
- A fresh 28,361,407-byte APK is written.
- `aapt2 dump badging` exits 0 and reports package `org.godotengine.minimalexportfailure`, min SDK 24, target SDK 36, ARM64.
- `apksigner verify --verbose --print-certs` exits 0; the APK verifies with v2 and v3 signatures.
- The APK has the expected native Android entries (`AndroidManifest.xml`, `classes.dex`, `lib/arm64-v8a/libgodot_android.so`) but **zero managed payload entries**: no `.godot/mono`, project DLL, `.deps.json`, or `.runtimeconfig.json`.

So this can produce an artifact that looks publishable to normal APK structure/signature checks while omitting the failed C# payload.

This appears consistent with `ExportPlugin._ExportBegin()` catching the exception from `_ExportBeginImpl()` and only calling `AddExceptionMessage()`, allowing the native export to continue:

- 4.7.2 catch: https://github.com/godotengine/godot/blob/4.7.2-stable/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L156-L168
- publish failure throw: https://github.com/godotengine/godot/blob/4.7.2-stable/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L285-L290

The same file/blob is still present on current `master` at bfc77b24e5f1ac2a36bb4996d960c4615fc0f045. PR #99254 remains open and currently has merge conflicts, so as of 2026-08-28 there is no merged fix or fixed engine version to record.

The separate headless `export/android/shutdown_adb_on_exit` diagnostic also appeared in this run, but it is unrelated to the successful exit/artifact behavior above.
