### ISSUE TITLE
graphical issues with material_tester demo [MESA, Linux]

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9525]
**Operating system or device - Godot version:**
Arch Linux, Intel HD4000 (Mesa 17.1.4), Godot 3 master

**Issue description:**
I ran into a couple of graphical issues (glitches?) running the new material tester demo.
see the attached screenshot for details.

1. The grid-like artifacts all over the place (especially visible in the lower left part of the image)
I suspect this is either a driver issue or a quality setting of sorts?

2. The cheese example has this strange lighting effect on top, if you zoom in, select the Lobby as a background and move the camera a specific way so the window is behind the cheese.
This doesn't look realistic, since cheese should neither reflect so much light nor let it pass through the material so much.

![cheese](https://user-images.githubusercontent.com/7927471/27898961-9fe9fdf0-6228-11e7-8144-80cbd4c415da.png)

**Comment by Noshyaar** [comment]
I also have this issue.
Antergos x86_64 - Godot 3.0 master branch
(I'm probably using Intel/Mesa. I don't really know how to get hardware/driver info so I'll just spam command output in here. :P)
```
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
...
01:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)
```
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell  (0x41e)
    Version: 17.1.4
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
...
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.1.4
...
OpenGL version string: 3.0 Mesa 17.1.4
...
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.1.4
```

**Comment by akien-mga** [comment]
> (I'm probably using Intel/Mesa. I don't really know how to get hardware/driver info so I'll just spam command output in here. :P)
>
> 00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
01:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev a1)

You're indeed using Intel Haswell, though you do have a NVIDIA discrete GPU (Optimus) which you don't use. Check https://wiki.archlinux.org/index.php/NVIDIA_Optimus if you'd like to learn how to use it.

**Comment by novemberist** [comment]
So I played around with the environment settings a bit and found out that the "grid effect" is caused by SSAO. Turning off SSAO completely or changing the bias settings to a higher value removes or reduces the effect. I suppose AO bias settings shouldn't really be gpu or driver specific?

**Comment by akien-mga** [comment]
> So I played around with the environment settings a bit and found out that the "grid effect" is caused by SSAO. Turning off SSAO completely or changing the bias settings to a higher value removes or reduces the effect. I suppose AO bias settings shouldn't really be gpu or driver specific?

That part might be #8708.

**Comment by novemberist** [comment]
Sounds like it's indeed a matter of the bias setting for the SSAO. However, Juan's default for this demo seemed to have worked for him (and others too) - so I guess this is still a gpu/driver specific issue.

**Comment by Noshyaar** [comment]
So I've enabled secondary GPU and used both simultaneously.
Both have different issues.
Left: Nvidia/Nouveau (DRI_PRIME=1) | Right: Intel/Mesa

![screenshot from 2017-07-06 15-52-33](https://user-images.githubusercontent.com/26753932/27903508-c9171bbe-6263-11e7-8a16-cc31d845ca74.png)
The issue on Nvidia/Nouveau won't happen until the scene is reloaded. The object will flash black then shadow artifacts appear.

The following screenshot is when the scene is not reloaded yet.
![screenshot from 2017-07-06 15-55-34](https://user-images.githubusercontent.com/26753932/27903509-c91a0db0-6263-11e7-9438-0854c9fc6ea9.png)

**Comment by novemberist** [comment]
Have you tried the proprietary Nvidia driver yet? I think Nouveau also uses Mesa for its 3D rendering.

**Comment by Noshyaar** [comment]
Using proprietary driver: Works perfectly. No any of the mentioned artifacts. Demo runs with higher framerate. ( Sorry, RMS :( )

![screenshot from 2017-07-06 16-40-29](https://user-images.githubusercontent.com/26753932/27905477-4617ce32-626a-11e7-9adb-636675c57971.png)

**Comment by reduz** [comment]
For the SSAO issue, I think this is probably MESA's fault, we should probably report it
The cheese issue needs a bugfix, but i don't remember it being that bad, will have to check

**Comment by akien-mga** [comment]
I'll try to ask MESA devs for guidance on how we can debug that/report issues efficiently to them.

**Comment by gamergamesz** [comment]
![screenshot 52](https://user-images.githubusercontent.com/13883739/27916683-786f00cc-6287-11e7-9f70-226a3f847993.png)
![screenshot 49](https://user-images.githubusercontent.com/13883739/27916684-787e52e8-6287-11e7-9176-f664a3de8e36.png)
![screenshot 50](https://user-images.githubusercontent.com/13883739/27916681-785f9a88-6287-11e7-8969-afc3c8828648.png)
![screenshot 51](https://user-images.githubusercontent.com/13883739/27916685-7883b030-6287-11e7-90dd-fb951f0dec93.png)
MSAA disabled
using nvidia and intel (screenshot is of both)
win10  nvidia 960m

**Comment by gamergamesz** [comment]
and those box like shadow appears when i hit the screen margin of viewport

**Comment by akien-mga** [comment]
@gamergamesz Please open a new bug report, it might be a totally different issue (and it likely is, you are running on Windows 10 with the proprietary NVIDIA driver, this issue is about MESA on Linux).

**Comment by gamergamesz** [comment]
ok

**Comment by eon-s** [comment]
On 7c679dd83 with AMD Carrizo (R5) amdgpu, MESA 17.1.2, if I manage to pass the import (sometimes hangs the system, like Unreal when running) it looks really good but has the same cheesy problem as the OP.

![badcheese](https://user-images.githubusercontent.com/10215987/27940671-5b3ead8e-62a2-11e7-8b79-0d650017d5fa.png)

**Comment by eon-s** [comment]
Turning on ¨follow surface¨ ssurf scattering option makes the cheese looks like it should, could it be related?

**Comment by vnen** [comment]
@eon-s the bug with the cheese material is not related to SSAO, but to subsurface scattering (see #9530). This issue is not driver related. The problem with SSAO on MESA is the grid-like artifacts.

**Comment by eon-s** [comment]
@vnen ah, okok, I was confused by the kaleidoscopic cheeses. 

I don't see any SSAO artifact with that configuration then.

**Comment by rredesigns** [comment]
I saw a similar problem trying out Evee engine in the new Blender release. So I assume this is going to be quite a pain to resolve. xD

**Comment by reduz** [comment]
I am still out of Intel HD 4000 to test. Anyone else will have to fix the SSAO problem. The subsurf scattering problem i'm working on it

**Comment by reduz** [comment]
subsurf scatter issue is a duplicate of #9530

**Comment by reduz** [comment]
subsurf scatter issue is fixed, can't test SSAO

**Comment by novemberist** [comment]
Arch Linux, HD4000 with Mesa 17.1.7

This is how the material tester demo looks on my system right now. Godot and the Demo are both on the latest version.  observations:
- SSAO issue still present
- the scene seems much too bright
- there are no buttons to switch to the next material
- performance seems much worse than I remember

![screenshot_20170822_144559](https://user-images.githubusercontent.com/7927471/29566299-a3280d22-8749-11e7-91ba-e5399bb49fd2.png)

**Comment by groud** [comment]
I have the same issue on the same configuration. 
I may investigate a little bit, but I'm not a shader expert.

**Comment by novemberist** [comment]
With a SSAO-Bias setting of about 0.4 (from default 0.01) all of the artifacts are gone. However, there also doesn't seem to be any visible effect os SSAO being enabled

![bias](https://user-images.githubusercontent.com/7927471/29582651-cdac9552-877d-11e7-8b65-aebecb238b84.png)

**Comment by groud** [comment]
If apply the following patch, I've got no artifacts anymore: 
```
-	float randomPatternRotationAngle = float((3 * ssC.x ^ ssC.y + ssC.x * ssC.y) * 10);
+	//float randomPatternRotationAngle = float((3 * ssC.x ^ ssC.y + ssC.x * ssC.y) * 10);
+	float randomPatternRotationAngle = 0.0;
```
need to investigate :)

**Comment by groud** [comment]
@novemberist , could you check with the last master if the issue is still present ?

**Comment by novemberist** [comment]
Already did. It's gone for me :) Good job! :+1:
