### ISSUE TITLE
Full screen Godot projects cannot be captured by the "Print Screen" key.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#953]
This has been found with Godot RC2 on a Win7 64 bit machine with an Ivy Bridge i7 CPU, an ATI HD 7xxx series GPU, and 16 gigs of RAM.

I'm wondering if this is intentional or not, the issue is that when you set your Godot scene to run at full screen, and you take a screenshot of it using the 'print screen' key, it won't actually get a shot of the actual game in play (instead it gets whatever you would get once you exit out).

This occurs in all cases that start up full screen play, windowed mode works in all cases (even in full size).

If this is fixable, that would be great and would help present projects to the community.

Thanks.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch? Is it also Windows-specific?

**Comment by akien-mga** [comment]
I confirm that "Print Screen" works fine on Linux, at least under KDE4 with ksnapshot: it brings me back to the desktop and proposes to save somewhere the fullscreen snapshot that was just taken.

**Comment by Ace-Dragon** [comment]
Just tested a 2.0 alpha build from late October and I can confirm that the issue still exists on Win64 builds.

**Comment by vnen** [comment]
TBH, Print Screen in fullscreen games has always been a lottery in Windows AFAIK. But this actually happens and there must be a way to avoid it.

**Comment by BlenderNPR** [comment]
Video capture confirmed not working in full screen in Windows 10.

**Comment by ChristopherMJohnson** [comment]
I also have an issue with Print Screen not working on windows 10. I also have the newest version 2.1

**Comment by Ace-Dragon** [comment]
Still an issue with Godot 3.0 alpha (recent build in the last week).

No description change is needed.

**Comment by akien-mga** [comment]
Any Windows dev up to investigate what could prevent screen capture in Godot windows?

**Comment by Crazy-P** [comment]
Works fine here. Alt+PrtSc works fine too.

Win10 - 64bit
Godot 3.0.2

**Comment by Calinou** [comment]
> Recording full screen engine via OBS-Studio not working.

As a workaround, you may be able to use a borderless window by enabling the **borderless** property in the Project Settings).

**Comment by RySchmitt** [comment]
I wasn't able to replicate this on windows 7 with either master or 3.0.6. I was able to use obs and the screenshot button.

**Comment by bojidar-bg** [comment]
What is the status on this issue? Can someone confirm on Windows 8/10?

**Comment by Anutrix** [comment]
This is one of the oldest issues tagged bug. It's been over 4.5 years. Can someone  at least confirm now?

**Comment by Calinou** [comment]
@Anutrix This was confirmed in #26327 recently (which is a duplicate of this issue).

**Comment by SailorOnDaTea** [comment]
win10 64bit LTSC
RX560
Ryzen 1800x
Asus B350 MB

Adrenalin 18.12.2

When I watch video in fullscreen and try to take a screenshot. it won't respond.
If I press winkey and bring start menu/taskbar then screenshot works but it is pointless when there is start menu/taskbar on top of video.

Also for games, if I run game first then try to record, sometimes it wont work. But If I record forst and launch game then it works. I can stop and atart in game as well. But it won't work if I dont run it first.

Sometimes I need to launch radeon settings (it is ok even if i just close without clicking anything)

It is as if it needs to awaken before doing anything .

Now will update to Adrenalin 19.6.3 and retry.

**Comment by SailorOnDaTea** [comment]
Ok after installing 19.6.3 and restart
I just opened a new video went fullscreen and pressed hotkey.
It took a snapshot at first
but then it stopped again.
So it worked once.
This is weird.
I use Ctrl+F8 for that.
I would say fullscreen application probably locked some keys but other screenshot programs like MWSnap work just fine with any key combinations.

To be honest if it was just screenshots I wouldn't bother with ReLive but there is not manylight and  decent recording software...

**Comment by Anutrix** [comment]
Just found something. If you defocus and refocus the fullscreen window(press windows key twice), it takes screenshot of the fullscreen window.

**Comment by Anutrix** [comment]
While testing, I made `OS.set_window_fullscreen(!OS.is_window_fullscreen())` execute whenever I press a random key X. After pressing X a few times and leaving the window in fullscreen, Windows+PrintScreen works perfectly.
Another thing: After it starts working, if I press Windows key to defocus, it stops working again.

**Comment by Calinou** [comment]
See also #25427.

**Comment by Anutrix** [comment]
> 
> 
> See also #25427.

That issue wasn't reproducible. Also, if we start the Example Project in that issue in full screen mode, after 2(3 actually because button says full screen off by default) toggles, Windows+PrintScreen works perfectly. Doesn't work if we set fullscreen to false in Project Settings and run the project.

**Comment by Anutrix** [comment]
After hundreds of tests and over 500(lol) screenshots, I have just come to the conclusion that "Window going from fullscreen to non-fullscreen" (`OS.set_window_fullscreen(false)`) effect is necessary at least once for the capture to work.

**Comment by Anutrix** [comment]
The odd thing is toggling fullscreen mode in ready doesn't get the Windows+PrtScreen working but doing it any function works for some reason. Still have no idea why. Does anyone have any idea?

**Comment by Anutrix** [comment]
Is there a way for the game to lose focus and give focus to Windows OS and regain focus? Because this seems to be reason for this issue.

**Comment by aaronfranke** [comment]
This might have been fixed by #37317, I can't reproduce this bug anymore. Needs more testing.

**Comment by UPetit** [comment]
Still the same on my side. I've tried all parameters for the window (On top, fullscreen, borderless) nothing works... It just captures the state of the window before the focus :/

**Comment by Calinou** [comment]
As a workaround, you can implement a script to save a PNG screenshot to a given location: https://github.com/Calinou/escape-space/blob/master/autoload/screenshot.gd

**Comment by Anutrix** [comment]
How did you guys test? Wasn't full screen broken on master?

**Comment by UPetit** [comment]
> As a workaround, you can implement a script to save a PNG screenshot to a given location: https://github.com/Calinou/escape-space/blob/master/autoload/screenshot.gd

Yeah maybe for standard screen capture it could do the trick.
If I need to record a gif of a specific feature in my game, there is no such trick to do that...



> How did you guys test? Wasn't full screen broken on master?
I ran my game, it launched a new fullscreen window of your main scene. Any screenshot taken while focusing the window will only capture you main scene in its state just after the start.
If I need to take a screenshot of a later scene (let's say I have a button to change my scene and I click on it). Any screenshot taken will still capture the first scene in its original state.
If I want to capture the current scene (the second one), I need to unfocus the game window and re-focus it so my screenshot will capture the game window in its current state etc.

It's like the screenshot can capture the screen in its live state...

**Comment by aaronfranke** [comment]
@UPetit Are you testing 3.2 or master? The bug might have been fixed on master.

**Comment by Anutrix** [comment]
@UPetit Did you use master or 3.2?

**Comment by avril-gh** [comment]
Windows 10 x64 , Godot Engine v3.2.2.beta.custom_build.dcfc876d3
tested - when you run game full screen and press PrintScreen the image will be in clipboard

**Comment by Anutrix** [comment]
@aaronfranke I couldn't test this bug on master due to https://github.com/godotengine/godot/issues/37588.

**Comment by KoBeWi** [comment]
Still valid in 9e34ba4

**Comment by RetrocadeMedia** [comment]
I'm on release 3.2.3, the issue persists. I personally get a couple different results:

This image includes weird black lines on the sides, and the whole screenshot has been moved downwards and shrunk. That bottom bar should run from the far left to the far right.
![Screenshot (76)](https://user-images.githubusercontent.com/33967782/94042883-f36efd80-fd80-11ea-9be1-dff0de4de59a.png)

This image has a top bar reminiscent of Windows 7, despite being in fullscreen. You'll notice it also has been shrunk and has the black bars, it doesn't meet up with the window. On my monitor it looked like the final screenshot, but it came out like this.
![Screenshot (89)](https://user-images.githubusercontent.com/33967782/94043539-ef8fab00-fd81-11ea-8416-1c5bdde72671.png)

Here is a final, not messed up image for comparison.
![Screenshot (95)](https://user-images.githubusercontent.com/33967782/94043085-37620280-fd81-11ea-900b-07bb14789dba.png)

As a note, when using dual monitors, using Print Screen seems to work 99% of the time. It's a good start, if a little annoying to have to paste and save every screenshot.

I'm sure the Godot Dev's and contributors are well aware of the issue, but I thought I'd provide some image examples of each screenshot style. So far "shrunk with black bars" seems to happen more often than the Windows 7 bar for me.

**Comment by Calinou** [comment]
@RetrocadeMedia You can use a script to take a screenshot of the project and save it. See [godot-editor-screenshooter](https://github.com/Calinou/godot-editor-screenshooter) for an example.

**Comment by RetrocadeMedia** [comment]
@Calinou I'm not too worried about taking editor screenshots. Thank you for the suggestion though.

**Comment by Calinou** [comment]
@RetrocadeMedia The script in question can be adapted to run inside a project :slightly_smiling_face:

**Comment by 730730** [comment]
Using 3.2.3 stable, issue persists. Tried every single configuration possible, including resizing and repositioning a borderless window instead of fullscreening it, and borderless fullscreen is still indistinguishable from regular fullscreen. Trying to capture with ShareX shows an outdated frame of the game, a common problem in a lot of games that run in non-borderless fullscreen.
For now I'll probably end up implementing an in-game screenshot function as posted above.

**Comment by Calinou** [comment]
@730730 Does it work if you keep the project in windowed mode and use [Borderless Gaming](https://github.com/codeusa/borderless-gaming/releases) to put it in fullscreen?

**Comment by Ace-Dragon** [comment]
Wow, this bug is still around? This is one of the very first reports I ever made for Godot.

I haven't tested with version 4 yet but I do ask, why is it so hard for Godot to support a feature that existed since the dawn of the personal computer?

**Comment by Anutrix** [comment]
1. It's not a feature. It's a bug. If you are talking about ability to take screenshots, Godot supports that.
2. The bug seems be not just in Godot but many other old games hinting it's an issue with the Windows API.
Everyone's been looking for a solution for a while now. I asked in DirectX server once and they too said it's might not be specific to Godot as some of them encountered it long ago but weren't sure how they fixed it.

**Comment by 730730** [comment]
> @730730 Does it work if you keep the project in windowed mode and use [Borderless Gaming](https://github.com/codeusa/borderless-gaming/releases) to put it in fullscreen?
That does work, yeah. Not much of a fix though as you can't just tell players to download some random software to be able to take screenshots. I do use BG myself on games where I have this exact same problem (or a similar problem where the screenshot looks just plain black/white), but I can't expect players to have the same knowledge.
As @Anutrix mentioned, it does seem this is a common problem in Windows games, and I'm assuming that even if there's a fix that could be applied, it hasn't been due to the multiplatform nature of Godot, as I imagine it could end up interfering with implementations in other platforms if the solution consists of a dirty hack.

I do find it misleading though to provide a "borderless" fullscreen option, which gamers have come to know as a solution to this specific problem, and have it provide no different functionality from regular fullscreen. I think a clarification in the docs on how this borderless mode works and what its limitations are in Windows would be helpful in lessening frustration when running into this issue.

**Comment by Calinou** [comment]
Godot actually doesn't support exclusive fullscreen on Windows. It's supposed to use borderless fullscreen at all times: https://github.com/godotengine/godot/pull/41746

**Comment by robbertzzz** [comment]
Can confirm this using 3.3 stable. What's more, I've got a 2D game with 3D objects inside viewports and rendering onto sprites. When I press shift+windows+s (snippet screenshot), all those viewport sprites flip upside down. Things get even more warped when using the normal printscreen key.

**Comment by Anixias** [comment]
Still an issue in 3.3.2 mono stable. Windows + Shift + S displays old render data, not up-to-date unless you focus a different window and then do the hotkey combination.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/60665, as this is the same underlying cause.
