### ISSUE TITLE
Editor window title and some button titles turn black when custom formatted tooltips are shown using Mobile/Forward+ renderer

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#96806]
### Tested versions

4.3.stable

### System information

macOS 14.6.1

### Issue description

When using the Mobile or Forward+ renderers the window title of the macOS editor window, (and unselected tab items to the left of the selected) turn black instead of white when the window loses focus. Interestingly, this also happens when you hover over FileSystem file items and get their tooltip popups (I guess these tooltips are implemented differently than other tooltips, causing the window to lose focus?).

The issue does not happen using the Compatibility renderer, which is also strange. 

Expected appearance (compatibility renderer):
![Screenshot 2024-09-10 at 19 01 30](https://github.com/user-attachments/assets/d2ec79f9-d3db-4a9d-9f75-cf0d08cfb492)

Mobile (same on Forward+):
![Screenshot 2024-09-10 at 19 02 20](https://github.com/user-attachments/assets/3434f35a-200f-40fe-8202-d40c2b5ae082)

Hover tooltip discrepancy. Notice effect when hovering over a file:
https://github.com/user-attachments/assets/ad464126-5de5-4ee8-b1c8-18160cab7bf1

### Steps to reproduce

- Run the Godot editor on macOS with a project using Mobile or Forward+.
- Open the About Godot or Settings window, causing the main window to lose focus.
- Or, try hovering a file in the file system.

### Minimal reproduction project (MRP)

Just editor required.

**Comment by lostminds** [comment]
After a little more investigation it looks like this is related not to window focus loss, but rather showing the more advanced custom formatted hover tool tips that are used for example for files in the File system panel. And as you can see in the Export dialog, it also affects some button titles. However, it's not triggered if the window loses focus as I thought at first, but when these special formatted tooltips are shown.

![Screenshot 2024-09-25 at 12 17 05](https://github.com/user-attachments/assets/2bc73c2a-2d7c-4a77-953d-94210dff32c9)

**Comment by lostminds** [comment]
Seems like this issue has been fixed in 4.4 since I can't reproduce it either after upgrading, so closing this

**Comment by Calinou** [comment]
This is likely related to https://github.com/godotengine/godot/issues/102066 (which is an issue I can still reproduce in 4.4.stable on macOS).

**Comment by lostminds** [comment]
> This is likely related to [#102066](https://github.com/godotengine/godot/issues/102066) (which is an issue I can still reproduce in 4.4.stable on macOS).

Well, they're similar in that in involves things turning black on window focus loss on macOS. However, it's completely different things turning black (Line2d vs UI text labels) and in this case it was in Mobile/Forward+ and not in Compatibility renderer, while in the linked issue it was the other way around. 

One thing it could be related to is if somewhere deep down something is referencing macOS system standard UI colors like [[NSColor labelColor]](https://developer.apple.com/documentation/appkit/nscolor/labelcolor?language=objc) etc. Since these colors are context sensitive based on application light/dark mode, system accessibility options etc, and if this was incorrectly set or changed it could cause these colors to swap based on when they're used to redraw some content after window focus change.
