### ISSUE TITLE
[4.4 dev2] Gizmo in CSGMesh3D is not updated and there is a struggle for depth

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#96969]
### Tested versions

4.3 stable, 4.4 dev2

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

I noticed two problems when using CSGMesh3D

1. AABB does not update (blue border) when resizing with the scale tool in the top bar
![1](https://github.com/user-attachments/assets/82ad7fea-0fd6-4eb6-a294-cf1934c09fe4)

3. When selecting CSGMesh3D, the Gizmo struggles for depth, this is especially noticeable when moving the camera
![2](https://github.com/user-attachments/assets/aef49421-e374-47e5-a8ce-07c426b9125f)

### Steps to reproduce

1. Open MRP
2. Select the biggest cube (BIGBOX)
3. Move the camera, you will notice artifacts on the cube (fight for depth)
4. Reduce the cube, AABB will not update until we select another node

### Minimal reproduction project (MRP)

[vox.zip](https://github.com/user-attachments/files/16996585/vox.zip)

**Comment by Calinou** [comment]
> 2. When selecting CSGMesh3D, the Gizmo struggles for depth, this is especially noticeable when moving the camera

This should be fixed by https://github.com/godotengine/godot/pull/100211.

**Comment by JekSun97** [comment]
> > 2. When selecting CSGMesh3D, the Gizmo struggles for depth, this is especially noticeable when moving the camera
> 
> This should be fixed by [#100211](https://github.com/godotengine/godot/pull/100211).

This does not fix the Gizmo update, but fixes the second issue
