### ISSUE TITLE
The About window is a bit messy

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9736]
In Godot 3.0 master, the About window shouldn't have two nested scrollbars, I find it too much for such a window. Also, it draws a rectangle going out of bounds:

![image](https://user-images.githubusercontent.com/1311555/28437708-f1e21e52-6d9b-11e7-90d2-c9218a321b30.png)

**Comment by capnm** [comment]
... and  the version label is missing the git commit sha:
![version](https://user-images.githubusercontent.com/4047289/28443153-9eef562e-6db4-11e7-9747-2071305f881f.png)

**Comment by Noshyaar** [comment]
Fixed in the PR.
Focus rectangle issue is reported here: #9612
I'm not sure what happened with the upper-right text. It should be as the following screenshot (without hash in the current version):

![image](https://user-images.githubusercontent.com/26753932/28451597-51640760-6e18-11e7-8285-f74ad7fd6395.png)

**Comment by Zylann** [comment]
The rectangle bug is still present:
![image](https://user-images.githubusercontent.com/1311555/28495578-718e02ea-6f51-11e7-84e6-2d9368cb30df.png)

**Comment by Noshyaar** [comment]
Yes, #9612 is still open. Need to fix where the hightlight is drawn.
