### ISSUE TITLE
Imported GLB model distorted when running the game in 4.3

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#97840]
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.5599) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

In Godot 4.3 my imported model is distorted when running the game. I have a model imported as GLB from Blender and added to a 3d scene. I also added a camera. In editor everything looks fine:

![image](https://github.com/user-attachments/assets/ff3b3f55-e493-43f7-bafd-7dfec1ad3cc8)

Also the camera preview looks fine.

![image](https://github.com/user-attachments/assets/561d05eb-7f3a-417d-aa3a-4d849621a180)

But when I run the game, the model is distorted, e.g. the body gets scaled up a lot while the hands and eyes move but retain their scale. 

![image](https://github.com/user-attachments/assets/af85b5f5-4ea8-4b11-b4d9-4e5243138f5f)

This same scene works just fine in Godot 4.2. 

![image](https://github.com/user-attachments/assets/e3fb2ae2-56c9-45aa-8e15-964fbe4193eb)

### Steps to reproduce

Open the MRP in both Godot 4.2 and Godot 4.3, run the `node_3d.tscn` scene to see the  results.

### Minimal reproduction project (MRP)

[bone_problem_reproducer.zip](https://github.com/user-attachments/files/17265753/bone_problem_reproducer.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #93502 as the culprit, @TokageItLab 

![image](https://github.com/user-attachments/assets/efc1cf5a-019b-4174-8f6f-11717efa8c48)

**Comment by TokageItLab** [comment]
Can't reproduce current master, maybe it has been fixed by https://github.com/godotengine/godot/pull/97489.

**Comment by derkork** [comment]
I can still reproduce this in 4.4.dev3. I'll stick with Godot 4.2 for now.

**Comment by matheusmdx** [comment]
I'm also can reproduce this issue in v4.4.dev3.official [f4af8201b] and latest master v4.4.dev.custom_build [4c4e67334], @TokageItLab can you double check from your end?


https://github.com/user-attachments/assets/5f2c3bb1-82de-45a9-905b-0fdc563ec9e3

**Comment by AThousandShips** [comment]
Can confirm on v4.4.dev.custom_build [4c4e67334]

**Comment by TokageItLab** [comment]
Ah I see why I could not reproduce it, it seems that this problem does not occur when `Editable Children` is enabled.

However, I suspect this is separate from the process issue. Because MeshInstance is not assigned a SkeletonPath, and I assume it is because it is a child of BoneAttachment. So I think this is a problem that should be solved by the importer. cc @fire @lyuma 

![image](https://github.com/user-attachments/assets/ef564c21-8977-498d-83ff-40cefc2d3880)
