### ISSUE TITLE
Impossible to use signals defined in gdscripts which extend other gdscripts

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#9816]
**Operating system or device - Godot version:** Arch Linux; Godot v3.0-alpha (custom built)

**Issue description:**
I created an `entity.gd` script with utility functions like `grid_move`. This script is extended by two other scripts, `player.gd` and `projectile.gd`.
`player.gd` defines two signals:
```
signal hit(prev_health, current_health)
signal spawned(health, move_timeout_timer)
```
These signals don't appear in the connections menu, and I can't connect them manually using `connect`. They appear in `get_signal_list`.

**Steps to reproduce:**
1. Create a base script
2. Create a script with a signal that extends the previous script and attach it to a node
3. Try to connect this signal to any other node

**Comment by eon-s** [comment]
I'm unable to reproduce on 45b498c4e, all custom signals appear and have autocompletion.

Can you share a project with non working signals?

**Comment by zatherz** [comment]
Are you sure that the signals are defined in a script that extends another script? I'll upload an example tomorrow.

**Comment by eon-s** [comment]
@zatherz Something like this? 

![signals](https://user-images.githubusercontent.com/10215987/28543842-942e358a-7097-11e7-8fb8-1393af55dc5a.png)

**Comment by zatherz** [comment]
No. You have one script, e.g. `entity.gd`, and then another script attached to a node, e.g. `player.gd`, that does `extends "res://entity.gd"`. Signals defined in `player.gd` don't work.

**Comment by eon-s** [comment]
@zatherz yes, that "sub" extends "base" and can emit signals from "sub" and "base", the other node can connect both, but a sample project may be better, maybe I'm missing another detail.

**Comment by zatherz** [comment]
Okay, I found the actual issue. The signals only appear after you reload the project.
* Make a new project
* Add a `Node`
* Assign it this script:
```
extends "res://base.gd"
signal test
```
* Create a new script called `base.gd` with the contents:
```
extends Node
```
* Save the scene
* Click on the Node connections pane (the `test` signal shouldn't be there)
* Quit to Project Manager
* Open the project again
* Open the scene
* Click on the Node connections pane (the `test` signal should be there)

**Comment by reduz** [comment]
I think i may have fixed this, can you please re-test?

**Comment by reduz** [comment]
I'm confident this was fixed, so closing

**Comment by sketchyfun** [comment]
This should be re-opened as it's still happening on a fairly recent master build I'm using. 

I have:

turret.gd
_which inherits from_
base_enemy.gd
_which inherits from_
damageable.gd

If I add a custom signal to damageable.gd or base_enemy.gd, the signal appears immediately in the inspector, but if I add it to turret.gd it won't appear until I reload the entire project

**Comment by akien-mga** [comment]
As per @vnen's comment, closing again as the original issue is fixed.

The other issue described by @sketchyfun and @vnen should likely go in its own issue, if still relevant.
