### ISSUE TITLE
Glow extremely Slow with Mobile on Android

### ISSUE THREAD

**Issue by Kajinor** [godotengine/godot#98531]
### Tested versions

4.4.dev3, (Probably also 4.3)

### System information

Android 14, Samsung Galaxy A35

### Issue description

With Mobile Renderer enabled, I created an empty scene without a sky or anything, and just put a MeshInstance with a Cube Mesh and a Standard Emissive Material. It renders with smooth 120 FPS on my Galaxy A35. 

Then I enable Glow to actually see some glowing. It works on my PC, but on my phone:

1. The glow is not visible, as if it is turned off somehow.
2. FPS drops from 120 to 37...

Then I switched to Compatibility Renderer:
1. Glow is visible now
2. FPS is back to 120

If I do the same in Unreal Engine, no matter if I use GLES3 or Vulkan renderer there, it is always at 60 FPS and Glow is always working.

So there must be a huge performance issue with turning on Glow/Postprocessing with Mobile Renderer. 

I read an official article that SSGI and other effects are not optimized in Godot yet and will improved with upcoming releases, so hopefully Glow will be part of that upcoming optimizations? 

Anyway, thanks for your hard work on the engine, just wanted to report this and hope it gets fixed soon. (Still kinda hope there is just a setting I did wrong).

### Steps to reproduce

I attached MRP. Basically just make an emissive cube, run on low/mid-range android device with Mobile compared to Compatibility renderer.

### Minimal reproduction project (MRP)

[slowglowmrp.zip](https://github.com/user-attachments/files/17526220/slowglowmrp.zip)

**Comment by Calinou** [comment]
> I read an official article that SSGI and other effects are not optimized in Godot yet and will improved with upcoming releases, so hopefully Glow will be part of that upcoming optimizations

The implementation of glow in Mobile closely follows the one used in Forward+, except it only uses fragment shaders instead of compute (due to poor compute shader support on mobile GPUs).

Compatibility uses a low-end-oriented glow implementation with less options available. It could be ported to Mobile, but this would change the appearance of projects that rely on the current glow implementation (unless we keep two codepaths side-by-side).

**Comment by Kajinor** [comment]
> Try reducing the resolution scale factor in the project settings (Scaling 3D > Scale) to a value between 0.5 and 0.7. Most 3D mobile projects don't render at native resolution for performance reasons.

Hmm I tried that, I set the Scaling 3D to 0.5 and the FPS drops even a bit more! It goes down to 28-30 FPS then....

Also, as I mentioned, the Glow is not even visible on mobile, I don't get any glow effect no matter how much I play with the glow related settings (e.g., setting HDR Threshold below 1.0). On PC, the Glow is working. I use Mobile Renderer on PC as well, so its the same Renderer.

> Compatibility uses a low-end-oriented glow implementation with less options available. It could be ported to Mobile, but this would change the appearance of projects that rely on the current glow implementation (unless we keep two codepaths side-by-side).

I think you should keep two codepaths then if possible. The thing is, in Unreal and Unity I get decent 60 FPS (probably above if I would stop locking the FPS there) with nice looking glow effects even if I choose Vulkan. 

I think glowing is essential for many games. So if Glow makes the game unplayable on a $300 Galaxy A35 mid-range phone, which has just been released in March 2024, then I think an additional code-path is definitely worth it. I mean so far, I only rendererd a Cube without shadows, sky, and other stuff.

The Compatibility Renderer solves this, but it lacks other features like Decals, DOF, etc. which GLES3 Renderer in Godot 3.6 all supports btw.

So the issue on Mobile with Godot 4.0 in a Nutshell is:

- Mobile Renderer is too slow for production use
- Compatibility Renderer lacks too many features

Don't get me wrong, I saw the huge improvements which have been added to Compatibility Renderer with the most recent updates. But I also read that the Compatibility Renderer is now "feature complete" so I don't expect more additions to it.

Right now, Godot 3.6 is actually the much better version if it would have the latest GDScript, GDExtension and Workflow additions like Godot 4.0 has and more frequent updates. Rendering vice, Godot 4.0 only brings less features and poorer performance on Mobile right now and I think that is something which should be changed.

Even on my Apple M1 Macbook Air, Mobile Renderer Glow drags down performance in a way it shouldn't be.

Anyway, I think Godot has great potential on Mobile, please just think about an additional code path OR adding more features to Compatibility Renderer. That would be awesome.

**Comment by Kazox61** [comment]
The performance drops even to 30 fps on a high end mobile device. This is a huge problem for projects targeting mobile devices. I'm not sure what to do now? Should I move to the Compatibility Renderer? @Kajinor what did you do?

**Comment by Calinou** [comment]
I would recommend using Compatibility for now, as its glow implementation is much faster on mobile devices.

**Comment by Kazox61** [comment]
Can I find somewhere what's not not supported on the Compatibility Renderer?

**Comment by Calinou** [comment]
> Can I find somewhere what's not not supported on the Compatibility Renderer?

There's a comparison here: https://docs.godotengine.org/en/latest/tutorials/rendering/renderers.html

**Comment by beicause** [comment]
I can't reproducible it in master branch. Both my PC and Android phone reach 60 fps:
PC: 

![Image](https://github.com/user-attachments/assets/8cc4290a-2ab1-4476-9720-6f375bcd1757)

Android:

![Image](https://github.com/user-attachments/assets/f1210651-bb51-41bf-bbe1-beeb89b74247)

**Comment by Kazox61** [comment]
Maybe it's related to some specific devices. But I definitely could reproduce the problem

**Comment by Kajinor** [comment]
It is still happening to me with latest Godot 4.4 Beta 4. The thing is that the glow is **not even visible** on my Android Phone, its not even working. But on my PC it is visible (Also using Mobile Renderer, same settings). That makes me thinking that the Renderer might run into an error or something and that this error is the reason for the bad fps and not the implementation of the glow effect. 

Or maybe there is just a wrong setting (perhaps a ".mobile" setting), but I already played with almost all the settings and nothing changes. (If I change the Glow Blend Mode from Additive to Replace, I only see a black screen on my Phone. Not sure if that is interesting.)

@beicause Did you apply any changes to the MRP I attached? Changed some settings? Or did it just work for you as it is?

Anyway, whatever it is, would be cool to have a fix or a workaround soon. Thanks

**Comment by Calinou** [comment]
> But on my PC it is visible (Also using Mobile Renderer, same settings)

Is it visible on PC at the same viewport size as the target device? The appearance of glow varies depending on viewport resolution (it's more visible at higher resolutions).

**Comment by beicause** [comment]
I didn't make any changes. The GPU of my android phone is ARM Mali-G76 MP16( It seems to be a high-end GPU, but I've been using it for four years).

**Comment by Kajinor** [comment]
Unfortunately, changing viewport sizes does not change anything about the visibility of the glow. I still always only see a normal white cube. If I make the viewport very small (e.g. 320x240), FPS goes back to 120 but thats expected. I think the glow effect is probably not executed at all for some reason, maybe there is an error not catched by Godot happening on certain GPUs?

The GPU is ARM Mali-G68 MP5 and it should definitely work with this one (Unity/Unreal with Vulkan does too), the phone also just came out in 2024.

**Comment by Kajinor** [comment]
I just wanted to mention that I did some more testing and it seems this issue only happens with the _mobile_ renderer but not with the _forward_plus_ renderer.  While the latter one is actually not intended for mobile devices, it makes the glow work.  Which is strange since both are using Vulkan and probably the same implementation of the glow effect. Maybe that helps somehow to figure out what the bug could be. 

Since it works with _forward_plus_, I assume it is not related to the implementation of the glow effect but more related to how things are handled in the renderer.

**Comment by clayjohn** [comment]
@Kajinor If your game is a 2D game, then this is a known longstanding bug.

**Comment by Kazox61** [comment]
@clayjohn same problem I have for 3d

**Comment by clayjohn** [comment]
> [@clayjohn](https://github.com/clayjohn) same problem I have for 3d

Sorry I wasn't clear. By "this" I meant glow not appearing when using the mobile renderer. 

Are you confirming that glow isn't appearing in 3D when you use the mobile renderer, or are you confirming that glow is slow on your mobile device?

**Comment by Kazox61** [comment]
Sorry, I mean slow on mobile

**Comment by clayjohn** [comment]
> Sorry, I mean slow on mobile

Thank you for clarifying. I have updated my original comment/question to be more clear. Sorry for the confusion

**Comment by Kajinor** [comment]
@clayjohn Its in 3D, there is also an MRP attached showing a (glowing) white cube. The cube is _not glowing_ for me and FPS are down. With _forward_plus_, it works.

As far as I can see, it seems we have 3 different cases now which are all happen with the same MRP:

1. For @Kazox61 , the cube is glowing but performance is bad
2. For @beicause , the cube is glowing and performance is good (Mali-G76 MP16, 4 years old, high-end)
3. For myself , the cube is _not glowing_ and performance is bad (Mali-G68 MP5, ~1 year old, mid-range)

**Comment by Repiteo** [comment]
Partially fixed by #109994

**Comment by clayjohn** [comment]
@Kajinor that PR should fix the issue with glow not appearing for you. 

I'll have a follow-up soon for improving performance

**Comment by Kajinor** [comment]
@clayjohn I can confirm that this fixed the issue for me and the glow is now visible. The performance is still an issue though. I am looking forward to the PR you are working on in this regard, sounds very promising! (But I guess it won't make it into 4.5 anymore)

**Comment by clayjohn** [comment]
@Kajinor that's great to hear! Thank you for confirming. 

The optimization will definitely have to wait until 4.6 since it is too risky for 4.5 at this point. 

I'm confident that it will save at least a few milliseconds for you!
