### ISSUE TITLE
Crash in RasterizerSceneGLES3::_render_geometry [Intel HD 3000, OSX]

### ISSUE THREAD

**Issue by marcelofg55** [godotengine/godot#9938]
**Operating system or device - Godot version:**
Mac OS X 10.11.6
Godot 3.0 latest master
Intel HD Graphics 3000

**Issue description:**
Was trying the latest master with the Window Management demo, it ran once and then started crashing everytime I tried to run it again.
I've attached the crash log and the console output.

[ConsoleOut.txt](https://github.com/godotengine/godot/files/1181946/ConsoleOut.txt)
[Crash.txt](https://github.com/godotengine/godot/files/1181941/Crash.txt)

**Steps to reproduce:**
Run the Window Management demo.

**Link to minimal example project:**
Use the Window Management demo.

**Comment by bruvzg** [comment]
Can't reproduce on macOS 10.12.6 (FirePro D300; https://github.com/godotengine/godot/commit/bb4b98defedf6aeadb94a497568f962981dd3ec7; https://github.com/godotengine/godot-demo-projects/commit/9365e97c0f6cb3dc9c355d6d6e03988a1230b871)

**Comment by akien-mga** [comment]
Likely a drivers issue then. Does Intel HD 3000 support OpenGL 3.3 on macOS?

**Comment by bruvzg** [comment]
@akien-mga Yes HD 3000 support OpenGL 3.3. [OpenGL Capabilities Tables](https://developer.apple.com/opengl/OpenGL-Capabilities-Tables.pdf)

**Comment by marcelofg55** [comment]
I was just re-checking the console output of this, maybe this crash has to do with this error:
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6237.

I've checked and the returned status is 0x8CD6 (GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT), not sure what's the problem though.

**Comment by thoughton** [comment]
I have the exact same issue here, with same gfx hardware, but running old Mac OS 10.9.5. Same assert failing, same line of code, same GL error status returned.

I have also had Godot load just the once. Only difference for me is I'm trying to create a new project rather than load a demo.

I've compiled from latest Master myself, and also tried a "calinou/godot" build from bintray, but both have the same issue.

**Comment by thoughton** [comment]
_(I mistakenly created a new issue, referenced above, for this same problem. I'm therefore closing that duplicate issue and re-posting my findings below.)_

Mac OS X 10.9.5, MacBook Air, Intel HD Graphics 3000 384 MB.

Godot master 277d9d6.

Godot crashes when loading into the editor (eg. after creating a new project in the launcher and selecting it).

No additional steps required.

**I have found that reverting the following commit actually fixes the issue for me:**

90445aa

However I do not fully understand the consequences of reverting this commit, or whether it's truly responsible for the crash, or if it's just essentially disabling a particular code path and the actual problem is elsewhere. Either way, I hope this will at least provide a clue.

I'll post the output and callstack from the crash in a follow-up post.

**Comment by thoughton** [comment]
```
./bin/godot.osx.tools.64
Current path: /godot
Couldn't open /godot/bin/godot.osx.tools.64.pck
Couldn't open godot.osx.tools.64.pck
Couldn't load/find /godot/project.godot or project.binary
Couldn't load/find /project.godot or project.binary
OpenGL ES 3.0 Renderer: Intel HD Graphics 3000 OpenGL Engine
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: gdnative/singletons
SVG_GENERATION TIME: 0.447839
OPENING: /test-277d9d6 (::test-277d9d6)
arguments
0: /godot/bin/godot.osx.tools.64
1: --path
2: /test-277d9d6
3: --editor
Current path: /godot
Couldn't open /godot/bin/godot.osx.tools.64.pck
Couldn't open godot.osx.tools.64.pck
OpenGL ES 3.0 Renderer: Intel HD Graphics 3000 OpenGL Engine
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
WARNING: not found: gdnative/singletons
SVG_GENERATION TIME: 0.424257
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
try to see fs update2
REIMPORT BECAUSE: modified resource time 0 vs 1505498312
import extension tried resource type for res://icon.png and its 
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: set_item_icon: Index p_idx out of size (items.size()).
   At: scene/gui/popup_menu.cpp:637.
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6261.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff87e8a5aa _sigtramp + 26
[2] 2   ???                                 0x0000000110480400 0x0 + 4568122368
[3] GHAL3D::ISAScheduler::CDependenceDAG::AddNodeEdges(GHAL3D::ISAScheduler::CDagNode*, GHAL3D::ISAScheduler::CDagNode*)
[4] GHAL3D::ISAScheduler::CDependenceDAG::Build()
[5] GHAL3D::ISAScheduler::CScheduler::Schedule()
[6] GHAL3D::CGen4CodeGeneratorContext::LocalScheduling(GHAL3D::CShader const*, GHAL3D::SKernelCompilerControls const&)
[7] GHAL3D::CGen6PixelShaderKernelProgram::LocalScheduling()
[8] GHAL3D::CGen6PixelShaderKernelProgram::Build()
[9] GHAL3D::CGen6PixelShaderKernelProgram::Create(void const*, PLATFORM_STR, S3DKernelHardwareCapabilities const&, GHAL3D::CPixelShader const*, GHAL3D::SGen6PixelShaderKernelProgramCacheKey const*, GHAL3D::CGen6PixelShaderKernelProgram*&)
[10] GHAL3D::CGen6PixelShaderKernelProgramCacheData::Initialize()
[11] GHAL3D::CGen6PixelShaderKernelProgramCacheData::Create(GHAL3D::CStateProcessorCache*, GHAL3D::SGen6PixelShaderKernelProgramCacheKey const&, GHAL3D::CGen6PixelShaderKernelProgramCacheData*&)
[12] GHAL3D::CStateCache<GHAL3D::SGen6PixelShaderKernelProgramCacheKey, GHAL3D::CGen6PixelShaderKernelProgramCacheData>::AllocateData(GHAL3D::SGen6PixelShaderKernelProgramCacheKey const&, GHAL3D::HANDLE_TYPE&)
[13] GHAL3D::CGen6StateProcessorCache::GetPixelShaderKernelProgram()
[14] GHAL3D::CGen6PrivateStateProcessor::BindIndirectState()
[15] GHAL3D::CGen6PrivateStateProcessor::BindPipeline()
[16] 16  AppleIntelHD3000GraphicsGLDriver    0x000000011340aef7 glrAppleSyncState + 85
[17] 17  AppleIntelHD3000GraphicsGLDriver    0x000000011370d28e glrRenderVertexArray + 983
[18] 18  GLEngine                            0x00007fff80a272f6 glDrawArrays_GL3Exec + 285
[19] RasterizerSceneGLES3::_render_geometry(RasterizerSceneGLES3::RenderList::Element*) (in godot.osx.tools.64) (rasterizer_scene_gles3.cpp:1492)
[20] RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, unsigned int, bool, bool, bool, bool, bool) (in godot.osx.tools.64) (rasterizer_scene_gles3.cpp:2132)
[21] RasterizerSceneGLES3::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) (in godot.osx.tools.64) (rasterizer_scene_gles3.cpp:4017)
[22] VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, unsigned int, RID, RID, RID, int) (in godot.osx.tools.64) (visual_server_scene.cpp:1646)
[23] VisualServerScene::render_camera(RID, RID, Vector2, RID) (in godot.osx.tools.64) (visual_server_scene.cpp:1300)
[24] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (in godot.osx.tools.64) (visual_server_viewport.cpp:69)
[25] VisualServerViewport::draw_viewports() (in godot.osx.tools.64) (visual_server_viewport.cpp:295)
[26] VisualServerRaster::draw() (in godot.osx.tools.64) (visual_server_raster.cpp:110)
[27] VisualServerWrapMT::draw() (in godot.osx.tools.64) (visual_server_wrap_mt.cpp:126)
[28] Main::iteration() (in godot.osx.tools.64) (main.cpp:1641)
[29] ProgressDialog::task_step(String const&, String const&, int, bool) (in godot.osx.tools.64) (progress_dialog.cpp:204)
[30] EditorNode::progress_task_step(String const&, String const&, int, bool) (in godot.osx.tools.64) (editor_node.cpp:3279)
[31] EditorProgress::step(String const&, int, bool) (in godot.osx.tools.64) (editor_node.h:788)
[32] EditorFileSystem::reimport_files(Vector<String> const&) (in godot.osx.tools.64) (editor_file_system.cpp:1502)
[33] EditorFileSystem::_update_scan_actions() (in godot.osx.tools.64) (editor_file_system.cpp:393)
[34] EditorFileSystem::_notification(int) (in godot.osx.tools.64) (editor_file_system.cpp:1018)
[35] EditorFileSystem::_notificationv(int, bool) (in godot.osx.tools.64) (editor_file_system.h:100)
[36] Object::notification(int, bool) (in godot.osx.tools.64) (object.cpp:851)
[37] SceneTree::_notify_group_pause(StringName const&, int) (in godot.osx.tools.64) (scene_tree.cpp:911)
[38] SceneTree::idle(float) (in godot.osx.tools.64) (scene_tree.cpp:488)
[39] Main::iteration() (in godot.osx.tools.64) (main.cpp:1632)
[40] OS_OSX::run() (in godot.osx.tools.64) (os_osx.mm:1879)
[41] main (in godot.osx.tools.64) (godot_main_osx.mm:90)
[42] 42  libdyld.dylib                       0x00007fff89c555fd start + 1
[43] 43  ???                                 0x0000000000000004 0x0 + 4
-- END OF BACKTRACE --
```

**Comment by thoughton** [comment]
A thought: I wonder whether it's worth renaming this Issue? Because for me it does not seem to be related to the Window Management demo, as it also happens even when creating a brand new project.

**Comment by akien-mga** [comment]
If #11315 can be fixed by reverting 90445aa, I don't get how it could be a duplicate of this #9938 which predates that commit... but it's true that the crash logs are similar, so I guess some more debugging is needed.

**Comment by thoughton** [comment]
Ah sorry, I should've checked the dates... Want me to re-open #11315 and remove my re-posts from this one?

**Comment by akien-mga** [comment]
No, that's what I planned to do initially but since the stacktraces *are* basically identical, it might still be the same bug nowadays. Maybe @marcelofg55's bug was fixed, and then reintroduced with the commit you found.

**Comment by thoughton** [comment]
This is still an issue on recent Master (fb6066).

I'd mentioned previously that reverting https://github.com/godotengine/godot/commit/90445aae67159adafbcbb5a0027d1e793d6ea7ef fixed the issue; but I've narrowed it down a little further to it being just reverting the code change (not the shader) fixes it.

To be more precise, I'm changing the code **from** this:
```
// (Crashes)
bool has_base_alpha = (p_material->shader->spatial.uses_alpha &&
    !p_material->shader->spatial.uses_alpha_scissor) ||
    p_material->shader->spatial.uses_screen_texture; 
```
Back **to** this:
```
// (Works)
bool has_base_alpha = (p_material->shader->spatial.uses_alpha &&
    !p_material->shader->spatial.uses_alpha_scissor) ||
    p_material->shader->spatial.uses_screen_texture ||
    p_material->shader->spatial.unshaded; 
```

I've tried debugging it some more, but I'll be the first to admit that I am not a graphics programmer so I don't really know what I'm doing...

I did a little research and found a StackOverflow discussion here (https://stackoverflow.com/questions/6150441/opengl-es-exc-bad-access-on-gldrawarrays#6152615) that suggested these types of exceptions upon calling `glDrawArrays()` are often caused by _"GL state having an array still bound that shouldn't be"_.

Maybe that's of some use? I don't know.

**Comment by akien-mga** [comment]
Nice debugging @thoughton and sorry for the delay. This line was changed a few days ago in 9cf19f8d, can you still reproduce the bug now?

**Comment by thoughton** [comment]
Hi @akien-mga, thanks for the update. Unfortunately the bug is still present for me with latest master (a60896869e6c17f674ff25bee87cabb54cd4403d).

**Comment by reduz** [comment]
Kicking to 3.2, where will probably be closed given this chipset no longer supports Vulkan and will go via GLES2 backend.

**Comment by qarmin** [comment]
Still is reproducible in master 16d4021
```
[0] RegisterProcTableCallback
[1] RegisterProcTableCallback
[2] RegisterProcTableCallback
[3] RegisterProcTableCallback
[4] RegisterProcTableCallback
[5] RegisterProcTableCallback
[6] RegisterProcTableCallback
[7] RegisterProcTableCallback
[8] RasterizerSceneGLES2::_render_geometry (c:\pr\godot\drivers\gles2\rasterizer_scene_gles2.cpp:1528)
[9] RasterizerSceneGLES2::_render_render_list (c:\pr\godot\drivers\gles2\rasterizer_scene_gles2.cpp:2422)
[10] RasterizerSceneGLES2::render_scene (c:\pr\godot\drivers\gles2\rasterizer_scene_gles2.cpp:2733)
[11] VisualServerScene::_render_scene (c:\pr\godot\servers\visual\visual_server_scene.cpp:2157)
[12] VisualServerScene::render_camera (c:\pr\godot\servers\visual\visual_server_scene.cpp:1726)
[13] VisualServerViewport::_draw_viewport (c:\pr\godot\servers\visual\visual_server_viewport.cpp:70)
[14] VisualServerViewport::draw_viewports (c:\pr\godot\servers\visual\visual_server_viewport.cpp:308)
[15] VisualServerRaster::draw (c:\pr\godot\servers\visual\visual_server_raster.cpp:107)
[16] VisualServerWrapMT::draw (c:\pr\godot\servers\visual\visual_server_wrap_mt.cpp:104)
[17] Main::iteration (c:\pr\godot\main\main.cpp:1886)
[18] OS_Windows::run (c:\pr\godot\platform\windows\os_windows.cpp:2785)
[19] widechar_main (c:\pr\godot\platform\windows\godot_win.cpp:150)
[20] _main (c:\pr\godot\platform\windows\godot_win.cpp:172)
[21] main (c:\pr\godot\platform\windows\godot_win.cpp:184)
[22] __scrt_common_main_seh (d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[23] BaseThreadInitThunk
```

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch / 3.2 beta 2?

**Comment by akien-mga** [comment]
No answer, so I'll assume that it's either fixed (there were many fixes around this code the past 2 months), or if not, that it's unlikely to ever be as the drivers for this chipset are really broken.
